import { withOpeningFeedback } from "./feedback";

export const badOpeningPunishmentDrillsSEOText = `
Bad Opening Punishment Drills is not a normal opening drill built around one fixed repertoire.
It is a pattern drill for players who want to punish wasted tempi, wandering queens, delayed castling, passive setups, and overcommitted piece placement on sight.

The point is not to memorize every bad opening. That is impossible.
The point is to recognize what kind of mistake you are actually facing and use the right punishment for that mistake.
If they are undeveloped, open the center and expose it.
If they are passive and cramped, keep the pawns that are suffocating them until every useful improving move is yours.
If they delay castling, use forcing moves first and make the open files belong to your connected rooks.
If they commit too early in a symmetrical position, ask what option they just ruled out and exploit that commitment immediately.

These drills focus on practical punishment themes: count the bad decisions, trade central pawns when you are readier, pin the key defender before the king hides, keep passive structures cramped, force the issue against uncastled kings, and punish early commitments before the opponent can change plans.
If you want to stop letting ugly openings survive into equal middlegames, this drill is built for that.
`;

export const badOpeningPunishmentDrillsLines = withOpeningFeedback([
  {
    category: "Threshold",
    id: "bad-opening-punishment-01-one-slow-move",
    name: "One slow move is not a refutation",
    description: "This line teaches restraint. One lazy move is not enough to force tactics, so Black should just take space, develop, and accept the easier game.",
    moves: ["e4", "e5", "a3", "Nf6", "Nc3", "d5", "exd5", "Nxd5", "Nf3", "Nxc3", "bxc3", "Bd6", "d4", "O-O", "Bd3", "Re8", "O-O", "Nd7", "Ng5", "Nf6", "Re1", "h6", "Ne4", "Nxe4", "Bxe4", "exd4", "cxd4", "Qh4"],
    explanations: [
      "White starts with pawn to {{square e4}} and claims the center in the usual way.",
      "Let's learn how to punish bad openings! The point of this drill is not to memorize every weird setup your opponent might choose, but to recognize what kind of mistake they actually made and choose the punishment that fits it. This first line teaches restraint, so start with {{square e5}} and take clean central space.",
      "This line is here to teach the first rule: one slow move is not enough. {{square a3}} is a loss of time, but not a tactical blunder yet.",
      "So Black does not hunt ghosts. Black just develops a piece toward the center and takes the easier version of the game.",
      "White develops the {{knight c3 full}} and still has a playable position.",
      "Black strikes with ...{{square d5}} because central pressure is the clean punishment when the opponent gives you time.",
      "White captures and clarifies the center.",
      "Black recaptures with a piece, keeps development flowing, and makes the knight active in one move.",
      "White develops and hopes the early {{square a3}} can be forgotten.",
      "Black trades on {{square c3}} and damages the queenside structure before White finishes organizing.",
      "White recaptures, but the doubled c-pawns are the price of the earlier drift.",
      "Black develops the bishop to a natural square and points toward the kingside.",
      "White rebuilds the center at last.",
      "Black castles and reaches the cleaner version of the position. One slow move did not lose by force, but it still gave Black the easier game.",
      "White finally points a bishop toward the kingside and tries to finish development sensibly.",
      "Black centralizes a rook at once. This is the kind of reward you get from not overforcing earlier. Black now has the cleaner structure, the easier rook placement, and no weaknesses to babysit.",
      "White gets the king safe, which is why this line is not a refutation story. White is worse, not dead.",
      "Black reroutes the knight to improve it without concession. The extra tempo from {{square a3}} has turned into time for Black to reorganize first.",
      "White looks for activity on {{square g5}} because passive defense would leave Black with a free hand.",
      "Black calmly covers the sensitive squares and asks White what the jump really achieved. Good punishment often looks quiet.",
      "White tries to contest the e-file before Black takes it over completely.",
      "Black questions the knight immediately. Once Black has completed development, White's active pieces can be challenged one by one.",
      "White chooses the more central retreat so the knight can still influence the board.",
      "Black is happy to trade here because the damaged queenside structure means simplified positions still favor Black.",
      "White recaptures and keeps the bishop active, trying to prove the structure can still hold.",
      "Now Black opens the center. Notice the timing: not on move three, but only after development and king safety made the trade useful.",
      "White restores a pawn in the center, but the structure is still loose and the c-pawn damage remains.",
      "Black immediately asks concrete questions on the kingside. One slow move was never a forced win, but it gave Black the easier structure, cleaner pieces, and the first real initiative."
    ]
  }
,
  {
    category: "Three poor decisions",
    id: "bad-opening-punishment-02-open-center",
    name: "Three poor decisions means open the center",
    description: "This is the threshold line. After two queen moves and one side pawn move, White has lost enough time that Black should open the center immediately.",
    moves: ["e4", "e5", "Qf3", "Nc6", "a3", "Nf6", "Qd1", "d5", "exd5", "Nxd5", "Nf3", "e4", "Ng1", "Bc5", "d3", "Qf6", "Qe2", "O-O", "dxe4", "Re8", "Nf3", "Bf5", "Bg5", "Qxb2", "Qd1", "Rxe4+"],
    explanations: [
      "White begins with {{square e4}} and takes central space.",
      "Think of the central pawns as curtains on a stage: if your opponent is underdeveloped, you punish them by opening the center and drawing those curtains aside so the difference in development becomes impossible to hide. This line teaches you to count the bad decisions first, then strike, so start with {{square e5}}.",
      "The early {{queen f3 full}} is not the punishment trigger by itself. It is only the first wasted tempo, and the point of the line is to count accurately.",
      "Black develops and covers the center instead of reacting emotionally to the queen.",
      "{{square a3}} is the second poor decision. White is drifting, but Black still should not force matters yet.",
      "Black keeps developing because the rule is proportional punishment, not automatic tactics.",
      "Now the queen goes back to {{square d1}}. That is the third poor decision, and this is the moment the lesson changes.",
      "Black plays ...{{square d5}} immediately because now White is behind enough in development for an open center to become a real punishment.",
      "White accepts the trade and opens more lines.",
      "Black recaptures with the knight, which improves a piece and keeps the center exposed.",
      "White finally develops a knight, but the king is still in the middle and the lost tempi still matter.",
      "Black pushes ...{{square e4}}, gains more time, and keeps White from catching up cleanly.",
      "White has to retreat the knight all the way back. That is exactly what the earlier wasted moves bought.",
      "Black develops the bishop with tempo toward the kingside. White is still uncastled and Black's lead is now obvious.",
      "White finally tries to close the center a little and create room to breathe.",
      "Black keeps the queen active without overextending. The point is to add pressure to {{square f2}} and {{square e5}} while White is still tangled.",
      "White overprotects the center and tries to connect the back rank.",
      "Black castles before White can stabilize. The punishment is working because Black gets king safety and activity at the same time.",
      "White grabs the advanced pawn, hoping material relief will also solve the development problem.",
      "Black replaces the pawn with open-file pressure. Once the center opens, rooks are the natural pieces to bring in.",
      "White develops at last, but only after being forced around by threats.",
      "Black places the bishop on an active square with tempo and keeps White from coordinating cleanly.",
      "White tries to trade an attacking piece and reduce the pressure.",
      "Black grabs the pawn on {{square b2}} because White's queen dance left the queenside unattended. Punishment often spills from the center into side weaknesses.",
      "White has to retreat again. The queen has spent the opening running instead of helping.",
      "Now the open center pays off completely. Black invades with the rook because White never found time to coordinate the pieces."
    ]
  }
,
  {
    category: "Delayed castling",
    id: "bad-opening-punishment-03-trade-queens-while-king-stuck",
    name: "Trade queens when their king is the one stuck",
    description: "This line teaches that once Black is castled and White is not, Black can open the center and even welcome queen trades because the active rook belongs to Black.",
    moves: ["d4", "Nf6", "a3", "g6", "h3", "Bg7", "Nc3", "O-O", "e4", "d6", "Nf3", "e5", "dxe5", "dxe5", "Qxd8+", "Rxd8", "Bg5", "h6", "Bh4", "Nc6", "Bd3", "Be6", "O-O", "g5", "Bg3", "Nh5", "Bh2", "Nf4", "Bxf4", "exf4"],
    explanations: [
      "White starts with {{square d4}} and claims central space.",
      "This line teaches the delayed-castling version of punishment: once your opponent spends time on side moves and leaves the king in the center, the side that castles first gets to welcome open lines and even queen trades later. Start with {{knight f6 full}}.",
      "{{square a3}} is one of the wasted tempi this line is built around. On its own it is only a warning sign.",
      "Black builds a kingside fianchetto and keeps development efficient.",
      "{{square h3}} is another slow move, so now the opening story is about White spending time without getting the king safe.",
      "Black develops the bishop to {{square g7}}, where it supports the later break and reminds us that Black will be ready first.",
      "White develops a piece, but the king is still no closer to safety.",
      "Black castles first. That matters because now Black can afford to open the position sooner.",
      "White grabs more center with {{square e4}}, but central pawns do not erase lost time.",
      "Black supports the center and gets ready to challenge it directly.",
      "White develops, but the king is still in the center after two wasted pawn moves.",
      "Black plays ...{{square e5}} now because the pieces are ready and White's king is still exposed.",
      "White captures to avoid giving Black easy central space.",
      "Black recaptures and clears the d-file. This is exactly the kind of trade that exposes underdevelopment.",
      "White tries to reduce danger by trading queens.",
      "Black welcomes the trade because the rook becomes active on {{square d8}} immediately, while White is still the side that has not castled.",
      "White develops with tempo on the rook and hopes to prove the queen trade reduced Black's pressure.",
      "Black asks the bishop a direct question. With queens off, there is no need to rush. The rook on {{square d8}} already gives Black the easier game.",
      "White preserves the bishop, trying to keep pressure without conceding the bishop pair.",
      "Black finally brings the queenside knight out. This is the payoff of the earlier queen trade: the rook came out for free, so the rest of development is smooth.",
      "White tries to finish development and prepare castling.",
      "Black develops with gain of coordination, covers key central squares, and prepares to use kingside space later.",
      "White does get castled, but notice how long it took and how much Black improved first.",
      "Black grabs space immediately. Once White's king is finally safe, Black can still use the lead in activity to ask new questions.",
      "White retreats again. White is still the side reacting.",
      "Black continues the chase and aims for {{square f4}}. The lesson is that the queen trade did not end the attack. It converted the lead into an easier middlegame.",
      "White keeps the bishop pair but loses another tempo.",
      "The knight lands on a real outpost because White's earlier drift gave Black time to organize.",
      "White decides to give up the bishop pair rather than allow the knight to sit forever.",
      "Black recaptures toward the center and keeps the more useful pawn structure. The center is now open on Black's terms, not White's."
    ]
  }
,
  {
    category: "Cheap mate tries",
    id: "bad-opening-punishment-04-queen-attack-collapse",
    name: "Cheap mate try collapses after ...d5",
    description: "This line teaches how to punish fake attack setups. White spends time on the queen and a side pawn, so Black waits, counts, and only then hits the center.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Qh5", "g6", "Qf3", "Nf6", "a3", "d5", "exd5", "Nd4", "Qd1", "Bg4", "f3", "Bf5", "d3", "Nxd5", "Ne2", "Bc5", "Nxd4", "Qh4+", "Kf1", "Bxd4", "Qe1+", "Qxe1+", "Kxe1", "O-O-O"],
    explanations: [
      "White starts with {{square e4}} and opens the usual king pawn game.",
      "This line teaches how to punish fake attacks without panicking. When the opponent throws the queen forward too early, do not lash out on move two; finish your job, count the wasted moves, and only then hit the center. Start with {{square e5}}.",
      "The bishop comes to {{square c4}}, eyeing {{square f7}}. That alone is normal, so this line is not about punishing the bishop move itself.",
      "Black develops and covers the center.",
      "{{queen h5 full}} is the classic cheap mating try. The lesson here is to stay calm and ask whether White is really developed enough to justify this attack.",
      "...{{square g6}} is calm and direct. Black is not refuting anything yet, just forcing the queen to spend another move.",
      "White slides the queen to {{square f3}} instead of fixing development. That is two queen moves already.",
      "Black develops another piece and keeps {{square d5}} ready.",
      "Now {{square a3}} appears. That is the third poor decision, and now Black deserves more than equal development.",
      "Black hits with ...{{square d5}} at once. The center must be opened before White gets time to castle or regroup.",
      "White takes, but that only increases the activity of Black's pieces.",
      "The knight jump to {{square d4}} comes with tempo and creates immediate threats against the queen and {{square c2}}.",
      "White has to run the queen back again. The whole attack has turned into self-inflicted time loss.",
      "Black develops with tempo again and attacks the queen one more time. The punishment is no longer theoretical. White is being forced to react every move.",
      "White tries to kick the bishop and finally build some shelter around the king.",
      "Black retreats with purpose, keeps the bishop active, and preserves pressure on {{square c2}} and {{square d3}}.",
      "White tries to solidify the center, but every defensive move now comes a tempo late.",
      "Black cashes in one of the central pawns only after the tactical pressure forced White into passivity.",
      "White develops, but it is defensive development, not attacking development.",
      "Black points another piece toward the kingside and keeps the queen-side options alive. The point is to make every move threaten something.",
      "White eliminates the advanced knight because leaving it there would be too dangerous.",
      "Black immediately replaces the knight's pressure with a check. This is how fake attacks get punished: White ends up being the side whose king gets hunted.",
      "White loses castling rights. That is the real collapse, not just the earlier queen moves.",
      "Black takes the bishop with tempo and keeps White's king exposed in the center. The attack outlived the first tactic because Black's pieces were better placed all along.",
      "White tries to force queens off and reduce the heat.",
      "Black is happy to trade because the uncastled king and broken coordination remain.",
      "White recaptures, but the king has been dragged into the middle.",
      "Black castles long and reaches a position where the pieces are coordinated, the king is safe, and White's opening shortcuts have turned into a bad end of the middlegame."
    ]
  }
,
  {
    category: "Key defender",
    id: "bad-opening-punishment-05-pin-before-castle",
    name: "Pin the defender before the king hides",
    description: "This line teaches the next step after opening the center: if White still wants to castle kingside, pin the key defender and attack the place the king is heading.",
    moves: ["e4", "e5", "Qf3", "Nc6", "a3", "Nf6", "Qd1", "d5", "exd5", "Nxd5", "Nf3", "Bg4", "Be2", "Qd7", "O-O", "O-O-O", "d3", "f6", "Nc3", "g5", "Nxd5", "Qxd5", "Be3", "h5", "Nd2", "Bxe2", "Qxe2", "g4"],
    explanations: [
      "White opens with {{square e4}}.",
      "This line teaches the follow-up after you have earned the attack: do not throw pieces at the king at random, pin the defender that will protect the castled position and attack the side they are heading toward. Start with {{square e5}}.",
      "{{queen f3 full}} is one wasted tempo, but this line is not teaching a cheap shot against the queen by itself.",
      "Black develops and refuses to drift.",
      "{{square a3}} is another non-essential tempo, so the count is rising again.",
      "Black develops again because the idea is to earn the attack first.",
      "White sends the queen back to {{square d1}}, and now the wasted time is undeniable.",
      "Black opens the center with ...{{square d5}} because this is the right moment to expose the difference in development.",
      "White trades pawns, trying to simplify.",
      "Black recaptures with activity and keeps the more useful pieces.",
      "White develops and hopes to castle out of trouble.",
      "Black plays B{{square g4}} first. Do not rush random tactics. Pin the {{knight f3 full}}, because that knight is the key defender of the kingside.",
      "White blocks the pin path, but the position is still passive and the king has only one natural home left.",
      "Black brings the queen to {{square d7}} and connects the rooks. The attack is being aimed at the place White is about to choose.",
      "White castles kingside because there is no easy queenside setup available.",
      "Black castles long. This is the practical lesson: attack where the king is going, not where it is.",
      "White tries to hold the center together and claim a little breathing room.",
      "Black supports the {{square e5}} point and prepares to attack without loosening the center.",
      "White develops, but the kingside is still the place where the game will be decided.",
      "Black expands immediately because the pinned defender and opposite-side castling make space-gaining moves especially strong.",
      "White grabs the knight to reduce Black's attacking resources.",
      "Black recaptures with the queen and keeps all the attacking lanes open.",
      "White tries to cover dark squares and make the kingside harder to crack.",
      "Black keeps rolling pawns because White has not solved the real issue: the kingside defenders are tied down and the attack is aimed right at them.",
      "White brings another defender over. That is already a win for Black's plan because White's pieces are being pulled backward.",
      "Black exchanges off a defender at exactly the moment the position wants fewer white defenders, not more.",
      "White recaptures, but the queen now has to defend instead of create counterplay.",
      "Black tears open more dark squares. This is the conversion of the pin-before-castle lesson: once the right defender is neutralized, the pawn storm becomes much harder to meet."
    ]
  }
,
{
    category: "Passive play",
    id: "bad-opening-punishment-06-a3-e3-shell",
    name: "Do not free the cramped setup too early",
    description: "This is the opposite lesson from the open-center lines. White is passive and cramped, so the pawns are White's problem and Black should not trade them off too soon.",
    moves: ["e3", "d5", "d4", "Nf6", "Bd3", "c5", "c3", "Nc6", "Nf3", "Bg4", "O-O", "e6", "Nbd2", "Bd6", "h3", "Bh5", "b3", "O-O", "Bb2", "Qe7", "Re1", "Rfd8", "a3", "Rac8"],
    explanations: [
      "White begins with {{square e3}}, and this line is here to teach passive-play punishment, not underdevelopment punishment.",
      "This line teaches the opposite lesson from the open-center punishments. When the opponent is passive and cramped, their pawns are part of their problem, so you should not rush to trade them off and free them. Start by claiming space with {{square d5}}.",
      "White builds a shell with pawns and pieces behind it. The key idea is that these pawns are part of White's problem, not something Black should rush to trade away.",
      "Black develops and keeps the center under control.",
      "White points the bishop toward the kingside, but the setup is still fairly passive and short on space.",
      "Black challenges the center with ...{{square c5}} while keeping the structure intact. The goal is to cramp White first, not free White.",
      "White supports the center, but those pawns also start to crowd White's own pieces.",
      "Black develops another piece and keeps all the useful breaks available.",
      "White develops the king knight, still without asking Black a difficult question.",
      "Black pins the knight and keeps improving instead of rushing to release the center.",
      "White castles, but the position is still cramped and short on active counterplay.",
      "Black supports the center and keeps the dark-squared bishop healthy behind the chain.",
      "White develops again, but there is still no meaningful pressure on Black's position.",
      "Black develops the bishop to an active square and gets closer to full coordination.",
      "White spends another move on {{square h3}}, but that still does not solve the space problem.",
      "Black simply preserves the bishop and keeps the pressure. There is no reason to help White by clarifying too early.",
      "White adds {{square b3}}, another slow move in an already cramped structure.",
      "Black castles and removes tactical noise. This is the patient part of the punishment.",
      "White develops the bishop at last, but Black's position is already easier to play.",
      "Black places the queen on {{square e7}}, where it supports the center and the rooks.",
      "White centralizes a rook, but the position is still more useful for Black because Black has more space and cleaner piece routes.",
      "Black brings a rook to the open file and keeps stacking small improvements that White cannot really match.",
      "White plays {{square a3}}, another move that does not change the real problem.",
      "Black completes the other rook development with ...R{{square c8}}. Now every black piece is doing something useful, and only now does opening the position start to make sense."
    ]
  }
,
{
    category: "Passive play",
    id: "bad-opening-punishment-07-open-only-after-maxing-out",
    name: "Only open once every useful move is yours",
    description: "This line is the conversion stage of the passive-play lesson. Black improves everything first, then opens only when the resulting position will help Black more than White.",
    moves: ["e3", "d5", "d4", "Nf6", "Bd3", "c5", "c3", "Nc6", "Nf3", "Bg4", "O-O", "e6", "Nbd2", "Bd6", "h3", "Bh5", "b3", "O-O", "Bb2", "Qe7", "Re1", "Rfd8", "a3", "Rac8", "c4", "cxd4", "exd4", "Bf4"],
    explanations: [
      "White starts with the same passive shell and gives Black the same kind of position to work with.",
      "This line is the conversion stage of the passive-play lesson. You are not trying to win instantly here; you are trying to improve every piece until only your side still has useful moves, and only then do you open the position. Start with {{square d5}}.",
      "White builds a queen pawn structure, but it is the cramped version of one. That is why this line does not rush to open the board.",
      "Black develops and keeps control over the key dark squares.",
      "White develops the bishop, but still without real central ambition.",
      "Black challenges the center immediately and makes White commit.",
      "White supports the center, but also locks more pieces behind pawns.",
      "Black develops and keeps the position flexible.",
      "White develops normally, but nothing here asks Black to solve a hard problem.",
      "Black pins and keeps improving. The point is not to win instantly. The point is to make every black move count more.",
      "White castles and hopes the game will stay quiet.",
      "Black supports the center and keeps the structure intact.",
      "White brings out another piece, but the setup is still short on useful activity.",
      "Black develops the bishop and keeps building.",
      "White plays {{square h3}}, which looks tidy but still does not challenge the center.",
      "Black preserves the bishop and refuses to give White easy simplification.",
      "White adds {{square b3}}, another move spent on shape rather than pressure.",
      "Black castles and keeps the position fully under control.",
      "White develops the bishop, but Black is the side with the easier plans now.",
      "Black centralizes the queen and connects the whole setup.",
      "White places a rook on the e-file, but Black still has the more useful improvements.",
      "Black takes over the d-file and prepares to open on Black's terms, not White's.",
      "White plays {{square a3}}, still drifting.",
      "Black finishes rook development. This is the important threshold. Now the position is maximized.",
      "White finally challenges in the center, but this comes after Black already claimed every useful square and file.",
      "Black captures now, not earlier. That is the whole lesson. Before this, the pawns were helping to cramp White.",
      "White recaptures and hopes the position is opening in time to free the pieces.",
      "Black's bishop jumps to {{square f4}} with immediate activity. Once the position opens after full preparation, the side with the better center and better coordination gets the real benefit."
    ]
  }
,
{
    category: "Forcing moves",
    id: "bad-opening-punishment-08-force-before-they-castle",
    name: "Use the forcing move before they can stabilize",
    description: "This line teaches the delayed-castling rule: do not telegraph the attack with a rook move first. Play the loud move now and keep White reacting.",
    moves: ["c4", "e5", "Nc3", "Nf6", "g3", "c6", "d4", "exd4", "Qxd4", "d5", "cxd5", "cxd5", "Nf3", "Nc6", "Qa4", "d4", "Nb5", "Bb4+", "Bd2", "Bxd2+", "Nxd2", "O-O", "Nf3", "d3", "Rd1", "Qb6", "Rxd3", "Bf5"],
    explanations: [
      "White opens with {{square c4}} and heads for a flexible English setup.",
      "This line teaches the sharp delayed-castling rule: if the opponent is still uncastled, do not telegraph the attack with a slow rook move first, play the forcing move when the moment comes and keep them reacting. Start by taking central space with {{square e5}}.",
      "White develops naturally.",
      "Black develops and keeps pressure on the center.",
      "White prepares the kingside fianchetto, but the important story in this line is that White is going to stay uncastled too long.",
      "Black supports the center and prepares a solid structure behind the pawn breaks.",
      "White takes more space in the center.",
      "Black captures and forces White's queen out earlier than White wants.",
      "White recaptures, but the queen is now a visible target.",
      "Black hits the center immediately instead of letting White consolidate.",
      "White clarifies the structure.",
      "Black restores the pawn and keeps a healthy central chain.",
      "White develops, but the king is still in the middle.",
      "Black develops and keeps queen pressure in reserve.",
      "White steps the queen aside, but it is another tempo spent on the queen.",
      "Black gains space with ...{{square d4}} and makes White deal with the center before castling.",
      "White looks for activity, but this does not solve the king problem.",
      "Black checks first and forces another concession.",
      "White blocks with the bishop.",
      "Black removes that bishop and strips away another defender.",
      "White recaptures, but another piece has been dragged away from its best square.",
      "Black castles first. That is the key precondition for the next forcing play.",
      "White returns the knight, but the king is still not safe.",
      "This is the lesson. Do not announce the attack with a slow rook move. Play the forcing move now and keep White reacting.",
      "White tries to pin the pawn and stop it from becoming a spear in the center.",
      "Black calmly unpins the pawn, attacks new weaknesses, and keeps the king boxed in indirectly.",
      "White removes the advanced pawn, but this costs more time and opens more lines.",
      "Black develops with tempo and keeps the initiative. White still has not castled, so Black's forcing sequence already did its job."
    ]
  }
,
{
    category: "Forcing moves",
    id: "bad-opening-punishment-09-connected-rooks-own-the-file",
    name: "When your rooks are connected, the file is yours",
    description: "This line teaches the second half of the delayed-castling lesson: once the forcing move has created an open file, the side with connected rooks owns it.",
    moves: ["c4", "e5", "Nc3", "Nf6", "g3", "c6", "d4", "exd4", "Qxd4", "d5", "cxd5", "cxd5", "Nf3", "Nc6", "Qa4", "d4", "Nb5", "Bb4+", "Bd2", "Bxd2+", "Nxd2", "O-O", "Nf3", "d3", "Rd1", "Qb6", "Rxd3", "Bf5", "Rd1", "Rad8", "Nd6", "Nb4", "Nxf5", "Qa5", "Rxd8", "Rxd8"],
    explanations: [
      "White chooses {{square c4}} and aims for a flexible start.",
      "This line teaches the conversion after the forcing move lands: once your rooks are connected and your opponent's are not, any open file belongs to you, and that is how delayed castling gets punished for real. Start with {{square e5}}.",
      "White develops the knight.",
      "Black develops and keeps White honest in the center.",
      "White prepares to fianchetto, but again the real lesson is that White's king is going to remain in the middle while Black gets coordinated first.",
      "Black reinforces the center and keeps the structure ready for direct play.",
      "White grabs more space.",
      "Black captures and forces the queen into the open.",
      "White recaptures, but that queen move is the first hint of lost time.",
      "Black challenges the center immediately.",
      "White exchanges.",
      "Black restores the structure and keeps a real central pawn.",
      "White develops, but the king is still not close to safety.",
      "Black develops and keeps the queen side active.",
      "White spends another tempo on the queen.",
      "Black pushes ...{{square d4}} and forces White to solve concrete problems first.",
      "White jumps the knight forward.",
      "Black checks and gains another useful move.",
      "White blocks with the bishop.",
      "Black trades it off and removes a defender.",
      "White recaptures, but the pieces are no longer coordinated.",
      "Black castles and is now ready to open files with no fear.",
      "White improves the knight, but the king is still stuck.",
      "Black drives the pawn forward and keeps the position loud.",
      "White pins the pawn and tries to contain the center.",
      "Black unpins with {{queen b6 full}} and points at multiple weaknesses at once.",
      "White takes the pawn to reduce the pressure.",
      "Black develops with tempo and keeps White from stabilizing.",
      "White retreats the rook and hopes the worst is over.",
      "This is the next lesson. Black's rooks are connected and White's are not, so any open file belongs to Black.",
      "White moves the same knight again, looking active but falling further behind in coordination.",
      "Black jumps to {{square b4}} and spots the critical entry points at {{square c2}} and {{square d3}}.",
      "White grabs the bishop, but material matters less than the attack and the trapped king here.",
      "Black plays {{queen a5 full}} and creates multiple threats at once. The queen, knight, and rooks are now working together.",
      "White tries to reduce pressure by trading on the file.",
      "Black replaces the rook with the other rook immediately. That is the whole imbalance. Black can keep ownership of the file and White cannot."
    ]
  }
,
  {
    category: "Second mover",
    id: "bad-opening-punishment-10-exploit-the-option-they-ruled-out",
    name: "Exploit the option their move just ruled out",
    description: "This line teaches the second-mover idea. White's move to Nf3 rules out Ne2, and Black should immediately ask how to exploit that missing option.",
    moves: ["e4", "e6", "d4", "d5", "exd5", "exd5", "Nf3", "Bd6", "Bd3", "Ne7", "O-O", "O-O", "Bg5", "f6", "Bh4", "Bf5", "Bg3", "Bxg3", "hxg3", "Qd7", "Re1", "Nbc6", "Nbd2", "Rae8", "Bb5", "a6", "Bxc6", "Nxc6", "Nf1", "Rxe1", "Qxe1", "Re8"],
    explanations: [
      "White opens with {{square e4}} and heads into the Exchange French.",
      "This line teaches the second-mover idea. White moved first, but every move also closes another door, and your job as Black is to ask which option just disappeared and how to exploit that commitment. Start with {{square e6}}.",
      "White takes central space.",
      "Black challenges it directly.",
      "White exchanges and makes the structure look symmetrical.",
      "Black recaptures and accepts the balanced pawn structure.",
      "White develops the knight to {{square f3}}, and this is the exact commitment the line is built around: White has ruled out {{square e2}}.",
      "Black puts the bishop on {{square d6}} first and asks what White's move has committed to.",
      "White mirrors with the bishop, which is natural but no longer fully flexible.",
      "Black reroutes the knight to {{square e7}}. This is the asymmetry. Because White chose {{square f3}}, only Black gets this clean bishop trade plan.",
      "White castles and keeps the position normal on the surface.",
      "Black castles too and has already matched development cleanly.",
      "White tries to use the bishop actively.",
      "Black hits it with ...{{square f6}} and reminds White that the bishop does not own these squares for free.",
      "White keeps the bishop, but the retreat costs control.",
      "Black's bishop reaches {{square f5}}, where it is no longer the bad bishop at all.",
      "White can meet the bishop, but this is still Black's trade to enjoy.",
      "Black gladly swaps the light squared bishop for White's good bishop.",
      "White recaptures, but Black has solved the problem piece and kept the easier middlegame.",
      "Black calmly centralizes the queen and prepares to coordinate the rooks. After solving the bishop problem, Black gets to think in long-term plans instead of repairs.",
      "White fights for the e-file because that is one of the few ways to keep the position from drifting fully into Black's hands.",
      "Black develops the knight to a natural square now that the {{square e7}} square is no longer needed. This is the second-mover reward: White committed first, Black chose the cleaner setup later.",
      "White finally finishes queenside development, but Black has already dictated which trades are favorable.",
      "Black doubles the rooks around the e-file and shows the full point of the bishop exchange. The bad bishop is gone, the good bishop remains, and the heavy pieces get the active file.",
      "White tries to provoke a concession and disrupt the rook coordination.",
      "Black asks the bishop to decide immediately. White's active move becomes another target.",
      "White gives up the bishop to avoid losing time retreating.",
      "Black recaptures toward the center and improves the knight. Black's pieces keep gaining useful squares from White's earlier commitments.",
      "White reroutes the knight and tries to hold the light squares together.",
      "Black finally uses the e-file. Once the pieces are coordinated, the active file becomes a real asset, not just a pretty idea.",
      "White has to give the queen the job of recapturing because the coordination is already strained.",
      "Black replaces the rook with the other rook immediately. The lesson keeps repeating: when your structure is healthier and your pieces are more harmonious, trades do not kill the advantage, they clarify it."
    ]
  }
,
{
    category: "Second mover",
    id: "bad-opening-punishment-11-early-bishop-becomes-a-target",
    name: "If they commit the bishop early, make it prove itself",
    description: "This is the other second-mover lesson. If White commits the bishop to d3 early, Black should ask how to make that bishop become a target.",
    moves: ["e4", "e6", "d4", "d5", "exd5", "exd5", "Bd3", "c5", "Nf3", "Nc6", "O-O", "c4", "Re1+", "Be7", "Bf1", "Nf6", "b3", "b5", "a4", "b4", "bxc4", "dxc4"],
    explanations: [
      "White opens with {{square e4}} and prepares the Exchange French.",
      "This line teaches the other second-mover punishment: if White commits a bishop too early, do not just mirror development, make that bishop prove it belongs there and turn it into a target. Start with {{square e6}}.",
      "White takes more central space.",
      "Black challenges it in standard French fashion.",
      "White exchanges and keeps the structure symmetrical for a moment.",
      "Black recaptures and keeps a central pawn ready to become the only real center left.",
      "White develops the bishop early, and that is the commitment this line wants to punish.",
      "Black plays ...{{square c5}} immediately and asks the bishop on {{square d3}} to prove it belongs there before White finishes development.",
      "White develops and ignores the warning.",
      "Black adds support. The threat of ...{{square c4}} is getting stronger.",
      "White castles, but still leaves the bishop standing in front of the coming pawn.",
      "This is the punishment. Black gains space with tempo because White committed the bishop too early.",
      "White tries to create activity before retreating.",
      "Black blocks calmly and keeps the structure healthy.",
      "The bishop is forced backward. Black has already won both space and time.",
      "Black develops into the improved structure.",
      "White tries to undermine the pawn chain.",
      "Black supports the advanced pawn and keeps the queenside cramp in place.",
      "White keeps challenging the chain.",
      "Black keeps driving forward. The space edge came from White's earlier commitment.",
      "White finally trades to reduce the bind.",
      "Black recaptures with the d-pawn and keeps the only true central pawn left. Now Black has the easier attacking role and White has the position to defend."
    ]
  }

]);
