import { withOpeningFeedback } from "./feedback";

export const bishopsOpeningLines = withOpeningFeedback([
  {
    category: "Urusov Gambit",
    id: "bishops-opening-center-fork-recovery",
    name: "Center strike and queen recovery",
    description: "Punish ...Nxe4 by opening the center, forcing tactical concessions, and winning the pawn back cleanly.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    explanations: [
      "Let's learn the Bishop's Opening! Start with pawn to {{square e4}} and get ready to develop fast with the bishop coming to {{square c4}}.",
      "Black copies the central claim and keeps a classical structure.",
      "Develop the bishop to {{square c4}} so it points at {{square f7}} and supports central tactics.",
      "Black develops naturally and attacks {{square e4}} right away.",
      "Strike in the center before Black is fully coordinated. This is the core tactical idea.",
      "Black grabs a pawn, but the knight steps into danger while the center is still loose.",
      "Open the e-file and remove Black's e-pawn so your bishop and queen get more scope.",
      "Black develops with tempo and tries to keep pressure on {{square f2}} and the center.",
      "The queen hits {{square e4}} and {{square f7}} at once, forcing Black to solve concrete problems instead of just enjoying the extra pawn.",
      "Black chooses a tactical check, hoping king exposure will justify the pawn grab.",
      "Step to {{square f1}} and keep the king relatively safe. The important point is that the queen still has access to {{square e4}}.",
      "Black castles to finish development, but the tactical dust has not settled.",
      "Recover the {{knight e4 full}} and end the sequence with material restored and Black's activity not worth much."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-rook-net-on-g7",
    name: "Rook net with Re1 and Qxg7",
    description: "A forcing line where Black's knight adventure and king safety problems let White attack the rook and dark squares.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nxe4", "Qxd4", "Nd6", "O-O", "Nxc4", "Re1+", "Be7", "Qxg7", "Rf8", "Bh6"],
    explanations: [
      "Claim space and keep flexible attacking options.",
      "Black meets the center in standard fashion.",
      "Develop toward {{square f7}}, the usual soft spot in open games.",
      "Black attacks {{square e4}} and invites sharp play.",
      "Challenge the center immediately so Black has to answer concrete threats.",
      "Black accepts the challenge and opens the position.",
      "Develop with tempo in mind. White wants quick piece activity, not slow pawn grabbing.",
      "Black takes again, but now the {{knight e4 full}} can become a tactical target.",
      "Centralize the queen, hit {{square g7}} ideas later, and recover the pawn at once.",
      "Black retreats the knight to hold things together and cover key squares.",
      "Castle first. In these lines king safety and rook activation matter more than snatching material instantly.",
      "Black wins the bishop pair temporarily, but the {{knight c4 full}} can become irrelevant if the king gets hit.",
      "Use the open e-file immediately. The check forces Black into a passive defensive move.",
      "Black blocks, but the {{bishop e7 full}} now interferes with rook coordination.",
      "Grab {{square g7}} because the rook and king are awkwardly placed and the pawn was poisoned.",
      "Black tries to save the back rank and hold the rook together.",
      "Develop with threat. B{{square h6}} clamps dark squares and makes the {{rook f8 full}} very hard to untangle."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-accept-sac-and-regroup",
    name: "Accept the knight sac and collect both pawns",
    description: "Black overreaches on f2 and White calmly regroups, taking back material while keeping the extra center pawns.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Bc5", "e5", "Ng4", "h3", "Nxf2", "Kxf2", "d3+", "Kf1", "dxc2", "Qxc2"],
    explanations: [
      "Occupy the center and open lines.",
      "Black mirrors the center and keeps the game open.",
      "Aim at {{square f7}} and prepare rapid development.",
      "Black develops with pressure on {{square e4}}.",
      "Challenge the center before Black gets comfortable.",
      "Black takes and opens the d-file.",
      "Develop and prepare to recapture or push with tempo.",
      "Black chooses active development instead of greed on {{square e4}}.",
      "Drive the knight and gain space. This also closes the bishop's route back to {{square e7}}.",
      "The knight jumps forward, eyeing tactical shots.",
      "Ask the knight where it belongs and stop easy jumps to {{square g4}} or {{square f4}} later.",
      "Black sacs on {{square f2}} hoping king exposure will be enough compensation.",
      "Accept it. White should not fear this when the follow-up is under control.",
      "Black keeps trying to justify the sacrifice by pushing a dangerous passed pawn.",
      "Step back to safety and make sure the queen can deal with the pawn chain.",
      "Black reaches {{square c2}}, but the pawn has run far ahead of the rest of the army.",
      "Simply remove the advanced pawn. White ends the sequence up material with Black's attack gone."
    ]
  },
  {
    category: "Philidor style traps",
    id: "bishops-opening-philidor-queen-win",
    name: "Philidor trap with Ne5 and Qxd8",
    description: "Against a slow ...d6 and ...h6 setup, White opens lines and uses a bishop sac plus central knight jump to win the queen.",
    moves: ["e4", "e5", "Bc4", "d6", "Nf3", "h6", "d4", "exd4", "c3", "dxc3", "Bxf7+", "Kxf7", "Ne5+", "dxe5", "Qxd8"],
    explanations: [
      "Take the center and free the pieces.",
      "Black chooses a more restrained setup.",
      "Develop actively and target {{square f7}} before Black is fully ready.",
      "Black supports {{square e5}} but blocks the dark bishop for now.",
      "Develop and prepare {{square d4}}.",
      "This is slow. Black spends a tempo on luft instead of development.",
      "Open the center while Black is behind in development.",
      "Black accepts and hopes the extra pawn matters.",
      "Offer another pawn to rip lines open and distract Black from king safety.",
      "Black accepts again, but now the queenside pawn grab has badly loosened coordination.",
      "Sac on {{square f7}} to drag the king out and remove the defender of {{square e6}} and {{square d5}} ideas.",
      "Black has to take or remain materially down with the king still under fire.",
      "Jump into the center with check. The knight attacks key dark squares and the queen route to {{square d8}} becomes real.",
      "Black removes the knight, but that opens the d-file and abandons the queen.",
      "Take the queen. The whole tactic works because Black spent too many tempi on pawns and too few on development."
    ]
  },
  {
    category: "Philidor style traps",
    id: "bishops-opening-philidor-mate-on-f7",
    name: "Philidor mate on f7",
    description: "A mating pattern where the king is dragged out, the queen lands on h5, and the weakened diagonal finishes the game.",
    moves: ["e4", "e5", "Bc4", "d6", "Nf3", "h6", "d4", "exd4", "c3", "dxc3", "Bxf7+", "Kxf7", "Ne5+", "Ke8", "Qh5+", "Ke7", "Qf7#"],
    explanations: [
      "Claim the center and keep maximum flexibility.",
      "Black meets the center but stays a bit cramped.",
      "Develop with direct pressure on {{square f7}}.",
      "Black supports {{square e5}} but still lags in development.",
      "Develop and prepare the central break.",
      "Again Black wastes a useful tempo instead of contesting the initiative.",
      "Open lines while Black's king is still in the middle.",
      "Black grabs the pawn and allows tactical play.",
      "Use {{square c3}} to accelerate development and open diagonals.",
      "Black accepts greedily and keeps opening files near the king.",
      "The bishop sac is the trigger that exposes the king and removes the {{square f7}} shield.",
      "Black takes, but the king is now far too loose.",
      "Check from the center. The knight jump takes away key escape squares.",
      "Black declines to take the knight and runs back, hoping to survive.",
      "Bring the queen in with tempo. {{square h5}} is the clean attacking square in this structure.",
      "The king steps to {{square e7}}, but that walks straight into the mating net.",
      "Mate. The queen covers {{square e7}} and {{square f8}}, the bishop controls the diagonal, and Black's undeveloped pieces cannot help."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-free-queen-line",
    name: "Free queen after Bxd5 and Bxf7+",
    description: "A tactical punishment where Black's central expansion leaves the queen loose on d8.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "d5", "Bxd5", "Nc5", "Bxf7+", "Ke7", "Bg5+", "Kxf7", "Bxd8"],
    explanations: [
      "Take space and open lines.",
      "Black mirrors the center.",
      "Develop actively and eye {{square f7}}.",
      "Black pressures {{square e4}} and invites tactical play.",
      "Challenge the center before Black finishes development.",
      "Black grabs the pawn and assumes the knight is safe.",
      "Open the center and ask Black to prove the {{knight e4 full}} belongs there.",
      "Black supports the knight and attacks your bishop, but this also loosens the diagonal toward {{square d8}}.",
      "Capture on {{square d5}} with tempo and centralize the bishop where it attacks {{square f7}} and {{square b7}}.",
      "Black retreats, but the king and queen remain tied to the center.",
      "Remove the key defender and drag the king out. This is the tactical point of the line.",
      "Black steps forward because castling is impossible and the king needs a square.",
      "Pin the queen line and keep forcing moves only. No time to let Black stabilize.",
      "Black takes the bishop, but that walks the king onto the diagonal you wanted.",
      "Take the {{queen d8 full}}. The sequence works because Black's king and queen never had time to coordinate."
    ]
  },
  {
    category: "Center play",
    id: "bishops-opening-d5-space-edge",
    name: "Space gain versus early ...Nc6",
    description: "A practical line where White gains space with d5 and emerges with smoother development.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nc6", "d5", "Nd4", "c3", "b5", "Bd3", "Bc5", "cxd4", "Bxd4", "Nf3"],
    explanations: [
      "Claim the center and open your pieces.",
      "Black mirrors the setup.",
      "Develop with pressure on the weak {{square f7}} point.",
      "Black develops and controls the center.",
      "Challenge the middle before Black settles.",
      "Black defends {{square e5}} and keeps options.",
      "Gain space and kick the knight away. This is the direct positional answer.",
      "The knight jumps to an active square but can still be questioned.",
      "Support the center and prepare to ask that knight what it is doing on {{square d4}}.",
      "Black expands on the queenside to gain space and keep the bishop active.",
      "Retreat to a useful diagonal. The bishop still eyes {{square h7}} and supports future castling.",
      "Black develops naturally, but the center remains unstable.",
      "Remove the advanced knight and simplify toward a healthier structure.",
      "Black recaptures, but the {{bishop d4 full}} can later be challenged by development.",
      "Develop with tempo against the bishop and get ready to castle. White's position is easier to handle."
    ]
  },
  {
    category: "Endgame grabs",
    id: "bishops-opening-knight-takes-h8",
    name: "Endgame rook grab on h8",
    description: "An early queen trade leaves Black's rook loose on h8, and White's knight exploits it even at the cost of getting trapped.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "d6", "dxe5", "dxe5", "Qxd8+", "Kxd8", "Nf3", "Nc6", "Ng5", "Be6", "Bxe6", "fxe6", "Nf7+", "Ke7", "Nxh8"],
    explanations: [
      "Occupy the center and free both bishops.",
      "Black mirrors and keeps options open.",
      "Develop toward {{square f7}} and invite open-game tactics.",
      "Black develops and watches {{square e4}}.",
      "Challenge the center immediately.",
      "Black chooses a Philidor-style structure, solid but somewhat passive.",
      "Clarify the center and force Black to recapture in a way that opens lines.",
      "Black accepts and leaves the d-file vulnerable.",
      "Trade queens while Black is stuck in the center. This shifts the battle toward piece activity and king placement.",
      "Black's king is forced to {{square d8}} and loses castling rights.",
      "Develop and prepare to target the awkward king and rooks.",
      "Black gets a piece out, but the {{rook h8 full}} still lacks support.",
      "Jump aggressively. The knight attacks {{square e6}} and {{square f7}} themes and exploits Black's awkward king.",
      "Black blocks and tries to finish development.",
      "Trade off the key defender so the {{square f7}} jump becomes stronger.",
      "Black's pawn structure is damaged and the king remains awkward.",
      "Check first. This forces the king again and clears the route to {{square h8}}.",
      "The king steps to {{square e7}}, but the rook is now hanging.",
      "Take the rook. The knight may get trapped later, but winning exchange material is the whole point of the line."
    ]
  },
  {
    category: "Boden-Kieseritzky style",
    id: "bishops-opening-qg4-versus-qf6",
    name: "Qg4 pressure against ...Bc5",
    description: "A sharp bishop's opening line where White uses Qg4 and Nd5 to attack f7 and force Black into defense.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Bc5", "Qg4", "Qf6", "Nd5", "Qxf2+", "Kd1", "d6", "Qxg7", "Be6", "Nxc7+", "Kd7", "Nxe6", "Nge7", "Nh3"],
    explanations: [
      "Take the center and keep open-game options.",
      "Black mirrors and stays classical.",
      "Develop with immediate pressure on {{square f7}}.",
      "Black protects {{square e5}} and develops.",
      "Develop the queenside knight and keep {{square d5}} under control.",
      "Black copies your bishop placement and also hits {{square f2}} ideas.",
      "The queen heads to {{square g4}} to pressure {{square g7}} and {{square f7}} at once. This is a very concrete setup.",
      "Black defends {{square f7}} and contests the g-file tactics.",
      "Jump into {{square d5}} where the knight attacks {{square c7}}, {{square e7}}, and {{square f6}} while exploiting the queen's placement.",
      "Black takes on {{square f2}} with check, going for counterplay instead of passive defense.",
      "Step to {{square d1}}. The king is exposed for the moment, but White's attack still has the initiative.",
      "Black tries to consolidate and free the {{square c8}} bishop.",
      "Grab the {{pawn g7 full}} because Black's rook and king are still poorly coordinated.",
      "Black develops and covers key squares, but the {{square c7}} fork remains a problem.",
      "Take on {{square c7}} with check and pull Black's king further from harmony.",
      "The king moves to {{square d7}} where it remains vulnerable.",
      "Collect the {{bishop e6 full}} and convert the tactics into material.",
      "Black finally develops another piece and tries to trap the queen side activity.",
      "Retreat the knight to {{square h3}}, keeping it safe and preparing to regroup after the tactical phase."
    ]
  },
  {
    category: "Bishop's Opening mainlines",
    id: "bishops-opening-bishop-trade-queen-side-castle",
    name: "Bishop trade into queenside castling",
    description: "A tactical line where both sides grab material, but White's king gets safe first and the queenside knight wins material.",
    moves: ["e4", "e5", "Bc4", "Bc5", "d4", "Bxd4", "Nf3", "Nc6", "Nxd4", "Nxd4", "Be3", "Nc6", "Qg4", "Qf6", "Nc3", "d5", "Qg3", "dxc4", "Nd5", "Qg6", "Nxc7+", "Kd8", "Nxa8", "Qxg3", "O-O-O+", "Bd7", "fxg3"],
    explanations: [
      "Take the center and free your pieces.",
      "Black mirrors and keeps the game open.",
      "Develop with pressure on {{square f7}}.",
      "Black develops symmetrically and eyes the center.",
      "Open the center before Black finishes coordination.",
      "Black takes, choosing active piece play over pawn structure.",
      "Develop with tempo against the bishop and prepare to recover the pawn.",
      "Black supports the bishop and improves control of {{square d4}}.",
      "Trade in the center to simplify the tactical tension.",
      "Black recaptures and centralizes the knight.",
      "Develop while hitting {{square d4}} and preparing queenside castling ideas.",
      "Black retreats to a stable square and keeps piece activity.",
      "The queen becomes active on the kingside, pressuring {{square g7}} and the center.",
      "Black defends carefully and keeps an eye on {{square g6}} and {{square f2}} themes.",
      "Develop the knight and increase pressure on {{square d5}} and {{square b5}} squares.",
      "Black strikes in the center to question your setup immediately.",
      "Keep the queen active while avoiding exchanges that help Black.",
      "Black wins a pawn, but this opens more lines and leaves the king uncastled.",
      "Jump into {{square d5}} with tempo and threaten {{square c7}} and {{square e7}} motifs.",
      "Black offers a queen trade route and tries to survive the tactics.",
      "Fork with check. This is the key tactical payoff.",
      "The king is forced to {{square d8}} and stays exposed.",
      "Take the {{rook a8 full}} and convert the attack into material.",
      "Black trades queens to reduce danger, but it does not solve the development problem.",
      "Castle long with check, getting your king safe while keeping the initiative.",
      "Black interposes to stop the check and finish development.",
      "Recapture on {{square g3}} and end with a stable extra-material position and active rooks."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-bxf7-queen-check-recovery",
    name: "Bxf7 check and queen recovery",
    description: "A direct tactical line where Bxf7 and Qd5 win back the pawn while exposing the king.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Nc6", "Bxf7+", "Kxf7", "Qd5+", "Ke8", "Qxe4"],
    explanations: [
      "Take central space and free the bishop and queen.",
      "Black copies the center.",
      "Develop with pressure on {{square f7}}.",
      "Black attacks {{square e4}} and invites tactics.",
      "Challenge the center before Black can settle.",
      "Black grabs the pawn, but the knight and king become tactical targets.",
      "Open the center and expose the downside of the knight excursion.",
      "Black develops another defender, trying to make the extra pawn stick.",
      "Sac on {{square f7}} to drag the king out and disrupt coordination.",
      "Black accepts, but the king is now misplaced.",
      "Check from {{square d5}}, attacking {{square e4}} at the same time and keeping complete control of the play.",
      "Black steps back, but the {{knight e4 full}} is still loose.",
      "Recover the knight and finish the sequence with material equalized and Black's king still awkward."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-classical-pressure-with-bd3",
    name: "Classical pressure after Qh4",
    description: "White recovers the pawn, develops fast, and aims everything at the kingside after Black's knight retreat.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nxe4", "Qxd4", "Nf6", "Nc3", "Nc6", "Qh4", "Be7", "Bg5", "O-O", "O-O-O", "d6", "Bd3"],
    explanations: [
      "Claim space and open lines.",
      "Black mirrors the center.",
      "Develop toward the weak {{square f7}} square.",
      "Black attacks {{square e4}} and encourages an open position.",
      "Hit the center immediately.",
      "Black accepts and opens the d-file.",
      "Develop and prepare to recover the pawn with activity.",
      "Black takes on {{square e4}}, but that invites queen centralization.",
      "Recover the pawn and centralize the queen in one move.",
      "Black retreats the knight, admitting the {{square e4}} outpost was temporary.",
      "Develop another piece and increase central control.",
      "Black matches development and covers {{square e5}} and {{square d4}}.",
      "Place the {{queen h4 full}} because this is the natural attacking square in these Keidansky structures. {{square h7}} and h-file ideas now become concrete.",
      "Black develops but also blocks coordination between rook and bishop.",
      "Pin the knight and keep adding force to the kingside. If Black drifts here, the attack tends to build by itself.",
      "Black castles, but White's pieces are already pointing that way.",
      "Castle long so both rooks can join the attack. This is the practical reason White centralizes the queen so early.",
      "Black tries to complete development and blunt the center.",
      "B{{square d3}} is the dream square from these transcript ideas: bishop to {{square d3}}, {{queen h4 full}}, then direct pressure before Black can untangle."
    ]
  },
  {
    category: "Early queen trade",
    id: "bishops-opening-d5-queen-trade-structure-edge",
    name: "Queen trade and damaged structure",
    description: "An early ...d5 and ...dxc4 sequence leads to queen trade, doubled f-pawns, and a clean structural edge for White.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "d5", "dxe5", "dxc4", "Qxd8+", "Kxd8", "exf6", "gxf6", "Nc3"],
    explanations: [
      "Occupy the center and keep open-game options.",
      "Black mirrors and stays classical.",
      "Develop with direct pressure on {{square f7}}.",
      "Black develops and adds pressure to {{square e4}}.",
      "Challenge the center right away.",
      "Black counters in the center instead of allowing a free initiative.",
      "Clarify the center and open the d-file so tactical ideas become possible.",
      "Black takes the bishop's pawn, but this leaves the queen vulnerable to trade.",
      "Force the queens off while Black is still uncastled.",
      "Black's king must recapture and loses castling rights immediately.",
      "Pick up the {{knight f6 full}} and make Black's pawn structure pay the price.",
      "Black recaptures, but the kingside pawns are now doubled and weak.",
      "Develop simply. In the resulting position White's easier development and Black's damaged structure are the real story."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bgfive-d6-structure-damage",
    name: "Bg5 and structural damage",
    description: "A calmer setup where White uses Bg5 and Nd5 to provoke doubled kingside pawns.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "d6", "Nd5", "h6", "Bxf6", "gxf6", "Ne2"],
    explanations: [
      "Take the center and keep the game open.",
      "Black mirrors and keeps equal central space.",
      "Develop the bishop actively toward {{square f7}}.",
      "Black develops and controls {{square d4}} and {{square e5}}.",
      "Develop the knight and support central jumps like {{square d5}}.",
      "Black develops naturally and prepares to castle.",
      "Choose a quieter setup that keeps the center stable and supports future kingside play.",
      "Black develops the bishop to an active square.",
      "Pin the knight while Black's bishop sits on {{square c5}}. That makes the pin more annoying because there is no easy ...B{{square e7}} neutralizer.",
      "Black supports {{square e5}} and frees the {{square c8}} bishop.",
      "Jump into {{square d5}} and make the pin concrete. If you trade on {{square f6}} later, Black's kingside structure pays for it.",
      "Black questions the bishop but also creates a hook on the kingside.",
      "Take on {{square f6}} to damage the pawn structure. This is the positional point of the line.",
      "Black recaptures and accepts long-term weakness around the king.",
      "Develop calmly. White keeps the healthier structure and flexible plans."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bh4-h5-space-gain",
    name: "Bh4 retreat and h-pawn clamp",
    description: "A slow bishop's opening plan where White tempts pawn advances and then fixes Black's kingside weaknesses with h5.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "h6", "Bh4", "g5", "Bg3", "d6", "h4", "g4", "h5"],
    explanations: [
      "Take the center and open lines.",
      "Black mirrors the center.",
      "Develop with pressure on the sensitive kingside.",
      "Black develops and fights for the center.",
      "Develop and keep {{square d5}} ideas available.",
      "Black adds another defender and prepares to castle.",
      "Stay flexible and keep the position closed enough for maneuvering.",
      "Black develops actively.",
      "Pin the knight and invite a decision about kingside structure.",
      "Black questions the bishop immediately.",
      "Retreat while keeping the bishop active on the diagonal.",
      "Black gains space, but every pawn move on the kingside weakens dark squares.",
      "Retreat again to a useful square and keep pressure on {{square e5}}.",
      "Black shores up the center, but the kingside remains loose.",
      "Start fixing the pawn chain. {{square h4}} is not random, it is aimed at creating lasting targets.",
      "Black advances again, which gains space but locks the pawns onto vulnerable squares.",
      "Fix the weakness with {{square h5}}. White now has clear long-term targets on {{square g4}} and the dark squares."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bb4-simple-development",
    name: "Simple development versus ...Bb4",
    description: "Nothing tactical here. White just develops cleanly and reaches a playable position without concessions.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bb4", "Ne2", "O-O", "O-O"],
    explanations: [
      "Take space and keep the center flexible.",
      "Black mirrors and stays classical.",
      "Develop actively toward {{square f7}}.",
      "Black supports the center and develops.",
      "Develop the knight and keep options for {{square f4}} or Ng{{square e2}} ideas.",
      "Black develops naturally.",
      "Choose a controlled setup that supports later central expansion.",
      "Black pins the knight and increases piece activity.",
      "Break the pin on your own terms and keep the c-pawn flexible.",
      "Black castles and completes king safety.",
      "Castle as well. White has finished development cleanly and can now play a normal middlegame."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-nd5-trade-into-ne2",
    name: "Nd5 trade against castled Black",
    description: "A useful improving line where White jumps into d5, trades the active bishop pair, and keeps a stable setup.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "O-O", "Nd5", "Be7", "Nxe7+", "Qxe7", "Ne2"],
    explanations: [
      "Take central space and open the diagonals.",
      "Black mirrors and keeps classical central control.",
      "Develop with pressure on {{square f7}}.",
      "Black supports {{square e5}} and develops.",
      "Develop the knight and support central jumps.",
      "Black develops naturally and prepares to castle.",
      "Stay flexible and keep the structure sound.",
      "Black puts the bishop on an active attacking diagonal.",
      "Pin the knight and make Black decide whether to tolerate the pressure.",
      "Black castles, so now king safety is settled and the battle becomes positional.",
      "Use the {{square d5}} outpost. The knight is hard to challenge because your {{square e4}} and {{square c3}} resources support it indirectly.",
      "Black steps back to reduce tactical issues.",
      "Trade the bishop pair that was helping defend the kingside.",
      "Black recaptures with the queen and gives up some queen activity for structural simplicity.",
      "Regroup the knight to a flexible square where it can support {{square f4}}, {{square g3}}, or {{square c3}} plans later."
    ]
  },
  {
    category: "Mainline development",
    id: "bishops-opening-open-center-bb5-line",
    name: "Open center and castle",
    description: "A more balanced line where White plays for space with e5, exchanges in the center, and heads into a normal game.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nc6", "e5", "d5", "Bb5", "Ne4", "Nxd4", "Bd7", "Bxc6", "bxc6", "O-O"],
    explanations: [
      "Take the center and begin classical development.",
      "Black mirrors the center.",
      "Develop with pressure on {{square f7}}.",
      "Black attacks {{square e4}} and develops.",
      "Challenge the center while Black is still sorting out piece placement.",
      "Black accepts and opens the game.",
      "Develop and prepare to recover the pawn with activity.",
      "Black supports the center and develops another piece.",
      "Gain space and ask the {{knight f6 full}} to make a decision.",
      "Black hits back in the center and seeks equality by force.",
      "Pin the knight and keep pressure on {{square c6}} and {{square e8}}-related tactics.",
      "Black centralizes the knight aggressively.",
      "Trade off Black's best centralized piece and simplify.",
      "Black develops while preparing to recapture on {{square c6}} if needed.",
      "Give up the bishop pair to damage the queenside structure and remove a defender.",
      "Black recaptures and is left with doubled c-pawns.",
      "Castle and finish development. The opening phase is over and White has a normal playable edge based on structure."
    ]
  },
  {
    category: "Direct attack",
    id: "bishops-opening-greco-style-queen-hunt",
    name: "Direct attack after Bxf7+ and Qh5+",
    description: "A forcing attacking line against ...Bc5 and ...exd4 where White drags the king out and wins heavy material with checks.",
    moves: ["e4", "e5", "Bc4", "Bc5", "d4", "exd4", "Bxf7+", "Kxf7", "Qh5+", "g6", "Qxc5", "Nc6", "Nf3", "d6", "Qd5+", "Be6", "Ng5+", "Ke7", "Qxe6+"],
    explanations: [
      "Take the center and free the pieces.",
      "Black mirrors in classical style.",
      "Develop with pressure on {{square f7}}.",
      "Black develops symmetrically and also eyes {{square f2}}.",
      "Open the center before Black is fully coordinated.",
      "Black takes and allows tactical play around the king.",
      "Sac on {{square f7}} to force the king out. This is the critical attacking idea.",
      "Black accepts and loses the right to castle.",
      "Bring the queen out with check immediately. In sacrificial lines, tempo is everything.",
      "Black blocks the check, but the dark squares stay weak.",
      "Take the {{bishop c5 full}} and convert the sacrifice into concrete material while keeping the initiative.",
      "Black develops and tries to cover central entry squares.",
      "Develop another attacker and prepare to bring the rook or knight into the attack.",
      "Black tries to hide behind development, but the king is still exposed.",
      "Another check, forcing Black to keep reacting instead of coordinating.",
      "Black blocks, but that piece becomes a tactical target too.",
      "Jump with check and attack the pinned or overloaded pieces around the king.",
      "Black's king flees, but the position is still collapsing.",
      "Take on {{square e6}} with check and keep the attack going with a winning material plus initiative balance."
    ]
  },
  {
    category: "Berlin Defense",
    id: "bishops-opening-berlin-d3-re1-pressure",
    name: "Berlin d3 setup with Re1 pressure",
    description: "A solid Bishop's Opening answer to ...Nf6 where White castles early, kicks the pin, and makes the e5-pawn the center of the game.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d3", "d5", "Nf3", "Nc6", "O-O", "Bg4", "h3", "Bh5", "Re1"],
    explanations: [
      "Take the center and keep the bishop active on the long diagonal.",
      "Black develops aggressively and attacks {{square e4}} at once.",
      "Develop outside the pawn chain and keep pressure on {{square f7}} in the background.",
      "The Berlin setup challenges {{square e4}} immediately and invites a choice.",
      "Support {{square e4}} instead of entering the sharpest gambit lines right away.",
      "Black grabs central space, but the {{pawn e5 full}} can become hard to hold.",
      "Develop and start asking how Black plans to defend {{square e5}}.",
      "Black adds support, but this also commits the queenside knight early.",
      "Castle first. King safety matters because the next phase is direct pressure on {{square e5}}.",
      "Black uses the standard pin to slow your kingside play.",
      "Kick the bishop and ask whether it really belongs on the {{square h5}}-{{square d1}} diagonal.",
      "The bishop retreats, but the pin is less convincing once the knight is free to move later.",
      "Put the {{rook e1 full}} and make {{square e5}} the center of the position. This is the practical point of the whole setup."
    ]
  },
  {
    category: "Vienna Hybrid",
    id: "bishops-opening-spielmann-ng5-counter",
    name: "Spielmann counter with Ng5 and Qf3",
    description: "White delays Nf3 until the f-pawn is out, then answers ...Ng4 with a faster attack and an immediate mate threat on f7.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Bc5", "d3", "d6", "f4", "Nf6", "Nf3", "Ng4", "Ng5", "Nf2", "Qf3"],
    explanations: [
      "Take the center and keep open attacking options.",
      "Black mirrors and keeps the game in open channels.",
      "Develop the bishop first and keep pressure on {{square f7}} from move two.",
      "Black protects {{square e5}} and develops naturally.",
      "Choose the queenside knight first so the f-pawn can advance before the kingside knight commits.",
      "Black develops the bishop actively and also eyes {{square f2}} ideas.",
      "Stay flexible and keep the option of a kingside pawn storm.",
      "Black supports {{square e5}}, but this also signals a slower setup White can attack.",
      "This is the core Spielmann-style idea from the transcript: use {{square f4}} to claim space and prepare direct kingside play.",
      "Black develops the knight and now starts eyeing jumps like ...N{{square g4}}.",
      "Only now develop the knight. White has kept the aggressive pawn structure without blocking it.",
      "Black jumps in, hoping pressure on {{square f2}} will be faster than White's attack on {{square f7}}.",
      "Counterattack immediately. The point is simple: your threat on {{square f7}} is stronger than Black's threat on {{square f2}}.",
      "Black grabs material and attacks rook and queen, but that actually helps White bring the queen into the attack.",
      "Q{{square f3}} creates the direct threat of Qx{{square f7}}# and shows why this setup is dangerous in practice."
    ]
  },
  {
    category: "Vienna Hybrid",
    id: "bishops-opening-spielmann-f5-qh5",
    name: "Immediate ...Ng4 met by f5 and Qh5",
    description: "If Black jumps to g4 before White has Nf3 in, White cuts off the bishop, threatens to win the knight, and creates an immediate mate threat with Qh5.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Bc5", "d3", "Nf6", "f4", "Ng4", "f5", "Nf2", "Qh5"],
    explanations: [
      "Take central space and keep the opening flexible.",
      "Black mirrors and keeps classical central control.",
      "Develop the bishop actively toward {{square f7}}.",
      "Black develops and protects {{square e5}}.",
      "Again White keeps the kingside knight back so the f-pawn can move first.",
      "Black develops the bishop and keeps both kingside and central ideas alive.",
      "Stay flexible and prepare aggressive pawn play.",
      "Black develops the knight and makes ...N{{square g4}} available.",
      "Push {{square f4}} before N{{square f3}}. That is the whole move-order point of this hybrid.",
      "Black jumps at the first chance, trying to create threats on {{square f2}} before White is ready.",
      "{{square f5}} is the key counter from the transcript. It cuts off the {{square c7}}-{{square h2}} bishop from helping and makes Qx{{square g4}} a real idea.",
      "Black still goes after {{square f2}}, hoping the fork threat will be enough.",
      "Q{{square h5}} answers everything with a direct mate threat on {{square f7}}. Black is the one who has to solve problems now."
    ]
  }
]);
