export const bishopsOpeningLines = [
  {
    category: "Urusov Gambit",
    id: "bishops-opening-center-fork-recovery",
    name: "Center strike and queen recovery",
    description: "Punish ...Nxe4 by opening the center, forcing tactical concessions, and winning the pawn back cleanly.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    explanations: [
      "Take central space and open lines for the queen and bishop.",
      "Black copies the central claim and keeps a classical structure.",
      "Develop the bishop to c4 so it points at f7 and supports central tactics.",
      "Black develops naturally and attacks e4 right away.",
      "Strike in the center before Black is fully coordinated. This is the core tactical idea.",
      "Black grabs a pawn, but the knight steps into danger while the center is still loose.",
      "Open the e-file and remove Black's e-pawn so your bishop and queen get more scope.",
      "Black develops with tempo and tries to keep pressure on f2 and the center.",
      "The queen hits e4 and f7 at once, forcing Black to solve concrete problems instead of just enjoying the extra pawn.",
      "Black chooses a tactical check, hoping king exposure will justify the pawn grab.",
      "Step to f1 and keep the king relatively safe. The important point is that the queen still has access to e4.",
      "Black castles to finish development, but the tactical dust has not settled.",
      "Recover the knight on e4 and end the sequence with material restored and Black's activity not worth much."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-rook-net-on-g7",
    name: "Rook net with Re1 and Qxg7",
    description: "A forcing line where Black's knight adventure and king safety problems let White attack the rook and dark squares.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nxe4", "Qxd4", "Nd6", "O-O", "Nxc4", "Re1+", "Be7", "Qxg7", "Rf8", "Bh6"],
    explanations: [
      "Claim space and keep flexible attacking options.",
      "Black meets the center in standard fashion.",
      "Develop toward f7, the usual soft spot in open games.",
      "Black attacks e4 and invites sharp play.",
      "Challenge the center immediately so Black has to answer concrete threats.",
      "Black accepts the challenge and opens the position.",
      "Develop with tempo in mind. White wants quick piece activity, not slow pawn grabbing.",
      "Black takes again, but now the knight on e4 can become a tactical target.",
      "Centralize the queen, hit g7 ideas later, and recover the pawn at once.",
      "Black retreats the knight to hold things together and cover key squares.",
      "Castle first. In these lines king safety and rook activation matter more than snatching material instantly.",
      "Black wins the bishop pair temporarily, but the knight on c4 can become irrelevant if the king gets hit.",
      "Use the open e-file immediately. The check forces Black into a passive defensive move.",
      "Black blocks, but the bishop on e7 now interferes with rook coordination.",
      "Grab g7 because the rook and king are awkwardly placed and the pawn was poisoned.",
      "Black tries to save the back rank and hold the rook together.",
      "Develop with threat. Bh6 clamps dark squares and makes the rook on f8 very hard to untangle."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-accept-sac-and-regroup",
    name: "Accept the knight sac and collect both pawns",
    description: "Black overreaches on f2 and White calmly regroups, taking back material while keeping the extra center pawns.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Bc5", "e5", "Ng4", "h3", "Nxf2", "Kxf2", "d3+", "Kf1", "dxc2", "Qxc2"],
    explanations: [
      "Occupy the center and open lines.",
      "Black mirrors the center and keeps the game open.",
      "Aim at f7 and prepare rapid development.",
      "Black develops with pressure on e4.",
      "Challenge the center before Black gets comfortable.",
      "Black takes and opens the d-file.",
      "Develop and prepare to recapture or push with tempo.",
      "Black chooses active development instead of greed on e4.",
      "Drive the knight and gain space. This also closes the bishop's route back to e7.",
      "The knight jumps forward, eyeing tactical shots.",
      "Ask the knight where it belongs and stop easy jumps to g4 or f4 later.",
      "Black sacs on f2 hoping king exposure will be enough compensation.",
      "Accept it. White should not fear this when the follow-up is under control.",
      "Black keeps trying to justify the sacrifice by pushing a dangerous passed pawn.",
      "Step back to safety and make sure the queen can deal with the pawn chain.",
      "Black reaches c2, but the pawn has run far ahead of the rest of the army.",
      "Simply remove the advanced pawn. White ends the sequence up material with Black's attack gone."
    ]
  },
  {
    category: "Philidor style traps",
    id: "bishops-opening-philidor-queen-win",
    name: "Philidor trap with Ne5 and Qxd8",
    description: "Against a slow ...d6 and ...h6 setup, White opens lines and uses a bishop sac plus central knight jump to win the queen.",
    moves: ["e4", "e5", "Bc4", "d6", "Nf3", "h6", "d4", "exd4", "c3", "dxc3", "Bxf7+", "Kxf7", "Ne5+", "dxe5", "Qxd8"],
    explanations: [
      "Take the center and free the pieces.",
      "Black chooses a more restrained setup.",
      "Develop actively and target f7 before Black is fully ready.",
      "Black supports e5 but blocks the dark bishop for now.",
      "Develop and prepare d4.",
      "This is slow. Black spends a tempo on luft instead of development.",
      "Open the center while Black is behind in development.",
      "Black accepts and hopes the extra pawn matters.",
      "Offer another pawn to rip lines open and distract Black from king safety.",
      "Black accepts again, but now the queenside pawn grab has badly loosened coordination.",
      "Sac on f7 to drag the king out and remove the defender of e6 and d5 ideas.",
      "Black has to take or remain materially down with the king still under fire.",
      "Jump into the center with check. The knight attacks key dark squares and the queen route to d8 becomes real.",
      "Black removes the knight, but that opens the d-file and abandons the queen.",
      "Take the queen. The whole tactic works because Black spent too many tempi on pawns and too few on development."
    ]
  },
  {
    category: "Philidor style traps",
    id: "bishops-opening-philidor-mate-on-f7",
    name: "Philidor mate on f7",
    description: "A mating pattern where the king is dragged out, the queen lands on h5, and the weakened diagonal finishes the game.",
    moves: ["e4", "e5", "Bc4", "d6", "Nf3", "h6", "d4", "exd4", "c3", "dxc3", "Bxf7+", "Kxf7", "Ne5+", "Ke8", "Qh5+", "Ke7", "Qf7#"],
    explanations: [
      "Claim the center and keep maximum flexibility.",
      "Black meets the center but stays a bit cramped.",
      "Develop with direct pressure on f7.",
      "Black supports e5 but still lags in development.",
      "Develop and prepare the central break.",
      "Again Black wastes a useful tempo instead of contesting the initiative.",
      "Open lines while Black's king is still in the middle.",
      "Black grabs the pawn and allows tactical play.",
      "Use c3 to accelerate development and open diagonals.",
      "Black accepts greedily and keeps opening files near the king.",
      "The bishop sac is the trigger that exposes the king and removes the f7 shield.",
      "Black takes, but the king is now far too loose.",
      "Check from the center. The knight jump takes away key escape squares.",
      "Black declines to take the knight and runs back, hoping to survive.",
      "Bring the queen in with tempo. h5 is the clean attacking square in this structure.",
      "The king steps to e7, but that walks straight into the mating net.",
      "Mate. The queen covers e7 and f8, the bishop controls the diagonal, and Black's undeveloped pieces cannot help."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-free-queen-line",
    name: "Free queen after Bxd5 and Bxf7+",
    description: "A tactical punishment where Black's central expansion leaves the queen loose on d8.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "d5", "Bxd5", "Nc5", "Bxf7+", "Ke7", "Bg5+", "Kxf7", "Bxd8"],
    explanations: [
      "Take space and open lines.",
      "Black mirrors the center.",
      "Develop actively and eye f7.",
      "Black pressures e4 and invites tactical play.",
      "Challenge the center before Black finishes development.",
      "Black grabs the pawn and assumes the knight is safe.",
      "Open the center and ask Black to prove the knight on e4 belongs there.",
      "Black supports the knight and attacks your bishop, but this also loosens the diagonal toward d8.",
      "Capture on d5 with tempo and centralize the bishop where it attacks f7 and b7.",
      "Black retreats, but the king and queen remain tied to the center.",
      "Remove the key defender and drag the king out. This is the tactical point of the line.",
      "Black steps forward because castling is impossible and the king needs a square.",
      "Pin the queen line and keep forcing moves only. No time to let Black stabilize.",
      "Black takes the bishop, but that walks the king onto the diagonal you wanted.",
      "Take the queen on d8. The sequence works because Black's king and queen never had time to coordinate."
    ]
  },
  {
    category: "Center play",
    id: "bishops-opening-d5-space-edge",
    name: "Space gain versus early ...Nc6",
    description: "A practical line where White gains space with d5 and emerges with smoother development.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nc6", "d5", "Nd4", "c3", "b5", "Bd3", "Bc5", "cxd4", "Bxd4", "Nf3"],
    explanations: [
      "Claim the center and open your pieces.",
      "Black mirrors the setup.",
      "Develop with pressure on the weak f7 point.",
      "Black develops and controls the center.",
      "Challenge the middle before Black settles.",
      "Black defends e5 and keeps options.",
      "Gain space and kick the knight away. This is the direct positional answer.",
      "The knight jumps to an active square but can still be questioned.",
      "Support the center and prepare to ask that knight what it is doing on d4.",
      "Black expands on the queenside to gain space and keep the bishop active.",
      "Retreat to a useful diagonal. The bishop still eyes h7 and supports future castling.",
      "Black develops naturally, but the center remains unstable.",
      "Remove the advanced knight and simplify toward a healthier structure.",
      "Black recaptures, but the bishop on d4 can later be challenged by development.",
      "Develop with tempo against the bishop and get ready to castle. White's position is easier to handle."
    ]
  },
  {
    category: "Endgame grabs",
    id: "bishops-opening-knight-takes-h8",
    name: "Endgame rook grab on h8",
    description: "An early queen trade leaves Black's rook loose on h8, and White's knight exploits it even at the cost of getting trapped.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "d6", "dxe5", "dxe5", "Qxd8+", "Kxd8", "Nf3", "Nc6", "Ng5", "Be6", "Bxe6", "fxe6", "Nf7+", "Ke7", "Nxh8"],
    explanations: [
      "Occupy the center and free both bishops.",
      "Black mirrors and keeps options open.",
      "Develop toward f7 and invite open-game tactics.",
      "Black develops and watches e4.",
      "Challenge the center immediately.",
      "Black chooses a Philidor-style structure, solid but somewhat passive.",
      "Clarify the center and force Black to recapture in a way that opens lines.",
      "Black accepts and leaves the d-file vulnerable.",
      "Trade queens while Black is stuck in the center. This shifts the battle toward piece activity and king placement.",
      "Black's king is forced to d8 and loses castling rights.",
      "Develop and prepare to target the awkward king and rooks.",
      "Black gets a piece out, but the h8-rook still lacks support.",
      "Jump aggressively. The knight attacks e6 and f7 themes and exploits Black's awkward king.",
      "Black blocks and tries to finish development.",
      "Trade off the key defender so the f7 jump becomes stronger.",
      "Black's pawn structure is damaged and the king remains awkward.",
      "Check first. This forces the king again and clears the route to h8.",
      "The king steps to e7, but the rook is now hanging.",
      "Take the rook. The knight may get trapped later, but winning exchange material is the whole point of the line."
    ]
  },
  {
    category: "Boden-Kieseritzky style",
    id: "bishops-opening-qg4-versus-qf6",
    name: "Qg4 pressure against ...Bc5",
    description: "A sharp bishop's opening line where White uses Qg4 and Nd5 to attack f7 and force Black into defense.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Bc5", "Qg4", "Qf6", "Nd5", "Qxf2+", "Kd1", "d6", "Qxg7", "Be6", "Nxc7+", "Kd7", "Nxe6", "Nge7", "Nh3"],
    explanations: [
      "Take the center and keep open-game options.",
      "Black mirrors and stays classical.",
      "Develop with immediate pressure on f7.",
      "Black protects e5 and develops.",
      "Develop the queenside knight and keep d5 under control.",
      "Black copies your bishop placement and also hits f2 ideas.",
      "The queen heads to g4 to pressure g7 and f7 at once. This is a very concrete setup.",
      "Black defends f7 and contests the g-file tactics.",
      "Jump into d5 where the knight attacks c7, e7, and f6 while exploiting the queen's placement.",
      "Black takes on f2 with check, going for counterplay instead of passive defense.",
      "Step to d1. The king is exposed for the moment, but White's attack still has the initiative.",
      "Black tries to consolidate and free the c8 bishop.",
      "Grab the g7-pawn because Black's rook and king are still poorly coordinated.",
      "Black develops and covers key squares, but the c7 fork remains a problem.",
      "Take on c7 with check and pull Black's king further from harmony.",
      "The king moves to d7 where it remains vulnerable.",
      "Collect the bishop on e6 and convert the tactics into material.",
      "Black finally develops another piece and tries to trap the queen side activity.",
      "Retreat the knight to h3, keeping it safe and preparing to regroup after the tactical phase."
    ]
  },
  {
    category: "Bishop's Opening mainlines",
    id: "bishops-opening-bishop-trade-queen-side-castle",
    name: "Bishop trade into queenside castling",
    description: "A tactical line where both sides grab material, but White's king gets safe first and the queenside knight wins material.",
    moves: ["e4", "e5", "Bc4", "Bc5", "d4", "Bxd4", "Nf3", "Nc6", "Nxd4", "Nxd4", "Be3", "Nc6", "Qg4", "Qf6", "Nc3", "d5", "Qg3", "dxc4", "Nd5", "Qg6", "Nxc7+", "Kd8", "Nxa8", "Qxg3", "O-O-O+", "Bd7", "fxg3"],
    explanations: [
      "Take the center and free your pieces.",
      "Black mirrors and keeps the game open.",
      "Develop with pressure on f7.",
      "Black develops symmetrically and eyes the center.",
      "Open the center before Black finishes coordination.",
      "Black takes, choosing active piece play over pawn structure.",
      "Develop with tempo against the bishop and prepare to recover the pawn.",
      "Black supports the bishop and improves control of d4.",
      "Trade in the center to simplify the tactical tension.",
      "Black recaptures and centralizes the knight.",
      "Develop while hitting d4 and preparing queenside castling ideas.",
      "Black retreats to a stable square and keeps piece activity.",
      "The queen becomes active on the kingside, pressuring g7 and the center.",
      "Black defends carefully and keeps an eye on g6 and f2 themes.",
      "Develop the knight and increase pressure on d5 and b5 squares.",
      "Black strikes in the center to question your setup immediately.",
      "Keep the queen active while avoiding exchanges that help Black.",
      "Black wins a pawn, but this opens more lines and leaves the king uncastled.",
      "Jump into d5 with tempo and threaten c7 and e7 motifs.",
      "Black offers a queen trade route and tries to survive the tactics.",
      "Fork with check. This is the key tactical payoff.",
      "The king is forced to d8 and stays exposed.",
      "Take the rook on a8 and convert the attack into material.",
      "Black trades queens to reduce danger, but it does not solve the development problem.",
      "Castle long with check, getting your king safe while keeping the initiative.",
      "Black interposes to stop the check and finish development.",
      "Recapture on g3 and end with a stable extra-material position and active rooks."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-bxf7-queen-check-recovery",
    name: "Bxf7 check and queen recovery",
    description: "A direct tactical line where Bxf7 and Qd5 win back the pawn while exposing the king.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Nc6", "Bxf7+", "Kxf7", "Qd5+", "Ke8", "Qxe4"],
    explanations: [
      "Take central space and free the bishop and queen.",
      "Black copies the center.",
      "Develop with pressure on f7.",
      "Black attacks e4 and invites tactics.",
      "Challenge the center before Black can settle.",
      "Black grabs the pawn, but the knight and king become tactical targets.",
      "Open the center and expose the downside of the knight excursion.",
      "Black develops another defender, trying to make the extra pawn stick.",
      "Sac on f7 to drag the king out and disrupt coordination.",
      "Black accepts, but the king is now misplaced.",
      "Check from d5, attacking e4 at the same time and keeping complete control of the play.",
      "Black steps back, but the knight on e4 is still loose.",
      "Recover the knight and finish the sequence with material equalized and Black's king still awkward."
    ]
  },
  {
    category: "Urusov Gambit",
    id: "bishops-opening-classical-pressure-with-bd3",
    name: "Classical pressure after Qh4",
    description: "White recovers the pawn, develops fast, and aims everything at the kingside after Black's knight retreat.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nxe4", "Qxd4", "Nf6", "Nc3", "Nc6", "Qh4", "Be7", "Bg5", "O-O", "O-O-O", "d6", "Bd3"],
    explanations: [
      "Claim space and open lines.",
      "Black mirrors the center.",
      "Develop toward the weak f7 square.",
      "Black attacks e4 and encourages an open position.",
      "Hit the center immediately.",
      "Black accepts and opens the d-file.",
      "Develop and prepare to recover the pawn with activity.",
      "Black takes on e4, but that invites queen centralization.",
      "Recover the pawn and centralize the queen in one move.",
      "Black retreats the knight, admitting the e4 outpost was temporary.",
      "Develop another piece and increase central control.",
      "Black matches development and covers e5 and d4.",
      "Place the queen on h4 where it eyes h7 and supports kingside pressure.",
      "Black develops but also blocks coordination between rook and bishop.",
      "Pin the knight and increase pressure on e7 and f6-related squares.",
      "Black castles, but White's pieces are already pointing that way.",
      "Castle long and commit to a full kingside attack.",
      "Black tries to complete development and blunt the center.",
      "Bring the bishop to the ideal attacking square where it supports h7 and the queen battery."
    ]
  },
  {
    category: "Early queen trade",
    id: "bishops-opening-d5-queen-trade-structure-edge",
    name: "Queen trade and damaged structure",
    description: "An early ...d5 and ...dxc4 sequence leads to queen trade, doubled f-pawns, and a clean structural edge for White.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "d5", "dxe5", "dxc4", "Qxd8+", "Kxd8", "exf6", "gxf6", "Nc3"],
    explanations: [
      "Occupy the center and keep open-game options.",
      "Black mirrors and stays classical.",
      "Develop with direct pressure on f7.",
      "Black develops and adds pressure to e4.",
      "Challenge the center right away.",
      "Black counters in the center instead of allowing a free initiative.",
      "Clarify the center and open the d-file so tactical ideas become possible.",
      "Black takes the bishop's pawn, but this leaves the queen vulnerable to trade.",
      "Force the queens off while Black is still uncastled.",
      "Black's king must recapture and loses castling rights immediately.",
      "Pick up the knight on f6 and make Black's pawn structure pay the price.",
      "Black recaptures, but the kingside pawns are now doubled and weak.",
      "Develop simply. In the resulting position White's easier development and Black's damaged structure are the real story."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bgfive-d6-structure-damage",
    name: "Bg5 and structural damage",
    description: "A calmer setup where White uses Bg5 and Nd5 to provoke doubled kingside pawns.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "d6", "Nd5", "h6", "Bxf6", "gxf6", "Ne2"],
    explanations: [
      "Take the center and keep the game open.",
      "Black mirrors and keeps equal central space.",
      "Develop the bishop actively toward f7.",
      "Black develops and controls d4 and e5.",
      "Develop the knight and support central jumps like d5.",
      "Black develops naturally and prepares to castle.",
      "Choose a quieter setup that keeps the center stable and supports future kingside play.",
      "Black develops the bishop to an active square.",
      "Pin the knight and make Black think about kingside structure.",
      "Black supports e5 and frees the c8 bishop.",
      "Jump into d5, using the outpost created by your restrained center.",
      "Black questions the bishop but also creates a hook on the kingside.",
      "Take on f6 to damage the pawn structure. This is the positional point of the line.",
      "Black recaptures and accepts long-term weakness around the king.",
      "Develop calmly. White keeps the healthier structure and flexible plans."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bh4-h5-space-gain",
    name: "Bh4 retreat and h-pawn clamp",
    description: "A slow bishop's opening plan where White tempts pawn advances and then fixes Black's kingside weaknesses with h5.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "h6", "Bh4", "g5", "Bg3", "d6", "h4", "g4", "h5"],
    explanations: [
      "Take the center and open lines.",
      "Black mirrors the center.",
      "Develop with pressure on the sensitive kingside.",
      "Black develops and fights for the center.",
      "Develop and keep d5 ideas available.",
      "Black adds another defender and prepares to castle.",
      "Stay flexible and keep the position closed enough for maneuvering.",
      "Black develops actively.",
      "Pin the knight and invite a decision about kingside structure.",
      "Black questions the bishop immediately.",
      "Retreat while keeping the bishop active on the diagonal.",
      "Black gains space, but every pawn move on the kingside weakens dark squares.",
      "Retreat again to a useful square and keep pressure on e5.",
      "Black shores up the center, but the kingside remains loose.",
      "Start fixing the pawn chain. h4 is not random, it is aimed at creating lasting targets.",
      "Black advances again, which gains space but locks the pawns onto vulnerable squares.",
      "Fix the weakness with h5. White now has clear long-term targets on g4 and the dark squares."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-bb4-simple-development",
    name: "Simple development versus ...Bb4",
    description: "Nothing tactical here. White just develops cleanly and reaches a playable position without concessions.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bb4", "Ne2", "O-O", "O-O"],
    explanations: [
      "Take space and keep the center flexible.",
      "Black mirrors and stays classical.",
      "Develop actively toward f7.",
      "Black supports the center and develops.",
      "Develop the knight and keep options for f4 or Nge2 ideas.",
      "Black develops naturally.",
      "Choose a controlled setup that supports later central expansion.",
      "Black pins the knight and increases piece activity.",
      "Break the pin on your own terms and keep the c-pawn flexible.",
      "Black castles and completes king safety.",
      "Castle as well. White has finished development cleanly and can now play a normal middlegame."
    ]
  },
  {
    category: "Quiet systems",
    id: "bishops-opening-nd5-trade-into-ne2",
    name: "Nd5 trade against castled Black",
    description: "A useful improving line where White jumps into d5, trades the active bishop pair, and keeps a stable setup.",
    moves: ["e4", "e5", "Bc4", "Nc6", "Nc3", "Nf6", "d3", "Bc5", "Bg5", "O-O", "Nd5", "Be7", "Nxe7+", "Qxe7", "Ne2"],
    explanations: [
      "Take central space and open the diagonals.",
      "Black mirrors and keeps classical central control.",
      "Develop with pressure on f7.",
      "Black supports e5 and develops.",
      "Develop the knight and support central jumps.",
      "Black develops naturally and prepares to castle.",
      "Stay flexible and keep the structure sound.",
      "Black puts the bishop on an active attacking diagonal.",
      "Pin the knight and make Black decide whether to tolerate the pressure.",
      "Black castles, so now king safety is settled and the battle becomes positional.",
      "Use the d5 outpost. The knight is hard to challenge because your e4 and c3 resources support it indirectly.",
      "Black steps back to reduce tactical issues.",
      "Trade the bishop pair that was helping defend the kingside.",
      "Black recaptures with the queen and gives up some queen activity for structural simplicity.",
      "Regroup the knight to a flexible square where it can support f4, g3, or c3 plans later."
    ]
  },
  {
    category: "Mainline development",
    id: "bishops-opening-open-center-bb5-line",
    name: "Open center and castle",
    description: "A more balanced line where White plays for space with e5, exchanges in the center, and heads into a normal game.",
    moves: ["e4", "e5", "Bc4", "Nf6", "d4", "exd4", "Nf3", "Nc6", "e5", "d5", "Bb5", "Ne4", "Nxd4", "Bd7", "Bxc6", "bxc6", "O-O"],
    explanations: [
      "Take the center and begin classical development.",
      "Black mirrors the center.",
      "Develop with pressure on f7.",
      "Black attacks e4 and develops.",
      "Challenge the center while Black is still sorting out piece placement.",
      "Black accepts and opens the game.",
      "Develop and prepare to recover the pawn with activity.",
      "Black supports the center and develops another piece.",
      "Gain space and ask the f6-knight to make a decision.",
      "Black hits back in the center and seeks equality by force.",
      "Pin the knight and keep pressure on c6 and e8-related tactics.",
      "Black centralizes the knight aggressively.",
      "Trade off Black's best centralized piece and simplify.",
      "Black develops while preparing to recapture on c6 if needed.",
      "Give up the bishop pair to damage the queenside structure and remove a defender.",
      "Black recaptures and is left with doubled c-pawns.",
      "Castle and finish development. The opening phase is over and White has a normal playable edge based on structure."
    ]
  },
  {
    category: "Direct attack",
    id: "bishops-opening-greco-style-queen-hunt",
    name: "Direct attack after Bxf7+ and Qh5+",
    description: "A forcing attacking line against ...Bc5 and ...exd4 where White drags the king out and wins heavy material with checks.",
    moves: ["e4", "e5", "Bc4", "Bc5", "d4", "exd4", "Bxf7+", "Kxf7", "Qh5+", "g6", "Qxc5", "Nc6", "Nf3", "d6", "Qd5+", "Be6", "Ng5+", "Ke7", "Qxe6+"],
    explanations: [
      "Take the center and free the pieces.",
      "Black mirrors in classical style.",
      "Develop with pressure on f7.",
      "Black develops symmetrically and also eyes f2.",
      "Open the center before Black is fully coordinated.",
      "Black takes and allows tactical play around the king.",
      "Sac on f7 to force the king out. This is the critical attacking idea.",
      "Black accepts and loses the right to castle.",
      "Bring the queen out with check immediately. In sacrificial lines, tempo is everything.",
      "Black blocks the check, but the dark squares stay weak.",
      "Take the bishop on c5 and convert the sacrifice into concrete material while keeping the initiative.",
      "Black develops and tries to cover central entry squares.",
      "Develop another attacker and prepare to bring the rook or knight into the attack.",
      "Black tries to hide behind development, but the king is still exposed.",
      "Another check, forcing Black to keep reacting instead of coordinating.",
      "Black blocks, but that piece becomes a tactical target too.",
      "Jump with check and attack the pinned or overloaded pieces around the king.",
      "Black's king flees, but the position is still collapsing.",
      "Take on e6 with check and keep the attack going with a winning material plus initiative balance."
    ]
  }
];
