import { withOpeningFeedback } from "./feedback";

// src/openings/caroKannLines.js

// SEO / page intro text for Caro-Kann drills
export const caroKannSEOText = `
The Caro-Kann Defense starts with 1. e4 c6 and aims for a solid central challenge with ...d5
while keeping Black's light-squared bishop flexible.

These drills cover the main student-facing structures you listed:
- Advance Variation (3. e5) with the key ...c5 break and typical pressure on e5 and d4
- Exchange and Panov-style structures (3. exd5 / 4. c4) where piece activity and pawn structure matter
- Classical / Two Knights setups (3. Nc3) with development and early piece pressure themes

Each line includes move-by-move explanations that state the concrete purpose:
what is being attacked or defended, what pawn break is being prepared, and what concession is being forced.
`;

export const caroKannLines = withOpeningFeedback([
  {
    category: "Advance Variation",
    id: "caro-kann-line-01-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 1: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "a3", "e6", "b4", "a5", "b5", "Nxe5", "Bb2", "f6", "Bxe5", "fxe5", "Qh5+", "g6", "Qxe5", "Nf6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Let's learn the Caro-Kann! This opening's one of the best counter attacks to white playing pawn e4. Let's start with playing with pawn to c6.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Prevent ...Bb4 and prepare b4 space.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Support the pawn on c5 or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on b4/b5 and open files on the queenside.", "Gain space and try to kick a knight, but also create targets on the queenside.", "Remove a central pawn and hit key squares. Often needs to be tactically supported.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Directly attack the e5 pawn. It can be necessary but it creates king-safety commitments.", "Remove a key defender or pawn to open lines and win tempi.", "Recapture while opening the f-file; often leaves king safety questions.", "Force a concession: king move or pawn move. Used to exploit an uncastled king.", "Kick a checking queen and prepare to develop the bishop, but weaken dark squares.", "Win material, but check whether it concedes development or tactics.", "Develop and pressure e4/d5 squares, aiming to increase central pressure."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-02-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 2: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "c3", "e6", "b4", "a5", "Bb5", "Bd7", "Bxc6", "Bxc6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support e5 and grab kingside space, but can weaken e4 and king safety.", "Develop toward f5 without blocking the f-pawn; a common maneuver vs f4 structures.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Support the pawn on c5 or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on b4/b5 and open files on the queenside.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Challenge the bishop and complete development while defending key squares.", "Trade to clarify structure and sometimes win time on development.", "Trade to clarify structure and sometimes win time on development."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-03-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 3: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "h3", "Bxf3", "Qxf3", "Nxd4", "Qd3", "Nc6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on d4 and prepare the usual ...Bg4 plan against the f3-knight.", "Develop and support d4 and e5, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Develop the bishop before ...e6 and pin the knight that helps defend d4.", "This often helps Black because the bishop was happy to trade for the f3-knight anyway.", "Trade off a key defender of d4. In these structures that exchange is often part of Black's plan.", "Recapture while keeping structure intact and maintaining central flexibility.", "Win the d4 pawn once the f3-knight is gone and the base of White's chain is loose.", "Step back to defend c2 and keep the queen near the center after losing the d4 pawn.", "Return to c6 so the knight keeps pressure on e5 and supports the rest of Black's development."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-04-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 4: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "h3", "Bxf3", "gxf3", "Qb6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on d4 and prepare the usual ...Bg4 plan against the f3-knight.", "Develop and support d4 and e5, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Develop the bishop before ...e6 and pin the knight that helps defend d4.", "This often helps Black because the bishop was happy to trade for the f3-knight anyway.", "Trade off a key defender of d4. In these structures that exchange is often part of Black's plan.", "Recapture, but the damaged structure leaves d4 harder to hold and gives Black clear targets.", "The standard double attack. Black hits d4 again and also attacks b2, which makes defense awkward."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-05-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 5: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "f4", "cxd4", "cxd4", "h5", "Nf3", "Bg4", "Be2", "e6", "O-O", "Qb6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on d4 and prepare the usual ...Bg4 plan against the f3-knight.", "Support e5 and grab kingside space, but can weaken e4 and king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Gain space on the kingside and create a hook if White overextends there.", "Develop and support d4 and e5, also helps king safety.", "Develop the bishop before ...e6 and pin the knight that helps defend d4.", "Unpin and prepare castling without conceding structure damage.", "Only now close the chain. Black keeps the bishop outside first, then solidifies the center.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "The standard double attack. Black hits d4 again and also attacks b2, which makes defense awkward."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-07-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 7: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "a3", "e6", "b4", "a5", "Bb2", "axb4", "axb4", "Rxa1", "Bxa1", "Nxb4"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Prevent ...Bb4 and prepare b4 space.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Support the pawn on c5 or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on b4 and open the queenside before White can settle.", "Develop the bishop to support the queenside pawns, but White is still behind in development.", "Exchange on b4 to strip away White's pawn cover and open more lines.", "Recapture, but the a-file and the rook on a1 are now vulnerable.", "Take the rook while White is still undeveloped and cash in on the open a-file.", "Recapture, but the bishop gets dragged to a1 and Black's knight jump comes with tempo.", "Recover another pawn and punish White's queenside expansion before the pieces are coordinated."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-08-e4-c6-d4-d5-exd5-cxd5-c4-nf6",
    name: "Line 8: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4", "Nf6", "Nc3", "g6", "Nf3", "Bg7", "cxd5", "Nxd5", "Bc4", "Nxc3", "bxc3", "Qc7"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Open lines and convert the center into a structure fight.", "Enter Panov style play: space plus development, at the cost of an isolated pawn risk.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "Develop, add central control, and support key pawn breaks.", "Kick a checking queen and prepare to develop the bishop, but weaken dark squares.", "Develop and support d4 and e5, also helps king safety.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Open lines and convert the center into a structure fight.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-09-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 9: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "h3", "Bxf3", "Bxf3", "Qb6", "Be3", "Qxb2", "Nd2", "Bb4"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on d4 and prepare the usual ...Bg4 plan against the f3-knight.", "Develop and support d4 and e5, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Develop the bishop before ...e6 and pin the knight that helps defend d4.", "Unpin and prepare castling without conceding structure damage.", "Only now close the chain. Black keeps the bishop outside first, then solidifies the center.", "This often helps Black because the bishop was happy to trade for the f3-knight anyway.", "Trade off a key defender of d4. In these structures that exchange is often part of Black's plan.", "Recapture, but the f3-knight is gone and d4 is now harder for White to hold.", "The standard double attack. Black hits d4 again and also attacks b2, which makes defense awkward.", "Cover d4 and stop immediate tactical shots on b2 or c2.", "Grab b2 when White cannot hold both pawns. The rook on a1 can become a tactical target too.", "Reroute the knight to cover c4 and b3 while trying to trap the queen.", "Pin the knight and increase tactical pressure while the queen on b2 is still active."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-10-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 10: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Bb5", "Qa5", "Bxc6+", "bxc6", "Bd2", "Qb6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Pressure c3 and e5 and often win time by forcing a response.", "Trade to clarify structure and sometimes win time on development. With check to force a reply and keep tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Pressure d4 and b2, forcing White to spend time defending or trading queens."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-11-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 11: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Ng3", "h5", "h4", "Bg4", "Be2", "e6", "Nf3", "Bd6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Develop, add central control, and support key pawn breaks.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Space gain and sometimes a hook to attack White's kingside pawn chain (or gain air). Risky if it weakens squares.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Pin the knight and increase pressure on d4 or f3-based structures.", "Unpin and prepare castling without conceding structure damage.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Develop and support d4 and e5, also helps king safety.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-12-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 12: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "O-O", "Nge7", "Nc3", "Nf5", "Be3", "Be7", "a3", "O-O"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on d4 and prepare the usual ...Bg4 plan against the f3-knight.", "Develop and support d4 and e5, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Develop the bishop before ...e6 and pin the knight that helps defend d4.", "Unpin and prepare castling without conceding structure damage.", "Only now close the chain. Black keeps the bishop outside first, then solidifies the center.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Reroute the knight through e7 because f6 is unavailable, keeping ...Nf5 in reserve.", "Develop, add central control, and support key pawn breaks.", "Land on f5 to add another attacker to d4 and pressure e3 and g3.", "Cover d4 and make it harder for Black to win the base of the pawn chain immediately.", "Complete development and prepare castling, also supports ...f6 breaks sometimes.", "Prevent ...Bb4 and prepare b4 space.", "King safety and rook activation. Often the best way to connect pieces before tactics."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-13-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 13: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Ng3", "h5", "Nf3", "h4", "Ne2", "Bg4"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Develop, add central control, and support key pawn breaks.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Space gain and sometimes a hook to attack White's kingside pawn chain (or gain air). Risky if it weakens squares.", "Develop and support d4 and e5, also helps king safety.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Reposition to avoid pins and support f4 or g3 setups.", "Pin the knight and increase pressure on d4 or f3-based structures."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-14-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 14: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Be3", "Nh6", "Bxh6", "gxh6", "Nf3", "Qb6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Develop toward f5 without blocking the f-pawn; a common maneuver vs f4 structures.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Develop and support d4 and e5, also helps king safety.", "Pressure d4 and b2, forcing White to spend time defending or trading queens."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-15-e4-c6-d4-d5-exd5-cxd5-bd3-nc6",
    name: "Line 15: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3", "Nc6", "c3", "Nf6", "h3", "e5", "dxe5", "Nxe5"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Open lines and convert the center into a structure fight.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "Ask the pinning bishop to decide and reduce long-term pin pressure.", "Advance and gain space, but accept that the pawn can become a target.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Remove a central pawn and hit key squares. Often needs to be tactically supported."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-16-e4-c6-d4-d5-exd5-cxd5-c4-nf6",
    name: "Line 16: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4", "Nf6", "cxd5", "Nxd5", "Nc3", "Nc6", "Nf3", "Bf5", "Bc4", "e6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Open lines and convert the center into a structure fight.", "Enter Panov style play: space plus development, at the cost of an isolated pawn risk.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "Open lines and convert the center into a structure fight.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Develop, add central control, and support key pawn breaks.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop and support d4 and e5, also helps king safety.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-17-e4-c6-d4-d5-exd5-cxd5-bd3-nc6",
    name: "Line 17: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3", "Nc6", "c3", "Nf6", "Bf4", "Bg4", "Qb3", "Qd7", "Nd2", "e6", "Ngf3", "Bd6", "Bxd6", "Qxd6", "O-O", "O-O"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Recapture toward the center, vacate c6 for the knight, and reach an easy development scheme.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Develop naturally now that c6 is free and Black no longer has the usual space issue.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "Develop actively and prepare the standard idea of meeting ...e6 with the bishop already outside the chain.", "Develop the bishop before ...e6 and pin the knight. In Exchange structures this is a very common motif.", "Hit b7 and d5, asking Black to defend before finishing development.", "Defend b7 and keep the option of queenside castling or ...e6 without loosening anything.", "Support c4/e4 structures, reroute pieces, and cover f3 squares if needed.", "Only now lock the chain. The bishop is already out, so Black keeps it active.", "Reinforce the center and prepare quick castling.", "Develop to a strong diagonal and prepare to castle. Black's setup stays simple here.", "Trade a strong attacking bishop, but Black is happy to simplify with full development.", "Recapture centrally and keep the queen active while controlling the kingside dark squares.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "King safety and rook activation. Often the best way to connect pieces before tactics."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-18-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 18: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "b4", "a5", "c3", "axb4", "cxb4", "Bd7", "Bxc6", "Bxc6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Support the pawn on c5 or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on b4/b5 and open files on the queenside.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Challenge the bishop and complete development while defending key squares.", "Trade to clarify structure and sometimes win time on development.", "Trade to clarify structure and sometimes win time on development."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-19-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 19: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "c3", "Bd6", "Bd3", "O-O", "Qc2", "Re8+", "Ne2", "h5", "Be3", "Nd7", "O-O-O", "Nf8"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Develop, add central control, and support key pawn breaks.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "Force a response with check, gaining tempo to improve your attack or development.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Force a response with check, gaining tempo to improve your attack or development.", "Reposition to avoid pins and support f4 or g3 setups.", "Space gain and sometimes a hook to attack White's kingside pawn chain (or gain air). Risky if it weakens squares.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Castle long when the center is stable enough, bringing rook to the d-file quickly.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-20-e4-c6-d4-d5-exd5-cxd5-nf3-nf6",
    name: "Line 20: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nf3", "Nf6", "Bd3", "Bg4", "O-O", "Nc6", "c3", "e6", "h3", "Bh5", "Bg5", "Bd6", "Nbd2", "h6", "Bh4", "Qc7"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Open lines and convert the center into a structure fight.", "Develop and support d4 and e5, also helps king safety.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Pin the knight and increase pressure on d4 or f3-based structures.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Ask the pinning bishop to decide and reduce long-term pin pressure.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-21-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 21: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "Nf3", "Bg4", "Be3", "Nf5", "Bf2", "g5", "fxg5", "e6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support e5 and grab kingside space, but can weaken e4 and king safety.", "Develop toward f5 without blocking the f-pawn; a common maneuver vs f4 structures.", "Develop and support d4 and e5, also helps king safety.", "Pin the knight and increase pressure on d4 or f3-based structures.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Jump to an active square to hit d4/e3/g3 and pressure key pawns.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-22-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 22: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Nf3", "Bg4", "Bb5", "Qa5+", "Nc3", "e6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop and support d4 and e5, also helps king safety.", "Pin the knight and increase pressure on d4 or f3-based structures.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Pressure c3 and e5 and often win time by forcing a response. With check to force a reply and keep tempo.", "Develop, add central control, and support key pawn breaks.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-23-e4-c6-d4-d5-exd5-cxd5-nf3-nf6",
    name: "Line 23: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nf3", "Nf6", "Bd3", "Bg4", "O-O", "Nc6", "c3", "e6", "Bg5", "Be7", "Nbd2", "O-O", "Qc2", "h6", "Bh4", "Rc8"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Open the e-file and keep a pawn presence in the center.", "Open lines and convert the center into a structure fight.", "Develop and support d4 and e5, also helps king safety.", "Develop and pressure e4/d5 squares, aiming to increase central pressure.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Pin the knight and increase pressure on d4 or f3-based structures.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Complete development and prepare castling, also supports ...f6 breaks sometimes.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-24-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 24: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "O-O", "Nge7", "Nc3", "Nf5", "Be3", "Be7", "h3", "Bxf3", "Bxf3", "O-O", "Rc1", "f6", "exf6", "Bxf6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop and support d4 and e5, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Pin the knight and increase pressure on d4 or f3-based structures.", "Unpin and prepare castling without conceding structure damage.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Develop without committing the f-pawn, preparing ...Nf5 and solid king safety.", "Develop, add central control, and support key pawn breaks.", "Jump to an active square to hit d4/e3/g3 and pressure key pawns.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Complete development and prepare castling, also supports ...f6 breaks sometimes.", "Ask the pinning bishop to decide and reduce long-term pin pressure.", "Remove a defender and often force White to choose structure damage or queen recapture.", "Remove a defender and often force White to choose structure damage or queen recapture.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Put the rook on the open or semi-open file and pressure c-file targets.", "Directly attack the e5 pawn. It can be necessary but it creates king-safety commitments.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-25-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 25: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "Bxc6+", "bxc6", "b4", "a5", "c3", "axb4", "cxb4", "Qh4", "Bd2", "Qe4+", "Qe2", "Qxg2", "Qf3", "Qg6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Trade to clarify structure and sometimes win time on development. With check to force a reply and keep tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Support the pawn on c5 or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on b4/b5 and open files on the queenside.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Force a response with check, gaining tempo to improve your attack or development.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-26-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 26: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "Nf3", "Bg4", "Be2", "e6", "Be3", "Nf5"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Support e5 and grab kingside space, but can weaken e4 and king safety.", "Develop toward f5 without blocking the f-pawn; a common maneuver vs f4 structures.", "Develop and support d4 and e5, also helps king safety.", "Pin the knight and increase pressure on d4 or f3-based structures.", "Unpin and prepare castling without conceding structure damage.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Jump to an active square to hit d4/e3/g3 and pressure key pawns."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-27-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 27: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "Nf3", "Bd6", "Bd3", "O-O", "O-O", "Re8", "h3", "Nd7", "c3", "Nf8"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Develop, add central control, and support key pawn breaks.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Challenge the e4-knight immediately. This is the simplest way to solve Black's space problem.", "Force a response with check, gaining tempo to improve your attack or development.", "Accept doubled pawns, but open lines, free the pieces, and keep the kingside heavily protected.", "Develop and support d4 and e5, also helps king safety.", "Develop naturally, point at h2, and prepare to castle behind the extra f-pawn cover.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Use the open e-file at once and make White feel the awkward king placement.", "Ask the bishop to decide and stop White from expanding without thought.", "Reroute toward f8 or e5 and finish development without having to memorize much.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Tuck the knight back into the kingside setup and keep the position rock solid."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-28-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 28: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "c3", "Bd6", "Bd3", "O-O", "Qc2", "Re8+", "Ne2", "h5", "O-O", "h4", "h3", "Nd7", "Be3", "Nf8"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Develop, add central control, and support key pawn breaks.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Challenge the e4-knight immediately. This is the simplest way to solve Black's space problem.", "Force a response with check, gaining tempo to improve your attack or development.", "Accept doubled pawns, but open lines, free the pieces, and keep the kingside heavily protected.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Develop naturally, point at h2, and prepare to castle behind the extra f-pawn cover.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Use the open e-file at once and make White respond before completing development.", "Reposition to avoid pins and support f4 or g3 setups.", "Gain space and set up ...h4, which can make White's kingside harder to coordinate.", "King safety and rook activation. Often the best way to connect pieces before tactics.", "Drive the knight from g3 and claim more space on the kingside.", "White asks the bishop to decide, but the kingside structure is already under pressure.", "Reroute toward f8 or e5 and keep the kingside compact.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Tuck the knight back into the kingside setup and keep the position rock solid."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-29-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 29: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "Be3", "Ne7", "c3", "Nf5", "Bd4", "Bd7"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...d5 while keeping the light-squared bishop free.", "Build a strong center and support e4.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure d4 and e5. Also supports ...d4 or ...e5 ideas in some lines.", "Develop with pressure and often provoke concessions like ...Bd7 or ...Qa5.", "Support ...d5 or ...c5 structure, open the dark bishop, and prepare king safety.", "Develop and often fight Qb6/Qa5 pressure by covering key squares.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Support d4 and prepare to recapture with a pawn, keeping central control.", "Jump to an active square to hit d4/e3/g3 and pressure key pawns.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Challenge the bishop and complete development while defending key squares."],
  },
]);