import { withOpeningFeedback } from "./feedback";

// src/openings/caroKannLines.js

// SEO / page intro text for Caro-Kann drills
export const caroKannSEOText = `
The Caro-Kann Defense starts with 1. e4 c6. It's often described as a "better version of the French Defense" because Black gets to develop the light-squared bishop before locking the pawn chain with ...e6.

The goal is to challenge White's center immediately with ...d5, creating a solid "pyramid" of pawns (c6-d5-e6) once the bishop is out, and to make White prove their space advantage is worth something.

These drills cover the main practical structures:
- Advance Variation (3. e5), where Black's main way to fight for a win is the ...c5 pawn break, attacking the base of White's chain (d4), and developing the bishop to f5.
- Exchange and Panov structures (3. exd5 / 4. c4), where Black gets an easy, safe setup by developing naturally and controlling d5 against the Isolated Queen's Pawn.
- Classical / Two Knights setups (3. Nc3), where Black usually trades on e4 and develops the bishop to f5 or g4, staying wary of early queen pins and smothered mate traps.

The goal of these explanations is to act as your coach. They tell you what each move is trying to attack, defend, or prepare so the Caro-Kann feels like a clear plan instead of a memorization test.
`;

export const caroKannLines = withOpeningFeedback([
  {
    category: "Advance Variation",
    id: "caro-kann-line-01-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 1: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "a3", "e6", "b4", "a5", "b5", "Nxe5", "Bb2", "f6", "Bxe5", "fxe5", "Qh5+", "g6", "Qxe5", "Nf6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Prevent ...B{{square b4}} and prepare {{square b4}} space.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety.", "Support the {{pawn c5 full}} or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on {{square b4}}/{{square b5}} and open files on the queenside.", "Gain space and try to kick a knight, but also create targets on the queenside.", "Remove a central pawn and hit key squares. Often needs to be tactically supported.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Directly attack the {{square e5}} pawn. It can be necessary but it creates king-safety commitments.", "Remove a key defender or pawn to open lines and win tempi.", "Recapture while opening the f-file; often leaves king safety questions.", "Force a concession: king move or pawn move. Used to exploit an uncastled king.", "Kick a checking queen and prepare to develop the bishop, but weaken dark squares.", "Win material, but check whether it concedes development or tactics.", "Develop and pressure {{square e4}}/{{square d5}} squares, aiming to increase central pressure."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-02-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 2: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "c3", "e6", "b4", "a5", "Bb5", "Bd7", "Bxc6", "Bxc6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White wins a pawn for the moment, but gives Black a clear target and extra time.", "The {{knight c6 full}} piles pressure on {{square d4}} and {{square e5}}. In the Caro-Kann that job is very concrete.", "White reinforces {{square e5}}, but creates more dark-square and king-safety questions.", "Start the knight route toward {{square f5}}. In these Advance structures that knight often attacks the bishop that defends White's center.", "White keeps the {{square d4}} pawn supported so the chain stays intact.", "Open the dark-squared bishop and prepare to challenge the extra {{square c5}} pawn or the center itself.", "White tries to keep the extra pawn, but is still behind in development.", "Attack the pawn chain before it becomes stable.", "White develops with tempo, but still has to justify all the queenside pawn moves.", "Challenge the bishop and complete development without loosening the position.", "White gives up the bishop pair to damage the queenside structure.", "Recapture toward the center and keep both bishops active."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-03-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 3: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "h3", "Bxf3", "Qxf3", "Nxd4", "Qd3", "Nc6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White develops another defender of the center.", "Clarify the center before White gets too comfortable.", "White keeps the broad center, but {{square d4}} is now the obvious base to attack.", "Exactly the bishop move this structure wants. Pin the knight so it cannot keep helping the center.", "This does not really solve Black's problem because the bishop was happy to trade for that knight anyway.", "Trade off a key defender of {{square d4}} and make White's center easier to attack.", "White keeps the structure clean, but the queen cannot defend every weakness by herself.", "Once the knight is gone, Black wins the base of the chain.", "White has to step back and cover {{square c2}} while keeping the queen near the center.", "Reset the knight to a healthy square and keep the pressure going."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-04-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 4: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "h3", "Bxf3", "gxf3", "Qb6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White develops another defender of the center.", "Clarify the center before White gets too comfortable.", "White keeps the broad center, but {{square d4}} is now the obvious base to attack.", "Bring the bishop out before ...{{square e6}} and pin the knight that helps hold the center together.", "This does not really solve Black's problem because the bishop was happy to trade for that knight anyway.", "Trade off a key defender of {{square d4}} and make White choose between structure and activity.", "White keeps a {{pawn f3 full}}, but the structure is damaged and {{square d4}} becomes harder to protect.", "The standard follow-up. Black attacks {{square d4}} and {{square b2}} at the same time and asks White to solve two problems at once."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-05-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 5: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "f4", "cxd4", "cxd4", "h5", "Nf3", "Bg4", "Be2", "e6", "O-O", "Qb6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White grabs kingside space, but that only matters if the center stays closed and healthy.", "Clarify the center before White gets too comfortable.", "White keeps the broad center, but {{square d4}} is now the obvious base to attack.", "Gain space and create a hook on the kingside. The move works because Black already has counterplay in the center.", "White develops another defender of the center.", "Get the bishop outside the chain first and pin the knight that helps hold {{square d4}}.", "White unpins and prepares to castle, but Black has already achieved the main setup goal.", "Only now close the structure. Black gets the bishop out first and then supports the center.", "Finish king safety before the concrete queen move.", "The familiar double attack on {{square d4}} and {{square b2}}. In the Advance, this queen move is often the payoff for Black's setup."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-07-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 7: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "a3", "e6", "b4", "a5", "Bb2", "axb4", "axb4", "Rxa1", "Bxa1", "Nxb4"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Prevent ...B{{square b4}} and prepare {{square b4}} space.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety.", "Support the {{pawn c5 full}} or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on {{square b4}} and open the queenside before White can settle.", "Develop the bishop to support the queenside pawns, but White is still behind in development.", "Exchange on {{square b4}} to strip away White's pawn cover and open more lines.", "Recapture, but the a-file and the {{rook a1 full}} are now vulnerable.", "Take the rook while White is still undeveloped and cash in on the open a-file.", "Recapture, but the bishop gets dragged to {{square a1}} and Black's knight jump comes with tempo.", "Recover another pawn and punish White's queenside expansion before the pieces are coordinated."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-08-e4-c6-d4-d5-exd5-cxd5-c4-nf6",
    name: "Line 8: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4", "Nf6", "Nc3", "g6", "Nf3", "Bg7", "cxd5", "Nxd5", "Bc4", "Nxc3", "bxc3", "Qc7"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center and reach the easy Caro-Kann structure.", "This is the Panov. White grabs space and activity, even if it may mean an isolated pawn later.", "Defend {{square d5}} first. In the Panov, Black usually develops rather than grabbing on {{square c4}}.", "White develops naturally and adds more central control.", "Prepare ...B{{square g7}} and a solid kingside setup while keeping {{square d5}} protected.", "White keeps developing and supports the center.", "Fianchetto the bishop so it bears down on {{square d4}} and helps Black castle safely.", "White simplifies before Black gets full coordination.", "Recapture with a piece and keep development flowing.", "White points at {{square d5}} and {{square f7}} and tries to use the lead in development.", "Trade off an active piece and damage White's queenside structure.", "White keeps the bishop pair, but the c-pawns and the isolated-pawn themes remain.", "Support the center, eye {{square c3}}, and continue normal development without loosening the position."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-09-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 9: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "h3", "Bxf3", "Bxf3", "Qb6", "Be3", "Qxb2", "Nd2", "Bb4"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Challenge the center from the side and start untangling Black's cramped pieces.", "Support {{square d4}} and prepare to recapture with a pawn, keeping central control.", "Develop with pressure on {{square d4}} and prepare the usual ...B{{square g4}} plan against the {{knight f3 full}}.", "Develop and support {{square d4}} and {{square e5}}, also helps king safety.", "Resolve central tension and force White to define their structure.", "Resolve central tension and force White to define their structure.", "Develop the bishop before ...{{square e6}} and pin the knight that helps defend {{square d4}}.", "Unpin and prepare castling without conceding structure damage.", "Only now close the chain. Black keeps the bishop outside first, then solidifies the center.", "This often helps Black because the bishop was happy to trade for the {{knight f3 full}} anyway.", "Trade off a key defender of {{square d4}}. In these structures that exchange is often part of Black's plan.", "Recapture, but the {{knight f3 full}} is gone and {{square d4}} is now harder for White to hold.", "The standard double attack. Black hits {{square d4}} again and also attacks {{square b2}}, which makes defense awkward.", "Cover {{square d4}} and stop immediate tactical shots on {{square b2}} or {{square c2}}.", "Grab {{square b2}} when White cannot hold both pawns. The {{rook a1 full}} can become a tactical target too.", "Reroute the knight to cover {{square c4}} and {{square b3}} while trying to trap the queen.", "Pin the knight and increase tactical pressure while the {{queen b2 full}} is still active."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-10-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 10: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Bb5", "Qa5", "Bxc6+", "bxc6", "Bd2", "Qb6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Support {{square d4}} and prepare to recapture with a pawn, keeping central control.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Develop with pressure and often provoke concessions like ...B{{square d7}} or ...Q{{square a5}}.", "Pressure {{square c3}} and {{square e5}} and often win time by forcing a response.", "Trade to clarify structure and sometimes win time on development. With check to force a reply and keep tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Pressure {{square d4}} and {{square b2}}, forcing White to spend time defending or trading queens."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-11-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 11: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "The Classical Variation (Tartakower/Korchnoi). Here White plays Ng3 to keep the knight and Black strikes on the kingside with ...h5.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Ng3", "h5", "h4", "Bg4", "Be2", "e6", "Nf3", "Bd6"],
    explanations: ["White takes the center.", "Caro-Kann! We prepare ...{{square d5}} without blocking our light-squared bishop.", "White builds the big center.", "Strike immediately. We're challenging White's control of the center.", "White develops and defends {{square e4}} with a knight.", "Trade! We remove White's central pawn. This is the main line of the Caro-Kann.", "White recaptures, centralizing the knight.", "Develop and challenge the central knight right away.", "White refuses the trade, trying to keep pieces on the board to build an attack.", "Strike on the wing! Since White's knight moved to {{square g3}}, we immediately try to kick it with our h-pawn.", "White stops our h-pawn from advancing further.", "Develop the bishop! Notice how we get our problem piece out before playing ...{{square e6}}.", "White develops and offers a trade of bishops.", "Now we play {{square e6}}, locking our pawn chain (the pyramid) while our bishop is safely outside.", "White develops the knight.", "Develop the dark-squared bishop to its most active diagonal, pointing at White's kingside."]
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-12-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 12: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "O-O", "Nge7", "Nc3", "Nf5", "Be3", "Be7", "a3", "O-O"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White develops another defender of the center.", "Clarify the center before White gets too comfortable.", "White keeps the broad center, but {{square d4}} is now the obvious base to attack.", "Bring the bishop out before ...{{square e6}} and pin the knight that helps hold the center together.", "White unpins and prepares to castle.", "Only now close the structure. Black got the bishop outside first, which is the whole point.", "Castle and connect the rooks before the next wave of pressure.", "When {{square f6}} is unavailable, the knight goes to {{square e7}} on the way to {{square f5}}.", "White adds another defender and hopes to keep the center intact.", "The whole reroute had a purpose: hit the bishop that props up White's center and add one more attacker to {{square d4}}.", "That bishop often has to babysit {{square d4}}, so White keeps it on the job.", "Finish development and keep the position ready for ...{{square f6}} later if needed.", "White stops ...B{{square b4}} and hints at queenside space, but Black's setup is already in place.", "Complete king safety and keep the central pressure ready."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-13-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 13: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "The Classical Variation where Black pushes ...h4 against White's Ng3 setup to harass the knight before bringing out the bishop.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Ng3", "h5", "Nf3", "h4", "Ne2", "Bg4"],
    explanations: ["White takes the center.", "Caro-Kann! We prepare ...{{square d5}} without blocking our light-squared bishop.", "White builds the big center.", "Strike immediately. We're challenging White's control of the center.", "White develops and defends {{square e4}} with a knight.", "Trade! We remove White's central pawn. This is the main line of the Caro-Kann.", "White recaptures, centralizing the knight.", "Develop and challenge the central knight right away.", "White refuses the trade, trying to keep pieces on the board to build an attack.", "Strike on the wing! Since White's knight moved to {{square g3}}, we immediately try to kick it with our h-pawn.", "White ignores our pawn and develops naturally.", "Keep pushing! Make that knight uncomfortable.", "White is forced to retreat the knight to an awkward square.", "Now develop the bishop to an active square, pinning White's remaining knight. Black is doing great here!"],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-14-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 14: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Be3", "Nh6", "Bxh6", "gxh6", "Nf3", "Qb6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White develops the bishop to help defend the center.", "Head toward {{square f5}}. In these Advance lines the knight often wants the bishop that is holding White's chain together.", "White gives up the bishop pair to stop that reroute immediately.", "Black accepts the damaged structure because the g-file opens and the queen can still become active quickly.", "White develops and tries to finish the setup before Black's pressure grows.", "Hit {{square d4}} and {{square b2}} immediately. Even with a damaged kingside, Black gets active play from the queen."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-15-e4-c6-d4-d5-exd5-cxd5-bd3-nc6",
    name: "Line 15: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3", "Nc6", "c3", "Nf6", "h3", "e5", "dxe5", "Nxe5"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center and reach the easy Caro-Kann structure.", "White develops a bishop to an active square and eyes the kingside.", "The {{knight c6 full}} is natural here because the c-pawn is gone and Black has no space problem.", "White supports the center and prepares to finish the setup.", "Bring out the second knight. In the Exchange, Black usually just gets the pieces out cleanly.", "White asks the bishop to decide, but Black does not need to rush anything.", "Strike in the center once development is under control.", "White takes to avoid letting Black keep a strong pawn duo.", "Recapture with a piece and keep the simple, active Exchange setup."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-16-e4-c6-d4-d5-exd5-cxd5-c4-nf6",
    name: "Line 16: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4", "Nf6", "cxd5", "Nxd5", "Nc3", "Nc6", "Nf3", "Bf5", "Bc4", "e6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center and reach the easy Caro-Kann structure.", "This is the Panov. White accepts an isolated-pawn risk in return for activity.", "Defend {{square d5}} first. Against the Panov, Black does not need to help White by grabbing on {{square c4}}.", "White simplifies before Black finishes development.", "Recapture with the knight and keep everything active.", "White develops and pressures the center.", "Now the other knight comes out because {{square d5}} is already secure.", "White keeps developing and prepares to castle.", "Get the bishop outside the chain before ...{{square e6}}. This is one of the basic Caro-Kann rules.", "White develops actively, but the central structure will decide the game more than the piece placement alone.", "Only now support the center and free the dark-squared bishop."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-17-e4-c6-d4-d5-exd5-cxd5-bd3-nc6",
    name: "Line 17: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3", "Nc6", "c3", "Nf6", "Bf4", "Bg4", "Qb3", "Qd7", "Nd2", "e6", "Ngf3", "Bd6", "Bxd6", "Qxd6", "O-O", "O-O"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center, free {{square c6}} for the knight, and reach the easy Exchange setup.", "White develops a bishop to an active square and eyes the kingside.", "The {{knight c6 full}} comes out with no space issues because the c-pawn is already gone.", "White supports {{square d4}} and prepares a normal setup.", "Bring out the second knight. In the Exchange, Black usually just finishes development cleanly.", "White puts the bishop outside the chain, which is exactly what Black also wants to do.", "Get the bishop out before ...{{square e6}} and pin the knight. This is one of the simplest Exchange ideas.", "White hits {{square b7}} and {{square d5}} before Black finishes development.", "Defend {{square b7}} cleanly and keep the rest of the setup simple.", "White improves coordination and keeps an eye on {{square e4}} and {{square c4}} ideas.", "Only now play ...{{square e6}}. The bishop is already active, so Black gives up nothing.", "White reinforces the center and gets ready to castle.", "Develop the other bishop to a useful square and keep the setup easy.", "White gives up a good bishop, but Black is happy to simplify with full development.", "Recapture toward the center and keep the queen active.", "Castle and finish the textbook Exchange setup.", "Castle and complete development with no loose pieces."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-18-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 18: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "b4", "a5", "c3", "axb4", "cxb4", "Bd7", "Bxc6", "Bxc6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Develop with pressure and often provoke concessions like ...B{{square d7}} or ...Q{{square a5}}.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety.", "Support the {{pawn c5 full}} or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on {{square b4}}/{{square b5}} and open files on the queenside.", "Support {{square d4}} and prepare to recapture with a pawn, keeping central control.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Challenge the bishop and complete development while defending key squares.", "Trade to clarify structure and sometimes win time on development.", "Trade to clarify structure and sometimes win time on development."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-19-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 19: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "The Tartakower/Korchnoi variation. Black accepts doubled f-pawns in exchange for rapid development, a solid position, and the half-open e-file.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "c3", "Bd6", "Bd3", "O-O", "Qc2", "Re8+", "Ne2", "h5", "Be3", "Nd7", "O-O-O", "Nf8"],
    explanations: ["White claims the center.", "Caro-Kann. Prepare ...{{square d5}} without locking the bishop.", "White builds the big center.", "Challenge the center immediately.", "White develops and defends {{square e4}} with a knight.", "Trade! We remove White's central pawn.", "White recaptures, centralizing the knight.", "Develop and challenge the central knight right away.", "White decides to take, entering the Tartakower/Korchnoi variation.", "Recapture with the e-pawn! We accept doubled f-pawns because we get rapid development, the half-open e-file, and a rock-solid king position.", "White solidifies the center.", "Develop the bishop to its most active diagonal, pointing at White's kingside.", "White develops the bishop, eyeing our kingside.", "Castle! With the extra f-pawn cover, our king is very safe here.", "White sets up a battery, aiming at our h-pawn.", "Use the open e-file immediately with check, forcing White to respond.", "White blocks the check and develops the knight.", "Gain space on the kingside and prepare to challenge White's pieces.", "White develops the dark-squared bishop.", "Develop the queenside knight calmly. We're prioritizing solid coordination.", "White castles long, playing for activity but committing the king to the opposite side.", "Reroute the knight! The knight swings to {{square f8}} to defend the kingside and prepare to jump to {{square e6}} or {{square g6}}. A very standard Caro-Kann maneuver."]
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-20-e4-c6-d4-d5-exd5-cxd5-nf3-nf6",
    name: "Line 20: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nf3", "Nf6", "Bd3", "Bg4", "O-O", "Nc6", "c3", "e6", "h3", "Bh5", "Bg5", "Bd6", "Nbd2", "h6", "Bh4", "Qc7"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center and reach the easy Caro-Kann structure.", "White develops naturally and keeps options open.", "Develop the king knight first and keep {{square d5}} under control.", "White develops an active bishop toward the kingside.", "Get the bishop outside the chain before ...{{square e6}}.", "White castles and finishes the basic setup.", "Now the {{knight c6 full}} joins the structure and adds more control to {{square d4}} and {{square e5}}.", "White supports the center and keeps the setup compact.", "Only now support the center with ...{{square e6}} because the light-squared bishop is already active.", "White asks the bishop to decide, but Black does not have to rush the trade.", "Keep the bishop active and wait for a better moment to clarify the tension.", "White keeps the bishop outside the chain and looks toward the kingside.", "Put the dark-squared bishop on an active square and prepare simple castling.", "White improves coordination and keeps an eye on {{square e4}} and {{square c4}} ideas.", "Ask the bishop again and make White define the kingside structure.", "White keeps the bishop, but Black has made the kingside plan clearer.", "Support {{square e5}} and c-file ideas while connecting the rooks."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-21-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 21: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "Nf3", "Bg4", "Be3", "Nf5", "Bf2", "g5", "fxg5", "e6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Support {{square e5}} and grab kingside space, but can weaken {{square e4}} and king safety.", "Develop toward {{square f5}} without blocking the f-pawn; a common maneuver vs {{square f4}} structures.", "Develop and support {{square d4}} and {{square e5}}, also helps king safety.", "Pin the knight and increase pressure on {{square d4}} or {{square f3}}-based structures.", "Develop and often fight Q{{square b6}}/Q{{square a5}} pressure by covering key squares.", "Jump to an active square to hit {{square d4}}/{{square e3}}/{{square g3}} and pressure key pawns.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-22-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 22: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Nf3", "Bg4", "Bb5", "Qa5+", "Nc3", "e6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Develop and support {{square d4}} and {{square e5}}, also helps king safety.", "Pin the knight and increase pressure on {{square d4}} or {{square f3}}-based structures.", "Develop with pressure and often provoke concessions like ...B{{square d7}} or ...Q{{square a5}}.", "Pressure {{square c3}} and {{square e5}} and often win time by forcing a response. With check to force a reply and keep tempo.", "Develop, add central control, and support key pawn breaks.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety."],
  },
  {
    category: "Exchange Variation",
    id: "caro-kann-line-23-e4-c6-d4-d5-exd5-cxd5-nf3-nf6",
    name: "Line 23: e4 c6 d4 d5 exd5 cxd5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nf3", "Nf6", "Bd3", "Bg4", "O-O", "Nc6", "c3", "e6", "Bg5", "Be7", "Nbd2", "O-O", "Qc2", "h6", "Bh4", "Rc8"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White opens the position and heads for an Exchange structure.", "Recapture toward the center and reach the easy Caro-Kann structure.", "White develops naturally and keeps options open.", "Develop the king knight first and keep {{square d5}} under control.", "White develops an active bishop toward the kingside.", "Get the bishop outside the chain before ...{{square e6}}.", "White castles and finishes the basic setup.", "Now the {{knight c6 full}} joins the structure and adds more control to {{square d4}} and {{square e5}}.", "White supports the center and keeps the setup compact.", "Only now support the center with ...{{square e6}} because the light-squared bishop is already active.", "White pins and hopes to build kingside pressure.", "Finish development and prepare to castle before reacting to every threat.", "White improves coordination and keeps the attack ideas alive.", "Castle and make it clear that Black's position is fully coordinated.", "White centralizes the queen and eyes the kingside.", "Ask the bishop to decide and reduce some of White's attacking potential.", "White keeps the bishop, but gives Black a clear target for future tempi.", "Put the rook on the useful file before any center or queenside break."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-24-e4-c6-d4-d5-e5-c5-c3-nc6",
    name: "Line 24: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "cxd4", "cxd4", "Bg4", "Be2", "e6", "O-O", "Nge7", "Nc3", "Nf5", "Be3", "Be7", "h3", "Bxf3", "Bxf3", "O-O", "Rc1", "f6", "exf6", "Bxf6"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White reinforces {{square d4}} so the pawn chain keeps its shape.", "The knight's mission is simple: pile pressure on {{square d4}} and {{square e5}}.", "White develops another defender of the center.", "Clarify the center before White gets too comfortable.", "White keeps the broad center, but {{square d4}} is now the obvious base to attack.", "Bring the bishop out before ...{{square e6}} and pin the knight that helps hold the center together.", "White unpins and prepares to castle.", "Only now close the structure. Black got the bishop outside first, which is the whole point.", "Castle and connect the rooks before the next wave of pressure.", "When {{square f6}} is unavailable, the knight goes to {{square e7}} on the way to {{square f5}}.", "White adds another defender and hopes to keep the center intact.", "The whole reroute had a purpose: hit the bishop that props up White's center and add one more attacker to {{square d4}}.", "That bishop often has to babysit {{square d4}}, so White keeps it on the job.", "Finish development and keep the position ready for ...{{square f6}} later if needed.", "White asks whether the bishop really wants to stay on {{square g4}} any longer.", "Trade off a useful defender and reduce White's control over the dark squares.", "White keeps the structure clean, but the center has fewer defenders now.", "Castle and make the next break easier to calculate.", "Put the rook on the c-file where it can watch {{square c3}} and {{square c2}} ideas.", "Now Black goes after the center directly. Once the pieces are developed, the {{square e5}} pawn becomes the main target.", "White gives up the advanced pawn rather than lose it for nothing.", "Recapture with an active bishop and keep pressure on {{square d4}} and the kingside."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-25-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 25: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "Bxc6+", "bxc6", "b4", "a5", "c3", "axb4", "cxb4", "Qh4", "Bd2", "Qe4+", "Qe2", "Qxg2", "Qf3", "Qg6"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Develop with pressure and often provoke concessions like ...B{{square d7}} or ...Q{{square a5}}.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety.", "Trade to clarify structure and sometimes win time on development. With check to force a reply and keep tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Support the {{pawn c5 full}} or gain space. Usually costs development, so it must be justified.", "Hit the pawn chain on {{square b4}}/{{square b5}} and open files on the queenside.", "Support {{square d4}} and prepare to recapture with a pawn, keeping central control.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Force a response with check, gaining tempo to improve your attack or development.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Capture to change the pawn structure or remove a key defender. Make sure the recapture does not give the opponent tempo.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-26-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 26: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "f4", "Nh6", "Nf3", "Bg4", "Be2", "e6", "Be3", "Nf5"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the big pawn center Black is aiming at.", "Challenge the center immediately instead of copying it.", "White grabs space, but the advanced pawn can become a long-term target.", "This is the main Advance Variation break. Black goes after the center before White gets a free game.", "White wins a pawn for the moment, but gives Black a clear target and extra time.", "The {{knight c6 full}} piles pressure on {{square d4}} and {{square e5}}. In the Caro-Kann that job is very concrete.", "White reinforces {{square e5}}, but creates more dark-square and king-safety questions.", "Start the knight route toward {{square f5}}. In these Advance structures that knight often attacks the bishop that defends White's center.", "White develops another defender of the center.", "Bring the bishop out before ...{{square e6}} and pin the knight that helps hold the center together.", "White unpins and tries to keep the center organized.", "Only now support the structure and free the dark-squared bishop.", "White develops the bishop because that piece often has to help defend {{square d4}}.", "Land on {{square f5}} and attack the bishop that is trying to hold the center together."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-27-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 27: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "Nf3", "Bd6", "Bd3", "O-O", "O-O", "Re8", "h3", "Nd7", "c3", "Nf8"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White develops naturally and adds more central control.", "Clarify the center before White gets too comfortable.", "White keeps a piece in the center, but Black challenges it right away.", "Challenge the {{knight e4 full}} immediately. This is the simplest way to solve Black's space problem.", "White gives up the knight to damage the structure and enter the doubled-f-pawn line.", "Black accepts doubled pawns because the e-file opens, the pieces get free squares, and the king stays solid enough.", "White develops and prepares to castle against Black's active piece play.", "Develop naturally, point at {{square h2}}, and get ready to castle behind the extra f-pawn cover.", "White places the bishop on its most natural square.", "Castle and finish the easy part of development.", "White castles too, so Black can start using the open files.", "Use the open e-file at once and make White feel the awkward king placement.", "White asks the bishop to decide before expanding further.", "Reroute calmly. Black does not need to rush in this structure.", "White supports the center and keeps the position tidy.", "The knight tucks back into the kingside setup and keeps the position rock solid."],
  },
  {
    category: "Classical or Two Knights",
    id: "caro-kann-line-28-e4-c6-d4-d5-nc3-dxe4-nxe4-nf6",
    name: "Line 28: e4 c6 d4 d5 Nc3 dxe4 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "exf6", "c3", "Bd6", "Bd3", "O-O", "Qc2", "Re8+", "Ne2", "h5", "O-O", "h4", "h3", "Nd7", "Be3", "Nf8"],
    explanations: ["White starts with pawn to {{square e4}} and claims central space.", "Let's learn the Caro-Kann Defense! When White plays {{square e4}}, answer with pawn to {{square c6}} and prepare a solid counter in the center.", "White builds the center Black is about to challenge.", "Challenge the center immediately instead of copying it.", "White develops naturally and adds more central control.", "Clarify the center before White gets too comfortable.", "White keeps a piece in the center, but Black challenges it right away.", "Challenge the {{knight e4 full}} immediately. This is the simplest way to solve Black's space problem.", "White gives up the knight to damage the structure and enter the doubled-f-pawn line.", "Black accepts doubled pawns because the e-file opens, the pieces get free squares, and the king stays solid enough.", "White supports the center and prepares the usual developing setup.", "Develop naturally, point at {{square h2}}, and get ready to castle behind the extra f-pawn cover.", "White places the bishop actively and keeps an eye on the kingside.", "Castle and finish the easy part of development.", "White lines up on the kingside and the e-file.", "Use the open e-file at once and make White answer before drifting into a slow setup.", "White reroutes to a safer square and keeps future {{square f4}} or {{square g3}} ideas alive.", "Gain space and set up ...{{square h4}} so White's kingside pieces have less room.", "White castles, but the kingside is already the area Black wants to squeeze.", "Drive the knight from {{square g3}} and claim more space.", "White asks the bishop to decide, but the structure is already under pressure.", "Reroute calmly and keep the kingside compact.", "White develops and hopes to hold the dark squares together.", "The knight tucks back into the kingside setup and keeps the position rock solid."],
  },
  {
    category: "Advance Variation",
    id: "caro-kann-line-29-e4-c6-d4-d5-e5-c5-dxc5-nc6",
    name: "Line 29: e4 c6 d4 d5 e5 c5 ...",
    description: "From your provided repertoire list. Explanations focus on plan, targets, and typical Caro-Kann ideas.",
    moves: ["e4", "c6", "d4", "d5", "e5", "c5", "dxc5", "Nc6", "Bb5", "e6", "Be3", "Ne7", "c3", "Nf5", "Bd4", "Bd7"],
    explanations: ["Claim space and open lines for the king bishop and queen.", "Prepare ...{{square d5}} while keeping the light-squared bishop free.", "Build a strong center and support {{square e4}}.", "Challenge the center immediately. The Caro-Kann is about pressure, not mirroring.", "Advance and gain space, but accept that the pawn can become a target.", "Hit White's center from the side. This is a main Caro-Kann break vs the Advance.", "Grab the pawn, but give Black development tempo and a clear target to win back.", "Develop and pressure {{square d4}} and {{square e5}}. Also supports ...{{square d4}} or ...{{square e5}} ideas in some lines.", "Develop with pressure and often provoke concessions like ...B{{square d7}} or ...Q{{square a5}}.", "Support ...{{square d5}} or ...{{square c5}} structure, open the dark bishop, and prepare king safety.", "Develop and often fight Q{{square b6}}/Q{{square a5}} pressure by covering key squares.", "Black improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Support {{square d4}} and prepare to recapture with a pawn, keeping central control.", "Jump to an active square to hit {{square d4}}/{{square e3}}/{{square g3}} and pressure key pawns.", "White improves piece placement or pawn structure. The point is to support the current plan without conceding tempo.", "Challenge the bishop and complete development while defending key squares."],
  },
]);