import { withOpeningFeedback } from "./feedback";

export const danishGambitLines = withOpeningFeedback([
  {
    category: "Danish Gambit",
    id: "danishGambit-01-2e86f944",
    name: "Classic Qb3 pressure and bishop pair attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "O-O",
      "Qxb4"
    ],
    explanations: [
      "Let's learn the Danish Gambit! Start with pawn to {{square e4}} and get ready to trade material for fast development and open lines.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "{{square c3}} offers another pawn on purpose. The transcript's point is simple: keep opening lines until Black's extra material stops mattering.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Develop B{{square c4}} and point straight at {{square f7}}. In the Danish, this bishop plus the queen create the attack before Black finishes development.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Bx{{square b2}} restores the bishop pair. This is the real Danish compensation: both bishops get long open diagonals and Black still has loose pieces and an exposed king side.",
      "B{{square b4}}+ is Black's bishop attack from the transcript. The check looks annoying, but White can block, keep developing, and stay on the attack.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "Q{{square b3}} is the standard Danish pressure move. You hit {{square f7}} and {{square b7}} at the same time and force Black to answer threats instead of untangling.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Take on {{square b4}} once the bishop is loose. You have recovered a key piece and kept the bishop pair and initiative."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-02-3475f07f",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Qe7",
      "Ne2",
      "Qxe4",
      "Qb3",
      "Bxc3+",
      "Bxc3",
      "Qg6",
      "O-O"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black moves the queen to {{square e7}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White places the {{knight e2 full}} to improve central influence and set up the next tactic or break.",
      "Black captures on {{square e4}} with the queen, usually removing a key defender or converting initiative into material.",
      "White plays Q{{square b3}}, immediately threatening {{square f7}} and {{square b7}} and forcing Black to spend a move on defense instead of consolidating.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square c3}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black moves the queen to {{square g6}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-03-96879586",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "dxc4",
      "Qxd8+",
      "Kxd8",
      "fxg7",
      "Bxg7",
      "Bxg7",
      "Rg8",
      "Bf6+"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square d5}} to claim space and define which files and diagonals will open.",
      "White captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square c4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on {{square d8}} with the king, usually removing a key defender or converting initiative into material.",
      "White captures on {{square g7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square g7}} with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on {{square g7}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to {{square g8}} to pressure an open file created by earlier trades.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-04-7f279b20",
    name: "Nh5 blunder punished",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Nh5",
      "Qxh5"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "{{square e5}} is the standard Danish reaction to ...N{{square f6}}. You gain time, push the knight around, and keep the attack flowing before Black can consolidate.",
      "N{{square h5}} is the kind of greedy move the transcript warns about. Black tries to hold material and forgets basic piece safety.",
      "Qx{{square h5}} wins the knight cleanly. This is one of the easiest Danish punishments to remember: kick the knight, then take it when it lands badly."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-05-83afba8b",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "Bxc3+",
      "Qxc3",
      "O-O",
      "Nf3",
      "Nc6",
      "O-O",
      "Nxe4",
      "Qxg7#"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "B{{square b4}}+ is the bishop check line from the transcript. Black uses the check to gain time, but White can keep developing without giving up the attack.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "Q{{square b3}} is the classic Danish pressure move. You hit {{square f7}} and {{square b7}} at once and keep Black reacting instead of coordinating.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square c3}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "White develops N{{square f3}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Nx{{square e4}} looks like a double attack, but Black is ignoring the mating threat on {{square g7}}.",
      "Qx{{square g7}}# is the point. Black got distracted by material and forgot that the {{bishop c4 full}} and {{queen c3 full}} already built a mating net."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-06-b53511b0",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Qe7",
      "Qe2",
      "Ng8",
      "Nc3",
      "Nc6",
      "Nd5",
      "Qd8",
      "Nf6+",
      "gxf6",
      "exf6+",
      "Nge7",
      "fxe7",
      "Qxe7",
      "Bxh8"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black moves the queen to {{square e7}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White uses Q{{square e2}} to defend {{square e4}} and challenge the central knight; it often aims for a queen trade to calm the position.",
      "Black places the {{knight g8 full}} to improve central influence and set up the next tactic or break.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White places the {{knight d5 full}} to improve central influence and set up the next tactic or break.",
      "Black moves the queen to {{square d8}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check to keep the initiative.",
      "Black places the knight on ge7 to improve central influence and set up the next tactic or break.",
      "White captures on {{square e7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square e7}} with the queen, usually removing a key defender or converting initiative into material.",
      "White captures on {{square h8}} with the bishop, usually removing a key defender or converting initiative into material."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-07-ac8243ff",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "Bb4+",
      "Bc3",
      "Bxc3+",
      "Nxc3",
      "dxc4",
      "fxg7",
      "Qxd1+",
      "Rxd1",
      "Rg8",
      "Nd5",
      "Na6",
      "Nf6+",
      "Ke7",
      "Nxg8+"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square d5}} to claim space and define which files and diagonals will open.",
      "White captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White develops the bishop to {{square c3}}, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square c3}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square c4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square g7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on {{square d1}} with the rook, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to {{square g8}} to pressure an open file created by earlier trades.",
      "White places the {{knight d5 full}} to improve central influence and set up the next tactic or break.",
      "Black places the {{knight a6 full}} to improve central influence and set up the next tactic or break.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black moves the king to {{square e7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-08-6df9b32d",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Qe7",
      "Qe2",
      "Ng8",
      "Nc3",
      "Nc6",
      "Nd5",
      "Qd8",
      "Nf6+",
      "gxf6",
      "exf6+",
      "Be7",
      "fxe7",
      "Qxe7",
      "Bxh8"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black moves the queen to {{square e7}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White uses Q{{square e2}} to defend {{square e4}} and challenge the central knight; it often aims for a queen trade to calm the position.",
      "Black places the {{knight g8 full}} to improve central influence and set up the next tactic or break.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White places the {{knight d5 full}} to improve central influence and set up the next tactic or break.",
      "Black moves the queen to {{square d8}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check to keep the initiative.",
      "Black develops the bishop to {{square e7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on {{square e7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square e7}} with the queen, usually removing a key defender or converting initiative into material.",
      "White captures on {{square h8}} with the bishop, usually removing a key defender or converting initiative into material."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-09-3092f768",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "Bb4+",
      "Bc3",
      "Bxc3+",
      "Nxc3",
      "dxc4",
      "fxg7",
      "Qxd1+",
      "Rxd1",
      "Rg8",
      "Nd5",
      "Rxg7",
      "Nxc7+"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square d5}} to claim space and define which files and diagonals will open.",
      "White captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White develops the bishop to {{square c3}}, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square c3}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square c4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square g7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on {{square d1}} with the rook, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to {{square g8}} to pressure an open file created by earlier trades.",
      "White places the {{knight d5 full}} to improve central influence and set up the next tactic or break.",
      "Black captures on {{square g7}} with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-10-98435a68",
    name: "Declined with 3...Nc6 met by d5",
    description: "If Black avoids the accepted gambit structure too early, White can still grab space and keep a comfortable game.",
    moves: [
      "e4",
      "e5",
      "d4",
      "Nc6",
      "d5",
      "Nce7",
      "Nf3"
    ],
    explanations: [
      "Take the center immediately and force Black to answer your pawn wedge.",
      "Black mirrors the center and keeps open-game development options.",
      "Strike at once. The Danish move order is designed to make Black solve central problems before development feels easy.",
      "Black chooses 3...N{{square c6}} instead of taking on {{square d4}}, but that lets White gain space for free.",
      "{{square d5}} kicks the knight and claims more room. This is the simple practical answer the transcript recommends against an early ...N{{square c6}}.",
      "The knight has to retreat and Black has already lost time.",
      "Develop normally. White keeps the space edge and can continue with a normal open-game setup."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-11-1246322f",
    name: "Declined: calm development",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "d3",
      "Bxd3"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black pushes a pawn to {{square d3}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on {{square d3}} with the bishop, usually removing a key defender or converting initiative into material."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-12-4b9ddeec",
    name: "Central challenge with ...d5",
    description: "When Black hits the center instead of grabbing both pawns, White keeps a sound open-game structure and develops normally.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "d5",
      "exd5",
      "Qxd5",
      "cxd4",
      "Nc6",
      "Nf3"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black chooses the central counter with ...{{square d5}} instead of taking on {{square c3}}. The point is to give one pawn back and free development.",
      "White captures on {{square d5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square d5}} with the queen, usually removing a key defender or converting initiative into material.",
      "cx{{square d4}} restores a healthy center. If Black avoids the full gambit, White is still fine with a normal development lead.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "Develop and keep things simple. This no longer has the full Danish attack, but White still gets easy piece play."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-13-061d1c4d",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "d5",
      "Bxd5",
      "Nf6",
      "Bxf7+",
      "Kxf7",
      "Qxd8",
      "Bb4+",
      "Qd2",
      "Bxd2+",
      "Nxd2"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black advances a central pawn to {{square d5}} to claim space and define which files and diagonals will open.",
      "White captures on {{square d5}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on {{square f7}} with the king, usually removing a key defender or converting initiative into material.",
      "White captures on {{square d8}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the queen to {{square d2}} with a concrete task, either defending a pawn or creating a direct threat.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square d2}} with the knight, usually removing a key defender or converting initiative into material."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-14-7fb17400",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "dxc4",
      "Qxd8+",
      "Kxd8",
      "fxg7",
      "Bb4+",
      "Nc3",
      "Rg8",
      "O-O-O+",
      "Bd7",
      "Nd5"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square d5}} to claim space and define which files and diagonals will open.",
      "White captures on {{square f6}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square c4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on {{square d8}} with the king, usually removing a key defender or converting initiative into material.",
      "White captures on {{square g7}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black activates a rook to {{square g8}} to pressure an open file created by earlier trades.",
      "White gives check to keep the initiative.",
      "Black develops the bishop to {{square d7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the {{knight d5 full}} to improve central influence and set up the next tactic or break."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-15-ae402429",
    name: "Qb3 pressure with Rfe1 follow-up",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "Bxc3+",
      "Qxc3",
      "O-O",
      "Nf3",
      "Nc6",
      "O-O",
      "d6",
      "Rfe1"
    ],
    explanations: [
      "White advances a central pawn to {{square e4}} to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "White plays {{square d4}}, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on {{square d4}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays {{square c3}} to undermine the {{pawn d4 full}} and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on {{square c3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on {{square b2}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square b2}} with the bishop, usually removing a key defender or converting initiative into material.",
      "B{{square b4}}+ is the bishop attack from the transcript. The check is annoying, but White can block, finish development, and keep the initiative.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "Q{{square b3}} keeps the usual Danish pressure on {{square f7}} and {{square b7}} and makes Black solve threats before improving the position.",
      "Bx{{square c3}}+ gives up the checking bishop for White's knight. In an open game, White is usually happy to keep both bishops and recapture with the queen.",
      "White captures on {{square c3}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "White develops N{{square f3}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "...{{square d6}} is a solid defensive move, but it also gives White one more tempo to pile up pressure before Black is fully coordinated.",
      "Rf{{square e1}} keeps attacking instead of cashing out. The rook joins the e-file, supports {{square e5}} ideas, and makes it harder for Black to coordinate."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-16-3e4a1c9b",
    name: "Nf6 trap with Bxf7 and Qd5",
    description: "Punish ...Nf6 and ...Ne4 by exposing the king, hitting the loose knight, and recovering the pawn with initiative.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Ne4",
      "Bxf7+",
      "Kxf7",
      "Qd5+",
      "Ke8",
      "Qxe4"
    ],
    explanations: [
      "Open the center immediately. In the Danish you give material for speed and open diagonals.",
      "Black meets the center in classical style.",
      "Offer central contact right away so the position opens before Black can coordinate.",
      "Black accepts and opens files, which is exactly what the gambit is built for.",
      "Offer the second pawn too. White wants lines, not a quiet pawn structure.",
      "Black grabs again and stays material up, but development still lags badly.",
      "Develop to {{square c4}} and aim directly at {{square f7}}, the usual tactical focal point.",
      "Black takes the b-pawn, but now both bishops get long open diagonals.",
      "Recapture with the bishop and keep the bishop pair alive. This is the core Danish compensation.",
      "Black develops the knight and wants to castle, but that piece becomes the target.",
      "{{square e5}} gains time and kicks the knight. This is the standard reaction when Black brings the knight to {{square f6}} too early.",
      "N{{square e4}} looks active, but this is exactly the kind of knight jump the Danish wants to punish.",
      "Bx{{square f7}}+ is the standard Danish sacrifice here. You drag the king forward so the queen can hit both the king and the loose knight.",
      "Black has to take, and now the king has lost castling rights.",
      "Q{{square d5}}+ is the tactical point. It checks the king and attacks the {{knight e4 full}} at the same time.",
      "Black steps back, but the knight is still loose.",
      "Qx{{square e4}} wins the knight back and leaves Black with the worse king and worse coordination. That is the Danish trade: activity first, material later."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-17-91f2c6ad",
    name: "Bb4+ main line with en passant promotion idea",
    description: "Use Nbd2, the Bxf7 sacrifice, the en passant check, and the passed c-pawn to blow open Black's position.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nd2",
      "Nf6",
      "e5",
      "Ne4",
      "Bxf7+",
      "Kxf7",
      "Qb3+",
      "d5",
      "exd6+",
      "Be6",
      "Qxb4",
      "Nxd2",
      "Qf4+",
      "Kg8",
      "dxc7",
      "Qe8",
      "Qe5",
      "Qf7",
      "cxb8=Q+"
    ],
    explanations: [
      "Take the center and force the game open at once.",
      "Black answers classically and keeps the e-pawn protected.",
      "Challenge the center before Black develops comfortably.",
      "Black accepts and opens the position, which is what White wants.",
      "Offer the next pawn to keep opening lines.",
      "Black takes again and stays greedy.",
      "Develop with pressure on {{square f7}}. The bishop is the spearhead of the Danish attack.",
      "Black takes the second pawn too, but now both bishops become extremely strong.",
      "Recover the bishop and keep every diagonal open toward Black's king side.",
      "B{{square b4}}+ is the main bishop check setup. Black tries to gain time with the check and slow White's attack before the center blows open.",
      "N{{square d2}} is the clean block. You meet the bishop attack without giving up momentum and keep your pieces ready for the next wave.",
      "Black develops and hopes to castle next.",
      "{{square e5}} gains time and starts the attack before Black can finish coordinating.",
      "N{{square e4}} attacks the pinned knight and looks clever, but it misses the standard sacrifice.",
      "Bx{{square f7}}+ drags the king forward and removes the defender of {{square e4}} tactics.",
      "Black takes, but now the king is stuck in the center.",
      "Q{{square b3}}+ attacks the king and the {{bishop b4 full}} at the same time.",
      "Black tries to close the position with ...{{square d5}} and save the bishop.",
      "ex{{square d6}}+ is the key resource. The en passant check keeps the king exposed and opens even more lines for the attack.",
      "Black blocks the check and attacks the queen, but the {{bishop b4 full}} is still loose.",
      "Qx{{square b4}} wins the checking bishop back. White is still attacking, and Black still has not solved the king problem.",
      "Black grabs on {{square d2}} and hopes White will finally slow down.",
      "Q{{square f4}}+ is the stronger move. The queen swings to the king side and keeps the initiative instead of recapturing immediately.",
      "Black runs to {{square g8}}, but the position is still collapsing.",
      "dx{{square c7}} creates a dangerous passed pawn with tempo. The c-pawn now attacks major pieces and promotion squares.",
      "Black tries to keep control of the back rank and the {{knight b8 full}}.",
      "Q{{square e5}} builds the long-diagonal battery and threatens to crash through on {{square g7}}.",
      "Black defends as best as possible, but the {{knight b8 full}} is no longer protected enough.",
      "cx{{square b8}}=Q+ is the payoff. The passed pawn queens with check, and the attack turns into decisive material."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-18-4b8d2f71",
    name: "d6 setup punished with Qb3 and Ng5",
    description: "When Black uses ...d6 to stop e5, White can switch to direct pressure on e6 and f7.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "d6",
      "Nf3",
      "Be6",
      "Bxe6",
      "fxe6",
      "Qb3",
      "Qc8",
      "Ng5",
      "Ke7",
      "Nxe6",
      "Qxe6",
      "Qxb7"
    ],
    explanations: [
      "Claim the center and prepare to open lines quickly.",
      "Black answers in classical fashion.",
      "Challenge the center immediately. Danish positions work best when files open early.",
      "Black accepts and opens the game.",
      "Offer the second pawn for activity.",
      "Black takes it and stays two pawns up for the moment.",
      "Develop with immediate pressure on {{square f7}}.",
      "Black stays greedy, but now White's bishops get both long diagonals.",
      "Recover the bishop and keep the attacking setup intact.",
      "...{{square d6}} tries to stop {{square e5}} and make Black's development safer.",
      "Develop normally. White does not need to force {{square e5}} if there is a more direct attack.",
      "Black tries to neutralize the {{square c4}} bishop by exchanging it.",
      "Trade on {{square e6}} to damage Black's structure and create a fixed pawn target.",
      "Black recaptures, but the {{square e6}} pawn becomes weak and the dark squares open up.",
      "Q{{square b3}} is the key switch. It attacks both {{square f7}} and {{square e6}} and forces Black into passive defense.",
      "Q{{square c8}} is Black's awkward way to defend both targets at once.",
      "N{{square g5}} increases the pressure on {{square f7}} and {{square e6}} and makes the king uncomfortable.",
      "Black steps into the center because castling is no longer realistic.",
      "Nx{{square e6}} wins the damaged pawn and keeps the king exposed.",
      "Black recaptures, but now the b-pawn is loose and the queen side remains undeveloped.",
      "Qx{{square b7}} picks up another pawn and threatens the rook. White is better because Black never solved the king-safety problem."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-19-a7c5e3d2",
    name: "Nc6 and ...Bb4 met by Nd5 and Qg4",
    description: "Against the more theoretical ...Nc6 setup, White shifts from Bxf7 tricks to direct pressure with Nd5, Qd4, and Qg4.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nc6",
      "Nf3",
      "Bb4+",
      "Nc3",
      "Nf6",
      "O-O",
      "O-O",
      "Nd5",
      "Nxd5",
      "exd5",
      "Ne7",
      "Qd4",
      "Nf5",
      "Qg4",
      "d6",
      "Bd3"
    ],
    explanations: [
      "Open the center and invite the accepted Danish structure.",
      "Black claims the center and waits to see whether White will really gambit.",
      "Challenge the center right away.",
      "Black takes and opens the game.",
      "Offer the c-pawn too. The whole point is rapid development and open lines.",
      "Black accepts and keeps grabbing material.",
      "Develop with pressure on {{square f7}} and keep the bishops active.",
      "Black takes the second pawn, but that leaves White with full diagonals for both bishops.",
      "Recapture on {{square b2}} and restore the bishop pair.",
      "...N{{square c6}} is a more careful setup. The {{bishop b4 full}} will be defended later, so White should not rely on the old Bx{{square f7}} and Q{{square b3}} trick.",
      "Develop naturally and prepare to castle. White still wants speed first.",
      "Black checks and tries to build a more solid defensive shell.",
      "N{{square c3}} blocks the check and keeps the pieces flowing toward the center.",
      "Black develops and aims to finish castling.",
      "Castle first. King safety matters because White is about to open more lines.",
      "Black also castles, hoping the extra pawns will now count.",
      "N{{square d5}} is the real point of this setup. The knight jumps into a strong outpost and hits {{square c7}} and {{square f6}} ideas.",
      "Black trades it off to avoid immediate tactical threats.",
      "ex{{square d5}} gains a tempo by attacking the {{knight c6 full}} and opens more central lines.",
      "Black retreats, but White gets to keep the initiative.",
      "Q{{square d4}} creates a dangerous battery with the bishop and keeps pressure on {{square g7}} and {{square d6}} squares.",
      "Black attacks the queen and tries to cover the weak points.",
      "Q{{square g4}} keeps all the threats. White attacks {{square g7}} and the {{knight f5 full}} at the same time.",
      "Black tries to hold the position together with ...{{square d6}}.",
      "B{{square d3}} adds one more attacker. White now threatens the knight, the {{bishop b4 full}}, and mate ideas on {{square g7}}."
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-20-5d1f8b34",
    name: "d5 and ...c6 blunder loses the queen",
    description: "The immediate ...c6 chase looks natural, but Bxf7+ and Qxd8 punish it on the spot.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "d5",
      "Bxd5",
      "c6",
      "Bxf7+",
      "Kxf7",
      "Qxd8"
    ],
    explanations: [
      "Open the center and head for active piece play.",
      "Black mirrors the center.",
      "Strike before Black can complete development.",
      "Black accepts and opens the game.",
      "Offer the next pawn to keep lines opening.",
      "Black takes again and stays material up for the moment.",
      "Develop with immediate pressure on {{square f7}}.",
      "Black grabs the b-pawn too, leaving White with open diagonals for both bishops.",
      "Bx{{square b2}} restores the bishop pair and keeps every tactical idea alive.",
      "...{{square d5}} is one of Black's more serious attempts to return material and free development.",
      "Bx{{square d5}} keeps the bishop active and continues to point toward {{square f7}}.",
      "...{{square c6}} looks natural because it hits the bishop and seems to force a queen trade soon.",
      "Bx{{square f7}}+ is the tactical refutation. The king is dragged away from the {{queen d8 full}}.",
      "Black has to take, otherwise the queen still falls after more checks.",
      "Qx{{square d8}} wins the queen cleanly. This is the exact punishment the transcript highlights against the premature ...{{square c6}} chase."
    ]
  }
]);
