import { withOpeningFeedback } from "./feedback";

export const danishGambitLines = withOpeningFeedback([
  {
    category: "Danish Gambit",
    id: "danishGambit-01-2e86f944",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "O-O",
      "Qxb4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White plays Qb3, immediately threatening f7 and b7 and forcing Black to spend a move on defense instead of consolidating.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "White captures on b4 with the queen, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-02-3475f07f",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Qe7",
      "Ne2",
      "Qxe4",
      "Qb3",
      "Bxc3+",
      "Bxc3",
      "Qg6",
      "O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black moves the queen to e7 with a concrete task, either defending a pawn or creating a direct threat.",
      "White places the knight on e2 to improve central influence and set up the next tactic or break.",
      "Black captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "White plays Qb3, immediately threatening f7 and b7 and forcing Black to spend a move on defense instead of consolidating.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on c3 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black moves the queen to g6 with a concrete task, either defending a pawn or creating a direct threat.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-03-96879586",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "dxc4",
      "Qxd8+",
      "Kxd8",
      "fxg7",
      "Bxg7",
      "Bxg7",
      "Rg8",
      "Bf6+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on c4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on d8 with the king, usually removing a key defender or converting initiative into material.",
      "White captures on g7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on g7 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on g7 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to g8 to pressure an open file created by earlier trades.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-04-7f279b20",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Nh5",
      "Qxh5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black places the knight on h5 to improve central influence and set up the next tactic or break.",
      "White captures on h5 with the queen, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-05-83afba8b",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "Bxc3+",
      "Qxc3",
      "O-O",
      "Nf3",
      "Nc6",
      "O-O",
      "Nxe4",
      "Qxg7#"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White plays Qb3, immediately threatening f7 and b7 and forcing Black to spend a move on defense instead of consolidating.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on c3 with the queen, usually removing a key defender or converting initiative into material.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White gives checkmate with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-06-b53511b0",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Qe7",
      "Qe2",
      "Ng8",
      "Nc3",
      "Nc6",
      "Nd5",
      "Qd8",
      "Nf6+",
      "gxf6",
      "exf6+",
      "Nge7",
      "fxe7",
      "Qxe7",
      "Bxh8"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black moves the queen to e7 with a concrete task, either defending a pawn or creating a direct threat.",
      "White uses Qe2 to defend e4 and challenge the central knight; it often aims for a queen trade to calm the position.",
      "Black places the knight on g8 to improve central influence and set up the next tactic or break.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White places the knight on d5 to improve central influence and set up the next tactic or break.",
      "Black moves the queen to d8 with a concrete task, either defending a pawn or creating a direct threat.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check to keep the initiative.",
      "Black places the knight on ge7 to improve central influence and set up the next tactic or break.",
      "White captures on e7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on e7 with the queen, usually removing a key defender or converting initiative into material.",
      "White captures on h8 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-07-ac8243ff",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "Bb4+",
      "Bc3",
      "Bxc3+",
      "Nxc3",
      "dxc4",
      "fxg7",
      "Qxd1+",
      "Rxd1",
      "Rg8",
      "Nd5",
      "Na6",
      "Nf6+",
      "Ke7",
      "Nxg8+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White develops the bishop to c3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on c3 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on c4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on g7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on d1 with the rook, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to g8 to pressure an open file created by earlier trades.",
      "White places the knight on d5 to improve central influence and set up the next tactic or break.",
      "Black places the knight on a6 to improve central influence and set up the next tactic or break.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-08-6df9b32d",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "Qe7",
      "Qe2",
      "Ng8",
      "Nc3",
      "Nc6",
      "Nd5",
      "Qd8",
      "Nf6+",
      "gxf6",
      "exf6+",
      "Be7",
      "fxe7",
      "Qxe7",
      "Bxh8"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black moves the queen to e7 with a concrete task, either defending a pawn or creating a direct threat.",
      "White uses Qe2 to defend e4 and challenge the central knight; it often aims for a queen trade to calm the position.",
      "Black places the knight on g8 to improve central influence and set up the next tactic or break.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White places the knight on d5 to improve central influence and set up the next tactic or break.",
      "Black moves the queen to d8 with a concrete task, either defending a pawn or creating a direct threat.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check to keep the initiative.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on e7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on e7 with the queen, usually removing a key defender or converting initiative into material.",
      "White captures on h8 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-09-3092f768",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "Bb4+",
      "Bc3",
      "Bxc3+",
      "Nxc3",
      "dxc4",
      "fxg7",
      "Qxd1+",
      "Rxd1",
      "Rg8",
      "Nd5",
      "Rxg7",
      "Nxc7+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White develops the bishop to c3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on c3 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on c4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on g7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on d1 with the rook, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to g8 to pressure an open file created by earlier trades.",
      "White places the knight on d5 to improve central influence and set up the next tactic or break.",
      "Black captures on g7 with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-10-98435a68",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "Nc6",
      "d5",
      "Nce7",
      "Nf3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "Black places the knight on ce7 to improve central influence and set up the next tactic or break.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-11-1246322f",
    name: "Declined: calm development",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "d3",
      "Bxd3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black pushes a pawn to d3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on d3 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-12-4b9ddeec",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "d5",
      "exd5",
      "Qxd5",
      "cxd4",
      "Nc6",
      "Nf3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on d5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on d5 with the queen, usually removing a key defender or converting initiative into material.",
      "White captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-13-061d1c4d",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "d5",
      "Bxd5",
      "Nf6",
      "Bxf7+",
      "Kxf7",
      "Qxd8",
      "Bb4+",
      "Qd2",
      "Bxd2+",
      "Nxd2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on d5 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on f7 with the king, usually removing a key defender or converting initiative into material.",
      "White captures on d8 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the queen to d2 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on d2 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-14-7fb17400",
    name: "Danish Gambit main line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Nf6",
      "e5",
      "d5",
      "exf6",
      "dxc4",
      "Qxd8+",
      "Kxd8",
      "fxg7",
      "Bb4+",
      "Nc3",
      "Rg8",
      "O-O-O+",
      "Bd7",
      "Nd5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to d5 to claim space and define which files and diagonals will open.",
      "White captures on f6 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on c4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on d8 with the king, usually removing a key defender or converting initiative into material.",
      "White captures on g7 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black activates a rook to g8 to pressure an open file created by earlier trades.",
      "White gives check to keep the initiative.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the knight on d5 to improve central influence and set up the next tactic or break."
    
    ]
  },
  {
    category: "Danish Gambit",
    id: "danishGambit-15-ae402429",
    name: "Classic Qb3 pressure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "d4",
      "exd4",
      "c3",
      "dxc3",
      "Bc4",
      "cxb2",
      "Bxb2",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Qb3",
      "Bxc3+",
      "Qxc3",
      "O-O",
      "Nf3",
      "Nc6",
      "O-O",
      "d6",
      "Rfe1"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays d4, offering central contact immediately; the whole gambit is built around opening the center for bishops.",
      "Black captures on d4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White plays c3 to undermine the pawn on d4 and open the c file; if Black takes, White gets rapid piece play.",
      "Black captures on c3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black captures on b2 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on b2 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White plays Qb3, immediately threatening f7 and b7 and forcing Black to spend a move on defense instead of consolidating.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on c3 with the queen, usually removing a key defender or converting initiative into material.",
      "Black castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black pushes a pawn to d6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White activates a rook to fe1 to pressure an open file created by earlier trades."
    
    ]
  }
]);
