export const englishOpeningLines = [
  {
    "category": "English Opening",
    "id": "english-01",
    "name": "Symmetrical Variation with Knight Attack",
    "description": "Early e4 push against Nf6",
    "moves": ["c4", "Nf6", "Nc3", "e6", "e4", "Bb4", "e5", "Bxc3", "bxc3", "Ne4", "Qg4", "Ng5", "h4"],
    "explanations": [
      "Let's learn the English Opening! Rather than immediately pushing our central pawns, we start with the flank pawn to c4. This flexible opening can transpose into many different structures.",
      "Black responds with the knight to f6, preparing to control the center and develop pieces.",
      "We develop our queenside knight, supporting the center and preparing to control key squares.",
      "Black plays e6, supporting a future d5 break and preparing bishop development.",
      "We strike in the center with e4, establishing a strong pawn presence and challenging Black's setup.",
      "Black pins our knight with Bb4, creating immediate tension and threatening to double our pawns.",
      "We push forward with e5, attacking the knight and gaining space in the center.",
      "Black captures on c3, accepting doubled pawns but damaging our queenside structure.",
      "We recapture with the b-pawn, maintaining material equality but accepting doubled pawns for active play.",
      "Black's knight moves to e4, occupying a central outpost and attacking our weakened pawn structure.",
      "We develop the queen aggressively to g4, attacking the g7 pawn and threatening the knight on e4.",
      "Black retreats the knight to g5, avoiding capture but moving to a less stable square.",
      "After the final move - Well done! We're winning that knight :D By pushing h4, we attack the knight on g5 which has limited retreat squares, forcing Black into difficult defensive choices."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-02",
    "name": "Reversed Sicilian with Knight Trade",
    "description": "Early central pawn exchange leading to knight misplacement",
    "moves": ["c4", "e5", "Nc3", "Nc6", "Nf3", "Bc5", "Nxe5", "Nxe5", "d4", "Nxc4", "dxc5"],
    "explanations": [
      "We begin with the English Opening, starting with our flank pawn to c4.",
      "Black responds with e5, establishing a symmetrical pawn structure.",
      "We develop our queenside knight, preparing to control the center.",
      "Black develops the knight to c6, mirroring our development.",
      "We develop the kingside knight, putting immediate pressure on the e5 pawn.",
      "Black develops the bishop to c5, controlling the center and preparing kingside castling.",
      "We capture on e5, initiating central exchanges and testing Black's position.",
      "Black recaptures with the knight, maintaining material equality.",
      "We push d4, challenging Black's center and opening lines for our pieces.",
      "Black captures our knight on c4, winning material but placing the knight on an unstable square.",
      "After the final move - Nice! Even though material is equal, black's knight is so misplaced that the computer gives us a +2 point advantage. By capturing on c5, we regain our pawn and leave Black's knight stranded on c4 with no retreat."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-03",
    "name": "Botvinnik System with Bishop Win",
    "description": "Knight maneuver wins bishop",
    "moves": ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "e3", "Bb4", "Qc2", "d6", "Nd5", "Nxd5", "cxd5", "Ne7", "Qa4+", "Bd7", "Qxb4"],
    "explanations": [
      "We open with the English, playing c4 to control the center from the flank.",
      "Black responds with e5, establishing a classical center.",
      "We develop the queenside knight, preparing for central control.",
      "Black develops the knight to f6, attacking the center and preparing castling.",
      "We develop the kingside knight, increasing central pressure.",
      "Black develops the other knight to c6, completing knight development.",
      "We play e3, supporting the center and preparing bishop development.",
      "Black pins our knight with Bb4, creating tactical possibilities.",
      "We develop the queen to c2, supporting the center and preparing queenside play.",
      "Black supports the e5 pawn with d6, maintaining the central structure.",
      "We move the knight to d5, challenging Black's pieces and creating threats.",
      "Black captures our knight, simplifying the position.",
      "We recapture with the pawn, gaining central control and opening the c-file.",
      "Black retreats the knight to e7, preparing to regroup.",
      "We check with the queen, developing with tempo and attacking the bishop.",
      "Black blocks with the bishop, defending while developing.",
      "After the final move -  You just won yourself a free bishop :D By capturing on b4, we win a piece for free as the bishop has no safe retreat."
    ]
  },
  {
    "category": " English Opening",
    "id": "english-04",
    "name": "Queen's Gambit Declined Structure",
    "description": "Early d5 exchange leads to development advantage",
    "moves": ["c4", "d5", "cxd5", "Qxd5", "Nc3", "Qd8", "Nf3", "Nf6", "d4", "e6", "e4", "Bb4", "Bd3"],
    "explanations": [
      "We begin with the English Opening, playing c4 to control the center.",
      "Black immediately challenges with d5, entering Queen's Gambit Declined territory.",
      "We capture on d5, simplifying the center.",
      "Black recaptures with the queen, centralizing but potentially exposing it.",
      "We develop the knight with tempo against the queen.",
      "Black retreats the queen to d8, avoiding further harassment.",
      "We develop the kingside knight, completing our knight development.",
      "Black develops the knight to f6, attacking the center.",
      "We establish a strong pawn center with d4.",
      "Black plays e6, supporting the center and preparing bishop development.",
      "We push e4, establishing a powerful pawn duo in the center.",
      "Black pins our knight with Bb4, creating tactical tension.",
      "After the final move - Our development and our center are soooo much better than black's. Even with equal material, the computer is giving us a +1.3 point advantage. By developing the bishop to d3, we complete our development with a strong piece eyeing the kingside."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-05",
    "name": "Kingside Attack Variation",
    "description": "Early e5 push attacks knight",
    "moves": ["c4", "Nf6", "Nc3", "e6", "e4", "Bb4", "e5", "Ng8", "Qg4"],
    "explanations": [
      "We start with the English Opening, playing c4 to control the center from the flank.",
      "Black develops the knight to f6, attacking the center.",
      "We develop the queenside knight, preparing for central expansion.",
      "Black plays e6, preparing d5 and bishop development.",
      "We strike in the center with e4, establishing a strong presence.",
      "Black pins our knight with Bb4, creating immediate tension.",
      "We push e5, attacking the knight and gaining space.",
      "Black retreats the knight all the way to g8, losing considerable time.",
      "After the final move - Beautiful! Black has a few ways to save the g7 pawn, but they all come at a cost of pawn structure or development. The computer loves our position so much that we get a +1.3 point advantage. By playing Qg4, we attack the vulnerable g7 pawn and maintain strong initiative."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-06",
    "name": "Central Break with Space Advantage",
    "description": "Complex pawn exchange leads to space advantage",
    "moves": ["c4", "Nf6", "Nc3", "e6", "e4", "d5", "e5", "Nfd7", "cxd5", "Nxe5", "d4", "Ng6", "dxe6", "Bxe6", "d5"],
    "explanations": [
      "We open with the English, playing c4 to control central squares.",
      "Black develops the knight to f6, preparing for central play.",
      "We develop the queenside knight, supporting the center.",
      "Black plays e6, preparing the d5 break.",
      "We establish a strong center with e4.",
      "Black challenges immediately with d5.",
      "We push e5, gaining space and attacking the knight.",
      "Black retreats the knight to d7, maintaining defense of e5.",
      "We capture on d5, opening the center.",
      "Black captures on e5 with the knight, winning a pawn.",
      "We push d4, attacking the knight and regaining initiative.",
      "Black retreats the knight to g6, avoiding capture.",
      "We capture on e6, opening the position and damaging Black's pawn structure.",
      "Black recaptures with the bishop, developing a piece.",
      "After the final move - Nice!! We have a solid space advantage over black. The eval bar says +0.8 for us. By pushing d5, we gain space, attack the bishop, and establish a strong passed pawn."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-07",
    "name": "Dutch Defense Reversed",
    "description": "Against f5 setup",
    "moves": ["c4", "e5", "Nc3", "f5", "d4", "e4", "Bf4", "Nf6", "e3"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black responds with e5, establishing a classical center.",
      "We develop the queenside knight.",
      "Black plays f5, adopting a Dutch Defense style setup.",
      "We strike in the center with d4, challenging Black's structure.",
      "Black pushes e4, gaining space but locking the position.",
      "We develop the bishop to f4, controlling key squares and preparing development.",
      "Black develops the knight to f6, completing kingside development.",
      "After the final move - Nice! Our center is stronger and we have more development than black. The computer gives us a +1 point advantage. By playing e3, we support our center, prepare bishop development, and maintain a solid position."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-08",
    "name": "Bishop Pair Advantage",
    "description": "Knight maneuver wins bishop pair",
    "moves": ["c4", "e5", "Nc3", "Bb4", "Nd5", "Bc5", "e3", "c6", "d4", "cxd5", "dxc5"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black pins our knight with Bb4.",
      "We move the knight to d5, challenging Black's position.",
      "Black retreats the bishop to c5, maintaining the pin.",
      "We play e3, supporting the center and preparing development.",
      "Black challenges our knight with c6.",
      "We push d4, attacking the bishop and opening the center.",
      "Black captures our knight, simplifying the position.",
      "After the final move - Well done! Our bishop pair gives us a +1 eval advantage. By capturing on c5, we win the bishop pair and establish a strong positional advantage."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-09",
    "name": "Central Pawn Majority",
    "description": "Early pawn exchange leads to central control",
    "moves": ["c4", "e5", "Nc3", "Bc5", "e3", "Nf6", "d4", "exd4", "exd4"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black develops the bishop to c5.",
      "We play e3, preparing central expansion.",
      "Black develops the knight to f6.",
      "We push d4, challenging the center.",
      "Black captures on d4.",
      "After the final move - Well done! Now we have 2 pawns in the center while black has 0 - and they also have to spend a turn moving their bishop. By recapturing with the pawn, we establish a strong central pawn majority."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-10",
    "name": "King's Indian Reversed",
    "description": "Symmetrical fianchetto setup",
    "moves": ["c4", "Nf6", "Nc3", "g6", "g3", "Bg7", "Bg2", "O-O", "d4", "d6", "Nf3", "Nbd7", "O-O"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black develops the knight to f6.",
      "We develop the queenside knight.",
      "Black plays g6, preparing a fianchetto.",
      "We play g3, preparing our own fianchetto.",
      "Black completes the fianchetto with Bg7.",
      "We complete our fianchetto with Bg2.",
      "Black castles kingside.",
      "We establish a central presence with d4.",
      "Black supports the center with d6.",
      "We develop the kingside knight.",
      "Black develops the queenside knight.",
      "After the final move - Well done!! We are slightly ahead in evaluation and winrate. By castling, we complete our development and secure our king."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-11",
    "name": "Symmetrical Fianchetto System",
    "description": "Complete symmetrical development",
    "moves": ["c4", "g6", "Nc3", "Bg7", "g3", "d6", "Bg2", "Nf6", "Nf3", "O-O", "O-O"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black plays g6, preparing a fianchetto setup.",
      "We develop the queenside knight.",
      "Black completes the fianchetto with Bg7.",
      "We play g3, preparing our own fianchetto.",
      "Black supports the center with d6.",
      "We complete our fianchetto with Bg2.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black castles kingside.",
      "After the final move - Well done! That's what I like to see :) It's a symmetrical game, and you'll play on from here. By castling, we complete our development and prepare for middlegame play."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-12",
    "name": "Symmetrical English with d4 Break",
    "description": "Early d4 exchange in symmetrical position",
    "moves": ["c4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "Nf3", "Nf6", "d4", "cxd4", "Nxd4", "O-O", "O-O"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds symmetrically with c5.",
      "We develop the queenside knight.",
      "Black develops the knight to c6.",
      "We play g3, preparing a fianchetto.",
      "Black plays g6, mirroring our setup.",
      "We complete our fianchetto with Bg2.",
      "Black completes their fianchetto with Bg7.",
      "We develop the kingside knight.",
      "Black develops the knight to f6.",
      "We break symmetry with d4, challenging the center.",
      "Black captures on d4.",
      "We recapture with the knight, centralizing it.",
      "Black castles kingside.",
      "After the final move - That was... emotional. By castling, we complete our development and secure our king in a complex symmetrical position."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-13",
    "name": "Slav Defense Setup",
    "description": "Against c6 and d5 setup",
    "moves": ["c4", "c6", "Nf3", "d5", "e3", "Nf6", "Nc3", "Bg4", "Qb3", "Qb6", "Ne5"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black plays c6, preparing d5 in Slav Defense style.",
      "We develop the kingside knight.",
      "Black plays d5, challenging the center.",
      "We play e3, supporting the center and preparing development.",
      "Black develops the knight to f6.",
      "We develop the queenside knight.",
      "Black develops the bishop to g4, pinning our knight.",
      "We develop the queen to b3, attacking b7 and challenging the pin.",
      "Black develops the queen to b6, defending b7 and maintaining the pin.",
      "After the final move - Nice!! We got out of that sticky pin. And if black ever trades our queens, we're happy to open up the a-file for our rook. By playing Ne5, we attack the bishop and break the pin while occupying a strong central square."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-14",
    "name": "Four Knights System",
    "description": "Standard development against Bb4",
    "moves": ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "e3", "Bb4", "Qc2", "d6", "Nd5", "Bc5", "a3", "a5", "b3"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the other knight to c6.",
      "We play e3, preparing development.",
      "Black pins our knight with Bb4.",
      "We develop the queen to c2, preparing queenside play.",
      "Black supports the center with d6.",
      "We move the knight to d5, challenging Black's position.",
      "Black retreats the bishop to c5.",
      "We play a3, preventing ...Bb4 ideas and preparing queenside expansion.",
      "Black plays a5, preventing our b4 advance.",
      "After the final move - Well done! We'll plant our bishop on b2 next, and then play the game from there. By playing b3, we prepare to develop our bishop to b2 and maintain a solid position."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-15",
    "name": "King's Fianchetto Setup",
    "description": "Against Dutch-style f5",
    "moves": ["c4", "e5", "Nc3", "d6", "Nf3", "f5", "g3", "Nf6", "Bg2"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black supports the center with d6.",
      "We develop the kingside knight.",
      "Black plays f5, adopting a Dutch-style setup.",
      "We play g3, preparing a fianchetto.",
      "Black develops the knight to f6.",
      "After the final move - Well done! After a castle, we'll enjoy the rest of the game with an extremely strong bishop on g2. By completing our fianchetto, we establish a strong diagonal for our bishop."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-16",
    "name": "Tactical Exchange Variation",
    "description": "Complex pawn exchange leads to equality",
    "moves": ["c4", "Nf6", "Nc3", "e6", "e4", "d5", "e5", "d4", "exf6", "dxc3", "bxc3", "Qxf6", "Nf3"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black develops the knight to f6.",
      "We develop the queenside knight.",
      "Black plays e6, preparing d5.",
      "We establish a strong center with e4.",
      "Black challenges immediately with d5.",
      "We push e5, attacking the knight.",
      "Black pushes d4, attacking our knight.",
      "We capture the knight on f6.",
      "Black captures our knight on c3.",
      "We recapture with the b-pawn.",
      "Black recaptures the pawn on f6 with the queen.",
      "After the final move - Nice! Next, we'll develop our bishop to d3 and then castle. The position is about equal. By developing the knight to f3, we complete our knight development and prepare for castling."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-17",
    "name": "Queen's Pawn Game Transposition",
    "description": "Transposes to Queen's Pawn structure",
    "moves": ["c4", "e6", "Nc3", "d5", "e3", "Nf6", "Nf3", "Be7", "b3", "O-O", "Bb2", "c5", "cxd5", "exd5", "d4"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black plays e6, preparing d5.",
      "We develop the queenside knight.",
      "Black plays d5, challenging the center.",
      "We play e3, supporting the center.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the bishop to e7.",
      "We play b3, preparing a queenside fianchetto.",
      "Black castles kingside.",
      "We complete our fianchetto with Bb2.",
      "Black plays c5, challenging the center.",
      "We capture on d5.",
      "Black recaptures with the e-pawn.",
      "After the final move - Nice! We put an end to blacks central pawn storm. By playing d4, we establish a strong pawn center and challenge Black's position."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-18",
    "name": "Closed System with Bb4",
    "description": "Standard development against pin",
    "moves": ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "e3", "Bb4", "Qc2", "d6", "Nd5", "Nxd5", "cxd5", "Ne7", "Qa4+", "Bd7", "Qxb4"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the other knight to c6.",
      "We play e3, preparing development.",
      "Black pins our knight with Bb4.",
      "We develop the queen to c2.",
      "Black supports the center with d6.",
      "We move the knight to d5.",
      "Black captures our knight.",
      "We recapture with the pawn.",
      "Black retreats the knight to e7.",
      "We check with the queen.",
      "Black blocks with the bishop.",
      "After the final move - You just won yourself a free bishop :D By capturing on b4, we win a piece for free."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-19",
    "name": "Botvinnik System Repeat",
    "description": "Repeat of bishop win line",
    "moves": ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "e3", "Bb4", "Qc2", "d6", "Nd5", "Nxd5", "cxd5", "Ne7", "Qa4+", "Bd7", "Qxb4"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the other knight to c6.",
      "We play e3, supporting the center.",
      "Black pins our knight with Bb4.",
      "We develop the queen to c2.",
      "Black supports the center with d6.",
      "We move the knight to d5.",
      "Black captures our knight.",
      "We recapture with the pawn.",
      "Black retreats the knight to e7.",
      "We check with the queen.",
      "Black blocks with the bishop.",
      "After the final move - You just won yourself a free bishop :D By capturing on b4, we win a piece for free."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-20",
    "name": "King's Indian Attack Setup",
    "description": "Fianchetto against Dutch setup",
    "moves": ["c4", "e5", "Nc3", "d6", "Nf3", "f5", "g3", "Nf6", "Bg2"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black supports the center with d6.",
      "We develop the kingside knight.",
      "Black plays f5, adopting a Dutch setup.",
      "We play g3, preparing a fianchetto.",
      "Black develops the knight to f6.",
      "After the final move - Well done! After a castle, we'll enjoy the rest of the game with an extremely strong bishop on g2."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-21",
    "name": "Tactical Center Variation",
    "description": "Complex pawn exchanges",
    "moves": ["c4", "Nf6", "Nc3", "e6", "e4", "d5", "e5", "d4", "exf6", "dxc3", "bxc3", "Qxf6", "Nf3"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black develops the knight to f6.",
      "We develop the queenside knight.",
      "Black plays e6, preparing d5.",
      "We establish a strong center with e4.",
      "Black challenges immediately with d5.",
      "We push e5, attacking the knight.",
      "Black pushes d4, attacking our knight.",
      "We capture the knight on f6.",
      "Black captures our knight on c3.",
      "We recapture with the b-pawn.",
      "Black recaptures the pawn on f6 with the queen.",
      "After the final move - Nice! Next, we'll develop our bishop to d3 and then castle. The position is about equal."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-22",
    "name": "Queen's Pawn Game Structure",
    "description": "Transpositional line",
    "moves": ["c4", "e6", "Nc3", "d5", "e3", "Nf6", "Nf3", "Be7", "b3", "O-O", "Bb2", "c5", "cxd5", "exd5", "d4"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black plays e6, preparing d5.",
      "We develop the queenside knight.",
      "Black plays d5, challenging the center.",
      "We play e3, supporting the center.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the bishop to e7.",
      "We play b3, preparing a queenside fianchetto.",
      "Black castles kingside.",
      "We complete our fianchetto with Bb2.",
      "Black plays c5, challenging the center.",
      "We capture on d5.",
      "Black recaptures with the e-pawn.",
      "After the final move - Nice! We put an end to blacks central pawn storm."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-23",
    "name": "Symmetrical English Basic",
    "description": "Basic symmetrical setup",
    "moves": ["c4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "Nf3", "Nf6", "d4", "cxd4", "Nxd4", "O-O", "O-O"],
    "explanations": [
      "We begin with the English Opening, playing c4.",
      "Black responds symmetrically with c5.",
      "We develop the queenside knight.",
      "Black develops the knight to c6.",
      "We play g3, preparing a fianchetto.",
      "Black plays g6, mirroring our setup.",
      "We complete our fianchetto with Bg2.",
      "Black completes their fianchetto with Bg7.",
      "We develop the kingside knight.",
      "Black develops the knight to f6.",
      "We break symmetry with d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black castles kingside.",
      "After the final move - That was... emotional. By castling, we complete our development."
    ]
  },
  {
    "category": "English Opening",
    "id": "english-24",
    "name": "Four Knights English",
    "description": "Standard four knights setup",
    "moves": ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "e3", "Bb4", "Qc2", "d6", "Nd5", "Bc5", "a3", "a5", "b3"],
    "explanations": [
      "We open with the English, playing c4.",
      "Black responds with e5.",
      "We develop the queenside knight.",
      "Black develops the knight to f6.",
      "We develop the kingside knight.",
      "Black develops the other knight to c6.",
      "We play e3, preparing development.",
      "Black pins our knight with Bb4.",
      "We develop the queen to c2.",
      "Black supports the center with d6.",
      "We move the knight to d5.",
      "Black retreats the bishop to c5.",
      "We play a3, preventing ...Bb4.",
      "Black plays a5, preventing b4.",
      "After the final move - Well done! We'll plant our bishop on b2 next, and then play the game from there."
    ]
  }
];