import { withOpeningFeedback } from "./feedback";

export const englundGambitLines = withOpeningFeedback([
  {
    "category": "Englund Gambit",
    "id": "englund-01",
    "name": "Classic Englund Gambit Accepted",
    "description": "Immediate pawn sacrifice for development",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Nbd2",
      "Qxf4",
      "e3",
      "Qb4"
    ],
    "explanations": [
      "White starts with pawn to {{square d4}} and claims central space.",
      "Let's learn the Englund Gambit! When White plays {{square d4}}, answer with pawn to {{square e5}} and drag the game away from quiet Queen's Pawn positions.",
      "White accepts the gambit, gaining a material advantage but allowing Black counterplay.",
      "Black develops the knight with tempo, attacking the {{square e5}} pawn immediately.",
      "White develops the knight to defend {{square e5}} while preparing kingside castling.",
      "Black develops the queen actively, targeting the {{square e5}} pawn and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}, but this exposes it to future attacks.",
      "Black checks the king while attacking the {{square b2}} pawn, creating immediate threats.",
      "White blocks the check with the knight, developing a piece but blocking the queen's bishop.",
      "Black captures the bishop, winning material and maintaining the initiative.",
      "White attacks the queen with a pawn push, gaining tempo to continue development.",
      "The queen retreats to a safe square while maintaining pressure on {{square b2}} and the center."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-02",
    "name": "Alternative Knight Block",
    "description": "Different knight block leads to similar tactics",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Nc3",
      "Qxf4",
      "e3",
      "Qb4"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit sacrifice, aiming to disrupt White's development.",
      "White accepts the pawn, gaining material but allowing Black counterplay.",
      "Black develops the knight with immediate pressure on the {{square e5}} pawn.",
      "White develops the knight naturally, defending {{square e5}} and preparing castling.",
      "Black's queen develops to {{square e7}}, targeting the {{square e5}} pawn and preparing ...Q{{square b4}}+.",
      "White develops the bishop to {{square f4}}, active but potentially exposed.",
      "Black checks the king while attacking the {{square b2}} pawn, creating immediate threats.",
      "White blocks with the queen's knight, developing a piece but allowing ...Qx{{square f4}}.",
      "Black captures the bishop, winning material and maintaining pressure.",
      "White attacks the queen with a pawn push, gaining time to develop.",
      "The queen retreats safely while maintaining threats against White's position."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-03",
    "name": "Classic Checkmate Pattern",
    "description": "Quick mate after Qb4+ and bishop maneuvers",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Bc3",
      "Bb4",
      "Qd2",
      "Bxc3",
      "Qxc3",
      "Qc1#"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn opening.",
      "The Englund Gambit - sacrificing a pawn for rapid development and attack.",
      "White accepts the pawn, gaining material but allowing Black's initiative.",
      "Black develops the knight with tempo, attacking the {{square e5}} pawn.",
      "White develops the knight to defend {{square e5}} and prepare kingside castling.",
      "Black's queen develops actively, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively but exposes it to future attacks.",
      "Black checks the king while threatening the {{square b2}} pawn, creating immediate pressure.",
      "White blocks the check with the bishop, but this allows ...Qx{{square b2}}.",
      "Black captures the {{square b2}} pawn, attacking the rook and increasing material advantage.",
      "White attacks the queen with the bishop, attempting to regain tempo.",
      "Black pins the bishop with ...B{{square b4}}, creating tactical threats.",
      "White develops the queen to defend the bishop and connect rooks.",
      "Black captures the bishop, eliminating a defender and opening lines.",
      "White recaptures with the queen, but this leaves the back rank vulnerable.",
      "Checkmate! The queen delivers mate on {{square c1}}, exploiting White's underdeveloped position."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-04",
    "name": "Queen Block Variation",
    "description": "White blocks with queen instead of bishop",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Qd2",
      "Qxb2",
      "Qc3",
      "Bb4",
      "Bd2",
      "Bxc3",
      "Bxc3",
      "Qc1#"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central presence.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material advantage.",
      "Black develops the knight with immediate pressure on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}, but this exposes it.",
      "Black checks the king while threatening the {{square b2}} pawn.",
      "White blocks with the queen, but this allows ...Qx{{square b2}}.",
      "Black captures the {{square b2}} pawn, attacking the rook and gaining material.",
      "White attacks the queen, trying to regain tempo and development.",
      "Black pins the queen with ...B{{square b4}}, creating tactical threats.",
      "White develops the bishop to break the pin.",
      "Black captures the queen, winning material and maintaining attack.",
      "White recaptures with the bishop, but the position remains critical.",
      "Checkmate! Black's queen delivers mate on {{square c1}}, exploiting White's exposed king."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-05",
    "name": "Knight Sacrifice Line",
    "description": "White sacrifices knight for attack",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Nc3",
      "Bb4",
      "Nd5",
      "Bxd2+",
      "Nxd2",
      "Nb4",
      "Nxc7+",
      "Kd8",
      "Nxa8",
      "Nxc2+",
      "Qxc2",
      "Qxc2"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}.",
      "Black checks the king while threatening {{square b2}}.",
      "White blocks with the bishop, allowing ...Qx{{square b2}}.",
      "Black captures the {{square b2}} pawn, attacking the rook.",
      "White develops the knight, aiming for counterplay.",
      "Black pins the knight, creating tactical opportunities.",
      "White sacrifices the knight to disrupt Black's position.",
      "Black captures with check, maintaining material advantage.",
      "White recaptures with the knight.",
      "Black attacks the queen with the knight, gaining tempo.",
      "White's knight captures with check, creating complications.",
      "Black's king is forced to move, losing castling rights.",
      "White captures the rook, winning material compensation.",
      "Black's knight delivers check, attacking the queen.",
      "White captures the knight with the queen.",
      "Black captures the queen, simplifying to a winning endgame."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-06",
    "name": "Bxc3 Capture Line",
    "description": "Bishop captures on c3 leads to material gain",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Bc3",
      "Bb4",
      "Qd2",
      "Bxc3",
      "Nxc3",
      "Qxa1+",
      "Qd1",
      "Qxc3+"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}.",
      "Black checks the king while threatening {{square b2}}.",
      "White blocks with the bishop, allowing ...Qx{{square b2}}.",
      "Black captures the {{square b2}} pawn, attacking the rook.",
      "White attacks the queen with the bishop.",
      "Black pins the bishop with ...B{{square b4}}, creating threats.",
      "White develops the queen to defend and connect rooks.",
      "Black captures the bishop, winning material.",
      "White recaptures with the knight, developing a piece.",
      "Black captures the rook with check, gaining significant material.",
      "White blocks with the queen, but the position remains difficult.",
      "Black captures the knight with check, maintaining a decisive advantage."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-07",
    "name": "Nd5 Attack Line",
    "description": "Knight to d5 creates threats",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Nc3",
      "Qxf4",
      "Nd5",
      "Qe4",
      "Nxc7+",
      "Kd8",
      "Nxa8",
      "Nxe5",
      "Nxe5",
      "Qxe5"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}.",
      "Black checks the king while threatening {{square b2}}.",
      "White blocks with the knight, developing a piece.",
      "Black captures the bishop, winning material.",
      "White attacks with the knight, threatening fork tactics.",
      "Black's queen retreats to defend and maintain material.",
      "White's knight captures with check, creating complications.",
      "Black's king is forced to move, losing castling rights.",
      "White captures the rook, gaining material compensation.",
      "Black captures the {{square e5}} pawn with the knight.",
      "White captures the knight, simplifying the position.",
      "Black recaptures with the queen, maintaining material balance."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-08",
    "name": "d5 Advance Variation",
    "description": "White advances d5 instead of capturing",
    "moves": [
      "d4",
      "e5",
      "d5",
      "Nf6",
      "c4",
      "Bb4+"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - offering a pawn sacrifice.",
      "White declines the gambit, advancing the pawn to gain space.",
      "Black develops the knight to its natural square, attacking {{square d5}}.",
      "White supports the {{square d5}} pawn and expands on the queenside.",
      "Black develops the bishop with check, pinning the knight and creating pressure."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-09",
    "name": "Bd2 Capture Line",
    "description": "Bishop captures on d2 leads to simplification",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Nc3",
      "Bb4",
      "Nd5",
      "Bxd2+",
      "Nxd2",
      "Nb4",
      "Nxb4",
      "Qxb4"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}} and preparing ...Q{{square b4}}+.",
      "White develops the bishop actively to {{square f4}}.",
      "Black checks the king while threatening {{square b2}}.",
      "White blocks with the bishop, allowing ...Qx{{square b2}}.",
      "Black captures the {{square b2}} pawn, attacking the rook.",
      "White develops the knight, aiming for counterplay.",
      "Black pins the knight with ...B{{square b4}}.",
      "White attacks with the knight, creating threats.",
      "Black captures with check, simplifying the position.",
      "White recaptures with the knight.",
      "Black attacks the queen with the knight.",
      "White captures the knight, exchanging pieces.",
      "Black recaptures with the queen, maintaining material advantage."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-10",
    "name": "e3 Exchange Variation",
    "description": "White plays e3 instead of capturing",
    "moves": [
      "d4",
      "e5",
      "e3",
      "exd4",
      "exd4",
      "d5"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - offering a pawn sacrifice.",
      "White prepares to recapture on {{square d4}}, maintaining solid central structure.",
      "Black captures the pawn, forcing the exchange.",
      "White recaptures, maintaining a central pawn majority.",
      "Black establishes a central pawn of their own, creating balanced play."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-11",
    "name": "Nc3 Development Line",
    "description": "White develops knight early",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Nc3",
      "Nxe5",
      "Nxe5",
      "Qxe5",
      "e4",
      "Bb4"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}}.",
      "White develops the queen's knight, preparing central expansion.",
      "Black captures the {{square e5}} pawn with the knight.",
      "White recaptures with the knight, exchanging pieces.",
      "Black recaptures with the queen, centralizing the piece.",
      "White advances the e-pawn, establishing a strong center.",
      "Black develops the bishop with a pin on the knight, creating pressure."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-12",
    "name": "Bf4 Capture Line",
    "description": "Bishop to f4 followed by knight capture",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Nc3",
      "Nxe5",
      "Bf4",
      "Nxf3+",
      "gxf3",
      "d6"
    ],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on {{square e5}}.",
      "White develops the knight to defend {{square e5}} and prepare castling.",
      "Black's queen develops to {{square e7}}, targeting {{square e5}}.",
      "White develops the queen's knight, preparing central expansion.",
      "Black captures the {{square e5}} pawn with the knight.",
      "White develops the bishop actively, attacking the knight.",
      "Black captures with check, forcing recapture and damaging White's pawn structure.",
      "White recaptures with the pawn, doubling pawns but opening the g-file.",
      "Black advances the d-pawn, gaining central space and preparing development."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-13",
    "name": "Critical Rb1 defense",
    "description": "White's best practical defense against the classic trap.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Nc3",
      "Bb4",
      "Rb1",
      "Qa3",
      "Rb3",
      "Qa5"
    ],
    "explanations": [
      "White opens with the queen's pawn and claims central space.",
      "The Englund Gambit offers a pawn to get activity before White is coordinated.",
      "White accepts material and asks Black to prove the compensation.",
      "Black develops with tempo and starts the usual pressure on {{square e5}}.",
      "White defends the pawn and keeps normal development on track.",
      "Black adds a second attacker and prepares the forcing check on {{square b4}}.",
      "B{{square f4}} is natural for many {{square d4}} players, but it gives Black a concrete target.",
      "The queen check hits the king, the bishop, and the {{square b2}} pawn at once.",
      "B{{square d2}} is the standard block, but it allows Black's queen to grab on {{square b2}}.",
      "Qx{{square b2}} wins a pawn and attacks the rook, which is the whole point of the check.",
      "White develops and tries to trap the queen while keeping pressure on {{square d5}} and {{square b5}} ideas.",
      "B{{square b4}} is the key practical move from the transcript. It pins {{square c3}} and makes White solve tactical problems first.",
      "R{{square b1}} is the critical defense. White saves the rook, attacks the queen, and keeps {{square c3}} protected.",
      "Q{{square a3}} is the calm retreat. Black stays active and keeps pressure on {{square a2}}, {{square c3}}, and the diagonal.",
      "White keeps chasing the queen, hoping the extra tempi will turn into a real advantage.",
      "Q{{square a5}} is the standard follow-up. Black is still active, but from here the position becomes a real fight rather than a trap."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-14",
    "name": "Critical Nd5 challenge",
    "description": "The strongest practical test of the classic Qb2 line.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Nc3",
      "Bb4",
      "Rb1",
      "Qa3",
      "Nd5",
      "Ba5"
    ],
    "explanations": [
      "White opens with the queen's pawn and takes central space.",
      "The Englund Gambit aims for immediate activity instead of long-term structural soundness.",
      "White accepts the pawn and forces Black to play energetically.",
      "N{{square c6}} develops with tempo and asks White how the extra pawn will be held.",
      "White covers {{square e5}} and prepares to castle if things calm down.",
      "Q{{square e7}} adds another attacker and sets up the forcing queen excursion to {{square b4}}.",
      "B{{square f4}} is natural, but Black is counting on it for concrete tactics.",
      "The check on {{square b4}} hits multiple targets and starts the trap tree.",
      "B{{square d2}} is the standard retreat that keeps material but loosens {{square b2}}.",
      "Black takes on {{square b2}} and attacks the rook. This is the jackpot line from the transcript.",
      "White develops and tries to prove the queen is overextended.",
      "B{{square b4}} is the important practical move. It pins {{square c3}} and keeps tactical pressure alive.",
      "R{{square b1}} is the best defensive move. White saves the rook and keeps {{square c3}} from falling.",
      "Q{{square a3}} is Black's best retreat when White knows the main trap and refuses to hang material.",
      "N{{square d5}} is the critical follow-up from the transcript. It attacks {{square c7}} and also hits the bishop.",
      "B{{square a5}} keeps the bishop safe while preserving pressure. Black is no longer trapping by force, but the game is still sharp."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-15",
    "name": "Bf4 Immediate Capture",
    "description": "Early bishop development leads to immediate capture",
    "moves": [
      "d4",
      "e5",
      "Bf4",
      "exf4"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White develops the bishop early, but this is premature in this line.",
      "Black immediately captures the bishop, winning a piece for a pawn with a strong initiative."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-16",
    "name": "Blackburne-Hartlaub queenside castling plan",
    "description": "The stronger transcript-backed setup with ...d6, rapid queenside development, and a direct kingside attack.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "d6",
      "exd6",
      "Bxd6",
      "Nf3",
      "Nc6",
      "Nc3",
      "Bg4",
      "e3",
      "Qe7",
      "Be2",
      "O-O-O",
      "Bd2",
      "Nf6",
      "O-O",
      "h5",
      "h3",
      "Bxf3",
      "Bxf3",
      "Qe5"
    ],
    "explanations": [
      "White claims the center with the queen's pawn.",
      "Black immediately gambits a pawn to pull White out of a normal {{square d4}} structure.",
      "White accepts and tries to stay a pawn up.",
      "Instead of chasing a cheap trick, Black offers a second pawn to open lines and gain development.",
      "White keeps grabbing material, which is what this setup invites.",
      "Bx{{square d6}} is the point of the gambit. Black gets a developed bishop, open lines, and quick piece play.",
      "White develops and tries to consolidate the extra pawns.",
      "Black develops the queenside knight first because the main plan is usually queenside castling.",
      "White adds support in the center and keeps the extra material.",
      "B{{square g4}} develops with purpose and starts pressure on the diagonal toward {{square d1}} and {{square h2}}.",
      "White supports {{square f3}} and makes room for the dark-squared bishop.",
      "Q{{square e7}} connects rooks and clears {{square d8}} so castling long becomes possible.",
      "White develops, but Black is the side dictating the pace.",
      "Queenside castling lands the rook on the open d-file immediately, which is the core positional point from the transcript.",
      "White brings the bishop out to keep the queen safe and finish coordination.",
      "Black develops another piece and keeps the kingside attack ready.",
      "White castles, but now Black's attack is the faster one.",
      "The pawn storm starts right away. The transcript's main practical point is that Black often attacks much faster here.",
      "{{square h3}} is natural, but it does not solve White's real problem, which is king safety.",
      "Bx{{square f3}} removes a defender and makes White's kingside easier to attack.",
      "White recaptures, but now the structure is looser and the king has fewer clean defenders.",
      "Q{{square e5}} centralizes the queen, points at {{square h2}}, and supports further attacking moves like ...{{square g5}} or ...{{square h4}}."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-17",
    "name": "Blackburne-Hartlaub versus 6.Bg5",
    "description": "White tries to be active with Bg5, but Black keeps the same queenside-castling plan and attacks anyway.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "d6",
      "exd6",
      "Bxd6",
      "Nf3",
      "Nc6",
      "Nc3",
      "Bg4",
      "Bg5",
      "f6",
      "Bh4",
      "Qe7",
      "e3",
      "O-O-O",
      "Bd3",
      "Ne5",
      "Qe2",
      "Bb4"
    ],
    "explanations": [
      "White starts with a standard central claim.",
      "Black chooses the Englund and aims for an unbalanced fight immediately.",
      "White accepts the pawn and tests Black's compensation.",
      "Black switches to the stronger ...{{square d6}} setup from the transcript.",
      "White keeps the extra pawn for the moment.",
      "The bishop recaptures and Black gets the active piece play the gambit is built around.",
      "White develops and looks for a clean way to finish development.",
      "Black brings out the queenside knight first because castling long is part of the plan.",
      "White reinforces the center and keeps extra material.",
      "B{{square g4}} develops with tempo and starts the usual pressure down the diagonal.",
      "B{{square g5}} looks active because it hits the queen side of Black's setup, but the transcript's point is that it does not really change anything.",
      "{{square f6}} kicks the bishop immediately and asks White to decide where it belongs.",
      "The bishop drops back, but it is no longer doing much for White's position.",
      "Black keeps the same setup. Q{{square e7}} prepares queenside castling and keeps the attack flowing.",
      "White supports the center and makes space for the bishop.",
      "Black castles long exactly as in the main line. The rook is now on the open d-file.",
      "White develops the bishop to block pressure and help the queen side stay coordinated.",
      "N{{square e5}} is a direct attacking move from the transcript. It increases pressure on {{square f3}} while the knight is pinned to the king.",
      "White tries to prepare queenside castling and get out of danger.",
      "B{{square b4}} is the key practical squeeze. Black is ready to disrupt White's structure whichever side White chooses for the king."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-18",
    "name": "Hold-the-pawn line met by ...Qf6",
    "description": "A stronger opponent keeps the pawn on e5, and Black solves it with development instead of forcing the old trap.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "d6",
      "Nf3",
      "Nc6",
      "Bf4",
      "Bg4",
      "exd6",
      "Qf6",
      "e3",
      "O-O-O"
    ],
    "explanations": [
      "White takes central space with the queen's pawn.",
      "Black chooses the Englund to force an immediate imbalance.",
      "White accepts the pawn and hopes to stay a clean pawn up.",
      "Black offers a second pawn and opens lines instead of trying to recover material too slowly.",
      "Instead of taking on {{square d6}}, White keeps the {{square e5}} pawn and develops. This is the stronger practical try the transcript points out.",
      "N{{square c6}} adds pressure to {{square e5}} and again asks White whether the pawn can really be held.",
      "B{{square f4}} is a natural developing move that tries to support {{square e5}} and stay active.",
      "B{{square g4}} keeps Black on the same attacking plan as in the accepted lines.",
      "White finally takes on {{square d6}}, hoping the extra pawn and Black's d-pawn structure will kill the initiative.",
      "Q{{square f6}} is the key transcript move. It attacks the bishop, eyes {{square b2}}, and still supports queenside castling.",
      "White tries to keep the position together and finish development.",
      "Black castles long anyway. The rook reaches the open d-file and the initiative is fully intact."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-19",
    "name": "Critical defense with Rb5 and final trap",
    "description": "The sharp continuation after White finds the best practical defensive moves in the classical Qb2 line.",
    "moves": [
      "d4",
      "e5",
      "dxe5",
      "Nc6",
      "Nf3",
      "Qe7",
      "Bf4",
      "Qb4+",
      "Bd2",
      "Qxb2",
      "Nc3",
      "Bb4",
      "Rb1",
      "Qa3",
      "Nd5",
      "Ba5",
      "Rb5",
      "Bxd2+",
      "Qxd2",
      "Kd8",
      "Qg5+",
      "f6",
      "Qxg7"
    ],
    "explanations": [
      "White opens with the queen's pawn and claims central space.",
      "Black chooses the old practical Englund trap line rather than the stronger ...{{square d6}} setup.",
      "White accepts the gambit and asks Black to prove the compensation.",
      "N{{square c6}} develops with tempo against the {{square e5}} pawn.",
      "White defends the pawn and keeps normal development available.",
      "Q{{square e7}} adds another attacker and prepares the forcing queen check on {{square b4}}.",
      "B{{square f4}} is the move the trap is aimed at. It is natural for many {{square d4}} players.",
      "The queen check hits multiple targets at once and starts the forcing line.",
      "B{{square d2}} is the standard retreat that keeps the position together for the moment.",
      "Black takes on {{square b2}}, wins a pawn, and attacks the rook in the corner.",
      "White develops and heads for the critical defensive setup instead of hanging another piece.",
      "B{{square b4}} is the key practical move. It pins {{square c3}} and keeps pressure on White's coordination.",
      "R{{square b1}} is the most important defensive move from the transcript. White saves the rook and attacks the queen.",
      "Q{{square a3}} is the best queen retreat because it stays active and keeps pressure on {{square c3}} and {{square a2}}.",
      "N{{square d5}} is the strongest follow-up. It attacks {{square c7}} and also hits the bishop.",
      "B{{square a5}} is the recommended bishop retreat. Black keeps pressure and avoids immediate tactics.",
      "R{{square b5}} is the engine-like move Gotham called the hardest practical defense. White keeps the rook active and adds more pressure.",
      "Black simplifies with check and tries to drag White away from perfect coordination.",
      "White recaptures and keeps the pieces active. This is the point where the line stops being a cheap trap and becomes a real fight.",
      "K{{square d8}} is forced because Black's king has to step out of the center pressure.",
      "Q{{square g5}}+ is the final tactical try from the transcript. White keeps the initiative and asks whether Black can hold everything together.",
      "{{square f6}} is practically forced to block the check and cover key squares.",
      "Qx{{square g7}} grabs material with check threats still in the air. Even after White finds the best defense, Black is only surviving tactically here, not crushing."
    ]
  }
]);
