export const englundGambitLines = [
  {
    "category": "Englund Gambit",
    "id": "englund-01",
    "name": "Classic Englund Gambit Accepted",
    "description": "Immediate pawn sacrifice for development",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Nbd2", "Qxf4", "e3", "Qb4"],
    "explanations": [
      "White establishes central presence with the queen's pawn, controlling e5 and c5.",
      "The Englund Gambit - Black sacrifices a pawn to disrupt White's center and quick development.",
      "White accepts the gambit, gaining a material advantage but allowing Black counterplay.",
      "Black develops the knight with tempo, attacking the e5 pawn immediately.",
      "White develops the knight to defend e5 while preparing kingside castling.",
      "Black develops the queen actively, targeting the e5 pawn and preparing ...Qb4+.",
      "White develops the bishop actively to f4, but this exposes it to future attacks.",
      "Black checks the king while attacking the b2 pawn, creating immediate threats.",
      "White blocks the check with the knight, developing a piece but blocking the queen's bishop.",
      "Black captures the bishop, winning material and maintaining the initiative.",
      "White attacks the queen with a pawn push, gaining tempo to continue development.",
      "The queen retreats to a safe square while maintaining pressure on b2 and the center."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-02",
    "name": "Alternative Knight Block",
    "description": "Different knight block leads to similar tactics",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Nc3", "Qxf4", "e3", "Qb4"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit sacrifice, aiming to disrupt White's development.",
      "White accepts the pawn, gaining material but allowing Black counterplay.",
      "Black develops the knight with immediate pressure on the e5 pawn.",
      "White develops the knight naturally, defending e5 and preparing castling.",
      "Black's queen develops to e7, targeting the e5 pawn and preparing ...Qb4+.",
      "White develops the bishop to f4, active but potentially exposed.",
      "Black checks the king while attacking the b2 pawn, creating immediate threats.",
      "White blocks with the queen's knight, developing a piece but allowing ...Qxf4.",
      "Black captures the bishop, winning material and maintaining pressure.",
      "White attacks the queen with a pawn push, gaining time to develop.",
      "The queen retreats safely while maintaining threats against White's position."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-03",
    "name": "Classic Checkmate Pattern",
    "description": "Quick mate after Qb4+ and bishop maneuvers",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4", "Qd2", "Bxc3", "Qxc3", "Qc1#"],
    "explanations": [
      "White establishes central control with the queen's pawn opening.",
      "The Englund Gambit - sacrificing a pawn for rapid development and attack.",
      "White accepts the pawn, gaining material but allowing Black's initiative.",
      "Black develops the knight with tempo, attacking the e5 pawn.",
      "White develops the knight to defend e5 and prepare kingside castling.",
      "Black's queen develops actively, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively but exposes it to future attacks.",
      "Black checks the king while threatening the b2 pawn, creating immediate pressure.",
      "White blocks the check with the bishop, but this allows ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook and increasing material advantage.",
      "White attacks the queen with the bishop, attempting to regain tempo.",
      "Black pins the bishop with ...Bb4, creating tactical threats.",
      "White develops the queen to defend the bishop and connect rooks.",
      "Black captures the bishop, eliminating a defender and opening lines.",
      "White recaptures with the queen, but this leaves the back rank vulnerable.",
      "Checkmate! The queen delivers mate on c1, exploiting White's underdeveloped position."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-04",
    "name": "Queen Block Variation",
    "description": "White blocks with queen instead of bishop",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Qd2", "Qxb2", "Qc3", "Bb4", "Bd2", "Bxc3", "Bxc3", "Qc1#"],
    "explanations": [
      "White opens with the queen's pawn, establishing central presence.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material advantage.",
      "Black develops the knight with immediate pressure on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4, but this exposes it.",
      "Black checks the king while threatening the b2 pawn.",
      "White blocks with the queen, but this allows ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook and gaining material.",
      "White attacks the queen, trying to regain tempo and development.",
      "Black pins the queen with ...Bb4, creating tactical threats.",
      "White develops the bishop to break the pin.",
      "Black captures the queen, winning material and maintaining attack.",
      "White recaptures with the bishop, but the position remains critical.",
      "Checkmate! Black's queen delivers mate on c1, exploiting White's exposed king."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-05",
    "name": "Knight Sacrifice Line",
    "description": "White sacrifices knight for attack",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Nc3", "Bb4", "Nd5", "Bxd2+", "Nxd2", "Nb4", "Nxc7+", "Kd8", "Nxa8", "Nxc2+", "Qxc2", "Qxc2"],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the bishop, allowing ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook.",
      "White develops the knight, aiming for counterplay.",
      "Black pins the knight, creating tactical opportunities.",
      "White sacrifices the knight to disrupt Black's position.",
      "Black captures with check, maintaining material advantage.",
      "White recaptures with the knight.",
      "Black attacks the queen with the knight, gaining tempo.",
      "White's knight captures with check, creating complications.",
      "Black's king is forced to move, losing castling rights.",
      "White captures the rook, winning material compensation.",
      "Black's knight delivers check, attacking the queen.",
      "White captures the knight with the queen.",
      "Black captures the queen, simplifying to a winning endgame."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-06",
    "name": "Bxc3 Capture Line",
    "description": "Bishop captures on c3 leads to material gain",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4", "Qd2", "Bxc3", "Nxc3", "Qxa1+", "Qd1", "Qxc3+"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the bishop, allowing ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook.",
      "White attacks the queen with the bishop.",
      "Black pins the bishop with ...Bb4, creating threats.",
      "White develops the queen to defend and connect rooks.",
      "Black captures the bishop, winning material.",
      "White recaptures with the knight, developing a piece.",
      "Black captures the rook with check, gaining significant material.",
      "White blocks with the queen, but the position remains difficult.",
      "Black captures the knight with check, maintaining a decisive advantage."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-07",
    "name": "Nd5 Attack Line",
    "description": "Knight to d5 creates threats",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Nc3", "Qxf4", "Nd5", "Qe4", "Nxc7+", "Kd8", "Nxa8", "Nxe5", "Nxe5", "Qxe5"],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the knight, developing a piece.",
      "Black captures the bishop, winning material.",
      "White attacks with the knight, threatening fork tactics.",
      "Black's queen retreats to defend and maintain material.",
      "White's knight captures with check, creating complications.",
      "Black's king is forced to move, losing castling rights.",
      "White captures the rook, gaining material compensation.",
      "Black captures the e5 pawn with the knight.",
      "White captures the knight, simplifying the position.",
      "Black recaptures with the queen, maintaining material balance."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-08",
    "name": "d5 Advance Variation",
    "description": "White advances d5 instead of capturing",
    "moves": ["d4", "e5", "d5", "Nf6", "c4", "Bb4+"],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - offering a pawn sacrifice.",
      "White declines the gambit, advancing the pawn to gain space.",
      "Black develops the knight to its natural square, attacking d5.",
      "White supports the d5 pawn and expands on the queenside.",
      "Black develops the bishop with check, pinning the knight and creating pressure."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-09",
    "name": "Bd2 Capture Line",
    "description": "Bishop captures on d2 leads to simplification",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Nc3", "Bb4", "Nd5", "Bxd2+", "Nxd2", "Nb4", "Nxb4", "Qxb4"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the bishop, allowing ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook.",
      "White develops the knight, aiming for counterplay.",
      "Black pins the knight with ...Bb4.",
      "White attacks with the knight, creating threats.",
      "Black captures with check, simplifying the position.",
      "White recaptures with the knight.",
      "Black attacks the queen with the knight.",
      "White captures the knight, exchanging pieces.",
      "Black recaptures with the queen, maintaining material advantage."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-10",
    "name": "e3 Exchange Variation",
    "description": "White plays e3 instead of capturing",
    "moves": ["d4", "e5", "e3", "exd4", "exd4", "d5"],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - offering a pawn sacrifice.",
      "White prepares to recapture on d4, maintaining solid central structure.",
      "Black captures the pawn, forcing the exchange.",
      "White recaptures, maintaining a central pawn majority.",
      "Black establishes a central pawn of their own, creating balanced play."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-11",
    "name": "Nc3 Development Line",
    "description": "White develops knight early",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Nc3", "Nxe5", "Nxe5", "Qxe5", "e4", "Bb4"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5.",
      "White develops the queen's knight, preparing central expansion.",
      "Black captures the e5 pawn with the knight.",
      "White recaptures with the knight, exchanging pieces.",
      "Black recaptures with the queen, centralizing the piece.",
      "White advances the e-pawn, establishing a strong center.",
      "Black develops the bishop with a pin on the knight, creating pressure."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-12",
    "name": "Bf4 Capture Line",
    "description": "Bishop to f4 followed by knight capture",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Nc3", "Nxe5", "Bf4", "Nxf3+", "gxf3", "d6"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5.",
      "White develops the queen's knight, preparing central expansion.",
      "Black captures the e5 pawn with the knight.",
      "White develops the bishop actively, attacking the knight.",
      "Black captures with check, forcing recapture and damaging White's pawn structure.",
      "White recaptures with the pawn, doubling pawns but opening the g-file.",
      "Black advances the d-pawn, gaining central space and preparing development."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-13",
    "name": "Rb1 Defense Line",
    "description": "White defends b2 with rook",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Nc3", "Bb4", "Rb1", "Qa3", "Rb3", "Qa5"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the bishop, allowing ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook.",
      "White develops the knight, preparing counterplay.",
      "Black pins the knight with ...Bb4.",
      "White defends with the rook, protecting the knight and attacking the queen.",
      "Black's queen retreats to a safer square.",
      "White attacks the queen with the rook, gaining tempo.",
      "Black's queen retreats further, maintaining pressure on the position."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-14",
    "name": "Nd5 Attack with Ba5",
    "description": "Knight to d5 met with Ba5 retreat",
    "moves": ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Nc3", "Bb4", "Rb1", "Qa3", "Nd5", "Ba5"],
    "explanations": [
      "White opens with the queen's pawn, establishing central control.",
      "The Englund Gambit - sacrificing a pawn for rapid development.",
      "White accepts the gambit pawn, gaining material.",
      "Black develops the knight with tempo on e5.",
      "White develops the knight to defend e5 and prepare castling.",
      "Black's queen develops to e7, targeting e5 and preparing ...Qb4+.",
      "White develops the bishop actively to f4.",
      "Black checks the king while threatening b2.",
      "White blocks with the bishop, allowing ...Qxb2.",
      "Black captures the b2 pawn, attacking the rook.",
      "White develops the knight, preparing counterplay.",
      "Black pins the knight with ...Bb4.",
      "White defends with the rook, protecting the knight.",
      "Black's queen retreats to maintain pressure.",
      "White attacks with the knight, threatening fork tactics.",
      "Black retreats the bishop, maintaining the pin and preparing ...O-O-O."
    ]
  },
  {
    "category": "Englund Gambit",
    "id": "englund-15",
    "name": "Bf4 Immediate Capture",
    "description": "Early bishop development leads to immediate capture",
    "moves": ["d4", "e5", "Bf4", "exf4"],
    "explanations": [
      "White establishes central control with the queen's pawn.",
      "The Englund Gambit - sacrificing a pawn for initiative.",
      "White develops the bishop early, but this is premature in this line.",
      "Black immediately captures the bishop, winning a piece for a pawn with a strong initiative."
    ]
  }
];