export const frenchDefenseLines = [
  {
    "category": "French Defense",
    "id": "french-01",
    "name": "Tarrasch Variation with c5",
    "description": "Nd2 variation with early c5 break",
    "moves": ["e4", "e6", "d4", "d5", "Nd2", "c5", "c3", "cxd4", "cxd4", "dxe4", "Nxe4", "Bb4+", "Bd2", "Qxd4", "Qa4+", "Nc6"],
    "explanations": [
      "White establishes central control with the king's pawn.",
      "French Defense - Black prepares to challenge the center with ...d5.",
      "White reinforces the center and supports the e4 pawn.",
      "Black immediately challenges White's central pawn structure.",
      "Tarrasch Variation - White develops knight while keeping c3 clear for the c-pawn.",
      "Black attacks the d4 pawn, forcing White to make a decision in the center.",
      "White supports the d4 pawn, preparing to maintain central control.",
      "Black captures on d4, forcing the recapture to open the center.",
      "White recaptures, maintaining a central pawn majority.",
      "Black captures the e4 pawn, exchanging central pawns.",
      "White recaptures with the knight, developing a piece while maintaining structure.",
      "Bishop check - Black pins the knight against the king, creating tactical opportunities.",
      "White blocks the check with the bishop, developing a piece and breaking the pin.",
      "Black boldly captures the d4 pawn with the queen, accepting doubled pawns for active play.",
      "Queen check - White attacks the loose bishop while developing the queen actively.",
      "Black blocks the check with the knight while developing a piece to its natural square."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-02",
    "name": "Advance Variation Main Line",
    "description": "Classical Advance French with Qb6",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "c3", "Qb6", "Nf3", "Nc6", "Be2", "cxd4", "cxd4", "Nge7", "O-O", "Nf5", "Be3", "Qxb2", "Nbd2", "Be7"],
    "explanations": [
      "White claims space in the center with the king's pawn.",
      "French Defense - Black prepares to challenge White's center with ...d5.",
      "White reinforces the center with the d-pawn.",
      "Black immediately stakes a claim in the center.",
      "Advance Variation - White gains space and fixes the pawn structure.",
      "Standard counterplay - Black attacks both the b2 pawn and d4 pawn simultaneously.",
      "White supports the d4 pawn, maintaining the central stronghold.",
      "Queen attacks the b2 pawn, putting pressure on White's queenside.",
      "Knight develops to its natural square, controlling central squares.",
      "Black develops the knight to support the ...c5 advance and control d4.",
      "Bishop develops modestly, preparing kingside castling.",
      "Black captures on d4, opening the c-file and challenging the center.",
      "White recaptures, maintaining the pawn center.",
      "Black develops the knight to e7, a flexible square preparing ...Nf5 or ...Ng6.",
      "White castles kingside, bringing the king to safety.",
      "Knight moves to f5, attacking the e3 bishop and eyeing the d4 pawn.",
      "Bishop develops to e3, supporting the d4 pawn and controlling the center.",
      "Queen captures the b2 pawn - a risky but aggressive move that wins material.",
      "White develops the knight, preparing to attack the queen and defend the c3 square.",
      "Black develops the bishop, completing minor piece development."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-03",
    "name": "Advance Variation with Nf5",
    "description": "Knight to f5 creates pressure",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "c3", "Qb6", "Nf3", "Nc6", "Be2", "cxd4", "cxd4", "Nge7", "O-O", "Nf5", "Nc3", "Nfxd4", "Nxd4", "Qxd4"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares for ...d5 challenge.",
      "White reinforces the center with d4.",
      "Black challenges the center immediately.",
      "Advance Variation - White gains space and restricts Black's pieces.",
      "Black attacks the b2 pawn, putting immediate pressure on White.",
      "White supports the d4 pawn with c3.",
      "Queen continues pressure on White's queenside.",
      "Knight develops to f3, controlling central squares.",
      "Black develops knight, supporting the ...c5 pawn break.",
      "White develops bishop, preparing kingside castling.",
      "Black captures on d4, opening the c-file.",
      "White recaptures with the c-pawn.",
      "Black develops knight to e7, a flexible square in the Advance French.",
      "White castles, bringing king to safety.",
      "Knight jumps to f5, attacking the e3 square and eyeing the d4 pawn.",
      "White develops the queenside knight, preparing for central play.",
      "Black's knight captures on d4, sacrificing itself to disrupt White's center.",
      "White captures the knight, but now the queen is exposed.",
      "Black's queen recaptures, gaining central control and attacking the e5 pawn."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-04",
    "name": "Advance Variation with Bd7",
    "description": "Bishop develops to d7",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "c3", "Qb6", "Nf3", "Nc6", "Bd3", "cxd4", "cxd4", "Bd7", "O-O", "Nxd4", "Nxd4", "Qxd4", "Nc3", "a6"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares the central challenge.",
      "White reinforces with d4.",
      "Black immediately challenges White's center.",
      "Advance Variation - White gains space.",
      "Black's queen attacks b2, creating immediate pressure.",
      "White supports d4 with c3.",
      "Queen puts pressure on White's queenside.",
      "Knight develops to its natural square.",
      "Black develops knight, supporting the ...c5 break.",
      "White develops bishop more actively than Be2, eyeing the h7 square.",
      "Black captures on d4, opening the position.",
      "White recaptures with the c-pawn.",
      "Bishop develops to d7, connecting rooks and preparing queenside play.",
      "White castles kingside.",
      "Knight captures on d4, sacrificing itself to disrupt White's center.",
      "White captures the knight.",
      "Black's queen recaptures, gaining central control.",
      "White develops the queenside knight.",
      "Black prevents Nb5, securing the queenside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-05",
    "name": "Advance Variation with Nf3",
    "description": "Early Nf3 development",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "Nf3", "cxd4", "Nxd4", "Ne7", "Nc3", "Nbc6", "Bb5", "Bd7"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces the center with d4.",
      "Black challenges the center immediately.",
      "Advance Variation - White gains space on the kingside.",
      "Black attacks the d4 pawn, forcing concessions.",
      "White develops knight instead of supporting with c3.",
      "Black captures on d4, opening the center.",
      "White recaptures with knight, developing a piece.",
      "Black develops knight to e7, a flexible square in this structure.",
      "White develops the queenside knight.",
      "Black develops the other knight to c6, putting pressure on d4.",
      "White develops bishop with pin on the knight.",
      "Black develops bishop, breaking the pin and connecting rooks."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-06",
    "name": "Advance Variation with Nxc6",
    "description": "Knight exchange on c6",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "Nf3", "cxd4", "Nxd4", "Ne7", "Nc3", "Nbc6", "Nxc6", "Nxc6"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks the d4 pawn.",
      "White develops knight to its natural square.",
      "Black captures on d4, opening the center.",
      "White recaptures with knight.",
      "Black develops knight to e7, preparing ...Nf5 or ...Ng6.",
      "White develops the queenside knight.",
      "Black develops knight to c6, attacking d4.",
      "White exchanges knights, simplifying the position.",
      "Black recaptures, maintaining piece activity."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-07",
    "name": "Winawer Variation Main Line",
    "description": "Classical Winawer with Bb4",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Bb4", "e5", "h6", "exf6", "hxg5", "fxg7", "Rg8", "Qh5", "Qf6"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces the center with d4.",
      "Black challenges the center.",
      "White develops knight, attacking d5.",
      "Black develops knight, attacking e4.",
      "Bishop pins the knight, putting pressure on Black's position.",
      "Winawer Variation - Black pins the knight, creating immediate tension.",
      "White advances, attacking the pinned knight.",
      "Black attacks the bishop, forcing it to move or be captured.",
      "White captures the knight, but loses the bishop pair.",
      "Black captures the bishop, gaining the bishop pair.",
      "Pawn advances to g7, threatening to promote and disrupting Black's kingside.",
      "Rook attacks the advanced pawn.",
      "Queen develops aggressively, attacking g5 and eyeing the kingside.",
      "Black develops queen, defending g5 and preparing to contest the position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-08",
    "name": "Advance Variation with Qxd4",
    "description": "Queen captures on d4",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "Nf3", "cxd4", "Qxd4", "Nc6", "Bb5", "Ne7"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks the d4 pawn.",
      "White develops knight to its natural square.",
      "Black captures on d4, opening the center.",
      "Queen recaptures, centralizing but potentially exposing itself.",
      "Knight develops with tempo against the queen.",
      "Bishop develops with pin on the knight.",
      "Knight moves to e7, breaking the pin and maintaining flexibility."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-09",
    "name": "Classical Variation with Bg5",
    "description": "Bg5 pin against Nf6",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7", "Nf3", "c5", "Bg5", "Qb6"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "White develops knight, attacking d5.",
      "Black develops knight, attacking e4.",
      "White advances, attacking the knight.",
      "Knight retreats to d7, maintaining defense of e5.",
      "White develops the kingside knight.",
      "Black attacks the d4 pawn, creating counterplay.",
      "Bishop pins the knight, putting pressure on Black's position.",
      "Queen attacks b2, creating threats on the queenside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-10",
    "name": "Exchange Variation Main Line",
    "description": "Early pawn exchange",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "Nc3", "Nf6", "Nf3", "Bb4", "Bd2", "O-O"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies the center.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight, eyeing d5 and e4 squares.",
      "Black develops knight, completing kingside development.",
      "White develops the other knight.",
      "Bishop pins the knight, creating immediate pressure.",
      "Bishop develops, breaking the pin.",
      "Black castles, bringing the king to safety."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-11",
    "name": "Exchange Variation with Nb4",
    "description": "Knight maneuver to attack d3",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "Bd3", "Nc6", "Nf3", "Nb4", "O-O", "Nxd3"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies the position.",
      "Black recaptures, maintaining symmetry.",
      "White develops bishop actively, eyeing the kingside.",
      "Black develops knight, preparing queenside play.",
      "White develops knight to its natural square.",
      "Knight jumps to b4, attacking the bishop on d3.",
      "White castles, bringing king to safety.",
      "Black captures the bishop, exchanging a knight for bishop."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-12",
    "name": "French Defense with Bf3",
    "description": "Bishop retreats to f3 after exchange",
    "moves": ["e4", "e6", "d4", "d5", "Bd3", "dxe4", "Bxe4", "Nf6", "Bf3", "c5", "Ne2", "Be7"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White develops bishop, preparing kingside castling.",
      "Black captures on e4, exchanging pawns.",
      "Bishop recaptures, maintaining piece activity.",
      "Black develops knight, attacking the bishop.",
      "Bishop retreats to f3, maintaining control of central squares.",
      "Black challenges the center with c5.",
      "White develops knight to e2, keeping options for f4 or g3.",
      "Black develops bishop, preparing kingside castling."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-13",
    "name": "Tarrasch Variation with Nc3",
    "description": "Alternative knight development",
    "moves": ["e4", "e6", "d4", "d5", "Nd2", "c5", "c3", "cxd4", "cxd4", "dxe4", "Nxe4", "Bb4+", "Nc3", "Nf6", "Nf3", "O-O", "Bd3", "b6", "O-O", "Bb7"],
    "explanations": [
      "White establishes central control with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center immediately.",
      "Tarrasch Variation - Knight develops while keeping c3 free.",
      "Black attacks the d4 pawn.",
      "White supports d4 with c3.",
      "Black captures on d4, opening the center.",
      "White recaptures, maintaining central control.",
      "Black captures on e4, exchanging pawns.",
      "White recaptures with knight.",
      "Bishop check, pinning the knight.",
      "White develops knight to c3 instead of blocking with bishop.",
      "Black develops knight, attacking the e4 knight.",
      "White develops the kingside knight.",
      "Black castles, bringing king to safety.",
      "White develops bishop actively.",
      "Black prepares to develop the bishop to b7.",
      "White castles, bringing king to safety.",
      "Black completes development with bishop to b7."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-14",
    "name": "Winawer Variation with Bd2",
    "description": "Bishop retreats instead of exf6",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Bb4", "e5", "h6", "Bd2", "Bxc3", "bxc3", "Ne4", "Bd3", "Nxd2", "Qxd2", "c5"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "White develops knight, attacking d5.",
      "Black develops knight, attacking e4.",
      "Bishop pins the knight.",
      "Winawer Variation - Black pins the knight.",
      "White advances, attacking the pinned knight.",
      "Black attacks the bishop.",
      "Bishop retreats, avoiding capture.",
      "Black captures on c3, doubling White's pawns.",
      "White recaptures, accepting doubled pawns for bishop pair.",
      "Black's knight moves to e4, occupying a strong central outpost.",
      "White develops bishop, attacking the knight.",
      "Knight captures the bishop, exchanging pieces.",
      "Queen recaptures, developing with tempo.",
      "Black attacks the center, challenging White's pawn structure."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-15",
    "name": "Exchange Variation with c4",
    "description": "Queenside pawn break",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "c4", "Bb4+", "Nc3", "Nf6", "Nf3", "O-O", "Be2", "dxc4"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White plays c4, challenging Black's central pawn.",
      "Bishop check, developing with tempo.",
      "White blocks with knight, developing a piece.",
      "Black develops knight.",
      "White develops the other knight.",
      "Black castles, bringing king to safety.",
      "White develops bishop modestly.",
      "Black captures the pawn, accepting an isolated queen's pawn position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-16",
    "name": "Exchange Variation with Bd6",
    "description": "Bishop develops to d6",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "Bd3", "Nc6", "c3", "Bd6"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops bishop actively.",
      "Black develops knight.",
      "White supports the center with c3.",
      "Black develops bishop to d6, eyeing the kingside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-17",
    "name": "Tarrasch Variation with exd5",
    "description": "Early pawn capture",
    "moves": ["e4", "e6", "d4", "d5", "Nd2", "c5", "exd5", "Qxd5", "dxc5", "Bxc5"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks d4 with c5.",
      "White captures on d5, simplifying the center.",
      "Queen recaptures, centralizing but potentially exposed.",
      "White captures on c5, gaining a pawn.",
      "Bishop recaptures, developing with tempo."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-18",
    "name": "Exchange Variation with Bg4",
    "description": "Bishop pin on the knight",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "Nf3", "Nf6", "Bd3", "Bd6", "O-O", "O-O", "c3", "Bg4"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight.",
      "Black develops knight.",
      "White develops bishop actively.",
      "Black develops bishop to d6.",
      "White castles, bringing king to safety.",
      "Black castles, bringing king to safety.",
      "White supports the center with c3.",
      "Bishop pins the knight, creating pressure on White's position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-19",
    "name": "Tarrasch Variation with Bc4",
    "description": "Active bishop development",
    "moves": ["e4", "e6", "d4", "d5", "Nd2", "c5", "exd5", "Qxd5", "Ngf3", "cxd4", "Bc4", "Qd6", "O-O", "Nf6", "Nb3", "Nc6", "Nbxd4", "Nxd4", "Nxd4", "Be7"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks d4 with c5.",
      "White captures on d5, simplifying.",
      "Queen recaptures, centralizing.",
      "White develops the other knight.",
      "Black captures on d4.",
      "Bishop develops actively to c4, eyeing f7.",
      "Queen retreats to d6, defending f7.",
      "White castles, bringing king to safety.",
      "Black develops knight.",
      "White's knight moves to b3, eyeing d4 and c5 squares.",
      "Black develops the other knight.",
      "White captures on d4 with knight.",
      "Black recaptures with knight.",
      "White recaptures with the other knight.",
      "Black develops bishop, preparing kingside play."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-20",
    "name": "Tarrasch Variation with Bb5",
    "description": "Bishop pin on c6",
    "moves": ["e4", "e6", "d4", "d5", "Nd2", "c5", "Ngf3", "cxd4", "Nxd4", "Nc6", "Bb5", "Ne7"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks d4 with c5.",
      "White develops the other knight.",
      "Black captures on d4.",
      "White recaptures with knight.",
      "Black develops knight, attacking d4.",
      "Bishop pins the knight.",
      "Knight moves to e7, breaking the pin while developing."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-21",
    "name": "Winawer Variation with g5",
    "description": "Kingside pawn advance",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Bb4", "e5", "h6", "Bh4", "g5"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "White develops knight, attacking d5.",
      "Black develops knight, attacking e4.",
      "Bishop pins the knight.",
      "Winawer Variation - Black pins the knight.",
      "White advances, attacking the knight.",
      "Black attacks the bishop.",
      "Bishop retreats to h4.",
      "Black advances g5, attacking the bishop and gaining space on the kingside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-22",
    "name": "Exchange Variation with Bg5 and Bg4",
    "description": "Mutual bishop pins",
    "moves": ["e4", "e6", "d4", "d5", "exd5", "exd5", "Nf3", "Nf6", "Bd3", "Bd6", "O-O", "O-O", "Bg5", "Bg4"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight.",
      "Black develops knight.",
      "White develops bishop actively.",
      "Black develops bishop to d6.",
      "White castles, bringing king to safety.",
      "Black castles, bringing king to safety.",
      "White pins the knight with bishop.",
      "Black pins White's knight with bishop, creating symmetrical tension."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-23",
    "name": "Advance Variation with a3",
    "description": "Preventive move on queenside",
    "moves": ["e4", "e6", "d4", "d5", "e5", "c5", "c3", "Qb6", "Nf3", "Nc6", "a3", "c4", "Nbd2", "Na5", "Be2", "Bd7"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks b2 with queen.",
      "White supports d4 with c3.",
      "Queen continues pressure on queenside.",
      "White develops knight.",
      "Black develops knight.",
      "White prevents ...Bb4, securing the b3 square.",
      "Black advances pawn to c4, gaining space on queenside.",
      "White develops knight, preparing to challenge the c4 pawn.",
      "Knight moves to a5, supporting the c4 pawn.",
      "White develops bishop modestly.",
      "Black develops bishop, connecting rooks."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-24",
    "name": "Classical Variation with f4",
    "description": "Kingside pawn advance",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7", "f4", "c5", "Nf3", "Nc6", "Be3", "cxd4", "Nxd4", "Bc5", "Qd2", "O-O"],
    "explanations": [
      "White claims the center with e4.",
      "French Defense - Black prepares ...d5.",
      "White reinforces with d4.",
      "Black challenges the center.",
      "White develops knight, attacking d5.",
      "Black develops knight, attacking e4.",
      "White advances, attacking the knight.",
      "Knight retreats to d7.",
      "White advances f4, supporting the e5 pawn and gaining space.",
      "Black attacks the center with c5.",
      "White develops knight.",
      "Black develops the other knight.",
      "White develops bishop, supporting the center.",
      "Black captures on d4.",
      "White recaptures with knight.",
      "Black develops bishop with tempo.",
      "Queen moves to d2, connecting rooks and defending d4.",
      "Black castles, bringing king to safety."
    ]
  }
];