import { withOpeningFeedback } from "./feedback";

export const frenchDefenseSEOText = `
The French Defense starts with 1. e4 e6 and fights for the center with ...d5 while keeping Black solid.

These drills cover the main student-facing structures in this file:
- Advance Variation plans with ...c5, ...Qb6, ...Nf5, and the practical ...Bd7 / ...Rc8 ideas
- Tarrasch Variation pressure lines, including the Kf1 Greek gift trap and the ...f6 tactical response
- Exchange and Fort Knox / Rubinstein setups where development plans matter more than memorizing one move order
- Winawer and Classical structures with pins, central breaks, and concrete tactical races

Each line explains the actual target, break, or tactical point so the move reasons stay tied to the board.
`;

export const frenchDefenseLines = withOpeningFeedback([
  {
    "category": "French Defense",
    "id": "french-01",
    "name": "Tarrasch Variation: ...Bb4+ and ...Qxd4",
    "description": "Open-center Tarrasch line with queen activity and a check on the diagonal.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "c5",
      "c3",
      "cxd4",
      "cxd4",
      "dxe4",
      "Nxe4",
      "Bb4+",
      "Bd2",
      "Qxd4",
      "Qa4+",
      "Nc6"
    ],
    "explanations": [
      "White starts with pawn to {{square e4}} and grabs central space.",
      "Let's learn the French Defense! When White plays {{square e4}}, answer with pawn to {{square e6}} and get ready to challenge the center with ...{{square d5}}.",
      "White reinforces the center and supports the {{square e4}} pawn.",
      "Black immediately challenges White's central pawn structure.",
      "Tarrasch Variation - White develops the knight without blocking the c-pawn, which keeps {{square c3}} available later.",
      "Black attacks the {{square d4}} pawn, forcing White to make a decision in the center.",
      "White supports the {{square d4}} pawn, preparing to maintain central control.",
      "Black captures on {{square d4}}, forcing the recapture to open the center.",
      "White recaptures, maintaining a central pawn majority.",
      "Black captures the {{square e4}} pawn, exchanging central pawns.",
      "White recaptures with the knight, developing a piece while maintaining structure.",
      "The check develops with tempo and asks White to solve the pin before finishing development.",
      "White blocks the check with the bishop, developing a piece and breaking the pin.",
      "Black grabs the {{square d4}} pawn and relies on queen activity before White can organize a clean lead in development.",
      "Q{{square a4}}+ checks the king and hits the loose bishop at the same time, so White gets active play for the pawn.",
      "Black blocks the check with the knight while developing a piece to its natural square."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-02",
    "name": "Advance Variation: Qb6 pressure on d4 and b2",
    "description": "Advance French with ...Qb6 and the standard attack on the base of White's pawn chain.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Qb6",
      "Nf3",
      "Nc6",
      "Be2",
      "cxd4",
      "cxd4",
      "Nge7",
      "O-O",
      "Nf5",
      "Be3",
      "Qxb2",
      "Nbd2",
      "Be7"
    ],
    "explanations": [
      "White claims space in the center with the king's pawn.",
      "French Defense - Black prepares to challenge White's center with ...{{square d5}}.",
      "White reinforces the center with the d-pawn.",
      "Black immediately stakes a claim in the center.",
      "Advance Variation - White gains space, but the advanced chain gives Black clear targets on {{square d4}} and {{square e5}}.",
      "Black strikes with the standard ...{{square c5}} break, attacking the base of the pawn chain instead of the head.",
      "White supports the {{square d4}} pawn, maintaining the central stronghold.",
      "...Q{{square b6}} is a typical French move: it pressures {{square d4}} indirectly and also hits {{square b2}} at once.",
      "Knight develops to its natural square, controlling central squares.",
      "Black develops the knight to support the ...{{square c5}} advance and control {{square d4}}.",
      "Bishop develops modestly, preparing kingside castling.",
      "Black captures on {{square d4}}, opening the c-file and challenging the center.",
      "White recaptures, maintaining the pawn center.",
      "The knight heads for {{square f5}} because the {{square f6}} square is no longer available in this structure.",
      "White castles kingside, bringing the king to safety.",
      "From {{square f5}} the knight increases the pressure on {{square d4}} and makes it harder for White to coordinate comfortably.",
      "Bishop develops to {{square e3}}, supporting the {{square d4}} pawn and controlling the center.",
      "Black grabs {{square b2}} when the tactic works, but the queen can still become a target if White develops quickly.",
      "White develops the knight, preparing to attack the queen and defend the {{square c3}} square.",
      "B{{square e7}} is a calm finish to development after the queenside pawn grab."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-03",
    "name": "Advance Variation: ...Nf5 and tactical pressure on d4",
    "description": "Advance French where ...Nf5 and ...Nfxd4 test whether White can really hold the center.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Qb6",
      "Nf3",
      "Nc6",
      "Be2",
      "cxd4",
      "cxd4",
      "Nge7",
      "O-O",
      "Nf5",
      "Nc3",
      "Nfxd4",
      "Nxd4",
      "Qxd4"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares for ...{{square d5}} challenge.",
      "White reinforces the center with {{square d4}}.",
      "Black challenges the center immediately.",
      "Advance Variation - White gains space and restricts Black's pieces.",
      "Black uses the usual French plan: pressure the base on {{square d4}} and keep an eye on {{square b2}}.",
      "White supports the {{square d4}} pawn with {{square c3}}.",
      "Queen continues pressure on White's queenside.",
      "Knight develops to {{square f3}}, controlling central squares.",
      "Black develops knight, supporting the ...{{square c5}} pawn break.",
      "White develops bishop, preparing kingside castling.",
      "Black captures on {{square d4}}, opening the c-file.",
      "White recaptures with the c-pawn.",
      "...Nge7 keeps the route to {{square f5}} open and avoids blocking the f-pawn.",
      "White castles, bringing king to safety.",
      "The knight lands on {{square f5}}, where it attacks {{square d4}} and asks whether White can maintain the center without concessions.",
      "White develops the queenside knight, preparing for central play.",
      "This is a tactical liquidation, not a random sacrifice. Black gives up the knight only because the queen can recapture with effect.",
      "White captures the knight, but now the queen is exposed.",
      "Qx{{square d4}} wins back the piece and leaves Black with active queen play and pressure on {{square e5}}."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-04",
    "name": "Advance Variation: Bd3 line with ...Bd7 and ...Nxd4",
    "description": "Bd3 setup where Black liquidates the center and uses queen activity instead of passive defense.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Qb6",
      "Nf3",
      "Nc6",
      "Bd3",
      "cxd4",
      "cxd4",
      "Bd7",
      "O-O",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nc3",
      "a6"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares the central challenge.",
      "White reinforces with {{square d4}}.",
      "Black immediately challenges White's center.",
      "Advance Variation - White gains space.",
      "Black's queen attacks {{square b2}}, creating immediate pressure.",
      "White supports {{square d4}} with {{square c3}}.",
      "Queen puts pressure on White's queenside.",
      "Knight develops to its natural square.",
      "Black develops knight, supporting the ...{{square c5}} break.",
      "B{{square d3}} is active because it points toward {{square h7}}, which is why Black often wants to neutralize it quickly.",
      "Black captures on {{square d4}}, opening the position.",
      "White recaptures with the c-pawn.",
      "...B{{square d7}} connects the rooks and supports a clean central liquidation without weakening the queenside.",
      "White castles kingside.",
      "This is a temporary tactical liquidation. Black clears {{square d4}} because the queen is ready to recapture and stay active.",
      "White captures the knight.",
      "The queen lands on {{square d4}} with tempo and turns central tension into direct piece activity.",
      "White develops the queenside knight.",
      "...{{square a6}} keeps N{{square b5}} out of the position so the {{queen d4 full}} stays more comfortable."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-05",
    "name": "Advance Variation: premature Bb5 met by ...Bd7",
    "description": "An early bishop pin that often just helps Black gain time and prepare ...Nxe5 ideas.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "Nf3",
      "cxd4",
      "Nxd4",
      "Ne7",
      "Nc3",
      "Nbc6",
      "Bb5",
      "Bd7"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces the center with {{square d4}}.",
      "Black challenges the center immediately.",
      "Advance Variation - White gains space on the kingside.",
      "Black attacks the {{square d4}} pawn, forcing concessions.",
      "White develops quickly, but skipping {{square c3}} means Black gets easier play against {{square d4}}.",
      "Black captures on {{square d4}}, opening the center.",
      "White recaptures with knight, developing a piece.",
      "Black develops knight to {{square e7}}, a flexible square in this structure.",
      "White develops the queenside knight.",
      "Black develops the other knight to {{square c6}}, putting pressure on {{square d4}}.",
      "B{{square b5}} looks natural, but in this structure it often helps Black because the bishop can be questioned immediately.",
      "...B{{square d7}} is not just development. It also hints at tactical ideas based on ...Nx{{square e5}} once White relaxes."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-06",
    "name": "Advance Variation with Nxc6",
    "description": "Knight exchange on c6",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "Nf3",
      "cxd4",
      "Nxd4",
      "Ne7",
      "Nc3",
      "Nbc6",
      "Nxc6",
      "Nxc6"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks the {{square d4}} pawn.",
      "White develops knight to its natural square.",
      "Black captures on {{square d4}}, opening the center.",
      "White recaptures with knight.",
      "Black develops knight to {{square e7}}, preparing ...N{{square f5}} or ...N{{square g6}}.",
      "White develops the queenside knight.",
      "Black develops knight to {{square c6}}, attacking {{square d4}}.",
      "White exchanges knights, simplifying the position.",
      "Black recaptures, maintaining piece activity."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-07",
    "name": "Winawer Variation Main Line",
    "description": "Classical Winawer with Bb4",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "Bg5",
      "Bb4",
      "e5",
      "h6",
      "exf6",
      "hxg5",
      "fxg7",
      "Rg8",
      "Qh5",
      "Qf6"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces the center with {{square d4}}.",
      "Black challenges the center.",
      "White develops knight, attacking {{square d5}}.",
      "Black develops knight, attacking {{square e4}}.",
      "Bishop pins the knight, putting pressure on Black's position.",
      "Winawer Variation - Black pins the knight, creating immediate tension.",
      "White advances, attacking the pinned knight.",
      "Black attacks the bishop, forcing it to move or be captured.",
      "White captures the knight, but loses the bishop pair.",
      "Black captures the bishop, gaining the bishop pair.",
      "Pawn advances to {{square g7}}, threatening to promote and disrupting Black's kingside.",
      "Rook attacks the advanced pawn.",
      "Queen develops aggressively, attacking {{square g5}} and eyeing the kingside.",
      "Black develops queen, defending {{square g5}} and preparing to contest the position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-08",
    "name": "Advance Variation with Qxd4",
    "description": "Queen captures on d4",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "Nf3",
      "cxd4",
      "Qxd4",
      "Nc6",
      "Bb5",
      "Ne7"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks the {{square d4}} pawn.",
      "White develops knight to its natural square.",
      "Black captures on {{square d4}}, opening the center.",
      "Queen recaptures, centralizing but potentially exposing itself.",
      "Knight develops with tempo against the queen.",
      "Bishop develops with pin on the knight.",
      "Knight moves to {{square e7}}, breaking the pin and maintaining flexibility."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-09",
    "name": "Classical Steinitz setup with ...Qb6",
    "description": "Steinitz-style structure where Black pressures d4 and b2 instead of rushing kingside play.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "e5",
      "Nfd7",
      "Nf3",
      "c5",
      "Bg5",
      "Qb6"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "White develops knight, attacking {{square d5}}.",
      "Black develops knight, attacking {{square e4}}.",
      "White advances, attacking the knight.",
      "Knight retreats to {{square d7}}, maintaining defense of {{square e5}}.",
      "White develops the kingside knight.",
      "...{{square c5}} is the standard French counterplay. Black goes after the base on {{square d4}} instead of trying to match White's space.",
      "Bishop pins the knight, putting pressure on Black's position.",
      "...Q{{square b6}} is a very typical French move because it hits {{square b2}} and keeps {{square d4}} under long-term pressure."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-10",
    "name": "Exchange Variation Main Line",
    "description": "Early pawn exchange",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "Nc3",
      "Nf6",
      "Nf3",
      "Bb4",
      "Bd2",
      "O-O"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies the center.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight, eyeing {{square d5}} and {{square e4}} squares.",
      "Black develops knight, completing kingside development.",
      "White develops the other knight.",
      "Bishop pins the knight, creating immediate pressure.",
      "Bishop develops, breaking the pin.",
      "Black castles, bringing the king to safety."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-11",
    "name": "Exchange Variation with Nb4",
    "description": "Knight maneuver to attack d3",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "Bd3",
      "Nc6",
      "Nf3",
      "Nb4",
      "O-O",
      "Nxd3"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies the position.",
      "Black recaptures, maintaining symmetry.",
      "White develops bishop actively, eyeing the kingside.",
      "Black develops knight, preparing queenside play.",
      "White develops knight to its natural square.",
      "Knight jumps to {{square b4}}, attacking the {{bishop d3 full}}.",
      "White castles, bringing king to safety.",
      "Black captures the bishop, exchanging a knight for bishop."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-12",
    "name": "Rubinstein Variation: bishop retreat to f3",
    "description": "3.Bd3 with an early exchange on e4, followed by the bishop stepping back to keep useful diagonals.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Bd3",
      "dxe4",
      "Bxe4",
      "Nf6",
      "Bf3",
      "c5",
      "Ne2",
      "Be7"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}} and a solid pawn chain.",
      "White reinforces the center with {{square d4}}.",
      "Black challenges the center immediately.",
      "B{{square d3}} is an offbeat but logical bishop development that aims for quick castling and active piece play.",
      "Black captures on {{square e4}} and asks White to justify the early bishop move.",
      "Bx{{square e4}} wins the pawn back at once and keeps the bishop active.",
      "N{{square f6}} develops with tempo by attacking the bishop again.",
      "B{{square f3}} keeps the bishop on a useful diagonal and avoids giving Black an easy target.",
      "...{{square c5}} is the normal French reaction after the exchange on {{square e4}}: hit the center and challenge White to justify the bishop setup.",
      "N{{square e2}} supports the center and keeps options like {{square f4}} or {{square g3}} available.",
      "B{{square e7}} completes development and prepares kingside castling."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-13",
    "name": "Tarrasch Variation with Nc3",
    "description": "Alternative knight development",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "c5",
      "c3",
      "cxd4",
      "cxd4",
      "dxe4",
      "Nxe4",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Nf3",
      "O-O",
      "Bd3",
      "b6",
      "O-O",
      "Bb7"
    ],
    "explanations": [
      "White establishes central control with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center immediately.",
      "Tarrasch Variation - Knight develops while keeping {{square c3}} free.",
      "Black attacks the {{square d4}} pawn.",
      "White supports {{square d4}} with {{square c3}}.",
      "Black captures on {{square d4}}, opening the center.",
      "White recaptures, maintaining central control.",
      "Black captures on {{square e4}}, exchanging pawns.",
      "White recaptures with knight.",
      "Bishop check, pinning the knight.",
      "White develops knight to {{square c3}} instead of blocking with bishop.",
      "Black develops knight, attacking the {{square e4}} knight.",
      "White develops the kingside knight.",
      "Black castles, bringing king to safety.",
      "White develops bishop actively.",
      "Black prepares to develop the bishop to {{square b7}}.",
      "White castles, bringing king to safety.",
      "Black completes development with bishop to {{square b7}}."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-14",
    "name": "Winawer Variation with Bd2",
    "description": "Bishop retreats instead of exf6",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "Bg5",
      "Bb4",
      "e5",
      "h6",
      "Bd2",
      "Bxc3",
      "bxc3",
      "Ne4",
      "Bd3",
      "Nxd2",
      "Qxd2",
      "c5"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "White develops knight, attacking {{square d5}}.",
      "Black develops knight, attacking {{square e4}}.",
      "Bishop pins the knight.",
      "Winawer Variation - Black pins the knight.",
      "White advances, attacking the pinned knight.",
      "Black attacks the bishop.",
      "Bishop retreats, avoiding capture.",
      "Black captures on {{square c3}}, doubling White's pawns.",
      "White recaptures, accepting doubled pawns for bishop pair.",
      "Black's knight moves to {{square e4}}, occupying a strong central outpost.",
      "White develops bishop, attacking the knight.",
      "Knight captures the bishop, exchanging pieces.",
      "Queen recaptures, developing with tempo.",
      "Black attacks the center, challenging White's pawn structure."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-15",
    "name": "Exchange Variation with c4",
    "description": "Queenside pawn break",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "c4",
      "Bb4+",
      "Nc3",
      "Nf6",
      "Nf3",
      "O-O",
      "Be2",
      "dxc4"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White plays {{square c4}}, challenging Black's central pawn.",
      "Bishop check, developing with tempo.",
      "White blocks with knight, developing a piece.",
      "Black develops knight.",
      "White develops the other knight.",
      "Black castles, bringing king to safety.",
      "White develops bishop modestly.",
      "Black captures the pawn, accepting an isolated queen's pawn position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-16",
    "name": "Exchange Variation with Bd6",
    "description": "Bishop develops to d6",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "Bd3",
      "Nc6",
      "c3",
      "Bd6"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops bishop actively.",
      "Black develops knight.",
      "White supports the center with {{square c3}}.",
      "Black develops bishop to {{square d6}}, eyeing the kingside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-17",
    "name": "Tarrasch Variation with exd5",
    "description": "Early pawn capture",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "c5",
      "exd5",
      "Qxd5",
      "dxc5",
      "Bxc5"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks {{square d4}} with {{square c5}}.",
      "White captures on {{square d5}}, simplifying the center.",
      "Queen recaptures, centralizing but potentially exposed.",
      "White captures on {{square c5}}, gaining a pawn.",
      "Bishop recaptures, developing with tempo."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-18",
    "name": "Exchange Variation with Bg4",
    "description": "Bishop pin on the knight",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "Nf3",
      "Nf6",
      "Bd3",
      "Bd6",
      "O-O",
      "O-O",
      "c3",
      "Bg4"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight.",
      "Black develops knight.",
      "White develops bishop actively.",
      "Black develops bishop to {{square d6}}.",
      "White castles, bringing king to safety.",
      "Black castles, bringing king to safety.",
      "White supports the center with {{square c3}}.",
      "Bishop pins the knight, creating pressure on White's position."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-19",
    "name": "Tarrasch Variation with Bc4",
    "description": "Active bishop development",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "c5",
      "exd5",
      "Qxd5",
      "Ngf3",
      "cxd4",
      "Bc4",
      "Qd6",
      "O-O",
      "Nf6",
      "Nb3",
      "Nc6",
      "Nbxd4",
      "Nxd4",
      "Nxd4",
      "Be7"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks {{square d4}} with {{square c5}}.",
      "White captures on {{square d5}}, simplifying.",
      "Queen recaptures, centralizing.",
      "White develops the other knight.",
      "Black captures on {{square d4}}.",
      "Bishop develops actively to {{square c4}}, eyeing {{square f7}}.",
      "Queen retreats to {{square d6}}, defending {{square f7}}.",
      "White castles, bringing king to safety.",
      "Black develops knight.",
      "White's knight moves to {{square b3}}, eyeing {{square d4}} and {{square c5}} squares.",
      "Black develops the other knight.",
      "White captures on {{square d4}} with knight.",
      "Black recaptures with knight.",
      "White recaptures with the other knight.",
      "Black develops bishop, preparing kingside play."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-20",
    "name": "Tarrasch Variation with Bb5",
    "description": "Bishop pin on c6",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "c5",
      "Ngf3",
      "cxd4",
      "Nxd4",
      "Nc6",
      "Bb5",
      "Ne7"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Tarrasch Variation - Knight develops.",
      "Black attacks {{square d4}} with {{square c5}}.",
      "White develops the other knight.",
      "Black captures on {{square d4}}.",
      "White recaptures with knight.",
      "Black develops knight, attacking {{square d4}}.",
      "Bishop pins the knight.",
      "Knight moves to {{square e7}}, breaking the pin while developing."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-21",
    "name": "Winawer Variation with g5",
    "description": "Kingside pawn advance",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "Bg5",
      "Bb4",
      "e5",
      "h6",
      "Bh4",
      "g5"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "White develops knight, attacking {{square d5}}.",
      "Black develops knight, attacking {{square e4}}.",
      "Bishop pins the knight.",
      "Winawer Variation - Black pins the knight.",
      "White advances, attacking the knight.",
      "Black attacks the bishop.",
      "Bishop retreats to {{square h4}}.",
      "Black advances {{square g5}}, attacking the bishop and gaining space on the kingside."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-22",
    "name": "Exchange Variation with Bg5 and Bg4",
    "description": "Mutual bishop pins",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "exd5",
      "exd5",
      "Nf3",
      "Nf6",
      "Bd3",
      "Bd6",
      "O-O",
      "O-O",
      "Bg5",
      "Bg4"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Exchange Variation - White simplifies.",
      "Black recaptures, maintaining symmetry.",
      "White develops knight.",
      "Black develops knight.",
      "White develops bishop actively.",
      "Black develops bishop to {{square d6}}.",
      "White castles, bringing king to safety.",
      "Black castles, bringing king to safety.",
      "White pins the knight with bishop.",
      "Black pins White's knight with bishop, creating symmetrical tension."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-23",
    "name": "Advance Variation: a3 stops ...Nb4",
    "description": "Preventive queenside move that stops ...Nb4, but Black can still gain space and play on the dark squares.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Qb6",
      "Nf3",
      "Nc6",
      "a3",
      "c4",
      "Nbd2",
      "Na5",
      "Be2",
      "Bd7"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "Advance Variation - White gains space.",
      "Black attacks {{square b2}} with queen.",
      "White supports {{square d4}} with {{square c3}}.",
      "Queen continues pressure on queenside.",
      "White develops knight.",
      "Black develops knight.",
      "{{square a3}} is mainly about stopping ...N{{square b4}} and keeping Black's queenside pieces from jumping in too easily.",
      "...{{square c4}} gains space and fixes the queenside structure, even though it also commits Black to that side of the board.",
      "White develops knight, preparing to challenge the {{square c4}} pawn.",
      "N{{square a5}} supports the {{square c4}} pawn and makes it harder for White to challenge that wedge cleanly.",
      "White develops bishop modestly.",
      "Black develops bishop, connecting rooks."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-24",
    "name": "Classical Variation with f4",
    "description": "Kingside pawn advance",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "e5",
      "Nfd7",
      "f4",
      "c5",
      "Nf3",
      "Nc6",
      "Be3",
      "cxd4",
      "Nxd4",
      "Bc5",
      "Qd2",
      "O-O"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black prepares ...{{square d5}}.",
      "White reinforces with {{square d4}}.",
      "Black challenges the center.",
      "White develops knight, attacking {{square d5}}.",
      "Black develops knight, attacking {{square e4}}.",
      "White advances, attacking the knight.",
      "Knight retreats to {{square d7}}.",
      "White advances {{square f4}}, supporting the {{square e5}} pawn and gaining space.",
      "Black attacks the center with {{square c5}}.",
      "White develops knight.",
      "Black develops the other knight.",
      "White develops bishop, supporting the center.",
      "Black captures on {{square d4}}.",
      "White recaptures with knight.",
      "Black develops bishop with tempo.",
      "Queen moves to {{square d2}}, connecting rooks and defending {{square d4}}.",
      "Black castles, bringing king to safety."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-25",
    "name": "Tarrasch Trap: Kf1 and Bxh7+",
    "description": "The Kf1 Tarrasch idea where White sidesteps the check and punishes an automatic castle.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "Nf6",
      "e5",
      "Nfd7",
      "Bd3",
      "c5",
      "c3",
      "Nc6",
      "Ne2",
      "Qb6",
      "Nf3",
      "cxd4",
      "cxd4",
      "Bb4+",
      "Kf1",
      "O-O",
      "Bxh7+",
      "Kxh7",
      "Ng5+",
      "Kg8",
      "Qd3"
    ],
    "explanations": [
      "White claims the center with {{square e4}}.",
      "French Defense - Black keeps the structure solid and prepares ...{{square d5}}.",
      "White reinforces the center with {{square d4}}.",
      "Black challenges the center immediately.",
      "The Tarrasch keeps {{square c2}}-{{square c3}} available and avoids an early pin on the {{square c3}} knight.",
      "Black develops naturally and attacks {{square e4}}.",
      "White gains space and asks the knight to move.",
      "The retreat keeps pressure on {{square e5}} and supports the usual ...{{square c5}} break.",
      "B{{square d3}} points at {{square h7}}, which matters later if Black gets careless with castling.",
      "Black starts the standard French counterplay against the center.",
      "White supports the chain and keeps {{square d4}} defended.",
      "Black adds more pressure to {{square d4}}.",
      "N{{square e2}} is a key Tarrasch move because it reinforces {{square d4}} without blocking the c-pawn.",
      "...Q{{square b6}} is thematic. Black increases the pressure on {{square d4}} and watches {{square b2}} at the same time.",
      "N{{square f3}} adds another defender and finishes the basic setup.",
      "Black trades on {{square d4}} to strip away one defender from the base of the chain.",
      "White recaptures and keeps the center together.",
      "The check looks active, but it also gives White a tactical option if Black autopilots.",
      "K{{square f1}} is the point of the line. White gives up castling rights but keeps the pieces coordinated for an attack.",
      "Castling here is the mistake. Black walks into a version of the Greek gift that works even without the queen going to {{square h5}}.",
      "Bx{{square h7}}+ drags the king out and starts the attack immediately.",
      "Black accepts the bishop, but the king is now exposed.",
      "N{{square g5}}+ forces the king to keep walking and opens the route for the queen.",
      "K{{square g8}} is natural, but the king is still short of defenders.",
      "Q{{square d3}} is the key twist from the transcript. The queen switches to the {{square d3}}-{{square h7}} route because the knight blocks the usual Q{{square h5}} idea."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-26",
    "name": "Tarrasch Trap: ...f6 met by Nf4 and Nxe6",
    "description": "When Black avoids castling with ...f6, White can hit e6 and jump into the dark squares.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nd2",
      "Nf6",
      "e5",
      "Nfd7",
      "Bd3",
      "c5",
      "c3",
      "Nc6",
      "Ne2",
      "Qb6",
      "Nf3",
      "cxd4",
      "cxd4",
      "Bb4+",
      "Kf1",
      "f6",
      "Nf4",
      "fxe5",
      "Nxe6"
    ],
    "explanations": [
      "White takes space in the center.",
      "Black chooses the French setup with ...{{square e6}} and ...{{square d5}} coming next.",
      "White builds the classical pawn center.",
      "Black challenges it immediately.",
      "The Tarrasch keeps options flexible and avoids an early ...B{{square b4}} pin on {{square c3}}.",
      "Black develops and attacks {{square e4}}.",
      "White gains space and fixes the chain.",
      "The knight drops back to support ...{{square c5}} and keep pressure on {{square e5}}.",
      "B{{square d3}} points at {{square h7}} and keeps attacking chances alive.",
      "Black starts the standard French counterplay against {{square d4}}.",
      "{{square c3}} supports the center and prepares to recapture with a pawn.",
      "N{{square c6}} adds more pressure to {{square d4}}.",
      "N{{square e2}} is the normal Tarrasch reinforcement of the pawn chain.",
      "...Q{{square b6}} increases the pressure on {{square d4}} and asks White to defend accurately.",
      "N{{square f3}} is the practical way to cover {{square d4}} again.",
      "Black liquidates once on {{square d4}} to chip away at the chain.",
      "White recaptures and keeps the central pawn structure intact.",
      "The check still invites the same K{{square f1}} resource.",
      "K{{square f1}} sidesteps the check and keeps the attacking pieces ready.",
      "...{{square f6}} is Black's attempt to avoid castling into Bx{{square h7}}+ and hit {{square e5}} immediately.",
      "N{{square f4}} is stronger than a routine recapture. White hits {{square e6}} and starts playing directly at the king.",
      "Black grabs the pawn, but that opens the {{square e6}} square for White's knight jump.",
      "Nx{{square e6}} is the key tactical point. The knight attacks {{square g7}}, controls {{square f8}} so castling is impossible, and keeps Black under immediate pressure."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-27",
    "name": "Advance Trap: 7.Bb5? met by ...Bd7 and ...Nxe5",
    "description": "A common developing move that actually helps Black win the e5 pawn.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Nc6",
      "Bb5",
      "Bd7",
      "Nf3",
      "Nxe5"
    ],
    "explanations": [
      "White takes space in the center.",
      "Black chooses the French structure and prepares ...{{square d5}}.",
      "White reinforces the center.",
      "Black challenges the center immediately.",
      "The Advance grabs space, but the pawn chain can become a target.",
      "...{{square c5}} is the standard break against that chain.",
      "{{square c3}} keeps the chain together, but it also makes the position resemble French structures Black often knows well.",
      "N{{square c6}} adds more pressure to {{square d4}} and {{square e5}}.",
      "B{{square b5}} looks natural, but here it is usually the wrong square because the bishop becomes a tactical target.",
      "...B{{square d7}} pretends to solve a pin, but the real point is to prepare a tactic against {{square e5}}.",
      "N{{square f3}} is a normal move, yet it lets Black use the idea immediately.",
      "...Nx{{square e5}} is the shock move from the transcript. If White takes the knight, Black takes the {{bishop b5 full}} and wins the {{square e5}} pawn anyway."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-28",
    "name": "Advance Plan: ...Rc8, ...Nb4, and the trapped rook idea",
    "description": "Black uses ...Rc8 and ...Nb4 to trade off Bd3 or trap the rook if the bishop retreats.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "e5",
      "c5",
      "c3",
      "Nc6",
      "Nf3",
      "Bd7",
      "Bd3",
      "Rc8",
      "O-O",
      "cxd4",
      "cxd4",
      "Nb4",
      "Be2",
      "Nc2"
    ],
    "explanations": [
      "White takes space in the center.",
      "Black enters the French structure and prepares to challenge it.",
      "White reinforces the center.",
      "Black strikes at it immediately.",
      "The Advance gains space but also leaves Black clear strategic targets.",
      "...{{square c5}} is the standard undermining break.",
      "{{square c3}} supports {{square d4}} and keeps the chain intact.",
      "N{{square c6}} adds pressure to {{square d4}} and keeps the queenside flexible.",
      "N{{square f3}} is normal development and helps support {{square d4}}.",
      "...B{{square d7}} is a practical setup move that prepares queenside development without committing the queen.",
      "B{{square d3}} is White's key attacking bishop in many Advance French positions.",
      "...R{{square c8}} looks quiet, but it prepares a concrete idea on the c-file.",
      "White castles normally.",
      "Black trades on {{square d4}} to remove one defender from the pawn chain.",
      "White keeps the center together with the c-pawn.",
      "...N{{square b4}} goes after the {{bishop d3 full}}, which is the main attacking piece in White's setup.",
      "Retreating the bishop looks safe, but it walks into the point of ...R{{square c8}}.",
      "...N{{square c2}} is the trap. The {{rook c8 full}} protects the knight, and White suddenly has a {{rook a1 full}} that is very hard to save."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-29",
    "name": "Fort Knox Variation: bishop reroute to c6",
    "description": "Black solves the bad bishop problem with ...Bd7, ...Bc6, and a clean Fort Knox setup.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "dxe4",
      "Nxe4",
      "Bd7",
      "Nf3",
      "Bc6",
      "Bd3",
      "Nd7",
      "O-O",
      "Ngf6",
      "Nxf6+",
      "Qxf6"
    ],
    "explanations": [
      "White takes the center with {{square e4}}.",
      "Black chooses the French structure and prepares ...{{square d5}}.",
      "White reinforces the center.",
      "Black challenges it immediately.",
      "N{{square c3}} is the classical way to defend {{square e4}}.",
      "Black simplifies at once and heads for a setup that avoids cramped piece play.",
      "White recaptures with the knight and keeps a lead in development.",
      "...B{{square d7}} starts the Fort Knox plan and prepares to reroute the so-called bad bishop.",
      "White develops naturally.",
      "...B{{square c6}} is the point. The bishop reaches an active diagonal instead of staying buried behind the {{square e6}} pawn.",
      "B{{square d3}} develops toward the kingside and keeps typical attacking ideas alive.",
      "N{{square d7}} completes development and supports the key central and queenside squares around the bishop.",
      "White castles normally.",
      "Ngf6 adds another attacker to White's centralized knight and finishes the basic setup.",
      "White usually trades, hoping Black will have to recapture awkwardly.",
      "Qx{{square f6}} is the transcript idea. The queen recapture keeps the knight free, preserves the bishop setup, and puts direct pressure on White's kingside pieces."
    ]
  },
  {
    "category": "French Defense",
    "id": "french-30",
    "name": "Fort Knox Tactic: ...Bxf3 counterstrike",
    "description": "After ...Qxf6, a direct pin on the queen can fail because Black has a tactical bishop shot.",
    "moves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "dxe4",
      "Nxe4",
      "Bd7",
      "Nf3",
      "Bc6",
      "Bd3",
      "Nd7",
      "O-O",
      "Ngf6",
      "Nxf6+",
      "Qxf6",
      "Bg5",
      "Bxf3",
      "Bxf6",
      "Bxd1"
    ],
    "explanations": [
      "White takes the center with {{square e4}}.",
      "Black chooses the French structure and prepares ...{{square d5}}.",
      "White reinforces the center.",
      "Black challenges it immediately.",
      "N{{square c3}} is the classical defense of {{square e4}}.",
      "Black simplifies and heads for the Fort Knox setup.",
      "White recaptures with the knight.",
      "...B{{square d7}} begins the bishop reroute.",
      "White develops a knight and prepares kingside castling.",
      "...B{{square c6}} activates the light-squared bishop on a much better diagonal.",
      "White points a bishop at the kingside.",
      "N{{square d7}} keeps the setup coordinated.",
      "White castles.",
      "...Ngf6 attacks the {{square e4}} knight and finishes development.",
      "White exchanges on {{square f6}}.",
      "Black recaptures with the queen, keeping the structure and pressure exactly as the transcript recommends.",
      "B{{square g5}} looks like it might trap the queen, so many players play it quickly.",
      "...Bx{{square f3}} is the counterstrike. Black does not panic about the queen and hits the defender instead.",
      "White grabs the queen, but this is the tactical mistake.",
      "...Bx{{square d1}} is the point. Black wins White's queen back and the whole sequence leaves Black ahead materially."
    ]
  }
]);
