import { withOpeningFeedback } from "./feedback";

// src/openings/friedLiverAttackLines.js

// SEO / page intro text for Fried Liver Attack drills
export const friedLiverSEOText = `
The Fried Liver Attack is one of the sharpest tactical weapons in the Italian Game, arising after
1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. Ng5.

White attacks the sensitive f7 square, often sacrifices on f7, and tries to drag Black's king into the center.
These drills cover the main Ke8 and Ke6 king retreats, common tactical blunders after Bxd5, and practical sidelines like the Traxler and the 5...Na5 defense.

Use this page to rehearse forcing move orders, spot Qf7 mate patterns, and understand when the attack is winning and when it should be toned down.
`;

export const friedLiverAttackLines = withOpeningFeedback([
  // Categories: Main line, Ke6 king-walk, Declined lines, Traxler, Two Knights sidelines

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-ke8-retreat",
    name: "Main line: Ke8 retreat, recover on d5",
    description: "Classic Fried Liver. Black retreats, White takes on d5, and the direct Qf7 mate threat remains the main point.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5"],
    explanations: [
      "Let's learn the Fried Liver Attack! Start with pawn to {{square e4}} and build toward quick development and pressure on {{square f7}}.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Put the bishop on the long diagonal and start aiming at {{square f7}}.",
      "Black develops, but this allows the sharp Two Knights positions.",
      "This is the key Fried Liver move. White attacks {{square f7}} and invites ...{{square d5}}.",
      "Black hits the center and opens lines. This is standard, but it also makes the coming sacrifice possible.",
      "White accepts and clears the {{square e4}} square while opening the position.",
      "This natural recapture is the move the Fried Liver is built against.",
      "The signature sacrifice. White gives up the knight to drag the king out and expose the dark squares.",
      "Black accepts the piece, but the king is now in the open and the {{knight d5 full}} is pinned.",
      "Queen out with check. White attacks the exposed king and adds a second attacker to the pinned {{knight d5 full}}.",
      "This retreat is solid compared with the wilder king walk, but it still leaves Black under heavy pressure.",
      "White wins the knight back and keeps the real threat in view: Q{{square f7}} mate is now hanging over the position."
    ]
  },


  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-ke8-nd4-blunder-mate",
    name: "Main line: ...Nd4 loses to Qf7 mate",
    description: "After Ke8 and Bxd5, ...Nd4 looks active but it stops defending f7 and loses on the spot.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Nd4", "Qf7#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is playable, but only if Black respects the Q{{square f7}} mating idea.",
      "White recovers the pinned knight and keeps the attack going.",
      "This move attacks the queen and {{square c2}}, but it abandons control of {{square f7}}.",
      "Mate. The queen lands on {{square f7}} with support from the {{bishop d5 full}}, exactly the pattern this line is trying to reach."
    ]
  },


  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-kg8-and-quick-mate",
    name: "Main line: Kg8 walks into mate",
    description: "If Black runs to g8 instead of e8, the attack becomes forcing and White mates quickly.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Kg8", "Bxd5+", "Qxd5", "Qxd5+", "Be6", "Qxe6#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "Running to {{square g8}} looks safer, but it actually walks into a forcing mating net.",
      "White takes the pinned knight with check and keeps every move forcing.",
      "Black tries to trade pieces and slow the attack.",
      "White welcomes the queen trade because it comes with check and keeps the king exposed.",
      "Black blocks, but this places the bishop on the mating square.",
      "Mate on {{square e6}}. This is the clean finish the transcript points to after ...K{{square g8}}."
    ]
  },


  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-bd7-blunder-mate",
    name: "Main line: ...Bd7 loses to Qf7 mate",
    description: "After Bxd5, ...Bd7 looks like development, but it still leaves the f7 square undefended.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Bd7", "Qf7#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with the Q{{square f7}} mate threat.",
      "White recovers the pinned knight and keeps the attack going.",
      "Natural development is not enough here. The {{square f7}} square is still collapsing.",
      "Mate. This is one of the direct transcript blunders after Bx{{square d5}}."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-nb4-blunder-mate",
    name: "Main line: ...Nb4 loses to Qf7 mate",
    description: "The knight jump looks active, but it ignores the only threat that matters.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Nb4", "Qf7#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with Q{{square f7}}.",
      "White recovers the pinned knight and keeps the attack going.",
      "This knight jump attacks {{square c2}}, but it is completely irrelevant to the mating threat.",
      "Mate. The attack is so forcing here that Black does not get time for side threats."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-bc5-blunder-mate",
    name: "Main line: ...Bc5 loses to Qf7 mate",
    description: "Developing the bishop does not matter when the king is still getting mated on f7.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Bc5", "Qf7#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with Q{{square f7}}.",
      "White recovers the pinned knight and keeps the attack going.",
      "This bishop move develops a piece, but it still fails to address the direct mate.",
      "Mate. Another transcript blunder that dies immediately on {{square f7}}."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-bd6-blunder-mate",
    name: "Main line: ...Bd6 loses to Qf7 mate",
    description: "Even a blocking bishop move is too slow once White has reached Bxd5 with threats intact.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Bd6", "Qf7#"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with Q{{square f7}}.",
      "White recovers the pinned knight and keeps the attack going.",
      "Trying to interpose or develop is still too slow here.",
      "Mate. The {{bishop d6 full}} does nothing against the queen-bishop attack on {{square f7}}."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-qxd5-loses-queen",
    name: "Main line: ...Qxd5 just drops the queen",
    description: "If Black gets impatient and takes the bishop with the queen, White simply wins the queen back.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Qxd5", "Qxd5"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with Q{{square f7}}.",
      "White recovers the pinned knight and keeps the attack going.",
      "This queen grab is a pure blunder. The queen walks onto a square where White can trade it off immediately.",
      "White simply takes the queen. This is the transcript's free queen branch."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-qe7-bxc6-and-qxc6-check",
    name: "Main line: ...Qe7 allows Bxc6+ and Qxc6+",
    description: "Qe7 covers f7, but it still lets White remove the knight on c6 and hit the a8 rook with check.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5", "Qe7", "Bxc6+", "bxc6", "Qxc6+"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. White immediately attacks the king and the {{knight d5 full}}.",
      "K{{square e8}} is only safe if Black deals with Q{{square f7}}.",
      "White recovers the pinned knight and keeps the attack going.",
      "This does stop the immediate mate on {{square f7}}, so it is a better try than the outright blunders.",
      "White switches targets and removes the {{knight c6 full}} with check.",
      "Black usually recaptures, but that opens a new tactical problem.",
      "Queen takes {{square c6}} with check. White wins the {{pawn c6 full}} and attacks the {{rook a8 full}} at the same time, exactly the tactic described in the transcript."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-greedy-defense-nxa1-and-rd1",
    name: "Greedy defense: ...Nxa1 and Rd1",
    description: "Black grabs rook, White races with development and threats.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "c6", "d4", "Nxc2", "dxe5", "Nxa1", "Rd1"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Most resilient move. Black keeps the king exposed, but at least the king now defends the {{knight d5 full}}.",
      "Add a third attacker to {{square d5}}. The pinned knight is still the key target.",
      "Jump toward {{square c2}} and {{square d3}}, counterattacking.",
      "Castle and bring the rook into play.",
      "Forced to keep the {{knight b4 full}} supporting {{square d5}}. If that knight gets chased, Black loses the defender on {{square d5}}.",
      "Hit the center and open lines while the king is unsafe.",
      "Grab material and counterattack.",
      "Open lines and win a pawn with tempo.",
      "Win the {{rook a1 full}}, very greedy.",
      "Bring a rook to the open file and threaten the king and queen.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-4-nxe4-5-bxf7",
    name: "Declined: 4...Nxe4 5.Bxf7+",
    description: "Black counters in the center, White checks and pushes d4.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "Nxd4", "c3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Take a central pawn and block lines.",
      "Chase the knight and open c-file ideas.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-win-the-queen-with-bxd8",
    name: "Declined: win the queen with Bxd8",
    description: "Tactical sequence that wins material after forcing king captures.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "Nxg5", "Bxg5+", "Kxf7", "Bxd8"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Remove the attacker to reduce threats.",
      "Regain material with tempo and keep the king exposed.",
      "Accept the sacrifice and expose the king.",
      "Win the {{queen d8 full}} after forcing king captures.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-h6-and-d5-space-gain",
    name: "Declined: h6 and d5 space gain",
    description: "Kick the knight, then build a strong center while king is exposed.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "h6", "Nxe4", "Kxf7", "d5"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Kick the knight and force a decision.",
      "Take the central knight and reduce counterplay.",
      "Accept the sacrifice and expose the king.",
      "Gain space and open lines, also hits pieces.",
    ]
  },


  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-qd3-pressure",
    name: "Ke6 line: Nc3, Bxd5+, Qd3 pressure",
    description: "Against the king walk to e6, White keeps attacking the pinned knight on d5 and centralizes the queen again.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nd4", "Bxd5+", "Kd6", "Qd3"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point straight at {{square f7}}.",
      "Black develops, but the {{square f7}} square is now the target.",
      "This is the Fried Liver setup.",
      "Black challenges the center and opens lines.",
      "White takes and keeps the position open.",
      "Black recaptures in the usual way.",
      "White sacrifices on {{square f7}} to drag the king out.",
      "Black accepts, but the king is exposed and the {{knight d5 full}} is pinned.",
      "Queen check. The king has to keep moving.",
      "This is Black's most resilient practical try from the transcript. The king stays ugly, but it does help defend {{square d5}}.",
      "This is the important improvement. White adds a third attacker to the pinned {{knight d5 full}}.",
      "Black counters by hitting the queen and {{square c2}}, trying to distract White from the attack.",
      "White ignores the queen hit because checking and removing the pinned defender matters more.",
      "The king keeps walking, which shows Black still has not solved the king safety problem.",
      "Centralize again. White keeps pressure on the king and stays ready to meet Black's material grabs with more checks."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-nd4-counterattack-ne4-mate",
    name: "Ke6 line: ...Nd4 counterattack, Ne4#",
    description: "Black hits the queen and the c2 pawn, but White keeps the initiative and mates after the greedy rook grab.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nd4", "Bxd5+", "Kd6", "Qf7", "Nxc2+", "Kd1", "Nxa1", "Ne4#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Most resilient move. Black keeps the king exposed, but at least the king now defends the {{knight d5 full}}.",
      "Add a third attacker to {{square d5}}. The pinned knight is still the key target.",
      "Hit the queen and {{square c2}}, trying to distract White from the attack.",
      "Ignore the queen threat because the check matters more than Black's counterplay.",
      "The king runs to {{square d6}}, but it is still stuck in the middle of the board.",
      "Step onto {{square f7}} and threaten N{{square e4}}#, so Black is already in a mating net.",
      "Grab the {{square c2}} pawn with check and try to cash in on the counterattack.",
      "Step to {{square d1}}. White keeps the attack alive and does not need the rook to finish the game.",
      "Black wins the {{rook a1 full}}, but the king is still completely exposed.",
      "Mate. The knight jumps to {{square e4}} and seals every escape square around the king.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-nxc2-and-bxd5",
    name: "Ke6 line: ...Nxc2 and Bxd5+",
    description: "Black counterattacks on c2, White keeps tempo with check.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "Nxc2", "Bxd5+"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Jump toward {{square c2}} and {{square d3}}, counterattacking.",
      "Castle and bring the rook into play.",
      "Grab material and counterattack.",
      "Same idea but with check to keep the king boxed in.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-re1-and-bf4",
    name: "Ke6 line: Re1+ and Bf4+",
    description: "Central break and rook check to keep the king in danger.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "c6", "d4", "exd4", "Re1+", "Kd6", "Bf4+"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Jump toward {{square c2}} and {{square d3}}, counterattacking.",
      "Castle and bring the rook into play.",
      "Forced again. Black needs the {{knight b4 full}} anchored to {{square d5}}, otherwise White wins that knight next.",
      "Hit the center and open lines while the king is unsafe.",
      "Continue the main tactical plan and improve piece activity.",
      "Check on the e-file and pin defenders.",
      "King steps, trying to escape the e-file checks.",
      "Develop with check and improve piece activity.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-long-forcing-mate-net",
    name: "Ke6 line: long forcing mate net",
    description: "Long tactical line ending in Bf4 mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "Qa5+", "Bd2", "Qxb5", "Bf4#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support {{square d5}} and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Check to force king responses and keep tempo.",
      "Block checks and set up the finishing net.",
      "Grab the queen or a key defender to finish the attack.",
      "Deliver checkmate with the bishop on the key diagonal.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-alternative-finish-with-nf7",
    name: "Ke6 line: alternative finish with Nf7",
    description: "Similar structure but different endgame tactics and forks.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "b6", "Qg3+", "Kb7", "Nd6+", "Kc6", "Nf7"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support {{square d5}} and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Create escape squares and cover key diagonals.",
      "Bring the queen in with check and tighten the net.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork with check and keep the king trapped.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork threats and keep the king under pressure.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-o-o-o-and-rook-lift",
    name: "Ke6 line: O-O-O and rook lift",
    description: "Castle long and attack with rook checks and bishops.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "exd4", "Bf4", "dxc3", "O-O-O", "cxb2+", "Kb1", "c6", "Rhe1+", "Kf7", "Bc7+", "Ke8", "Bxd8", "Kxd8", "Bxd5"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Continue the main tactical plan and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Castle long to connect rooks and bring the rook to the d-file attack.",
      "Create a passed pawn with check and force the king move.",
      "Step away from checks and protect the rook/king.",
      "Support {{square d5}} and create luft for pieces, also kicks attackers later.",
      "Bring the rook into the e-file with check, piling on the king.",
      "Continue the main tactical plan and improve piece activity.",
      "Force a check that restricts the king and can win material.",
      "Step back, keeping pieces near the king.",
      "Win the {{queen d8 full}} after forcing king captures.",
      "Continue the main tactical plan and improve piece activity.",
      "Remove the centralized defender and keep the initiative.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-queen-side-mate-qa3",
    name: "Ke6 line: queen-side mate Qa3",
    description: "Forcing king hunt that ends with Qa3 mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "Bxe6", "Qc3", "b6", "Bf4+", "Kb7", "Nd6+", "Ka6", "Qa3#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at {{square f7}} and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to {{square d5}} and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support {{square d5}} and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Capture to remove a defender and open lines.",
      "Continue the main tactical plan and improve piece activity.",
      "Create escape squares and cover key diagonals.",
      "Develop with check and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork with check and keep the king trapped.",
      "Continue the main tactical plan and improve piece activity.",
      "Checkmate. This line ends immediately.",
    ]
  },


  {
    category: "Fried Liver Attack",
    id: "fried-liver-traxler-4-bc5-sideline",
    name: "Traxler: take on f7 and evacuate",
    description: "If Black plays 4...Bc5, do not force standard Fried Liver ideas. Take on f7+, retreat, and play a more normal attacking game.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Bc5", "Bxf7+", "Ke7", "Bb3"],
    explanations: [
      "Start with {{square e4}} and claim the center.",
      "Black mirrors the center and keeps the game open.",
      "Develop with tempo by attacking {{square e5}}.",
      "Defend {{square e5}} and develop normally.",
      "Develop and point at {{square f7}}.",
      "Black develops and allows sharp play.",
      "White attacks {{square f7}}, but the exact Fried Liver sacrifice only works against the usual ...{{square d5}} structure.",
      "This is the Traxler counterattack. The transcript is right to warn that you should not mindlessly force the normal Fried Liver here.",
      "Take on {{square f7}} with check and pull the king out before Black gets the full counterattack.",
      "Black steps up and tries to use the active bishops and king to create tactics.",
      "Evacuate the bishop. White keeps the extra pawn and should now play sound attacking chess instead of pretending every line is the same."
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-two-knights-5-na5-bishop-chase",
    name: "Two Knights: 5...Na5 bishop chase",
    description: "Black hits the bishop, White keeps development and structure.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Na5", "Bb5+", "c6", "dxc6", "bxc6", "Bd3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack {{square e5}} and develop the king knight.",
      "Defend {{square e5}} and develop.",
      "Target {{square f7}} and develop with initiative.",
      "Attack {{square e4}} and develop.",
      "Pressure {{square f7}} and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Best practical defense. Black avoids the losing ...Nx{{square d5}} recapture and heads for a more balanced position.",
      "Check and force a concession in development.",
      "Support {{square d5}} and create luft for pieces, also kicks attackers later.",
      "Win the {{square c6}} pawn and open files.",
      "Recapture and open the b-file.",
      "Develop and aim at {{square h7}} and the center.",
    ]
  },

]);
