// src/openings/friedLiverAttackLines.js

// SEO / page intro text for Fried Liver Attack drills
export const friedLiverSEOText = `
The Fried Liver Attack is a sharp tactical line that can arise from the Italian Game, Two Knights Defense:
1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. Ng5.

White aims at the sensitive f7 square and is often willing to sacrifice a knight to drag Black's king into the open.
These drills focus on forcing lines, checks, and common tactical motifs like king hunts, forks, and rapid development.

Use this page to practice the exact move orders and understand why each move is played.
`;

export const friedLiverAttackLines = [
  // Categories: Main line, Ke6 king-walk, Declined lines, Traxler, Two Knights sidelines
  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-ke8-retreat",
    name: "Main line: Ke8 retreat",
    description: "Classic Fried Liver sacrifice, queen check, and bishop takes d5.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke8", "Bxd5"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Step back, keeping pieces near the king.",
      "Remove the centralized defender and keep the initiative.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-main-line-kg8-and-quick-mate",
    name: "Main line: Kg8 and quick mate",
    description: "Forcing queen trade and a direct mate on e6.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Kg8", "Bxd5+", "Qxd5", "Qxd5+", "Be6", "Qxe6#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Run to safety on the kingside.",
      "Same idea but with check to keep the king boxed in.",
      "Return material and trade attackers if possible.",
      "Trade queens under check to reduce danger, if allowed.",
      "Develop and cover key squares, also blocking lines.",
      "Deliver mate on e6, using the queen and bishop coordination.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-greedy-defense-nxa1-and-rd1",
    name: "Greedy defense: ...Nxa1 and Rd1",
    description: "Black grabs rook, White races with development and threats.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "c6", "d4", "Nxc2", "dxe5", "Nxa1", "Rd1"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Jump toward c2 and d3, counterattacking.",
      "Castle and bring the rook into play.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Hit the center and open lines while the king is unsafe.",
      "Grab material and counterattack.",
      "Open lines and win a pawn with tempo.",
      "Win the rook on a1, very greedy.",
      "Bring a rook to the open file and threaten the king and queen.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-4-nxe4-5-bxf7",
    name: "Declined: 4...Nxe4 5.Bxf7+",
    description: "Black counters in the center, White checks and pushes d4.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "Nxd4", "c3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Take a central pawn and block lines.",
      "Chase the knight and open c-file ideas.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-win-the-queen-with-bxd8",
    name: "Declined: win the queen with Bxd8",
    description: "Tactical sequence that wins material after forcing king captures.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "Nxg5", "Bxg5+", "Kxf7", "Bxd8"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Remove the attacker to reduce threats.",
      "Regain material with tempo and keep the king exposed.",
      "Accept the sacrifice and expose the king.",
      "Win the queen on d8 after forcing king captures.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-declined-h6-and-d5-space-gain",
    name: "Declined: h6 and d5 space gain",
    description: "Kick the knight, then build a strong center while king is exposed.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Nxe4", "Bxf7+", "Ke7", "d4", "h6", "Nxe4", "Kxf7", "d5"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Take the central knight and reduce counterplay.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Hit the center and open lines while the king is unsafe.",
      "Kick the knight and force a decision.",
      "Take the central knight and reduce counterplay.",
      "Accept the sacrifice and expose the king.",
      "Gain space and open lines, also hits pieces.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-qd3-pressure",
    name: "Ke6 line: Qd3 pressure",
    description: "King walks to e6, White keeps checks and centralized queen.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nd4", "Bxd5+", "Kd6", "Qd3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Jump to an outpost and hit key squares.",
      "Same idea but with check to keep the king boxed in.",
      "King steps, trying to escape the e-file checks.",
      "Centralize the queen and keep pressure on the king.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-nxc2-and-bxd5",
    name: "Ke6 line: ...Nxc2 and Bxd5+",
    description: "Black counterattacks on c2, White keeps tempo with check.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "Nxc2", "Bxd5+"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Jump toward c2 and d3, counterattacking.",
      "Castle and bring the rook into play.",
      "Grab material and counterattack.",
      "Same idea but with check to keep the king boxed in.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-re1-and-bf4",
    name: "Ke6 line: Re1+ and Bf4+",
    description: "Central break and rook check to keep the king in danger.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4", "O-O", "c6", "d4", "exd4", "Re1+", "Kd6", "Bf4+"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Jump toward c2 and d3, counterattacking.",
      "Castle and bring the rook into play.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Hit the center and open lines while the king is unsafe.",
      "Continue the main tactical plan and improve piece activity.",
      "Check on the e-file and pin defenders.",
      "King steps, trying to escape the e-file checks.",
      "Develop with check and improve piece activity.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-long-forcing-mate-net",
    name: "Ke6 line: long forcing mate net",
    description: "Long tactical line ending in Bf4 mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "Qa5+", "Bd2", "Qxb5", "Bf4#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Check to force king responses and keep tempo.",
      "Block checks and set up the finishing net.",
      "Grab the queen or a key defender to finish the attack.",
      "Deliver checkmate with the bishop on the key diagonal.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-alternative-finish-with-nf7",
    name: "Ke6 line: alternative finish with Nf7",
    description: "Similar structure but different endgame tactics and forks.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "b6", "Qg3+", "Kb7", "Nd6+", "Kc6", "Nf7"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Create escape squares and cover key diagonals.",
      "Bring the queen in with check and tighten the net.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork with check and keep the king trapped.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork threats and keep the king under pressure.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-o-o-o-and-rook-lift",
    name: "Ke6 line: O-O-O and rook lift",
    description: "Castle long and attack with rook checks and bishops.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "exd4", "Bf4", "dxc3", "O-O-O", "cxb2+", "Kb1", "c6", "Rhe1+", "Kf7", "Bc7+", "Ke8", "Bxd8", "Kxd8", "Bxd5"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Continue the main tactical plan and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Castle long to connect rooks and bring the rook to the d-file attack.",
      "Create a passed pawn with check and force the king move.",
      "Step away from checks and protect the rook/king.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Bring the rook into the e-file with check, piling on the king.",
      "Continue the main tactical plan and improve piece activity.",
      "Force a check that restricts the king and can win material.",
      "Step back, keeping pieces near the king.",
      "Win the queen on d8 after forcing king captures.",
      "Continue the main tactical plan and improve piece activity.",
      "Remove the centralized defender and keep the initiative.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-ke6-line-queen-side-mate-qa3",
    name: "Ke6 line: queen-side mate Qa3",
    description: "Forcing king hunt that ends with Qa3 mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Ne7", "d4", "c6", "dxe5", "Kd7", "Bg5", "Kc7", "Bxd5", "cxd5", "Nb5+", "Kb8", "e6", "Bxe6", "Qc3", "b6", "Bf4+", "Kb7", "Nd6+", "Ka6", "Qa3#"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Recapture and centralize a knight.",
      "Sacrifice for initiative by dragging the king out and hitting key squares.",
      "Accept the sacrifice and expose the king.",
      "Check and aim at f7 and the exposed king.",
      "Walk forward, risky but tries to escape immediate tactics.",
      "Develop and add support to d5 and central play.",
      "Retreat to cover key squares and block lines.",
      "Hit the center and open lines while the king is unsafe.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Open lines and win a pawn with tempo.",
      "King keeps walking, trying to avoid direct mates.",
      "Develop and pin or threaten, keeping pressure.",
      "Keep the king away from the center line.",
      "Remove the centralized defender and keep the initiative.",
      "Open lines by capturing.",
      "Jump with check and keep the king boxed in.",
      "Continue the main tactical plan and improve piece activity.",
      "Advance to open lines and create a decisive threat.",
      "Capture to remove a defender and open lines.",
      "Continue the main tactical plan and improve piece activity.",
      "Create escape squares and cover key diagonals.",
      "Develop with check and improve piece activity.",
      "Continue the main tactical plan and improve piece activity.",
      "Fork with check and keep the king trapped.",
      "Continue the main tactical plan and improve piece activity.",
      "Checkmate. This line ends immediately.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-traxler-4-bc5-sideline",
    name: "Traxler: 4...Bc5 sideline",
    description: "Black countergambit, White chooses a safer retreat.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Bc5", "Bxf7+", "Ke7", "Bb3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Enter the Traxler counterattack, aiming for tactics on f2 and the king.",
      "Force the king to move and keep the initiative.",
      "King steps up, trying to survive.",
      "Retreat and keep the bishop safe while staying active.",
    ]
  },

  {
    category: "Fried Liver Attack",
    id: "fried-liver-two-knights-5-na5-bishop-chase",
    name: "Two Knights: 5...Na5 bishop chase",
    description: "Black hits the bishop, White keeps development and structure.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Na5", "Bb5+", "c6", "dxc6", "bxc6", "Bd3"],
    explanations: [
      "Take the center and open lines for pieces.",
      "Mirror the center and fight for space.",
      "Attack e5 and develop the king knight.",
      "Defend e5 and develop.",
      "Target f7 and develop with initiative.",
      "Attack e4 and develop.",
      "Pressure f7 and hint at a quick attack.",
      "Gain space and open lines, also hits pieces.",
      "Accept the challenge and open lines.",
      "Attack the bishop and aim to win the b3 square.",
      "Check and force a concession in development.",
      "Support d5 and create luft for pieces, also kicks attackers later.",
      "Win the c6 pawn and open files.",
      "Recapture and open the b-file.",
      "Develop and aim at h7 and the center.",
    ]
  },

];
