export const italianGameLines = [
  {
    "category": "Italian Game",
    "id": "italian-01",
    "name": "French Attack Transposition",
    "description": "e4 e5 opening transposing to French structure",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7", "f4", "c5", "Nf3", "Nc6", "Be3", "cxd4", "Nxd4", "Bc5", "Qd2", "O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "French Defense - Black prepares to challenge the center with ...d5.",
      "White reinforces the center and prepares to establish a strong pawn duo.",
      "Black immediately challenges White's central pawn structure.",
      "White develops the knight to support the central pawns and attack d5.",
      "Black develops the knight, attacking the e4 pawn and preparing kingside castling.",
      "White advances the pawn, gaining space and attacking the knight.",
      "The knight retreats to a defensive square while supporting the c5 break.",
      "White secures the e5 pawn and prepares a potential kingside expansion.",
      "Black strikes at the center, attacking the d4 pawn and White's pawn chain.",
      "White develops the knight to its natural square, controlling key central squares.",
      "Black develops the knight, increasing pressure on the d4 pawn.",
      "White develops the bishop to support the d4 pawn and prepare queenside castling.",
      "Black captures on d4, forcing the recapture and opening the c-file.",
      "White recaptures with the knight, centralizing the piece and controlling key squares.",
      "Black develops the bishop actively, attacking the knight and pinning it against the queen.",
      "White develops the queen to connect the rooks and prepare queenside castling.",
      "Black castles to safety, completing kingside development and securing the king."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-02",
    "name": "Evans Gambit Accepted - Main Line",
    "description": "Classical Evans Gambit with aggressive play",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "Bxa1", "Re1+", "Ne7", "Bxe7", "Qxe7", "Rxe7+", "Kxe7", "Qxa1"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit! White sacrifices a pawn for rapid development and open lines.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening the c-file and activating the queen's diagonal.",
      "Bishop check - Black pins the knight against the king, creating tactical opportunities.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative and open lines.",
      "Black captures the knight, but helps White open the b-file.",
      "White recaptures, opening the b-file and attacking the bishop.",
      "Black captures the pawn, but the bishop becomes exposed on c3.",
      "Brilliant bishop move! White pins the knight to the king and attacks the rook.",
      "Black captures the rook, winning material but fatally delaying development.",
      "Rook check - White exploits Black's uncastled king and exposed position.",
      "The knight blocks the check, but remains pinned and vulnerable.",
      "White captures the knight, maintaining the pin on the queen.",
      "Black recaptures with the queen, but the queen remains pinned.",
      "Rook captures the queen with check! White's attack reaches decisive proportions.",
      "The king is forced to recapture, losing the right to castle.",
      "White's queen captures the bishop, regaining material with a dominant position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-03",
    "name": "Two Knights Defense - Fried Liver Attempt",
    "description": "Aggressive knight capture line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, accepting the challenge to White's center.",
      "White recaptures, gaining a central pawn and tempo on the knight.",
      "Black develops the bishop actively, targeting the vulnerable f2 square.",
      "White's queen attacks both the knight and the f7 pawn, creating multiple threats.",
      "Bishop sacrifice! Black creates chaos by exposing White's king position.",
      "White's king is forced to capture, losing the right to castle.",
      "Black castles to safety despite the material sacrifice, securing the king.",
      "White captures the knight, but Black has compensation with White's exposed king."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-04",
    "name": "Evans Gambit with Bb6 Retreat",
    "description": "Bishop retreats to b6 instead of capturing",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb6", "e5", "Ng4", "h3", "Nh6", "d5", "Na5", "Bg5", "f6", "exf6"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Black retreats the bishop, declining to enter the complications of Bb4+.",
      "White advances the pawn, gaining space and attacking the knight.",
      "The knight moves to attack the vulnerable f2 square, a typical response to e5.",
      "White attacks the knight, forcing it to move or be captured.",
      "The knight retreats to the edge of the board, passive but safe.",
      "White advances the pawn, gaining space and attacking the knight.",
      "The knight attacks the bishop, gaining tempo while developing.",
      "White develops the bishop with a pin on the f6 pawn.",
      "Black attacks the bishop while challenging the center.",
      "White captures the pawn, opening the e-file and isolating Black's d-pawn."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-05",
    "name": "Evans Gambit with d6 Defense",
    "description": "Black plays d6 to solidify center",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "d6", "Rc1", "Ba5", "Qa4", "O-O", "d5", "Ne5", "Nxe5", "dxe5", "Qxa5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, but helps White open the b-file.",
      "White recaptures, opening the b-file and attacking the bishop.",
      "Black captures the pawn, but the bishop becomes exposed.",
      "White develops the bishop with a pin on the knight to the king.",
      "Solid defensive move - Black supports the center and opens a retreat for the bishop.",
      "White develops the rook, attacking the exposed bishop.",
      "Black retreats the bishop, maintaining the pin on the knight.",
      "White's queen attacks both the bishop and knight simultaneously.",
      "Black castles to safety, completing kingside development.",
      "White advances the pawn, gaining space in the center.",
      "The knight moves to a central outpost, attacking multiple squares.",
      "White captures the knight, eliminating Black's active piece.",
      "Black recaptures, maintaining material equality.",
      "White's queen captures the bishop, equalizing material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-06",
    "name": "Evans Gambit with Bb4 Retreat",
    "description": "Bishop retreats to b4 after capture",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "d6", "Rc1", "Bb4", "Bxb4", "Nxb4", "Qe1+", "Qe7", "Qxb4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, but helps White open the b-file.",
      "White recaptures, opening the b-file and attacking the bishop.",
      "Black captures the pawn, but the bishop becomes exposed.",
      "White develops the bishop with a pin on the knight to the king.",
      "Solid defensive move - Black supports the center.",
      "White develops the rook, attacking the exposed bishop.",
      "Black retreats the bishop, avoiding capture and maintaining activity.",
      "White captures the bishop, eliminating Black's active piece.",
      "Black recaptures with the knight, centralizing the piece.",
      "Queen check - White attacks the knight while developing the queen.",
      "Black blocks the check with the queen, defending the knight.",
      "White captures the knight, regaining material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-07",
    "name": "Evans Gambit Mate",
    "description": "Beautiful mating attack",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "Ncd6", "Qxg7", "Qf6", "Qxf6", "Nxf6", "Re1+", "Kf8", "Bh6+", "Kg8", "Re5", "Nde4", "Nd2", "d6", "Nxe4", "Nxe4", "Re8#"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "Brilliant queen move! White attacks both g7 and the knight simultaneously.",
      "The knight moves to defend g7, but creates new weaknesses.",
      "Queen sacrifice! White captures the g7 pawn, threatening mate on h8.",
      "Black blocks with the queen, attempting to defend.",
      "White captures the queen, eliminating Black's best defender.",
      "Black recaptures, but the position remains critically weak.",
      "Rook check - White exploits the pinned knight and exposed king.",
      "The king moves to f8, the only safe square.",
      "Bishop check - White forces the king back to g8.",
      "The king returns to g8, but now faces a coordinated attack.",
      "White's rook maneuvers to the fifth rank, preparing a mating net.",
      "The knight blocks the rook's path to e8.",
      "White develops the knight, clearing the e-file for the rook.",
      "Black advances the pawn, but it's too late to defend.",
      "White captures the knight, eliminating a key defender.",
      "Black recaptures, but the defense has collapsed.",
      "Checkmate! The rook delivers the final blow on the back rank."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-08",
    "name": "Evans Gambit with h6",
    "description": "Black plays h6 early",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "h6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "d6", "O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Prophylactic move - Black prevents Bg5 but wastes a tempo.",
      "White pushes in the center, executing the Evans Gambit idea.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Solid defensive move - Black supports the center and develops.",
      "White castles to safety, completing development with a comfortable position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-09",
    "name": "Two Knights Defense - Main Line",
    "description": "Classical Two Knights Defense",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qd8", "Rxe4+", "Be7", "Nxd4", "O-O", "Nxc6", "Qxd1+", "Nxd1", "bxc6", "Rxe7"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "The rook moves to pin the knight against the king, creating immediate threats.",
      "Black pushes the pawn to attack the bishop and break the pin.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to safety, but Black's development remains incomplete.",
      "Rook captures the pinned knight with check, exploiting Black's lagging development.",
      "The bishop blocks the check while developing to a natural square.",
      "White's knight recaptures the central pawn, controlling key squares.",
      "Black castles to safety, finally getting the king to relative security.",
      "White captures the knight, creating doubled pawns in Black's camp.",
      "Black initiates a queen trade to simplify the position.",
      "White recaptures with the knight, maintaining piece activity.",
      "Black recaptures, accepting doubled pawns on the c-file.",
      "The rook captures the bishop, giving White the bishop pair and better pawn structure."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-10",
    "name": "Evans Gambit with Bf6",
    "description": "Bishop retreats to f6",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "c6", "Nxf7", "Kxf7", "Qf3+", "Kg8", "Rae1", "cxb5", "Rxe7"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the f7 square.",
      "Black attacks the knight, attempting to remove the threat.",
      "Bishop check - White creates additional threats.",
      "Black blocks the check with the pawn.",
      "Knight sacrifice! White destroys Black's king protection.",
      "The king is forced to capture, exposing itself to attack.",
      "Queen check - White immediately attacks the exposed king.",
      "The king retreats to g8, the only safe square.",
      "White develops the other rook, bringing the last piece into the attack.",
      "Black captures the bishop, winning material but losing coordination.",
      "White captures the knight, regaining material with a winning attack."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-11",
    "name": "Evans Gambit - Extended Attack Line",
    "description": "Deep tactical line with multiple knight moves",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "Ncd6", "Qxg7", "Qf6", "Qxf6", "Nxf6", "Re1+", "Kf8", "Bh6+", "Kg8", "Re5", "Nfe4", "Re1", "f6", "Re7", "Nf5", "Re8+", "Kf7", "Rxh8", "Nxh6", "Rxe4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "Brilliant queen move! White attacks both g7 and the knight simultaneously.",
      "The knight moves to defend g7, but creates new weaknesses.",
      "Queen sacrifice! White captures the g7 pawn, threatening mate on h8.",
      "Black blocks with the queen, attempting to defend.",
      "White captures the queen, eliminating Black's best defender.",
      "Black recaptures, but the position remains critically weak.",
      "Rook check - White exploits the pinned knight and exposed king.",
      "The king moves to f8, the only safe square.",
      "Bishop check - White forces the king back to g8.",
      "The king returns to g8, but now faces a coordinated attack.",
      "White's rook maneuvers to the fifth rank, preparing a mating net.",
      "The knight blocks the rook's path to e8.",
      "The rook returns to e1, maintaining pressure on the e-file.",
      "Black advances the pawn, attempting to defend.",
      "White's rook attacks the seventh rank, creating new threats.",
      "The knight attacks the bishop, attempting counterplay.",
      "Rook check - White continues the assault on Black's position.",
      "The king moves to f7, trying to escape the attack.",
      "White captures the rook, winning material.",
      "Black captures the bishop, eliminating an attacker.",
      "White captures the knight, regaining material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-12",
    "name": "Evans Gambit - Mate in 6 Variation",
    "description": "Quick mating attack after Bb5+",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "Kf8", "Qh5", "g6", "Qf3", "hxg5", "Qf6", "Rh4", "Rxh4", "gxh4", "Re1", "Bd7", "Rxe7", "Qxe7", "Qh8#"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the f7 square.",
      "Black attacks the knight, attempting to remove the threat.",
      "Bishop check - White creates additional threats.",
      "The king moves to f8, avoiding immediate mate threats.",
      "White's queen attacks both f7 and h6 simultaneously.",
      "Black defends with the pawn, but weakens the kingside.",
      "White repositions the queen to threaten mate on f6.",
      "Black captures the knight, but opens the h-file.",
      "White's queen threatens mate on g7.",
      "Black tries to defend with the rook.",
      "White captures the rook, eliminating a key defender.",
      "Black recaptures, but the position remains critically weak.",
      "White brings the other rook into the attack.",
      "Black develops the bishop, but it's too late for defense.",
      "Rook sacrifice! White destroys Black's remaining defenses.",
      "Black captures the rook, but now faces an unstoppable mate.",
      "Checkmate! The queen delivers the final blow on h8."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-13",
    "name": "Two Knights Defense - Modern Line with d6",
    "description": "Solid approach with d6 instead of Nf6",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "Nc6", "Bb5", "Bd7", "Nc3", "exd4", "Nxd4", "Nxd4", "Bxd7+", "Qxd7", "Qxd4", "Nf6", "Bg5", "Be7", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Philidor Defense - Black prepares to support the e5 pawn with d6.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "Ruy Lopez style - White pins the knight to the king.",
      "Black develops the bishop to break the pin on the knight.",
      "White develops the knight to its natural square, supporting the center.",
      "Black captures the pawn, opening the center.",
      "White recaptures with the knight, centralizing the piece.",
      "Black captures the knight, simplifying the position.",
      "White captures the bishop, forcing a recapture.",
      "Black recaptures with the queen, centralizing the piece.",
      "White's queen recaptures the knight, controlling the center.",
      "Black develops the knight to its natural square.",
      "White pins the knight to the king, creating pressure.",
      "Black develops the bishop, breaking the pin and completing development.",
      "White castles queenside, completing development with an active position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-14",
    "name": "Two Knights Defense - Modern with Bf4",
    "description": "Quiet development with Bf4",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "exd4", "Nxd4", "Nf6", "Nc3", "Be7", "Bf4", "O-O", "Qd2", "a6", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Philidor Defense - Black prepares to support the e5 pawn with d6.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White recaptures with the knight, centralizing the piece.",
      "Black develops the knight to its natural square.",
      "White develops the knight to support the center.",
      "Black develops the bishop quietly, preparing kingside castling.",
      "White develops the bishop to an active diagonal, avoiding early trades.",
      "Black castles to safety, securing the king.",
      "White's queen connects the rooks and prepares queenside castling.",
      "Prophylactic move - Black prevents Nb5.",
      "White castles queenside, setting up an opposite-side castling position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-15",
    "name": "Two Knights Defense - d5 Advance",
    "description": "Immediate d5 push after d4",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "d6", "d5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Solid defense - Black supports the e5 pawn and maintains central control.",
      "White advances the pawn, gaining space and attacking the knight."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-16",
    "name": "Two Knights Defense - Qa5 Variation",
    "description": "Queen retreats to a5 instead of d8",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qa5", "Nxe4", "Be6", "Neg5", "O-O-O", "Nxe6", "fxe6", "Rxe6", "Bd6", "Bg5", "Rde8", "Qe2"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "The rook moves to pin the knight against the king, creating immediate threats.",
      "Black pushes the pawn to attack the bishop and break the pin.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to a5, maintaining pressure on the e1 square.",
      "White captures the knight, regaining material.",
      "Black develops the bishop, defending the d5 square.",
      "White attacks the bishop with the knight, creating threats.",
      "Black castles queenside, securing the king on the opposite side.",
      "White captures the bishop, damaging Black's pawn structure.",
      "Black recaptures, accepting doubled pawns on the e-file.",
      "White captures the pawn, regaining material.",
      "Black develops the bishop actively, targeting the kingside.",
      "White pins the knight to the queen, creating pressure.",
      "Black doubles rooks on the e-file, challenging White's control.",
      "White's queen develops to connect the rooks and support the center."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-17",
    "name": "Two Knights Defense - Queen Trade Line",
    "description": "Early queen trade variation",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qd8", "Rxe4+", "Be7", "Nxd4", "O-O", "Nxc6", "bxc6", "Qxd8", "Bxd8", "Rc4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "The rook moves to pin the knight against the king, creating immediate threats.",
      "Black pushes the pawn to attack the bishop and break the pin.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to safety, but Black's development remains incomplete.",
      "Rook captures the pinned knight with check, exploiting Black's lagging development.",
      "The bishop blocks the check while developing to a natural square.",
      "White's knight recaptures the central pawn, controlling key squares.",
      "Black castles to safety, finally getting the king to relative security.",
      "White captures the knight, damaging Black's pawn structure.",
      "Black recaptures, accepting doubled pawns on the c-file.",
      "White trades queens, simplifying the position.",
      "Black recaptures with the bishop, completing the exchange.",
      "White's rook moves to the c-file, targeting Black's weak pawns."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-18",
    "name": "Two Knights Defense - Exchange Variation",
    "description": "Early bishop exchange line",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "Nc6", "Bb5", "exd4", "Qxd4", "Bd7", "Bxc6", "Bxc6", "Nc3", "Nf6", "Bg5", "Be7", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Philidor Defense - Black prepares to support the e5 pawn with d6.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "Ruy Lopez style - White pins the knight to the king.",
      "Black captures the pawn, opening the center.",
      "White's queen recaptures, centralizing the piece.",
      "Black develops the bishop to break the pin on the knight.",
      "White captures the knight, damaging Black's pawn structure.",
      "Black recaptures with the bishop, maintaining the bishop pair.",
      "White develops the knight to its natural square.",
      "Black develops the knight to its natural square.",
      "White pins the knight to the king, creating pressure.",
      "Black develops the bishop, breaking the pin and completing development.",
      "White castles queenside, completing development with an active position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-19",
    "name": "Evans Gambit - Bd7 Retreat Line",
    "description": "Bishop retreats to d7 after Bb5+",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "Bd7", "Qe2", "hxg5", "Re1", "O-O", "Rxe7", "Bxb5", "Qxb5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the f7 square.",
      "Black attacks the knight, attempting to remove the threat.",
      "Bishop check - White creates additional threats.",
      "Black blocks the check with the bishop.",
      "White develops the queen, supporting the attack.",
      "Black captures the knight, eliminating a threat.",
      "White repositions the rook to the e-file, maintaining pressure.",
      "Black castles to safety, securing the king.",
      "White captures the knight, regaining material.",
      "Black captures the bishop, winning material.",
      "White captures the bishop, completing the exchange with a balanced position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-20",
    "name": "Two Knights Defense - Qh5 Variation",
    "description": "Queen retreats to h5 after Bxd5",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qh5", "Nxe4", "Be6", "Bg5", "Bd6", "Nxd6+", "cxd6", "Bf4", "Qd5", "c3"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking e4.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "The rook moves to pin the knight against the king, creating immediate threats.",
      "Black pushes the pawn to attack the bishop and break the pin.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to h5, avoiding exchange and maintaining kingside pressure.",
      "White captures the knight, regaining material.",
      "Black develops the bishop, defending key squares.",
      "White pins the f6 pawn to the queen, creating pressure.",
      "Black develops the bishop actively, targeting the kingside.",
      "White captures the bishop with check, damaging Black's pawn structure.",
      "Black recaptures, accepting an isolated pawn on d6.",
      "White develops the bishop to an active diagonal.",
      "Black's queen centralizes, controlling key squares.",
      "White supports the center, preparing further development."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-21",
    "name": "Evans Gambit - Nh7 Attack",
    "description": "Knight sacrifice on h7 line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "O-O", "Nxh7", "Kxh7", "Qh5+", "Kg8", "Rh4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the f7 square.",
      "Black castles to safety, securing the king.",
      "Knight sacrifice! White destroys Black's kingside pawn structure.",
      "The king is forced to capture, exposing itself to attack.",
      "Queen check - White immediately attacks the exposed king.",
      "The king retreats to g8, the only safe square.",
      "White's rook moves to the h-file, threatening mate on h7."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-22",
    "name": "Evans Gambit - O-O Variation",
    "description": "Black castles early instead of capturing",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "O-O", "Qxc4", "Nd6", "Qb3"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Black develops the knight with tempo by attacking the e4 pawn.",
      "Evans Gambit - White sacrifices a pawn for rapid development.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "White castles to safety, sacrificing material for initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "White advances the pawn, attacking the knight and gaining space.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "Brilliant queen move! White attacks both g7 and the knight simultaneously.",
      "Black castles to safety, securing the king.",
      "White captures the knight, regaining material.",
      "Black's knight develops to a good defensive square.",
      "White's queen moves to an active diagonal, maintaining pressure."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-23",
    "name": "Evans Gambit - h6 with Complications",
    "description": "h6 line with tactical complications",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "h6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nf6", "e5", "Ne4", "O-O", "Nxc3", "bxc3", "Bxc3", "Qb3", "Bxa1", "Bxf7+", "Kf8", "Ba3+", "d6", "exd6", "cxd6", "Bg6", "Qf6", "Bxd6+", "Ne7", "Re1"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the e5 pawn and control central squares.",
      "Black develops the knight to defend the e5 pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the f7-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "White prepares to push the d-pawn, supporting central expansion.",
      "Prophylactic move - Black prevents Bg5 but wastes a tempo.",
      "White pushes in the center, executing the Evans Gambit idea.",
      "Black accepts the gambit, capturing the central pawn.",
      "White recaptures, opening lines for development.",
      "Bishop check - Black pins the knight against the king.",
      "White blocks the check while developing a piece to its natural square.",
      "Black develops the knight to its natural square.",
      "White advances the pawn, attacking the knight and gaining space.",
      "The knight moves forward, attacking multiple squares.",
      "White castles to safety, completing development.",
      "Black captures the knight, but helps White open the b-file.",
      "White recaptures, opening the b-file and attacking the bishop.",
      "Black captures the pawn, but the bishop becomes exposed.",
      "White's queen attacks both the bishop and f7 simultaneously.",
      "Black captures the rook, winning material but exposing the king.",
      "Bishop sacrifice! White destroys Black's king protection.",
      "The king is forced to move, losing the right to castle.",
      "Bishop check - White continues the attack.",
      "Black blocks the check with the pawn.",
      "White captures the pawn, opening lines.",
      "Black recaptures, but the position remains critical.",
      "White moves the bishop to pin the pawn to the king.",
      "Black defends with the queen, attempting to stabilize.",
      "Bishop check - White maintains the initiative.",
      "The knight blocks the check, but the position remains difficult for Black.",
      "White develops the rook, bringing the last piece into the attack."
    ]
  }
];