import { withOpeningFeedback } from "./feedback";

export const italianGameSEOText = `
The Italian Game (1. e4 e5 2. Nf3 Nc6 3. Bc4) is one of the oldest and most fundamental openings in chess. It focuses on three things: rapid development, total central control, and immediate pressure on the weakest point in Black's camp: the {{square f7}} pawn.

The star of the show is the "Italian Bishop" on {{square c4}}, which laser-beams the king before Black can even castle.

These drills cover the core Italian battles:
- The Giuoco Piano (Quiet Game): Using c3 and d4 to build a massive pawn center and overwhelm Black with activity.
- The Two Knights Defense: Sharp tactical races where White targets f7 and Black counterstrikes in the center.
- Tactical Fireworks: Forcing lines where a single misstep by Black leads to a direct mating attack or a winning material advantage.

Don't just develop—develop with a purpose. Every move should prepare the central strike or increase the pressure on the king!
`;

export const italianGameLines = withOpeningFeedback([
  {
    "category": "Italian Game",
    "id": "italian-01",
    "name": "French Defense Transposition (Tarrasch/Classical style)",
    "description": "Black answers 1.e4 with e6, leading to French Defense structures that require solid central play.",
    "moves": ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7", "f4", "c5", "Nf3", "Nc6", "Be3", "cxd4", "Nxd4", "Bc5", "Qd2", "O-O"],
    "explanations": [
      "Let's learn the Italian Game! Start with pawn to {{square e4}} and build toward quick development and pressure on {{square f7}}.",
      "French Defense! We're no longer in a symmetrical game; we're in a fight for the center.",
      "White claims full control. We build the dream center.",
      "Black strikes back immediately, challenging our d4 pawn.",
      "Develop and defend! We support our center while bringing a piece into the game.",
      "Black pressures e4 and prepares to develop their kingside.",
      "The space wedge! We push forward, cramping Black's position and kicking the knight.",
      "The knight retreats, but it's already eyeing the c5 break.",
      "Solidify! We support our e5 pawn and prepare for a kingside attack.",
      "Black strikes at the base of our chain! The classic French counter-attack.",
      "Develop naturally and keep the center under control.",
      "Black adds more pressure to d4. The tension is rising!",
      "Develop the bishop and support the center. We're getting ready for queenside castling.",
      "Trade! Black tries to clear out the center.",
      "Recapture and centralize. Our knight is a monster on d4!",
      "Black develops their 'good' bishop and pins our knight. A very active defense.",
      "Connect the rooks and prepare to castle long. White is ready for a big attack.",
      "Black castles to safety. Now it's a race between our kingside attack and Black's queenside pressure!"
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-02",
    "name": "Italian Center Attack - The Main Line Blast",
    "description": "The classic center attack with c3 and d4. White sacrifices material for a devastating lead in development and an open e-file.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "Bxa1", "Re1+", "Ne7", "Bxe7", "Qxe7", "Rxe7+", "Kxe7", "Qxa1"],
    "explanations": [
      "White claims the center. Standard and strong.",
      "Let's learn the Italian Game! Black mirrors. Symmetrical but not for long.",
      "Develop the knight and attack e5. We're forcing Black to react.",
      "Black defends and develops. The stage is set.",
      "The Italian Bishop! We take aim at the weakest square: {{square f7}}.",
      "The Giuoco Piano. Black develops their own bishop, mirroring our pressure.",
      "Prepare the strike! We play c3 to support a future d4 push.",
      "Black develops and hits e4. They're playing for counter-activity.",
      "Boom! The central strike. We attack the bishop and the center simultaneously.",
      "Black takes, but they're opening lines for our pieces.",
      "Recapture with the pawn. We keep our central dominance.",
      "Check! Black uses their best defensive resource to slow us down.",
      "Develop and block. We're ignoring the pin and focusing on development.",
      "Greed! Black takes on e4, but they're walking into a firestorm.",
      "Castle and unpin! We're ignoring the material and opening the e-file for our rook.",
      "Black keeps taking material, but they're losing precious time.",
      "Recapture. Every piece of ours is now active and ready to strike.",
      "Black grabs a second pawn and a rook, but their pieces are far away while ours are attacking their king.",
      "The crusher! We develop with tempo and cut the king off from castling. The king is trapped in the center!",
      "Black captures the rook, but they're fatally behind in development.",
      "Check! The 'Highway' is open. The rook on e1 is a monster.",
      "Forced block. The knight is pinned and overloaded. It's almost over.",
      "Remove the defender! We trade our bishop for the key defender of the king.",
      "Black must take back, but their queen is now pinned to the king.",
      "The payoff! We win the queen and maintain a winning attack.",
      "The king is dragged into the open, losing all rights to safety.",
      "Regain material and dominate. White has a queen for a rook and bishop, and Black's king is still a target. A tactical masterpiece!"
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-03",
    "name": "Two Knights Defense - Open Tactical Line",
    "description": "Sharp tactical line after 4.d4 Nxe4 5.dxe5.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "Nxe4", "dxe5", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White opens the center at once, aiming for activity rather than slow maneuvering.",
      "Black captures the pawn, accepting the challenge to White's center.",
      "White recaptures toward the center and asks Black concrete tactical questions.",
      "Black develops the bishop actively, targeting the vulnerable {{square f2}} square.",
      "White's queen attacks both the knight and the {{square f7}} pawn, creating multiple threats.",
      "Bishop sacrifice! Black creates chaos by exposing White's king position.",
      "White's king is forced to capture, losing the right to castle.",
      "Black castles to safety despite the material sacrifice, securing the king.",
      "White captures the knight, but Black has compensation with White's exposed king."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-04",
    "name": "Italian Center Attack - Bb6 Retreat",
    "description": "Black retreats the bishop instead of checking, and White keeps rolling the center.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb6", "e5", "Ng4", "h3", "Nh6", "d5", "Na5", "Bg5", "f6", "exf6"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Passive retreat. If Black does not check on {{square b4}}, White's central pawns keep rolling.",
      "Gain space and chase the knight before Black can untangle.",
      "The knight moves to attack the vulnerable {{square f2}} square, a typical response to {{square e5}}.",
      "Ask the knight to decide before it causes trouble on {{square f2}}.",
      "The knight retreats to the edge of the board, passive but safe.",
      "Key move. White plays {{square d5}} first, seizes the initiative, and keeps Black from consolidating.",
      "The knight attacks the bishop, gaining tempo while developing.",
      "Develop with a pin and prepare to exploit Black's cramped kingside.",
      "Black hits the bishop and the center, but the move loosens the king.",
      "White opens the e-file and makes Black's d-pawn and king harder to coordinate."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-05",
    "name": "Italian Center Attack - ...d6 Defense",
    "description": "Black tries to barricade the diagonal with ...d6 after the center attack.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "d6", "Rc1", "Ba5", "Qa4", "O-O", "d5", "Ne5", "Nxe5", "dxe5", "Qxa5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep pushing without interruption.",
      "White blocks the check while developing a piece to its natural square.",
      "Black exploits the pin to grab {{square e4}}, but falls further behind in development.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Greedy but common. Black removes the knight, yet helps White open files.",
      "White recaptures and keeps gaining tempi on the loose bishop.",
      "Black keeps grabbing material, but the bishop is now far from the defense.",
      "Develop with tempo and cut off Black's king. This is the attacking setup the transcript prefers over casual queen moves.",
      "Black tries to barricade the diagonal and survive long enough to castle.",
      "Strong practical move. The rook steps out of danger and attacks the bishop with tempo.",
      "Black retreats the bishop, maintaining the pin on the knight.",
      "Keep the bishop and knight under pressure at the same time.",
      "Black castles to safety, completing kingside development.",
      "Critical move. White grabs the initiative before Black can stabilize with ...{{square d5}} himself.",
      "The knight moves to a central outpost, attacking multiple squares.",
      "White captures the knight, eliminating Black's active piece.",
      "Black recaptures, maintaining material equality.",
      "White's queen captures the bishop, equalizing material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-06",
    "name": "Italian Center Attack - ...Bb4 Retreat",
    "description": "Black meets Rc1 by dropping the bishop back to b4.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Nxc3", "bxc3", "Bxc3", "Ba3", "d6", "Rc1", "Bb4", "Bxb4", "Nxb4", "Qe1+", "Qe7", "Qxb4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot just keep rolling the center.",
      "White blocks the check while developing a piece to its natural square.",
      "Black takes {{square e4}} because the knight is pinned, but White gets the e-file for the attack.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black removes the knight and hopes to stay greedy, but White gains open lines.",
      "White recaptures and keeps the b-file and bishop tempos.",
      "Black takes another pawn, but the bishop becomes a tactical target.",
      "White develops with tempo and fixes Black's king in the center.",
      "Black tries to close the diagonal and complete development.",
      "The rook move both saves the rook and hits the exposed bishop.",
      "Black retreats the bishop, avoiding capture and maintaining activity.",
      "White captures the bishop, eliminating Black's active piece.",
      "Black recaptures with the knight, centralizing the piece.",
      "Queen check keeps the king uncomfortable and the {{knight b4 full}} under pressure.",
      "Black blocks the check with the queen, defending the knight.",
      "White captures the knight, regaining material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-07",
    "name": "Italian Center Attack - Mating Attack",
    "description": "Center attack line ending in a direct mating net.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "Ncd6", "Qxg7", "Qf6", "Qxf6", "Nxf6", "Re1+", "Kf8", "Bh6+", "Kg8", "Re5", "Nde4", "Nd2", "d6", "Nxe4", "Nxe4", "Re8#"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep pushing for free.",
      "White blocks the check while developing a piece to its natural square.",
      "Black exploits the pin to grab {{square e4}}, but White gets the initiative and open e-file.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White plays {{square d5}} before Black can consolidate with ...{{square d5}} himself.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "White's queen joins the attack with tempo against {{square g7}} and the knight.",
      "The knight moves to defend {{square g7}}, but creates new weaknesses.",
      "Queen sacrifice! White captures the {{square g7}} pawn, threatening mate on {{square h8}}.",
      "Black blocks with the queen, attempting to defend.",
      "White captures the queen, eliminating Black's best defender.",
      "Black recaptures, but the position remains critically weak.",
      "Rook check - White exploits the pinned knight and exposed king.",
      "The king moves to {{square f8}}, the only safe square.",
      "Bishop check - White forces the king back to {{square g8}}.",
      "The king returns to {{square g8}}, but now faces a coordinated attack.",
      "Rook lift. White keeps feeding pieces into the attack instead of cashing out too early.",
      "The knight blocks the rook's path to {{square e8}}.",
      "White develops the knight, clearing the e-file for the rook.",
      "Black advances the pawn, but it's too late to defend.",
      "White captures the knight, eliminating a key defender.",
      "Black recaptures, but the defense has collapsed.",
      "Checkmate! The rook delivers the final blow on the back rank."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-08",
    "name": "Italian Center Attack vs Early ...h6",
    "description": "Black wastes a tempo with ...h6 and White grabs the center immediately.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "h6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "d6", "O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. The point of {{square c3}} is a clear center strike, not a random waiting move.",
      "Slow move. Black tries to rule out B{{square g5}} ideas but gives White extra time.",
      "Use the tempo immediately. White hits the bishop and {{square e5}} before Black has real counterplay.",
      "Black accepts the central break, but White gets the active game.",
      "White keeps the center intact and opens lines for the attack.",
      "Best practical reaction. The check slows White down more than a quiet retreat would.",
      "White blocks the check while developing a piece to its natural square.",
      "Black tries to hold the position together with a solid shell.",
      "White completes development and keeps the easier game."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-09",
    "name": "Max Lange Attack - Main Line",
    "description": "Main Max Lange tactical line after 4.d4 exd4 5.O-O Nxe4 6.Re1.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qd8", "Rxe4+", "Be7", "Nxd4", "O-O", "Nxc6", "Qxd1+", "Nxd1", "bxc6", "Rxe7"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "This is the Max Lange idea: pin the {{square e4}} knight and attack with development instead of material.",
      "Black's main defensive resource. The pawn break hits the bishop and interrupts White's momentum.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to safety, but Black's development remains incomplete.",
      "White removes the advanced knight with check before Black can finish development.",
      "The bishop blocks the check while developing to a natural square.",
      "White's knight recaptures the central pawn, controlling key squares.",
      "Black castles to safety, finally getting the king to relative security.",
      "White captures the knight, creating doubled pawns in Black's camp.",
      "Black initiates a queen trade to simplify the position.",
      "White recaptures with the knight, maintaining piece activity.",
      "Black recaptures, accepting doubled pawns on the c-file.",
      "The rook captures the bishop, giving White the bishop pair and better pawn structure."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-10",
    "name": "Italian Center Attack - ...Bf6 Defensive Retreat",
    "description": "Center attack line where Black retreats the bishop to f6 and White attacks the kingside.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "c6", "Nxf7", "Kxf7", "Qf3+", "Kg8", "Rae1", "cxb5", "Rxe7"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep rolling the pawns.",
      "White blocks the check while developing a piece to its natural square.",
      "Black grabs {{square e4}} thanks to the pin, but White gets dangerous activity for it.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White plays {{square d5}} first and keeps Black from consolidating.",
      "The bishop retreats, but the piece no longer helps defend the king.",
      "R{{square e1}} is the natural attacking move. White immediately points a rook at the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "Pin the knight and increase the pressure on {{square f6}} and {{square f7}}.",
      "Black captures the bishop, exchanging pieces.",
      "The knight jump keeps the attack alive and increases the pressure on {{square f7}}.",
      "Black chases the knight, but the kingside gets looser.",
      "Bishop check - White creates additional threats.",
      "Black blocks the check with the pawn.",
      "Typical attacking sacrifice. White rips open the king once enough pieces point at {{square f7}}.",
      "The king is forced to capture, exposing itself to attack.",
      "Queen check - White immediately attacks the exposed king.",
      "The king retreats to {{square g8}}, the only safe square.",
      "Bring the last rook in. The attack matters more than material counting here.",
      "Black captures the bishop, winning material but losing coordination.",
      "White captures the knight, regaining material with a winning attack."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-11",
    "name": "Italian Center Attack - Extended Attack Line",
    "description": "Long attacking line from the center attack after ...Bxc3 and ...Ne5.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "Ncd6", "Qxg7", "Qf6", "Qxf6", "Nxf6", "Re1+", "Kf8", "Bh6+", "Kg8", "Re5", "Nfe4", "Re1", "f6", "Re7", "Nf5", "Re8+", "Kf7", "Rxh8", "Nxh6", "Rxe4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot simply keep pushing.",
      "White blocks the check while developing a piece to its natural square.",
      "Black exploits the pin to grab {{square e4}}, but that gives White the e-file and the initiative.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White claims {{square d5}} first because if Black gets ...{{square d5}} in, the whole attack slows down.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "Brilliant queen move! White attacks both {{square g7}} and the knight simultaneously.",
      "The knight moves to defend {{square g7}}, but creates new weaknesses.",
      "Queen sacrifice! White captures the {{square g7}} pawn, threatening mate on {{square h8}}.",
      "Black blocks with the queen, attempting to defend.",
      "White captures the queen, eliminating Black's best defender.",
      "Black recaptures, but the position remains critically weak.",
      "Rook check - White exploits the pinned knight and exposed king.",
      "The king moves to {{square f8}}, the only safe square.",
      "Bishop check - White forces the king back to {{square g8}}.",
      "The king returns to {{square g8}}, but now faces a coordinated attack.",
      "White's rook maneuvers to the fifth rank, preparing a mating net.",
      "The knight blocks the rook's path to {{square e8}}.",
      "The rook returns to {{square e1}}, maintaining pressure on the e-file.",
      "Black advances the pawn, attempting to defend.",
      "White's rook attacks the seventh rank, creating new threats.",
      "The knight attacks the bishop, attempting counterplay.",
      "Rook check - White continues the assault on Black's position.",
      "The king moves to {{square f7}}, trying to escape the attack.",
      "White captures the rook, winning material.",
      "Black captures the bishop, eliminating an attacker.",
      "White captures the knight, regaining material with a better position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-12",
    "name": "Italian Center Attack - Mate in 6",
    "description": "Sharp center attack line ending in a forced mating net.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "Kf8", "Qh5", "g6", "Qf3", "hxg5", "Qf6", "Rh4", "Rxh4", "gxh4", "Re1", "Bd7", "Rxe7", "Qxe7", "Qh8#"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep the pawn roller going for free.",
      "White blocks the check while developing a piece to its natural square.",
      "Black exploits the pin to grab {{square e4}}, but White gets dangerous attacking play in return.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White seizes {{square d5}} before Black can use that square to consolidate.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "Pin the knight and prepare to open more lines toward the king.",
      "Black captures the bishop, exchanging pieces.",
      "The knight lands on {{square g5}} and keeps the attack focused on {{square f7}} and {{square h7}}.",
      "Black kicks the knight, but also loosens the dark squares around the king.",
      "Bishop check - White creates additional threats.",
      "The king moves to {{square f8}}, avoiding immediate mate threats.",
      "The queen joins the attack and starts direct mating threats.",
      "Black defends with the pawn, but weakens the kingside.",
      "White keeps the queen active and forces Black to solve threats, not improve pieces.",
      "Black captures the knight, but opens the h-file.",
      "The queen penetrates. Black is already one defensive move short.",
      "Black tries to defend with the rook.",
      "White captures the rook, eliminating a key defender.",
      "Black recaptures, but the position remains critically weak.",
      "Bring the last rook into the attack. The e-file does the real work in these positions.",
      "Black develops the bishop, but it's too late for defense.",
      "Rook sacrifice! White destroys Black's remaining defenses.",
      "Black captures the rook, but now faces an unstoppable mate.",
      "Checkmate! The queen delivers the final blow on {{square h8}}."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-13",
    "name": "Philidor Defense - Bb5 Exchange Line",
    "description": "Philidor move order with early Bb5 and queen trade into active queenside castling.",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "Nc6", "Bb5", "Bd7", "Nc3", "exd4", "Nxd4", "Nxd4", "Bxd7+", "Qxd7", "Qxd4", "Nf6", "Bg5", "Be7", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the center and chooses a solid Philidor structure.",
      "White develops the knight, attacks {{square e5}}, and prepares {{square d4}}.",
      "The Philidor setup supports {{square e5}} and keeps Black compact.",
      "White seizes more space and challenges the center directly.",
      "Black develops and adds pressure to {{square d4}} and {{square e5}}.",
      "White pins the knight and increases pressure on {{square e5}}.",
      "Black breaks the pin and prepares to recapture cleanly.",
      "White develops another piece and keeps central control.",
      "Black opens the center before White is fully developed.",
      "White recaptures with a piece and centralizes the knight.",
      "Black simplifies and removes White's active central knight.",
      "White trades off the bishop before resolving the center.",
      "Black recaptures with the queen and keeps the pieces coordinated.",
      "White trades queens and reaches a cleaner structure.",
      "Black develops and fights for the central dark squares.",
      "White pins the knight and makes kingside castling less comfortable.",
      "Black breaks the pin and prepares to castle.",
      "White castles long and activates the {{rook d1 full}}."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-14",
    "name": "Philidor Defense - Quiet Bf4 Line",
    "description": "Philidor setup with Bf4 and opposite-side castling.",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "exd4", "Nxd4", "Nf6", "Nc3", "Be7", "Bf4", "O-O", "Qd2", "a6", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the center and chooses a solid Philidor structure.",
      "White develops the knight, attacks {{square e5}}, and prepares {{square d4}}.",
      "The Philidor setup supports {{square e5}} and keeps Black compact.",
      "White seizes more space and challenges the center directly.",
      "Black clarifies the center before White can overbuild it.",
      "White recaptures with a piece and keeps the knight active.",
      "Black develops naturally and attacks {{square e4}}.",
      "White supports the center and prepares queenside development.",
      "Black develops quietly and gets ready to castle.",
      "White places the bishop on an active diagonal, eyeing {{square d6}} and {{square e5}}.",
      "Black secures the king.",
      "White connects the rooks and prepares long castling.",
      "Useful waiting move that controls {{square b5}} and gives Black some luft.",
      "White castles long and gets an opposite-side castling setup."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-15",
    "name": "Two Knights Defense - d5 Advance",
    "description": "Immediate d5 push after d4",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "d6", "d5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Solid defense - Black supports the {{square e5}} pawn and maintains central control.",
      "White advances the pawn, gaining space and attacking the knight."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-16",
    "name": "Max Lange Attack - Qa5 Line",
    "description": "Max Lange line where Black's queen retreats to a5.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qa5", "Nxe4", "Be6", "Neg5", "O-O-O", "Nxe6", "fxe6", "Rxe6", "Bd6", "Bg5", "Rde8", "Qe2"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "This is the Max Lange idea: pin the {{square e4}} knight and attack with development instead of material.",
      "Black's main defensive resource. The pawn break hits the bishop and interrupts White's momentum.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to {{square a5}}, maintaining pressure on the {{square e1}} square.",
      "White removes the advanced knight with check before Black can finish development.",
      "Black develops the bishop, defending the {{square d5}} square.",
      "White attacks the bishop with the knight, creating threats.",
      "Black castles queenside, securing the king on the opposite side.",
      "White captures the bishop, damaging Black's pawn structure.",
      "Black recaptures, accepting doubled pawns on the e-file.",
      "White captures the pawn, regaining material.",
      "Black develops the bishop actively, targeting the kingside.",
      "White pins the knight to the queen, creating pressure.",
      "Black doubles rooks on the e-file, challenging White's control.",
      "White's queen develops to connect the rooks and support the center."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-17",
    "name": "Max Lange Attack - Queen Trade Line",
    "description": "Max Lange line leading to an early queen trade.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qd8", "Rxe4+", "Be7", "Nxd4", "O-O", "Nxc6", "bxc6", "Qxd8", "Bxd8", "Rc4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "This is the Max Lange idea: pin the {{square e4}} knight and attack with development instead of material.",
      "Black's main defensive resource. The pawn break hits the bishop and interrupts White's momentum.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to safety, but Black's development remains incomplete.",
      "White removes the advanced knight with check before Black can finish development.",
      "The bishop blocks the check while developing to a natural square.",
      "White's knight recaptures the central pawn, controlling key squares.",
      "Black castles to safety, finally getting the king to relative security.",
      "White captures the knight, damaging Black's pawn structure.",
      "Black recaptures, accepting doubled pawns on the c-file.",
      "White trades queens, simplifying the position.",
      "Black recaptures with the bishop, completing the exchange.",
      "White's rook moves to the c-file, targeting Black's weak pawns."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-18",
    "name": "Philidor Defense - Exchange Variation",
    "description": "Philidor move order with early Bb5 and bishop exchange.",
    "moves": ["e4", "e5", "Nf3", "d6", "d4", "Nc6", "Bb5", "exd4", "Qxd4", "Bd7", "Bxc6", "Bxc6", "Nc3", "Nf6", "Bg5", "Be7", "O-O-O"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the center and chooses a solid Philidor structure.",
      "White develops the knight, attacks {{square e5}}, and prepares {{square d4}}.",
      "The Philidor setup supports {{square e5}} and keeps Black compact.",
      "White seizes more space and challenges the center directly.",
      "Black develops and adds pressure to {{square d4}} and {{square e5}}.",
      "White pins the knight and asks Black how to untangle.",
      "Black opens the center before White finishes development.",
      "White recaptures with the queen and centralizes immediately.",
      "Black breaks the pin and prepares ...Bx{{square c6}}.",
      "White damages Black's queenside structure and removes a defender.",
      "Black accepts the structural damage to keep piece activity.",
      "White develops and increases control over the center.",
      "Black develops the knight and prepares to castle.",
      "White pins the knight and makes kingside castling less comfortable.",
      "Black breaks the pin and prepares to secure the king.",
      "White castles long and activates the {{rook d1 full}}."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-19",
    "name": "Italian Center Attack - ...Bd7 Retreat Line",
    "description": "Center attack line where Black answers Bb5+ with ...Bd7.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "h6", "Bb5+", "Bd7", "Qe2", "hxg5", "Re1", "O-O", "Rxe7", "Bxb5", "Qxb5"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep the center rolling without interruption.",
      "White blocks the check while developing a piece to its natural square.",
      "Black uses the pin to grab {{square e4}}, but White still gets the initiative.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White claims {{square d5}} first and stops Black from consolidating with ...{{square d5}}.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the {{square f7}} square.",
      "Black attacks the knight, attempting to remove the threat.",
      "Bishop check - White creates additional threats.",
      "Black blocks the check with the bishop.",
      "White develops the queen, supporting the attack.",
      "Black captures the knight, eliminating a threat.",
      "White repositions the rook to the e-file, maintaining pressure.",
      "Black castles to safety, securing the king.",
      "White captures the knight, regaining material.",
      "Black captures the bishop, winning material.",
      "White captures the bishop, completing the exchange with a balanced position."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-20",
    "name": "Max Lange Attack - Qh5 Line",
    "description": "Max Lange line where Black's queen retreats to h5.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O", "Nxe4", "Re1", "d5", "Bxd5", "Qxd5", "Nc3", "Qh5", "Nxe4", "Be6", "Bg5", "Bd6", "Nxd6+", "cxd6", "Bf4", "Qd5", "c3"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Two Knights Defense - Black develops the knight with tempo by attacking {{square e4}}.",
      "White pushes in the center, challenging Black's pawn structure.",
      "Black captures the pawn, opening the center.",
      "White castles to safety, sacrificing a pawn for rapid development.",
      "Black captures the pawn, accepting material but falling behind in development.",
      "This is the Max Lange idea: pin the {{square e4}} knight and attack with development instead of material.",
      "Black's main defensive resource. The pawn break hits the bishop and interrupts White's momentum.",
      "White captures the pawn, maintaining pressure on the pinned knight.",
      "The queen captures the bishop, but now becomes a target for White's pieces.",
      "White develops the knight with tempo, attacking the exposed queen.",
      "The queen retreats to {{square h5}}, avoiding exchange and maintaining kingside pressure.",
      "White removes the advanced knight with check before Black can finish development.",
      "Black develops the bishop, defending key squares.",
      "White pins the {{square f6}} pawn to the queen, creating pressure.",
      "Black develops the bishop actively, targeting the kingside.",
      "White captures the bishop with check, damaging Black's pawn structure.",
      "Black recaptures, accepting an isolated {{pawn d6 full}}.",
      "White develops the bishop to an active diagonal.",
      "Black's queen centralizes, controlling key squares.",
      "White supports the center, preparing further development."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-21",
    "name": "Italian Center Attack - Nxh7 Attack",
    "description": "Center attack line with the classic knight sacrifice on h7.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Bf6", "Re1", "Ne7", "Rxe4", "d6", "Bg5", "Bxg5", "Nxg5", "O-O", "Nxh7", "Kxh7", "Qh5+", "Kg8", "Rh4"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot just keep rolling the center.",
      "White blocks the check while developing a piece to its natural square.",
      "Black exploits the pin to grab {{square e4}}, but White gets activity and open lines for the attack.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White plays {{square d5}} first and keeps Black from consolidating.",
      "Black retreats the bishop to a defensive square.",
      "White develops the rook, attacking the pinned knight.",
      "The knight retreats to a safer square.",
      "White captures the knight, regaining material.",
      "Black advances the pawn, defending the center and bishop.",
      "White attacks the bishop, forcing a decision.",
      "Black captures the bishop, exchanging pieces.",
      "White recaptures with the knight, threatening the {{square f7}} square.",
      "Black castles to safety, securing the king.",
      "Typical attacking shot. White tears open the kingside once enough pieces are aimed there.",
      "The king is forced to capture, exposing itself to attack.",
      "Bring the queen in immediately. The attack now revolves around direct threats on {{square h7}} and {{square f7}}.",
      "The king retreats to {{square g8}}, the only safe square.",
      "Classic rook lift. White threatens mate and forces Black to find only moves."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-22",
    "name": "Italian Center Attack - Early ...O-O Line",
    "description": "Black castles early in the center attack instead of grabbing more material.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4", "O-O", "Bxc3", "d5", "Ne5", "bxc3", "Nxc4", "Qd4", "O-O", "Qxc4", "Nd6", "Qb3"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. This is the core Italian center attack, hitting both the bishop and the {{square e5}} pawn.",
      "Black develops the knight with tempo by attacking the {{square e4}} pawn.",
      "Strike in the center with tempo on the bishop and the {{square e5}} pawn.",
      "Black takes in the center, but White gets open lines and rapid development.",
      "White recaptures with the c-pawn to keep the center mobile and open the c-file.",
      "Best defensive resource. Black checks first so White cannot keep pushing pawns unchecked.",
      "White blocks the check while developing a piece to its natural square.",
      "Black grabs {{square e4}} because the knight is pinned, but White keeps the initiative.",
      "Do not defend passively. Castling unpins the knight and keeps the initiative.",
      "Black captures the knight, removing a defender from White's position.",
      "Critical move. White plays {{square d5}} first because giving Black time for ...{{square d5}} would stabilize everything.",
      "The knight moves to a central square, attacking multiple pieces.",
      "White recaptures, maintaining material balance.",
      "Black captures the bishop, winning material but exposing the king.",
      "Brilliant queen move! White attacks both {{square g7}} and the knight simultaneously.",
      "Black chooses king safety first. The king escapes, but White keeps the easier game.",
      "White captures the knight, regaining material.",
      "Black's knight develops to a good defensive square.",
      "White's queen moves to an active diagonal, maintaining pressure."
    ]
  },
  {
    "category": "Italian Game",
    "id": "italian-23",
    "name": "Italian Center Attack - Early ...h6 Complications",
    "description": "Sharp center attack line against an early ...h6.",
    "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "h6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nf6", "e5", "Ne4", "O-O", "Nxc3", "bxc3", "Bxc3", "Qb3", "Bxa1", "Bxf7+", "Kf8", "Ba3+", "d6", "exd6", "cxd6", "Bg6", "Qf6", "Bxd6+", "Ne7", "Re1"],
    "explanations": [
      "White establishes central control with the king's pawn opening.",
      "Black mirrors the move, contesting the center immediately.",
      "White develops the knight to attack the {{square e5}} pawn and control central squares.",
      "Black develops the knight to defend the {{square e5}} pawn and maintain central influence.",
      "White's bishop takes up an aggressive post on the {{square f7}}-hitting diagonal.",
      "Black develops the bishop symmetrically, creating the Italian Game structure.",
      "Prepare {{square d4}}. {{square c3}} gives White a direct center-attacking plan.",
      "Slow move. Black spends a tempo on ...{{square h6}} and gives White extra room for action.",
      "White strikes in the center before Black can coordinate.",
      "Black accepts the central clash, but White gets open lines and development.",
      "White recaptures with the c-pawn and keeps the center mobile.",
      "Best practical reaction. The check slows White down more than a quiet retreat would.",
      "White blocks the check while developing a piece to its natural square.",
      "Black develops the knight to its natural square.",
      "White gains space and forces the knight to choose a square.",
      "The knight moves forward, attacking multiple squares.",
      "White castles to safety, completing development.",
      "Black captures the knight, but helps White open the b-file.",
      "White recaptures, opening the b-file and attacking the bishop.",
      "Black captures the pawn, but the bishop becomes exposed.",
      "The queen creates a double attack on the bishop and {{square f7}}, keeping Black under tactical pressure.",
      "Black captures the rook, winning material but exposing the king.",
      "Bishop sacrifice! White destroys Black's king protection.",
      "The king is forced to move, losing the right to castle.",
      "Bishop check - White continues the attack.",
      "Black blocks the check with the pawn.",
      "White captures the pawn, opening lines.",
      "Black recaptures, but the position remains critical.",
      "White moves the bishop to pin the pawn to the king.",
      "Black defends with the queen, attempting to stabilize.",
      "Bishop check - White maintains the initiative.",
      "The knight blocks the check, but the position remains difficult for Black.",
      "White develops the rook, bringing the last piece into the attack."
    ]
  }
]);
