import { withOpeningFeedback } from "./feedback";

export const kingsGambitLines = withOpeningFeedback([
  {
    category: "King's Gambit",
    id: "kingsGambit-01-899b8126",
    name: "Allgaier style queen check attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Ke8",
      "Qh5+",
      "Ke7",
      "Qe5+",
      "Kf7",
      "Bc4+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays f6 to support g5 and clamp down on e5, but it weakens e6 and opens lines if White can sacrifice to rip it open.",
      "White captures on g5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e8, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to f7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-02-1c16d08e",
    name: "King's Gambit attacking setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "Bg4",
      "Bxf4",
      "Bxf3",
      "Qxf3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on f3 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on f3 with the queen, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-03-22395211",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "Bg7",
      "Nxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the knight on h6 to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White places the knight on d3 to improve central influence and set up the next tactic or break.",
      "Black develops the bishop to g7, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on f4 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-04-017652b4",
    name: "Allgaier style queen check attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Bg7",
      "Qxg7+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays f6 to support g5 and clamp down on e5, but it weakens e6 and opens lines if White can sacrifice to rip it open.",
      "White captures on g5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black develops the bishop to g7, choosing a diagonal that targets a weakness or supports a central break.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-05-32f16c21",
    name: "Allgaier style queen check attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Kf7",
      "Qxd8"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays f6 to support g5 and clamp down on e5, but it weakens e6 and opens lines if White can sacrifice to rip it open.",
      "White captures on g5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to f7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White captures on d8 with the queen, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-06-ab502c92",
    name: "Allgaier style queen check attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Rg8",
      "exf6+",
      "Kf7",
      "Bc4+",
      "d5",
      "Bxd5+",
      "Be6",
      "Bxe6+",
      "Kxe6",
      "Qxg8+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays f6 to support g5 and clamp down on e5, but it weakens e6 and opens lines if White can sacrifice to rip it open.",
      "White captures on g5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black activates a rook to g8 to pressure an open file created by earlier trades.",
      "White gives check to keep the initiative.",
      "Black moves the king to f7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black strikes with d5 in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black develops the bishop to e6, choosing a diagonal that targets a weakness or supports a central break.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on e6 with the king, usually removing a key defender or converting initiative into material.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-07-5b92c57a",
    name: "Falkbeer counterattack structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Qxd5",
      "Nc3",
      "Qe6+",
      "Be2",
      "Bd6",
      "O-O",
      "Nf6",
      "Bb5+",
      "Bd7",
      "Re1"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black strikes with d5 in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on d5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on d5 with the queen, usually removing a key defender or converting initiative into material.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White develops the bishop to e2, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to d6, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White activates a rook to e1 to pressure an open file created by earlier trades."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-08-22395163",
    name: "Falkbeer counterattack structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Qxd5",
      "Nc3",
      "Qe6+",
      "Be2",
      "Bc5",
      "d4",
      "Bd6",
      "O-O",
      "Nf6",
      "Bb5+",
      "c6",
      "Re1"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black strikes with d5 in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on d5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on d5 with the queen, usually removing a key defender or converting initiative into material.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White develops the bishop to e2, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to c5, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black develops the bishop to d6, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black plays c6 to kick a bishop or support d5 later, but it can cost a tempo in a position where time is everything.",
      "White activates a rook to e1 to pressure an open file created by earlier trades."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-09-89178ff9",
    name: "Allgaier style queen check attack",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Kf7",
      "Qxf4",
      "Qe7",
      "Be2",
      "Bg7",
      "O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays f6 to support g5 and clamp down on e5, but it weakens e6 and opens lines if White can sacrifice to rip it open.",
      "White captures on g5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to e7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "Black moves the king to f7, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White captures on f4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black moves the queen to e7 with a concrete task, either defending a pawn or creating a direct threat.",
      "White develops the bishop to e2, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to g7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-10-3ffce502",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Bxg4",
      "Qxg4",
      "Nf6",
      "Qxf4",
      "Nc6",
      "Bb5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White captures on g4 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on g4 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on g4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on f4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-11-e618b761",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "Be7",
      "Bxf4",
      "Bxh4+",
      "g3",
      "Bf6",
      "c3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the knight on h6 to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White places the knight on d3 to improve central influence and set up the next tactic or break.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f6, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-12-3a24a9e2",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "f3",
      "gxf3",
      "gxf3",
      "Qxf3",
      "Bg4",
      "Qf2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the knight on h6 to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White places the knight on d3 to improve central influence and set up the next tactic or break.",
      "Black pushes a pawn to f3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on f3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on f3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on f3 with the queen, usually removing a key defender or converting initiative into material.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White moves the queen to f2 with a concrete task, either defending a pawn or creating a direct threat."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-13-512545cd",
    name: "King's Gambit attacking setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "Nf6",
      "Nc3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-14-a5f5f500",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Rh7",
      "d4",
      "d6",
      "Nxf7",
      "Rxf7",
      "Bxf7+",
      "Kxf7",
      "Bxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black activates a rook to h7 to pressure an open file created by earlier trades.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White captures on f7 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on f7 with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on f7 with the king, usually removing a key defender or converting initiative into material.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-15-9ce7614e",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "Nf6",
      "d4",
      "Nxe4",
      "Bxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-16-60fa99dd",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "f3",
      "gxf3",
      "Be7",
      "Bf4",
      "Bxh4+",
      "Kd2",
      "Nc6",
      "c3",
      "Qf6",
      "Kc2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the knight on h6 to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White places the knight on d3 to improve central influence and set up the next tactic or break.",
      "Black pushes a pawn to f3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on f3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to d2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black places the knight on c6 to improve central influence and set up the next tactic or break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black moves the queen to f6 with a concrete task, either defending a pawn or creating a direct threat.",
      "White moves the king to c2, typically forced by checks; the priority becomes re coordinating pieces and finding safety."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-17-1c2e6c8c",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "h5",
      "Nf2",
      "Be7",
      "d4",
      "Bxh4",
      "Bxf4",
      "Bxf2+",
      "Kxf2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White captures on g4 with the knight, usually removing a key defender or converting initiative into material.",
      "Black plays h5 to either support the g4 pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White places the knight on f2 to improve central influence and set up the next tactic or break.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on h4 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on f2 with the king, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-18-af5d3b3f",
    name: "Falkbeer counterattack structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Nf6",
      "c4",
      "c6",
      "d4",
      "cxd5",
      "c5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black strikes with d5 in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on d5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to c4 to claim space and define which files and diagonals will open.",
      "Black plays c6 to kick a bishop or support d5 later, but it can cost a tempo in a position where time is everything.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on d5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White advances a central pawn to c5 to claim space and define which files and diagonals will open."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-19-32d8ddd5",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Be7",
      "d4",
      "Bxh4+",
      "Nf2",
      "Bxf2+",
      "Kxf2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White captures on g4 with the knight, usually removing a key defender or converting initiative into material.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White places the knight on f2 to improve central influence and set up the next tactic or break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on f2 with the king, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-20-24650b2e",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Nf6",
      "Nxf6+",
      "Qxf6",
      "Nc3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White captures on g4 with the knight, usually removing a key defender or converting initiative into material.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on f6 with the queen, usually removing a key defender or converting initiative into material.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-21-6188e684",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "Nf6",
      "d4",
      "d6",
      "Nd3",
      "Nxe4",
      "Bxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to e5 aiming at f7 and c6 and forcing Black to decide whether to chase the knight or allow threats.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White places the knight on d3 to improve central influence and set up the next tactic or break.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on f4 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-22-9a7773f3",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "g5",
      "h4",
      "g4",
      "Ng1"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White plays f4, offering the pawn so Black's e pawn moves off e5, opening lines and the f file for a fast attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black plays d6 to reinforce e5 and limit White's e5 jumps, trying to survive the opening with a solid center.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black pushes g5 to hold the f4 pawn and hit the knight later, but it also weakens f5 and the dark squares around the king.",
      "White pushes a pawn to h4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances g4 to chase the f3 knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White retreats to g1 as a last resort when chased; the goal is to re route to f3 or e2 without losing more material."
    
    ]
  }
]);
