import { withOpeningFeedback } from "./feedback";

export const kingsIndianDefenseLines = withOpeningFeedback([
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-01",
    "name": "Classical Variation - Bd3 Trap with ...Bg4",
    "description": "White blocks the queen's defense of d4, and Black builds pressure with ...Bg4, ...Nc6, and ...Nd7",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Bd3",
      "Bg4",
      "h3",
      "Bxf3",
      "Qxf3",
      "Nc6",
      "Be3",
      "Nd7",
      "Ne2",
      "Nde5",
      "dxe5",
      "Nxe5",
      "Qg3",
      "Nxd3+",
      "Kd2",
      "Nxb2"
    ],
    "explanations": [
      "White claims central space and prepares a broad pawn center.",
      "Let’s learn the King’s Indian Defense! This leads to extremely fun games when White plays d4. Step 1: knight to f6.",
      "White supports d4 and grabs more space on the queenside.",
      "Black prepares the kingside fianchetto and long-term pressure on the center.",
      "White develops naturally and reinforces e4.",
      "Black places the bishop on the long diagonal where it will help target d4.",
      "White builds the classical center with pawns on d4 and e4.",
      "Black supports the thematic ...e5 break and keeps the structure flexible.",
      "White develops and prepares to castle.",
      "Black castles early so the king is safe before the counterplay begins.",
      "Bd3 looks natural, but it also blocks the queen from helping defend d4.",
      "Black pins the knight because removing that defender makes d4 much harder to hold.",
      "White questions the bishop, but this also helps Black clarify the plan.",
      "Black is happy to trade here because the real target is White's center, especially d4.",
      "White keeps the center intact, but the queen becomes a tactical target later.",
      "Black adds a second attacker to d4 and develops with purpose.",
      "White tries to hold d4 and finish development.",
      "Black reroutes the knight to open the bishop and renew the pressure on d4.",
      "White adds one more defender, trying to keep the center together.",
      "Black jumps into e5, hitting d3 and increasing the tactical strain on White's setup.",
      "White removes the knight, but this does not solve the underlying pressure.",
      "Black restores the knight to an active central square and keeps the bishop on d3 hanging in the air.",
      "White points at g7, but the center and queenside are still collapsing.",
      "Black finally collects the bishop with check, which is the whole tactical point of the setup.",
      "White's king is dragged into the center and loses the right to castle.",
      "Black wins another pawn with tempo and emerges clearly up material."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-02",
    "name": "Classical Variation with e5 break",
    "description": "Typical central tension with early e5 challenge",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "O-O",
      "exd4",
      "Nxd4",
      "Re8",
      "f3",
      "c6",
      "Be3",
      "d5",
      "cxd5",
      "Nxd5",
      "Bf2",
      "Nf4",
      "Bc4",
      "Qg5",
      "Bg3",
      "Qc5"
    ],
    "explanations": [
      "White establishes central control with the queen's pawn opening.",
      "Black develops the knight to its natural square, attacking central squares.",
      "White expands on the queenside, supporting d4 and gaining space.",
      "Black prepares the King's Indian formation with the fianchetto.",
      "White develops the knight to support the e4 advance.",
      "Black completes the fianchetto, placing the bishop on the critical diagonal.",
      "White establishes the classical pawn center with d4 and e4.",
      "Black supports the e5 break, typical King's Indian structure.",
      "White develops the knight, preparing kingside castling.",
      "Black castles early, preparing counterplay.",
      "White develops the bishop quietly, preparing to castle kingside.",
      "Black executes the central break, challenging White's center immediately.",
      "White castles to safety before the tension escalates.",
      "Black resolves the central tension in their favor.",
      "White recaptures with the knight, controlling central squares.",
      "Black's rook occupies the half-open e-file, putting pressure on e4.",
      "White strengthens the e4 pawn but weakens kingside dark squares.",
      "Black prepares the d5 advance, challenging White's center further.",
      "White develops the bishop to defend d4 and control dark squares.",
      "Black breaks in the center, opening the game for their pieces.",
      "White captures to relieve pressure but gives up the center.",
      "Black recaptures with the knight, occupying a strong central square.",
      "White retreats the bishop, avoiding exchange but becoming passive.",
      "Black's knight jumps to an aggressive outpost, attacking g2 and e2.",
      "White develops the bishop with tempo, attacking f7.",
      "Black's queen enters the game with a double attack on g2 and c5.",
      "White's bishop blocks the queen's attack on g2.",
      "Black's queen retreats to a safe square with an attack on the bishop."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-03",
    "name": "Four Pawns Attack with b5 gambit",
    "description": "Aggressive Four Pawns Attack met with Benko-style gambit",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "Bd3",
      "exd5",
      "cxd5",
      "b5",
      "Nxb5",
      "Re8",
      "Nc3",
      "Nxe4",
      "Nxe4",
      "f5"
    ],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight, preparing the King's Indian setup.",
      "White expands on the queenside, supporting d4 and fighting for space.",
      "Black prepares the King's Indian formation with the fianchetto.",
      "White develops the knight to support the e4 advance.",
      "Black completes the fianchetto, controlling the long diagonal.",
      "White builds a massive pawn center with d4, e4, and f4.",
      "Black supports the e5 break and stabilizes the center.",
      "White begins the aggressive Four Pawns Attack.",
      "Black castles into the storm, preparing a counterattack.",
      "White develops the knight, supporting the center.",
      "Black counterattacks White's center from the queenside.",
      "White advances to gain space, typical in the Four Pawns Attack.",
      "Black immediately challenges the advanced d5 pawn.",
      "White develops the bishop to an active diagonal.",
      "Black captures to open the e-file for their rook.",
      "White recaptures, maintaining the pawn chain but opening the c-file.",
      "Black sacrifices a pawn Benko-style for queenside initiative.",
      "White accepts the gambit, winning a pawn but delaying development.",
      "Black's rook occupies the e-file, putting pressure on e4.",
      "White returns the knight to a development square.",
      "Black executes a tactical shot, capturing the central pawn.",
      "White is forced to recapture.",
      "Black attacks the knight with the pawn, gaining tempo and space."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-04",
    "name": "Exchange Variation with queen trade",
    "description": "Early queen exchange leads to simplified endgame-type position",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "dxe5",
      "dxe5",
      "Qxd8",
      "Rxd8",
      "Nxe5",
      "Nxe4",
      "Nxf7",
      "Bxc3+",
      "bxc3",
      "Kxf7"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight to its natural square.",
      "White expands on the queenside, supporting d4 and gaining space.",
      "Black prepares the King's Indian formation.",
      "White develops the knight, supporting e4.",
      "Black completes the fianchetto development.",
      "White establishes the classical center.",
      "Black supports the e5 break.",
      "White continues natural knight development.",
      "Black castles early.",
      "White develops the bishop quietly, preparing to castle.",
      "Black executes the central break, challenging White's center.",
      "White captures to resolve the tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying the position.",
      "Black recaptures with the rook, now controlling the d-file.",
      "White's knight captures the central pawn, winning material.",
      "Black counterattacks, capturing with tempo on the knight.",
      "White sacrifices the knight, attacking the rook and king.",
      "Black's bishop captures with check, winning the knight back.",
      "White is forced to recapture, damaging the pawn structure.",
      "Black's king captures the knight, resulting in roughly equal material."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-05",
    "name": "Four Pawns Attack with early e5",
    "description": "Aggressive pawn push leads to tactical complications",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "e5",
      "dxe5",
      "fxe5",
      "Nfd7",
      "Nf3",
      "c5",
      "Be3",
      "cxd4",
      "Bxd4",
      "Nc6",
      "Be2",
      "Nxd4",
      "Qxd4",
      "Nxe5",
      "Qxd8",
      "Rxd8",
      "Nxe5",
      "Bxe5"
    ],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight to an active square.",
      "White expands on the queenside, Queen's Gambit style.",
      "Black prepares the King's Indian signature move.",
      "White develops the knight to support e4.",
      "Black completes the fianchetto development.",
      "White builds a classical center.",
      "Black supports the e5 break.",
      "White begins the extremely aggressive Four Pawns Attack.",
      "Black castles into White's attack.",
      "White immediately pushes the central pawn, gaining space.",
      "Black captures to challenge White's center.",
      "White recaptures, opening the f-file.",
      "Black's knight retreats to challenge the e5 pawn.",
      "White develops the knight, supporting the center.",
      "Black counterattacks White's center.",
      "White develops the bishop to defend d4.",
      "Black captures to open the c-file.",
      "White recaptures with the bishop, controlling the center.",
      "Black develops the knight with an attack on the bishop.",
      "White's bishop retreats to safety.",
      "Black captures the bishop, simplifying.",
      "White recaptures with the queen.",
      "Black's knight captures the central pawn.",
      "White trades queens, simplifying to an endgame.",
      "Black recaptures with the rook.",
      "White's knight captures the knight.",
      "Black's bishop recaptures, completing the simplification."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-06",
    "name": "Orthodox Classical - ...Nf4 and ...Nh3+",
    "description": "Black uses the e-file and dark-square pressure to drive a knight into h3 with check",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "O-O",
      "exd4",
      "Nxd4",
      "Re8",
      "f3",
      "c6",
      "Be3",
      "d5",
      "cxd5",
      "Nxd5",
      "Bf2",
      "Nf4",
      "Bc4",
      "Qg5",
      "g3",
      "Nh3+"
    ],
    "explanations": [
      "White takes central space and starts a standard queen-pawn setup.",
      "Black develops actively and prepares the King's Indian structure.",
      "White supports d4 and expands on the queenside.",
      "Black prepares the kingside fianchetto.",
      "White develops and supports the center.",
      "Black completes the fianchetto and points the bishop toward the center.",
      "White builds the classical pawn duo on d4 and e4.",
      "Black keeps the center flexible and prepares the usual ...e5 break.",
      "White develops naturally and gets ready to castle.",
      "Black castles before opening the center.",
      "White chooses the main classical setup.",
      "Black strikes with ...e5, challenging the center and opening lines for the g7 bishop.",
      "White castles instead of clarifying the tension immediately.",
      "Black exchanges on d4 to pull White's knight forward and open central files.",
      "White recaptures and keeps central space.",
      "Black places the rook on the e-file, adding pressure to e4 and supporting later central breaks.",
      "White reinforces e4, but this also loosens the dark squares around the king.",
      "Black prepares ...d5, the standard follow-up to challenge White's center again.",
      "White develops and connects the rooks.",
      "Black breaks with ...d5 and asks White to resolve the central tension.",
      "White captures, giving up some central control to avoid being squeezed.",
      "Black recaptures with a well-placed knight that heads toward active squares.",
      "White retreats the bishop and keeps an eye on f7.",
      "Black jumps to f4, attacking key dark squares and creating threats against g2 and h3.",
      "White develops with tempo, but the kingside is already under pressure.",
      "Black's queen joins the attack and supports tactical ideas against the white king.",
      "White covers immediate threats with g3, but h3 and the dark squares become even weaker.",
      "Black lands ...Nh3+ and forces the king into an awkward defensive position."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-07",
    "name": "Four Pawns Attack with queenside expansion",
    "description": "White pushes pawns aggressively, Black counters with Re8",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "Bd3",
      "exd5",
      "cxd5",
      "b5",
      "O-O",
      "c4",
      "Bc2",
      "b4",
      "Ne2",
      "Re8"
    ],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight to its natural square.",
      "White expands on the queenside.",
      "Black prepares the King's Indian formation.",
      "White develops the knight to support e4.",
      "Black completes the fianchetto.",
      "White builds a massive center.",
      "Black supports the e5 break.",
      "White begins the Four Pawns Attack.",
      "Black castles kingside.",
      "White develops the knight.",
      "Black challenges White's center.",
      "White advances to gain space.",
      "Black challenges the d5 pawn.",
      "White develops the bishop to an active diagonal.",
      "Black captures to open the e-file.",
      "White recaptures, maintaining structure.",
      "Black sacrifices a pawn Benko-style.",
      "White castles to safety.",
      "Black advances the pawn to cramp White's bishop.",
      "White's bishop retreats.",
      "Black advances the pawn, attacking the knight.",
      "White's knight retreats to avoid capture.",
      "Black's rook occupies the half-open file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-08",
    "name": "Sämisch Variation with Bh6 exchange",
    "description": "White plays f3 and Bh6, forcing bishop exchange",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "cxd5",
      "a6",
      "Bh6",
      "Nxe4",
      "Nxe4",
      "Qh4+",
      "g3",
      "Qxh6",
      "Qxh6",
      "Bxh6",
      "Nxd6",
      "Nd7"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation, preparing Be3 and Qd2.",
      "Black castles early.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White advances to gain space.",
      "Black opens the position.",
      "White's queen develops to support Bh6.",
      "Black captures to open the center.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White's bishop attacks Black's strong bishop.",
      "Black executes a tactical shot, capturing the central pawn.",
      "White is forced to recapture.",
      "Black's queen checks, attacking the h6 bishop.",
      "White blocks the check with a pawn.",
      "Black's queen captures the bishop.",
      "White's queen recaptures.",
      "Black's bishop recaptures the queen.",
      "White's knight captures a pawn, winning material.",
      "Black's knight develops, attacking White's knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-09",
    "name": "Four Pawns Attack with Qa5+ tactic",
    "description": "Queen check leads to material gain for Black",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "Bd3",
      "exd5",
      "cxd5",
      "b5",
      "Bxb5",
      "Nxe4",
      "Nxe4",
      "Qa5+",
      "Nc3",
      "Bxc3+",
      "bxc3",
      "Qxb5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black plays a Benko-style gambit.",
      "White's bishop captures the pawn.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's queen checks with discovered attack on the knight.",
      "White's knight blocks the check.",
      "Black's bishop captures with check.",
      "White's pawn recaptures.",
      "Black's queen captures the bishop."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-10",
    "name": "Sämisch Variation with Bh6 and b4",
    "description": "Early Bh6 followed by queenside expansion",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "cxd5",
      "a6",
      "O-O-O",
      "b5",
      "Bh6",
      "b4"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White castles queenside, an aggressive choice.",
      "Black expands on the queenside.",
      "White attacks Black's strong bishop.",
      "Black advances the pawn, attacking the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-11",
    "name": "Sämisch Variation with Re8 pressure",
    "description": "Black develops rook to e-file for central pressure",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "exd5",
      "Re8"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures with the e-pawn, maintaining the center.",
      "Black's rook occupies the e-file, pressuring e4."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-12",
    "name": "Four Pawns Attack with early d5 advance",
    "description": "White pushes d5 immediately after Black's c5",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "e5",
      "dxe5",
      "fxe5",
      "Nfd7",
      "Nf3",
      "c5",
      "d5",
      "Nxe5",
      "Nxe5",
      "Bxe5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White immediately pushes the pawn.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's knight retreats.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn aggressively.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-13",
    "name": "Be3 Variation with early c5",
    "description": "White develops Be3 early, Black responds with c5",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Be2",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "Qa5",
      "cxd6",
      "Nxe4",
      "dxe7",
      "Re8"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing kingside castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black's queen attacks with tempo.",
      "White's pawn captures, opening the position.",
      "Black's knight captures the central pawn.",
      "White's pawn promotes to a passed pawn.",
      "Black's rook attacks the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-14",
    "name": "Sämisch Variation with queen trade",
    "description": "Early queen exchange leads to simplified middlegame",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "dxc5",
      "Qxd8",
      "Rxd8",
      "Bxc5",
      "Nc6",
      "Rd1",
      "Rxd1+",
      "Kxd1",
      "Nd7",
      "Ba3",
      "Bxc3",
      "bxc3",
      "Nde5",
      "f4",
      "Ng4",
      "Ke2",
      "Be6"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens, simplifying the position.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops with tempo.",
      "White's rook develops to the open file.",
      "Black trades rooks.",
      "White's king recaptures.",
      "Black's knight develops, attacking the bishop.",
      "White's bishop retreats.",
      "Black's bishop captures the knight.",
      "White's pawn recaptures.",
      "Black's knight moves to a central outpost.",
      "White's pawn attacks the knight.",
      "Black's knight retreats to an active square.",
      "White's king moves to safety.",
      "Black's bishop develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-15",
    "name": "Sämisch Variation with Nde5",
    "description": "Similar to previous line but with different knight maneuver",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "dxc5",
      "Qxd8",
      "Rxd8",
      "Bxc5",
      "Nc6",
      "Rd1",
      "Rxd1+",
      "Kxd1",
      "Nd7",
      "Be3",
      "Bxc3",
      "bxc3",
      "Nde5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's rook develops.",
      "Black trades rooks.",
      "White's king recaptures.",
      "Black's knight develops.",
      "White's bishop retreats.",
      "Black's bishop captures the knight.",
      "White's pawn recaptures.",
      "Black's knight moves to a strong central square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-16",
    "name": "Four Pawns Attack with Bf5 development",
    "description": "Black develops bishop to f5, challenging White's center",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "Be2",
      "exd5",
      "exd5",
      "Bf5",
      "O-O",
      "Ne4",
      "Nxe4",
      "Bxe4",
      "Bd3",
      "Bxf3",
      "Qxf3",
      "Nd7"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures with the e-pawn.",
      "Black develops the bishop actively.",
      "White castles to safety.",
      "Black's knight occupies a central outpost.",
      "White's knight captures the knight.",
      "Black's bishop recaptures.",
      "White's bishop develops, attacking the bishop.",
      "Black's bishop captures the knight.",
      "White's queen recaptures.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-17",
    "name": "Sämisch Variation with b6 and Ba6",
    "description": "Black plays b6 and Ba6 for queenside pressure",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "dxc5",
      "Qxd8",
      "Rxd8",
      "Bxc5",
      "Nc6",
      "Nge2",
      "b6",
      "Ba3",
      "Ba6"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight develops to avoid the pin.",
      "Black's pawn attacks the bishop.",
      "White's bishop retreats.",
      "Black's bishop develops to pin the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-18",
    "name": "Sämisch Variation with Qa5 and Nge2",
    "description": "White plays Nge2 to avoid queen pin on c3",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "Nge2",
      "Qa5",
      "Qd2",
      "Nc6",
      "O-O-O",
      "b6",
      "Kb1",
      "Ba6"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White's knight develops to avoid future pins.",
      "Black's queen attacks with tempo.",
      "White's queen develops to support Bh6.",
      "Black's knight develops.",
      "White castles queenside, an aggressive choice.",
      "Black prepares Ba6.",
      "White's king moves to safety.",
      "Black's bishop develops to pin the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-19",
    "name": "Glek Defense - ...Na6, ...Nc5, and ...a4 Clamp",
    "description": "Black avoids heavy theory, reroutes the knight to c5, and fixes the queenside with ...a4",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "d5",
      "a5",
      "O-O",
      "Na6",
      "a3",
      "Nc5",
      "Qc2",
      "a4",
      "Be3",
      "Nb3"
    ],
    "explanations": [
      "White takes central space with the standard queen-pawn start.",
      "Black develops flexibly and keeps the King's Indian structure in mind.",
      "White supports d4 and gains queenside space.",
      "Black prepares the kingside fianchetto.",
      "White develops and reinforces e4.",
      "Black completes the fianchetto and points at the center.",
      "White builds the classical pawn center.",
      "Black prepares the central strike and keeps the structure asymmetric.",
      "White develops toward quick castling.",
      "Black castles before starting counterplay.",
      "White finishes the standard classical development.",
      "Black plays the thematic ...e5 break to challenge the center and clear the bishop's diagonal.",
      "White grabs space with d5, which also gives Black a clear plan.",
      "Black starts queenside play with ...a5, discouraging b4 and preparing to secure c5.",
      "White castles to safety.",
      "Black chooses the Glek-style reroute. The knight heads for c5 instead of entering the heaviest main-line theory.",
      "White tries to prepare b4, which is a common but inaccurate plan here.",
      "Black reaches c5, the ideal outpost created by White's d5 advance.",
      "White develops the queen to support e4 and the queenside.",
      "Black fixes the queenside with ...a4, making b4 much harder to achieve for the rest of the game.",
      "White continues development, but the queenside is already restricted.",
      "Black jumps into b3, creating annoying pressure on c1 and the queenside dark squares."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-20",
    "name": "Averbakh Variation with Bg5",
    "description": "White pins early, but Black counters in the center and queenside instead of worrying about the pin",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Be2",
      "O-O",
      "Bg5",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "exd5",
      "Qb6",
      "Nf3",
      "Bf5",
      "O-O",
      "Ne4",
      "Nxe4",
      "Bxe4"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop.",
      "Black castles.",
      "White pins the knight early, but Black does not need to be too concerned about it.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's queen hits b2 and increases pressure on the queenside and center.",
      "White develops the knight.",
      "Black develops the bishop with tempo and keeps the initiative.",
      "White castles to safety.",
      "Black jumps into e4, using the loosened center to seize an active outpost.",
      "White's knight captures the knight.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-21",
    "name": "Exchange Variation - Bg5 Met by ...h6 and ...g5",
    "description": "After the queen trade, Black shows why an early Bg5 pin often just gives kingside tempi",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "dxe5",
      "dxe5",
      "Qxd8",
      "Rxd8",
      "Bg5",
      "Be6",
      "Nxe5",
      "h6",
      "Bh4",
      "g5",
      "Bg3",
      "Na6"
    ],
    "explanations": [
      "White takes central space with the standard opening.",
      "Black develops toward the King's Indian setup.",
      "White supports d4 and claims queenside space.",
      "Black prepares the kingside fianchetto.",
      "White develops and reinforces e4.",
      "Black completes the fianchetto and eyes the center.",
      "White builds the classical center.",
      "Black keeps the flexible ...e5 plan alive.",
      "White develops naturally.",
      "Black castles before opening the position.",
      "White develops the bishop and keeps options open.",
      "Black challenges the center with the thematic ...e5 break.",
      "White resolves the tension immediately.",
      "Black recaptures and opens the d-file for active piece play.",
      "White exchanges queens, heading for a quieter structure.",
      "Black recaptures with the rook and keeps easy development.",
      "White pins the knight, but in this structure the pin is not very dangerous because the knight is already well defended.",
      "Black develops smoothly and gets ready to challenge White's extra central pawn.",
      "White grabs the e5 pawn, hoping to come out a pawn up.",
      "Black kicks the bishop immediately and gains a useful tempo for kingside expansion.",
      "White retreats, but the bishop is already starting to lose influence.",
      "Black keeps chasing the bishop with ...g5, gaining space and more time for active play.",
      "White retreats again and ends up pushed toward the side of the board.",
      "Black starts the familiar ...Na6-c5 reroute while White's bishop remains misplaced."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-22",
    "name": "Exchange Variation with Nxe4",
    "description": "Early knight exchange after queen trade",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "dxe5",
      "dxe5",
      "Qxd8",
      "Rxd8",
      "Nxe5",
      "Nxe4",
      "Nxe4",
      "Bxe5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White captures to resolve tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's knight captures the central pawn.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-23",
    "name": "Classical Variation with knight exchange",
    "description": "Early knight exchange in the center",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "O-O",
      "exd4",
      "Nxd4",
      "Re8",
      "f3",
      "c6",
      "Be3",
      "d5",
      "cxd5",
      "Nxd5",
      "Nxd5",
      "cxd5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White develops the bishop.",
      "Black breaks in the center.",
      "White captures to relieve tension.",
      "Black recaptures with the knight.",
      "White exchanges knights.",
      "Black recaptures with the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-24",
    "name": "Sämisch Variation with Nd5",
    "description": "White plays Nd5 with tactical complications",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "dxc5",
      "Qxd8",
      "Rxd8",
      "Bxc5",
      "Nc6",
      "Nd5",
      "Nd7",
      "Nxe7+",
      "Nxe7",
      "Bxe7",
      "Bxb2"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight moves to a strong central square.",
      "Black's knight develops.",
      "White's knight checks, winning a pawn.",
      "Black's knight recaptures.",
      "White's bishop captures the knight.",
      "Black's bishop captures the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-25",
    "name": "Sämisch Variation with a4",
    "description": "White plays a4 to prevent Black's queenside expansion",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "cxd5",
      "a6",
      "a4",
      "Qa5",
      "Bd3",
      "b5",
      "Nge2",
      "b4",
      "Nd1",
      "Nbd7"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White prevents Black's queenside expansion.",
      "Black's queen attacks with tempo.",
      "White develops the bishop.",
      "Black expands on the queenside.",
      "White's knight develops to avoid pins.",
      "Black advances the pawn, attacking the knight.",
      "White's knight retreats to safety.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-26",
    "name": "Four Pawns Attack with dxe6",
    "description": "White captures on e6 early, opening the position",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "dxe6",
      "fxe6",
      "Bd3",
      "Nc6",
      "O-O",
      "Nd4",
      "Nxd4",
      "cxd4",
      "Nb5",
      "e5",
      "fxe5",
      "dxe5",
      "c5",
      "Be6"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White captures, opening the position.",
      "Black recaptures with the f-pawn.",
      "White develops the bishop.",
      "Black's knight develops.",
      "White castles to safety.",
      "Black's knight occupies a strong square.",
      "White exchanges knights.",
      "Black recaptures with the pawn.",
      "White's knight jumps forward.",
      "Black advances the pawn.",
      "White captures the pawn.",
      "Black recaptures.",
      "White advances the pawn.",
      "Black's bishop develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-27",
    "name": "Be3 Variation with f3",
    "description": "White plays Be3 followed by f3",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Be2",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "Qa5",
      "f3",
      "dxc5"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black's queen attacks with tempo.",
      "White strengthens the center but weakens dark squares.",
      "Black recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-28",
    "name": "Glek Defense - Bg5 Met by ...h6 and ...Nh7-f5",
    "description": "The bishop pin does little, while Black gains tempi and prepares the standard kingside pawn storm",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "d5",
      "a5",
      "Bg5",
      "h6",
      "Bh4",
      "Na6",
      "Nd2",
      "Qe8",
      "O-O",
      "Nh7"
    ],
    "explanations": [
      "White takes central space with the standard opening.",
      "Black develops flexibly and aims for the King's Indian structure.",
      "White supports d4 and claims more territory.",
      "Black prepares the kingside fianchetto.",
      "White develops and reinforces the center.",
      "Black completes the fianchetto and points at the center.",
      "White builds the classical pawn duo.",
      "Black supports the thematic ...e5 break.",
      "White develops toward kingside castling.",
      "Black castles before starting active play.",
      "White finishes the standard classical setup.",
      "Black strikes in the center with ...e5.",
      "White locks the center, which is exactly the kind of position where Black can attack on the wings.",
      "Black begins the queenside clamp and prepares the ...Na6-c5 reroute.",
      "White pins the knight, but the pin is not especially meaningful because f6 is already well defended.",
      "Black asks the bishop immediately and gains a useful tempo.",
      "White retreats, and the bishop starts drifting away from the main battle.",
      "Black sends the knight toward c5, the key square in this setup.",
      "White reorganizes to support the center.",
      "Black moves the queen to e8, a standard King's Indian move that supports ...Nh7 and ...f5.",
      "White castles, but Black's plan is already clear.",
      "Black reroutes the knight to h7 to prepare the main kingside break with ...f5."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-29",
    "name": "Sämisch Variation with Nxe7+",
    "description": "Tactical complications with knight check",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "dxc5",
      "dxc5",
      "Qxd8",
      "Rxd8",
      "Bxc5",
      "Nc6",
      "Nd5",
      "Nd7",
      "Bxe7",
      "Nxe7",
      "Nxe7+",
      "Kf8",
      "Nd5",
      "Bxb2"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight moves to a strong central square.",
      "Black's knight develops.",
      "White's bishop captures the knight.",
      "Black's knight recaptures.",
      "White's knight checks.",
      "Black's king moves to safety.",
      "White's knight moves to a strong square.",
      "Black's bishop captures the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-30",
    "name": "Sämisch Variation with Ra3",
    "description": "White develops rook to a3 for queenside defense",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Qd2",
      "exd5",
      "cxd5",
      "a6",
      "a4",
      "Qa5",
      "Ra3",
      "Nbd7"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White prevents Black's queenside expansion.",
      "Black's queen attacks with tempo.",
      "White develops the rook to an unusual square for defense.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-31",
    "name": "Four Pawns Attack with Bg4 exchange",
    "description": "Black develops Bg4, leading to bishop exchange",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f4",
      "O-O",
      "Nf3",
      "c5",
      "d5",
      "e6",
      "Be2",
      "exd5",
      "cxd5",
      "Bg4",
      "O-O",
      "Nbd7",
      "h3",
      "Bxf3",
      "Bxf3",
      "Re8"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black develops the bishop actively.",
      "White castles to safety.",
      "Black's knight develops.",
      "White attacks the bishop.",
      "Black exchanges bishop for knight.",
      "White recaptures with the bishop.",
      "Black's rook occupies the e-file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-32",
    "name": "Classical Variation with Kh1",
    "description": "White plays Kh1 early, preparing kingside play",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "O-O",
      "exd4",
      "Nxd4",
      "Re8",
      "f3",
      "c6",
      "Kh1",
      "Nbd7",
      "Bf4",
      "Nh5",
      "Bxd6",
      "Qf6",
      "Nb3",
      "Nf4"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White moves the king to safety, preparing kingside play.",
      "Black's knight develops.",
      "White develops the bishop actively.",
      "Black's knight attacks the bishop.",
      "White's bishop captures the pawn.",
      "Black's queen attacks the bishop.",
      "White's knight retreats.",
      "Black's knight moves to an aggressive square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-33",
    "name": "Be3 Variation with Nf3",
    "description": "White develops Be3 and Nf3",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Be2",
      "O-O",
      "Be3",
      "c5",
      "d5",
      "e6",
      "Nf3",
      "exd5",
      "cxd5",
      "Re8"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White develops the knight.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's rook occupies the e-file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-34",
    "name": "Orthodox Main Line with Bg5 and ...h6",
    "description": "Black keeps the normal setup and meets the bishop pin with a direct gain of tempo",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "O-O",
      "exd4",
      "Nxd4",
      "Re8",
      "f3",
      "c6",
      "Kh1",
      "Nbd7",
      "Bg5",
      "h6"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White moves the king to safety.",
      "Black's knight develops.",
      "White pins the knight, but the pin does not stop Black's main plan.",
      "Black gains a tempo with ...h6 and asks the bishop to prove it belongs on g5."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-35",
    "name": "Exchange Variation with Nd5",
    "description": "White plays Nd5 after queen exchange",
    "moves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "dxe5",
      "dxe5",
      "Qxd8",
      "Rxd8",
      "Nd5",
      "Rd7",
      "Nxe5",
      "Nxd5",
      "Nxd7",
      "Nb4",
      "Nxb8",
      "Nc2+",
      "Kd1",
      "Nxa1",
      "Bf4",
      "Rxb8"
    ],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White captures to resolve tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's knight moves to a strong central square.",
      "Black's rook moves to defend.",
      "White's knight captures the central pawn.",
      "Black's knight captures the knight.",
      "White's knight captures the rook.",
      "Black's knight moves with a fork threat.",
      "White's knight captures the knight.",
      "Black's knight forks king and rook.",
      "White's king moves to safety.",
      "Black's knight captures the rook.",
      "White's bishop develops.",
      "Black's rook captures the knight."
    ]
  }
]);
