import { withOpeningFeedback } from "./feedback";

export const kingsGambitSEOText = `
The King's Gambit (1. e4 e5 2. f4) is the ultimate "Romantic" opening. We sacrifice a pawn on move two to achieve three things: total central control, a rapid lead in development, and a "highway" for our rook on the open f-file.

The goal isn't to win the pawn back—it's to checkmate the king before Black can coordinate. Your primary target is almost always the weak {{square f7}} square.

These drills cover the soul of the gambit:
- Accepted Lines: Punishing greedy defense like ...g5 and ...f6, and handling the direct central counterstrike ...d5.
- The Bishop's Gambit: Why we don't fear ...Qh4+ and how the king finds a home on {{square f1}}.
- The Knight's Gambit: Using the "Golden Rule" (3. Nf3) to prevent checks and launch a crushing attack.
- Declined Traps: How to punish Black for being too solid or overusing pins.

Every move in the King's Gambit should be a threat. Don't fear the material—focus on the attack!
`;

export const kingsGambitLines = withOpeningFeedback([
  {
    category: "King's Gambit",
    id: "kingsGambit-01-899b8126",
    name: "Accepted: ...f6 punished by queen checks",
    description: "Black tries to hold the pawn with ...f6, but this opens the 'corridor of death' for the king. White wins with a brutal series of queen checks.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Ke8",
      "Qh5+",
      "Ke7",
      "Qe5+",
      "Kf7",
      "Bc4+"
    ],
    explanations: [
      "Let's learn the King's Gambit! White claims the center. The attack begins! {{square e4}}",
      "Black answers symmetrically, but we're about to change that.",
      "The King's Gambit! We offer the f-pawn to deflect Black's central control and open the f-file for our rook.",
      "Black accepts! Now the f-file is a highway for our future attack.",
      "The Golden Rule of the King's Gambit: develop the knight to prevent the devastating ...Qh4+ check.",
      "Black tries to support their extra pawn, but they're creating big weaknesses on the kingside.",
      "White immediately undermines the pawn chain. We want to rip open the kingside before Black can develop.",
      "The losing move! Black tries to hold everything with ...{{square f6}}, but this creates a 'corridor of death' straight to their king.",
      "Sacrifice! We give up the knight to rip open the dark squares around the king.",
      "Black takes, but their king is now completely exposed.",
      "Boom! The queen enters the attack with check. Black's kingside is a disaster zone.",
      "Black's king is forced to step into the center. No safety here!",
      "Recapture with check! We're winning back material while keeping the pressure at 100%.",
      "The king tries to hide, but the queen won't let him rest.",
      "Check again! We're driving the king back into the open where he blocks his own pieces.",
      "Forced. The king is walking into a nightmare.",
      "Check! The queen is a monster in the center of the board.",
      "Black's king is now a nomad, wandering the board with no shelter.",
      "Bring in the reserves! The bishop develops with check, targeting the weak {{square f7}} square. The game is over."
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-02-1c16d08e",
    name: "Accepted: ...d6 and ...Bg4 setup",
    description: "A more solid try for Black, but White simply completes development and regains the pawn with a superior center.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "Bg4",
      "Bxf4",
      "Bxf3",
      "Qxf3"
    ],
    explanations: [
      "The classic opening move.",
      "Black meets us in the center.",
      "King's Gambit! We're trading a flank pawn for a central one and an open file.",
      "Accepted. Black is a pawn up, but we have the initiative.",
      "Develop the knight to guard against the queen check. Safety first!",
      "Fischer's Defense. Black prepares to hold the kingside solid.",
      "Take full control! We build the dream pawn center with pawns on {{square e4}} and {{square d4}}.",
      "Black pins the knight, trying to reduce our attacking power.",
      "Develop the bishop and win our pawn back! We've achieved our goal: a massive center and active pieces.",
      "Black trades off their bishop to damage our structure, but they're losing time.",
      "Recapture with the queen. White has a lead in development and a perfect center. The attack continues!"
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-03-22395211",
    name: "Modern ...g4 chase line",
    description: "Black aggressively chases the knight, leading to a sharp tactical battle where White targets the f4 and f7 weaknesses.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "Bg7",
      "Nxf4"
    ],
    explanations: [
      "Claiming the center.",
      "Central response.",
      "The Gambit offer.",
      "Accepted! The f-file is now open for our business.",
      "Prevention! We stop the queen check and prepare to develop.",
      "Black overextends their pawns to hold onto the material.",
      "Undermine! We attack the base of the pawn chain immediately.",
      "Black chases our knight away, but they've left huge holes in their position.",
      "Jump forward! Our knight lands on a powerful outpost, eyeing {{square f7}} and {{square g4}}.",
      "Black tries to stabilize, but their kingside is looking very airy.",
      "Develop the 'King's Gambit Bishop' to its best square, aiming directly at the weak {{square f7}} point.",
      "Black develops a defender for {{square f7}}.",
      "Grab the center! We now have the space and the pieces ready for a breakthrough.",
      "Black tries to kick our knight, but we're happy to relocate.",
      "The knight moves to {{square d3}}, where it defends {{square e5}} and prepares to jump back into the action.",
      "Black fianchettos, but they're still behind in the race to coordinate.",
      "Recapture the pawn! White has a fantastic position with active pieces and a clear target on f7."
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-04-017652b4",
    name: "Accepted: ...Nf6 runs into Qxg7+",
    description: "Transcript-backed punishment line where Black's ...f6 and ...Nf6 leave the back rank and dark squares loose.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Bg7",
      "Qxg7+"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays {{square f6}} to support {{square g5}} and clamp down on {{square e5}}, but it weakens {{square e6}} and opens lines if White can sacrifice to rip it open.",
      "White captures on {{square g5}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square g5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to {{square e7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black develops the bishop to {{square g7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-05-32f16c21",
    name: "Accepted: ...Kf7 drops the queen",
    description: "Short forcing trap where Black's king walk leaves the queen on d8 undefended.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Kf7",
      "Qxd8"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays {{square f6}} to support {{square g5}} and clamp down on {{square e5}}, but it weakens {{square e6}} and opens lines if White can sacrifice to rip it open.",
      "White captures on {{square g5}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square g5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to {{square e7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to {{square f7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White captures on {{square d8}} with the queen, usually removing a key defender or converting initiative into material."
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-06-ab502c92",
    name: "Accepted: ...Rg8 tactical cleanup",
    description: "Longer forcing line where White keeps checking until the g8 rook falls.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Rg8",
      "exf6+",
      "Kf7",
      "Bc4+",
      "d5",
      "Bxd5+",
      "Be6",
      "Bxe6+",
      "Kxe6",
      "Qxg8+"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays {{square f6}} to support {{square g5}} and clamp down on {{square e5}}, but it weakens {{square e6}} and opens lines if White can sacrifice to rip it open.",
      "White captures on {{square g5}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square g5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to {{square e7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black activates a rook to {{square g8}} to pressure an open file created by earlier trades.",
      "White gives check to keep the initiative.",
      "Black moves the king to {{square f7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black strikes with {{square d5}} in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black develops the bishop to {{square e6}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on {{square e6}} with the king, usually removing a key defender or converting initiative into material.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-07-5b92c57a",
    name: "Accepted with ...d5 counterstrike and ...Bd6",
    description: "This is not a Falkbeer Countergambit. It is an accepted King's Gambit line where Black counterstrikes with ...d5 after taking on f4.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Qxd5",
      "Nc3",
      "Qe6+",
      "Be2",
      "Bd6",
      "O-O",
      "Nf6",
      "Bb5+",
      "Bd7",
      "Re1"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black strikes with {{square d5}} in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on {{square d5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square d5}} with the queen, usually removing a key defender or converting initiative into material.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White develops the bishop to {{square e2}}, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to {{square d6}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black develops the bishop to {{square d7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White activates a rook to {{square e1}} to pressure an open file created by earlier trades."
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-08-22395163",
    name: "Accepted with ...d5 counterstrike and ...Bc5",
    description: "Accepted King's Gambit line where Black mixes the central ...d5 break with an active bishop post on c5.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Qxd5",
      "Nc3",
      "Qe6+",
      "Be2",
      "Bc5",
      "d4",
      "Bd6",
      "O-O",
      "Nf6",
      "Bb5+",
      "c6",
      "Re1"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black strikes with {{square d5}} in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on {{square d5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square d5}} with the queen, usually removing a key defender or converting initiative into material.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White develops the bishop to {{square e2}}, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to {{square c5}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black develops the bishop to {{square d6}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black plays {{square c6}} to kick a bishop or support {{square d5}} later, but it can cost a tempo in a position where time is everything.",
      "White activates a rook to {{square e1}} to pressure an open file created by earlier trades."
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-09-89178ff9",
    name: "Accepted: White consolidates after the queen checks",
    description: "Transcript-backed follow-up where White cashes in the attack into a safer plus by regaining material and finishing development.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "f6",
      "Nxg5",
      "fxg5",
      "Qh5+",
      "Ke7",
      "Qxg5+",
      "Nf6",
      "e5",
      "Kf7",
      "Qxf4",
      "Qe7",
      "Be2",
      "Bg7",
      "O-O"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black plays {{square f6}} to support {{square g5}} and clamp down on {{square e5}}, but it weakens {{square e6}} and opens lines if White can sacrifice to rip it open.",
      "White captures on {{square g5}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square g5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the king to {{square e7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square e5}} to claim space and define which files and diagonals will open.",
      "Black moves the king to {{square f7}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White captures on {{square f4}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black moves the queen to {{square e7}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White develops the bishop to {{square e2}}, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to {{square g7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank."
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-10-3ffce502",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Bxg4",
      "Qxg4",
      "Nf6",
      "Qxf4",
      "Nc6",
      "Bb5"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White captures on {{square g4}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square g4}} with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on {{square g4}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White captures on {{square f4}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White plays B{{square b5}} to pin a knight and increase pressure on {{square e5}} or {{square c6}}, making defense of the center awkward."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-11-e618b761",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "Be7",
      "Bxf4",
      "Bxh4+",
      "g3",
      "Bf6",
      "c3"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square h5}} to either support the {{square g4}} pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the {{knight h6 full}} to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White places the {{knight d3 full}} to improve central influence and set up the next tactic or break.",
      "Black develops the bishop to {{square e7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on {{square f4}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White pushes a pawn to {{square g3}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to {{square f6}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to {{square c3}} to support a plan; check what weakness it creates and whether it helps development or attack."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-12-3a24a9e2",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "f3",
      "gxf3",
      "gxf3",
      "Qxf3",
      "Bg4",
      "Qf2"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square h5}} to either support the {{square g4}} pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the {{knight h6 full}} to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White places the {{knight d3 full}} to improve central influence and set up the next tactic or break.",
      "Black pushes a pawn to {{square f3}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on {{square f3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on {{square f3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on {{square f3}} with the queen, usually removing a key defender or converting initiative into material.",
      "Black develops the bishop to {{square g4}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White moves the queen to {{square f2}} with a concrete task, either defending a pawn or creating a direct threat."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-13-512545cd",
    name: "King's Gambit attacking setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "Nf6",
      "Nc3"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-14-a5f5f500",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Rh7",
      "d4",
      "d6",
      "Nxf7",
      "Rxf7",
      "Bxf7+",
      "Kxf7",
      "Bxf4"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square h5}} to either support the {{square g4}} pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black activates a rook to {{square h7}} to pressure an open file created by earlier trades.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White captures on {{square f7}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on {{square f7}} with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on {{square f7}} with the king, usually removing a key defender or converting initiative into material.",
      "White captures on {{square f4}} with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-15-9ce7614e",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "Nf6",
      "d4",
      "Nxe4",
      "Bxf4"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black captures on {{square e4}} with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on {{square f4}} with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-16-60fa99dd",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "h5",
      "Bc4",
      "Nh6",
      "d4",
      "d6",
      "Nd3",
      "f3",
      "gxf3",
      "Be7",
      "Bf4",
      "Bxh4+",
      "Kd2",
      "Nc6",
      "c3",
      "Qf6",
      "Kc2"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square h5}} to either support the {{square g4}} pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White develops B{{square c4}} to point at {{square f7}} and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black places the {{knight h6 full}} to improve central influence and set up the next tactic or break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White places the {{knight d3 full}} to improve central influence and set up the next tactic or break.",
      "Black pushes a pawn to {{square f3}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on {{square f3}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops the bishop to {{square e7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops B{{square f4}} to hit {{square c7}} or to support Q{{square b3}} ideas; it also helps complete development fast.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to {{square d2}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black places the {{knight c6 full}} to improve central influence and set up the next tactic or break.",
      "White pushes a pawn to {{square c3}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black moves the queen to {{square f6}} with a concrete task, either defending a pawn or creating a direct threat.",
      "White moves the king to {{square c2}}, typically forced by checks; the priority becomes re coordinating pieces and finding safety."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-17-1c2e6c8c",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "h5",
      "Nf2",
      "Be7",
      "d4",
      "Bxh4",
      "Bxf4",
      "Bxf2+",
      "Kxf2"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White captures on {{square g4}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black plays {{square h5}} to either support the {{square g4}} pawn chain or gain space, but it can also become a hook for White to open the h file.",
      "White places the {{knight f2 full}} to improve central influence and set up the next tactic or break.",
      "Black develops the bishop to {{square e7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black captures on {{square h4}} with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on {{square f4}} with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square f2}} with the king, usually removing a key defender or converting initiative into material."
    
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-18-af5d3b3f",
    name: "Accepted with ...Nf6 and c5 space wedge",
    description: "Accepted King's Gambit structure where White uses c4 and c5 for space after Black's ...Nf6 and ...c6 setup.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d5",
      "exd5",
      "Nf6",
      "c4",
      "c6",
      "d4",
      "cxd5",
      "c5"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black strikes with {{square d5}} in the center, aiming to trade off White's attacking momentum by opening lines for development and the queen.",
      "White captures on {{square d5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square c4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square c6}} to kick a bishop or support {{square d5}} later, but it can cost a tempo in a position where time is everything.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black captures on {{square d5}} to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White advances a central pawn to {{square c5}} to claim space and define which files and diagonals will open."
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-19-32d8ddd5",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Be7",
      "d4",
      "Bxh4+",
      "Nf2",
      "Bxf2+",
      "Kxf2"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White captures on {{square g4}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black develops the bishop to {{square e7}}, choosing a diagonal that targets a weakness or supports a central break.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White places the {{knight f2 full}} to improve central influence and set up the next tactic or break.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White captures on {{square f2}} with the king, usually removing a key defender or converting initiative into material."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-20-24650b2e",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "d6",
      "Nxg4",
      "Nf6",
      "Nxf6+",
      "Qxf6",
      "Nc3"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White captures on {{square g4}} with the knight, usually removing a key defender or converting initiative into material.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "Black captures on {{square f6}} with the queen, usually removing a key defender or converting initiative into material.",
      "White plays N{{square c3}} to add central control over {{square d5}} and {{square e4}} and to support a future {{square d4}} push or recapture."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-21-6188e684",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "Nf6",
      "d4",
      "d6",
      "Nd3",
      "Nxe4",
      "Bxf4"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White jumps to {{square e5}} aiming at {{square f7}} and {{square c6}} and forcing Black to decide whether to chase the knight or allow threats.",
      "Black develops N{{square f6}} to contest the center, hitting {{square e5}} or {{square e4}} and preparing quick castling.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White places the {{knight d3 full}} to improve central influence and set up the next tactic or break.",
      "Black captures on {{square e4}} with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on {{square f4}} with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  }
,
{
    category: "King's Gambit",
    id: "kingsGambit-22-9a7773f3",
    name: "Modern ...g4 chase line",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "d6",
      "d4",
      "g5",
      "h4",
      "g4",
      "Ng1"
    ],
    explanations: [
      
      "White takes the center and prepares the attack.",
      "Black mirrors, but the symmetry won't last long.",
      "The King's Gambit! We offer a pawn to open the f-file highway.",
      "Accepted. Black accepts the challenge and the material.",
      "The Golden Rule: stop the queen check and start development.",
      "Black plays {{square d6}} to reinforce {{square e5}} and limit White's {{square e5}} jumps, trying to survive the opening with a solid center.",
      "White advances a central pawn to {{square d4}} to claim space and define which files and diagonals will open.",
      "Black pushes {{square g5}} to hold the {{square f4}} pawn and hit the knight later, but it also weakens {{square f5}} and the dark squares around the king.",
      "White pushes a pawn to {{square h4}} to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black advances {{square g4}} to chase the {{square f3}} knight away from the center; the tradeoff is the g file and dark squares can become targets.",
      "White retreats to {{square g1}} as a last resort when chased; the goal is to re route to {{square f3}} or {{square e2}} without losing more material."
    
    ]
  }
,
  {
    category: "King's Gambit",
    id: "kingsGambit-23-c4b1d7a2",
    name: "Morphy line: Ng5 sacrifice and Qxg4",
    description: "The soul of Romantic chess: White sacrifices a knight to drag the king into the open, then launches a devastating attack with every piece.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ng5",
      "h6",
      "Nxf7",
      "Kxf7",
      "Qxg4",
      "Qf6",
      "Bc4+",
      "Ke8",
      "Nc3",
      "c6"
    ],
    explanations: [
      "White claims the center.",
      "Black meets us halfway.",
      "The King's Gambit! We're here for a fight, not a long endgame.",
      "Accepted. Black thinks the pawn is worth the risk.",
      "The Golden Rule: stop the queen check and prepare the attack.",
      "Black holds the pawn, but their kingside is starting to look like Swiss cheese.",
      "Undermine! We force Black to make a decision.",
      "Black chases the knight, but they're walking into a trap.",
      "The Morphy move! We land on a provocative square, inviting Black to attack us.",
      "Black takes the bait! They think they're winning a piece.",
      "The Allgaier Sacrifice! We give up the knight to drag Black's king onto the {{square f7}} square where he has no shelter.",
      "Black accepts the material, but their king is now a target for our entire army.",
      "Recapture with the queen. We've regained one pawn and opened the path for our bishops.",
      "Black tries to defend, but their position is crumbling.",
      "Check! The bishop enters the game with a vengeance, targeting the exposed king.",
      "The king is forced to retreat, losing even more time.",
      "Bring in more attackers! We develop the knight and prepare to jump into the center.",
      "Black tries to stop our knight, but they're playing defense while we're playing for checkmate. This is the King's Gambit!"
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-24-f1a6c9e4",
    name: "Declined trap: ...Nd4 runs into Bxf7+",
    description: "Black tries to be solid and use a pin, but White ignores the material and goes straight for the throat with a classic f7 sacrifice.",
    moves: [
      "e4",
      "e5",
      "f4",
      "Nc6",
      "Nf3",
      "d6",
      "Bc4",
      "Bg4",
      "O-O",
      "Nd4",
      "Bxf7+",
      "Kxf7",
      "Ng5+",
      "Qxg5",
      "fxg5+"
    ],
    explanations: [
      "The starting move.",
      "Symmetrical response.",
      "The King's Gambit! We're challenging the center immediately.",
      "Declined. Black develops a knight to keep the position solid.",
      "Develop and attack! We pressure {{square e5}} and guard the {{square h4}} square.",
      "Black reinforces the center, creating a very compact structure.",
      "Develop the bishop! It's already laser-focused on the weakest square: {{square f7}}.",
      "Black pins our knight, thinking they've neutralized our attack.",
      "Castle anyway! We don't fear the pin because our rook is now active on the open f-file.",
      "The mistake! Black thinks they're winning material by adding pressure to our pinned knight.",
      "Sacrifice! We ignore the knight and rip open the king's defenses. The {{square f7}} square is the target!",
      "Forced. Black has to take, but now their king is a sitting duck.",
      "Counter-attack! We jump in with the knight, attacking the king and the loose bishop on {{square g4}}.",
      "Black thinks they've won a piece and stopped the attack.",
      "The Discovery! We take back with the f-pawn, opening our rook's 'highway' with a discovered check. Black's queen is gone and the king is mate. Romantic chess at its finest!"
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-25-6b8e2f11",
    name: "Bishop's Gambit: Kf1 and quiet development",
    description: "In the Bishop's Gambit, we invite Black to check us on h4. We move the king to f1, but we gain a massive lead in development and control of the center.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Bc4",
      "Qh4+",
      "Kf1",
      "Bc5",
      "d4",
      "Bb6",
      "Nf3",
      "Qe7",
      "Nc3",
      "Nf6",
      "Qd3"
    ],
    explanations: [
      "The attack starts.",
      "Black mirrors.",
      "The King's Gambit! We're ready for an open game.",
      "Accepted. Black takes the pawn and the challenge.",
      "The Bishop's Gambit! We develop the bishop first, targeting {{square f7}} and leaving the knight flexible.",
      "Black jumps out with the check, thinking they've won the right to castle.",
      "The key move: K{{square f1}}! We don't mind losing castling rights because our king is safe behind our pawns, and Black's queen is now a target for our development.",
      "Black tries to attack our weak spot, but we're ready.",
      "Boom! We hit the bishop and take full control of the center in one move.",
      "Black is forced to retreat, losing time while we gain space.",
      "Develop with tempo! We hit the queen and prepare to win our pawn back.",
      "Black's queen has to run away. She's already losing the battle of the clocks.",
      "Bring out the reserves! We develop the knight and defend our center.",
      "Black tries to catch up in development, but they're already behind.",
      "Solidify! We protect our center and prepare to launch the final attack. White is clearly better here!"
    ]
  },
  {
    category: "King's Gambit",
    id: "kingsGambit-26-5d3a7c90",
    name: "Bishop's Gambit: Bxf7+ and trapped queen idea",
    description: "Black gets greedy and tries to hold the pawn with their queen, leading to a classic trap where White sacrifices a bishop to net the queen.",
    moves: [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Bc4",
      "Qh4+",
      "Kf1",
      "Bc5",
      "d4",
      "Bb6",
      "Nf3",
      "Qg4",
      "Bxf7+",
      "Kf8",
      "h3",
      "Qg3",
      "Nc3"
    ],
    explanations: [
      "Starting moves.",
      "Black meets us.",
      "The Gambit offer.",
      "Accepted. Let the games begin!",
      "The Bishop's Gambit setup.",
      "The common check.",
      "Step to {{square f1}}. We're completely safe.",
      "Black tries to scholar-mate us, but it's too late for that.",
      "Central dominance! We hit the bishop and gain space.",
      "Retreat. White is already winning the development race.",
      "Develop with tempo! We kick the queen.",
      "Greed! Black tries to hold onto the extra pawn with their queen instead of developing. This is a fatal mistake.",
      "The Sacrifice! We rip open the king's position. Black can't take the bishop because of a discovered check on their queen!",
      "The king is forced to move, losing all coordination.",
      "Trapping time! We restrict the queen's squares even further.",
      "The queen is almost out of breath. She's stuck in a cage of our pieces.",
      "Ignore the bishop and continue the real plan! We're about to play Ne2 and the queen will have nowhere left to go. A masterpiece of coordination!"
    ]
  }
]);
