export const kingsIndianDefenseLines = [
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-01",
    "name": "Classic Exchange Sacrifice Line",
    "description": "White accepts bishop exchange, Black launches counterplay with knight maneuvers",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Bd3", "Bg4", "h3", "Bxf3", "Qxf3", "Nc6", "Be3", "Nd7", "Ne2", "Nde5", "dxe5", "Nxe5", "Qg3", "Nxd3+", "Kd2", "Nxb2"],
    "explanations": [
      "White establishes central control with the classic d4 opening.",
      "Black develops the knight to its most natural square, attacking the center.",
      "White expands on the queenside, supporting the d4 pawn and preparing for further development.",
      "The characteristic King's Indian move, preparing to fianchetto the bishop.",
      "White develops the knight to support the e4 pawn and control central squares.",
      "Black completes the fianchetto, placing the bishop on the powerful long diagonal.",
      "White builds a strong classical pawn center with pawns on d4 and e4.",
      "Black supports the potential e5 break and solidifies the pawn structure.",
      "White continues development, controlling central squares and preparing to castle.",
      "Black castles early, securing the king and connecting the rooks.",
      "White develops the bishop to an active diagonal, supporting the e4 pawn.",
      "Black pins the knight to the queen, typical King's Indian pressure on White's center.",
      "White challenges the bishop, forcing it to make a decision.",
      "Black exchanges bishop for knight, giving White doubled pawns but removing a key defender.",
      "White recaptures with the queen, maintaining central control but exposing the queen.",
      "Black develops the knight with tempo, attacking the d4 pawn.",
      "White develops the bishop to defend d4 and control central dark squares.",
      "Black reroutes the knight, preparing to challenge White's center.",
      "White retreats the knight to defend d4 and avoid potential forks.",
      "Black occupies a strong central outpost, attacking both c4 and d3.",
      "White captures to eliminate Black's strong knight but opens the d-file.",
      "Black recaptures with the knight, maintaining a powerful central presence.",
      "White moves the queen to the kingside, targeting g7 and preparing attacks.",
      "Black captures the bishop with check, disrupting White's coordination.",
      "White moves the king to safety but becomes exposed in the center.",
      "Black captures the pawn, winning material with tempo on the rook."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-02",
    "name": "Classical Variation with e5 break",
    "description": "Typical central tension with early e5 challenge",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "exd4", "Nxd4", "Re8", "f3", "c6", "Be3", "d5", "cxd5", "Nxd5", "Bf2", "Nf4", "Bc4", "Qg5", "Bg3", "Qc5"],
    "explanations": [
      "White establishes central control with the queen's pawn opening.",
      "Black develops the knight to its natural square, attacking central squares.",
      "White expands on the queenside, supporting d4 and gaining space.",
      "Black prepares the King's Indian formation with the fianchetto.",
      "White develops the knight to support the e4 advance.",
      "Black completes the fianchetto, placing the bishop on the critical diagonal.",
      "White establishes the classical pawn center with d4 and e4.",
      "Black supports the e5 break, typical King's Indian structure.",
      "White develops the knight, preparing kingside castling.",
      "Black castles early, preparing counterplay.",
      "White develops the bishop quietly, preparing to castle kingside.",
      "Black executes the central break, challenging White's center immediately.",
      "White castles to safety before the tension escalates.",
      "Black resolves the central tension in their favor.",
      "White recaptures with the knight, controlling central squares.",
      "Black's rook occupies the half-open e-file, putting pressure on e4.",
      "White strengthens the e4 pawn but weakens kingside dark squares.",
      "Black prepares the d5 advance, challenging White's center further.",
      "White develops the bishop to defend d4 and control dark squares.",
      "Black breaks in the center, opening the game for their pieces.",
      "White captures to relieve pressure but gives up the center.",
      "Black recaptures with the knight, occupying a strong central square.",
      "White retreats the bishop, avoiding exchange but becoming passive.",
      "Black's knight jumps to an aggressive outpost, attacking g2 and e2.",
      "White develops the bishop with tempo, attacking f7.",
      "Black's queen enters the game with a double attack on g2 and c5.",
      "White's bishop blocks the queen's attack on g2.",
      "Black's queen retreats to a safe square with an attack on the bishop."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-03",
    "name": "Four Pawns Attack with b5 gambit",
    "description": "Aggressive Four Pawns Attack met with Benko-style gambit",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "Bd3", "exd5", "cxd5", "b5", "Nxb5", "Re8", "Nc3", "Nxe4", "Nxe4", "f5"],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight, preparing the King's Indian setup.",
      "White expands on the queenside, supporting d4 and fighting for space.",
      "Black prepares the King's Indian formation with the fianchetto.",
      "White develops the knight to support the e4 advance.",
      "Black completes the fianchetto, controlling the long diagonal.",
      "White builds a massive pawn center with d4, e4, and f4.",
      "Black supports the e5 break and stabilizes the center.",
      "White begins the aggressive Four Pawns Attack.",
      "Black castles into the storm, preparing a counterattack.",
      "White develops the knight, supporting the center.",
      "Black counterattacks White's center from the queenside.",
      "White advances to gain space, typical in the Four Pawns Attack.",
      "Black immediately challenges the advanced d5 pawn.",
      "White develops the bishop to an active diagonal.",
      "Black captures to open the e-file for their rook.",
      "White recaptures, maintaining the pawn chain but opening the c-file.",
      "Black sacrifices a pawn Benko-style for queenside initiative.",
      "White accepts the gambit, winning a pawn but delaying development.",
      "Black's rook occupies the e-file, putting pressure on e4.",
      "White returns the knight to a development square.",
      "Black executes a tactical shot, capturing the central pawn.",
      "White is forced to recapture.",
      "Black attacks the knight with the pawn, gaining tempo and space."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-04",
    "name": "Exchange Variation with queen trade",
    "description": "Early queen exchange leads to simplified endgame-type position",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "dxe5", "dxe5", "Qxd8", "Rxd8", "Nxe5", "Nxe4", "Nxf7", "Bxc3+", "bxc3", "Kxf7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight to its natural square.",
      "White expands on the queenside, supporting d4 and gaining space.",
      "Black prepares the King's Indian formation.",
      "White develops the knight, supporting e4.",
      "Black completes the fianchetto development.",
      "White establishes the classical center.",
      "Black supports the e5 break.",
      "White continues natural knight development.",
      "Black castles early.",
      "White develops the bishop quietly, preparing to castle.",
      "Black executes the central break, challenging White's center.",
      "White captures to resolve the tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying the position.",
      "Black recaptures with the rook, now controlling the d-file.",
      "White's knight captures the central pawn, winning material.",
      "Black counterattacks, capturing with tempo on the knight.",
      "White sacrifices the knight, attacking the rook and king.",
      "Black's bishop captures with check, winning the knight back.",
      "White is forced to recapture, damaging the pawn structure.",
      "Black's king captures the knight, resulting in roughly equal material."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-05",
    "name": "Four Pawns Attack with early e5",
    "description": "Aggressive pawn push leads to tactical complications",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "e5", "dxe5", "fxe5", "Nfd7", "Nf3", "c5", "Be3", "cxd4", "Bxd4", "Nc6", "Be2", "Nxd4", "Qxd4", "Nxe5", "Qxd8", "Rxd8", "Nxe5", "Bxe5"],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight to an active square.",
      "White expands on the queenside, Queen's Gambit style.",
      "Black prepares the King's Indian signature move.",
      "White develops the knight to support e4.",
      "Black completes the fianchetto development.",
      "White builds a classical center.",
      "Black supports the e5 break.",
      "White begins the extremely aggressive Four Pawns Attack.",
      "Black castles into White's attack.",
      "White immediately pushes the central pawn, gaining space.",
      "Black captures to challenge White's center.",
      "White recaptures, opening the f-file.",
      "Black's knight retreats to challenge the e5 pawn.",
      "White develops the knight, supporting the center.",
      "Black counterattacks White's center.",
      "White develops the bishop to defend d4.",
      "Black captures to open the c-file.",
      "White recaptures with the bishop, controlling the center.",
      "Black develops the knight with an attack on the bishop.",
      "White's bishop retreats to safety.",
      "Black captures the bishop, simplifying.",
      "White recaptures with the queen.",
      "Black's knight captures the central pawn.",
      "White trades queens, simplifying to an endgame.",
      "Black recaptures with the rook.",
      "White's knight captures the knight.",
      "Black's bishop recaptures, completing the simplification."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-06",
    "name": "Classical Variation with Nh3+ tactic",
    "description": "Knight check leads to discovered attack opportunities",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "exd4", "Nxd4", "Re8", "f3", "c6", "Be3", "d5", "cxd5", "Nxd5", "Bf2", "Nf4", "Bc4", "Qg5", "g3", "Nh3+"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight to an active square.",
      "White expands on the queenside, supporting d4.",
      "Black prepares the fianchetto.",
      "White develops the knight, supporting the center.",
      "Black completes the fianchetto development.",
      "White builds a classical center.",
      "Black prepares the central break.",
      "White develops the knight, preparing to castle.",
      "Black castles early.",
      "White challenges Black's central pawn.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White develops the bishop to defend the center.",
      "Black breaks in the center, equalizing space.",
      "White captures to relieve tension.",
      "Black recaptures with the knight.",
      "White retreats the bishop from attack.",
      "Black's knight jumps to an aggressive square.",
      "White develops the bishop with an attack on f7.",
      "Black's queen attacks with a double threat.",
      "White blocks the queen's attack with a pawn.",
      "Black's knight delivers a check with discovered attack on the queen."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-07",
    "name": "Four Pawns Attack with queenside expansion",
    "description": "White pushes pawns aggressively, Black counters with Re8",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "Bd3", "exd5", "cxd5", "b5", "O-O", "c4", "Bc2", "b4", "Ne2", "Re8"],
    "explanations": [
      "White establishes central control with the standard opening move.",
      "Black develops the knight to its natural square.",
      "White expands on the queenside.",
      "Black prepares the King's Indian formation.",
      "White develops the knight to support e4.",
      "Black completes the fianchetto.",
      "White builds a massive center.",
      "Black supports the e5 break.",
      "White begins the Four Pawns Attack.",
      "Black castles kingside.",
      "White develops the knight.",
      "Black challenges White's center.",
      "White advances to gain space.",
      "Black challenges the d5 pawn.",
      "White develops the bishop to an active diagonal.",
      "Black captures to open the e-file.",
      "White recaptures, maintaining structure.",
      "Black sacrifices a pawn Benko-style.",
      "White castles to safety.",
      "Black advances the pawn to cramp White's bishop.",
      "White's bishop retreats.",
      "Black advances the pawn, attacking the knight.",
      "White's knight retreats to avoid capture.",
      "Black's rook occupies the half-open file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-08",
    "name": "Sämisch Variation with Bh6 exchange",
    "description": "White plays f3 and Bh6, forcing bishop exchange",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "d5", "e6", "Qd2", "exd5", "cxd5", "a6", "Bh6", "Nxe4", "Nxe4", "Qh4+", "g3", "Qxh6", "Qxh6", "Bxh6", "Nxd6", "Nd7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation, preparing Be3 and Qd2.",
      "Black castles early.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White advances to gain space.",
      "Black opens the position.",
      "White's queen develops to support Bh6.",
      "Black captures to open the center.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White's bishop attacks Black's strong bishop.",
      "Black executes a tactical shot, capturing the central pawn.",
      "White is forced to recapture.",
      "Black's queen checks, attacking the h6 bishop.",
      "White blocks the check with a pawn.",
      "Black's queen captures the bishop.",
      "White's queen recaptures.",
      "Black's bishop recaptures the queen.",
      "White's knight captures a pawn, winning material.",
      "Black's knight develops, attacking White's knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-09",
    "name": "Four Pawns Attack with Qa5+ tactic",
    "description": "Queen check leads to material gain for Black",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "Bd3", "exd5", "cxd5", "b5", "Bxb5", "Nxe4", "Nxe4", "Qa5+", "Nc3", "Bxc3+", "bxc3", "Qxb5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black plays a Benko-style gambit.",
      "White's bishop captures the pawn.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's queen checks with discovered attack on the knight.",
      "White's knight blocks the check.",
      "Black's bishop captures with check.",
      "White's pawn recaptures.",
      "Black's queen captures the bishop."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-10",
    "name": "Sämisch Variation with Bh6 and b4",
    "description": "Early Bh6 followed by queenside expansion",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "d5", "e6", "Qd2", "exd5", "cxd5", "a6", "O-O-O", "b5", "Bh6", "b4"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White castles queenside, an aggressive choice.",
      "Black expands on the queenside.",
      "White attacks Black's strong bishop.",
      "Black advances the pawn, attacking the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-11",
    "name": "Sämisch Variation with Re8 pressure",
    "description": "Black develops rook to e-file for central pressure",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "d5", "e6", "Qd2", "exd5", "exd5", "Re8"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures with the e-pawn, maintaining the center.",
      "Black's rook occupies the e-file, pressuring e4."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-12",
    "name": "Four Pawns Attack with early d5 advance",
    "description": "White pushes d5 immediately after Black's c5",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "e5", "dxe5", "fxe5", "Nfd7", "Nf3", "c5", "d5", "Nxe5", "Nxe5", "Bxe5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White immediately pushes the pawn.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's knight retreats.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn aggressively.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-13",
    "name": "Be3 Variation with early c5",
    "description": "White develops Be3 early, Black responds with c5",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Be2", "O-O", "Be3", "c5", "dxc5", "Qa5", "cxd6", "Nxe4", "dxe7", "Re8"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing kingside castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black's queen attacks with tempo.",
      "White's pawn captures, opening the position.",
      "Black's knight captures the central pawn.",
      "White's pawn promotes to a passed pawn.",
      "Black's rook attacks the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-14",
    "name": "Sämisch Variation with queen trade",
    "description": "Early queen exchange leads to simplified middlegame",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "dxc5", "dxc5", "Qxd8", "Rxd8", "Bxc5", "Nc6", "Rd1", "Rxd1+", "Kxd1", "Nd7", "Ba3", "Bxc3", "bxc3", "Nde5", "f4", "Ng4", "Ke2", "Be6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens, simplifying the position.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops with tempo.",
      "White's rook develops to the open file.",
      "Black trades rooks.",
      "White's king recaptures.",
      "Black's knight develops, attacking the bishop.",
      "White's bishop retreats.",
      "Black's bishop captures the knight.",
      "White's pawn recaptures.",
      "Black's knight moves to a central outpost.",
      "White's pawn attacks the knight.",
      "Black's knight retreats to an active square.",
      "White's king moves to safety.",
      "Black's bishop develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-15",
    "name": "Sämisch Variation with Nde5",
    "description": "Similar to previous line but with different knight maneuver",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "dxc5", "dxc5", "Qxd8", "Rxd8", "Bxc5", "Nc6", "Rd1", "Rxd1+", "Kxd1", "Nd7", "Be3", "Bxc3", "bxc3", "Nde5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's rook develops.",
      "Black trades rooks.",
      "White's king recaptures.",
      "Black's knight develops.",
      "White's bishop retreats.",
      "Black's bishop captures the knight.",
      "White's pawn recaptures.",
      "Black's knight moves to a strong central square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-16",
    "name": "Four Pawns Attack with Bf5 development",
    "description": "Black develops bishop to f5, challenging White's center",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "Be2", "exd5", "exd5", "Bf5", "O-O", "Ne4", "Nxe4", "Bxe4", "Bd3", "Bxf3", "Qxf3", "Nd7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures with the e-pawn.",
      "Black develops the bishop actively.",
      "White castles to safety.",
      "Black's knight occupies a central outpost.",
      "White's knight captures the knight.",
      "Black's bishop recaptures.",
      "White's bishop develops, attacking the bishop.",
      "Black's bishop captures the knight.",
      "White's queen recaptures.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-17",
    "name": "Sämisch Variation with b6 and Ba6",
    "description": "Black plays b6 and Ba6 for queenside pressure",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "dxc5", "dxc5", "Qxd8", "Rxd8", "Bxc5", "Nc6", "Nge2", "b6", "Ba3", "Ba6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White trades queens.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight develops to avoid the pin.",
      "Black's pawn attacks the bishop.",
      "White's bishop retreats.",
      "Black's bishop develops to pin the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-18",
    "name": "Sämisch Variation with Qa5 and Nge2",
    "description": "White plays Nge2 to avoid queen pin on c3",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "Nge2", "Qa5", "Qd2", "Nc6", "O-O-O", "b6", "Kb1", "Ba6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White's knight develops to avoid future pins.",
      "Black's queen attacks with tempo.",
      "White's queen develops to support Bh6.",
      "Black's knight develops.",
      "White castles queenside, an aggressive choice.",
      "Black prepares Ba6.",
      "White's king moves to safety.",
      "Black's bishop develops to pin the knight."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-19",
    "name": "Classical Variation with a5 and Na6",
    "description": "Black plays a5 and Na6 for queenside play",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "d5", "a5", "O-O", "Na6", "a3", "Nc5", "Qc2", "a4", "Be3", "Nb3"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White advances the pawn.",
      "Black expands on the queenside.",
      "White castles to safety.",
      "Black's knight develops to the edge.",
      "White prevents Nb4.",
      "Black's knight moves to an active square.",
      "White's queen develops to support d3.",
      "Black advances the pawn further.",
      "White develops the bishop.",
      "Black's knight attacks the rook and c1 square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-20",
    "name": "Averbakh Variation with Bg5",
    "description": "White develops Bg5 early, pinning knight",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Be2", "O-O", "Bg5", "c5", "d5", "e6", "Qd2", "exd5", "exd5", "Qb6", "Nf3", "Bf5", "O-O", "Ne4", "Nxe4", "Bxe4"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop.",
      "Black castles.",
      "White's bishop pins the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's queen attacks b2 and d6.",
      "White develops the knight.",
      "Black's bishop develops actively.",
      "White castles to safety.",
      "Black's knight occupies a central outpost.",
      "White's knight captures the knight.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-21",
    "name": "Exchange Variation with Bg5",
    "description": "Early queen exchange followed by bishop pin",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "dxe5", "dxe5", "Qxd8", "Rxd8", "Bg5", "Be6", "Nxe5", "h6", "Bh4", "g5", "Bg3", "Na6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White captures to resolve tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White develops the bishop, pinning the knight.",
      "Black's bishop develops to a good square.",
      "White's knight captures the central pawn.",
      "Black attacks the bishop with the pawn.",
      "White retreats the bishop.",
      "Black attacks the bishop again, gaining space.",
      "White retreats the bishop to safety.",
      "Black's knight develops to the edge."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-22",
    "name": "Exchange Variation with Nxe4",
    "description": "Early knight exchange after queen trade",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "dxe5", "dxe5", "Qxd8", "Rxd8", "Nxe5", "Nxe4", "Nxe4", "Bxe5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White captures to resolve tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's knight captures the central pawn.",
      "Black's knight captures the central pawn.",
      "White's knight recaptures.",
      "Black's bishop recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-23",
    "name": "Classical Variation with knight exchange",
    "description": "Early knight exchange in the center",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "exd4", "Nxd4", "Re8", "f3", "c6", "Be3", "d5", "cxd5", "Nxd5", "Nxd5", "cxd5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White develops the bishop.",
      "Black breaks in the center.",
      "White captures to relieve tension.",
      "Black recaptures with the knight.",
      "White exchanges knights.",
      "Black recaptures with the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-24",
    "name": "Sämisch Variation with Nd5",
    "description": "White plays Nd5 with tactical complications",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "dxc5", "dxc5", "Qxd8", "Rxd8", "Bxc5", "Nc6", "Nd5", "Nd7", "Nxe7+", "Nxe7", "Bxe7", "Bxb2"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight moves to a strong central square.",
      "Black's knight develops.",
      "White's knight checks, winning a pawn.",
      "Black's knight recaptures.",
      "White's bishop captures the knight.",
      "Black's bishop captures the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-25",
    "name": "Sämisch Variation with a4",
    "description": "White plays a4 to prevent Black's queenside expansion",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "d5", "e6", "Qd2", "exd5", "cxd5", "a6", "a4", "Qa5", "Bd3", "b5", "Nge2", "b4", "Nd1", "Nbd7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White prevents Black's queenside expansion.",
      "Black's queen attacks with tempo.",
      "White develops the bishop.",
      "Black expands on the queenside.",
      "White's knight develops to avoid pins.",
      "Black advances the pawn, attacking the knight.",
      "White's knight retreats to safety.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-26",
    "name": "Four Pawns Attack with dxe6",
    "description": "White captures on e6 early, opening the position",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "dxe6", "fxe6", "Bd3", "Nc6", "O-O", "Nd4", "Nxd4", "cxd4", "Nb5", "e5", "fxe5", "dxe5", "c5", "Be6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White captures, opening the position.",
      "Black recaptures with the f-pawn.",
      "White develops the bishop.",
      "Black's knight develops.",
      "White castles to safety.",
      "Black's knight occupies a strong square.",
      "White exchanges knights.",
      "Black recaptures with the pawn.",
      "White's knight jumps forward.",
      "Black advances the pawn.",
      "White captures the pawn.",
      "Black recaptures.",
      "White advances the pawn.",
      "Black's bishop develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-27",
    "name": "Be3 Variation with f3",
    "description": "White plays Be3 followed by f3",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Be2", "O-O", "Be3", "c5", "dxc5", "Qa5", "f3", "dxc5"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black's queen attacks with tempo.",
      "White strengthens the center but weakens dark squares.",
      "Black recaptures."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-28",
    "name": "Classical Variation with Bg5 and h6",
    "description": "White plays Bg5, Black responds with h6",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "d5", "a5", "Bg5", "h6", "Bh4", "Na6", "Nd2", "Qe8", "O-O", "Nh7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White advances the pawn.",
      "Black expands on the queenside.",
      "White's bishop pins the knight.",
      "Black attacks the bishop.",
      "White retreats the bishop.",
      "Black's knight develops to the edge.",
      "White's knight retreats to support the center.",
      "Black's queen prepares to reposition.",
      "White castles to safety.",
      "Black's knight retreats to a defensive square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-29",
    "name": "Sämisch Variation with Nxe7+",
    "description": "Tactical complications with knight check",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "dxc5", "dxc5", "Qxd8", "Rxd8", "Bxc5", "Nc6", "Nd5", "Nd7", "Bxe7", "Nxe7", "Nxe7+", "Kf8", "Nd5", "Bxb2"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White captures the pawn.",
      "Black recaptures.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's bishop captures the pawn.",
      "Black's knight develops.",
      "White's knight moves to a strong central square.",
      "Black's knight develops.",
      "White's bishop captures the knight.",
      "Black's knight recaptures.",
      "White's knight checks.",
      "Black's king moves to safety.",
      "White's knight moves to a strong square.",
      "Black's bishop captures the pawn."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-30",
    "name": "Sämisch Variation with Ra3",
    "description": "White develops rook to a3 for queenside defense",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "O-O", "Be3", "c5", "d5", "e6", "Qd2", "exd5", "cxd5", "a6", "a4", "Qa5", "Ra3", "Nbd7"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White plays the Sämisch Variation.",
      "Black castles.",
      "White develops the bishop.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White's queen develops.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black prevents Nb5.",
      "White prevents Black's queenside expansion.",
      "Black's queen attacks with tempo.",
      "White develops the rook to an unusual square for defense.",
      "Black's knight develops."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-31",
    "name": "Four Pawns Attack with Bg4 exchange",
    "description": "Black develops Bg4, leading to bishop exchange",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4", "O-O", "Nf3", "c5", "d5", "e6", "Be2", "exd5", "cxd5", "Bg4", "O-O", "Nbd7", "h3", "Bxf3", "Bxf3", "Re8"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White begins the Four Pawns Attack.",
      "Black castles.",
      "White develops the knight.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black challenges d5.",
      "White develops the bishop.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black develops the bishop actively.",
      "White castles to safety.",
      "Black's knight develops.",
      "White attacks the bishop.",
      "Black exchanges bishop for knight.",
      "White recaptures with the bishop.",
      "Black's rook occupies the e-file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-32",
    "name": "Classical Variation with Kh1",
    "description": "White plays Kh1 early, preparing kingside play",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "exd4", "Nxd4", "Re8", "f3", "c6", "Kh1", "Nbd7", "Bf4", "Nh5", "Bxd6", "Qf6", "Nb3", "Nf4"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White moves the king to safety, preparing kingside play.",
      "Black's knight develops.",
      "White develops the bishop actively.",
      "Black's knight attacks the bishop.",
      "White's bishop captures the pawn.",
      "Black's queen attacks the bishop.",
      "White's knight retreats.",
      "Black's knight moves to an aggressive square."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-33",
    "name": "Be3 Variation with Nf3",
    "description": "White develops Be3 and Nf3",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Be2", "O-O", "Be3", "c5", "d5", "e6", "Nf3", "exd5", "cxd5", "Re8"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the bishop, preparing castling.",
      "Black castles.",
      "White develops the bishop to control dark squares.",
      "Black challenges the center.",
      "White advances the pawn.",
      "Black opens the position.",
      "White develops the knight.",
      "Black captures the pawn.",
      "White recaptures.",
      "Black's rook occupies the e-file."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-34",
    "name": "Classical Variation with Bg5 and h6",
    "description": "White plays Bg5, Black responds with h6",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "exd4", "Nxd4", "Re8", "f3", "c6", "Kh1", "Nbd7", "Bg5", "h6"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures with the knight.",
      "Black's rook occupies the e-file.",
      "White supports e4 but weakens the kingside.",
      "Black prepares the d5 push.",
      "White moves the king to safety.",
      "Black's knight develops.",
      "White develops the bishop, pinning the knight.",
      "Black attacks the bishop."
    ]
  },
  {
    "category": "King's Indian Defense",
    "id": "kings-indian-35",
    "name": "Exchange Variation with Nd5",
    "description": "White plays Nd5 after queen exchange",
    "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "dxe5", "dxe5", "Qxd8", "Rxd8", "Nd5", "Rd7", "Nxe5", "Nxd5", "Nxd7", "Nb4", "Nxb8", "Nc2+", "Kd1", "Nxa1", "Bf4", "Rxb8"],
    "explanations": [
      "White establishes central control with the standard opening.",
      "Black develops the knight.",
      "White expands on the queenside.",
      "Black prepares the fianchetto.",
      "White develops the knight.",
      "Black completes the fianchetto.",
      "White builds the center.",
      "Black supports e5.",
      "White develops the knight.",
      "Black castles.",
      "White develops the bishop.",
      "Black executes the central break.",
      "White captures to resolve tension.",
      "Black recaptures, opening the d-file.",
      "White exchanges queens, simplifying.",
      "Black's rook recaptures.",
      "White's knight moves to a strong central square.",
      "Black's rook moves to defend.",
      "White's knight captures the central pawn.",
      "Black's knight captures the knight.",
      "White's knight captures the rook.",
      "Black's knight moves with a fork threat.",
      "White's knight captures the knight.",
      "Black's knight forks king and rook.",
      "White's king moves to safety.",
      "Black's knight captures the rook.",
      "White's bishop develops.",
      "Black's rook captures the knight."
    ]
  }
];