import { withOpeningFeedback } from "./feedback";

export const petrovDefenseSEOText = `
The Petrov Defense starts with 1. e4 e5 2. Nf3 Nf6 and fights for the initiative immediately instead of passively defending e5.

These drills cover the two practical branches already living in this file:
- Standard Petrov positions with ...d6, ...Nxe4, central tension, and tactical resources built around pins on the e-file and pressure on d4
- Petrov Damiano Variation / Kholmov Gambit structures with 3. Nxe5 Nxe4, where Black uses the e-file pin, fast development, and counterattacking ideas like ...Qg5, ...Bg4, ...O-O-O, and direct king pressure

Each line explains the concrete point of the move: what is pinned, what is attacked, what tactical resource makes the line work, and when Black should prefer activity over material grabbing.
`;

export const petrovDefenseLines = withOpeningFeedback([
  {
    category: "Petrov Defense",
    id: "petrovDefense-01-895113e8",
    name: "Kholmov Gambit: 6.Bb5+ simplification",
    description: "Mirror the queen trick, then simplify with ...c6 and ...Nxc6 before winning the knight back.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "Bb5+",
      "c6",
      "Bxc6+",
      "Nxc6",
      "O-O",
      "dxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Let's learn the Petrov Defense! This opening will take white completely by surprise. We start by playing pawn to e5.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black to prove the knight on f6 was not a bluff.",
      "Black copies White and takes on e4, entering the Damiano or Kholmov territory where tactics matter more than dogma.",
      "White goes for the familiar e-file trick, attacking the knight and hoping a retreat loses Black's queen to Nc6+.",
      "Black mirrors the queen instead of retreating. The knight on e4 stays put and White's trap no longer works.",
      "White removes the advanced knight, but Black has already reached the position he wanted.",
      "Black hits the e5 knight while it is still tied to the e-file. The point is to win that knight back with tempo.",
      "White checks first, trying to squeeze one more useful move out of the position before the knight disappears.",
      "Black blocks the check, attacks the bishop, and keeps the plan of regaining the e5 knight under control.",
      "White gives up the bishop pair to drag a knight onto c6 and reduce some central pressure.",
      "Black recaptures, develops a piece, and keeps the extra activity.",
      "White gets the king safe before the center opens further.",
      "Black finally wins the pinned knight back and reaches material balance with a comfortable game."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-02-65e4b94b",
    name: "Kholmov Gambit: bishop chase with ...g5 and ...f5",
    description: "Transcript-backed trap using the e-file pin, a bishop chase, and long castling for activity.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qa4",
      "f4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black to prove the opening is sound.",
      "Black takes on e4 and invites the known queen trick.",
      "White chooses the forcing queen move, trying to pin the e4 knight to the queen.",
      "Black answers in kind. The knight does not retreat, and the e5 knight is the one that becomes awkward.",
      "White cashes in on e4, but the fight is only starting.",
      "Black attacks the e5 knight while the e-file pin limits White's options.",
      "White builds a center to keep the e5 pawn alive a little longer.",
      "Black removes the support behind that advanced pawn. This is the whole point of Black's move order.",
      "White keeps the pawn for the moment and opens lines.",
      "Black develops with tempo and hits e5 again.",
      "White uses a pin to slow down ...Nxe5 and squeeze out development.",
      "Black breaks the pin and prepares to castle long if the position stays sharp.",
      "White castles and hopes the extra space will matter.",
      "Black castles queenside because activity matters more than symmetry in this line.",
      "White develops naturally and overprotects e5.",
      "Black chases the bishop first. The bishop on f4 is a tactical target, not a proud piece here.",
      "White retreats, but the bishop now has fewer useful squares.",
      "Black uses the e-file pin again and prepares ...f4 to trap the bishop or regain the pawn.",
      "White looks for a check and tries to keep tactical pressure alive.",
      "Black keeps pushing. The bishop on g3 and the e5 pawn are both under direct fire."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-03-e3b56bbc",
    name: "Kholmov Gambit: trapped bishop after ...f4",
    description: "If White retreats the queen instead of solving the bishop problem, Black keeps pushing and tears open the kingside.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qe2",
      "f4",
      "Qh5+",
      "Qf7",
      "Qxg5",
      "fxg3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black to solve the problem accurately.",
      "Black takes on e4 and invites the queen pin idea.",
      "White goes for Qe2, the standard trap attempt against a careless retreat.",
      "Black mirrors the queen and refuses to blink.",
      "White removes the knight, but the structure now favors Black's next move.",
      "Black attacks the e5 knight while the e-file pin still matters.",
      "White builds a center to keep the extra pawn.",
      "Black strips away that support immediately.",
      "White recaptures and keeps the pawn chain for now.",
      "Black develops and piles more pressure onto e5.",
      "White develops the bishop to support the center, but it is about to become a target.",
      "Black gains time by chasing the bishop instead of hurrying to regain the pawn.",
      "White retreats to g3, the square that later becomes the problem.",
      "Black brings the f-pawn with tempo and keeps exploiting the e-file pin.",
      "White sidesteps with the queen, but this does not solve the bishop issue.",
      "Black keeps pushing because the bishop on g3 has no good future and White's king is still loose.",
      "White throws in a check to muddy the water before the bishop gets trapped.",
      "Black calmly covers the key squares and keeps the attack organized.",
      "White grabs a pawn to justify the queen dance.",
      "Black tears open the kingside and removes the bishop on g3. White's whole setup falls apart from here."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-04-381498b9",
    name: "Kholmov Gambit endgame: ...Nb4 and king walk",
    description: "Queen trade into an active endgame where Black keeps the initiative and hunts loose pawns.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "Bd3",
      "Bxd3",
      "cxd3",
      "Nb4",
      "Kd2",
      "O-O-O",
      "Nc3",
      "Nxd3",
      "Ke3",
      "Bc5+",
      "Kf3",
      "Bxf2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops the bishop to d3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on d3 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on d3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black places the knight on b4 to improve central influence and set up the next tactic or break.",
      "White moves the king to d2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black captures on d3 with the knight, usually removing a key defender or converting initiative into material.",
      "White moves the king to e3, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to f3, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black captures on f2 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-05-4a0deb88",
    name: "Bc4 sideline: ...Qg5 and ...Nxf2",
    description: "White points at f7, but ...d5 and queen activity turn it into a target-rich counterattack for Black.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Bc4",
      "d5",
      "Bb3",
      "Qg5",
      "O-O",
      "Qxe5",
      "d3",
      "Nxf2",
      "Rxf2",
      "Bc5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and hopes Black's development will lag.",
      "Black takes on e4 and accepts a sharp game.",
      "White points at f7 and tries to turn the opening into a direct attack.",
      "Black answers the bishop the Petrov way, by hitting the center and asking it to move again.",
      "White retreats, but that is already another lost tempo.",
      "Black's queen counterattack hits g2 and reminds White that Black has the initiative now.",
      "White castles to avoid some immediate tactics, but the queen on g5 keeps the pressure on.",
      "Black finally takes the e5 knight because the tactics now favor Black.",
      "White tries to build shelter and free the c1 bishop.",
      "Black jumps into f2 to drag the rook away and crack open the kingside.",
      "White has to recapture, but the rook is pulled offside and the king shelter is damaged.",
      "Black brings the bishop into the attack with tempo. The pieces now point straight at White's king."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-06-ead2fb12",
    name: "Bc4 sideline: queen raid on g2",
    description: "Black grabs the g2 pawn and develops with tempo while White struggles to coordinate.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Bc4",
      "d5",
      "Bb3",
      "Qg5",
      "Nf3",
      "Qxg2",
      "Rf1",
      "Bg4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black for precision.",
      "Black takes on e4 and keeps the game tactical.",
      "White points at f7 and hopes development will make the attack work.",
      "Black hits the center first and makes the bishop move again.",
      "White retreats, but Black keeps the initiative.",
      "Black's queen immediately goes after g2 and the loose kingside.",
      "White retreats the knight and hopes the queen raid can be punished later.",
      "Black just takes the pawn because White has no clean refutation.",
      "White tries to trap the queen indirectly and defend f2.",
      "Black develops with tempo, pins a defender, and leaves White tied to the back rank while the queen stays active."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-07-79bde82c",
    name: "Kholmov Gambit endgame: ...Rd5 rook lift",
    description: "After queen trades, Black still keeps the more active pieces and uses the d-file first.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "c3",
      "O-O-O",
      "Bb5",
      "Nxe5",
      "Bxe5",
      "Rd5",
      "Bxg7",
      "Bxg7"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on e5 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to d5 to pressure an open file created by earlier trades.",
      "White captures on g7 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on g7 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-08-951ab479",
    name: "Kholmov Gambit: ...Qc5+ wins the bishop",
    description: "Transcript-backed counterstrike where ...Bg4 and long castling create a direct tactical threat.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "O-O",
      "Qc5+",
      "Be3",
      "Qxb5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and starts the Damiano or Kholmov sequence.",
      "Black takes on e4 and accepts a tactical fight.",
      "White tries the standard queen pin idea.",
      "Black mirrors the queen and keeps the knight on e4.",
      "White removes the knight, but the structure already favors Black's counterplay.",
      "Black attacks the e5 knight and refuses passive defense.",
      "White supports the advanced knight with a center.",
      "Black cuts away that support immediately.",
      "White recaptures and keeps the e5 pawn alive for now.",
      "Black develops and keeps hitting the center.",
      "White chooses the natural f-pawn defense, a move the transcript specifically warns about.",
      "Black develops with tempo, pins the key piece, and prepares long castling.",
      "White adds another pin and thinks the e5 pawn is still secure.",
      "Black castles queenside as a counterstrike. The threats on the d-file are more important than the pinned knight.",
      "White castles to get out of the worst of the tactics.",
      "Black hits with Qc5+, attacking the king and the bishop at the same time.",
      "White blocks, but the bishop on b5 is still loose.",
      "Black simply takes the bishop. The whole sequence works because the pin and long castling gave Black the initiative."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-09-660cff85",
    name: "Kholmov Gambit endgame: ...Bh6 and ...Nxe5",
    description: "Black keeps squeezing the e5 pawn even after the queens come off.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "c3",
      "O-O-O",
      "Be3",
      "g5",
      "g3",
      "gxf4",
      "gxf4",
      "Bh6",
      "Nd2",
      "Nxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops the bishop to h6, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the knight on d2 to improve central influence and set up the next tactic or break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-10-a302b607",
    name: "Kholmov Gambit: mating net after ...Qxe5+",
    description: "The bishop chase turns into a direct king hunt with ...O-O-O, ...Bg4+, and a rook invasion.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qa4",
      "f4",
      "Bb5",
      "Qxe5+",
      "Kd1",
      "Bd7",
      "Re1",
      "O-O-O",
      "Rxe5",
      "Bg4+",
      "Ke1",
      "Rd1#"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and tests Black's move order.",
      "Black takes on e4 and heads for sharp play.",
      "White chooses Qe2, trying to exploit the e-file pin.",
      "Black mirrors and keeps the extra activity.",
      "White removes the advanced knight.",
      "Black attacks the e5 knight immediately. That knight is still Black's main target.",
      "White supports the e5 pawn with a center.",
      "Black removes the support behind it.",
      "White recaptures and keeps the pawn chain for the moment.",
      "Black develops and keeps the pressure coming.",
      "White develops the bishop, but it is about to be chased.",
      "Black gains time and starts the same bishop-chase plan from the transcript.",
      "White retreats to g3, where the bishop can later become trapped.",
      "Black uses the e-file pin again and prepares ...f4 or ...Qxe5+ depending on White's setup.",
      "White looks for a check and tries to keep the initiative alive.",
      "Black keeps the kingside clamped and preserves the attack.",
      "White adds one more pin, but Black can now cash in on the central tactics.",
      "Black takes on e5 with check and drags the king into the open.",
      "White has to step aside.",
      "Black develops, connects the attack, and prepares to castle long.",
      "White tries to contest the e-file before Black's rook arrives.",
      "Black castles long, and now every piece joins the king hunt.",
      "White grabs material, but the king is too exposed for that to matter.",
      "Black checks with tempo and drives the king onto the mating net.",
      "White has only one square.",
      "Rd1 is mate. This is the attacking idea the transcript warns about after Black castles long."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-11-b7a55a21",
    name: "Kholmov Gambit: queen to d5 and long castling",
    description: "White centralizes the queen, but Black still gets the usual kingside and center counterplay.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qd5",
      "f4",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to g3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to f5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White moves the queen to d5 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-12-a2e1d897",
    name: "Kholmov Gambit: ...Nd4 and ...Qh4-h3",
    description: "Long castling plus a knight jump to d4 gives Black an attacking setup that is easy to play.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "Nc3",
      "Nd4",
      "Bd3",
      "Qh4+",
      "g3",
      "Qh3",
      "Be3",
      "Bf3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black for accuracy.",
      "Black takes on e4 and enters the sharp Kholmov structure.",
      "White tries the queen pin.",
      "Black mirrors the queen and keeps the knight on e4.",
      "White removes that knight, but Black already has the right pawn structure.",
      "Black attacks the e5 knight while the e-file pin still helps.",
      "White supports the advanced pawn with d4.",
      "Black removes the support behind it.",
      "White recaptures and hopes the e5 pawn will survive.",
      "Black develops and keeps the pressure on.",
      "White chooses the f-pawn defense.",
      "Black develops with tempo and prepares to castle long.",
      "White adds another pin, but Black does not care about defending the knight passively.",
      "Black castles long as a direct counterattack.",
      "White develops and tries to cover the d-file.",
      "Black jumps into d4 with tempo, hitting c2 and opening more attacking lanes.",
      "White develops the bishop and tries to keep the center together.",
      "Black checks and brings the queen closer to the king.",
      "White is forced to create luft and weaken dark squares.",
      "Black keeps the queen on the h-file and refuses to let the attack cool down.",
      "White finally develops a piece to block lines.",
      "Black plants the bishop on f3, and the attack now plays itself on the light squares."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-13-4917221f",
    name: "Kholmov Gambit: sacrificial attack on h2",
    description: "Once the king is dragged around, Black keeps opening files and piling on checks.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "Bxc6",
      "Rd1+",
      "Kf2",
      "Rxh1",
      "Bxb7+",
      "Kb8",
      "Be3",
      "Qh4+",
      "g3",
      "Rxh2+",
      "Kf1",
      "Bh3+",
      "Ke1",
      "Qxg3+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check to keep the initiative.",
      "White moves the king to f2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black captures on h1 with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black moves the king to b8, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black gives check to keep the initiative.",
      "White moves the king to f1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to e1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-14-0f851c49",
    name: "Kholmov Gambit: Qa4+ sidestep fails",
    description: "Qa4+ looks clever, but the e5 knight is still pinned and Black recovers it anyway.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "Qa4+",
      "Bd7",
      "Qe4",
      "Nc6",
      "d4",
      "dxe5",
      "dxe5",
      "O-O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks Black to prove the immediate capture was sound.",
      "Black takes on e4 and invites the queen-based trap attempt.",
      "White chooses Qe2, still hoping the e-file pin will make Black retreat.",
      "Black mirrors the queen and keeps the position under control.",
      "White removes the knight.",
      "Black attacks the e5 knight right away. That is still the real target.",
      "Qa4+ tries to look clever, but it does not solve the problem because the knight on e5 is still pinned to the king.",
      "Black blocks the check, attacks the queen, and keeps White tied to the pin.",
      "White steps back and keeps contact with the e5 knight.",
      "Black develops and adds more pressure.",
      "White builds a center to support e5 one last time.",
      "Black removes that support.",
      "White recaptures and keeps the pawn for the moment.",
      "Black castles long and keeps the initiative while White still has to solve the central tension."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-15-cdc8e677",
    name: "Kholmov Gambit endgame: ...Nf3+ and ...Bxf4",
    description: "Simplified position where Black uses active pieces to punish White's loose kingside.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Nc3",
      "Qxe5",
      "Qxe5+",
      "Nxe5",
      "Bf4",
      "Bd6",
      "Nb5",
      "Nf3+",
      "gxf3",
      "Bxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to d6, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the knight on b5 to improve central influence and set up the next tactic or break.",
      "Black gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "White captures on f3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on f4 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-16-3b66d7f0",
    name: "Kholmov Gambit endgame: ...f6 break",
    description: "Queenless middlegame where Black undermines the e5 pawn with simple, direct play.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "Bd3",
      "Bxd3",
      "cxd3",
      "Nb4",
      "Kd2",
      "O-O-O",
      "Nc3",
      "f6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops the bishop to d3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on d3 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on d3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black places the knight on b4 to improve central influence and set up the next tactic or break.",
      "White moves the king to d2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to f6 to support a plan; check what weakness it creates and whether it helps development or attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-17-5434f392",
    name: "Qf3 sidestep: active retreat with ...Ng5",
    description: "White avoids Qe2, but Black still has an easy answer and can recover the pawn on schedule.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qf3",
      "Ng5",
      "Qf4",
      "d6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and tries to ask immediate questions.",
      "Black takes on e4 and keeps the game tactical.",
      "Qf3 is a sidestep that hits e4 and also hints at cheap mates on f7 if Black is careless.",
      "Black retreats actively to g5, covering key squares and stopping the nonsense cleanly.",
      "White keeps the queen active and hopes Black still has to solve problems.",
      "Black just plays d6, kicks the knight, and continues the normal recovery plan."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-18-c7454ce4",
    name: "Kholmov Gambit endgame: ...Bb4 pin",
    description: "After the bishop trade on c6, Black develops fast and keeps pressure on the queenside.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "Bxc6",
      "Bxc6",
      "O-O",
      "O-O-O",
      "Nc3",
      "Bb4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black puts Bb4 on the board to check or pin, trying to disrupt development and win a tempo."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-19-47348ed2",
    name: "Qf3 sidestep: queen retreat to e3",
    description: "A quieter queen sidestep that still gives Black an easy setup.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qf3",
      "Ng5",
      "Qe3",
      "Be7"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and asks for accuracy.",
      "Black takes on e4 and enters a tactical side line.",
      "Qf3 again avoids Qe2 and keeps an eye on e4 and f7.",
      "Black's retreat to g5 is still the clean answer.",
      "White backs the queen up to e3 and hopes for a quieter game.",
      "Black develops normally. Once the cheap threats are gone, White has gained nothing from the sidestep."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-20-faa259e3",
    name: "Kholmov Gambit endgame: ...Bc5 stops castling",
    description: "Black finishes development first and uses the c5 bishop to keep White's king awkward.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "c3",
      "O-O-O",
      "Bb5",
      "Bc5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and heads for sharp territory.",
      "Black takes on e4 and accepts the challenge.",
      "White tries the queen pin.",
      "Black mirrors the queen and keeps the knight on e4.",
      "White removes the knight.",
      "Black attacks the e5 knight while it is still the key tactical object.",
      "White supports the extra pawn with d4.",
      "Black removes that support.",
      "White chooses the queen trade line, heading for a queenless middlegame.",
      "Black trades queens and keeps the more active pieces.",
      "White recaptures, but the advanced pawn still needs work.",
      "Black develops and keeps pressure on e5.",
      "White uses the f-pawn to support the center.",
      "Black develops the bishop to a strong square and prepares to bring the king to safety.",
      "White plays c3 to keep the center from collapsing immediately.",
      "Black castles queenside first. Development speed matters more than pawn counting here.",
      "White tries to pin and slow Black down.",
      "Black answers with Bc5, taking over the diagonal and making White's kingside castling unpleasant."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-21-04bf546b",
    name: "Damiano Variation: 4.d3 retreat",
    description: "White chooses a safer structure and Black simply returns the knight to a solid square.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "d3",
      "Nf6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White grabs the e5 pawn and invites a sharp reply.",
      "Black takes on e4 immediately, entering the Damiano Variation.",
      "White chooses the safer d3 setup instead of the queen tricks.",
      "Black simply returns the knight to f6 and reaches a sound Petrov structure without drama."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-22-23a1453d",
    name: "Kholmov Gambit: ...a6 and ...Nxe5",
    description: "Black questions the bishop before recovering the e5 pawn under good conditions.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Nc3",
      "a6",
      "Ba4",
      "Nxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to a6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to a4, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-23-cc081ebf",
    name: "Kholmov Gambit: bishop trade on c6",
    description: "White gives up the bishop pair to reduce pressure, but Black develops smoothly.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Nc3",
      "a6",
      "Bxc6",
      "Bxc6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to a6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on c6 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-24-b5236397",
    name: "Kholmov Gambit endgame: ...Re8 and ...f6",
    description: "Black uses the e-file and the f-pawn break to finish off the advanced e5 pawn.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "c3",
      "O-O-O",
      "Nd2",
      "Nxe5",
      "Bxe5",
      "Re8",
      "f4",
      "f6",
      "Nf3",
      "fxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White places the knight on d2 to improve central influence and set up the next tactic or break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on e5 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to e8 to pressure an open file created by earlier trades.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black pushes a pawn to f6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-25-c0f4d6b9",
    name: "Classical Petrov: ...Bg4 and ...Nxd4",
    description: "Standard Petrov main line from the transcript, where Black uses a pin on f3 to win back d4 with activity.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "d6",
      "Nf3",
      "Nxe4",
      "d4",
      "d5",
      "Bd3",
      "Be7",
      "O-O",
      "Nc6",
      "Re1",
      "Bg4",
      "Bxe4",
      "dxe4",
      "Rxe4",
      "Bxf3",
      "Qxf3",
      "Nxd4"
    ],
    explanations: [
      
      "White claims the center and opens lines for quick development.",
      "Black matches the central stake and keeps the Petrov setup available.",
      "White attacks e5 and develops normally.",
      "Black counters White's center immediately instead of passively defending e5.",
      "White takes the pawn and tests the Petrov directly.",
      "Black does not copy on e4 here. The standard Petrov rule is to kick the knight first and only then recover material.",
      "White retreats to safety and keeps normal development available.",
      "Now Black takes on e4. The knight lands on a strong central square with tactics behind it.",
      "White builds a full center and tries to prove the e4 knight is overextended.",
      "Black answers in the center, defends the knight, and takes a share of the board.",
      "White develops the bishop and lines up against the e4 knight.",
      "Black calmly develops and prepares to castle. The knight on e4 is already accounted for.",
      "White castles before the center opens further.",
      "Black develops with tempo and increases pressure on d4 and e5.",
      "White attacks the e4 knight again and tries to win it by force.",
      "Bg4 is the energetic Petrov answer from the transcript. Black pins the knight on f3 and aims at d4 instead of retreating.",
      "White takes on e4 with the bishop to strip away the central outpost.",
      "Black recaptures with the d-pawn, opening the e-file and keeping the initiative.",
      "White grabs the pawn, but that rook is now overloaded and the center is loose.",
      "Black removes the knight that was defending d4. This is the tactical point of the whole line.",
      "White recaptures with the queen to keep material balance.",
      "Black wins back the d4 pawn with tempo and hits the queen. White's attempt to win the e4 knight only helped Black activate."
    ]
  }
]);
