export const petrovDefenseLines = [
  {
    category: "Petrov Defense",
    id: "petrovDefense-01-895113e8",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "Bb5+",
      "c6",
      "Bxc6+",
      "Nxc6",
      "O-O",
      "dxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black plays c6 to blunt checks on b5 and to prepare ...d5 in some lines, even if it costs a little time.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black captures on c6 with the knight, usually removing a key defender or converting initiative into material.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-02-65e4b94b",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qa4",
      "f4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to g3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to f5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White slides the queen to a4 to give check or pressure; it usually targets the e4 pawn or pins along the a4 e8 diagonal.",
      "Black pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-03-e3b56bbc",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qe2",
      "f4",
      "Qh5+",
      "Qf7",
      "Qxg5",
      "fxg3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to g3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to f5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black moves the queen to f7 with a concrete task, either defending a pawn or creating a direct threat.",
      "White captures on g5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black captures on g3 to open files and change the structure; ask what new line just opened and who benefits from it."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-04-381498b9",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "Bd3",
      "Bxd3",
      "cxd3",
      "Nb4",
      "Kd2",
      "O-O-O",
      "Nc3",
      "Nxd3",
      "Ke3",
      "Bc5+",
      "Kf3",
      "Bxf2"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops the bishop to d3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on d3 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on d3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black places the knight on b4 to improve central influence and set up the next tactic or break.",
      "White moves the king to d2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black captures on d3 with the knight, usually removing a key defender or converting initiative into material.",
      "White moves the king to e3, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to f3, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black captures on f2 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-05-4a0deb88",
    name: "Bc4 gambit try, tactical refutation",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Bc4",
      "d5",
      "Bb3",
      "Qg5",
      "O-O",
      "Qxe5",
      "d3",
      "Nxf2",
      "Rxf2",
      "Bc5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black hits the center with d5, the key Petrov idea: challenge e4 immediately instead of defending passively.",
      "White develops the bishop to b3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black moves the queen to g5 with a concrete task, either defending a pawn or creating a direct threat.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "White pushes a pawn to d3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black captures on f2 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on f2 with the rook, usually removing a key defender or converting initiative into material.",
      "Black develops the bishop to c5, choosing a diagonal that targets a weakness or supports a central break."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-06-ead2fb12",
    name: "Bc4 gambit try, tactical refutation",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Bc4",
      "d5",
      "Bb3",
      "Qg5",
      "Nf3",
      "Qxg2",
      "Rf1",
      "Bg4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White develops Bc4 to point at f7 and to support quick checks; in open games this bishop is often the main attacking piece.",
      "Black hits the center with d5, the key Petrov idea: challenge e4 immediately instead of defending passively.",
      "White develops the bishop to b3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black moves the queen to g5 with a concrete task, either defending a pawn or creating a direct threat.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black captures on g2 with the queen, usually removing a key defender or converting initiative into material.",
      "White activates a rook to f1 to pressure an open file created by earlier trades.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-07-79bde82c",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "c3",
      "O-O-O",
      "Bb5",
      "Nxe5",
      "Bxe5",
      "Rd5",
      "Bxg7",
      "Bxg7"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on e5 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to d5 to pressure an open file created by earlier trades.",
      "White captures on g7 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on g7 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-08-951ab479",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "O-O",
      "Qc5+",
      "Be3",
      "Qxb5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on b5 with the queen, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-09-660cff85",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "c3",
      "O-O-O",
      "Be3",
      "g5",
      "g3",
      "gxf4",
      "gxf4",
      "Bh6",
      "Nd2",
      "Nxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on f4 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops the bishop to h6, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the knight on d2 to improve central influence and set up the next tactic or break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-10-a302b607",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qa4",
      "f4",
      "Bb5",
      "Qxe5+",
      "Kd1",
      "Bd7",
      "Re1",
      "O-O-O",
      "Rxe5",
      "Bg4+",
      "Ke1",
      "Rd1#"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to g3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to f5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White slides the queen to a4 to give check or pressure; it usually targets the e4 pawn or pins along the a4 e8 diagonal.",
      "Black pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White moves the king to d1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White activates a rook to e1 to pressure an open file created by earlier trades.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White captures on e5 with the rook, usually removing a key defender or converting initiative into material.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to e1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives checkmate to keep the initiative."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-11-b7a55a21",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bf4",
      "g5",
      "Bg3",
      "f5",
      "Qd5",
      "f4",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black pushes a pawn to g5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to g3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black pushes a pawn to f5 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White moves the queen to d5 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-12-a2e1d897",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "Nc3",
      "Nd4",
      "Bd3",
      "Qh4+",
      "g3",
      "Qh3",
      "Be3",
      "Bf3"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black places the knight on d4 to improve central influence and set up the next tactic or break.",
      "White develops the bishop to d3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black moves the queen to h3 with a concrete task, either defending a pawn or creating a direct threat.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black develops the bishop to f3, choosing a diagonal that targets a weakness or supports a central break."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-13-4917221f",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "f4",
      "Bg4",
      "Bb5",
      "O-O-O",
      "Bxc6",
      "Rd1+",
      "Kf2",
      "Rxh1",
      "Bxb7+",
      "Kb8",
      "Be3",
      "Qh4+",
      "g3",
      "Rxh2+",
      "Kf1",
      "Bh3+",
      "Ke1",
      "Qxg3+"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to g4, choosing a diagonal that targets a weakness or supports a central break.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black gives check to keep the initiative.",
      "White moves the king to f2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black captures on h1 with the rook, usually removing a key defender or converting initiative into material.",
      "White gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "Black moves the king to b8, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "White develops the bishop to e3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White pushes a pawn to g3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black gives check to keep the initiative.",
      "White moves the king to f1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with a bishop to win time; in open games this often comes with a pin or an attack on an undefended piece.",
      "White moves the king to e1, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-14-0f851c49",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "Qa4+",
      "Bd7",
      "Qe4",
      "Nc6",
      "d4",
      "dxe5",
      "dxe5",
      "O-O-O"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White moves the queen to e4 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-15-cdc8e677",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Nc3",
      "Qxe5",
      "Qxe5+",
      "Nxe5",
      "Bf4",
      "Bd6",
      "Nb5",
      "Nf3+",
      "gxf3",
      "Bxf4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "White gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to d6, choosing a diagonal that targets a weakness or supports a central break.",
      "White places the knight on b5 to improve central influence and set up the next tactic or break.",
      "Black gives check with a knight, often aiming at a fork or to drag the king off castling rights.",
      "White captures on f3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black captures on f4 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-16-3b66d7f0",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "Bd3",
      "Bxd3",
      "cxd3",
      "Nb4",
      "Kd2",
      "O-O-O",
      "Nc3",
      "f6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White develops the bishop to d3, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on d3 with the bishop, usually removing a key defender or converting initiative into material.",
      "White captures on d3 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black places the knight on b4 to improve central influence and set up the next tactic or break.",
      "White moves the king to d2, typically forced by checks; the priority becomes re coordinating pieces and finding safety.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to f6 to support a plan; check what weakness it creates and whether it helps development or attack."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-17-5434f392",
    name: "Queen sidestep variation",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qf3",
      "Ng5",
      "Qf4",
      "d6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White moves the queen to f3 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black places the knight on g5 to improve central influence and set up the next tactic or break.",
      "White moves the queen to f4 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-18-c7454ce4",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "Bxc6",
      "Bxc6",
      "O-O",
      "O-O-O",
      "Nc3",
      "Bb4"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black puts Bb4 on the board to check or pin, trying to disrupt development and win a tempo."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-19-47348ed2",
    name: "Queen sidestep variation",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qf3",
      "Ng5",
      "Qe3",
      "Be7"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White moves the queen to f3 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black places the knight on g5 to improve central influence and set up the next tactic or break.",
      "White moves the queen to e3 with a concrete task, either defending a pawn or creating a direct threat.",
      "Black develops the bishop to e7, choosing a diagonal that targets a weakness or supports a central break."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-20-faa259e3",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "f4",
      "Bf5",
      "c3",
      "O-O-O",
      "Bb5",
      "Bc5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to c5, choosing a diagonal that targets a weakness or supports a central break."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-21-04bf546b",
    name: "Petrov main structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "d3",
      "Nf6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White pushes a pawn to d3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-22-23a1453d",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Nc3",
      "a6",
      "Ba4",
      "Nxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to a6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops the bishop to a4, choosing a diagonal that targets a weakness or supports a central break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-23-cc081ebf",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "dxe5",
      "Nc6",
      "Bb5",
      "Bd7",
      "O-O",
      "O-O-O",
      "Nc3",
      "a6",
      "Bxc6",
      "Bxc6"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White plays Bb5 to pin a knight and increase pressure on e5 or c6, making defense of the center awkward.",
      "Black develops the bishop to d7, choosing a diagonal that targets a weakness or supports a central break.",
      "White castles kingside to get the king safe and connect rooks; now you can think about central breaks instead of tactics on the back rank.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White plays Nc3 to add central control over d5 and e4 and to support a future d4 push or recapture.",
      "Black pushes a pawn to a6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White captures on c6 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black captures on c6 with the bishop, usually removing a key defender or converting initiative into material."
    
    ]
  },
  {
    category: "Petrov Defense",
    id: "petrovDefense-24-b5236397",
    name: "Main line with early queen trade",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "Nxe4",
      "Qe2",
      "Qe7",
      "Qxe4",
      "d6",
      "d4",
      "dxe5",
      "Qxe5",
      "Qxe5+",
      "dxe5",
      "Nc6",
      "Bf4",
      "Bf5",
      "c3",
      "O-O-O",
      "Nd2",
      "Nxe5",
      "Bxe5",
      "Re8",
      "f4",
      "f6",
      "Nf3",
      "fxe5"
    ],
    explanations: [
      
      "White advances a central pawn to e4 to claim space and define which files and diagonals will open.",
      "Black advances a central pawn to e5 to claim space and define which files and diagonals will open.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black develops Nf6 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "White captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "Black captures on e4 with the knight, usually removing a key defender or converting initiative into material.",
      "White plays Qe2 to confront the knight on e4 and keep the option to trade queens, which often kills Black's initiative.",
      "Black plays Qe7 to offer queen trades and clear the e file tension; the Petrov often aims for simplification into a solid structure.",
      "White captures on e4 with the queen, usually removing a key defender or converting initiative into material.",
      "Black plays d6 to support e5 and prepare ...dxe5 or ...Nc6, making the extra pawn on e5 harder for White to keep.",
      "White advances a central pawn to d4 to claim space and define which files and diagonals will open.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "White captures on e5 with the queen, usually removing a key defender or converting initiative into material.",
      "Black gives check with the queen, forcing a response and usually gaining a tempo for development or a follow up threat.",
      "White captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it.",
      "Black develops Nc6 to increase pressure on e5 and d4, and to prepare ...dxe5 or ...Bf5 in many lines.",
      "White develops Bf4 to hit c7 or to support Qb3 ideas; it also helps complete development fast.",
      "Black develops the bishop to f5, choosing a diagonal that targets a weakness or supports a central break.",
      "White pushes a pawn to c3 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black castles queenside, putting a rook on d8 or d1 and often committing to a sharper opposite side attack.",
      "White places the knight on d2 to improve central influence and set up the next tactic or break.",
      "Black captures on e5 with the knight, usually removing a key defender or converting initiative into material.",
      "White captures on e5 with the bishop, usually removing a key defender or converting initiative into material.",
      "Black activates a rook to e8 to pressure an open file created by earlier trades.",
      "White pushes a pawn to f4 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "Black pushes a pawn to f6 to support a plan; check what weakness it creates and whether it helps development or attack.",
      "White develops Nf3 to contest the center, hitting e5 or e4 and preparing quick castling.",
      "Black captures on e5 to open files and change the structure; ask what new line just opened and who benefits from it."
    
    ]
  }
];
