import { withOpeningFeedback } from "./feedback";

// SEO / page intro text for QGD drills
export const queensGambitDeclinedSEOText = `
The Queen's Gambit Declined (1. d4 d5 2. c4 e6) is the bedrock of classical chess. Black refuses the "wing pawn" bribe and builds a rock-solid center.

Your goal as White is to slowly dismantle this fortress. The most instructive way to do this is the Exchange Variation, where we clarify the center and launch a "Minority Attack" on the queenside to create permanent weaknesses in Black's structure.

These drills cover the soul of the QGD:
- The Exchange Variation: Using the Bxf6 and cxd5 plans to gain a clear strategic target.
- The Carlsbad Structure: Mastering the pawn play that defines high-level positional chess.
- Tactical Traps: Punishing Black's attempts to solve the "Bad QGD Bishop" on c8 too early or with the wrong piece order.

Solid, deep, and positional—the QGD teaches you how to win through superior coordination and patience!
`;

export const queensGambitDeclinedLines = withOpeningFeedback([
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-01",
    "name": "The Exchange Variation: Minority Attack Plan",
    "description": "The coach's top recommendation: clarify the center early and start the long-term squeeze.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "c6",
      "Bd3",
      "O-O",
      "Qc2"
    ],
    "explanations": [
      "White starts with the queen's pawn.",
      "Let's learn the Queen's Gambit Declined! Black builds a solid center.",
      "The Gambit! We challenge the center from the flank.",
      "Declined. Black supports d5 and prepares to develop.",
      "Develop the knight and increase pressure on the center.",
      "Black develops their best defender.",
      "The Exchange! We clarify the center immediately to give ourselves a clear plan.",
      "Black recaptures. Notice the pawn structure: White has fewer pawns on the queenside, leading to the 'Minority Attack'.",
      "The Star Bishop! We pin the knight before Black can castle.",
      "Black unpins and prepares king safety.",
      "Solidify! We build our own pyramid and open the path for the light-squared bishop.",
      "Black supports their center and prepares queenside development.",
      "The Golden Bishop! We put it on its best square, eyeing the kingside.",
      "Black castles to safety.",
      "The Waiting Move! We coordinate our pieces, support the center, and prepare to launch our queenside attack. White has a clear positional advantage!"
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-02",
    "name": "Ragozin style: Bb4 pin and h7 tactic",
    "description": "A sharp line where Black tries to be active with Bb4, but walks into a Greek Gift idea.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Bb4",
      "e3",
      "O-O",
      "Bd3",
      "dxc4",
      "Bxc4",
      "c5",
      "Nf3",
      "cxd4",
      "exd4",
      "Qc7",
      "Bxf6",
      "Qxc4",
      "Ne5",
      "Bxc3+",
      "bxc3",
      "Qxc3+",
      "Kf1",
      "gxf6",
      "Rc1",
      "Qa3",
      "Qg4+",
      "Kh8",
      "Nxf7+"
    ],
    "explanations": [
      "White takes the center.",
      "Black responds symmetrically.",
      "The Gambit offer.",
      "Declined.",
      "Develop and attack.",
      "Defend and develop.",
      "The Star Bishop! We pin the knight.",
      "Black counter-pins! This is the active Ragozin Defense.",
      "Solidify the center.",
      "Black castles to safety.",
      "Develop the attacking bishop.",
      "Black releases the tension, but they're giving up their stake in the center.",
      "Recapture with development.",
      "Black strikes back! Challenging our center immediately.",
      "Develop and defend.",
      "Trade! The center is opening up.",
      "Recapture. We now have an isolated d-pawn, but very active pieces.",
      "Black attacks the bishop, trying to force a decision.",
      "Trade! We remove the key defender of the kingside.",
      "Black recaptures, hitting our knight.",
      "Jump forward! We ignore the queen and target the exposed king.",
      "Black tries to simplify with a trade.",
      "Recapture. Our structure is damaged, but our attack is deadly.",
      "Black grabs a pawn with check.",
      "The king moves to safety. We don't fear the lack of castling.",
      "Black takes the knight, but they've opened their king's throat.",
      "Activate the rook with tempo! The queen must move.",
      "Black retreats, but there's no escape.",
      "BOOM! The queen enters the attack with check.",
      "Forced.",
      "CHECKMATE! The knight sacrifice on f7 leads to a beautiful finish. Tactical brilliance!"
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-03",
    "name": "Semi-Slav: e5 and Qg4 pressure",
    "description": "Win space with e5, kick the knight, and use Qg4 to ask direct kingside questions.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "Nf6",
      "cxd5",
      "cxd5",
      "e5",
      "Nfd7",
      "Qg4"
    ],
    "explanations": [
      "Start with the queen pawn and claim central space.",
      "Black meets it directly and builds a solid center of their own.",
      "Offer the c-pawn to challenge {{square d5}} from the side.",
      "Black keeps a QGD shell and opens the diagonal for the dark-squared bishop.",
      "N{{square c3}} is standard and increases pressure on {{square d5}}.",
      "With ...{{square c6}} Black supports {{square d5}} and heads for a Semi-Slav structure.",
      "White grabs the full center before Black finishes development.",
      "Black hits {{square e4}} immediately and asks White to justify the space grab.",
      "Clarify the center before Black can settle comfortably.",
      "Black keeps the pawn chain intact and hopes the center will hold.",
      "{{square e5}} gains space, drives the knight back, and starts to squeeze Black.",
      "The knight retreats and Black loses some freedom in the center.",
      "Q{{square g4}} is the direct follow-up: it hits {{square g7}} and turns the space advantage into kingside pressure."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-04",
    "name": "Exchange QGD: win a pawn with Qxd5",
    "description": "Exchange variation with Bg5 and queen picks up d5 after tactical details.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "b6",
      "Bxf6",
      "Bxf6",
      "Qh5",
      "g6",
      "Qxd5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black prepares to develop bishop to {{square b7}}.",
      "White captures, removing defender of {{square d5}} pawn.",
      "Black recaptures, developing the bishop.",
      "White attacks the weak {{square h7}} square.",
      "Black defends but weakens dark squares.",
      "White captures the undefended {{square d5}} pawn, winning material."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-05",
    "name": "Exchange QGD: Qc2, f3, and e4 plan",
    "description": "Use the Qc2 waiting move, keep the bishop pin, then prepare the standard f3 and e4 break.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "Ndf6",
      "f3",
      "Nd6",
      "e4",
      "dxe4",
      "fxe4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black stabilizes the {{square d5}} chain and keeps the standard QGD shell.",
      "Q{{square c2}} is the useful waiting move from the transcript. It supports {{square e4}}, coordinates with B{{square d3}} on the {{square h7}} diagonal, and keeps queenside castling available.",
      "Black asks the bishop to decide before finishing queenside development.",
      "Keep the bishop when possible. The retreat preserves the pin and keeps attacking ideas alive.",
      "Black finishes queenside development and keeps ...N{{square e4}} in reserve.",
      "White develops the last minor piece and prepares the standard {{square f3}}-{{square e4}} plan.",
      "The rook supports ...N{{square e4}} and gives Black extra central bite.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black regroups to keep {{square d5}} covered and reduce the force of White's break.",
      "{{square f3}} is the key preparatory move. It kicks the knight and makes {{square e4}} much easier to achieve.",
      "The knight falls back but still watches central squares.",
      "White finally gets the thematic break and asks Black to solve the center on White's terms.",
      "Black captures to reduce the bind before White can roll forward.",
      "White recaptures and keeps a broad center with active pieces behind it."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-06",
    "name": "Semi-Slav: central space with e5",
    "description": "A compact Semi-Slav line where White claims space and immediately chases the f6-knight.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "Nf6",
      "cxd5",
      "exd5",
      "e5"
    ],
    "explanations": [
      "White starts by staking out the center.",
      "Black answers in kind and keeps a solid pawn chain.",
      "The gambit challenges {{square d5}} from the side and asks Black how they want to hold the center.",
      "Black keeps QGD options open and frees the dark-squared bishop.",
      "N{{square c3}} adds pressure to {{square d5}} and supports {{square e4}}.",
      "With ...{{square c6}} Black reinforces {{square d5}} and heads into Semi-Slav territory.",
      "{{square e4}} takes as much central space as possible while Black is still undeveloped.",
      "The knight attacks {{square e4}} and forces White to decide how to handle the center.",
      "White clarifies the structure before Black can trade everything on favorable terms.",
      "Black keeps the {{square d5}} pawn and hopes the chain will hold.",
      "{{square e5}} is the whole point here: White gains space, kicks the knight, and starts restricting Black's pieces."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-07",
    "name": "Exchange QGD: Nf4 plan",
    "description": "Standard exchange structure with a kingside plan and piece maneuver.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "h6",
      "Bh4",
      "c6",
      "Nge2",
      "Bg4",
      "f3",
      "Bh5",
      "Nf4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "A useful waiting move: Black asks the bishop to decide before finishing queenside development.",
      "White keeps the pin, but the bishop has been pushed back and Black keeps kingside space-gaining ideas.",
      "Black supports the {{square d5}} pawn.",
      "White develops knight, preparing kingside plans.",
      "Black pins the knight.",
      "White breaks the pin and gains space.",
      "Black retreats bishop.",
      "White maneuvers knight to attack weak {{square d5}} and {{square h5}} squares."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-08",
    "name": "Ragozin: Ba3 idea",
    "description": "Ba3 targets the queenside and pressures the diagonal.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Bb4",
      "e3",
      "Bxc3+",
      "bxc3",
      "Nf6",
      "Ba3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Ragozin Defense: pins the knight.",
      "Reinforces the center and prepares bishop development.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black develops knight.",
      "White develops bishop to target Black's weak queenside pawns and control long diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-09",
    "name": "Exchange QGD: dxc5 break",
    "description": "Long plan that ends with dxc5 to open queenside lines.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Nf8",
      "f3",
      "Ne6",
      "Rad1",
      "c5",
      "dxc5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the {{square d5}} pawn.",
      "White supports the {{square e4}} break and places a heavy piece on the c-file for future pressure.",
      "A useful waiting move: Black asks the bishop to decide before finishing queenside development.",
      "White keeps the pin, but the bishop has been pushed back and Black keeps kingside space-gaining ideas.",
      "Black develops without tying up the queenside and keeps ...N{{square e4}} in mind.",
      "White develops knight, preparing {{square f3}} and {{square e4}}.",
      "The rook supports ...N{{square e4}} and gives Black more central bite on the e-file.",
      "White castles to safety.",
      "Black repositions knight for kingside defense.",
      "White prepares {{square e4}} break.",
      "Black develops knight to active square.",
      "White activates rook on d-file.",
      "Black challenges White's center.",
      "White captures, opening the center and gaining pawn majority."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-10",
    "name": "QGD with ...dxc4: immediate e4",
    "description": "If Black grabs on c4, take the center first with e4 and win the pawn back later with development.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "dxc4",
      "e4"
    ],
    "explanations": [
      "Start with the queen pawn and claim central space.",
      "Black meets it directly and makes a classical {{square d4}}-{{square d5}} center.",
      "Offer the c-pawn to distract Black from the middle.",
      "Black declines the gambit for the moment and keeps a solid chain.",
      "N{{square c3}} is the standard development square and adds pressure to {{square d5}}.",
      "Once Black grabs the pawn, the transcript's rule is simple: stop chasing it for a move and take the center instead.",
      "{{square e4}} builds the full pawn duo in the center. White gets the kind of space edge that usually pays the pawn back with interest."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-11",
    "name": "Exchange QGD: f5 and recapture",
    "description": "Line featuring ...f5 and a clean Nxc3 recapture.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "f5",
      "f3",
      "Nxc3",
      "Nxc3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the {{square d5}} pawn.",
      "White supports the {{square e4}} break and places a heavy piece on the c-file for future pressure.",
      "A useful waiting move: Black asks the bishop to decide before finishing queenside development.",
      "White keeps the pin, but the bishop has been pushed back and Black keeps kingside space-gaining ideas.",
      "Black develops without tying up the queenside and keeps ...N{{square e4}} in mind.",
      "White develops knight, preparing {{square f3}} and {{square e4}}.",
      "The rook supports ...N{{square e4}} and gives Black more central bite on the e-file.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black gains kingside space but weakens {{square e5}} square.",
      "White attacks the knight and prepares {{square e4}}.",
      "Black captures knight to relieve pressure.",
      "White recaptures, maintaining central control."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-12",
    "name": "Exchange QGD: c5 and dxc5",
    "description": "Black strikes with ...c5, White takes on c5 to win time.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c5",
      "dxc5",
      "Bxc5",
      "Nge2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White captures, gaining pawn majority and opening position.",
      "Black recaptures, developing bishop.",
      "White develops knight, preparing to attack weak {{square d5}} pawn."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-13",
    "name": "QGD Exchange: Carlsbad style build-up",
    "description": "Build up, then develop Bb2 in a Carlsbad-type structure.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "Nxd5",
      "e4",
      "Nxc3",
      "bxc3",
      "Be7",
      "Nf3",
      "O-O",
      "Bd3",
      "c5",
      "O-O",
      "cxd4",
      "cxd4",
      "Nc6",
      "Bb2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures with knight instead of pawn.",
      "White gains space in the center.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black develops bishop, preparing to castle.",
      "White develops knight to natural square.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures, maintaining central pawn.",
      "Black develops knight, attacking {{square d4}} pawn.",
      "White develops bishop to target Black's kingside and control long diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-14",
    "name": "Semi-Slav: sharp line with check",
    "description": "Semi-Slav structure with Bb4+ and forcing exchanges.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "dxe4",
      "Nxe4",
      "Nf6",
      "Nxf6+",
      "Qxf6",
      "Nf3",
      "Bb4+",
      "Bd2",
      "Bxd2+",
      "Qxd2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports {{square d5}} pawn.",
      "White strikes in the center.",
      "Black captures, accepting the pawn.",
      "White recaptures with knight.",
      "Black attacks the knight.",
      "White captures, forcing queen recapture.",
      "Black recaptures with queen.",
      "White develops knight to natural square.",
      "Check! Black develops bishop with tempo.",
      "White blocks the check and develops bishop.",
      "Check! Black exchanges bishops.",
      "White recaptures, developing queen actively."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-15",
    "name": "Semi-Slav: queen grab and tactics",
    "description": "Tactical line with early queen grabs and checks.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "dxe4",
      "Nxe4",
      "Bb4+",
      "Bd2",
      "Qxd4",
      "Bxb4",
      "Qxe4+",
      "Be2",
      "Qxg2",
      "Bf3",
      "Qg5",
      "Ne2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports {{square d5}} pawn.",
      "White strikes in the center.",
      "Black captures, accepting the pawn.",
      "White recaptures with knight.",
      "Check! Black develops bishop with tempo.",
      "White blocks the check and develops bishop.",
      "Black captures central pawn with queen.",
      "White captures bishop, attacking the queen.",
      "Check! Black saves queen and attacks bishop.",
      "White blocks the check and develops bishop.",
      "Black captures pawn and attacks rook.",
      "White defends rook and attacks queen.",
      "Black moves queen to safer square.",
      "White develops knight, preparing to attack exposed queen."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-16",
    "name": "Tarrasch: Qa4+ and regain",
    "description": "Queen check then regain central material with tempo.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c5",
      "cxd5",
      "cxd4",
      "Qa4+",
      "Bd7",
      "Qxd4",
      "exd5",
      "Qxd5",
      "Nf6",
      "Qb3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Tarrasch Defense: immediately challenges center.",
      "White exchanges to open position.",
      "Black captures pawn with pawn.",
      "Check! White develops queen with tempo, attacking {{square a7}}.",
      "Black blocks check and develops bishop.",
      "White captures pawn, regaining material.",
      "Black recaptures pawn.",
      "White captures pawn, equalizing material.",
      "Black develops knight, attacking queen.",
      "White retreats queen to active square, maintaining pressure on {{square b7}} and {{square d5}}."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-17",
    "name": "Tarrasch: isolate pressure and Rc1",
    "description": "Tactical sequence and rook activation with Rc1.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c5",
      "cxd5",
      "exd5",
      "Nf3",
      "Nc6",
      "dxc5",
      "d4",
      "Na4",
      "Bxc5",
      "Nxc5",
      "Qa5+",
      "Bd2",
      "Qxc5",
      "Rc1"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Tarrasch Defense: immediately challenges center.",
      "White exchanges to isolate Black's d-pawn.",
      "Black recaptures, creating isolated pawn.",
      "White develops knight to natural square.",
      "Black develops knight, attacking {{square d4}} square.",
      "White captures, gaining pawn.",
      "Black advances pawn, gaining space.",
      "White moves knight to attack bishop.",
      "Black captures pawn, developing bishop.",
      "White captures bishop, gaining material.",
      "Check! Black attacks knight with queen.",
      "White blocks check and develops bishop.",
      "Black captures knight, regaining material.",
      "White activates rook on semi-open file, attacking queen."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-18",
    "name": "QGD Exchange: long mainline with ...b6",
    "description": "A long Exchange QGD where Black solves the c8 bishop with ...b6 and White keeps the more active setup.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "Nxd5",
      "e4",
      "Nxc3",
      "bxc3",
      "c5",
      "Nf3",
      "cxd4",
      "cxd4",
      "Bb4+",
      "Bd2",
      "Bxd2+",
      "Qxd2",
      "O-O",
      "Bc4",
      "Nd7",
      "O-O",
      "b6",
      "Rfe1",
      "Bb7",
      "Rad1",
      "Rc8",
      "Bb3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures with knight.",
      "White gains space in center.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black challenges White's center.",
      "White develops knight to natural square.",
      "Black captures, opening the center.",
      "White recaptures, maintaining central pawn.",
      "Check! Black develops bishop with tempo.",
      "White blocks check and develops bishop.",
      "Check! Black exchanges bishops.",
      "White recaptures, developing queen.",
      "Black castles to safety.",
      "White develops bishop to active square.",
      "Black chooses ...N{{square d7}} so the queenside stays flexible and the bishop can often come to {{square b7}} later.",
      "White castles to safety.",
      "...{{square b6}} is the standard fix for the {{square c8}} bishop, but it also shows Black is still spending tempi solving development problems.",
      "White improves the rook and keeps pressure on the central files before anything opens.",
      "Now the bishop finally gets to {{square b7}}, but White has already completed a cleaner setup.",
      "White activates rook on d-file.",
      "Black activates rook on semi-open file.",
      "White retreats bishop to maintain pressure on {{square a2}}-{{square g8}} diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-19",
    "name": "Ragozin: quiet buildup",
    "description": "Bb4 pin, then quiet development into a playable middlegame.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Bb4",
      "e3",
      "Nf6",
      "a3",
      "Bxc3+",
      "bxc3",
      "O-O",
      "cxd5",
      "exd5",
      "Bd3",
      "c5",
      "Ne2",
      "Nc6",
      "O-O"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Ragozin Defense: pins the knight.",
      "Reinforces the center and prepares bishop development.",
      "Black develops knight.",
      "White forces bishop decision.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black castles to safety.",
      "White exchanges to open position.",
      "Black recaptures, maintaining isolated pawn.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White develops knight, avoiding pawn attacks.",
      "Black develops knight, attacking {{square d4}} pawn.",
      "White castles to safety, completing development."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-20",
    "name": "Exchange QGD: standard Qc2 and e4 break",
    "description": "Drill the main Exchange move order with Qc2, the bishop retreat, and the standard f3-e4 break.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "Ndf6",
      "f3",
      "Nxc3",
      "Nxc3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the {{square d5}} pawn.",
      "Q{{square c2}} is the waiting move that keeps the plan simple: support {{square e4}}, line up with B{{square d3}}, and keep queenside castling as an option.",
      "A useful waiting move: Black asks the bishop to decide before finishing queenside development.",
      "The bishop drops back but the pin still mattered, and White has not lost the thread of the plan.",
      "Black develops without tying up the queenside and keeps ...N{{square e4}} in mind.",
      "White develops the last minor piece and gets ready for the standard central expansion.",
      "The rook supports ...N{{square e4}} and gives Black more central bite on the e-file.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black repositions knight.",
      "This is the main trigger: hit the knight, support {{square e4}}, and prepare to open the center under favorable conditions.",
      "Black captures knight to relieve pressure.",
      "White recaptures with the knight and keeps central control plus active pieces."
    ]
  },
    {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-21",
    "name": "Exchange QGD: Rubinstein queen trap",
    "description": "A classic tactical trap where ...Nh5 looks natural but walks into Nxd5 and Bc7.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Nge2",
      "Nbd7",
      "O-O",
      "Re8",
      "Qc2",
      "h6",
      "Bf4",
      "Nh5",
      "Nxd5",
      "cxd5",
      "Bc7"
    ],
    "explanations": [
      "White starts with the queen pawn and claims central space.",
      "Black answers with the standard QGD center.",
      "The c-pawn challenges {{square d5}} and asks Black how they want to hold the middle.",
      "Black declines the gambit and keeps the structure intact.",
      "N{{square c3}} develops and adds pressure to {{square d5}}.",
      "Black develops the knight toward the center.",
      "White chooses the Exchange structure on purpose, aiming for a clear plan rather than tension.",
      "Black recaptures with the e-pawn and keeps the usual QGD formation.",
      "The bishop comes out before {{square e3}} so it does not get boxed in.",
      "Black breaks the pin and prepares to castle.",
      "White supports the center and opens the diagonal for the other bishop.",
      "Black castles and hopes the position will stay quiet.",
      "B{{square d3}} is the natural square in these Exchange structures because it supports the kingside and central breaks.",
      "...{{square c6}} keeps {{square d5}} solid and takes {{square b5}} away from White's knight.",
      "Nge2 finishes development without blocking the f-pawn, which matters in many Exchange plans.",
      "Black develops calmly and thinks the position is under control.",
      "White castles before starting any concrete tactics.",
      "The rook steps to {{square e8}} to support central play and future ...N{{square e4}} ideas.",
      "Q{{square c2}} is a precise waiting move: it supports {{square e4}}, reinforces the {{bishop d3 full}}, and points toward {{square h7}}.",
      "Black asks the bishop a question and expects to gain time.",
      "B{{square f4}} keeps the bishop active and, more importantly, preserves the {{square c7}}-{{square d8}} diagonal.",
      "...N{{square h5}} looks logical because Black attacks the bishop again, but this is the tactical mistake.",
      "Nx{{square d5}} blows up the center at the right moment. White uses the fact that Black's queen and back rank pieces are poorly coordinated.",
      "Black has to take, but that capture jams the queen's escape squares.",
      "B{{square c7}} is the punchline. The bishop traps the {{queen d8 full}} and turns the natural-looking ...N{{square h5}} plan into a tactical disaster."
    ]
  }
,
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-22",
    "name": "Main QGD mission line with queenside castling",
    "description": "Use Bg5, Qc2, cxd5, and Bd3 before castling long when Black heads for ...Bb7.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Nf3",
      "Nbd7",
      "Qc2",
      "b6",
      "cxd5",
      "exd5",
      "Bd3",
      "Bb7",
      "O-O-O"
    ],
    "explanations": [
      "White starts with the queen pawn and claims the center.",
      "Black answers with the standard QGD setup.",
      "The gambit challenges {{square d5}} from the side and fights for more central space.",
      "Black keeps the pawn chain intact and frees the dark-squared bishop.",
      "N{{square c3}} adds pressure to {{square d5}} and fits the main QGD plan.",
      "Black develops the knight and now gives White something concrete to pin.",
      "B{{square g5}} is the transcript's first bishop mission in the main declined setup: pin the knight before playing {{square e3}}.",
      "Black breaks the pin with the usual bishop development.",
      "Now {{square e3}} is safe because the {{square c1}} bishop already escaped.",
      "Black castles and waits to see how White will organize the center.",
      "N{{square f3}} completes kingside development and keeps the center flexible.",
      "Black finishes queenside development and holds the center together.",
      "Q{{square c2}} is the useful waiting move. It supports {{square e4}} ideas, lines up with B{{square d3}}, and keeps long castling available.",
      "Black tries to solve the {{square c8}} bishop with a {{square b6}}-B{{square b7}} setup.",
      "This is the moment the transcript highlights: White can release the tension because Black's bishop is about to look silly behind the pawn chain.",
      "Black must recapture and keeps the basic structure, but the bishop path is no longer especially impressive.",
      "B{{square d3}} is now the natural square. White develops with direct kingside pressure and no wasted move.",
      "Black gets the bishop out, but it does not challenge White's central plan very much from {{square b7}}.",
      "Castling long fits the transcript's practical low-Elo plan: line the rooks up and start pawn play on the kingside."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-23",
    "name": "Main QGD: hold the bishop until ...dxc4",
    "description": "Keep the light-squared bishop flexible so it can recapture on c4 in one move.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Nf3",
      "Nbd7",
      "Qc2",
      "dxc4",
      "Bxc4"
    ],
    "explanations": [
      "White starts with the queen pawn and claims central space.",
      "Black meets it with the standard QGD center.",
      "The c-pawn challenges {{square d5}} and asks Black how they want to defend the middle.",
      "Black declines the gambit and keeps the pawn chain intact.",
      "N{{square c3}} is the normal square and increases pressure on {{square d5}}.",
      "Black develops the knight, which gives White a piece to pin.",
      "B{{square g5}} gets the bishop out before {{square e3}} and makes Black explain the {{knight f6 full}}.",
      "Black breaks the pin with the usual bishop move.",
      "{{square e3}} supports the center and opens the diagonal for the other bishop.",
      "Black castles and hopes White will waste time recovering the pawn.",
      "N{{square f3}} finishes kingside development and keeps everything under control.",
      "Black develops calmly and keeps the {{square c4}} pawn for the moment.",
      "Q{{square c2}} is the waiting move from the transcript: improve the queen before committing the {{square f1}} bishop.",
      "Once Black finally releases the tension with ...dxc4, the bishop mission becomes simple.",
      "Bx{{square c4}} develops with tempo and wins the pawn back in the cleanest possible way."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-24",
    "name": "Semi-Slav mission line with Qc2 and Bh4",
    "description": "Against an early ...c6 setup, develop by mission: Nf3 first, then Bg5, e3, Qc2, and only retreat the bishop when asked.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "c6",
      "Nc3",
      "e6",
      "Nf3",
      "Nf6",
      "Bg5",
      "Be7",
      "e3",
      "Nbd7",
      "Qc2",
      "h6",
      "Bh4",
      "O-O"
    ],
    "explanations": [
      "White starts with the queen pawn and claims space.",
      "Black answers directly and builds a classical center.",
      "The c-pawn challenges {{square d5}} from the side.",
      "With ...{{square c6}} Black shows a Slav or Semi-Slav shell instead of the pure QGD move order.",
      "N{{square c3}} supports the center and keeps pressure on {{square d5}}.",
      "Black keeps the structure solid and opens the diagonal for the dark-squared bishop.",
      "Because there is no {{knight f6 full}} yet, the transcript's left-to-right mission says to move on and develop the knight first.",
      "Now the knight appears on {{square f6}} and White can come back to the bishop mission.",
      "B{{square g5}} is the clean developing move: pin the knight before locking the bishop in with {{square e3}}.",
      "Black unpins immediately and asks White how the center will be supported.",
      "{{square e3}} keeps the chain solid and opens the diagonal for the other bishop.",
      "Black develops the queenside and keeps the center together.",
      "Q{{square c2}} is the useful waiting move here too. It supports {{square e4}} ideas and coordinates with a future B{{square d3}}.",
      "Black finally asks the bishop a direct question.",
      "B{{square h4}} follows the transcript exactly: keep the bishop if you can and do not lose the thread of development.",
      "Black castles, and White has reached a clean Semi-Slav setup without memorizing anything sharp."
    ]
  }
]);
