// Auto-generated drill lines

export const queensGambitAcceptedLines = [
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-01",
    "name": "Central break with e4 and queenside undermine",
    "description": "Accepted pawn, then White builds a center and breaks Black's pawn chain.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "Bd7",
      "d5",
      "e6",
      "dxe6",
      "fxe6",
      "Nxb5",
      "Bxb5",
      "Qh5+",
      "g6",
      "Qxb5+"
    ],
    "explanations": [
      "Establishes central control and opens lines for the queen and bishop.",
      "Black occupies the center, preparing a solid pawn structure.",
      "Offers the queen's gambit to disrupt Black's center and gain space.",
      "Black accepts the gambit, taking a pawn but delaying development.",
      "White builds a strong pawn center, creating immediate pressure.",
      "Black defends the pawn while expanding on the queenside.",
      "White immediately challenges the advanced b5 pawn, creating tension.",
      "Black protects the b5 pawn with this pawn move.",
      "Forces the capture, opening the a-file for White's rook.",
      "Black recaptures, maintaining material but weakening queenside structure.",
      "Develops a knight with tempo as it attacks the loose b5 pawn.",
      "Black saves the bishop from potential capture after Nxb5.",
      "White pushes the d-pawn to cramp Black's position and limit piece activity.",
      "Black challenges the advanced d5 pawn to open lines.",
      "Creates an isolated pawn for Black and opens the e-file.",
      "Black recaptures toward the center but creates a weak doubled e-pawn.",
      "White exploits the pinned b5 pawn to win material.",
      "Black must recapture, losing the bishop pair advantage.",
      "A discovered attack on the unprotected bishop on b5 with check!",
      "Black blocks the check but weakens the kingside dark squares.",
      "Wins back the bishop with tempo, leaving White up material."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-02",
    "name": "Early ...e5, attack on h8 rook",
    "description": "A forcing tactical line where White's queen infiltrates to win the rook.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "c5",
      "Ne5",
      "Be6",
      "Bxe6",
      "fxe6",
      "Qh5+",
      "g6",
      "Nxg6",
      "hxg6",
      "Qxh8"
    ],
    "explanations": [
      "Standard central pawn opening.",
      "Mirrors White's central control.",
      "Queen's Gambit offer to challenge Black's center.",
      "Accepting the gambit but giving up center control.",
      "White establishes a strong pawn center (e4, d4).",
      "Black immediately challenges the center, creating tactical possibilities.",
      "Develops knight while attacking e5 pawn.",
      "Black takes the pawn but opens the e-file for White.",
      "White recovers the gambit pawn with active piece development.",
      "Black tries to challenge White's center and gain space.",
      "White occupies a strong central outpost, threatening multiple ideas.",
      "Black develops bishop, attacking White's strong bishop on c4.",
      "Forces a structural weakness: if ...fxe6, the f-file opens and kingside weakens.",
      "Black recaptures, creating a doubled pawn and weakening the kingside.",
      "Check! Targeting the weak g6 square and exposed dark squares.",
      "Forced: the only legal move blocks but critically weakens dark squares.",
      "Sacrifices the knight to destroy Black's pawn shield and expose the king.",
      "Forced recapture, opening the h-file completely.",
      "White wins the rook as the h8 rook is trapped and unprotected."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-03",
    "name": "Rook win with Rxa8",
    "description": "Simple trap: queenside rook is taken after ...b5 and ...a6 setup.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "a6",
      "axb5",
      "axb5",
      "Rxa8"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer to create imbalance.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black tries to hold onto the gambit pawn with this expansion.",
      "White immediately challenges the advanced pawn, creating a weakness.",
      "Black defends the pawn but creates an opportunity for White.",
      "Forces the capture, opening the a-file completely.",
      "Black recaptures, but now the rook on a8 is unprotected.",
      "White immediately captures the undefended rook on a8, winning material."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-04",
    "name": "Kingside attack and bishop takes f8",
    "description": "White pushes e5 and aims for a quick tactic on f8.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e6",
      "Bxc4",
      "Nf6",
      "Nc3",
      "Be7",
      "e5",
      "Nd5",
      "Qg4",
      "O-O",
      "Bh6",
      "g6",
      "Bxf8"
    ],
    "explanations": [
      "Standard opening move to control center.",
      "Establishes central presence.",
      "Queen's Gambit offer to create play.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black prepares to develop the kingside bishop.",
      "White recovers the pawn with active piece development.",
      "Black develops knight, attacking e4 pawn.",
      "White develops knight, reinforcing the e4 pawn.",
      "Black develops bishop, preparing to castle.",
      "White gains space and attacks the knight on f6.",
      "Black retreats the knight to a central square.",
      "White's queen targets the weak g7 pawn and prevents castling.",
      "Black castles kingside despite the pressure.",
      "White develops bishop with tempo, attacking the g7 pawn.",
      "Black defends g7 but weakens dark squares around the king.",
      "White captures the bishop, removing a key defender and winning material."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-05",
    "name": "Bxf7 sacrifice and queen takes g4",
    "description": "Accepted pawn, then tactical sequence with a bishop sacrifice to expose the king.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "Bg4",
      "Bxc4",
      "exd4",
      "Bxf7+",
      "Kxf7",
      "Ne5+",
      "Ke8",
      "Qxg4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black pins the knight to the queen, creating tactical possibilities.",
      "White recovers the pawn, developing with tempo.",
      "Black captures in the center but opens the e-file.",
      "Greek Gift sacrifice! Destroys Black's pawn shield and exposes the king.",
      "Forced capture, but now the king is exposed in the center.",
      "Knight check, exploiting the exposed king position.",
      "The king must retreat, losing castling rights.",
      "White wins back the bishop, maintaining material advantage with better development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-06",
    "name": "Qb3 pressure and queen side raid",
    "description": "Development with Qb3, then tactical captures on b7 and c6.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Bg4",
      "Qb3",
      "Qd7",
      "Bxf7+",
      "Qxf7",
      "Qxb7",
      "Rd8",
      "Qxc6+"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking d4 square.",
      "White castles to safety and connects rooks.",
      "Black pins the knight, creating pressure.",
      "White attacks f7 and b7 simultaneously, creating double threats.",
      "Black defends f7 but blocks the d7 square.",
      "Sacrifice to expose Black's king and queen position.",
      "Black must capture with the queen, now exposed on f7.",
      "White wins a pawn and attacks the rook on a8.",
      "Black moves rook to a safer square.",
      "Check! Wins the knight and maintains initiative."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-07",
    "name": "Forcing mate with Qe6#",
    "description": "A direct mating pattern after queen and bishop coordinate on e6.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Bg4",
      "Qb3",
      "Bxf3",
      "Bxf7+",
      "Ke7",
      "Qe6#"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking d4 square.",
      "White castles to safety.",
      "Black pins the knight, creating pressure.",
      "White attacks f7 and b7 simultaneously.",
      "Black captures the knight, but removes the pin.",
      "Sacrifice to expose the king's position.",
      "King must move to e7, blocking the bishop's escape.",
      "Checkmate! King cannot move and is attacked by queen and bishop."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-08",
    "name": "Qxa4+ and win back pawn",
    "description": "White immediately recaptures the pawn with check and stabilizes.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "bxa4",
      "Qxa4+",
      "Bd7",
      "Qxc4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black tries to hold onto the gambit pawn.",
      "White immediately challenges the advanced pawn.",
      "Black captures, opening the a-file.",
      "Check! White develops queen with tempo, attacking a4 pawn and rook.",
      "Black blocks the check and develops a piece.",
      "White recaptures the gambit pawn, equalizing material with better development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-09",
    "name": "Simplify with Qxf3",
    "description": "Clean line where White eliminates the pin and consolidates.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "Bg4",
      "Bxc4",
      "Bxf3",
      "Qxf3"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black pins the knight, creating pressure.",
      "White recovers the pawn with active development.",
      "Black captures the knight, eliminating the pin but giving up bishop pair.",
      "White recaptures, developing the queen actively and maintaining the bishop pair advantage."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-10",
    "name": "Knight fork with Nc7+",
    "description": "Tactical idea: jump to c7 with check to win material or force concessions.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "b4",
      "Nb5",
      "a6",
      "Bf4",
      "Bb7",
      "Nc7+"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black tries to hold onto the gambit pawn.",
      "White immediately challenges the advanced pawn.",
      "Black defends the pawn.",
      "White captures, opening the a-file.",
      "Black recaptures, maintaining material.",
      "White develops knight, attacking b5 pawn.",
      "Black pushes the pawn to attack the knight.",
      "White jumps to b5, threatening c7 fork.",
      "Black attacks the knight.",
      "White develops bishop with tempo, attacking c7.",
      "Black develops bishop, attacking e4 pawn.",
      "Knight fork! Attacks both king and rook, winning material."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-11",
    "name": "Advance to d6 and squeeze",
    "description": "Space grab with d5 then d6, restricting Black's development.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "Bd7",
      "d5",
      "a6",
      "Nf3",
      "e6",
      "d6",
      "Qb6",
      "e5"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black tries to hold onto the gambit pawn.",
      "White immediately challenges the advanced pawn.",
      "Black defends the pawn.",
      "White captures, opening the a-file.",
      "Black recaptures, maintaining material.",
      "White develops knight, attacking b5 pawn.",
      "Black develops bishop to protect b5.",
      "White advances d-pawn, cramping Black's position.",
      "Black prepares b4 push.",
      "White develops knight to natural square.",
      "Black challenges the advanced d-pawn.",
      "White advances further, creating a powerful passed pawn that restricts Black's pieces.",
      "Black develops queen to attack d6 pawn.",
      "White gains more space and restricts Black's knight development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-12",
    "name": "Develop and regroup with Qb3",
    "description": "Positional line: develop pieces and keep pressure on b7 and c4.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Be6",
      "Nbd2",
      "Nf6",
      "Qb3",
      "Bxc4",
      "Nxc4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking d4 square.",
      "White castles to safety.",
      "Black develops bishop, attacking White's strong bishop.",
      "White develops knight, reinforcing the center.",
      "Black develops knight to natural square.",
      "White attacks f7 and b7 simultaneously.",
      "Black captures the bishop, simplifying.",
      "White recaptures with knight, maintaining pressure on d5 and e5 squares."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-13",
    "name": "Qh3 retreat after sacrifice",
    "description": "White's queen retreats but keeps pressure after tactical exchanges.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "c5",
      "Ne5",
      "Be6",
      "Bxe6",
      "fxe6",
      "Qh5+",
      "g6",
      "Nxg6",
      "Nf6",
      "Qh3"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black challenges White's center further.",
      "White occupies strong central outpost.",
      "Black develops bishop, attacking White's bishop.",
      "White captures, forcing structural weakness.",
      "Black recaptures, creating doubled pawns.",
      "Check! Attacking weak g6 square.",
      "Black blocks, weakening dark squares.",
      "Sacrifice to destroy Black's pawn structure.",
      "Black develops knight, attacking the queen.",
      "White retreats queen to safe square while maintaining pressure on e6 pawn."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-14",
    "name": "Exchange sacrifice on a8 then Ra2",
    "description": "Queenside tactics with rook invasion and follow-up rook repositioning.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "a6",
      "Nxb5",
      "axb5",
      "Rxa8",
      "Bb7",
      "Ra2"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black tries to hold onto the gambit pawn.",
      "White immediately challenges the advanced pawn.",
      "Black defends the pawn.",
      "White captures, opening the a-file.",
      "Black recaptures, maintaining material.",
      "White develops knight, attacking b5 pawn.",
      "Black protects the pawn.",
      "White sacrifices knight for two pawns and initiative.",
      "Black captures, winning material temporarily.",
      "White captures rook, regaining material with interest.",
      "Black develops bishop, attacking the rook.",
      "White retreats rook to safe square, maintaining the extra pawn."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-15",
    "name": "Solid development against Bb4",
    "description": "Accepted pawn line where White develops and castles safely.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e6",
      "Bxc4",
      "Nf6",
      "Nc3",
      "Bb4",
      "e5",
      "Nd5",
      "Ne2",
      "O-O",
      "O-O"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black prepares bishop development.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking e4 pawn.",
      "White develops knight, reinforcing e4 pawn.",
      "Black pins the knight, creating pressure.",
      "White gains space and attacks the knight.",
      "Black retreats knight to central square.",
      "White develops knight to avoid the pin and protect c3.",
      "Black castles to safety.",
      "White castles to safety, completing development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-16",
    "name": "Quiet line: trade and develop",
    "description": "Standard development with Nbd2 and recapture on c4.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Be6",
      "Nbd2",
      "Bxc4",
      "Nxc4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking e5 pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking d4 square.",
      "White castles to safety.",
      "Black develops bishop, attacking White's bishop.",
      "White develops knight, preparing to recapture on c4.",
      "Black captures the bishop, simplifying.",
      "White recaptures with knight, maintaining central control and piece activity."
    ]
  }
];