import { withOpeningFeedback } from "./feedback";

// SEO / page intro text for QGA drills
export const queensGambitAcceptedSEOText = `
The Queen's Gambit Accepted (1. d4 d5 2. c4 dxc4) is not a real gambit—it's a deflection! White offers a "wing pawn" (the c-pawn) to remove Black's only central pawn. 

Black can't actually keep the extra pawn without falling into direct tactical disasters. Your goal as White is to take the full center with e3 or e4 and prove that Black's development is too slow to matter.

These drills cover the core QGA lessons:
- The "Overhold" Trap: Using a4 and Qf3 to win the a8 rook if Black tries to defend the pawn with ...b5 and ...c6.
- Central Dominance: Building the dream pawn duo (d4 and e4) and using active piece play to recover the pawn with interest.
- Practical Punishment: Forcing lines where Black's queen adventures or slow development lead to immediate checkmating attacks.

Don't panic about the pawn. Take the center, finish your development, and the pawn will usually fall back into your lap!
`;

export const queensGambitAcceptedLines = withOpeningFeedback([
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-01",
    "name": "The 'Overhold' Trap: winning the a8 rook",
    "description": "If Black tries to keep the pawn with ...b5 and ...c6, White uses a4 and the powerful Qf3 to trap the rook.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e3",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Qf3"
    ],
    "explanations": [
      "Let's learn the Queen's Gambit Accepted! White starts with the queen's pawn.{{square d4}}",
      "Black meets us in the center.",
      "The Gambit! We offer a wing pawn to deflect Black's central control.",
      "Accepted. Black takes the pawn, but they've given up their stake in the center.",
      "The Rule: play e3 first to open the bishop's path to recovery.",
      "Greed! Black tries to hold onto the extra pawn instead of developing.",
      "The antidote! We attack the base of the pawn chain immediately.",
      "Black doubles down on the defense, creating a very shaky pawn structure.",
      "Trade! We open the a-file by force.",
      "Black recaptures, thinking they've saved the pawn chain.",
      "BOOM! The punchline. The queen jumps to {{square f3}}, attacking the trapped {{rook a8 full}} through the gap in the pawns. White wins major material!"
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-02",
    "name": "Full Center Control: The e4 Blast",
    "description": "White takes the full center immediately and uses the space to launch a direct attack.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4"
    ],
    "explanations": [
      "White claims the center.",
      "Black responds symmetrically.",
      "The Gambit offer.",
      "Accepted. Black accepts the challenge.",
      "The Center Blast! Since the d-pawn is gone, we take the whole center right now.",
      "Black counter-strikes! This is the most aggressive way to challenge White's space.",
      "Develop and attack! We pressure {{square e5}} and keep our development lead.",
      "Black takes more material, but they're opening lines for our army.",
      "Recapture with development! We've won our pawn back and we have a massive lead in development. White is doing great!"
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-03",
    "name": "Punish ...a6 with Rxa8",
    "description": "If Black overholds with ...b5 and ...a6, White can open the a-file and take the rook.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "a6",
      "axb5",
      "axb5",
      "Rxa8"
    ],
    "explanations": [
      "{{square d4}} claims central space and prepares to challenge Black's structure.",
      "Black matches the center for now.",
      "{{square c4}} is the gambit offer and asks Black whether the {{square c4}} pawn is really worth the trouble.",
      "Black accepts, but now every pawn move used to keep {{square c4}} can become a hook for White.",
      "{{square e4}} is the clean QGA reaction. Take the center first and punish the pawn later.",
      "Black tries to hold {{square c4}} with a pawn chain instead of catching up in development.",
      "{{square a4}} is the direct antidote. White attacks the base of that chain immediately.",
      "...{{square a6}} is the mistake the transcript highlights: it seems natural, but it leaves the rook trapped behind the pawn wall.",
      "axb5 forces the a-file open.",
      "Black recaptures and keeps the pawn chain, but now the {{rook a8 full}} is hanging behind it.",
      "Rx{{square a8}} simply wins the rook. Black spent too many moves trying to keep one extra pawn."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-04",
    "name": "Kingside attack and bishop takes f8",
    "description": "White pushes e5 and aims for a quick tactic on f8.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e6",
      "Bxc4",
      "Nf6",
      "Nc3",
      "Be7",
      "e5",
      "Nd5",
      "Qg4",
      "O-O",
      "Bh6",
      "g6",
      "Bxf8"
    ],
    "explanations": [
      "Standard opening move to control center.",
      "Establishes central presence.",
      "Queen's Gambit offer to create play.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black prepares to develop the kingside bishop.",
      "White recovers the pawn with active piece development.",
      "Black develops knight, attacking {{square e4}} pawn.",
      "White develops knight, reinforcing the {{square e4}} pawn.",
      "Black develops bishop, preparing to castle.",
      "White gains space and attacks the {{knight f6 full}}.",
      "Black retreats the knight to a central square.",
      "White's queen targets the weak {{square g7}} pawn and prevents castling.",
      "Black castles kingside despite the pressure.",
      "White develops bishop with tempo, attacking the {{square g7}} pawn.",
      "Black defends {{square g7}} but weakens dark squares around the king.",
      "White captures the bishop, removing a key defender and winning material."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-05",
    "name": "Bxf7 sacrifice and queen takes g4",
    "description": "Accepted pawn, then tactical sequence with a bishop sacrifice to expose the king.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "Bg4",
      "Bxc4",
      "exd4",
      "Bxf7+",
      "Kxf7",
      "Ne5+",
      "Ke8",
      "Qxg4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking {{square e5}} pawn.",
      "Black pins the knight to the queen, creating tactical possibilities.",
      "White recovers the pawn, developing with tempo.",
      "Black captures in the center but opens the e-file.",
      "Greek Gift sacrifice! Destroys Black's pawn shield and exposes the king.",
      "Forced capture, but now the king is exposed in the center.",
      "Knight check, exploiting the exposed king position.",
      "The king must retreat, losing castling rights.",
      "White wins back the bishop, maintaining material advantage with better development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-06",
    "name": "Qb3 pressure and queen side raid",
    "description": "Development with Qb3, then tactical captures on b7 and c6.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Bg4",
      "Qb3",
      "Qd7",
      "Bxf7+",
      "Qxf7",
      "Qxb7",
      "Rd8",
      "Qxc6+"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking {{square e5}} pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking {{square d4}} square.",
      "White castles to safety and connects rooks.",
      "Black pins the knight, creating pressure.",
      "White attacks {{square f7}} and {{square b7}} simultaneously, creating double threats.",
      "Black defends {{square f7}} but blocks the {{square d7}} square.",
      "Sacrifice to expose Black's king and queen position.",
      "Black must capture with the queen, now exposed on {{square f7}}.",
      "White wins a pawn and attacks the {{rook a8 full}}.",
      "Black moves rook to a safer square.",
      "Check! Wins the knight and maintains initiative."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-07",
    "name": "Forcing mate with Qe6#",
    "description": "A direct mating pattern after queen and bishop coordinate on e6.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Bg4",
      "Qb3",
      "Bxf3",
      "Bxf7+",
      "Ke7",
      "Qe6#"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking {{square e5}} pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking {{square d4}} square.",
      "White castles to safety.",
      "Black pins the knight, creating pressure.",
      "White attacks {{square f7}} and {{square b7}} simultaneously.",
      "Black captures the knight, but removes the pin.",
      "Sacrifice to expose the king's position.",
      "King must move to {{square e7}}, blocking the bishop's escape.",
      "Checkmate! King cannot move and is attacked by queen and bishop."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-08",
    "name": "Qxa4+ and clean pawn recovery",
    "description": "When Black grabs on a4, White gets the c4-pawn back with check and finishes the recovery cleanly.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "bxa4",
      "Qxa4+",
      "Bd7",
      "Qxc4"
    ],
    "explanations": [
      "White starts with the queen's pawn and aims for central control.",
      "Black occupies the center.",
      "{{square c4}} offers the gambit and asks Black to justify taking away from the center.",
      "Black accepts and temporarily wins a pawn, but development now matters more than material.",
      "{{square e4}} is again the point: White gets a broad center before spending time on recovery.",
      "Black tries to keep the extra pawn with ...{{square b5}}.",
      "{{square a4}} undermines the queenside chain right away.",
      "Black captures on {{square a4}}, but this opens the queen's path with tempo.",
      "Qx{{square a4}}+ recovers one pawn immediately and checks at the same time, so Black cannot consolidate.",
      "B{{square d7}} is forced to answer the check.",
      "Qx{{square c4}} wins the gambit pawn back. White has the healthier center and cleaner development."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-09",
    "name": "Simplify with Qxf3",
    "description": "Clean line where White eliminates the pin and consolidates.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "Bg4",
      "Bxc4",
      "Bxf3",
      "Qxf3"
    ],
    "explanations": [
      "{{square d4}} claims the center.",
      "Black answers in the center.",
      "{{square c4}} is the gambit offer and challenges {{square d5}} from the side.",
      "Black accepts, so White will answer with fast central play.",
      "{{square e4}} grabs central space before chasing the pawn.",
      "Black strikes back at the center right away.",
      "N{{square f3}} develops and puts pressure on {{square e5}}.",
      "B{{square g4}} pins the knight and tries to use White's {{queen d1 full}} as a target.",
      "Bx{{square c4}} gets the pawn back with development.",
      "Bx{{square f3}} gives up the bishop pair to remove one defender of the center.",
      "Qx{{square f3}} recaptures cleanly. White keeps the center and finishes the opening with easier piece play."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-10",
    "name": "Nc7+ fork after the overhold",
    "description": "If Black keeps pushing the queenside pawns, White can jump into c7 with a fork.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "b4",
      "Nb5",
      "a6",
      "Bf4",
      "Bb7",
      "Nc7+"
    ],
    "explanations": [
      "{{square d4}} claims the center.",
      "Black mirrors it.",
      "{{square c4}} offers the gambit and invites Black to prove the extra pawn is worth the time spent defending it.",
      "Black accepts and steps away from central tension.",
      "{{square e4}} builds the center first, exactly as the transcript recommends.",
      "Black hangs on to {{square c4}} with ...{{square b5}}.",
      "{{square a4}} attacks the base of the chain before Black can settle.",
      "...{{square c6}} reinforces {{square b5}}, but it also locks Black into a pawn-holding scheme.",
      "axb5 opens lines and keeps undermining the queenside structure.",
      "Black recaptures and stays material up for the moment.",
      "N{{square c3}} develops with tempo against {{square b5}} and prepares tactical jumps.",
      "...{{square b4}} looks active, but it gives the knight the exact square it wants.",
      "N{{square b5}} heads for {{square c7}} and takes aim at the weak dark squares and back-rank pieces.",
      "...{{square a6}} tries to chase the knight again, but Black is still playing only pawn moves.",
      "B{{square f4}} adds one more attacker and makes the {{square c7}} fork much harder to stop.",
      "B{{square b7}} develops, but it is too slow against the tactical threat.",
      "N{{square c7}}+ forks king and rook. This is the kind of punishment that happens when Black keeps defending the pawn instead of developing."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-11",
    "name": "d5-d6 squeeze against the overhold",
    "description": "White keeps the center rolling while Black stays tied to the extra pawn.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "Bd7",
      "d5",
      "a6",
      "Nf3",
      "e6",
      "d6",
      "Qb6",
      "e5"
    ],
    "explanations": [
      "{{square d4}} takes central space from move one.",
      "Black matches it.",
      "{{square c4}} is the gambit offer and starts the fight over the center.",
      "Black accepts, which means White should answer with activity, not passive pawn chasing.",
      "{{square e4}} grabs the center while Black still has not developed.",
      "Black keeps trying to hold the pawn with queenside moves.",
      "{{square a4}} attacks the chain immediately.",
      "...{{square c6}} reinforces {{square b5}} but fixes Black into a passive setup.",
      "axb5 opens the a-file and loosens the queenside further.",
      "Black keeps the pawn, but the structure is getting harder and harder to defend.",
      "N{{square c3}} develops with tempo and keeps pressure on {{square b5}}.",
      "B{{square d7}} is a defensive move. Black still has little real development.",
      "{{square d5}} uses the central space advantage. White gains room while Black is busy guarding pawns.",
      "...{{square a6}} prepares another pawn push, but still does not solve the development problem.",
      "N{{square f3}} adds a piece and keeps the center protected.",
      "...{{square e6}} is forced because Black has to fight the advanced d-pawn somehow.",
      "{{square d6}} is the squeeze. The passed pawn cuts across Black's position and keeps several pieces tied down.",
      "Q{{square b6}} attacks the pawn directly because Black has no easy way to challenge it with pieces.",
      "{{square e5}} gains even more space and makes Black's kingside development awkward too."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-12",
    "name": "Develop and regroup with Qb3",
    "description": "Positional line: develop pieces and keep pressure on b7 and c4.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Be6",
      "Nbd2",
      "Nf6",
      "Qb3",
      "Bxc4",
      "Nxc4"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking {{square e5}} pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black develops knight, attacking {{square d4}} square.",
      "White castles to safety.",
      "Black develops bishop, attacking White's strong bishop.",
      "White develops knight, reinforcing the center.",
      "Black develops knight to natural square.",
      "White attacks {{square f7}} and {{square b7}} simultaneously.",
      "Black captures the bishop, simplifying.",
      "White recaptures with knight, maintaining pressure on {{square d5}} and {{square e5}} squares."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-13",
    "name": "Qh3 retreat after sacrifice",
    "description": "White's queen retreats but keeps pressure after tactical exchanges.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "c5",
      "Ne5",
      "Be6",
      "Bxe6",
      "fxe6",
      "Qh5+",
      "g6",
      "Nxg6",
      "Nf6",
      "Qh3"
    ],
    "explanations": [
      "Standard central opening.",
      "Central pawn response.",
      "Queen's Gambit offer.",
      "Accepts the pawn but gives up center control.",
      "White builds a strong pawn center.",
      "Black immediately challenges White's center.",
      "White develops knight, attacking {{square e5}} pawn.",
      "Black captures, opening the center.",
      "White recovers the pawn with active development.",
      "Black challenges White's center further.",
      "White occupies strong central outpost.",
      "Black develops bishop, attacking White's bishop.",
      "White captures, forcing structural weakness.",
      "Black recaptures, creating doubled pawns.",
      "Check! Attacking weak {{square g6}} square.",
      "Black blocks, weakening dark squares.",
      "Sacrifice to destroy Black's pawn structure.",
      "Black develops knight, attacking the queen.",
      "White retreats queen to safe square while maintaining pressure on {{square e6}} pawn."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-14",
    "name": "Exchange sac on a8 with rook escape",
    "description": "White uses the open a-file to take the rook, then keeps the rook active.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Nc3",
      "a6",
      "Nxb5",
      "axb5",
      "Rxa8",
      "Bb7",
      "Ra2"
    ],
    "explanations": [
      "White starts with central space.",
      "Black matches the center.",
      "{{square c4}} is the gambit offer and asks Black to prove the extra pawn is safe.",
      "Black accepts and gives White a target on the queenside.",
      "{{square e4}} follows the transcript's plan: claim the center before worrying about recovery.",
      "Black tries to keep {{square c4}} with another queenside pawn move.",
      "{{square a4}} hits the base of the chain at once.",
      "...{{square c6}} looks like a tidy defense, but it traps the {{rook a8 full}} behind its own pawns.",
      "axb5 opens the a-file by force.",
      "Black recaptures and keeps the pawn chain for one move longer.",
      "N{{square c3}} develops with tempo and keeps pressure on {{square b5}}.",
      "...{{square a6}} defends {{square b5}}, but now the tactical cost is bigger than the pawn gain.",
      "Nx{{square b5}} removes the key defender and clears the a-file further.",
      "Black has to take the knight or lose the pawn chain completely.",
      "Rx{{square a8}} wins the rook. White gives up a knight but gets major material and keeps the initiative.",
      "B{{square b7}} attacks the rook and tries to use the open diagonal.",
      "R{{square a2}} keeps the rook alive and ready to swing across if needed."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-15",
    "name": "Strong center against ...Bb4",
    "description": "White gets the pawn back, keeps the center, and completes development against the pin.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e6",
      "Bxc4",
      "Nf6",
      "Nc3",
      "Bb4",
      "e5",
      "Nd5",
      "Ne2",
      "O-O",
      "O-O"
    ],
    "explanations": [
      "{{square d4}} claims space in the center.",
      "Black answers in kind.",
      "{{square c4}} offers the gambit and asks Black to decide between central stability and extra material.",
      "Black accepts, so White should answer with central play.",
      "{{square e4}} is the main mission after the accepted gambit: take the center and make Black prove the pawn matters.",
      "Black prepares to develop while still hoping White's center can be challenged later.",
      "Bx{{square c4}} calmly wins the pawn back with development.",
      "Black hits {{square e4}} and asks White to justify the center.",
      "N{{square c3}} reinforces {{square e4}} and develops with tempo.",
      "B{{square b4}} adds a pin, but Black still has not solved White's central space.",
      "{{square e5}} gains more room and kicks the knight away from the center.",
      "N{{square d5}} is the best square, but the knight can still become a future target.",
      "N{{square e2}} breaks the pin cleanly and keeps {{square c3}} and {{square e4}} protected.",
      "Black castles and finally gets the king safe.",
      "White castles too. The center is still White's main asset, which is the exact payoff the transcript emphasizes after QGA."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-16",
    "name": "Quiet line: trade and develop",
    "description": "Standard development with Nbd2 and recapture on c4.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e4",
      "e5",
      "Nf3",
      "exd4",
      "Bxc4",
      "Nc6",
      "O-O",
      "Be6",
      "Nbd2",
      "Bxc4",
      "Nxc4"
    ],
    "explanations": [
      "{{square d4}} claims central space.",
      "Black answers in the center.",
      "{{square c4}} offers the gambit and asks Black to justify taking away from the center.",
      "Black accepts, so White answers by taking space, not by panicking over the pawn.",
      "{{square e4}} builds the broad center that the transcript emphasizes.",
      "Black challenges it immediately.",
      "N{{square f3}} develops while attacking {{square e5}}.",
      "Black captures in the center to reduce White's pawn mass.",
      "Bx{{square c4}} recovers the gambit pawn with a piece, not another pawn move.",
      "N{{square c6}} develops and pressures {{square d4}}.",
      "White castles and keeps development smooth.",
      "B{{square e6}} questions the active bishop.",
      "Nbd2 adds support and keeps recapture options ready.",
      "Black trades the bishop to simplify.",
      "Nx{{square c4}} restores the balance with active pieces and a healthy center."
    ]
  },
  {
    "category": "Queen's Gambit Accepted",
    "id": "queens-gambit-accepted-17",
    "name": "Simple punish with Ra3",
    "description": "If Black overholds with ...b5 and ...c6, the rook lift is a clean practical punishment.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "dxc4",
      "e3",
      "b5",
      "a4",
      "c6",
      "axb5",
      "cxb5",
      "Ra3"
    ],
    "explanations": [
      "{{square d4}} starts the fight for the center.",
      "Black occupies central space.",
      "{{square c4}} challenges the {{square d5}} pawn from the side and invites Black to either defend or accept the pawn.",
      "Black accepts and gives White a queenside target.",
      "{{square e3}} is the simpler recovery setup. White frees the bishop and keeps development easy.",
      "Black tries to hang on to the extra pawn with a broad pawn chain.",
      "{{square a4}} undermines the chain before Black can finish development.",
      "...{{square c6}} looks safe, but it leaves the rook boxed in behind the pawn wall.",
      "axb5 opens the file White wanted.",
      "Black recaptures and still clings to the extra pawn.",
      "R{{square a3}} is the practical rook lift from the transcript's theme. The rook attacks {{square a8}} directly and Black's pawn-holding plan falls apart."
    ]
  }
]
);
