export const queensGambitDeclinedLines = [
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-01",
    "name": "Ragozin style with Bb4 and tactical shot",
    "description": "Bb4 pin and a forcing sequence that includes a sacrifice idea on h7.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Bb4",
      "e3",
      "Nf6",
      "a3",
      "Bxc3+",
      "bxc3",
      "O-O",
      "cxd5",
      "Nxd5",
      "Bd3",
      "Nxc3",
      "Qc2",
      "Nd5",
      "Bxh7+",
      "Kh8",
      "Bd3"
    ],
    "explanations": [
      "Establishes central control and opens lines.",
      "Solid central response, declining the gambit.",
      "Queen's Gambit offer to challenge Black's center.",
      "Prepares bishop development while maintaining central tension.",
      "Develops knight, increasing control over central squares.",
      "Ragozin Defense: pins the knight, creating immediate pressure.",
      "Reinforces the center and prepares bishop development.",
      "Develops knight, attacking the c4 pawn indirectly.",
      "Forces Black to decide about the bishop on b4.",
      "Black gives up the bishop pair but doubles White's pawns.",
      "White gets the bishop pair but has doubled c-pawns.",
      "Black secures the king and connects rooks.",
      "White resolves central tension, opening the c-file.",
      "Black recaptures with the knight, maintaining piece activity.",
      "White develops bishop actively, eyeing the h7 square.",
      "Black captures the pawn but removes a defender from the kingside.",
      "White develops queen with tempo, attacking the knight.",
      "Black retreats the knight, but it's now overloaded.",
      "Greek Gift sacrifice! Standard attack against castled king.",
      "Forced: King moves to h8 to avoid checkmate threats.",
      "White retreats bishop, maintaining the attack with threats like Qh7#."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-02",
    "name": "Tarrasch structure, early simplification",
    "description": "Tarrasch type structure where White wins a central pawn after exchanges.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c5",
      "cxd5",
      "exd5",
      "Nf3",
      "Nc6",
      "dxc5",
      "Bxc5",
      "Qxd5",
      "Qxd5",
      "Nxd5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development while maintaining structure.",
      "Develops knight to control central squares.",
      "Tarrasch Defense: immediately challenges White's center.",
      "White exchanges to create an isolated queen's pawn for Black.",
      "Black must recapture with the pawn, creating an isolated d-pawn.",
      "White develops knight, increasing pressure on d5.",
      "Black develops knight, defending the d5 pawn indirectly.",
      "White captures, forcing Black to recapture and giving White a central pawn majority.",
      "Black recaptures with the bishop, developing a piece.",
      "White immediately attacks the isolated d5 pawn.",
      "Black exchanges queens to simplify the position.",
      "White recaptures with the knight, gaining a central outpost."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-03",
    "name": "Semi-Slav: aggressive queen sortie",
    "description": "Semi-Slav structure with space and early queen pressure.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "Nf6",
      "cxd5",
      "cxd5",
      "e5",
      "Nfd7",
      "Qg4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports d5 pawn and prepares ...b5.",
      "White strikes in the center, claiming more space.",
      "Black develops knight, attacking e4 pawn.",
      "White exchanges to open the center.",
      "Black recaptures, maintaining central pawn.",
      "White gains space and attacks the knight.",
      "Black retreats knight, preparing ...Nc6 or ...Nb6.",
      "White attacks g7 pawn, creating immediate kingside pressure."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-04",
    "name": "Exchange QGD: win a pawn with Qxd5",
    "description": "Exchange variation with Bg5 and queen picks up d5 after tactical details.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "b6",
      "Bxf6",
      "Bxf6",
      "Qh5",
      "g6",
      "Qxd5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black prepares to develop bishop to b7.",
      "White captures, removing defender of d5 pawn.",
      "Black recaptures, developing the bishop.",
      "White attacks the weak h7 square.",
      "Black defends but weakens dark squares.",
      "White captures the undefended d5 pawn, winning material."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-05",
    "name": "Main Exchange QGD plan with f3 and e4",
    "description": "Develop, regroup, then break the center with f3 and e4.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "Ndf6",
      "f3",
      "Nd6",
      "e4",
      "dxe4",
      "fxe4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the d5 pawn.",
      "White develops queen to support e4 break.",
      "Black attacks the bishop.",
      "White retreats bishop, maintaining the pin.",
      "Black develops knight, preparing ...Ne4.",
      "White develops knight, preparing f3 and e4.",
      "Black activates rook on semi-open file.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black repositions knight.",
      "White prepares e4 break by supporting the pawn.",
      "Black retreats knight.",
      "White executes central break.",
      "Black captures, opening the center.",
      "White recaptures, gaining central space and activity."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-06",
    "name": "Semi-Slav: push e5",
    "description": "Semi-Slav structure where White gains space with e5.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "Nf6",
      "cxd5",
      "exd5",
      "e5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports d5 pawn.",
      "White strikes in the center, claiming more space.",
      "Black develops knight, attacking e4 pawn.",
      "White exchanges to open the center.",
      "Black recaptures, maintaining central pawn.",
      "White gains space, attacks the knight, and restricts Black's pieces."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-07",
    "name": "Exchange QGD: Nf4 plan",
    "description": "Standard exchange structure with a kingside plan and piece maneuver.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "h6",
      "Bh4",
      "c6",
      "Nge2",
      "Bg4",
      "f3",
      "Bh5",
      "Nf4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black attacks the bishop.",
      "White retreats bishop, maintaining the pin.",
      "Black supports the d5 pawn.",
      "White develops knight, preparing kingside plans.",
      "Black pins the knight.",
      "White breaks the pin and gains space.",
      "Black retreats bishop.",
      "White maneuvers knight to attack weak d5 and h5 squares."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-08",
    "name": "Ragozin: Ba3 idea",
    "description": "Ba3 targets the queenside and pressures the diagonal.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Bb4",
      "e3",
      "Bxc3+",
      "bxc3",
      "Nf6",
      "Ba3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Ragozin Defense: pins the knight.",
      "Reinforces the center and prepares bishop development.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black develops knight.",
      "White develops bishop to target Black's weak queenside pawns and control long diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-09",
    "name": "Exchange QGD: dxc5 break",
    "description": "Long plan that ends with dxc5 to open queenside lines.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Nf8",
      "f3",
      "Ne6",
      "Rad1",
      "c5",
      "dxc5"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the d5 pawn.",
      "White develops queen to support e4 break.",
      "Black attacks the bishop.",
      "White retreats bishop, maintaining the pin.",
      "Black develops knight, preparing ...Ne4.",
      "White develops knight, preparing f3 and e4.",
      "Black activates rook on semi-open file.",
      "White castles to safety.",
      "Black repositions knight for kingside defense.",
      "White prepares e4 break.",
      "Black develops knight to active square.",
      "White activates rook on d-file.",
      "Black challenges White's center.",
      "White captures, opening the center and gaining pawn majority."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-10",
    "name": "QGD with ...dxc4, immediate e4",
    "description": "Black takes on c4, White responds by building a strong pawn center.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "dxc4",
      "e4"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Black accepts the gambit in QGD structure.",
      "White immediately builds strong pawn center, compensating for the pawn."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-11",
    "name": "Exchange QGD: f5 and recapture",
    "description": "Line featuring ...f5 and a clean Nxc3 recapture.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "f5",
      "f3",
      "Nxc3",
      "Nxc3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the d5 pawn.",
      "White develops queen to support e4 break.",
      "Black attacks the bishop.",
      "White retreats bishop, maintaining the pin.",
      "Black develops knight, preparing ...Ne4.",
      "White develops knight, preparing f3 and e4.",
      "Black activates rook on semi-open file.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black gains kingside space but weakens e5 square.",
      "White attacks the knight and prepares e4.",
      "Black captures knight to relieve pressure.",
      "White recaptures, maintaining central control."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-12",
    "name": "Exchange QGD: c5 and dxc5",
    "description": "Black strikes with ...c5, White takes on c5 to win time.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c5",
      "dxc5",
      "Bxc5",
      "Nge2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White captures, gaining pawn majority and opening position.",
      "Black recaptures, developing bishop.",
      "White develops knight, preparing to attack weak d5 pawn."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-13",
    "name": "QGD Exchange: Carlsbad style build-up",
    "description": "Build up, then develop Bb2 in a Carlsbad-type structure.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "Nxd5",
      "e4",
      "Nxc3",
      "bxc3",
      "Be7",
      "Nf3",
      "O-O",
      "Bd3",
      "c5",
      "O-O",
      "cxd4",
      "cxd4",
      "Nc6",
      "Bb2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures with knight instead of pawn.",
      "White gains space in the center.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black develops bishop, preparing to castle.",
      "White develops knight to natural square.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White castles to safety.",
      "Black captures, opening the center.",
      "White recaptures, maintaining central pawn.",
      "Black develops knight, attacking d4 pawn.",
      "White develops bishop to target Black's kingside and control long diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-14",
    "name": "Semi-Slav: sharp line with check",
    "description": "Semi-Slav structure with Bb4+ and forcing exchanges.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "dxe4",
      "Nxe4",
      "Nf6",
      "Nxf6+",
      "Qxf6",
      "Nf3",
      "Bb4+",
      "Bd2",
      "Bxd2+",
      "Qxd2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports d5 pawn.",
      "White strikes in the center.",
      "Black captures, accepting the pawn.",
      "White recaptures with knight.",
      "Black attacks the knight.",
      "White captures, forcing queen recapture.",
      "Black recaptures with queen.",
      "White develops knight to natural square.",
      "Check! Black develops bishop with tempo.",
      "White blocks the check and develops bishop.",
      "Check! Black exchanges bishops.",
      "White recaptures, developing queen actively."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-15",
    "name": "Semi-Slav: queen grab and tactics",
    "description": "Tactical line with early queen grabs and checks.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c6",
      "e4",
      "dxe4",
      "Nxe4",
      "Bb4+",
      "Bd2",
      "Qxd4",
      "Bxb4",
      "Qxe4+",
      "Be2",
      "Qxg2",
      "Bf3",
      "Qg5",
      "Ne2"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Semi-Slav Defense: supports d5 pawn.",
      "White strikes in the center.",
      "Black captures, accepting the pawn.",
      "White recaptures with knight.",
      "Check! Black develops bishop with tempo.",
      "White blocks the check and develops bishop.",
      "Black captures central pawn with queen.",
      "White captures bishop, attacking the queen.",
      "Check! Black saves queen and attacks bishop.",
      "White blocks the check and develops bishop.",
      "Black captures pawn and attacks rook.",
      "White defends rook and attacks queen.",
      "Black moves queen to safer square.",
      "White develops knight, preparing to attack exposed queen."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-16",
    "name": "Tarrasch: Qa4+ and regain",
    "description": "Queen check then regain central material with tempo.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c5",
      "cxd5",
      "cxd4",
      "Qa4+",
      "Bd7",
      "Qxd4",
      "exd5",
      "Qxd5",
      "Nf6",
      "Qb3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Tarrasch Defense: immediately challenges center.",
      "White exchanges to open position.",
      "Black captures pawn with pawn.",
      "Check! White develops queen with tempo, attacking a7.",
      "Black blocks check and develops bishop.",
      "White captures pawn, regaining material.",
      "Black recaptures pawn.",
      "White captures pawn, equalizing material.",
      "Black develops knight, attacking queen.",
      "White retreats queen to active square, maintaining pressure on b7 and d5."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-17",
    "name": "Tarrasch: isolate pressure and Rc1",
    "description": "Tactical sequence and rook activation with Rc1.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "c5",
      "cxd5",
      "exd5",
      "Nf3",
      "Nc6",
      "dxc5",
      "d4",
      "Na4",
      "Bxc5",
      "Nxc5",
      "Qa5+",
      "Bd2",
      "Qxc5",
      "Rc1"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Tarrasch Defense: immediately challenges center.",
      "White exchanges to isolate Black's d-pawn.",
      "Black recaptures, creating isolated pawn.",
      "White develops knight to natural square.",
      "Black develops knight, attacking d4 square.",
      "White captures, gaining pawn.",
      "Black advances pawn, gaining space.",
      "White moves knight to attack bishop.",
      "Black captures pawn, developing bishop.",
      "White captures bishop, gaining material.",
      "Check! Black attacks knight with queen.",
      "White blocks check and develops bishop.",
      "Black captures knight, regaining material.",
      "White activates rook on semi-open file, attacking queen."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-18",
    "name": "QGD Exchange: long mainline with b6",
    "description": "Long exchange mainline with queenside development and activity.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "Nxd5",
      "e4",
      "Nxc3",
      "bxc3",
      "c5",
      "Nf3",
      "cxd4",
      "cxd4",
      "Bb4+",
      "Bd2",
      "Bxd2+",
      "Qxd2",
      "O-O",
      "Bc4",
      "Nd7",
      "O-O",
      "b6",
      "Rfe1",
      "Bb7",
      "Rad1",
      "Rc8",
      "Bb3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures with knight.",
      "White gains space in center.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black challenges White's center.",
      "White develops knight to natural square.",
      "Black captures, opening the center.",
      "White recaptures, maintaining central pawn.",
      "Check! Black develops bishop with tempo.",
      "White blocks check and develops bishop.",
      "Check! Black exchanges bishops.",
      "White recaptures, developing queen.",
      "White castles to safety.",
      "White develops bishop to active square.",
      "Black develops knight, preparing ...b6.",
      "Black castles to safety.",
      "Black prepares bishop development.",
      "White activates rook on e-file.",
      "Black develops bishop to long diagonal.",
      "White activates rook on d-file.",
      "Black activates rook on semi-open file.",
      "White retreats bishop to maintain pressure on a2-g8 diagonal."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-19",
    "name": "Ragozin: quiet buildup",
    "description": "Bb4 pin, then quiet development into a playable middlegame.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Bb4",
      "e3",
      "Nf6",
      "a3",
      "Bxc3+",
      "bxc3",
      "O-O",
      "cxd5",
      "exd5",
      "Bd3",
      "c5",
      "Ne2",
      "Nc6",
      "O-O"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Ragozin Defense: pins the knight.",
      "Reinforces the center and prepares bishop development.",
      "Black develops knight.",
      "White forces bishop decision.",
      "Black captures, doubling White's pawns.",
      "White recaptures, opening b-file.",
      "Black castles to safety.",
      "White exchanges to open position.",
      "Black recaptures, maintaining isolated pawn.",
      "White develops bishop to active diagonal.",
      "Black challenges White's center.",
      "White develops knight, avoiding pawn attacks.",
      "Black develops knight, attacking d4 pawn.",
      "White castles to safety, completing development."
    ]
  },
  {
    "category": "Queen's Gambit Declined",
    "id": "queens-gambit-declined-20",
    "name": "Exchange QGD: standard mainline",
    "description": "Standard exchange mainline through f3 and Nxc3, good for drilling move order.",
    "moves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "cxd5",
      "exd5",
      "Bg5",
      "Be7",
      "e3",
      "O-O",
      "Bd3",
      "c6",
      "Qc2",
      "h6",
      "Bh4",
      "Nbd7",
      "Nge2",
      "Re8",
      "O-O",
      "Ne4",
      "Bxe7",
      "Qxe7",
      "Rae1",
      "Ndf6",
      "f3",
      "Nxc3",
      "Nxc3"
    ],
    "explanations": [
      "Standard central opening.",
      "Solid central response.",
      "Queen's Gambit offer.",
      "Prepares bishop development.",
      "Develops knight to control central squares.",
      "Develops knight to natural square.",
      "Exchange variation: simplifies the center.",
      "Black recaptures, maintaining central pawn.",
      "White pins the knight, creating pressure.",
      "Black develops bishop, breaking the pin.",
      "Reinforces the center and prepares bishop development.",
      "Black castles to safety.",
      "White develops bishop to active diagonal.",
      "Black supports the d5 pawn.",
      "White develops queen to support e4 break.",
      "Black attacks the bishop.",
      "White retreats bishop, maintaining the pin.",
      "Black develops knight, preparing ...Ne4.",
      "White develops knight, preparing f3 and e4.",
      "Black activates rook on semi-open file.",
      "White castles to safety.",
      "Black occupies central outpost.",
      "White exchanges bishops to relieve pressure.",
      "Black recaptures with queen.",
      "White activates rook on e-file.",
      "Black repositions knight.",
      "White attacks knight and prepares e4 break.",
      "Black captures knight to relieve pressure.",
      "White recaptures, maintaining central control and piece activity."
    ]
  }
];