export const scotchGameLines = [
  {
    "category": "Scotch Game",
    "id": "scotch-01",
    "name": "Classical Scotch Main Line",
    "description": "Standard Scotch with bishop exchange",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Nf6", "Nxc6", "bxc6", "Bxc5"],
    "explanations": [
      "Let's learn the scotch game! This opening literally just feels like a cheat code - it's so easy to get a winning position in just a few moves, and ALL of black's most common responses, especially at <2000 ELO, will make them lose on the spot. We begin with pawn to e4.",
      "Black responds with e5, establishing the classical center.",
      "We develop the knight to f3, attacking the e5 pawn and developing a piece.",
      "Black develops the knight to c6, defending the e5 pawn.",
      "We immediately strike in the center with d4, opening lines and challenging Black's position.",
      "Black captures on d4, accepting the exchange.",
      "We recapture with the knight, centralizing a piece.",
      "Black develops the bishop to c5, attacking our knight and controlling the center.",
      "We develop the bishop to e3, defending the knight and preparing queenside castling.",
      "Black develops the knight to f6, attacking e4 and preparing kingside castling.",
      "We capture on c6, damaging Black's pawn structure.",
      "Black recaptures with the b-pawn, creating doubled pawns but opening the b-file.",
      "We capture the bishop, winning the bishop pair and maintaining a strong position."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-02",
    "name": "Scotch Four Knights Variation",
    "description": "Queen exchange line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "c5", "Qe3", "Nf6", "e5"],
    "explanations": [
      "We open with e4, establishing central control.",
      "Black responds with e5, mirroring our central pawn.",
      "We develop the knight to f3, attacking e5.",
      "Black defends with Nc6.",
      "We strike immediately with d4, opening the center.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight, simplifying the position.",
      "We recapture with the queen, centralizing it but potentially exposing it.",
      "Black attacks our queen with c5, gaining tempo.",
      "We move the queen to e3, maintaining central presence.",
      "Black develops the knight to f6.",
      "We push e5, attacking the knight and gaining space."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-03",
    "name": "Göring Gambit Declined",
    "description": "Tactical line with knight win",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "Nf6", "dxe5", "Nxe4", "Bc4", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    "explanations": [
      "We begin with e4, establishing the center.",
      "Black responds with e5.",
      "We develop Nf3, attacking e5.",
      "Black develops Nc6.",
      "We play d4, challenging the center.",
      "Black develops Nf6 instead of capturing on d4.",
      "We capture on e5.",
      "Black captures on e4 with the knight.",
      "We develop the bishop to c4, attacking f7.",
      "Black develops Bc5.",
      "We attack with Qd5, threatening multiple pieces.",
      "Black checks with Bxf2+.",
      "We move the king to f1.",
      "Black castles.",
      "After the final move - Nice! We have an extra knight. By capturing on e4, we regain our pawn and maintain material advantage."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-04",
    "name": "Scotch with d6 Defense",
    "description": "Against passive d6 setup",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "d6", "d5", "Nd4", "Nxd4", "exd4", "Qxd4"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black plays Nc6.",
      "We strike with d4.",
      "Black plays d6, a more passive defense.",
      "We push d5, gaining space.",
      "Black moves the knight to d4.",
      "We capture the knight.",
      "Black recaptures with the pawn.",
      "We capture with the queen, centralizing it."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-05",
    "name": "Complex Tactical Line",
    "description": "Long tactical sequence",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Qf6", "Nb5", "Bc5", "Qe2", "Bb6", "N1c3", "a6", "Nd5", "Qd8", "Nxb6", "cxb6", "Nd6+", "Kf8", "Bf4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4, opening the center.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops the queen to f6, attacking our knight.",
      "We move the knight to b5, threatening c7.",
      "Black develops Bc5.",
      "We develop the queen to e2, preparing castling.",
      "Black retreats the bishop to b6.",
      "We develop the other knight to c3.",
      "Black plays a6, attacking our knight.",
      "We move the knight to d5, centralizing.",
      "Black retreats the queen to d8.",
      "We capture the bishop on b6.",
      "Black recaptures with the c-pawn.",
      "We check with Nd6+.",
      "Black moves the king to f8.",
      "After the final move - Wow. The material is equal but we will win from here 100% of the time. Our knight is just too good. We'll castle now, develop our last pieces, and then launch a huge attack on black's weak position. By developing Bf4, we increase pressure on the weakened dark squares."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-06",
    "name": "Scotch Gambit Accepted",
    "description": "Aggressive attacking line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "d6", "Nc3", "Nf6", "Bg5", "Be7", "O-O-O", "O-O", "e5", "dxe5", "Qxe5", "Qe8", "Qxc7", "Be6", "Bb5", "Qc8", "Qxe7"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin the knight with Bg5.",
      "Black develops Be7.",
      "We castle queenside.",
      "Black castles kingside.",
      "We push e5.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves the queen to e8.",
      "We capture on c7.",
      "Black develops Be6.",
      "We develop Bb5.",
      "Black moves the queen to c8.",
      "After the final move -  Knight will be coming to c7. Knight will win a rook. GG. By capturing on e7, we win material and maintain a crushing position."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-07",
    "name": "Kingside Attack Variation",
    "description": "Sacrificial attack line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "bxc6", "Bd3", "Bc5", "e5", "Qe7", "O-O", "Nd5", "Nd2", "O-O", "Ne4", "Bb6", "c4", "Nb4", "Nf6+", "gxf6", "Bxh7+", "Kxh7", "Qh5+", "Kg8", "Qg4+", "Kh7", "Qh4+", "Kg8", "Bh6", "Qxe5", "Qh7+", "Kf8", "Qh8+", "Ke7", "Qxg7+", "Kd6", "Qxf6+", "Kc5", "Qxe5"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We develop Bd3.",
      "Black develops Bc5.",
      "We push e5.",
      "Black develops Qe7.",
      "We castle kingside.",
      "Black moves the knight to d5.",
      "We develop Nd2.",
      "Black castles.",
      "We move the knight to e4.",
      "Black retreats the bishop to b6.",
      "We push c4.",
      "Black moves the knight to b4.",
      "We sacrifice with Nf6+.",
      "Black captures with g-pawn.",
      "We sacrifice the bishop with Bxh7+.",
      "Black captures with the king.",
      "We check with Qh5+.",
      "Black moves the king to g8.",
      "We check with Qg4+.",
      "Black moves the king to h7.",
      "We check with Qh4+.",
      "Black moves the king to g8.",
      "We develop Bh6.",
      "Black captures on e5.",
      "After the final move - Nice job winning a queen! The attack continues with mate threats."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-08",
    "name": "Pressure on c7 Square",
    "description": "Knight domination line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Ng8", "Nc3", "d6", "Bf4", "dxe5", "Qxe5+", "Qe7", "Nb5", "Qxe5+", "Bxe5"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures on e5.",
      "We check with Qxe5+.",
      "Black blocks with Qe7.",
      "We move the knight to b5.",
      "Black captures our queen.",
      "After the final move - Knight will be coming to c7. Knight will win a rook. GG. By recapturing with the bishop, we maintain a dominating position."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-09",
    "name": "C7 Square Pressure Line",
    "description": "Similar to previous with Be7",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Ng8", "Nc3", "d6", "Bf4", "dxe5", "Qxe5+", "Be7", "Nb5"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures on e5.",
      "We check with Qxe5+.",
      "Black blocks with Be7.",
      "After the final move - It's over. We just have too much pressure on the c7 square. There's a bunch of ways black COULD respond here, but none of them are good. By moving Nb5, we threaten the vulnerable c7 square."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-10",
    "name": "Rook Win Variation",
    "description": "Winning material line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Qe7", "Be3", "Ng8", "Nc3", "d6", "Nd5", "Qd7", "exd6", "Bxd6", "Qxg7"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We move the knight to d5.",
      "Black moves the queen to d7.",
      "We capture on d6.",
      "Black recaptures with the bishop.",
      "After the final move - It's over. We're winning a rook and probably a few other pieces too. By capturing on g7, we attack the rook and win material."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-11",
    "name": "Material Advantage Line",
    "description": "Winning two pawns",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "d6", "Nc3", "Nf6", "Bg5", "Be7", "O-O-O", "O-O", "e5", "dxe5", "Qxe5", "Qe8", "Qxc7", "Be6", "Bb5", "Rc8", "Qxb7", "Rb8", "Bxe8", "Rxb7", "Ba4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin with Bg5.",
      "Black develops Be7.",
      "We castle queenside.",
      "Black castles kingside.",
      "We push e5.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves the queen to e8.",
      "We capture on c7.",
      "Black develops Be6.",
      "We develop Bb5.",
      "Black moves the rook to c8.",
      "We capture on b7.",
      "Black moves the rook to b8.",
      "We capture the queen.",
      "Black captures our queen.",
      "After the final move - Nice! We made out like bandits and are now up two pawns! By retreating the bishop to a4, we save it and maintain our material advantage."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-12",
    "name": "Positional Advantage Line",
    "description": "Comfortable position with advantage",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Nxd4", "Bxd4", "Bxd4", "Qxd4", "Qf6", "e5", "Qb6", "Qxb6", "axb6", "Nc3", "Ne7", "O-O-O", "O-O", "Bc4"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black captures our knight.",
      "We recapture with the bishop.",
      "Black captures our bishop.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to b6.",
      "We exchange queens.",
      "Black recaptures with a-pawn.",
      "We develop Nc3.",
      "Black develops Ne7.",
      "We castle queenside.",
      "Black castles kingside.",
      "After the final move - Nice! We have a very comfortable position. It'll be up to you to convert our 1.5 point advantage into a win. By developing Bc4, we complete our development with a strong bishop."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-13",
    "name": "Development Advantage Line",
    "description": "Better development and king safety",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Qf6", "e5", "Qe6", "Bc4", "Qg6", "Nc3", "Qxg2", "Bd5", "Qg6", "Bd2"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to e6.",
      "We develop Bc4.",
      "Black moves the queen to g6.",
      "We develop Nc3.",
      "Black captures on g2.",
      "We develop Bd5.",
      "Black retreats the queen to g6.",
      "After the final move - Even though material is equal, this game is not even close. Our development is so much better, and our king is about to be so much safer. By developing Bd2, we complete our development and prepare to castle."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-14",
    "name": "Crushing Advantage Line",
    "description": "+5 advantage position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Qe7", "Be3", "Ng8", "Nc3", "d6", "Nd5", "Qd7", "exd6", "Qxd6", "Bf4", "Qe6+", "Be2"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We move the knight to d5.",
      "Black moves the queen to d7.",
      "We capture on d6.",
      "Black recaptures with the queen.",
      "We develop Bf4.",
      "Black checks with the queen.",
      "After the final move - Well done! The material is equal but we will literally win this game 100% of the time. Our pieces are just so good, and the computer gives us a +5 point advantage. By blocking with Be2, we develop a piece and prepare to castle."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-15",
    "name": "Attacking Line with Qf4",
    "description": "+2 advantage position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Qf6", "e5", "Qe6", "Bc4", "Qb6", "Qf4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to e6.",
      "We develop Bc4.",
      "Black moves the queen to b6.",
      "After the final move - Well done! Black will scramble to stop our attack, and in the meantime we'll castle and keep developing our pieces. The computer has at a +2 point advantage. By moving Qf4, we maintain pressure and prepare to develop our pieces."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-16",
    "name": "Space Advantage Line",
    "description": "+1 advantage with space",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "d6", "d5", "Nce7", "c4", "Nf6", "Nc3"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black plays d6.",
      "We push d5.",
      "Black retreats the knight to e7.",
      "We play c4.",
      "Black develops Nf6.",
      "After the final move - Well done! We have so much space - giving us a +1 point advantage. By developing Nc3, we complete our knight development and control the center."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-17",
    "name": "Terrifying Position Line",
    "description": "Strong attacking setup",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "bxc6", "Bd3", "Bc5", "e5", "Nd5", "Qg4", "g6", "Bh6", "d6", "Qa4", "Bd7", "O-O"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We develop Bd3.",
      "Black develops Bc5.",
      "We push e5.",
      "Black moves the knight to d5.",
      "We develop Qg4.",
      "Black plays g6.",
      "We develop Bh6.",
      "Black plays d6.",
      "We move the queen to a4.",
      "Black develops Bd7.",
      "After the final move - Well done! Our position is just terrifying for black. By castling, we secure our king and prepare for the attack."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-18",
    "name": "Endgame Advantage Line",
    "description": "Better endgame prospects",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "dxc6", "Qxd8+", "Kxd8", "f3"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with d-pawn.",
      "We exchange queens.",
      "Black captures with the king.",
      "After the final move - Well done! We will develop and castle - something our opponent no longer has the ability to do. By playing f3, we support the center and prepare development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-19",
    "name": "Central Control Line",
    "description": "+1 advantage with center control",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "O-O", "O-O", "Ne5", "Be2", "d5", "f4", "Nc4", "Bxc4", "dxc4", "Nd2"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d5.",
      "We push f4.",
      "Black moves the knight to c4.",
      "We capture the knight.",
      "Black recaptures with the pawn.",
      "After the final move - Well done! We own the center and have more development and a better pawn structure. The computer gives us a +1 point advantage. By developing Nd2, we reposition the knight and maintain control."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-20",
    "name": "Queen Exchange Line",
    "description": "Simple center control",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Qf6", "e5", "Qb6", "Be3", "Qxd4", "Bxd4"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to b6.",
      "We develop Be3.",
      "Black captures our queen.",
      "After the final move - Well done! We simply own the center now. By recapturing with the bishop, we maintain a strong centralized piece."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-21",
    "name": "Pawn Push Advantage",
    "description": "Edge with f4 push",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "O-O", "O-O", "Ne5", "Be2", "d6", "f4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d6.",
      "After the final move - Well done! That pawn push is giving us an edge of the opponent. By pushing f4, we gain space and attack the knight."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-22",
    "name": "High Win Rate Line",
    "description": "70%+ win rate from position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "Ne5", "Be2", "d5", "O-O", "dxe4", "Nb5", "Bd6", "Bc5", "O-O", "Nxd6", "cxd6", "Qxd6", "Qxd6", "Bxd6"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d5.",
      "We castle.",
      "Black captures on e4.",
      "We move the knight to b5.",
      "Black retreats the bishop to d6.",
      "We develop Bc5.",
      "Black castles.",
      "We capture on d6.",
      "Black recaptures with c-pawn.",
      "We capture on d6 with queen.",
      "Black captures our queen.",
      "After the final move - Well done! We win over 70% of the time from here. By capturing the bishop, we maintain material equality with better prospects."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-23",
    "name": "Standard Development Line",
    "description": "Ready to play position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "d6", "O-O"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black plays d6.",
      "After the final move - Well done! We are ready to play some chess. By castling, we secure our king and complete development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-24",
    "name": "Bishop Attack Line",
    "description": "Attacking the bishop",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Qf6", "Nb5", "Bc5", "Qe2", "Bb6", "N1c3", "Nge7", "Be3"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Qf6.",
      "We move the knight to b5.",
      "Black develops Bc5.",
      "We develop Qe2.",
      "Black retreats the bishop to b6.",
      "We develop the other knight.",
      "Black develops Nge7.",
      "After the final move - Well done! We'll try and take that bishop if we can, and castle if we can't. By developing Be3, we attack the bishop and prepare development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-25",
    "name": "Standard Middle Game",
    "description": "Equal middle game position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "O-O", "O-O", "d6", "Nxc6", "Nxc6", "Bxc5", "dxc5", "f4", "Be6", "e5", "Qe7", "Bxe6", "Qxe6", "Nd2"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black plays d6.",
      "We capture on c6.",
      "Black recaptures with the knight.",
      "We capture the bishop.",
      "Black recaptures with the pawn.",
      "We push f4.",
      "Black develops Be6.",
      "We push e5.",
      "Black develops Qe7.",
      "We capture the bishop.",
      "Black recaptures with the queen.",
      "After the final move - Well done! Let's play some chess now. By developing Nd2, we reposition the knight for the middle game."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-26",
    "name": "Slight Advantage Line",
    "description": "Better position",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7", "Bc4", "O-O", "O-O", "d6", "Nxc6", "Nxc6", "Bxc5", "dxc5", "f4", "Be6", "e5", "Qg6", "Bd3", "Bf5", "Bxf5", "Qxf5", "Nd2"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black plays d6.",
      "We capture on c6.",
      "Black recaptures with the knight.",
      "We capture the bishop.",
      "Black recaptures with the pawn.",
      "We push f4.",
      "Black develops Be6.",
      "We push e5.",
      "Black moves the queen to g6.",
      "We develop Bd3.",
      "Black develops Bf5.",
      "We capture the bishop.",
      "Black recaptures with the queen.",
      "After the final move - Well done! We have a slightly better position. By developing Nd2, we prepare for the middle game."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-27",
    "name": "Perfect Play Line",
    "description": "Both sides play perfectly",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "bxc6", "Bd3", "d5", "exd5", "cxd5", "O-O", "Be7", "c4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We develop Bd3.",
      "Black plays d5.",
      "We capture on d5.",
      "Black recaptures with c-pawn.",
      "We castle.",
      "Black develops Be7.",
      "After the final move - Well done! Both you and black played absolutely perfectly. By playing c4, we challenge the center and create play."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-28",
    "name": "Repeat Line 1",
    "description": "Similar to earlier line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Nf6", "Nxc6", "bxc6", "Bxc5"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We capture the bishop, maintaining advantage."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-29",
    "name": "Repeat Line 2",
    "description": "Another repeated line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "Nf6", "dxe5", "Nxe4", "Bc4", "Bc5", "Qd5", "Bxf2+", "Kf1", "O-O", "Qxe4"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black develops Nf6.",
      "We capture on e5.",
      "Black captures on e4.",
      "We develop Bc4.",
      "Black develops Bc5.",
      "We play Qd5.",
      "Black checks with Bxf2+.",
      "We move Kf1.",
      "Black castles.",
      "After the final move - Nice! We have an extra knight."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-30",
    "name": "Repeat Line 3",
    "description": "Another repetition",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Qf6", "Nb5", "Bc5", "Qe2", "Bb6", "N1c3", "a6", "Nd5", "Qd8", "Nxb6", "cxb6", "Nd6+", "Kf8", "Bf4"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Qf6.",
      "We move Nb5.",
      "Black develops Bc5.",
      "We develop Qe2.",
      "Black retreats Bb6.",
      "We develop N1c3.",
      "Black plays a6.",
      "We move Nd5.",
      "Black retreats Qd8.",
      "We capture Nxb6.",
      "Black recaptures cxb6.",
      "We check Nd6+.",
      "Black moves Kf8.",
      "After the final move - Wow. The material is equal but we will win from here 100% of the time."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-31",
    "name": "Repeat Line 4",
    "description": "Another repeated sequence",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "d6", "Nc3", "Nf6", "Bg5", "Be7", "O-O-O", "O-O", "e5", "dxe5", "Qxe5", "Qe8", "Qxc7", "Be6", "Bb5", "Qc8", "Qxe7"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin with Bg5.",
      "Black develops Be7.",
      "We castle queenside.",
      "Black castles kingside.",
      "We push e5.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves Qe8.",
      "We capture Qxc7.",
      "Black develops Be6.",
      "We develop Bb5.",
      "Black moves Qc8.",
      "After the final move - Knight will be coming to c7. Knight will win a rook. GG."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-32",
    "name": "Repeat Line 5",
    "description": "Another repeat",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Ng8", "Nc3", "d6", "Bf4", "dxe5", "Qxe5+", "Qe7", "Nb5", "Qxe5+", "Bxe5"],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black retreats Ng8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures dxe5.",
      "We check Qxe5+.",
      "Black blocks Qe7.",
      "We move Nb5.",
      "Black captures Qxe5+.",
      "After the final move - Knight will be coming to c7. Knight will win a rook. GG."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-33",
    "name": "Repeat Line 6",
    "description": "Final repeated line",
    "moves": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nxd4", "Qxd4", "Nf6", "e5", "Qe7", "Be3", "Ng8", "Nc3", "d6", "Nd5", "Qd7", "exd6", "Bxd6", "Qxg7"],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Nf6.",
      "We push e5.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats Ng8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We move Nd5.",
      "Black moves Qd7.",
      "We capture exd6.",
      "Black recaptures Bxd6.",
      "After the final move - It's over. We're winning a rook and probably a few other pieces too."
    ]
  }
];