import { withOpeningFeedback } from "./feedback";

export const scotchGameLines = withOpeningFeedback([
  {
    "category": "Scotch Game",
    "id": "scotch-01",
    "name": "Classical Scotch Main Line",
    "description": "Standard Scotch with bishop exchange",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Nf6",
      "Nxc6",
      "bxc6",
      "Bxc5"
    ],
    "explanations": [
      "Let's learn the scotch game! This opening literally just feels like a cheat! We begin with pawn to e4.",
      "Black responds with e5, establishing the classical center.",
      "We develop the knight to f3, attacking the e5 pawn and developing a piece.",
      "Black develops the knight to c6, defending the e5 pawn.",
      "We immediately strike in the center with d4, opening lines and challenging Black's position.",
      "Black captures on d4, accepting the exchange.",
      "We recapture with the knight, centralizing a piece.",
      "Black develops the bishop to c5, attacking our knight and controlling the center.",
      "We develop the bishop to e3, defending the knight and preparing queenside castling.",
      "Black develops the knight to f6, attacking e4 and preparing kingside castling.",
      "We capture on c6, damaging Black's pawn structure.",
      "Black recaptures with the b-pawn, creating doubled pawns but opening the b-file.",
      "We capture the bishop, winning the bishop pair and maintaining a strong position."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-02",
    "name": "Scotch Four Knights Variation",
    "description": "Queen exchange line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "c5",
      "Qe3",
      "Nf6",
      "e5"
    ],
    "explanations": [
      "We open with e4, establishing central control.",
      "Black responds with e5, mirroring our central pawn.",
      "We develop the knight to f3, attacking e5.",
      "Black defends with Nc6.",
      "We strike immediately with d4, opening the center.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight, simplifying the position.",
      "We recapture with the queen, centralizing it but potentially exposing it.",
      "Black attacks our queen with c5, gaining tempo.",
      "We move the queen to e3, maintaining central presence.",
      "Black develops the knight to f6.",
      "We push e5, attacking the knight and gaining space."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-03",
    "name": "Göring Gambit Declined",
    "description": "Tactical line with knight win",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "Nf6",
      "dxe5",
      "Nxe4",
      "Bc4",
      "Bc5",
      "Qd5",
      "Bxf2+",
      "Kf1",
      "O-O",
      "Qxe4"
    ],
    "explanations": [
      "We begin with e4, establishing the center.",
      "Black responds with e5.",
      "We develop Nf3, attacking e5.",
      "Black develops Nc6.",
      "We play d4, challenging the center.",
      "Black develops Nf6 instead of capturing on d4.",
      "We capture on e5.",
      "Black captures on e4 with the knight.",
      "We develop the bishop to c4, attacking f7.",
      "Black develops Bc5.",
      "We attack with Qd5, threatening multiple pieces.",
      "Black checks with Bxf2+.",
      "We move the king to f1.",
      "Black castles.",
      "After the final move - Nice! We have an extra knight. By capturing on e4, we regain our pawn and maintain material advantage."
    ]
  },
  {
    "category": "Scotch Gambit",
    "id": "scotch-gambit-01",
    "name": "Scotch Gambit: Haxo Trap",
    "description": "If Black grabs on c3, Bxf7+ and Qd5+ drag the king out and win back material with interest.",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Bc4",
      "Bc5",
      "c3",
      "dxc3",
      "Bxf7+",
      "Kxf7",
      "Qd5+",
      "Ke8",
      "Qh5+",
      "g6",
      "Qxc5"
    ],
    "explanations": [
      "We open with e4 and claim central space.",
      "Black mirrors with e5.",
      "We develop Nf3 and prepare to hit the center.",
      "Black develops Nc6 and supports e5.",
      "d4 is the Scotch move, challenging the center immediately.",
      "Black accepts the pawn and opens the position.",
      "Bc4 turns the game into the Scotch Gambit. We value rapid development and pressure on f7 over the pawn.",
      "Bc5 is natural. Black develops and tries to hold the extra pawn.",
      "c3 attacks the d4 pawn and tempts black into grabbing still more material.",
      "dxc3 is the greedy move. Black keeps pawns, but king safety and development fall behind.",
      "Bxf7+ is the key sacrifice from the transcript. f7 is the weakest square and the king gets dragged out.",
      "Black has to take, or else the position collapses even faster.",
      "Qd5+ is the point. It checks the king and hits the bishop on c5 at the same time.",
      "Ke8 is the practical retreat, but black has already lost castling rights.",
      "Qh5+ is the useful in-between check. We force another concession before taking material back.",
      "g6 is forced to block the queen.",
      "Qxc5 wins the bishop back. White has recovered material and black still has a king stuck in the center."
    ]
  },
  {
    "category": "Scotch Gambit",
    "id": "scotch-gambit-02",
    "name": "Scotch Gambit: Dubois-Réti Trap",
    "description": "Against ...Nf6, Ng5 and fast castling create Fried Liver style pressure on f7.",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Bc4",
      "Nf6",
      "Ng5",
      "d5",
      "exd5",
      "Nxd5",
      "O-O",
      "Be7",
      "Nxf7",
      "Kxf7",
      "Qf3+"
    ],
    "explanations": [
      "We open with e4 and take central space.",
      "Black replies with e5.",
      "We develop Nf3 and prepare to strike in the center.",
      "Black develops Nc6 and supports e5.",
      "d4 starts the Scotch and asks black to decide the center right away.",
      "Black takes and opens lines.",
      "Bc4 keeps the initiative and immediately points at f7.",
      "Nf6 is a natural developing move, but it lets us increase the pressure on f7.",
      "Ng5 is the aggressive follow-up from the transcript. We attack f7 twice and force black to react.",
      "d5 is the most natural counterstrike against the bishop and the center.",
      "We capture on d5 to keep lines open and avoid losing the initiative.",
      "Black recaptures with the knight, which looks natural but walks into a tactical setup.",
      "O-O first. The transcript's point is that Nxf7 immediately would allow ...Qe7+ and spoil the attack.",
      "Be7 tries to cover the king and get ready to castle.",
      "Now Nxf7 works. We rip open the king and use the bishop and rook together.",
      "Black has to take the knight.",
      "Qf3+ is the Fried Liver style follow-up. We check the king, hit d5, and keep black's pieces tied down."
    ]
  },
  {
    "category": "Scotch Gambit",
    "id": "scotch-gambit-03",
    "name": "Scotch Gambit: London Defense, Morphy Castles",
    "description": "After ...Bb4+, c3 and O-O keep development first. If Black keeps grabbing pawns, Bxb2 points straight at g7 and the rook.",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Bc4",
      "Bb4+",
      "c3",
      "dxc3",
      "O-O",
      "cxb2",
      "Bxb2"
    ],
    "explanations": [
      "We open with e4 and claim the center.",
      "Black mirrors with e5.",
      "We develop Nf3 and prepare the Scotch structure.",
      "Black develops Nc6 and covers e5.",
      "d4 is the immediate central challenge.",
      "Black takes and opens the game.",
      "Bc4 chooses the Scotch Gambit. The bishop comes out with tempo and eyes f7.",
      "Bb4+ is a common check, but black is still not fixing development problems.",
      "c3 blocks the check while attacking the bishop and offering more material for speed.",
      "Black grabs on c3 and keeps trying to hold pawns.",
      "O-O is the Morphy idea from the transcript. We ignore the pawn and prioritize development and rook activity.",
      "Black takes one more pawn, getting even greedier.",
      "Bxb2 plants the bishop on the long diagonal toward g7 and the rook on h8, which is the core attacking idea in this setup."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-04",
    "name": "Scotch with d6 Defense",
    "description": "Against passive d6 setup",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "d6",
      "d5",
      "Nd4",
      "Nxd4",
      "exd4",
      "Qxd4"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black plays Nc6.",
      "We strike with d4.",
      "Black plays d6, a more passive defense.",
      "We push d5, gaining space.",
      "Black moves the knight to d4.",
      "We capture the knight.",
      "Black recaptures with the pawn.",
      "We capture with the queen, centralizing it."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-05",
    "name": "Nb5 Pressure Line",
    "description": "Aggressive c7 pressure after ...Qf6",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Qf6",
      "Nb5",
      "Bc5",
      "Qe2",
      "Bb6",
      "N1c3",
      "a6",
      "Nd5",
      "Qd8",
      "Nxb6",
      "cxb6",
      "Nd6+",
      "Kf8",
      "Bf4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4, opening the center.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black puts the queen on f6 to pressure the knight, but that move also abandons the d8 square.",
      "Nb5 takes immediate advantage of that. We threaten Nc7+ with a fork on the king and rook.",
      "Black develops Bc5.",
      "Qe2 keeps the queens on, supports castling, and leaves the c7 threat hanging over black.",
      "Black retreats the bishop to b6.",
      "We develop the other knight to c3.",
      "Black plays a6, attacking our knight.",
      "Nd5 centralizes the knight and keeps the queen tied down to the back rank.",
      "Black retreats the queen to d8.",
      "We capture the bishop on b6.",
      "Black recaptures with the c-pawn.",
      "Nd6+ is the key jump. The knight lands deep in black's camp and forces the king off its best square.",
      "Black moves the king to f8.",
      "After the final move, Bf4 brings another piece into the attack and targets the weakened dark squares around the stranded king."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-06",
    "name": "Classical Scotch, Qa4 Style Attack",
    "description": "Queenside castling and e5 break against ...d6 and ...Nf6",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "d6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "O-O-O",
      "O-O",
      "e5",
      "dxe5",
      "Qxe5",
      "Qe8",
      "Qxc7",
      "Be6",
      "Bb5",
      "Qc8",
      "Qxe7"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin the knight with Bg5.",
      "Black develops Be7.",
      "We castle queenside so the rook lands on d1 and immediately supports the central break.",
      "Black castles kingside.",
      "e5 is the thematic punch. We hit the knight, open lines, and start exploiting the rook on d1.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves the queen to e8.",
      "Qxc7 picks up the c7 pawn and drags black's queen and rook into a tactical mess.",
      "Black develops Be6.",
      "Bb5 is the point. We hit the queen while keeping pressure on e7 and the back rank.",
      "Black moves the queen to c8.",
      "After the final move, Qxe7 wins material cleanly. Black's queen got overloaded and the c7 and d-file pressure never went away."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-07",
    "name": "Kingside Attack Variation",
    "description": "Sacrificial kingside attack",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nf6",
      "Nxc6",
      "bxc6",
      "Bd3",
      "Bc5",
      "e5",
      "Qe7",
      "O-O",
      "Nd5",
      "Nd2",
      "O-O",
      "Ne4",
      "Bb6",
      "c4",
      "Nb4",
      "Nf6+",
      "gxf6",
      "Bxh7+",
      "Kxh7",
      "Qh5+",
      "Kg8",
      "Qg4+",
      "Kh7",
      "Qh4+",
      "Kg8",
      "Bh6",
      "Qxe5"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6 to damage the pawn structure before launching play on the kingside.",
      "Black recaptures with the b-pawn, opening the b-file but loosening dark squares around the king.",
      "We develop Bd3 and line the bishop up with h7.",
      "Black develops Bc5, an active move that also leaves the king side exposed to tactics.",
      "We push e5 to gain space and kick the knight off its best square.",
      "Black plays Qe7 to support the knight and hold e5.",
      "We castle before attacking so the rook can join and our king stays out of the blast radius.",
      "Black reroutes the knight to d5.",
      "We develop Nd2 to support e4 and f3 ideas while keeping pieces ready for the attack.",
      "Black castles.",
      "We improve the knight to e4, aiming at f6, d6, and g5.",
      "Black retreats the bishop to b6, but that does not solve the king side pressure.",
      "We play c4 to gain more space and challenge the knight on d5.",
      "Black jumps to b4.",
      "We start the tactical sequence with Nf6+, ripping open the king side at the cost of a piece.",
      "Black accepts with gxf6, but that also opens the g-file and weakens the king.",
      "We continue with Bxh7+, dragging the king further into the open.",
      "Black takes the bishop.",
      "Qh5+ keeps the king exposed and forces it to keep moving.",
      "Black steps to g8.",
      "Qg4+ shifts the queen to a new checking lane and keeps the attack alive.",
      "Black runs to h7.",
      "Qh4+ keeps the king boxed in and maintains pressure on the weakened dark squares.",
      "Black returns to g8.",
      "Bh6 adds another attacker and threatens mating ideas against g7 and h-file squares.",
      "Black grabs the e5 pawn, but the attack is still the only thing that matters here."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-08",
    "name": "Pressure on c7 Square",
    "description": "Knight domination line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Ng8",
      "Nc3",
      "d6",
      "Bf4",
      "dxe5",
      "Qxe5+",
      "Qe7",
      "Nb5",
      "Qxe5+",
      "Bxe5"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures on e5.",
      "We check with Qxe5+.",
      "Black blocks with Qe7.",
      "Nb5 renews the real threat: Nc7+ with a fork on the king and rook.",
      "Black captures our queen.",
      "After the final move, Bxe5 keeps the better structure and leaves black struggling to solve the c7 problem."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-09",
    "name": "C7 Square Pressure Line",
    "description": "Similar to previous with Be7",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Ng8",
      "Nc3",
      "d6",
      "Bf4",
      "dxe5",
      "Qxe5+",
      "Be7",
      "Nb5"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures on e5.",
      "We check with Qxe5+.",
      "Black blocks with Be7.",
      "After the final move, Nb5 sets up Nc7+ and makes the c7 square the center of the position."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-10",
    "name": "Rook Win Variation",
    "description": "Winning material line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Qe7",
      "Be3",
      "Ng8",
      "Nc3",
      "d6",
      "Nd5",
      "Qd7",
      "exd6",
      "Bxd6",
      "Qxg7"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "Nd5 is a strong central jump. It hits c7 ideas and makes black's queen placement awkward.",
      "Black moves the queen to d7.",
      "We capture on d6.",
      "Black recaptures with the bishop.",
      "After the final move, Qxg7 wins the rook on h8 because black's back rank and king side are too loose."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-11",
    "name": "Material Advantage Line",
    "description": "Winning two pawns",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "d6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "O-O-O",
      "O-O",
      "e5",
      "dxe5",
      "Qxe5",
      "Qe8",
      "Qxc7",
      "Be6",
      "Bb5",
      "Rc8",
      "Qxb7",
      "Rb8",
      "Bxe8",
      "Rxb7",
      "Ba4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin with Bg5.",
      "Black develops Be7.",
      "We castle queenside.",
      "Black castles kingside.",
      "We push e5.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves the queen to e8.",
      "We capture on c7.",
      "Black develops Be6.",
      "We develop Bb5.",
      "Black moves the rook to c8.",
      "We capture on b7.",
      "Black moves the rook to b8.",
      "We capture the queen.",
      "Black captures our queen.",
      "After the final move - Nice! We made out like bandits and are now up two pawns! By retreating the bishop to a4, we save it and maintain our material advantage."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-12",
    "name": "Positional Advantage Line",
    "description": "Comfortable position with advantage",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Nxd4",
      "Bxd4",
      "Bxd4",
      "Qxd4",
      "Qf6",
      "e5",
      "Qb6",
      "Qxb6",
      "axb6",
      "Nc3",
      "Ne7",
      "O-O-O",
      "O-O",
      "Bc4"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black captures our knight.",
      "We recapture with the bishop.",
      "Black captures our bishop.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to b6.",
      "We exchange queens.",
      "Black recaptures with a-pawn.",
      "We develop Nc3.",
      "Black develops Ne7.",
      "We castle queenside.",
      "Black castles kingside.",
      "After the final move - Nice! We have a very comfortable position. It'll be up to you to convert our 1.5 point advantage into a win. By developing Bc4, we complete our development with a strong bishop."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-13",
    "name": "Development Advantage Line",
    "description": "Better development and king safety",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Qf6",
      "e5",
      "Qe6",
      "Bc4",
      "Qg6",
      "Nc3",
      "Qxg2",
      "Bd5",
      "Qg6",
      "Bd2"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to e6.",
      "We develop Bc4.",
      "Black moves the queen to g6.",
      "We develop Nc3.",
      "Black captures on g2.",
      "We develop Bd5.",
      "Black retreats the queen to g6.",
      "After the final move - Even though material is equal, this game is not even close. Our development is so much better, and our king is about to be so much safer. By developing Bd2, we complete our development and prepare to castle."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-14",
    "name": "Crushing Advantage Line",
    "description": "+5 advantage position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Qe7",
      "Be3",
      "Ng8",
      "Nc3",
      "d6",
      "Nd5",
      "Qd7",
      "exd6",
      "Qxd6",
      "Bf4",
      "Qe6+",
      "Be2"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats the knight to g8.",
      "We develop Nc3.",
      "Black plays d6.",
      "Nd5 centralizes with tempo and keeps the queen tied to defensive tasks.",
      "Black moves the queen to d7.",
      "We capture on d6.",
      "Black recaptures with the queen.",
      "We develop Bf4.",
      "Black checks with the queen.",
      "After the final move, Be2 is a calm consolidating move. White is ready to castle and black still has to solve development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-15",
    "name": "Attacking Line with Qf4",
    "description": "+2 advantage position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Qf6",
      "e5",
      "Qe6",
      "Bc4",
      "Qb6",
      "Qf4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to e6.",
      "We develop Bc4.",
      "Black moves the queen to b6.",
      "After the final move - Well done! Black will scramble to stop our attack, and in the meantime we'll castle and keep developing our pieces. The computer has at a +2 point advantage. By moving Qf4, we maintain pressure and prepare to develop our pieces."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-16",
    "name": "Space Advantage Line",
    "description": "+1 advantage with space",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "d6",
      "d5",
      "Nce7",
      "c4",
      "Nf6",
      "Nc3"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black plays d6.",
      "We push d5.",
      "Black retreats the knight to e7.",
      "We play c4.",
      "Black develops Nf6.",
      "After the final move - Well done! We have so much space - giving us a +1 point advantage. By developing Nc3, we complete our knight development and control the center."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-17",
    "name": "Terrifying Position Line",
    "description": "Strong attacking setup",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nf6",
      "Nxc6",
      "bxc6",
      "Bd3",
      "Bc5",
      "e5",
      "Nd5",
      "Qg4",
      "g6",
      "Bh6",
      "d6",
      "Qa4",
      "Bd7",
      "O-O"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We develop Bd3.",
      "Black develops Bc5.",
      "We push e5.",
      "Black moves the knight to d5.",
      "We develop Qg4.",
      "Black plays g6.",
      "We develop Bh6.",
      "Black plays d6.",
      "We move the queen to a4.",
      "Black develops Bd7.",
      "After the final move - Well done! Our position is just terrifying for black. By castling, we secure our king and prepare for the attack."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-18",
    "name": "Endgame Advantage Line",
    "description": "Better endgame prospects",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nf6",
      "Nxc6",
      "dxc6",
      "Qxd8+",
      "Kxd8",
      "f3"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with d-pawn.",
      "We exchange queens.",
      "Black captures with the king.",
      "After the final move - Well done! We will develop and castle - something our opponent no longer has the ability to do. By playing f3, we support the center and prepare development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-19",
    "name": "Central Control Line",
    "description": "+1 advantage with center control",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "O-O",
      "O-O",
      "Ne5",
      "Be2",
      "d5",
      "f4",
      "Nc4",
      "Bxc4",
      "dxc4",
      "Nd2"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d5.",
      "We push f4.",
      "Black moves the knight to c4.",
      "We capture the knight.",
      "Black recaptures with the pawn.",
      "After the final move - Well done! We own the center and have more development and a better pawn structure. The computer gives us a +1 point advantage. By developing Nd2, we reposition the knight and maintain control."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-20",
    "name": "Queen Exchange Line",
    "description": "Simple center control",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Qf6",
      "e5",
      "Qb6",
      "Be3",
      "Qxd4",
      "Bxd4"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black develops Qf6.",
      "We push e5.",
      "Black moves the queen to b6.",
      "We develop Be3.",
      "Black captures our queen.",
      "After the final move - Well done! We simply own the center now. By recapturing with the bishop, we maintain a strong centralized piece."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-21",
    "name": "Pawn Push Advantage",
    "description": "Edge with f4 push",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "O-O",
      "O-O",
      "Ne5",
      "Be2",
      "d6",
      "f4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d6.",
      "After the final move - Well done! That pawn push is giving us an edge of the opponent. By pushing f4, we gain space and attack the knight."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-22",
    "name": "High Win Rate Line",
    "description": "70%+ win rate from position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "Ne5",
      "Be2",
      "d5",
      "O-O",
      "dxe4",
      "Nb5",
      "Bd6",
      "Bc5",
      "O-O",
      "Nxd6",
      "cxd6",
      "Qxd6",
      "Qxd6",
      "Bxd6"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black moves the knight to e5.",
      "We retreat the bishop to e2.",
      "Black plays d5.",
      "We castle.",
      "Black captures on e4.",
      "We move the knight to b5.",
      "Black retreats the bishop to d6.",
      "We develop Bc5.",
      "Black castles.",
      "We capture on d6.",
      "Black recaptures with c-pawn.",
      "We capture on d6 with queen.",
      "Black captures our queen.",
      "After the final move - Well done! We win over 70% of the time from here. By capturing the bishop, we maintain material equality with better prospects."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-23",
    "name": "Standard Development Line",
    "description": "Ready to play position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "d6",
      "O-O"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black plays d6.",
      "After the final move - Well done! We are ready to play some chess. By castling, we secure our king and complete development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-24",
    "name": "Bishop Attack Line",
    "description": "Attacking the bishop",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Qf6",
      "Nb5",
      "Bc5",
      "Qe2",
      "Bb6",
      "N1c3",
      "Nge7",
      "Be3"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Qf6.",
      "We move the knight to b5.",
      "Black develops Bc5.",
      "We develop Qe2.",
      "Black retreats the bishop to b6.",
      "We develop the other knight.",
      "Black develops Nge7.",
      "After the final move - Well done! We'll try and take that bishop if we can, and castle if we can't. By developing Be3, we attack the bishop and prepare development."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-25",
    "name": "Standard Middle Game",
    "description": "Equal middle game position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "O-O",
      "O-O",
      "d6",
      "Nxc6",
      "Nxc6",
      "Bxc5",
      "dxc5",
      "f4",
      "Be6",
      "e5",
      "Qe7",
      "Bxe6",
      "Qxe6",
      "Nd2"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black plays d6.",
      "We capture on c6.",
      "Black recaptures with the knight.",
      "We capture the bishop.",
      "Black recaptures with the pawn.",
      "We push f4.",
      "Black develops Be6.",
      "We push e5.",
      "Black develops Qe7.",
      "We capture the bishop.",
      "Black recaptures with the queen.",
      "After the final move - Well done! Let's play some chess now. By developing Nd2, we reposition the knight for the middle game."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-26",
    "name": "Slight Advantage Line",
    "description": "Better position",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "O-O",
      "O-O",
      "d6",
      "Nxc6",
      "Nxc6",
      "Bxc5",
      "dxc5",
      "f4",
      "Be6",
      "e5",
      "Qg6",
      "Bd3",
      "Bf5",
      "Bxf5",
      "Qxf5",
      "Nd2"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Qf6.",
      "We play c3.",
      "Black develops Nge7.",
      "We develop Bc4.",
      "Black castles.",
      "We castle.",
      "Black plays d6.",
      "We capture on c6.",
      "Black recaptures with the knight.",
      "We capture the bishop.",
      "Black recaptures with the pawn.",
      "We push f4.",
      "Black develops Be6.",
      "We push e5.",
      "Black moves the queen to g6.",
      "We develop Bd3.",
      "Black develops Bf5.",
      "We capture the bishop.",
      "Black recaptures with the queen.",
      "After the final move - Well done! We have a slightly better position. By developing Nd2, we prepare for the middle game."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-27",
    "name": "Perfect Play Line",
    "description": "Both sides play perfectly",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nf6",
      "Nxc6",
      "bxc6",
      "Bd3",
      "d5",
      "exd5",
      "cxd5",
      "O-O",
      "Be7",
      "c4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We develop Bd3.",
      "Black plays d5.",
      "We capture on d5.",
      "Black recaptures with c-pawn.",
      "We castle.",
      "Black develops Be7.",
      "After the final move - Well done! Both you and black played absolutely perfectly. By playing c4, we challenge the center and create play."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-28",
    "name": "Repeat Line 1",
    "description": "Similar to earlier line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Nf6",
      "Nxc6",
      "bxc6",
      "Bxc5"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Bc5.",
      "We develop Be3.",
      "Black develops Nf6.",
      "We capture on c6.",
      "Black recaptures with b-pawn.",
      "We capture the bishop, maintaining advantage."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-29",
    "name": "Repeat Line 2",
    "description": "Another repeated line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "Nf6",
      "dxe5",
      "Nxe4",
      "Bc4",
      "Bc5",
      "Qd5",
      "Bxf2+",
      "Kf1",
      "O-O",
      "Qxe4"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black develops Nf6.",
      "We capture on e5.",
      "Black captures on e4.",
      "We develop Bc4.",
      "Black develops Bc5.",
      "We play Qd5.",
      "Black checks with Bxf2+.",
      "We move Kf1.",
      "Black castles.",
      "After the final move - Nice! We have an extra knight."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-30",
    "name": "Repeat Line 3",
    "description": "Another repetition",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Qf6",
      "Nb5",
      "Bc5",
      "Qe2",
      "Bb6",
      "N1c3",
      "a6",
      "Nd5",
      "Qd8",
      "Nxb6",
      "cxb6",
      "Nd6+",
      "Kf8",
      "Bf4"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black develops Qf6.",
      "We move Nb5.",
      "Black develops Bc5.",
      "We develop Qe2.",
      "Black retreats Bb6.",
      "We develop N1c3.",
      "Black plays a6.",
      "We move Nd5.",
      "Black retreats Qd8.",
      "We capture Nxb6.",
      "Black recaptures cxb6.",
      "We check Nd6+.",
      "Black moves Kf8.",
      "After the final move - Wow. The material is equal but we will win from here 100% of the time."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-31",
    "name": "Repeat Line 4",
    "description": "Another repeated sequence",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "d6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "O-O-O",
      "O-O",
      "e5",
      "dxe5",
      "Qxe5",
      "Qe8",
      "Qxc7",
      "Be6",
      "Bb5",
      "Qc8",
      "Qxe7"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "We recapture with the queen.",
      "Black plays d6.",
      "We develop Nc3.",
      "Black develops Nf6.",
      "We pin with Bg5.",
      "Black develops Be7.",
      "We castle queenside so the rook lands on d1 and immediately supports the central break.",
      "Black castles kingside.",
      "e5 is the thematic punch. We hit the knight, open lines, and start exploiting the rook on d1.",
      "Black captures on e5.",
      "We recapture with the queen.",
      "Black moves Qe8.",
      "Qxc7 picks up the c7 pawn and drags black's queen and rook into a tactical mess.",
      "Black develops Be6.",
      "Bb5 is the point. We hit the queen while keeping pressure on e7 and the back rank.",
      "Black moves Qc8.",
      "After the final move, Qxe7 wins material cleanly. Black's queen got overloaded and the c7 and d-file pressure never went away."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-32",
    "name": "Repeat Line 5",
    "description": "Another repeat",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Ng8",
      "Nc3",
      "d6",
      "Bf4",
      "dxe5",
      "Qxe5+",
      "Qe7",
      "Nb5",
      "Qxe5+",
      "Bxe5"
    ],
    "explanations": [
      "We open with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black retreats Ng8.",
      "We develop Nc3.",
      "Black plays d6.",
      "We develop Bf4.",
      "Black captures dxe5.",
      "We check Qxe5+.",
      "Black blocks Qe7.",
      "Nb5 renews the real threat: Nc7+ with a fork on the king and rook.",
      "Black captures Qxe5+.",
      "After the final move, Bxe5 keeps the better structure and leaves black struggling to solve the c7 problem."
    ]
  },
  {
    "category": "Scotch Game",
    "id": "scotch-33",
    "name": "Repeat Line 6",
    "description": "Final repeated line",
    "moves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "Nf6",
      "e5",
      "Qe7",
      "Be3",
      "Ng8",
      "Nc3",
      "d6",
      "Nd5",
      "Qd7",
      "exd6",
      "Bxd6",
      "Qxg7"
    ],
    "explanations": [
      "We begin with e4.",
      "Black plays e5.",
      "We develop Nf3.",
      "Black develops Nc6.",
      "We play d4.",
      "Black captures on d4.",
      "We recapture with the knight.",
      "Black captures our knight.",
      "Qxd4 centralizes the queen and makes black prove the early ...Nxd4 trade was worth it.",
      "Black develops Nf6.",
      "e5 is the critical gain of tempo. We chase the knight and seize more space.",
      "Black develops Qe7.",
      "We develop Be3.",
      "Black retreats Ng8.",
      "We develop Nc3.",
      "Black plays d6.",
      "Nd5 is a strong central jump. It hits c7 ideas and makes black's queen placement awkward.",
      "Black moves Qd7.",
      "We capture exd6.",
      "Black recaptures Bxd6.",
      "After the final move, Qxg7 wins the rook on h8 because black's back rank and king side are too loose."
    ]
  }
]);