import { withOpeningFeedback } from "./feedback";

// src/openings/sicilianDefenseLines.js

// SEO / page intro text for Sicilian Defense drills
export const sicilianSEOText = `
The Sicilian Defense fights for the center in an imbalanced way. Black's c-pawn has a
simple first job: if White offers d4, take it and trade a flank pawn for White's
central pawn. If White avoids that trade, Black often keeps the c-pawn in reserve and
hits the center another way with moves like ...e6, ...Nge7, and ...d5.

This page gives you Sicilian Defense drills built around recurring structures:
Open Sicilian setups, Dragon and Accelerated Dragon fianchetto pressure, Najdorf and
Classical flexibility, Kan and Paulsen queenside play, and practical answers to
anti-Sicilians like the Alapin, Bowdler, Grand Prix, and Moscow or Rossolimo systems.

Treat the Sicilian as a family of missions, not one memorized tree. Challenge d4 as
soon as it appears, finish development without drifting, and answer flank play with the
right central break or queenside counterplay.
`;


export const sicilianDefenseLines = withOpeningFeedback([
  // Categories: Open Sicilian, Anti-Sicilian, Closed Sicilian, Grand Prix, Moscow/Rossolimo

  {
    category: "Open Sicilian",
    id: "sicilian-open-mainline-classical",
    name: "Open Sicilian: Classical setup",
    description: "Mainline Open Sicilian: if White offers d4, take it immediately, then finish development with pressure on e4 and the c-file.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6", "Be3", "e6", "f3", "Be7", "Qd2", "O-O"],
    explanations: [
      "White starts with pawn to {{square e4}} and claims central space.",
      "Let's learn the Sicilian Defense! When White plays {{square e4}}, answer with pawn to {{square c5}} and create immediate imbalance.",
      "Develop and prepare the central break with {{square d4}}.",
      "Support the {{square c5}} structure, keep {{square e5}} under control, and prepare ...N{{square f6}}.",
      "White offers the central trade that defines the Open Sicilian.",
      "Take immediately. In Sicilian positions you do not let White keep both central pawns for free.",
      "White recaptures with development and central presence.",
      "Develop and hit {{square e4}}, making White defend before they start a wing attack.",
      "White covers {{square e4}} and adds another piece to the center.",
      "Develop and add more pressure on {{square d4}} and {{square e5}} while keeping your setup flexible.",
      "White starts a standard English Attack shell.",
      "Keep the center solid and open the dark bishop.",
      "White reinforces {{square e4}} and hints at {{square g4}} or long castling.",
      "Develop calmly. Black usually wants king safety before reacting to flank play.",
      "White coordinates the queenside-castling plan.",
      "Castle and finish the basic Sicilian setup."
    ]
  },

  {
    id: "sicilian-open-scheveningen",
    name: "Open Sicilian: Scheveningen structure",
    description: "Open Sicilian with ...e6 and ...d6, flexible and solid but watch kingside attacks.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "Be3", "a6", "f3", "Be7", "Qd2", "O-O"],
    explanations: [
      "White takes space and sets up fast development.",
      "Create asymmetry and contest {{square d4}} immediately.",
      "Develop and prepare {{square d4}}.",
      "Support the center and keep control of {{square e5}}.",
      "White goes for the Open Sicilian.",
      "Force the open center and typical Sicilian piece play.",
      "White recaptures with development.",
      "Pressure {{square e4}} and develop.",
      "Defend {{square e4}} and increase central control.",
      "Build the Scheveningen pawn shape and open the dark bishop.",
      "Natural development and a common English Attack setup.",
      "Useful luft and stops N{{square b5}} while preparing queenside play.",
      "Reinforce {{square e4}} and support {{square g4}} in some lines.",
      "Develop and prepare to castle.",
      "Support long castle and coordinate pressure on the kingside.",
      "Castle and connect rooks."
    ]
  },

  {
    id: "sicilian-open-najdorf-basic",
    name: "Open Sicilian: Najdorf with 6...a6",
    description: "Najdorf marker move ...a6 after standard development.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "Be3", "e5", "f3", "Be7", "Qd2", "Be6"],
    explanations: [
      "White claims the center and opens lines.",
      "Sicilian. Fight for {{square d4}} with an unbalanced pawn structure.",
      "Develop and prepare the Open Sicilian.",
      "Support ...{{square c5}} and prevent early {{square e5}} tactics.",
      "White commits to open central play.",
      "Exchange in the center and create imbalanced positions.",
      "White recaptures with development.",
      "Attack {{square e4}} and develop.",
      "Defend {{square e4}} and develop.",
      "Najdorf. Stop N{{square b5}} ideas and keep ...{{square e5}} or ...{{square e6}} flexible.",
      "English Attack style development.",
      "Najdorf often chooses ...{{square e5}} to gain space and hit the knight.",
      "Support the center and prepare {{square g4}} ideas.",
      "Keep structure flexible and open the dark bishop.",
      "Prepare long castle and coordinate attack.",
      "Develop and prepare to castle."
    ]
  },

  {
    id: "sicilian-open-dragon-basic",
    name: "Open Sicilian: Dragon setup",
    description: "Dragon: build the bishop house on g7, hit e4, and use the long diagonal plus c-file counterplay against White's kingside ambitions.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6", "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6"],
    explanations: [
      "White claims the center and opens development lanes.",
      "Sicilian. If White offers {{square d4}}, Black is ready to trade the c-pawn for that central pawn.",
      "Develop and prepare {{square d4}}.",
      "Support ...{{square c5}} and keep {{square e5}} under control.",
      "White opens the center and asks Black to clarify the pawn structure.",
      "Take immediately and reach the open Sicilian structure.",
      "White recaptures with a piece and centralizes.",
      "Develop and hit {{square e4}}.",
      "White covers {{square e4}} and keeps central space.",
      "Dragon bishop house. The fianchetto puts long-range pressure on the center and queenside.",
      "White points toward a Yugoslav Attack with opposite-side castling ideas.",
      "Complete the bishop house and keep building without drifting.",
      "White reinforces {{square e4}} and prepares a pawn storm.",
      "Castle before the race gets out of hand.",
      "White coordinates long castling and kingside pressure.",
      "Develop and add more pressure on {{square d4}}, with ...R{{square c8}} and queenside play often coming next."
    ]
  },

  {
    id: "sicilian-accelerated-dragon-basic",
    name: "Accelerated Dragon",
    description: "Accelerated Dragon: delay ...d6, develop fast with ...Nc6 and ...g6, and keep the one-move ...d5 break ready if White gets careless.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "g6", "Nc3", "Bg7", "Be3", "Nf6", "f3", "d6", "Qd2", "O-O"],
    explanations: [
      "White takes space and threatens quick development.",
      "Sicilian. Contest {{square d4}} without mirroring White's structure.",
      "Develop and prepare {{square d4}}.",
      "Develop immediately and pressure {{square d4}} before revealing the full setup.",
      "White opens the center.",
      "Exchange and create open Sicilian play.",
      "White recaptures and centralizes.",
      "Accelerated Dragon plan. Build the bishop house first and keep the d-pawn flexible.",
      "Develop and reinforce central control.",
      "Complete the fianchetto and pressure the long diagonal.",
      "White starts a sharp setup and points toward long castling.",
      "Develop and hit {{square e4}} while watching for a central break.",
      "White reinforces {{square e4}} and slows down ...N{{square g4}} ideas.",
      "Only now commit to ...{{square d6}} if you want a Dragon structure. Delaying this pawn was the whole point, because it kept ...{{square d5}} available sooner.",
      "White coordinates queenside-castling ideas.",
      "Castle and finish development before the race starts."
    ]
  },

  {
    id: "sicilian-sveshnikov-skeleton",
    name: "Sveshnikov skeleton",
    description: "Sveshnikov: early ...e5 after ...Nc6 and ...Nf6, very theory heavy but consistent plans.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5", "Ndb5", "d6", "Bg5", "a6", "Na3", "b5"],
    explanations: [
      "White claims space and opens lines.",
      "Sicilian. Fight for {{square d4}} with asymmetry.",
      "Develop and aim for {{square d4}}.",
      "Develop and pressure {{square d4}}.",
      "White opens the center.",
      "Exchange and create open lines.",
      "White recaptures with a piece.",
      "Develop and hit {{square e4}}.",
      "Defend {{square e4}} and develop.",
      "Sveshnikov marker. Grab space and hit the {{square d4}} knight.",
      "Typical. White jumps into {{square b5}} to target {{square d6}} and {{square c7}} squares.",
      "Hold {{square e5}} and stop immediate tactics on {{square d6}}.",
      "Pin the knight and increase pressure on the center.",
      "Kick the {{square b5}} knight support squares and prepare ...{{square b5}}.",
      "Re-route the knight to {{square c4}} or {{square b5}} in some lines.",
      "Gain queenside space and support ...{{square b4}} ideas."
    ]
  },

  {
    id: "sicilian-kan-basic",
    name: "Kan Sicilian",
    description: "Kan and Paulsen style setup: ...e6, ...a6, and often ...Qc7, keeping flexible development and strong central breaks.",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6", "Nc3", "Qc7", "Be2", "Nf6", "O-O", "d6", "Be3", "b5"],
    explanations: [
      "White takes central space.",
      "Sicilian. Contest {{square d4}} and avoid symmetry.",
      "Develop and prepare {{square d4}}.",
      "Kan style. Support {{square d5}} breaks later and open the dark bishop.",
      "Open Sicilian attempt.",
      "Accept the open center.",
      "White recaptures and develops.",
      "Flexible. Prevent N{{square b5}} ideas and prepare ...Q{{square c7}} or ...{{square b5}}.",
      "Develop and keep pressure on the center.",
      "Typical Kan idea, supporting ...{{square d5}} and queenside play.",
      "Develop and prepare safe castling.",
      "Develop and hit {{square e4}}.",
      "Castle and complete basic king safety.",
      "Stabilize the center and open the dark bishop.",
      "Develop and support central control.",
      "Queenside expansion, gaining space and supporting ...B{{square b7}}."
    ]
  },

  {
    id: "sicilian-taimanov-basic",
    name: "Taimanov setup",
    description: "Taimanov: ...e6 and ...Qc7 is a common plan, flexible piece placement.",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Nc3", "Qc7", "Be3", "a6", "Be2", "Nf6", "O-O", "d6"],
    explanations: [
      "White claims the center.",
      "Sicilian structure to fight for {{square d4}}.",
      "Develop and set up {{square d4}}.",
      "Keep options open and prepare ...{{square d5}} in some lines.",
      "Open center and gain space.",
      "Exchange in the center.",
      "White develops with recapture.",
      "Develop and pressure {{square d4}}.",
      "Defend and develop.",
      "Typical Taimanov idea, supporting ...{{square d5}} and coordinating pieces.",
      "Natural development, supports Q{{square d2}} and long castle ideas.",
      "Flexible, prevents N{{square b5}} and supports queenside expansion.",
      "Develop and prepare to castle safely.",
      "Develop and pressure {{square e4}}.",
      "Castle and connect rooks.",
      "Solidify the center and prepare ...B{{square e7}} and ...O-O."
    ]
  },

  {
    id: "sicilian-alapin-basic",
    name: "Vs Alapin: 2.c3",
    description: "Alapin (2.c3): respond with ...d5 to challenge the center directly.",
    moves: ["e4", "c5", "c3", "d5", "exd5", "Qxd5", "d4", "Nf6", "Nf3", "e6", "Be2", "cxd4", "cxd4", "Bb4+", "Nc3", "Qa5"],
    explanations: [
      "White claims the center.",
      "Sicilian response, but White avoids the Open Sicilian with {{square c3}}.",
      "Alapin. White supports {{square d4}} and reduces your typical counterplay lines.",
      "Direct counter in the center. Challenge {{square e4}} and punish slow play.",
      "White usually takes to avoid losing central control.",
      "Recapture with the queen, accepting early queen development for central pressure.",
      "Take space and build a center with {{square c3}} support.",
      "Develop and hit {{square e4}}, also prepares ...cx{{square d4}}.",
      "Develop and support the center.",
      "Prepare ...{{square d5}} or ...cx{{square d4}} and develop the dark bishop.",
      "Quiet development and prepare to castle.",
      "Challenge the center and open lines.",
      "Recapture and keep a pawn center.",
      "Check that develops a piece and forces a response.",
      "Block the check and develop, defending the center.",
      "Pressure {{square c3}} and {{square a2}}, keep the queen active."
    ]
  },

  {
    id: "sicilian-grand-prix-basic",
    name: "Vs Grand Prix: 2.Nc3 and 3.f4",
    description: "Grand Prix Attack: meet the wing setup with calm development, central control, and later counterplay against White's overextension.",
    moves: ["e4", "c5", "Nc3", "Nc6", "f4", "g6", "Nf3", "Bg7", "Bb5", "Nd4", "O-O", "e6", "d3", "Ne7", "Qe1", "O-O"],
    explanations: [
      "White takes space and prepares quick kingside play.",
      "Sicilian. Create imbalance and fight for {{square d4}} from the side.",
      "White avoids Open Sicilian structures and keeps the center more closed.",
      "Develop and control key squares, especially {{square d4}} and {{square e5}}.",
      "Grand Prix. White wants a fast wing attack before Black is fully coordinated.",
      "Build the bishop house and keep the kingside solid.",
      "White develops and keeps the attack flexible.",
      "Complete the fianchetto and keep long-range control of the center.",
      "White develops actively, but the bishop can help Black gain time with central piece play.",
      "Jump into the center and make White react. In anti-Sicilians, Black often improves by taking central squares instead of panicking on the wing.",
      "White castles and keeps attacking ideas alive.",
      "Solidify the dark squares and keep ...{{square d5}} in reserve.",
      "White supports the center and prepares the usual attacking maneuvers.",
      "The knight is flexible on {{square e7}} here, helping with king safety and later ...{{square d5}} ideas.",
      "White often wants Q{{square h4}} or Q{{square h4}}-{{square f2}} type pressure.",
      "Castle and finish development before deciding how to strike back."
    ]
  },

  {
    id: "sicilian-moscow-rossolimo-basic",
    name: "Vs Bb5+: Moscow and Rossolimo",
    description: "After 2.Nf3 d6 3.Bb5+ (Moscow) or 2...Nc6 3.Bb5 (Rossolimo), develop and get ready to unpin.",
    moves: ["e4", "c5", "Nf3", "d6", "Bb5+", "Bd7", "Bxd7+", "Qxd7", "O-O", "Nc6", "c4", "Nf6", "Nc3", "g6", "d3", "Bg7"],
    explanations: [
      "White claims space.",
      "Sicilian response.",
      "Develop and prepare {{square d4}}.",
      "Moscow move order. Keep control of {{square e5}} and prepare development.",
      "Check, aiming to disrupt development and sometimes trade pieces.",
      "Block and offer a trade, reducing White's pressure.",
      "White often takes to avoid retreating and to damage coordination.",
      "Recapture and keep development moving.",
      "Castle and keep a flexible structure.",
      "Develop and contest {{square d4}}.",
      "Grab queenside space and fight for {{square d5}}.",
      "Develop and pressure {{square e4}}.",
      "Develop and reinforce the center.",
      "Fianchetto plan for a solid setup.",
      "Develop and support central control.",
      "Complete fianchetto and pressure the diagonal."
    ]
  },



  {
    id: "sicilian-accelerated-dragon-d5-break",
    name: "Accelerated Dragon: punish Yugoslav setup with ...d5",
    description: "If White copies Dragon attacking ideas too early, keeping the pawn on d7 lets Black hit the center with ...d5 in one move.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "g6", "Nc3", "Bg7", "Be3", "Nf6", "f3", "O-O", "Qd2", "d5", "exd5", "Nxd5", "Nxc6", "bxc6"],
    explanations: [
      "White claims central space and opens lines for quick development.",
      "Sicilian. Use the c-pawn to fight for {{square d4}} without mirroring White's structure.",
      "Develop and prepare the central break with {{square d4}}.",
      "Develop immediately and add pressure to {{square d4}} before showing your full setup.",
      "White opens the center and asks Black to clarify the pawn structure.",
      "Trade the flank pawn for White's central pawn and reach an open Sicilian structure.",
      "White recaptures with development and central presence.",
      "Accelerated Dragon move order. The bishop belongs on {{square g7}} and Black still has not committed the d-pawn.",
      "Develop and reinforce {{square e4}} and {{square d5}} control.",
      "Complete the fianchetto and pressure the long diagonal.",
      "White copies Dragon attacking ideas and points toward long castling.",
      "Develop and hit {{square e4}} while staying ready for a central break.",
      "White reinforces {{square e4}} and prepares Q{{square d2}} with a Yugoslav style attack.",
      "Castle first. Black is ready to answer wing play with central counterplay.",
      "White signals queenside castling and a kingside pawn storm.",
      "This is the Accelerated Dragon point. Because the pawn is still on {{square d7}}, Black can break with ...{{square d5}} in one move.",
      "White usually takes because allowing Black to keep that center is even worse.",
      "Recapture with the knight, develop with tempo, and activate every piece at once.",
      "White often trades to reduce the pressure and simplify.",
      "The b-pawn recaptures toward the center, opens the b-file, and Black gets active piece play for free."
    ]
  },

  {
    category: "Anti-Sicilian",
    id: "sicilian-bowdler-e6-d5-punish",
    name: "Vs Bowdler: ...e6 and ...d5 with tempo",
    description: "Against 2.Bc4, block the bishop, prepare ...d5, and make that early bishop prove it belongs on c4.",
    moves: ["e4", "c5", "Bc4", "e6", "Nf3", "a6", "O-O", "Nf6", "Nc3", "d5", "exd5", "exd5", "Bb3", "Be7"],
    explanations: [
      "White takes space and keeps options open.",
      "Sicilian response, immediately contesting {{square d4}} and aiming for imbalance.",
      "Bowdler Attack. White develops as if Black had played ...{{square e5}}, but the bishop can become a target once the center opens.",
      "Block the bishop's diagonal right away and prepare a central strike with ...{{square d5}}.",
      "White develops and prepares to castle.",
      "A useful Sicilian move that supports ...{{square b5}} later and gives Black queenside space.",
      "White castles before the center is clarified.",
      "Develop and pressure {{square e4}} while keeping ...{{square d5}} ready.",
      "White develops naturally and keeps the {{bishop c4 full}}.",
      "Strike in the center with tempo. The {{bishop c4 full}} now has to justify its early development.",
      "White usually takes because leaving Black's {{pawn d5 full}} gives Black too much space.",
      "Recapture toward the center, open lines, and keep the {{bishop c4 full}} under pressure.",
      "The bishop retreats. That is the practical point of the whole idea.",
      "Finish development and enjoy the cleaner center and easier piece play."
    ]
  },

  {
    category: "Anti-Sicilian",
    id: "sicilian-bowdler-g6-nge7-d5-break",
    name: "Vs Bowdler: fianchetto shell and ...d5 break",
    description: "A simple anti-Bowdler setup: build the bishop house, keep the c-pawn in reserve, then hit the center with ...d5 once the count works.",
    moves: ["e4", "c5", "Bc4", "g6", "Nf3", "Bg7", "O-O", "Nc6", "d3", "e6", "Nc3", "Nge7", "Re1", "d5", "exd5", "exd5", "Bb3", "O-O", "h3", "Bg4"],
    explanations: [
      "White chooses an early bishop move instead of building a full center first.",
      "Sicilian. Since White did not offer {{square d4}}, Black keeps the c-pawn for later and develops normally.",
      "Bowdler setup. The bishop looks active now, but it can become a target when the center opens.",
      "Start the bishop house. The fianchetto gives Black long-range control before any pawn break happens.",
      "White develops and prepares to castle.",
      "Put the {{bishop g7 full}} before arguing about the center.",
      "White castles and hopes the setup stays quiet.",
      "Develop the queenside knight first. If White ever trades it, the b-pawn recaptures and the rook gets a useful file later.",
      "White supports {{square e4}} and keeps the center closed for the moment.",
      "Because the c-pawn is still on {{square c5}}, Black uses the neighboring e-pawn to prepare the central break.",
      "White develops and adds another attacker to {{square d5}}.",
      "The knight belongs on {{square e7}} here. It keeps the c-pawn flexible and adds one more piece to the {{square d5}} battle.",
      "A useful rook move. White steps off tactics and hints at {{square e5}} ideas.",
      "Strike now. White attacks {{square d5}} three times, but Black can match that count and open the center anyway.",
      "White usually takes to avoid giving Black a free space advantage.",
      "Recapture toward the center and keep more space than White.",
      "The bishop retreats. That is the practical point of the whole setup.",
      "Castle and finish development before looking for tactics.",
      "White makes luft and asks what Black's dark bishop will do.",
      "Pin the knight and make White's kingside setup less comfortable."
    ]
  },

  {
    category: "Classical Sicilian",
    id: "sicilian-classical-ng4-qxf2-trap",
    name: "Classical: ...Ng4 and ...Qxf2# trap",
    description: "A common trap when White copies Be3 systems too casually. ...Ng4 and ...Qb6 create a direct mate threat on f2.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "d6", "Be3", "Ng4", "Bg5", "Qb6", "Nb3", "Qxf2#"],
    explanations: [
      "White takes central space and opens lines for the pieces.",
      "Sicilian. Fight for {{square d4}} with an imbalanced pawn structure.",
      "Develop and prepare the Open Sicilian.",
      "Develop and pressure {{square d4}} immediately.",
      "White opens the center and heads for standard Sicilian play.",
      "Trade in the center and reach an open, tactical structure.",
      "White recaptures with development and central presence.",
      "Develop and hit {{square e4}}, forcing White to defend accurately.",
      "White covers {{square e4}} and adds another piece to the center.",
      "Classical Sicilian. Support the center and keep your bishops flexible.",
      "White often chooses B{{square e3}} to copy Dragon style attacking setups.",
      "Challenge the bishop immediately. Black does not have to sit and watch White build up freely.",
      "White keeps the bishop active, but the move also clears the diagonal to {{square f2}}.",
      "Hit {{square b2}}, pressure {{square d4}}, and most importantly line up the queen against {{square f2}}.",
      "This natural knight retreat looks sensible, but it walks straight into the mating idea.",
      "The queen lands on {{square f2}} supported by the {{knight g4 full}}, and White is mated."
    ]
  },

  {
    category: "Kan",
    id: "sicilian-paulsen-bb4-d5-break",
    name: "Paulsen and Kan: ...Qc7, ...Bb4, and ...d5",
    description: "This flexible setup makes queenside-castling attacks much harder because Black can pin the knight and break in the center.",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6", "Nc3", "Qc7", "Be3", "Nf6", "Qd2", "Bb4", "f3", "d5", "exd5", "Nxd5"],
    explanations: [
      "White takes space and opens lines.",
      "Sicilian. Black accepts asymmetry from move one.",
      "Develop and prepare {{square d4}}.",
      "Keep the structure flexible and open the dark bishop.",
      "White challenges the center directly.",
      "Trade the flank pawn for White's central pawn and reach open Sicilian play.",
      "White recaptures with development.",
      "A typical Kan move. It stops N{{square b5}} and keeps ...Q{{square c7}} and ...{{square b5}} available.",
      "White develops and reinforces the center.",
      "Paulsen style. The queen supports ...{{square d5}} and keeps Black's setup flexible.",
      "White points toward the usual B{{square e3}} and Q{{square d2}} attacking structure.",
      "Develop and hit {{square e4}} while waiting to see how White commits.",
      "White signals queenside castling and a kingside attack.",
      "Pin the knight and make White's attacking setup less comfortable.",
      "White has to defend {{square e4}} because the {{knight c3 full}} is pinned.",
      "Now hit the center. This is the main point of the setup, answer the flank attack with central counterplay.",
      "White usually takes because keeping the tension favors Black.",
      "Recapture with a piece, keep the initiative, and get active squares everywhere."
    ]
  },

  {
    category: "Smith-Morra Gambit",
    id: "sicilian-smith-morra-e5-trap-warning",
    name: "Smith-Morra: do not walk into the e5 and Bxf7+ tactic",
    description: "A tactical warning line. If Black accepts the gambit and develops carelessly, White can win the queen with e5 and Bxf7+.",
    moves: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "d6", "Bc4", "Nf6", "e5", "dxe5", "Bxf7+", "Kxf7", "Qxd8"],
    explanations: [
      "White takes central space and opens the queen and bishop.",
      "Sicilian. Black chooses imbalance immediately.",
      "White offers the Smith-Morra Gambit to get speed and active pieces.",
      "Black accepts the pawn. That is playable, but accuracy matters.",
      "White keeps investing in rapid development instead of material.",
      "Accepting the second gambit pawn opens lines, but Black's king and queen need respect.",
      "White recaptures with a piece and gets exactly the development they wanted.",
      "Natural development and central control.",
      "White develops another piece and prepares to castle quickly.",
      "A normal looking support move, but Black still has to watch tactical details.",
      "The bishop points at {{square f7}}, which is the soft spot in many accepted Morra positions.",
      "This natural move is the mistake. Black walks into a central tactic.",
      "White strikes in the center and opens lines before Black is coordinated.",
      "Taking the pawn looks greedy, but it allows the real point.",
      "Deflect the king away from the queen's defense and rip open the position.",
      "Forced. Black's king takes, but now the queen is loose.",
      "White wins the queen. The lesson is simple: in the Morra, do not develop on autopilot."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-rc8-nxe4-sac",
    name: "Dragon Yugoslav: ...Rc8 and ...Nxe4 tactics",
    description: "Yugoslav setup. Black expands with ...b5 and the exchange sacrifice ideas appear on d4.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "Kb1", "a5", "a4", "bxa4", "Nxa4", "Bxa4",
      "Bxa4", "Rc4", "Bb3", "Nxe4", "fxe4", "Rxd4"
    ],
    explanations: [
      "White grabs space and opens lines.",
      "Sicilian, immediately fights for {{square d4}}.",
      "Develop and prepare {{square d4}}.",
      "Keep control of {{square e5}} and support the center.",
      "White commits to the Open Sicilian.",
      "Open the center on your terms.",
      "White develops while recapturing.",
      "Hit {{square e4}} and develop.",
      "Defend {{square e4}} and develop.",
      "Dragon structure, aiming for ...B{{square g7}}.",
      "Yugoslav style, supports queenside castling and attacks.",
      "Put the bishop on the long diagonal.",
      "Reinforce {{square e4}} and stop ...N{{square g4}} ideas.",
      "Get king safety and connect rooks.",
      "Prepare long castle and connect to kingside pressure.",
      "Develop and pressure {{square d4}}.",
      "Add pressure on {{square f7}} and accelerate the attack.",
      "Develop and connect rooks, also covers key squares.",
      "White castles long and the game becomes race like.",
      "Typical Dragon rook placement against c and {{square c2}} squares.",
      "Keep bishop safe and keep pressure lines.",
      "Remove the centralized knight and reduce white pressure.",
      "White keeps a piece on the diagonal and recaptures.",
      "Queenside expansion, also hits the bishop and opens files.",
      "Standard safety move, avoid checks on {{square a1}} diagonal.",
      "Keep expanding and support ...{{square a4}} or ...{{square b4}} ideas.",
      "White tries to stop the pawn storm or force structure.",
      "Accept, open a file and create targets.",
      "White recaptures to remove the pawn and stabilize.",
      "Trade off that knight and reduce defense.",
      "White recaptures and keeps pieces active.",
      "Rook lift to pressure and enable tactics on {{square d4}} and {{square e4}}.",
      "Retreat and keep bishop while avoiding tactics.",
      "Tactical strike, grabbing central pawn and opening lines.",
      "White accepts and opens the f file and center.",
      "Follow up by winning material back or simplifying into advantage."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-h4-h5-qa5-rcx3",
    name: "Dragon Yugoslav: ...Qa5 and ...Rxc3 sequence",
    description: "Yugoslav attack line where Black hits c3 and the queen joins with checks and captures.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "hxg6", "fxg6",
      "Bh6", "Bxh6", "Qxh6", "Rxc3", "bxc3", "Qxc3", "Nb3", "Rc8"
    ],
    explanations: [
      "White takes space and aims for fast development.",
      "Sicilian, create imbalance and fight for {{square d4}}.",
      "Develop and prepare {{square d4}}.",
      "Solid center support, control {{square e5}}.",
      "White opens the center.",
      "Exchange and open lines for active play.",
      "White centralizes a knight.",
      "Develop and hit {{square e4}}.",
      "Defend {{square e4}} and develop.",
      "Dragon fianchetto plan.",
      "Yugoslav setup, supports long castle and attack.",
      "Bishop targets the long diagonal.",
      "Reinforce {{square e4}} and limit ...N{{square g4}}.",
      "King safety and rook connection.",
      "Support queenside castling and connect to {{square h6}} ideas.",
      "Develop and pressure {{square d4}}.",
      "Commit to opposite side castling.",
      "Develop and connect pieces, support queenside play.",
      "White starts pawn storm on the kingside.",
      "Rook to c file, target {{square c2}} and support tactics.",
      "White supports {{square h5}} and keeps space.",
      "Centralize and hit key squares, also targets {{square c4}} and {{square f3}}.",
      "Continue the pawn storm and open lines.",
      "Queen joins, pressures {{square a2}} and {{square c3}} and adds tactical threats.",
      "White opens the h file and tries to expose the king.",
      "Recapture and keep the f file structure, also open f file.",
      "Trade the key Dragon bishop or force concessions.",
      "Remove that attacker immediately.",
      "White keeps attacking chances on the h file.",
      "Typical exchange sacrifice idea on {{square c3}} to rip open lines.",
      "Forced recapture, structure changes and b file opens.",
      "Queen grabs material and keeps threats on {{square a1}} and {{square d4}}.",
      "Hit the queen and try to stabilize.",
      "Consolidate and keep pressure on the c file."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-kb1-qa5-nd5-queen-trade",
    name: "Dragon Yugoslav: Nd5 and queen trade sequence",
    description: "Yugoslav line where White jumps Nd5 and Black simplifies into tactics and endgame pressure.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "Kb1", "Qa5", "Nd5", "Qxd2",
      "Nxe7+", "Kh8", "Rxd2", "Rce8", "Nd5", "Nxd5", "exd5", "Nxf3",
      "Nxf3", "Rxe3"
    ],
    explanations: [
      "White takes space.",
      "Sicilian structure and counterplay.",
      "Develop and prepare {{square d4}}.",
      "Hold {{square e5}} and support the center.",
      "White opens the center.",
      "Exchange to create the Open Sicilian structure.",
      "White centralizes.",
      "Develop and hit {{square e4}}.",
      "Defend {{square e4}} and develop.",
      "Dragon plan, ...B{{square g7}} next.",
      "Yugoslav style attack prep.",
      "Place bishop on the long diagonal.",
      "Support {{square e4}} and limit ...N{{square g4}}.",
      "King safety.",
      "Prepare long castle and coordinate attack.",
      "Develop and pressure {{square d4}}.",
      "Opposite side castling, race begins.",
      "Develop and connect pieces.",
      "White starts direct pawn storm.",
      "Put rook on the c file for counterplay.",
      "Support {{square h5}} and keep pressure.",
      "Centralize and challenge key squares.",
      "Improve king safety on the queenside.",
      "Queen joins queenside pressure and checks threats.",
      "White jumps in to create tactics and hit {{square c7}} and {{square e7}} squares.",
      "Simplify by trading queens, reducing white attack speed.",
      "Tactical check and fork ideas, force king response.",
      "Step away from checks and keep pieces protected.",
      "Recapture the queen and keep rooks connected.",
      "Bring rook to e file and aim at {{square e3}} and {{square e4}} squares.",
      "Recentralize, keep pressure and block some lines.",
      "Remove the knight and simplify.",
      "Recapture and open the e file and diagonal.",
      "Tactic to win material or damage king safety.",
      "Recapture and try to hold structure.",
      "Grab pawn and keep initiative with active rook."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-qa5-nxf3-queen-exchange",
    name: "Dragon Yugoslav: ...Nxf3 and queen exchange",
    description: "Black uses ...Nxf3 and queen trades to convert tactical pressure into material.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "Kb1", "Nxf3",
      "Nxf3", "Rxc3", "Qxc3", "Qxc3", "bxc3", "Bxg4", "Be2", "Nxe4",
      "Bd4", "e5", "Bxa7", "Nxc3+", "Kb2", "Nxd1+"
    ],
    explanations: [
      "White takes space.",
      "Sicilian counterplay and imbalance.",
      "Develop and prepare {{square d4}}.",
      "Solid, control {{square e5}}.",
      "Open center plan.",
      "Exchange and open lines.",
      "White develops by recapturing.",
      "Hit {{square e4}} and develop.",
      "Defend {{square e4}} and develop.",
      "Dragon fianchetto.",
      "Yugoslav setup.",
      "Bishop on long diagonal.",
      "Support center and control {{square g4}}.",
      "King safety.",
      "Support long castle and {{square h6}} ideas.",
      "Develop and hit {{square d4}}.",
      "Commit to opposite side castling.",
      "Develop and coordinate pieces.",
      "Pawn storm attempt.",
      "Counterplay on c file.",
      "Support {{square h5}} push.",
      "Centralize, hit {{square c4}} and {{square f3}} structures.",
      "Open lines on kingside.",
      "Queen activates against {{square a2}} and {{square c3}}.",
      "Safety move, reduce checks.",
      "Remove defender and open lines for queen and rook.",
      "White recaptures to avoid losing material.",
      "Sacrifice on {{square c3}} to open the king and win structure.",
      "White tries to keep material balanced and stop threats.",
      "Trade queens to convert attack into endgame gains.",
      "Forced recapture, structure changes.",
      "Win pawn or remove attacker, reduce kingside pressure.",
      "Develop and protect key squares.",
      "Central pawn grab, also hits {{square c3}} weaknesses indirectly.",
      "Try to anchor a piece and aim for activity.",
      "Kick the bishop and gain central space.",
      "Grab pawn, but it can be risky if pieces get trapped.",
      "Fork and check to win material and simplify.",
      "Move king and stay in game.",
      "Win the rook, converting tactics into decisive material."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-hxg6-qa1-check",
    name: "Dragon Yugoslav: ...Qa1+ and ...Qxd4+",
    description: "Queen invades with checks after the c3 break and open diagonals.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "hxg6", "fxg6",
      "Bh6", "Bxh6", "Qxh6", "Rxc3", "bxc3", "Qxc3", "g5", "Qa1+",
      "Kd2", "Qxd4+"
    ],
    explanations: [
      "White takes space.",
      "Sicilian counterplay.",
      "Develop and prepare {{square d4}}.",
      "Support center and control {{square e5}}.",
      "Open the center.",
      "Exchange and open lines.",
      "White recaptures with development.",
      "Attack {{square e4}} and develop.",
      "Defend {{square e4}} and develop.",
      "Dragon fianchetto plan.",
      "Yugoslav style setup.",
      "Bishop on long diagonal.",
      "Reinforce {{square e4}} and limit piece jumps.",
      "King safety.",
      "Prepare long castle and attack.",
      "Develop and pressure {{square d4}}.",
      "Opposite side castling.",
      "Develop and connect pieces.",
      "Start pawn storm.",
      "Counterplay against {{square c2}} and {{square c3}}.",
      "Support {{square h5}}.",
      "Centralize and threaten key squares.",
      "Push for open lines.",
      "Queen joins queenside threats.",
      "Open lines to the king.",
      "Recapture and keep structure while opening f file.",
      "Trade off Dragon bishop or force weakening.",
      "Remove the attacker.",
      "Keep attack alive with queen on h file.",
      "Break {{square c3}} to open the king and win material.",
      "Forced structure change.",
      "Queen penetrates and targets {{square a1}} and {{square d4}} lines.",
      "Try to chase pieces and create threats.",
      "Immediate invasion, check based on open diagonal.",
      "King steps away and tries to survive.",
      "Take central pawn with check, converting attack into material."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-h4-rc4-nxe4-sac",
    name: "Dragon Yugoslav: h4 included before ...Nxe4",
    description: "Same tactical theme as the earlier ...Rc4 ...Nxe4 line, but with h4 instead of Kb1.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a4", "bxa4", "Nxa4", "Bxa4",
      "Bxa4", "Rc4", "Bb3", "Nxe4", "fxe4", "Rxd4"
    ],
    explanations: [
      "White takes space.",
      "Sicilian counterplay.",
      "Develop and prepare {{square d4}}.",
      "Keep {{square e5}} under control.",
      "Open the center.",
      "Exchange and open lines.",
      "White centralizes.",
      "Pressure {{square e4}}.",
      "Defend and develop.",
      "Dragon fianchetto.",
      "Yugoslav setup.",
      "Bishop on long diagonal.",
      "Support {{square e4}} and control {{square g4}}.",
      "King safety.",
      "Prepare long castle.",
      "Develop and pressure {{square d4}}.",
      "Add pressure and speed up attack.",
      "Develop and coordinate pieces.",
      "Opposite side castling.",
      "Counterplay on c file.",
      "Keep bishop safe.",
      "Remove white knight and reduce central control.",
      "White recaptures to keep presence.",
      "Expansion and tempo on pieces.",
      "White continues kingside pawn storm.",
      "Push queenside pawns for attack.",
      "White tries to slow down queenside play.",
      "Open the a file and keep initiative.",
      "White recaptures to stabilize.",
      "Trade to reduce defense.",
      "White keeps pieces active.",
      "Rook lift for pressure and tactics.",
      "Step away and keep bishop.",
      "Tactical strike in the center.",
      "White accepts and opens lines.",
      "Follow up by taking the bishop or central pawn line, converting tactics."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-a4-a3-a2-b3-endgame-push",
    name: "Dragon Yugoslav: queenside pawn break into endgame squeeze",
    description: "Long line with queenside pawn breaks, queen safety moves, and converting to a passed pawn plan.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a3", "b4", "axb4", "axb4",
      "Nd5", "Nxd5", "Bxg7", "Kxg7", "exd5", "Qa5", "Qd4+", "Kg8",
      "h5", "Bf5", "g4", "Bxc2", "Bxc2", "b3", "Rh2", "Rc7"
    ],
    explanations: [
      "White takes space.",
      "Sicilian counterplay.",
      "Develop and prepare {{square d4}}.",
      "Solid and controls {{square e5}}.",
      "Open center plan.",
      "Exchange and open lines.",
      "White recaptures with development.",
      "Pressure {{square e4}}.",
      "Defend and develop.",
      "Dragon setup.",
      "Yugoslav setup.",
      "Bishop on diagonal.",
      "Support {{square e4}} and slow ...N{{square g4}}.",
      "King safety.",
      "Prepare long castle and attack.",
      "Develop and pressure {{square d4}}.",
      "Aggressive bishop placement.",
      "Develop and coordinate.",
      "Opposite side castling.",
      "Rook on open file, typical Dragon play.",
      "Keep bishop safe.",
      "Trade off the central knight.",
      "White recaptures to keep piece activity.",
      "Expand and gain space, threaten to open files.",
      "White keeps pawn storm plan.",
      "Black expands on queenside, matching the race.",
      "White prepares to meet ...{{square b4}} with ax{{square b4}}, also slow a pawn push.",
      "Break open the queenside pawn structure.",
      "White accepts to avoid getting locked up.",
      "Black recaptures and opens the a file.",
      "White jumps in to create tactics and simplify.",
      "Remove the intruder.",
      "White trades the Dragon bishop's partner and reduces pressure.",
      "Recapture and keep king safe enough.",
      "Open lines and create a pawn majority structure.",
      "Queen activates and targets {{square a2}} and {{square a3}} squares.",
      "White gives check and tries to force king placement.",
      "Step out and avoid tactics.",
      "White continues kingside pawn storm.",
      "Activate bishop and hit {{square c2}} and {{square e4}} lines.",
      "White tries to chase the bishop and keep attack going.",
      "Tactic to win material and create threats.",
      "White recaptures and tries to reduce damage.",
      "Create a passed pawn and fix white pieces.",
      "Defensive rook move, prepare to meet b pawn.",
      "Consolidate and support the passed pawn plan."
    ]
  },

  {
    id: "sicilian-classical-sac-line-be2-qb6-queen-grab",
    name: "Tactics: Be2 and ...Qb6 pawn grab",
    description: "Sharp tactical sequence where the queen grabs b2 and lines open with checks.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be2", "Bg7", "Be3", "O-O", "O-O", "Nc6", "f4", "Qb6", "Nf5", "Qxb2",
      "Nxg7", "Qxc3", "Bd2", "Qd4+", "Kh1", "Kxg7"
    ],
    explanations: [
      "White takes space.",
      "Sicilian counterplay.",
      "Develop and prepare {{square d4}}.",
      "Solid center support.",
      "Open the center.",
      "Exchange and open lines.",
      "White develops by recapturing.",
      "Develop and pressure {{square e4}}.",
      "Defend {{square e4}} and develop.",
      "Dragon structure.",
      "Quieter development, keep options open.",
      "Fianchetto bishop, pressure on diagonal.",
      "Support center and develop, watch tactics on {{square b2}}.",
      "King safety.",
      "White also castles, reducing immediate mate threats.",
      "Develop and pressure {{square d4}}.",
      "Space grab, also creates targets.",
      "Pressure {{square b2}} and {{square d4}}, typical tactical idea.",
      "Jump in to create threats and hit {{square e7}} and {{square g7}} areas.",
      "Queen grabs pawn, accepting risk for material.",
      "White takes bishop, reducing dragon pressure.",
      "Queen grabs {{square c3}} and hits multiple targets.",
      "Try to trap or challenge the queen path.",
      "Check to force king move and keep initiative.",
      "Step away and avoid further checks.",
      "Black recaptures, restoring material balance and ending the tactic."
    ]
  },

  {
    id: "sicilian-bb5-anti-sicilian-bc4-plan",
    name: "Anti Sicilian: 3.Bc4 setup vs ...Nf6",
    description: "Early Bc4 against the Sicilian, play normal development and castle.",
    moves: ["e4", "c5", "Nf3", "d6", "Bc4", "Nf6", "Nc3", "e6", "d3", "Be7", "Bg5", "O-O", "O-O", "a6", "Re1", "b5"],
    explanations: [
      "White takes space.",
      "Sicilian response.",
      "Develop and prepare central play.",
      "Solid support and control {{square e5}}.",
      "Fast development aiming at {{square f7}} and quick plans.",
      "Develop and hit {{square e4}}.",
      "Develop and defend {{square e4}}.",
      "Solid, open bishop and prepare ...{{square d5}} breaks later.",
      "Keep center controlled and support {{square e4}}.",
      "Develop and prepare to castle.",
      "Pin the knight and increase pressure.",
      "King safety and rook connection.",
      "Castle and prepare central play.",
      "Gain space and ask the bishop about its square, also supports ...{{square b5}}.",
      "Put rook on e-file, support {{square e4}}-{{square e5}} breaks or tactics.",
      "Queenside expansion and gain tempo on pieces."
    ]
  },

  {
  id: "sicilian-dragon-yugoslav-h5-hxg6-continuation",
  name: "Dragon Yugoslav: h5-hxg6 continuation after Qd4+",
  description: "Dragon Yugoslav line with h5 push, ...Bf5 development, and hxg6 capture.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a3", "b4", "axb4", "axb4",
    "Nd5", "Nxd5", "Bxg7", "Kxg7", "exd5", "Qa5", "Qd4+", "Kg8",
    "h5", "Bf5", "hxg6", "fxg6"
  ],
  explanations: [
    "White claims the center.",
    "Sicilian counterplay.",
    "Develop and prepare {{square d4}}.",
    "Solid support for the center.",
    "Open the center.",
    "Exchange and create open lines.",
    "White recaptures and centralizes.",
    "Pressure {{square e4}} and develop.",
    "Defend {{square e4}} and develop.",
    "Dragon fianchetto setup.",
    "Yugoslav system, prepares queenside castling.",
    "Bishop on the long diagonal.",
    "Reinforce {{square e4}} and control {{square g4}} square.",
    "King safety.",
    "Connect rooks and prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "Active bishop placement, eyes {{square f7}}.",
    "Develop and connect rooks.",
    "Opposite side castling, race begins.",
    "Counterplay on the c-file.",
    "Retreat bishop to safety while keeping pressure.",
    "Trade off the centralized knight.",
    "White recaptures to maintain piece activity.",
    "Queenside expansion, gains space.",
    "White starts kingside pawn storm.",
    "Black expands on queenside to match.",
    "White prepares for ...{{square b4}} push.",
    "Break open the queenside structure.",
    "White captures to avoid being locked in.",
    "Black recaptures, opening the a-file.",
    "Knight jump to create threats and simplify.",
    "Capture the intruding knight.",
    "Trade the Dragon bishop, reducing black's attack.",
    "King recaptures, remaining safe.",
    "Recapture and create pawn structure.",
    "Queen activates, targeting weak squares.",
    "Check to gain time and challenge black's king.",
    "King steps back to {{square g8}}, avoiding further checks.",
    "Continue kingside attack with pawn push.",
    "Develop bishop actively, hitting {{square c2}} and supporting queenside.",
    "Exchange to open the h-file and attack.",
    "Recapture, keeping pawn structure and opening f-file for counterplay."
  ]
},

{
  id: "sicilian-dragon-be2-ng4-variation",
  name: "Dragon: Be2 with ...Ng4 variation",
  description: "Classical Dragon with Be2 where black plays ...Ng4 to trade bishops and develop initiative.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be2", "Bg7", "Be3", "O-O", "Qd2", "Nc6", "O-O-O", "Ng4",
    "Bxg4", "Bxg4", "f3", "Be6", "h4", "Qa5"
  ],
  explanations: [
    "White claims the center.",
    "Sicilian response, fighting for {{square d4}}.",
    "Develop and prepare {{square d4}}.",
    "Solid center support.",
    "Open the center.",
    "Exchange and create open lines.",
    "White recaptures and centralizes.",
    "Develop and pressure {{square e4}}.",
    "Defend {{square e4}} and develop.",
    "Dragon fianchetto.",
    "Classical development, less aggressive than B{{square c4}}.",
    "Bishop on the long diagonal.",
    "Develop bishop and support center.",
    "King safety.",
    "Prepare queenside castling.",
    "Develop and pressure {{square d4}}.",
    "White castles queenside.",
    "Knight jump to challenge the {{square e3}} bishop.",
    "White trades to avoid doubled pawns.",
    "Black recaptures, developing with tempo.",
    "Reinforce {{square e4}} and limit bishop's retreat squares.",
    "Bishop retreats to active diagonal.",
    "White starts kingside expansion.",
    "Queen activates, putting pressure on queenside."
  ]
},

{
  id: "sicilian-dragon-be2-ng4-nxe6-line",
  name: "Dragon: Be2 ...Ng4 with Nxe6 exchange",
  description: "Classical Dragon line where white exchanges on e6 and trades bishops with Bh6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be2", "Bg7", "Be3", "O-O", "Qd2", "Nc6", "O-O-O", "Ng4",
    "Bxg4", "Bxg4", "f3", "Be6", "Nxe6", "fxe6", "Bh6", "Qa5",
    "Bxg7", "Kxg7"
  ],
  explanations: [
    "White takes center.",
    "Sicilian counterplay.",
    "Develop and prepare {{square d4}}.",
    "Support center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon setup.",
    "Classical development.",
    "Fianchetto bishop.",
    "Develop bishop.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "White castles queenside.",
    "Challenge the {{square e3}} bishop.",
    "Trade bishop for knight.",
    "Recapture and develop.",
    "Support {{square e4}} and limit bishop.",
    "Bishop finds active square.",
    "Exchange to damage black's pawn structure.",
    "Recapture, creating doubled e-pawns but opening f-file.",
    "Threaten to trade the Dragon bishop.",
    "Queen activates with threats.",
    "Execute the bishop trade.",
    "King recaptures, remaining in center but with pawn cover."
  ]
},

{
  id: "sicilian-dragon-yugoslav-g4-be6-line",
  name: "Dragon Yugoslav: g4 with ...Be6 response",
  description: "Yugoslav attack with early g4, met by ...Be6 and knight exchange on e6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "g4", "Be6",
    "Nxe6", "fxe6", "O-O-O", "Ne5"
  ],
  explanations: [
    "White claims center.",
    "Sicilian defense.",
    "Develop and prepare {{square d4}}.",
    "Solid center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon fianchetto.",
    "Yugoslav setup.",
    "Bishop on long diagonal.",
    "Support {{square e4}}.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "Early kingside pawn storm.",
    "Develop bishop actively, hitting {{square d5}} and {{square c4}}.",
    "Exchange to damage black's pawn structure.",
    "Recapture, creating doubled e-pawns but opening f-file.",
    "White completes queenside castling.",
    "Knight centralizes to strong outpost."
  ]
},

{
  id: "sicilian-dragon-yugoslav-g5-nh5-line",
  name: "Dragon Yugoslav: g5 forcing ...Nh5",
  description: "Yugoslav attack with g4-g5 push, forcing knight to h5 where it's less active.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
    "g4", "Rc8", "g5", "Nh5"
  ],
  explanations: [
    "White takes center.",
    "Sicilian counterplay.",
    "Develop and prepare {{square d4}}.",
    "Support center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon setup.",
    "Yugoslav system.",
    "Bishop on diagonal.",
    "Support {{square e4}}.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "White castles queenside.",
    "Develop bishop.",
    "Start kingside pawn storm.",
    "Rook to c-file for counterplay.",
    "Push pawn, attacking knight.",
    "Knight retreats to edge, avoiding exchange but less active."
  ]
},

{
  id: "sicilian-dragon-yugoslav-h5-a4-bxf6",
  name: "Dragon Yugoslav: h5, ...a4, and Bxf6 exchange",
  description: "Yugoslav line with h5 push, met by ...a4 pawn advance and bishop exchange on f6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "h5", "a4",
    "Bxf6", "exf6"
  ],
  explanations: [
    "White takes center.",
    "Sicilian defense.",
    "Develop and prepare {{square d4}}.",
    "Solid center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon fianchetto.",
    "Yugoslav setup.",
    "Bishop on long diagonal.",
    "Support {{square e4}}.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "Active bishop placement.",
    "Develop bishop.",
    "Opposite side castling.",
    "Rook to c-file.",
    "Retreat bishop.",
    "Trade knight.",
    "Recapture with bishop.",
    "Queenside expansion.",
    "Kingside pawn storm.",
    "Black's queenside counter.",
    "Continue kingside attack.",
    "Pawn push, threatening to trap bishop.",
    "Trade bishop for knight to relieve pressure.",
    "Recapture, doubling pawns but opening e-file."
  ]
},

{
  id: "sicilian-dragon-yugoslav-h4-h5-be2-line",
  name: "Dragon Yugoslav: h4 met by ...h5 with Be2 setup",
  description: "Yugoslav attack where black responds to h4 with ...h5, blocking white's pawn storm.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
    "h4", "h5", "Be2", "Rc8"
  ],
  explanations: [
    "White claims center.",
    "Sicilian response.",
    "Develop and prepare {{square d4}}.",
    "Solid center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon setup.",
    "Yugoslav system.",
    "Bishop on diagonal.",
    "Support {{square e4}}.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "White castles queenside.",
    "Develop bishop.",
    "Start kingside pawn storm.",
    "Black blocks the pawn advance, stopping {{square h5}} ideas.",
    "Develop bishop, more solid than B{{square c4}}.",
    "Rook to c-file for queenside counterplay."
  ]
},

{
  id: "sicilian-dragon-yugoslav-nd5-early-line",
  name: "Dragon Yugoslav: Early Nd5 before h4",
  description: "Yugoslav line where white plays Nd5 immediately after ...b5, skipping h4 initially.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "Nd5", "Nxd5", "Bxg7", "Kxg7",
    "exd5", "a5", "a3", "Kg8"
  ],
  explanations: [
    "White claims center.",
    "Sicilian defense.",
    "Develop and prepare {{square d4}}.",
    "Solid center.",
    "Open center.",
    "Exchange.",
    "White recaptures.",
    "Pressure {{square e4}}.",
    "Defend and develop.",
    "Dragon fianchetto.",
    "Yugoslav setup.",
    "Bishop on long diagonal.",
    "Support {{square e4}}.",
    "King safety.",
    "Prepare long castle.",
    "Develop and pressure {{square d4}}.",
    "Active bishop placement.",
    "Develop bishop.",
    "Opposite side castling.",
    "Rook to c-file.",
    "Retreat bishop.",
    "Trade knight.",
    "Recapture with bishop.",
    "Queenside expansion.",
    "Knight jump to {{square d5}}, creating threats.",
    "Capture the knight.",
    "Trade the Dragon bishop.",
    "King recaptures.",
    "Recapture, creating passed d-pawn.",
    "Black continues queenside expansion.",
    "White prepares to meet ...{{square a4}}.",
    "King steps back to {{square g8}}, connecting rooks."
  ]
},

  {
    id: "sicilian-closed-mainline-g3-g6",
    name: "Closed Sicilian: g3 setup vs ...g6",
    description: "Closed Sicilian: White plays g3 and d3. Black fianchettos and strikes with ...d6 and ...e5.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "d6", "Be3", "e5", "Nf3", "Nge7", "O-O", "O-O"],
    explanations: [
      "White takes space and keeps options for Open or Closed setups.",
      "Sicilian. Black fights for {{square d4}} and creates an imbalanced structure.",
      "Closed Sicilian move order, keep the d pawn flexible and develop.",
      "Develop and add control of {{square d4}} and {{square e5}}.",
      "Commit to a kingside fianchetto and a slower buildup.",
      "Mirror the fianchetto, aiming for ...B{{square g7}} pressure on the long diagonal.",
      "Place the bishop on the long diagonal and support central breaks later.",
      "Develop bishop and increase control of the center.",
      "Keep the center closed, support {{square e4}}, and prepare piece development.",
      "Solid, supports ...{{square e5}} and controls key central squares.",
      "Develop and support queenside development, also eyes {{square c5}} squares.",
      "Stake out space and reduce white's easy {{square f4}} break, typical Closed Sicilian plan.",
      "Develop naturally and prepare to castle.",
      "Develop flexibly, keeping options like ...{{square f5}} or ...B{{square e6}}.",
      "King safety and connect rooks before attacking.",
      "Match castling and keep the position stable before choosing pawn breaks."
    ]
  },

  {
    id: "sicilian-closed-mainline-g3-e6",
    name: "Closed Sicilian: g3 setup vs ...e6",
    description: "Closed Sicilian where Black keeps the c-pawn, uses ...e6 and ...Nge7, and breaks with ...d5 once the center can be challenged cleanly.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "e6", "Bg2", "Nge7", "d3", "d5", "exd5", "exd5", "Nf3", "Be6", "O-O", "Bd7"],
    explanations: [
      "White takes central space.",
      "Sicilian structure. Black fights for {{square d4}} and keeps an imbalanced game from move one.",
      "Closed move order. White delays {{square d4}} and aims for a slower kingside build.",
      "Develop and control the key central squares.",
      "White prepares a fianchetto and keeps the center closed for the moment.",
      "Because the c-pawn is still on {{square c5}}, Black uses the neighboring e-pawn to prepare a later central strike.",
      "The {{bishop g2 full}} adds one more attacker to {{square d5}} and supports White's usual Closed Sicilian plans.",
      "The knight belongs on {{square e7}} here. It keeps the c-pawn flexible and adds another defender and attacker around {{square d5}}.",
      "White supports {{square e4}} and finishes the basic shell.",
      "Now Black can strike. White attacks {{square d5}} three times, but Black can match that count and challenge the center anyway.",
      "White usually takes to avoid giving Black a free space advantage.",
      "Recapture toward the center and keep more central space than White.",
      "White develops and prepares to castle.",
      "Develop actively and keep pressure on {{square c2}}, {{square d5}}, and the dark squares.",
      "Castle and get the king safe before the middlegame plans start.",
      "The bishop drops back to a useful square and keeps the whole position coordinated."
    ]
  },

  {
    id: "sicilian-closed-f4-plan-quick",
    name: "Closed Sicilian: quick f4 plan",
    description: "Closed Sicilian where White plays d3 and f4. Black responds with ...g6 and ...Bg7, then ...d6.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "d6", "f4", "e6", "Nf3", "Nge7", "O-O", "O-O"],
    explanations: [
      "White takes space and keeps options open.",
      "Sicilian counterplay.",
      "Closed move order, develop and keep d pawn flexible.",
      "Develop and contest key central squares.",
      "Prepare a kingside fianchetto.",
      "Fianchetto structure for black as well.",
      "Bishop supports central breaks and kingside play.",
      "Black mirrors and sets long diagonal pressure.",
      "Keep center closed and prepare {{square f4}} without losing {{square e4}}.",
      "Solid support, keeps ...{{square e5}} available.",
      "Main Closed Sicilian plan, expand on kingside and aim for {{square f5}}.",
      "Solid, prepares ...Ng{{square e7}} and keeps the center flexible.",
      "Develop and support {{square e5}} and {{square g5}} squares before pushing further.",
      "Develop and keep ...{{square d5}} and ...{{square f5}} options open.",
      "Castle and get the rook to the f file behind the f pawn.",
      "Castle and prepare to meet kingside play with central or queenside counterplay."
    ]
  },

  {
    id: "sicilian-closed-early-nge7-0-0",
    name: "Closed Sicilian: ...Nge7 and quick castling",
    description: "Simple Closed Sicilian plan for Black: build the fianchetto, keep the c-pawn in reserve, castle, then choose between ...d5 and ...f5 based on White's setup.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "e6", "Be3", "Nge7", "Qd2", "O-O", "f4", "d6", "Nf3", "f5"],
    explanations: [
      "White takes central space.",
      "Sicilian counterplay and imbalance.",
      "Closed Sicilian structure. White keeps the center closed and avoids the Open Sicilian.",
      "Develop and control {{square d4}} and {{square e5}}.",
      "White commits to a kingside fianchetto and a slower plan.",
      "Black mirrors with a fianchetto and keeps the long diagonal under control.",
      "The bishop supports White's center and future kingside play.",
      "The Dragon bishop house is useful even in quieter Sicilian structures.",
      "White supports {{square e4}} and keeps the center compact.",
      "Black uses ...{{square e6}} because the c-pawn is still on {{square c5}} and central counterplay may come later with ...{{square d5}}.",
      "White develops and often wants Q{{square d2}}, {{square f4}}, and a kingside squeeze.",
      "The knight goes to {{square e7}} so the c-pawn stays flexible and the center stays under control.",
      "White coordinates the attack and connects the rooks.",
      "Castle before arguing about pawn storms.",
      "White shows the real plan now: kingside expansion.",
      "With White pushing on the wing, Black chooses the solid ...{{square d6}} structure first and keeps the center stable.",
      "White completes development and keeps the kingside plan going.",
      "Meet wing play with your own pawn break. ...{{square f5}} contests space immediately and stops White from rolling forward for free."
    ]
  },
  {
    id: "sicilian-closed-e5-clamp",
    name: "Closed Sicilian: early ...e5 clamp",
    description: "Black plays an early ...e5 to clamp down on f4 and seize central space. A very common practical response.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "e5", "Nf3", "d6", "O-O", "Nge7", "Be3", "O-O"],
    explanations: [
      "White takes central space.",
      "Sicilian counterplay, fight for {{square d4}}.",
      "Closed Sicilian structure, flexible development.",
      "Develop and reinforce central control.",
      "Prepare a kingside fianchetto.",
      "Black mirrors with a fianchetto.",
      "Bishop supports kingside play and central control.",
      "Black completes the fianchetto.",
      "Keep the center closed and support {{square e4}}.",
      "Key move. Black clamps down on {{square f4}} and claims space, forcing White to find slower plans.",
      "Develop and prepare to castle, keeping options for {{square f4}} later.",
      "Support the {{square e5}} pawn and keep the position solid.",
      "Castle before committing to pawn pushes.",
      "Develop and keep ...{{square f5}} and ...B{{square e6}} options available.",
      "Develop and support queenside safety or a later {{square f4}} push.",
      "Castle and finish basic development."
    ]
  },

  {
    id: "sicilian-closed-botvinnik-style",
    name: "Closed Sicilian: Botvinnik-style buildup",
    description: "Classic Closed Sicilian plan with Be3, Qd2, and f4 ideas. Slow but dangerous kingside buildup.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "d6", "Be3", "e6", "Qd2", "Nf6", "f4", "O-O", "Nf3", "Rb8"],
    explanations: [
      "White takes space.",
      "Sicilian structure.",
      "Closed setup, avoid early {{square d4}}.",
      "Develop and contest central squares.",
      "Prepare B{{square g2}} and a kingside plan.",
      "Black fianchetto structure.",
      "Strong diagonal pressure.",
      "Black mirrors development.",
      "Solidify the center.",
      "Support ...{{square e5}} and keep structure flexible.",
      "Key Botvinnik idea, supports Q{{square d2}} and {{square f4}}.",
      "Flexible development, keeps ...{{square f5}} ideas alive.",
      "Prepare {{square f4}}, B{{square h6}}, and potential kingside pressure.",
      "Castle and get the king safe before counterplay starts.",
      "Commit to kingside space and prepare {{square f5}} attacks.",
      "Practical queenside prep, often supports ...{{square b5}}.",
      "Develop and connect the king side pieces before pushing more pawns.",
      "Keep development consistent and the move order legal."
    ]
  },

  {
    id: "sicilian-closed-direct-d5-break",
    name: "Closed Sicilian: direct ...d5 break",
    description: "Black challenges the center immediately with ...d5. White must understand the structure, not memorize moves.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "e6", "Bg2", "d5", "exd5", "exd5", "d3", "Nf6", "Nge2", "Bd6", "O-O", "O-O"],
    explanations: [
      "White takes central space.",
      "Sicilian counterplay.",
      "Closed Sicilian move order.",
      "Develop and pressure {{square d4}}.",
      "Prepare a fianchetto.",
      "Solid setup, opens dark-square bishop.",
      "Develop bishop and support the center.",
      "Critical break. Black immediately challenges {{square e4}} and aims for central equality.",
      "Remove the central tension and avoid allowing ...{{square d4}} at the wrong moment.",
      "Recapture and keep central presence, opening lines for pieces.",
      "Return to a Closed structure and support {{square e4}}.",
      "Develop and hit {{square e4}}, forcing White to keep defending the center.",
      "Develop and keep f-pawn flexible for {{square f4}} ideas.",
      "Develop actively and support kingside castling.",
      "Castle and get king safe.",
      "Castle and finish development."
    ]
  },

  {
    id: "sicilian-closed-rb8-queenside",
    name: "Closed Sicilian: ...Rb8 queenside expansion",
    description: "Black prepares queenside play early instead of committing to central breaks. Common in practical games.",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "Rb8", "f4", "b5", "Nf3", "b4", "Ne2", "a5"],
    explanations: [
      "White claims central space.",
      "Sicilian structure.",
      "Closed Sicilian setup.",
      "Develop and contest central squares.",
      "Prepare a kingside fianchetto.",
      "Black mirrors with a fianchetto.",
      "Develop bishop on the long diagonal.",
      "Black completes development.",
      "Keep the center closed and flexible.",
      "Prepare ...{{square b5}} and queenside expansion without committing the center.",
      "White starts kingside play and prepares {{square f5}}.",
      "Black expands on the queenside and aims to open files.",
      "Develop and prepare to castle before pushing more.",
      "Gain space and kick the knight, trying to open lines on the queenside.",
      "Re-route the knight and keep the center stable.",
      "Support queenside expansion and prepare ...{{square a4}} in some lines."
    ]
  },



  {
    id: "sicilian-qxd4-line-early-queen",
    name: "Sideline: early Qxd4 and ...Nc6 hit",
    description: "White recaptures with the queen, Black develops with tempo and equalizes quickly.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Qxd4", "Nc6", "Bb5", "Bd7", "Bxc6", "Bxc6", "Nc3", "Nf6", "Bg5", "e6"],
    explanations: [
      "White takes space.",
      "Sicilian counterplay.",
      "Develop and prepare {{square d4}}.",
      "Solid support of the center.",
      "Open the center.",
      "Exchange and open lines.",
      "Early queen recapture, but it can be hit with tempo.",
      "Develop and attack the queen immediately.",
      "Pin and keep pressure while avoiding queen harassment.",
      "Break the pin and develop.",
      "Trade to reduce black development and simplify.",
      "Recapture, maintain structure and development.",
      "Develop and keep the queen supported on {{square d4}} if needed.",
      "Develop and hit {{square e4}}, also prepares ...{{square e6}}.",
      "Develop and pin the knight, aiming for pressure on {{square d8}}/{{square a5}} lines.",
      "Solidify the center and open the dark bishop."
    ]
  },

  {
    id: "sicilian-bg5-h6-bh4-nxe4-core",
    name: "Dragon: Bg5 and ...Nxe4 tactic core",
    description: "Bg5 lines where ...Nxe4 appears as a central tactic and trades follow.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6", "Bg5", "Bg7", "Qd2", "h6", "Bh4", "Nc6", "O-O-O", "Nxe4", "Nxe4", "Nxd4"],
    explanations: [
      "White takes space.",
      "Sicilian response.",
      "Develop and prepare {{square d4}}.",
      "Solid, control {{square e5}}.",
      "Open center.",
      "Exchange and open lines.",
      "White develops with recapture.",
      "Pressure {{square e4}}.",
      "Defend and develop.",
      "Dragon setup.",
      "Pin the knight and increase pressure.",
      "Develop bishop and keep pressure on diagonal.",
      "Support long castle and coordination.",
      "Ask the bishop a question and gain luft.",
      "Keep the pin and avoid giving up bishop pair.",
      "Develop and pressure {{square d4}}.",
      "Commit to queenside castling and attack.",
      "Tactical grab in the center, testing white coordination.",
      "White recaptures to avoid losing pawn and keep pieces active.",
      "Follow up by trading the centralized knight and simplifying."
    ]
  },

  {
    category: "Closed Sicilian",
    id: "sicilian-closed-classical-f4-g3",
    name: "Closed Sicilian: Classical f4-g3 setup",
    description: "Slow kingside buildup with f4, g3, Bg2, and long maneuvering plans.",
    moves: ["e4", "c5", "Nc3", "Nc6", "f4", "g6", "Nf3", "Bg7", "g3", "d6", "Bg2", "e6", "O-O", "Nge7", "d3", "O-O"],
    explanations: [
      "Claim central space.",
      "Sicilian structure.",
      "Avoid Open Sicilian and keep structure closed.",
      "Develop and control {{square d4}}.",
      "Gain kingside space and signal attack.",
      "Prepare kingside fianchetto.",
      "Develop and support center.",
      "Bishop on long diagonal.",
      "Prepare B{{square g2}} and solid king safety.",
      "Solidify center.",
      "Complete fianchetto.",
      "Control {{square d5}} and prepare ...Ng{{square e7}}.",
      "King safety.",
      "Flexible knight, supports ...{{square d5}} breaks.",
      "Lock the center and prepare {{square f5}} or B{{square e3}}.",
      "Castle and connect rooks, preparing ...{{square d5}} breaks later."
    ]
  },
  {
    category: "Closed Sicilian",
    id: "sicilian-closed-kingside-storm-f5",
    name: "Closed Sicilian: Kingside storm with f5",
    description: "Direct pawn expansion. Risky but common at club level.",
    moves: ["e4", "c5", "Nc3", "Nc6", "f4", "g6", "Nf3", "Bg7", "f5", "d6", "g4", "h5", "gxh5", "gxh5", "d3", "Nf6"],
    explanations: [
      "Central space.",
      "Asymmetry.",
      "Closed Sicilian choice.",
      "Develop.",
      "Kingside expansion.",
      "Prepare defense.",
      "Develop.",
      "Fianchetto bishop.",
      "Close the center and start attack.",
      "Stabilize.",
      "Space grab, very committal.",
      "Typical counter, creates targets.",
      "Open the g-file and change the structure on the wing.",
      "Recapture and keep material equal while opening lines.",
      "Support the center and prepare piece development behind the pawn storm.",
      "Develop and challenge {{square e4}} and {{square g4}} squares."
    ]
  },

]);
