// src/openings/sicilianDefenseLines.js

export const sicilianDefenseLines = [
  {
    id: "sicilian-open-mainline-classical",
    name: "Open Sicilian: Classical setup",
    description: "Mainline Open Sicilian: develop normally with ...d6, ...Nf6, ...Nc6.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6"],
    explanations: [
      "e4: White takes central space and opens lines for pieces quickly.",
      "c5: Sicilian. Fight for d4 without mirroring with ...e5, and create imbalance.",
      "Nf3: Develop and attack d4 and e5 squares, also supports the d4 push.",
      "d6: Support ...c5 structure and prepare ...Nf6 without allowing e5 tactics.",
      "d4: White challenges the center directly and opens lines.",
      "cxd4: Accept the open game and force the typical Open Sicilian structure.",
      "Nxd4: White recaptures with a piece for development and central presence.",
      "Nf6: Hit e4 and develop, making White show how they defend the center.",
      "Nc3: Defend e4 and develop, enabling aggressive setups.",
      "Nc6: Develop, add more pressure on d4 and e5, and keep flexible plans."
    ]
  },

  {
    id: "sicilian-open-scheveningen",
    name: "Open Sicilian: Scheveningen structure",
    description: "Open Sicilian with ...e6 and ...d6, flexible and solid but watch kingside attacks.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6"],
    explanations: [
      "e4: White takes space and sets up fast development.",
      "c5: Create asymmetry and contest d4 immediately.",
      "Nf3: Develop and prepare d4.",
      "d6: Support the center and keep control of e5.",
      "d4: White goes for the Open Sicilian.",
      "cxd4: Force the open center and typical Sicilian piece play.",
      "Nxd4: White recaptures with development.",
      "Nf6: Pressure e4 and develop.",
      "Nc3: Defend e4 and increase central control.",
      "e6: Build the Scheveningen pawn shape and open the dark bishop."
    ]
  },

  {
    id: "sicilian-open-najdorf-basic",
    name: "Open Sicilian: Najdorf with 6...a6",
    description: "Najdorf marker move ...a6 after standard development.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"],
    explanations: [
      "e4: White claims the center and opens lines.",
      "c5: Sicilian. Fight for d4 with an unbalanced pawn structure.",
      "Nf3: Develop and prepare the Open Sicilian.",
      "d6: Support ...c5 and prevent early e5 tactics.",
      "d4: White commits to open central play.",
      "cxd4: Exchange in the center and create imbalanced positions.",
      "Nxd4: White recaptures with development.",
      "Nf6: Attack e4 and develop.",
      "Nc3: Defend e4 and develop.",
      "a6: Najdorf. Stop Nb5 ideas and keep ...e5 or ...e6 flexible."
    ]
  },

  {
    id: "sicilian-open-dragon-basic",
    name: "Open Sicilian: Dragon setup",
    description: "Dragon: play ...g6 and fianchetto the dark bishop, sharp opposite-side castling often happens.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6"],
    explanations: [
      "e4: White claims the center and opens development lanes.",
      "c5: Fight for d4 with asymmetry.",
      "Nf3: Develop and prepare d4.",
      "d6: Support ...c5 and keep e5 controlled.",
      "d4: Open Sicilian structure.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White recaptures with a piece and centralizes.",
      "Nf6: Develop and hit e4.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon. Prepare ...Bg7 for pressure on the long diagonal."
    ]
  },

  {
    id: "sicilian-accelerated-dragon-basic",
    name: "Accelerated Dragon",
    description: "Accelerated Dragon: skip ...d6 early, play ...Nc6 and ...g6 quickly.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "g6"],
    explanations: [
      "e4: White takes space and threatens quick development.",
      "c5: Sicilian. Contest d4 and avoid symmetry.",
      "Nf3: Develop and prepare d4.",
      "Nc6: Develop immediately and pressure d4, aiming for ...g6 next.",
      "d4: White opens the center.",
      "cxd4: Exchange and create open play.",
      "Nxd4: White recaptures and centralizes.",
      "g6: Accelerated Dragon plan, aiming for ...Bg7."
    ]
  },

  {
    id: "sicilian-sveshnikov-skeleton",
    name: "Sveshnikov skeleton",
    description: "Sveshnikov: early ...e5 after ...Nc6 and ...Nf6, very theory heavy but consistent plans.",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5", "Ndb5", "d6"],
    explanations: [
      "e4: White claims space and opens lines.",
      "c5: Sicilian. Fight for d4 with asymmetry.",
      "Nf3: Develop and aim for d4.",
      "Nc6: Develop and pressure d4.",
      "d4: White opens the center.",
      "cxd4: Exchange and create open lines.",
      "Nxd4: White recaptures with a piece.",
      "Nf6: Develop and hit e4.",
      "Nc3: Defend e4 and develop.",
      "e5: Sveshnikov marker. Grab space and hit the d4 knight.",
      "Ndb5: Typical. White jumps into b5 to target d6 and c7 squares.",
      "d6: Hold e5 and stop immediate tactics on d6."
    ]
  },

  {
    id: "sicilian-kan-basic",
    name: "Kan Sicilian",
    description: "Kan: ...e6 early, flexible development and often ...Qc7.",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6"],
    explanations: [
      "e4: White takes central space.",
      "c5: Sicilian. Contest d4 and avoid symmetry.",
      "Nf3: Develop and prepare d4.",
      "e6: Kan style. Support d5 breaks later and open the dark bishop.",
      "d4: Open Sicilian attempt.",
      "cxd4: Accept the open center.",
      "Nxd4: White recaptures and develops.",
      "a6: Flexible. Prevent Nb5 ideas and prepare ...Qc7 or ...b5."
    ]
  },

  {
    id: "sicilian-taimanov-basic",
    name: "Taimanov setup",
    description: "Taimanov: ...e6 and ...Qc7 is a common plan, flexible piece placement.",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Nc3", "Qc7"],
    explanations: [
      "e4: White claims the center.",
      "c5: Sicilian structure to fight for d4.",
      "Nf3: Develop and set up d4.",
      "e6: Keep options open and prepare ...d5 in some lines.",
      "d4: Open center and gain space.",
      "cxd4: Exchange in the center.",
      "Nxd4: White develops with recapture.",
      "Nc6: Develop and pressure d4.",
      "Nc3: Defend and develop.",
      "Qc7: Typical Taimanov idea, supporting ...d5 and coordinating pieces."
    ]
  },

  {
    id: "sicilian-alapin-basic",
    name: "Vs Alapin: 2.c3",
    description: "Alapin (2.c3): respond with ...d5 to challenge the center directly.",
    moves: ["e4", "c5", "c3", "d5", "exd5", "Qxd5"],
    explanations: [
      "e4: White claims the center.",
      "c5: Sicilian response, but White avoids the Open Sicilian with c3.",
      "c3: Alapin. White supports d4 and reduces your typical counterplay lines.",
      "d5: Direct counter in the center. Challenge e4 and punish slow play.",
      "exd5: White usually takes to avoid losing central control.",
      "Qxd5: Recapture with the queen, accepting early queen development for central pressure."
    ]
  },

  {
    id: "sicilian-grand-prix-basic",
    name: "Vs Grand Prix: 2.Nc3 and 3.f4",
    description: "Grand Prix attack structure: a common response is ...Nc6 and ...g6 with kingside control.",
    moves: ["e4", "c5", "Nc3", "Nc6", "f4", "g6"],
    explanations: [
      "e4: White takes space and prepares quick kingside play.",
      "c5: Sicilian. Create imbalance and fight for d4.",
      "Nc3: White avoids Open Sicilian structures and keeps options for f4.",
      "Nc6: Develop and control key squares, especially d4 and e5.",
      "f4: Grand Prix. White goes for fast kingside attack ideas.",
      "g6: Solid plan. Prepare ...Bg7 and reduce white's direct kingside damage."
    ]
  },

  {
    id: "sicilian-moscow-rossolimo-basic",
    name: "Vs Bb5+: Moscow and Rossolimo",
    description: "After 2.Nf3 d6 3.Bb5+ (Moscow) or 2...Nc6 3.Bb5 (Rossolimo), develop and get ready to unpin.",
    moves: ["e4", "c5", "Nf3", "d6", "Bb5+", "Bd7", "Bxd7+", "Qxd7"],
    explanations: [
      "e4: White claims space.",
      "c5: Sicilian response.",
      "Nf3: Develop and prepare d4.",
      "d6: Moscow move order. Keep control of e5 and prepare development.",
      "Bb5+: Check, aiming to disrupt development and sometimes trade pieces.",
      "Bd7: Block and offer a trade, reducing White's pressure.",
      "Bxd7+: White often takes to avoid retreating and to damage coordination.",
      "Qxd7: Recapture and keep development moving."
    ]
  },

  // Added lines from your list

  {
    id: "sicilian-dragon-yugoslav-rc8-nxe4-sac",
    name: "Dragon Yugoslav: ...Rc8 and ...Nxe4 tactics",
    description: "Yugoslav setup. Black expands with ...b5 and the exchange sacrifice ideas appear on d4.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "Kb1", "a5", "a4", "bxa4", "Nxa4", "Bxa4",
      "Bxa4", "Rc4", "Bb3", "Nxe4", "fxe4", "Rxd4"
    ],
    explanations: [
      "e4: White grabs space and opens lines.",
      "c5: Sicilian, immediately fights for d4.",
      "Nf3: Develop and prepare d4.",
      "d6: Keep control of e5 and support the center.",
      "d4: White commits to the Open Sicilian.",
      "cxd4: Open the center on your terms.",
      "Nxd4: White develops while recapturing.",
      "Nf6: Hit e4 and develop.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon structure, aiming for ...Bg7.",
      "Be3: Yugoslav style, supports queenside castling and attacks.",
      "Bg7: Put the bishop on the long diagonal.",
      "f3: Reinforce e4 and stop ...Ng4 ideas.",
      "O-O: Get king safety and connect rooks.",
      "Qd2: Prepare long castle and connect to kingside pressure.",
      "Nc6: Develop and pressure d4.",
      "Bc4: Add pressure on f7 and accelerate the attack.",
      "Bd7: Develop and connect rooks, also covers key squares.",
      "O-O-O: White castles long and the game becomes race like.",
      "Rc8: Typical Dragon rook placement against c and c2 squares.",
      "Bb3: Keep bishop safe and keep pressure lines.",
      "Nxd4: Remove the centralized knight and reduce white pressure.",
      "Bxd4: White keeps a piece on the diagonal and recaptures.",
      "b5: Queenside expansion, also hits the bishop and opens files.",
      "Kb1: Standard safety move, avoid checks on a1 diagonal.",
      "a5: Keep expanding and support ...a4 or ...b4 ideas.",
      "a4: White tries to stop the pawn storm or force structure.",
      "bxa4: Accept, open a file and create targets.",
      "Nxa4: White recaptures to remove the pawn and stabilize.",
      "Bxa4: Trade off that knight and reduce defense.",
      "Bxa4: White recaptures and keeps pieces active.",
      "Rc4: Rook lift to pressure and enable tactics on d4 and e4.",
      "Bb3: Retreat and keep bishop while avoiding tactics.",
      "Nxe4: Tactical strike, grabbing central pawn and opening lines.",
      "fxe4: White accepts and opens the f file and center.",
      "Rxd4: Follow up by winning material back or simplifying into advantage."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-h4-h5-qa5-rcx3",
    name: "Dragon Yugoslav: ...Qa5 and ...Rxc3 sequence",
    description: "Yugoslav attack line where Black hits c3 and the queen joins with checks and captures.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "hxg6", "fxg6",
      "Bh6", "Bxh6", "Qxh6", "Rxc3", "bxc3", "Qxc3", "Nb3", "Rc8"
    ],
    explanations: [
      "e4: White takes space and aims for fast development.",
      "c5: Sicilian, create imbalance and fight for d4.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid center support, control e5.",
      "d4: White opens the center.",
      "cxd4: Exchange and open lines for active play.",
      "Nxd4: White centralizes a knight.",
      "Nf6: Develop and hit e4.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon fianchetto plan.",
      "Be3: Yugoslav setup, supports long castle and attack.",
      "Bg7: Bishop targets the long diagonal.",
      "f3: Reinforce e4 and limit ...Ng4.",
      "O-O: King safety and rook connection.",
      "Qd2: Support queenside castling and connect to h6 ideas.",
      "Nc6: Develop and pressure d4.",
      "O-O-O: Commit to opposite side castling.",
      "Bd7: Develop and connect pieces, support queenside play.",
      "g4: White starts pawn storm on the kingside.",
      "Rc8: Rook to c file, target c2 and support tactics.",
      "h4: White supports h5 and keeps space.",
      "Ne5: Centralize and hit key squares, also targets c4 and f3.",
      "h5: Continue the pawn storm and open lines.",
      "Qa5: Queen joins, pressures a2 and c3 and adds tactical threats.",
      "hxg6: White opens the h file and tries to expose the king.",
      "fxg6: Recapture and keep the f file structure, also open f file.",
      "Bh6: Trade the key Dragon bishop or force concessions.",
      "Bxh6: Remove that attacker immediately.",
      "Qxh6: White keeps attacking chances on the h file.",
      "Rxc3: Typical exchange sacrifice idea on c3 to rip open lines.",
      "bxc3: Forced recapture, structure changes and b file opens.",
      "Qxc3: Queen grabs material and keeps threats on a1 and d4.",
      "Nb3: Hit the queen and try to stabilize.",
      "Rc8: Consolidate and keep pressure on the c file."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-kb1-qa5-nd5-queen-trade",
    name: "Dragon Yugoslav: Nd5 and queen trade sequence",
    description: "Yugoslav line where White jumps Nd5 and Black simplifies into tactics and endgame pressure.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "Kb1", "Qa5", "Nd5", "Qxd2",
      "Nxe7+", "Kh8", "Rxd2", "Rce8", "Nd5", "Nxd5", "exd5", "Nxf3",
      "Nxf3", "Rxe3"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian structure and counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Hold e5 and support the center.",
      "d4: White opens the center.",
      "cxd4: Exchange to create the Open Sicilian structure.",
      "Nxd4: White centralizes.",
      "Nf6: Develop and hit e4.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon plan, ...Bg7 next.",
      "Be3: Yugoslav style attack prep.",
      "Bg7: Place bishop on the long diagonal.",
      "f3: Support e4 and limit ...Ng4.",
      "O-O: King safety.",
      "Qd2: Prepare long castle and coordinate attack.",
      "Nc6: Develop and pressure d4.",
      "O-O-O: Opposite side castling, race begins.",
      "Bd7: Develop and connect pieces.",
      "g4: White starts direct pawn storm.",
      "Rc8: Put rook on the c file for counterplay.",
      "h4: Support h5 and keep pressure.",
      "Ne5: Centralize and challenge key squares.",
      "Kb1: Improve king safety on the queenside.",
      "Qa5: Queen joins queenside pressure and checks threats.",
      "Nd5: White jumps in to create tactics and hit c7 and e7 squares.",
      "Qxd2: Simplify by trading queens, reducing white attack speed.",
      "Nxe7+: Tactical check and fork ideas, force king response.",
      "Kh8: Step away from checks and keep pieces protected.",
      "Rxd2: Recapture the queen and keep rooks connected.",
      "Rce8: Bring rook to e file and aim at e3 and e4 squares.",
      "Nd5: Recentralize, keep pressure and block some lines.",
      "Nxd5: Remove the knight and simplify.",
      "exd5: Recapture and open the e file and diagonal.",
      "Nxf3: Tactic to win material or damage king safety.",
      "Nxf3: Recapture and try to hold structure.",
      "Rxe3: Grab pawn and keep initiative with active rook."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-qa5-nxf3-queen-exchange",
    name: "Dragon Yugoslav: ...Nxf3 and queen exchange",
    description: "Black uses ...Nxf3 and queen trades to convert tactical pressure into material.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "Kb1", "Nxf3",
      "Nxf3", "Rxc3", "Qxc3", "Qxc3", "bxc3", "Bxg4", "Be2", "Nxe4",
      "Bd4", "e5", "Bxa7", "Nxc3+", "Kb2", "Nxd1+"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay and imbalance.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid, control e5.",
      "d4: Open center plan.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White develops by recapturing.",
      "Nf6: Hit e4 and develop.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon fianchetto.",
      "Be3: Yugoslav setup.",
      "Bg7: Bishop on long diagonal.",
      "f3: Support center and control g4.",
      "O-O: King safety.",
      "Qd2: Support long castle and h6 ideas.",
      "Nc6: Develop and hit d4.",
      "O-O-O: Commit to opposite side castling.",
      "Bd7: Develop and coordinate pieces.",
      "g4: Pawn storm attempt.",
      "Rc8: Counterplay on c file.",
      "h4: Support h5 push.",
      "Ne5: Centralize, hit c4 and f3 structures.",
      "h5: Open lines on kingside.",
      "Qa5: Queen activates against a2 and c3.",
      "Kb1: Safety move, reduce checks.",
      "Nxf3: Remove defender and open lines for queen and rook.",
      "Nxf3: White recaptures to avoid losing material.",
      "Rxc3: Sacrifice on c3 to open the king and win structure.",
      "Qxc3: White tries to keep material balanced and stop threats.",
      "Qxc3: Trade queens to convert attack into endgame gains.",
      "bxc3: Forced recapture, structure changes.",
      "Bxg4: Win pawn or remove attacker, reduce kingside pressure.",
      "Be2: Develop and protect key squares.",
      "Nxe4: Central pawn grab, also hits c3 weaknesses indirectly.",
      "Bd4: Try to anchor a piece and aim for activity.",
      "e5: Kick the bishop and gain central space.",
      "Bxa7: Grab pawn, but it can be risky if pieces get trapped.",
      "Nxc3+: Fork and check to win material and simplify.",
      "Kb2: Move king and stay in game.",
      "Nxd1+: Win the rook, converting tactics into decisive material."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-hxg6-qa1-check",
    name: "Dragon Yugoslav: ...Qa1+ and ...Qxd4+",
    description: "Queen invades with checks after the c3 break and open diagonals.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
      "g4", "Rc8", "h4", "Ne5", "h5", "Qa5", "hxg6", "fxg6",
      "Bh6", "Bxh6", "Qxh6", "Rxc3", "bxc3", "Qxc3", "g5", "Qa1+",
      "Kd2", "Qxd4+"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Support center and control e5.",
      "d4: Open the center.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White recaptures with development.",
      "Nf6: Attack e4 and develop.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon fianchetto plan.",
      "Be3: Yugoslav style setup.",
      "Bg7: Bishop on long diagonal.",
      "f3: Reinforce e4 and limit piece jumps.",
      "O-O: King safety.",
      "Qd2: Prepare long castle and attack.",
      "Nc6: Develop and pressure d4.",
      "O-O-O: Opposite side castling.",
      "Bd7: Develop and connect pieces.",
      "g4: Start pawn storm.",
      "Rc8: Counterplay against c2 and c3.",
      "h4: Support h5.",
      "Ne5: Centralize and threaten key squares.",
      "h5: Push for open lines.",
      "Qa5: Queen joins queenside threats.",
      "hxg6: Open lines to the king.",
      "fxg6: Recapture and keep structure while opening f file.",
      "Bh6: Trade off Dragon bishop or force weakening.",
      "Bxh6: Remove the attacker.",
      "Qxh6: Keep attack alive with queen on h file.",
      "Rxc3: Break c3 to open the king and win material.",
      "bxc3: Forced structure change.",
      "Qxc3: Queen penetrates and targets a1 and d4 lines.",
      "g5: Try to chase pieces and create threats.",
      "Qa1+: Immediate invasion, check based on open diagonal.",
      "Kd2: King steps away and tries to survive.",
      "Qxd4+: Take central pawn with check, converting attack into material."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-h4-rc4-nxe4-sac",
    name: "Dragon Yugoslav: h4 included before ...Nxe4",
    description: "Same tactical theme as the earlier ...Rc4 ...Nxe4 line, but with h4 instead of Kb1.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a4", "bxa4", "Nxa4", "Bxa4",
      "Bxa4", "Rc4", "Bb3", "Nxe4", "fxe4", "Rxd4"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Keep e5 under control.",
      "d4: Open the center.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White centralizes.",
      "Nf6: Pressure e4.",
      "Nc3: Defend and develop.",
      "g6: Dragon fianchetto.",
      "Be3: Yugoslav setup.",
      "Bg7: Bishop on long diagonal.",
      "f3: Support e4 and control g4.",
      "O-O: King safety.",
      "Qd2: Prepare long castle.",
      "Nc6: Develop and pressure d4.",
      "Bc4: Add pressure and speed up attack.",
      "Bd7: Develop and coordinate pieces.",
      "O-O-O: Opposite side castling.",
      "Rc8: Counterplay on c file.",
      "Bb3: Keep bishop safe.",
      "Nxd4: Remove white knight and reduce central control.",
      "Bxd4: White recaptures to keep presence.",
      "b5: Expansion and tempo on pieces.",
      "h4: White continues kingside pawn storm.",
      "a5: Push queenside pawns for attack.",
      "a4: White tries to slow down queenside play.",
      "bxa4: Open the a file and keep initiative.",
      "Nxa4: White recaptures to stabilize.",
      "Bxa4: Trade to reduce defense.",
      "Bxa4: White keeps pieces active.",
      "Rc4: Rook lift for pressure and tactics.",
      "Bb3: Step away and keep bishop.",
      "Nxe4: Tactical strike in the center.",
      "fxe4: White accepts and opens lines.",
      "Rxd4: Follow up by taking the bishop or central pawn line, converting tactics."
    ]
  },

  {
    id: "sicilian-dragon-yugoslav-a4-a3-a2-b3-endgame-push",
    name: "Dragon Yugoslav: queenside pawn break into endgame squeeze",
    description: "Long line with queenside pawn breaks, queen safety moves, and converting to a passed pawn plan.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
      "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a3", "b4", "axb4", "axb4",
      "Nd5", "Nxd5", "Bxg7", "Kxg7", "exd5", "Qa5", "Qd4+", "Kg8",
      "h5", "Bf5", "g4", "Bxc2", "Bxc2", "b3", "Rh2", "Rc7"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid and controls e5.",
      "d4: Open center plan.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White recaptures with development.",
      "Nf6: Pressure e4.",
      "Nc3: Defend and develop.",
      "g6: Dragon setup.",
      "Be3: Yugoslav setup.",
      "Bg7: Bishop on diagonal.",
      "f3: Support e4 and slow ...Ng4.",
      "O-O: King safety.",
      "Qd2: Prepare long castle and attack.",
      "Nc6: Develop and pressure d4.",
      "Bc4: Aggressive bishop placement.",
      "Bd7: Develop and coordinate.",
      "O-O-O: Opposite side castling.",
      "Rc8: Rook on open file, typical Dragon play.",
      "Bb3: Keep bishop safe.",
      "Nxd4: Trade off the central knight.",
      "Bxd4: White recaptures to keep piece activity.",
      "b5: Expand and gain space, threaten to open files.",
      "h4: White keeps pawn storm plan.",
      "a5: Black expands on queenside, matching the race.",
      "a3: White prepares to meet ...b4 with axb4, also slow a pawn push.",
      "b4: Break open the queenside pawn structure.",
      "axb4: White accepts to avoid getting locked up.",
      "axb4: Black recaptures and opens the a file.",
      "Nd5: White jumps in to create tactics and simplify.",
      "Nxd5: Remove the intruder.",
      "Bxg7: White trades the Dragon bishop's partner and reduces pressure.",
      "Kxg7: Recapture and keep king safe enough.",
      "exd5: Open lines and create a pawn majority structure.",
      "Qa5: Queen activates and targets a2 and a3 squares.",
      "Qd4+: White gives check and tries to force king placement.",
      "Kg8: Step out and avoid tactics.",
      "h5: White continues kingside pawn storm.",
      "Bf5: Activate bishop and hit c2 and e4 lines.",
      "g4: White tries to chase the bishop and keep attack going.",
      "Bxc2: Tactic to win material and create threats.",
      "Bxc2: White recaptures and tries to reduce damage.",
      "b3: Create a passed pawn and fix white pieces.",
      "Rh2: Defensive rook move, prepare to meet b pawn.",
      "Rc7: Consolidate and support the passed pawn plan."
    ]
  },

  {
    id: "sicilian-classical-sac-line-be2-qb6-queen-grab",
    name: "Tactics: Be2 and ...Qb6 pawn grab",
    description: "Sharp tactical sequence where the queen grabs b2 and lines open with checks.",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
      "Be2", "Bg7", "Be3", "O-O", "O-O", "Nc6", "f4", "Qb6", "Nf5", "Qxb2",
      "Nxg7", "Qxc3", "Bd2", "Qd4+", "Kh1", "Kxg7"
    ],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid center support.",
      "d4: Open the center.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White develops by recapturing.",
      "Nf6: Develop and pressure e4.",
      "Nc3: Defend e4 and develop.",
      "g6: Dragon structure.",
      "Be2: Quieter development, keep options open.",
      "Bg7: Fianchetto bishop, pressure on diagonal.",
      "Be3: Support center and develop, watch tactics on b2.",
      "O-O: King safety.",
      "O-O: White also castles, reducing immediate mate threats.",
      "Nc6: Develop and pressure d4.",
      "f4: Space grab, also creates targets.",
      "Qb6: Pressure b2 and d4, typical tactical idea.",
      "Nf5: Jump in to create threats and hit e7 and g7 areas.",
      "Qxb2: Queen grabs pawn, accepting risk for material.",
      "Nxg7: White takes bishop, reducing dragon pressure.",
      "Qxc3: Queen grabs c3 and hits multiple targets.",
      "Bd2: Try to trap or challenge the queen path.",
      "Qd4+: Check to force king move and keep initiative.",
      "Kh1: Step away and avoid further checks.",
      "Kxg7: Black recaptures, restoring material balance and ending the tactic."
    ]
  },

  {
    id: "sicilian-bb5-anti-sicilian-bc4-plan",
    name: "Anti Sicilian: 3.Bc4 setup vs ...Nf6",
    description: "Early Bc4 against the Sicilian, play normal development and castle.",
    moves: ["e4", "c5", "Nf3", "d6", "Bc4", "Nf6", "Nc3", "e6", "d3", "Be7", "Bg5", "O-O"],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian response.",
      "Nf3: Develop and prepare central play.",
      "d6: Solid support and control e5.",
      "Bc4: Fast development aiming at f7 and quick plans.",
      "Nf6: Develop and hit e4.",
      "Nc3: Develop and defend e4.",
      "e6: Solid, open bishop and prepare ...d5 breaks later.",
      "d3: Keep center controlled and support e4.",
      "Be7: Develop and prepare to castle.",
      "Bg5: Pin the knight and increase pressure.",
      "O-O: King safety and rook connection."
    ]
  },

  {
  id: "sicilian-dragon-yugoslav-h5-hxg6-continuation",
  name: "Dragon Yugoslav: h5-hxg6 continuation after Qd4+",
  description: "Dragon Yugoslav line with h5 push, ...Bf5 development, and hxg6 capture.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "a3", "b4", "axb4", "axb4",
    "Nd5", "Nxd5", "Bxg7", "Kxg7", "exd5", "Qa5", "Qd4+", "Kg8",
    "h5", "Bf5", "hxg6", "fxg6"
  ],
  explanations: [
    "e4: White claims the center.",
    "c5: Sicilian counterplay.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid support for the center.",
    "d4: Open the center.",
    "cxd4: Exchange and create open lines.",
    "Nxd4: White recaptures and centralizes.",
    "Nf6: Pressure e4 and develop.",
    "Nc3: Defend e4 and develop.",
    "g6: Dragon fianchetto setup.",
    "Be3: Yugoslav system, prepares queenside castling.",
    "Bg7: Bishop on the long diagonal.",
    "f3: Reinforce e4 and control g4 square.",
    "O-O: King safety.",
    "Qd2: Connect rooks and prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "Bc4: Active bishop placement, eyes f7.",
    "Bd7: Develop and connect rooks.",
    "O-O-O: Opposite side castling, race begins.",
    "Rc8: Counterplay on the c-file.",
    "Bb3: Retreat bishop to safety while keeping pressure.",
    "Nxd4: Trade off the centralized knight.",
    "Bxd4: White recaptures to maintain piece activity.",
    "b5: Queenside expansion, gains space.",
    "h4: White starts kingside pawn storm.",
    "a5: Black expands on queenside to match.",
    "a3: White prepares for ...b4 push.",
    "b4: Break open the queenside structure.",
    "axb4: White captures to avoid being locked in.",
    "axb4: Black recaptures, opening the a-file.",
    "Nd5: Knight jump to create threats and simplify.",
    "Nxd5: Capture the intruding knight.",
    "Bxg7: Trade the Dragon bishop, reducing black's attack.",
    "Kxg7: King recaptures, remaining safe.",
    "exd5: Recapture and create pawn structure.",
    "Qa5: Queen activates, targeting weak squares.",
    "Qd4+: Check to gain time and challenge black's king.",
    "Kg8: King steps back to g8, avoiding further checks.",
    "h5: Continue kingside attack with pawn push.",
    "Bf5: Develop bishop actively, hitting c2 and supporting queenside.",
    "hxg6: Exchange to open the h-file and attack.",
    "fxg6: Recapture, keeping pawn structure and opening f-file for counterplay."
  ]
},

{
  id: "sicilian-dragon-be2-ng4-variation",
  name: "Dragon: Be2 with ...Ng4 variation",
  description: "Classical Dragon with Be2 where black plays ...Ng4 to trade bishops and develop initiative.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be2", "Bg7", "Be3", "O-O", "Qd2", "Nc6", "O-O-O", "Ng4",
    "Bxg4", "Bxg4", "f3", "Be6", "h4", "Qa5"
  ],
  explanations: [
    "e4: White claims the center.",
    "c5: Sicilian response, fighting for d4.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid center support.",
    "d4: Open the center.",
    "cxd4: Exchange and create open lines.",
    "Nxd4: White recaptures and centralizes.",
    "Nf6: Develop and pressure e4.",
    "Nc3: Defend e4 and develop.",
    "g6: Dragon fianchetto.",
    "Be2: Classical development, less aggressive than Bc4.",
    "Bg7: Bishop on the long diagonal.",
    "Be3: Develop bishop and support center.",
    "O-O: King safety.",
    "Qd2: Prepare queenside castling.",
    "Nc6: Develop and pressure d4.",
    "O-O-O: White castles queenside.",
    "Ng4: Knight jump to challenge the e3 bishop.",
    "Bxg4: White trades to avoid doubled pawns.",
    "Bxg4: Black recaptures, developing with tempo.",
    "f3: Reinforce e4 and limit bishop's retreat squares.",
    "Be6: Bishop retreats to active diagonal.",
    "h4: White starts kingside expansion.",
    "Qa5: Queen activates, putting pressure on queenside."
  ]
},

{
  id: "sicilian-dragon-be2-ng4-nxe6-line",
  name: "Dragon: Be2 ...Ng4 with Nxe6 exchange",
  description: "Classical Dragon line where white exchanges on e6 and trades bishops with Bh6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be2", "Bg7", "Be3", "O-O", "Qd2", "Nc6", "O-O-O", "Ng4",
    "Bxg4", "Bxg4", "f3", "Be6", "Nxe6", "fxe6", "Bh6", "Qa5",
    "Bxg7", "Kxg7"
  ],
  explanations: [
    "e4: White takes center.",
    "c5: Sicilian counterplay.",
    "Nf3: Develop and prepare d4.",
    "d6: Support center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon setup.",
    "Be2: Classical development.",
    "Bg7: Fianchetto bishop.",
    "Be3: Develop bishop.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "O-O-O: White castles queenside.",
    "Ng4: Challenge the e3 bishop.",
    "Bxg4: Trade bishop for knight.",
    "Bxg4: Recapture and develop.",
    "f3: Support e4 and limit bishop.",
    "Be6: Bishop finds active square.",
    "Nxe6: Exchange to damage black's pawn structure.",
    "fxe6: Recapture, creating doubled e-pawns but opening f-file.",
    "Bh6: Threaten to trade the Dragon bishop.",
    "Qa5: Queen activates with threats.",
    "Bxg7: Execute the bishop trade.",
    "Kxg7: King recaptures, remaining in center but with pawn cover."
  ]
},

{
  id: "sicilian-dragon-yugoslav-g4-be6-line",
  name: "Dragon Yugoslav: g4 with ...Be6 response",
  description: "Yugoslav attack with early g4, met by ...Be6 and knight exchange on e6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "g4", "Be6",
    "Nxe6", "fxe6", "O-O-O", "Ne5"
  ],
  explanations: [
    "e4: White claims center.",
    "c5: Sicilian defense.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon fianchetto.",
    "Be3: Yugoslav setup.",
    "Bg7: Bishop on long diagonal.",
    "f3: Support e4.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "g4: Early kingside pawn storm.",
    "Be6: Develop bishop actively, hitting d5 and c4.",
    "Nxe6: Exchange to damage black's pawn structure.",
    "fxe6: Recapture, creating doubled e-pawns but opening f-file.",
    "O-O-O: White completes queenside castling.",
    "Ne5: Knight centralizes to strong outpost."
  ]
},

{
  id: "sicilian-dragon-yugoslav-g5-nh5-line",
  name: "Dragon Yugoslav: g5 forcing ...Nh5",
  description: "Yugoslav attack with g4-g5 push, forcing knight to h5 where it's less active.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
    "g4", "Rc8", "g5", "Nh5"
  ],
  explanations: [
    "e4: White takes center.",
    "c5: Sicilian counterplay.",
    "Nf3: Develop and prepare d4.",
    "d6: Support center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon setup.",
    "Be3: Yugoslav system.",
    "Bg7: Bishop on diagonal.",
    "f3: Support e4.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "O-O-O: White castles queenside.",
    "Bd7: Develop bishop.",
    "g4: Start kingside pawn storm.",
    "Rc8: Rook to c-file for counterplay.",
    "g5: Push pawn, attacking knight.",
    "Nh5: Knight retreats to edge, avoiding exchange but less active."
  ]
},

{
  id: "sicilian-dragon-yugoslav-h5-a4-bxf6",
  name: "Dragon Yugoslav: h5, ...a4, and Bxf6 exchange",
  description: "Yugoslav line with h5 push, met by ...a4 pawn advance and bishop exchange on f6.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "h4", "a5", "h5", "a4",
    "Bxf6", "exf6"
  ],
  explanations: [
    "e4: White takes center.",
    "c5: Sicilian defense.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon fianchetto.",
    "Be3: Yugoslav setup.",
    "Bg7: Bishop on long diagonal.",
    "f3: Support e4.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "Bc4: Active bishop placement.",
    "Bd7: Develop bishop.",
    "O-O-O: Opposite side castling.",
    "Rc8: Rook to c-file.",
    "Bb3: Retreat bishop.",
    "Nxd4: Trade knight.",
    "Bxd4: Recapture with bishop.",
    "b5: Queenside expansion.",
    "h4: Kingside pawn storm.",
    "a5: Black's queenside counter.",
    "h5: Continue kingside attack.",
    "a4: Pawn push, threatening to trap bishop.",
    "Bxf6: Trade bishop for knight to relieve pressure.",
    "exf6: Recapture, doubling pawns but opening e-file."
  ]
},

{
  id: "sicilian-dragon-yugoslav-h4-h5-be2-line",
  name: "Dragon Yugoslav: h4 met by ...h5 with Be2 setup",
  description: "Yugoslav attack where black responds to h4 with ...h5, blocking white's pawn storm.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "O-O-O", "Bd7",
    "h4", "h5", "Be2", "Rc8"
  ],
  explanations: [
    "e4: White claims center.",
    "c5: Sicilian response.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon setup.",
    "Be3: Yugoslav system.",
    "Bg7: Bishop on diagonal.",
    "f3: Support e4.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "O-O-O: White castles queenside.",
    "Bd7: Develop bishop.",
    "h4: Start kingside pawn storm.",
    "h5: Black blocks the pawn advance, stopping h5 ideas.",
    "Be2: Develop bishop, more solid than Bc4.",
    "Rc8: Rook to c-file for queenside counterplay."
  ]
},

{
  id: "sicilian-dragon-yugoslav-nd5-early-line",
  name: "Dragon Yugoslav: Early Nd5 before h4",
  description: "Yugoslav line where white plays Nd5 immediately after ...b5, skipping h4 initially.",
  moves: [
    "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6", "Bc4", "Bd7", "O-O-O", "Rc8",
    "Bb3", "Nxd4", "Bxd4", "b5", "Nd5", "Nxd5", "Bxg7", "Kxg7",
    "exd5", "a5", "a3", "Kg8"
  ],
  explanations: [
    "e4: White claims center.",
    "c5: Sicilian defense.",
    "Nf3: Develop and prepare d4.",
    "d6: Solid center.",
    "d4: Open center.",
    "cxd4: Exchange.",
    "Nxd4: White recaptures.",
    "Nf6: Pressure e4.",
    "Nc3: Defend and develop.",
    "g6: Dragon fianchetto.",
    "Be3: Yugoslav setup.",
    "Bg7: Bishop on long diagonal.",
    "f3: Support e4.",
    "O-O: King safety.",
    "Qd2: Prepare long castle.",
    "Nc6: Develop and pressure d4.",
    "Bc4: Active bishop placement.",
    "Bd7: Develop bishop.",
    "O-O-O: Opposite side castling.",
    "Rc8: Rook to c-file.",
    "Bb3: Retreat bishop.",
    "Nxd4: Trade knight.",
    "Bxd4: Recapture with bishop.",
    "b5: Queenside expansion.",
    "Nd5: Knight jump to d5, creating threats.",
    "Nxd5: Capture the knight.",
    "Bxg7: Trade the Dragon bishop.",
    "Kxg7: King recaptures.",
    "exd5: Recapture, creating passed d-pawn.",
    "a5: Black continues queenside expansion.",
    "a3: White prepares to meet ...a4.",
    "Kg8: King steps back to g8, connecting rooks."
  ]
},


  {
    id: "sicilian-qxd4-line-early-queen",
    name: "Sideline: early Qxd4 and ...Nc6 hit",
    description: "White recaptures with the queen, Black develops with tempo and equalizes quickly.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Qxd4", "Nc6", "Bb5", "Bd7", "Bxc6", "Bxc6"],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian counterplay.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid support of the center.",
      "d4: Open the center.",
      "cxd4: Exchange and open lines.",
      "Qxd4: Early queen recapture, but it can be hit with tempo.",
      "Nc6: Develop and attack the queen immediately.",
      "Bb5: Pin and keep pressure while avoiding queen harassment.",
      "Bd7: Break the pin and develop.",
      "Bxc6: Trade to reduce black development and simplify.",
      "Bxc6: Recapture, maintain structure and development."
    ]
  },

  {
    id: "sicilian-bg5-h6-bh4-nxe4-core",
    name: "Dragon: Bg5 and ...Nxe4 tactic core",
    description: "Bg5 lines where ...Nxe4 appears as a central tactic and trades follow.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6", "Bg5", "Bg7", "Qd2", "h6", "Bh4", "Nc6", "O-O-O", "Nxe4", "Nxe4", "Nxd4"],
    explanations: [
      "e4: White takes space.",
      "c5: Sicilian response.",
      "Nf3: Develop and prepare d4.",
      "d6: Solid, control e5.",
      "d4: Open center.",
      "cxd4: Exchange and open lines.",
      "Nxd4: White develops with recapture.",
      "Nf6: Pressure e4.",
      "Nc3: Defend and develop.",
      "g6: Dragon setup.",
      "Bg5: Pin the knight and increase pressure.",
      "Bg7: Develop bishop and keep pressure on diagonal.",
      "Qd2: Support long castle and coordination.",
      "h6: Ask the bishop a question and gain luft.",
      "Bh4: Keep the pin and avoid giving up bishop pair.",
      "Nc6: Develop and pressure d4.",
      "O-O-O: Commit to queenside castling and attack.",
      "Nxe4: Tactical grab in the center, testing white coordination.",
      "Nxe4: White recaptures to avoid losing pawn and keep pieces active.",
      "Nxd4: Follow up by trading the centralized knight and simplifying."
    ]
  }
];
