import { withOpeningFeedback } from "./feedback";

// src/openings/staffordGambitLines.js

export const staffordGambitSEOText = `
The Stafford Gambit is a trap-heavy gambit for Black in the Petrov Defense:
1. e4 e5 2. Nf3 Nf6 3. Nxe5 Nc6.

Black gives up a pawn to accelerate development, open the d-file and bishop diagonal, and attack f2 before White can finish developing.
These drills focus on the core Stafford ideas: ...Bc5, ...Ng4, ...Qh4, forcing checks on f2, queen wins on d1, rook traps on h1, and h-file attacks after ...h5.
`;


export const staffordGambitLines = withOpeningFeedback([
  {
    category: "Main traps",
    id: "stafford-quick-mate-bg4",
    name: "Main Stafford trap: 6...Nxe4 and ...Bg4#",
    description: "White pins the knight, Black breaks the pin with ...Nxe4, and grabbing the queen runs straight into mate.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "Bxd8", "Bxf2+", "Ke2", "Bg4#"],
    explanations: [
      "Take central space and open lines for the pieces.",
      "Let's learn the most venomous, tricky, and trappy opening!! The Stafford Gambit! First, let's respond to pawn e4 with pawn e5.",
      "Develop and attack e5.",
      "Counterattack e4 and invite the pawn grab that starts the Stafford.",
      "White takes the pawn, but that knight can be chased and traded off.",
      "The Stafford move. Black develops with tempo instead of copying with ...Nxe4 and falling into a queen trap.",
      "White removes the attacker, but this helps Black open the d-file.",
      "Black captures backward on purpose to open the queen file and the bishop diagonal as fast as possible.",
      "White tries to consolidate, but this is the slow setup Stafford players want to see.",
      "The bishop almost always comes to c5. It points straight at f2 and starts the main attacking pattern.",
      "This pin looks natural, which is why this trap lands so often.",
      "Black breaks the pin immediately. The knight jumps into the center with tempo and keeps the attack alive.",
      "Greedy. White wins the queen but forgets that the king is about to be dragged into the open.",
      "This is the forcing move. Black must check first so the king cannot just step away and keep the queen.",
      "Ke2 is forced. White's king is exposed and the pieces are uncoordinated.",
      "Mate. The bishops and knight cover all the escape squares, so White never gets time to enjoy the queen."
    ]
  },
  {
    category: "Queen win traps",
    id: "stafford-queen-win-ke2-g4-qxd1",
    name: "e5 line: ...Bxf2+ and ...Qxd1",
    description: "White drives the knight, but the d3 setup still lets Black open f2 and win the queen on d1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "dxe4", "Bxf2+", "Ke2", "Bg4+", "Kxf2", "Qxd1"],
    explanations: [
      "Take central space and start with normal development.",
      "Meet the center and keep the Petrov structure.",
      "Develop and hit e5.",
      "Counterattack and invite the Stafford structure.",
      "White takes the pawn and asks Black to prove the compensation.",
      "Develop with tempo instead of copying on e4.",
      "White trades the knight, but Black wants the open d-file and the bishop diagonal.",
      "Black recaptures toward the c-file and keeps all the attacking pieces ready.",
      "White gains space and kicks the knight.",
      "The knight belongs on e4 here. It stays active and keeps f2 and d2 ideas in the air.",
      "This looks solid, but d3 is still a blunder if Black keeps playing actively.",
      "Black does not retreat. The bishop comes to c5 anyway and the attack starts on f2.",
      "White wins the knight, but this opens the diagonal Black was playing for.",
      "The forcing move again. Black drags the king out before cashing in anywhere else.",
      "Ke2 is forced, so the king steps onto the same file as the queen.",
      "Black checks first and lines up the queen on d1.",
      "White takes the bishop, but the queen still cannot escape the pin on the first rank.",
      "Black wins the queen and turns the attack into material."
    ]
  },
  {
    category: "Queen win traps",
    id: "stafford-queen-win-kxf2-qxd1",
    name: "e5 line: Kxf2 allows ...Qxd1",
    description: "The same e5 trap, but White takes on f2 right away and loses the queen immediately.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "dxe4", "Bxf2+", "Kxf2", "Qxd1"],
    explanations: [
      "Take space and open lines.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for counterplay.",
      "Take the pawn, but accept tactical risk.",
      "Develop and attack the knight with tempo.",
      "Trade, but open a file for Black.",
      "Recapture and free the bishop and queen.",
      "Kick the knight and gain space.",
      "Centralize and keep pressure on key squares.",
      "Develop, but keep an eye on f2.",
      "Develop with an immediate threat on f2.",
      "Remove the knight, but open lines.",
      "Sacrifice to open the king and diagonal.",
      "Capture, but the king becomes a target.",
      "Take the queen on d1 after the sacrifice."
    ]
  },

  {
    category: "Queen win traps",
    id: "stafford-queen-win-bg5-line",
    name: "Bg5 line: ...Bxf2+ wins the queen",
    description: "White pins first, then takes on e4, but the same f2 sacrifice still wins the queen on d1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "dxe4", "Bxf2+", "Ke2", "Bg4+", "Kxf2", "Qxd1"],
    explanations: [
      "Take the center.",
      "Meet in the center.",
      "Develop and attack e5.",
      "Invite the pawn grab and aim for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade off the knight, but open lines.",
      "Recapture and open files.",
      "Slow but solid, White tries to consolidate.",
      "Develop and point at f2.",
      "Pin and try to reduce tactics.",
      "Jump in, keeping threats on f2 and d2.",
      "Accept the trade, but open the f2 diagonal.",
      "Sacrifice to drag the king out.",
      "Forced king move into the open.",
      "Check and force the queen on d1 to fall.",
      "Take back, but the queen is still hanging.",
      "Win the queen on d1."
    ]
  },

  {
    category: "Mate traps",
    id: "stafford-mate-qh1",
    name: "Bc4 castling trap: ...Qh4 and ...Qh1#",
    description: "The classic castling trap. Black stacks attacks on f2 and h2 until White runs out of defenders.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "Bc4", "Ng4", "O-O", "Qh4", "h3", "Nxf2", "Qf3", "Nxh3+", "Kh2", "Nf2+", "Kg1", "Qh1#"],
    explanations: [
      "Take central space.",
      "Contest the center.",
      "Develop and attack e5.",
      "Black invites the Stafford structure and plays for activity instead of material.",
      "White grabs the pawn.",
      "The Stafford move develops with tempo.",
      "White trades the c6 knight away.",
      "Black recaptures and keeps every attacking piece ready to jump.",
      "White develops naturally and supports the center.",
      "The bishop goes to c5 and fixes f2 as the main target.",
      "This looks like normal development, but it lets White castle into a known Stafford attack.",
      "Black adds the knight to the f2 attack. This is the key Stafford pattern from the transcript.",
      "White castles, but Black was aiming at the castled king the whole time.",
      "Now the threat is concrete. ...Qh2# is coming and White has too many weaknesses to cover.",
      "h3 stops mate for one move, but it also weakens the dark squares around the king.",
      "Black breaks through on f2. The bishop supports the knight, and White's queen is also being hit in many lines.",
      "White tries to add a defender and keep the queen active.",
      "This check removes another defender and keeps White's king running.",
      "The king has to move. The attack only gets stronger.",
      "Another forcing check. Black keeps every move with tempo.",
      "White is driven back toward the corner.",
      "Mate on h1. The whole attack works because Black had more attackers than White had defenders."
    ]
  },
  {
    category: "Queen wins",
    id: "stafford-queen-win-qxh1",
    name: "e5 line: ...Nxg3 and ...Qxh1",
    description: "Black opens the dark squares, checks on e4, and then takes the rook on h1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d4", "Qh4", "g3", "Nxg3", "fxg3", "Qe4+", "Qe2", "Qxh1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, looking for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and open files.",
      "Gain space and hit the knight.",
      "Centralize and keep tactics alive.",
      "Fight for the center, but weaken the diagonal.",
      "Queen to h4, aiming at e4 and h2 squares.",
      "Defend the king side, but weaken dark squares.",
      "Fork and attack key squares, opening lines.",
      "Capture, but it opens the g file and king.",
      "Check to force a concession and keep tempo.",
      "Block and try to trade queens.",
      "Win the rook on h1."
    ]
  },

  {
    category: "Rook wins",
    id: "stafford-rook-win-nxh1",
    name: "Nc3 and f3: ...Nf2 and ...Nxh1",
    description: "Black's ...Ng4 idea is not just about f2. If White weakens the king with f3, the knight forks into h1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "f3", "Nf2", "Qe2", "Nxh1"],
    explanations: [
      "Take central space.",
      "Contest the center.",
      "Develop and attack e5.",
      "Invite the Stafford structure and the tactical fight that follows.",
      "White takes the pawn.",
      "Black develops with tempo instead of trying to copy White.",
      "White trades off the attacking knight on c6.",
      "Black recaptures backward to open files and diagonals quickly.",
      "White chooses a slow setup and gives Black time to aim at f2.",
      "The bishop lands on c5 and makes f2 a real tactical target.",
      "White develops naturally, but this move is one of the transcript's common traps.",
      "Black jumps toward f2. The knight and bishop now work together.",
      "This tries to kick the knight, but it weakens e3 and leaves the rook on h1 loose.",
      "Black dives into f2. The bigger point is the fork on h1 and the pressure on the queen side of the board.",
      "White covers what they can, but the rook is still hanging.",
      "Black takes the rook on h1 and comes out ahead."
    ]
  },
  {
    category: "Queen and rook wins",
    id: "stafford-rook-win-qh4-h5-line",
    name: "h3 counter met by ...h5: h-file conversion",
    description: "When White uses h3 to stop ...Ng4, Black can answer with ...h5 and still open the h-file for a direct attack.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Be2", "h5", "O-O", "Ng4", "h3", "Qd6", "Bxg4", "hxg4", "e5", "Qg6", "d4", "gxh3", "g3", "h2+", "Kh1", "Qe4+", "f3", "Qxd4", "Qxd4", "Bxd4"],
    explanations: [
      "Take space and open lines.",
      "Meet the center.",
      "Develop and attack e5.",
      "Invite the Stafford structure.",
      "White grabs the pawn.",
      "Black develops with tempo.",
      "White trades, but Black gets the open d-file and fast piece play.",
      "Black recaptures and keeps the initiative.",
      "White chooses a quiet setup instead of forcing tactics immediately.",
      "The bishop goes to c5 and keeps f2 under pressure.",
      "Be2 is one of the target setups against the Stafford h5 plan.",
      "Black plays h5 to keep the attack alive even if ...Ng4 gets challenged later.",
      "White castles, but Black was preparing to attack the castled king.",
      "Now the knight jumps in because the h-pawn already supports the idea of opening the h-file.",
      "White tries to ask the knight a question.",
      "Black keeps the queen centralized and preserves the attacking pieces.",
      "White eliminates the knight, but that was part of Black's idea.",
      "The h-pawn recaptures and opens the h-file toward White's king.",
      "White pushes in the center, hoping activity there will distract Black.",
      "Black's queen stays focused on the king side and dark squares.",
      "White opens more lines, but that helps the attacker too.",
      "Black grabs on h3 and creates another pawn deep in White's camp.",
      "White blocks what they can, but the king side remains full of holes.",
      "The h-pawn keeps rolling with check.",
      "Forced. White's king is driven into the corner.",
      "Black checks again and brings the queen deeper into the attack.",
      "White tries to block and survive.",
      "Black wins a central pawn and keeps total control of the attack.",
      "White trades queens to reduce the damage.",
      "Black recaptures and reaches a winning endgame because the attack already did its job."
    ]
  },
  {
    category: "Queen and rook wins",
    id: "stafford-h5-plan-variant",
    name: "h3 counter met by ...h5: c3 and rook trade line",
    description: "A second h5 plan where Black keeps the h-file attack alive and converts once the queen trade appears.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Be2", "h5", "c3", "Ng4", "d4", "Qh4", "g3", "Qf6", "f3", "h4", "fxg4", "hxg3", "Rf1", "gxh2", "Rxf6", "gxf6"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Invite the Stafford structure.",
      "White grabs the pawn.",
      "Black develops with tempo.",
      "White trades, but Black gets the open d-file and active pieces.",
      "Black recaptures and frees the bishop.",
      "White plays slowly, which is what the Stafford hopes for.",
      "The bishop goes to c5 and keeps f2 in sight.",
      "Be2 is a common practical setup against the Stafford.",
      "Black answers with h5 so the h-file attack still exists even if the knight gets traded.",
      "White supports the center and takes away some checking squares.",
      "Black still jumps in with the knight because the h-pawn gives the attack backup.",
      "White strikes the center, but the king side starts to loosen.",
      "The queen arrives on h4 and the threat is immediate.",
      "White blocks the attack for the moment, but g3 creates dark-square damage.",
      "Black keeps the queen active and avoids unnecessary trades.",
      "White tries to hold everything together, but this weakens the king even more.",
      "Black pushes h4 to rip open files near the king.",
      "White takes the knight, but that was the whole point of ...h5.",
      "The h-pawn recaptures and opens the file toward White's king.",
      "White contests the f-file with a rook.",
      "Black pushes through to h2 and creates a permanent tactical problem.",
      "White wins the queen, hoping to escape into an endgame.",
      "Black recaptures and still comes out better because the attack already won enough material."
    ]
  },
  {
    category: "Greedy tactics",
    id: "stafford-greedy-line-rg1-bxg1",
    name: "Qf3 sidestep: ...Nxf2 and ...Bxg1",
    description: "White tries to sidestep the main mate ideas with Qf3, but Black still wins material on the king side.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "Qf3", "Nxf2", "Rg1", "Nxd3+", "Bxd3", "Bxg1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, inviting the pawn grab.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines for Black.",
      "Recapture and activate quickly.",
      "Develop, but allow pressure to build.",
      "Develop and target f2.",
      "Develop and defend.",
      "Jump toward f2 tactics.",
      "Defend f2 and aim to trade queens.",
      "Sacrifice or win material on f2 with a fork.",
      "Defend the rook line, but it is awkward.",
      "Fork again with check and win more material.",
      "Capture back to reduce damage.",
      "Win the rook on g1."
    ]
  },

  {
    category: "Mate traps",
    id: "stafford-mate-qf2",
    name: "e5 line: ...Qh4+ and ...Qf2#",
    description: "A forcing mate after Qh4+ and the queen swings to f2.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "Be3", "Bxe3", "fxe3", "Qh4+", "Ke2", "Qf2#"],
    explanations: [
      "Take the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines for Black.",
      "Recapture and open files.",
      "Kick the knight and gain space.",
      "Centralize and keep tactics alive.",
      "Develop, but keep the king in the center.",
      "Develop and point at f2.",
      "Develop and block lines, but weaken dark squares.",
      "Exchange to open the diagonal to the king.",
      "Forced, recapture and weaken the king cover.",
      "Check and force the king into the open.",
      "Forced king move.",
      "Deliver mate by controlling escape squares."
    ]
  },

  {
    category: "Rook wins",
    id: "stafford-rook-win-qh4-qxh1",
    name: "e5 line: ...Qh4+ and ...Qxh1",
    description: "Black forces the queen onto h4 and wins the rook on h1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "Be3", "Bxe3", "fxe3", "Qh4+", "g3", "Nxg3", "hxg3", "Qxh1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, inviting tactics.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open the file.",
      "Recapture and activate quickly.",
      "Gain space and hit the knight.",
      "Centralize and keep threats.",
      "Develop and try to be solid.",
      "Develop and aim at f2.",
      "Develop, but it can open lines to the king.",
      "Exchange to clear the diagonal.",
      "Forced, and the king side becomes weaker.",
      "Check and force pawn moves.",
      "Block the check, but weaken the dark squares.",
      "Jump in and win material with a fork.",
      "Capture, but open the h file.",
      "Win the rook on h1."
    ]
  },

  {
    category: "Tactical middlegames",
    id: "stafford-line-nxe3-bxe3-qg5",
    name: "Nc3 line: ...Nxe3 and bishop pair pressure",
    description: "Black damages White's structure, plants the bishop on e3, and keeps the initiative with the queen.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "Be3", "Nxe3", "fxe3", "Bxe3", "Qf3", "Qg5"],
    explanations: [
      "Take the center.",
      "Meet in the center.",
      "Develop and attack e5.",
      "Petrov, offering activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and activate pieces.",
      "Develop cautiously.",
      "Develop and target f2.",
      "Develop and defend.",
      "Jump in and aim at f2 and e3.",
      "Challenge the attacker and develop.",
      "Trade off the defender and damage structure.",
      "Forced recapture, weakening the center.",
      "Use the bishop to invade and attack.",
      "Defend and offer queen trades.",
      "Avoid trades and keep pressure with the queen."
    ]
  },

  {
    category: "Perpetual check ideas",
    id: "stafford-perpetual-qe5-qd4",
    name: "h3 line: perpetual check fallback",
    description: "If White survives the first wave, Black can still force perpetual by keeping the queen checks going.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "h3", "Bxf2+", "Kxf2", "Nxe4+", "Kg1", "Qd4+", "Kh2", "Qe5+", "Kg1", "Qd4+"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open files.",
      "Recapture and open the diagonal.",
      "Develop, but leave the king in the center.",
      "Develop and aim at f2.",
      "Create luft, but loosen the king side.",
      "Sacrifice to open the king and force checks.",
      "Capture, but expose the king.",
      "Check in the center to keep initiative.",
      "Step away, but the king is still unsafe.",
      "Check and keep the king boxed in.",
      "Forced king move.",
      "Check to keep the attack going.",
      "Return, still under pressure.",
      "Repeat the check to keep control."
    ]
  },

  {
    category: "Accepted and simple play",
    id: "stafford-simple-d4-bxd4",
    name: "Natural d4 met by ...Bxd4",
    description: "When White strikes with d4 too early, Black can simply capture and keep the development lead.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "d4", "Bxd4"],
    explanations: [
      "Take the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and open files.",
      "Develop and prepare d4.",
      "Develop and pressure the center.",
      "Strike in the center to challenge Black's setup.",
      "Capture and keep development flowing."
    ]
  },

  {
    category: "h5 counterplay",
    id: "stafford-h3-counter-h5-qd4",
    name: "Best-line counter: h3 met by ...h5 and ...Qd4",
    description: "White's early h3 slows down ...Ng4, but Black can answer with ...h5 and keep the h-file attack alive anyway.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "h3", "h5", "Be2", "Qd4", "O-O", "Ng4", "hxg4", "hxg4"],
    explanations: [
      "Take space in the center.",
      "Meet the center and keep the Petrov structure.",
      "Develop and attack e5.",
      "Invite the Stafford structure.",
      "White grabs the pawn.",
      "Black develops with tempo instead of copying on e4.",
      "White trades the c6 knight away.",
      "Black recaptures backward on purpose to open the queen file and bishop diagonal.",
      "White chooses a slow setup and hopes to consolidate.",
      "The bishop goes to c5 and fixes the usual Stafford target on f2.",
      "This is one of White's best practical ideas because it stops an immediate ...Ng4.",
      "Black does not get emotional. ...h5 keeps the h-file attack in reserve and prepares to support a later sacrifice on g4.",
      "White develops the bishop and keeps castling available.",
      "The queen centralizes with tempo and makes it awkward for White to ignore the coming attack.",
      "White castles, but Black still gets the kind of king-side target the h5 plan was built for.",
      "Now the knight jumps in. The whole point of ...h5 was to make this sacrifice playable.",
      "White takes the knight to remove the attacker.",
      "Black recaptures with the h-pawn, opens the h-file, and keeps the attack going."
    ]
  },

  {
    category: "Declined lines",
    id: "stafford-decline-4-nf3-mainline",
    name: "Decline: 4.Nf3 and calm Petrov play",
    description: "If White gives the pawn back immediately, the game leaves Stafford territory and becomes a simpler Petrov.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nf3", "Nxe4", "Qe2", "Qe7", "Nc3", "Nxc3", "Qxe7+", "Bxe7", "dxc3", "d6"],
    explanations: [
      "Take space and open lines.",
      "Contest the center.",
      "Develop and attack e5.",
      "Counterattack e4 in Petrov style.",
      "White takes the pawn, but can also decide to return it quickly.",
      "Black develops with tempo and keeps the Stafford option available for one move.",
      "White retreats instead of trading on c6, so the real Stafford never appears.",
      "Black wins the pawn back and reaches normal Petrov territory.",
      "White pins the knight and tries to ask Black how the pawn will be held.",
      "This is the clean answer. Black breaks the pin and offers queen trades.",
      "White develops and prepares to recapture on c3.",
      "Black simplifies by trading knights.",
      "White accepts the queen trade to drain the tactics out of the position.",
      "Black recaptures and reaches a calm middlegame.",
      "White takes back with the pawn and opens the c-file.",
      "Black plays d6 and just finishes development."
    ]
  },
  {
    category: "Tactics and initiative",
    id: "stafford-bc4-line-ng3-check",
    name: "Bc4 castling trap: ...Ng3+ continuation",
    description: "A sharper continuation of the castling trap where Black keeps checking instead of cashing out immediately.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "Bc4", "Ng4", "O-O", "Qh4", "h3", "Nxf2", "Bxf7+", "Kf8", "Qh5", "Nxe4+", "Kh1", "Ng3+"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Invite the Stafford fight instead of a quiet Petrov.",
      "White grabs the pawn.",
      "Black develops with tempo.",
      "White trades the c6 knight away.",
      "Black recaptures and keeps the bishop and queen ready to attack.",
      "White develops naturally.",
      "The bishop lands on c5 and marks f2 as the target.",
      "White develops the bishop and prepares to castle into the attack.",
      "Black jumps in with the standard Stafford idea against f2.",
      "White castles, but Black's attack gets faster after castling, not slower.",
      "The queen arrives and threatens mate on h2.",
      "White creates luft, but the king side dark squares are now weaker.",
      "Black sacrifices on f2 to drag the king and queen into awkward squares.",
      "White checks on f7 instead of playing pure defense.",
      "Black steps to safety and keeps the attack going.",
      "White tries to keep the initiative with the queen.",
      "Black checks and wins another tempo while White's king is still exposed.",
      "White has to step away again.",
      "The knight keeps checking from g3 and Black stays in full control of the attack."
    ]
  }
]);
