// src/openings/staffordGambitLines.js

export const staffordGambitSEOText = `
The Stafford Gambit is a trap heavy gambit for Black in the Petrov Defense:
1. e4 e5 2. Nf3 Nf6 3. Nxe5 Nc6.

Black sacrifices a pawn to accelerate development and create immediate tactics against White's king and queen.
These drills focus on common Stafford themes: rapid piece activity, forcing checks, and typical queen traps.
`;


export const staffordGambitLines = [
  {
    category: "Main traps",
    id: "stafford-quick-mate-bg4",
    name: "Quick mate: Bg4# after Bxd8",
    description: "If White grabs the queen on d8, Black can finish with a fast mate.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "Bxd8", "Bxf2+", "Ke2", "Bg4#"],
    explanations: [
      "Take space in the center and open lines.",
      "Meet e4 and claim central space.",
      "Develop and attack e5.",
      "Petrov Defense, attack e4 and invite tactics.",
      "Grab the pawn, but the knight can become a target.",
      "Stafford idea, develop with tempo on the knight.",
      "Remove the attacker and simplify, but it gives Black a file.",
      "Recapture and open the d file for development.",
      "Solid setup, but it is slow and lets Black attack.",
      "Develop and aim at f2 and the king.",
      "Pin the knight and try to reduce tactics.",
      "Centralize and hit White's pieces with tempo.",
      "Grab the queen, but it ignores king safety.",
      "Sacrifice to open lines around the king and force checks.",
      "Step into the open, the king is now exposed.",
      "Deliver mate with bishop and queen side pieces coordinating."
    ]
  },

  {
    category: "Queen win traps",
    id: "stafford-queen-win-ke2-g4-qxd1",
    name: "Queen win: ...Bg4+ then ...Qxd1",
    description: "Black uses a check to win White's queen on d1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "dxe4", "Bxf2+", "Ke2", "Bg4+", "Kxf2", "Qxd1"],
    explanations: [
      "Take space and open lines.",
      "Contest the center.",
      "Develop and attack e5.",
      "Invite the pawn grab and aim for activity.",
      "Take the pawn, but the knight can get chased.",
      "Develop with tempo and threaten tactics.",
      "Simplify, but it helps Black open lines.",
      "Recapture and open files for pieces.",
      "Gain space and kick the knight on e4 squares.",
      "Centralize and keep threats on f2 and d2 squares.",
      "Develop and try to finish development safely.",
      "Develop with pressure on f2 and the king diagonal.",
      "Take the knight, but it opens the f2 square.",
      "Sacrifice to pull the king and open lines.",
      "Forced, the king steps out.",
      "Check and line up a queen capture on d1.",
      "Capture back, but the queen is now pinned to d1.",
      "Win the queen on d1 and convert the attack into material."
    ]
  },

  {
    category: "Queen win traps",
    id: "stafford-queen-win-kxf2-qxd1",
    name: "Queen win: king takes on f2 then ...Qxd1",
    description: "Same idea, but White captures with the king immediately.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "dxe4", "Bxf2+", "Kxf2", "Qxd1"],
    explanations: [
      "Take space and open lines.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for counterplay.",
      "Take the pawn, but accept tactical risk.",
      "Develop and attack the knight with tempo.",
      "Trade, but open a file for Black.",
      "Recapture and free the bishop and queen.",
      "Kick the knight and gain space.",
      "Centralize and keep pressure on key squares.",
      "Develop, but keep an eye on f2.",
      "Develop with an immediate threat on f2.",
      "Remove the knight, but open lines.",
      "Sacrifice to open the king and diagonal.",
      "Capture, but the king becomes a target.",
      "Take the queen on d1 after the sacrifice."
    ]
  },

  {
    category: "Queen win traps",
    id: "stafford-queen-win-bg5-line",
    name: "Queen win: Bg5 line ends with ...Qxd1",
    description: "If White plays Bg5 and captures on e4, Black can still win the queen.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "dxe4", "Bxf2+", "Ke2", "Bg4+", "Kxf2", "Qxd1"],
    explanations: [
      "Take the center.",
      "Meet in the center.",
      "Develop and attack e5.",
      "Invite the pawn grab and aim for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade off the knight, but open lines.",
      "Recapture and open files.",
      "Slow but solid, White tries to consolidate.",
      "Develop and point at f2.",
      "Pin and try to reduce tactics.",
      "Jump in, keeping threats on f2 and d2.",
      "Accept the trade, but open the f2 diagonal.",
      "Sacrifice to drag the king out.",
      "Forced king move into the open.",
      "Check and force the queen on d1 to fall.",
      "Take back, but the queen is still hanging.",
      "Win the queen on d1."
    ]
  },

  {
    category: "Mate traps",
    id: "stafford-mate-qh1",
    name: "Mate: ...Qh1# pattern",
    description: "A classic Stafford king hunt with a queen mate on h1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "Bc4", "Ng4", "O-O", "Qh4", "h3", "Nxf2", "Qf3", "Nxh3+", "Kh2", "Nf2+", "Kg1", "Qh1#"],
    explanations: [
      "Take central space.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov and invite tactics.",
      "Take the pawn.",
      "Develop with tempo and open lines.",
      "Trade, but help Black open the d file.",
      "Recapture and activate pieces quickly.",
      "Develop and support the center.",
      "Develop with a direct eye on f2.",
      "Develop and protect the king side.",
      "Jump in and aim for f2 tactics.",
      "Castle to safety, but the king can still be attacked.",
      "Bring the queen out with threats.",
      "Create luft, but weaken dark squares.",
      "Sacrifice to rip open the king side.",
      "Try to defend and trade queens if possible.",
      "Continue the attack with a check and remove defenders.",
      "Step away from checks, but the net tightens.",
      "Bring another piece in with check.",
      "Forced, step back toward the corner.",
      "Finish with checkmate on h1."
    ]
  },

  {
    category: "Queen wins",
    id: "stafford-queen-win-qxh1",
    name: "Queen win: ...Qxh1",
    description: "Black wins the rook on h1 after forcing checks.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d4", "Qh4", "g3", "Nxg3", "fxg3", "Qe4+", "Qe2", "Qxh1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, looking for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and open files.",
      "Gain space and hit the knight.",
      "Centralize and keep tactics alive.",
      "Fight for the center, but weaken the diagonal.",
      "Queen to h4, aiming at e4 and h2 squares.",
      "Defend the king side, but weaken dark squares.",
      "Fork and attack key squares, opening lines.",
      "Capture, but it opens the g file and king.",
      "Check to force a concession and keep tempo.",
      "Block and try to trade queens.",
      "Win the rook on h1."
    ]
  },

  {
    category: "Rook wins",
    id: "stafford-rook-win-nxh1",
    name: "Rook win: ...Nxh1",
    description: "Black wins the rook with a knight hop after pressure on f2.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "f3", "Nf2", "Qe2", "Nxh1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov and invite the pawn grab.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but give Black open files.",
      "Recapture and free the bishop.",
      "Develop cautiously, but allow pressure to build.",
      "Develop and point at f2.",
      "Develop and defend key squares.",
      "Jump toward f2 and h2 ideas.",
      "Try to kick the knight, but weaken the king side.",
      "Fork and threaten the rook and queen side squares.",
      "Defend, but the rook is still loose.",
      "Win the rook on h1."
    ]
  },

  {
    category: "Queen and rook wins",
    id: "stafford-rook-win-qh4-h5-line",
    name: "Long line: h5 plan and endgame conversion",
    description: "A longer forcing sequence where Black keeps threats and converts to an endgame.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Be2", "h5", "O-O", "Ng4", "h3", "Qd6", "Bxg4", "hxg4", "e5", "Qg6", "d4", "gxh3", "g3", "h2+", "Kh1", "Qe4+", "f3", "Qxd4", "Qxd4", "Bxd4"],
    explanations: [
      "Take space and open lines.",
      "Meet in the center.",
      "Develop and attack e5.",
      "Petrov, offering the gambit idea.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open the d file.",
      "Recapture and activate quickly.",
      "Develop, but stay passive.",
      "Develop and target f2.",
      "Develop and prepare to castle.",
      "Advance the h pawn to open the h file and attack.",
      "Castle, but Black still has initiative.",
      "Jump in and threaten tactics.",
      "Create luft, but weaken squares.",
      "Centralize the queen and keep pressure.",
      "Trade off a key attacker, but open the h file.",
      "Open the h file toward White's king.",
      "Push, but it can open lines against White.",
      "Reposition the queen for checks and captures.",
      "Try to open the center, but the king side is weak.",
      "Grab and create a dangerous passer on h3.",
      "Try to block, but the king side stays exposed.",
      "Advance to h2 with check and force the king into the corner.",
      "Forced king move.",
      "Check and win more material with tempo.",
      "Try to block and survive.",
      "Win a pawn and keep the attack converted into material.",
      "Trade queens to reach a winning endgame.",
      "Convert by taking back with the bishop."
    ]
  },

  {
    category: "Queen and rook wins",
    id: "stafford-h5-plan-variant",
    name: "Long line: h5 plan with c3 and rook trades",
    description: "Another longer Stafford structure with h pawn pushes and rook exchanges.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Be2", "h5", "c3", "Ng4", "d4", "Qh4", "g3", "Qf6", "f3", "h4", "fxg4", "hxg3", "Rf1", "gxh2", "Rxf6", "gxf6"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines for Black.",
      "Recapture and free the bishop.",
      "Develop, but allow Black to build up.",
      "Develop with pressure on f2.",
      "Prepare to castle and defend.",
      "Push the h pawn to open a file toward the king.",
      "Support the center and create a retreat square.",
      "Jump in and aim at f2 tactics.",
      "Open the center, but it can help Black's pieces.",
      "Queen to h4 with threats.",
      "Defend, but create weaknesses.",
      "Reposition to keep pressure and avoid trades.",
      "Try to stabilize, but loosen the king.",
      "Advance the h pawn again to open lines.",
      "Capture, but open files near the king.",
      "Open the h file and create a dangerous pawn.",
      "Put the rook on the f file to contest.",
      "Promote the pawn to h2, creating a major threat.",
      "Take the queen, but allow a recapture.",
      "Recapture and convert to a favorable endgame."
    ]
  },

  {
    category: "Greedy tactics",
    id: "stafford-greedy-line-rg1-bxg1",
    name: "Greedy line: ...Nxf2 and ...Bxg1",
    description: "Black wins material by hitting f2 and then taking on g1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "Qf3", "Nxf2", "Rg1", "Nxd3+", "Bxd3", "Bxg1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, inviting the pawn grab.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines for Black.",
      "Recapture and activate quickly.",
      "Develop, but allow pressure to build.",
      "Develop and target f2.",
      "Develop and defend.",
      "Jump toward f2 tactics.",
      "Defend f2 and aim to trade queens.",
      "Sacrifice or win material on f2 with a fork.",
      "Defend the rook line, but it is awkward.",
      "Fork again with check and win more material.",
      "Capture back to reduce damage.",
      "Win the rook on g1."
    ]
  },

  {
    category: "Mate traps",
    id: "stafford-mate-qf2",
    name: "Mate: ...Qf2# after Qh4+",
    description: "A forcing mate after Qh4+ and the queen swings to f2.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "Be3", "Bxe3", "fxe3", "Qh4+", "Ke2", "Qf2#"],
    explanations: [
      "Take the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines for Black.",
      "Recapture and open files.",
      "Kick the knight and gain space.",
      "Centralize and keep tactics alive.",
      "Develop, but keep the king in the center.",
      "Develop and point at f2.",
      "Develop and block lines, but weaken dark squares.",
      "Exchange to open the diagonal to the king.",
      "Forced, recapture and weaken the king cover.",
      "Check and force the king into the open.",
      "Forced king move.",
      "Deliver mate by controlling escape squares."
    ]
  },

  {
    category: "Rook wins",
    id: "stafford-rook-win-qh4-qxh1",
    name: "Rook win: ...Qxh1 after Qh4+",
    description: "Black forces the queen onto h4 and wins the rook on h1.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "e5", "Ne4", "d3", "Bc5", "Be3", "Bxe3", "fxe3", "Qh4+", "g3", "Nxg3", "hxg3", "Qxh1"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, inviting tactics.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open the file.",
      "Recapture and activate quickly.",
      "Gain space and hit the knight.",
      "Centralize and keep threats.",
      "Develop and try to be solid.",
      "Develop and aim at f2.",
      "Develop, but it can open lines to the king.",
      "Exchange to clear the diagonal.",
      "Forced, and the king side becomes weaker.",
      "Check and force pawn moves.",
      "Block the check, but weaken the dark squares.",
      "Jump in and win material with a fork.",
      "Capture, but open the h file.",
      "Win the rook on h1."
    ]
  },

  {
    category: "Tactical middlegames",
    id: "stafford-line-nxe3-bxe3-qg5",
    name: "Tactics: ...Nxe3 and ...Qg5",
    description: "Black gives up a bishop pair to win pawns and keep initiative.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Nc3", "Ng4", "Be3", "Nxe3", "fxe3", "Bxe3", "Qf3", "Qg5"],
    explanations: [
      "Take the center.",
      "Meet in the center.",
      "Develop and attack e5.",
      "Petrov, offering activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and activate pieces.",
      "Develop cautiously.",
      "Develop and target f2.",
      "Develop and defend.",
      "Jump in and aim at f2 and e3.",
      "Challenge the attacker and develop.",
      "Trade off the defender and damage structure.",
      "Forced recapture, weakening the center.",
      "Use the bishop to invade and attack.",
      "Defend and offer queen trades.",
      "Avoid trades and keep pressure with the queen."
    ]
  },

  {
    category: "Perpetual check ideas",
    id: "stafford-perpetual-qe5-qd4",
    name: "Perpetual checks: queen on d4",
    description: "Black forces repeated checks to keep the initiative and avoid being worse.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "h3", "Bxf2+", "Kxf2", "Nxe4+", "Kg1", "Qd4+", "Kh2", "Qe5+", "Kg1", "Qd4+"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open files.",
      "Recapture and open the diagonal.",
      "Develop, but leave the king in the center.",
      "Develop and aim at f2.",
      "Create luft, but loosen the king side.",
      "Sacrifice to open the king and force checks.",
      "Capture, but expose the king.",
      "Check in the center to keep initiative.",
      "Step away, but the king is still unsafe.",
      "Check and keep the king boxed in.",
      "Forced king move.",
      "Check to keep the attack going.",
      "Return, still under pressure.",
      "Repeat the check to keep control."
    ]
  },

  {
    category: "Accepted and simple play",
    id: "stafford-simple-d4-bxd4",
    name: "Simple: 6.d4 and ...Bxd4",
    description: "If White plays d4 early, Black can just take and develop.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "d4", "Bxd4"],
    explanations: [
      "Take the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, aiming for activity.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and open files.",
      "Develop and prepare d4.",
      "Develop and pressure the center.",
      "Strike in the center to challenge Black's setup.",
      "Capture and keep development flowing."
    ]
  },

  {
    category: "Declined lines",
    id: "stafford-decline-4-nf3-mainline",
    name: "Decline: 4.Nf3 and simplify",
    description: "If White declines the pawn with 4.Nf3, the game becomes a calmer Petrov line.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nf3", "Nxe4", "Qe2", "Qe7", "Nc3", "Nxc3", "Qxe7+", "Bxe7", "dxc3", "d6"],
    explanations: [
      "Take space and open lines.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov Defense.",
      "Take the pawn, but White may give it back.",
      "Develop with tempo and keep options.",
      "Retreat and avoid giving Black open files.",
      "Win the pawn back and equalize material.",
      "Pin the knight and aim to win back the pawn.",
      "Defend and offer queen trades.",
      "Develop and prepare to recapture.",
      "Simplify by trading knights.",
      "Trade queens to reduce tactics.",
      "Recapture and reach a calmer position.",
      "Take back with the pawn and open the c file.",
      "Develop and solidify the center."
    ]
  },

  {
    category: "Tactics and initiative",
    id: "stafford-bc4-line-ng3-check",
    name: "Tactics: Bc4 line ending with ...Ng3+",
    description: "A sharp sideline where Black keeps checks and initiative.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "Nc3", "Bc5", "Bc4", "Ng4", "O-O", "Qh4", "h3", "Nxf2", "Bxf7+", "Kf8", "Qh5", "Nxe4+", "Kh1", "Ng3+"],
    explanations: [
      "Control the center.",
      "Contest the center.",
      "Develop and attack e5.",
      "Petrov, invite the gambit.",
      "Take the pawn.",
      "Develop with tempo.",
      "Trade, but open lines.",
      "Recapture and activate quickly.",
      "Develop and defend.",
      "Develop and pressure f2.",
      "Develop aggressively and aim at f7.",
      "Jump in and threaten tactics.",
      "Castle, but the king can still be attacked.",
      "Bring the queen out with threats.",
      "Create luft, but weaken squares.",
      "Sacrifice to open the king side.",
      "Check and force the king into defense.",
      "Forced response to the check.",
      "Keep the queen active and threaten mates.",
      "Check and win time to improve pieces.",
      "Step to safety, but remain under attack.",
      "Continue with a check to keep initiative."
    ]
  }
];
