import { withOpeningFeedback } from "./feedback";

export const vantKruijsOpeningLines = withOpeningFeedback([
  {
    category: "Main setup",
    id: "vant-kruijs-01-central-build",
    name: "Qb3 system met by ...d5, ...c5, and ...e5",
    description: "Black ignores the cosmetic queenside pressure, develops cleanly, and reaches the ideal anti-system central break with ...e5.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nf3", "e6", "Be2", "Bd6", "O-O", "O-O", "Nbd2", "e5"],
    explanations: [
      "White starts with pawn to {{square e3}}, a flexible move that does not fight for the center yet.",
      "Let's learn the Van't Kruijs Opening! When White opens with {{square e3}}, answer with pawn to {{square d5}} and claim the center.",
      "White prepares {{square d4}}, but this is still a passive version of a queen pawn shell.",
      "Black develops naturally, controls {{square e4}}, and keeps both central breaks available.",
      "White finally builds a center, but it is not stable yet.",
      "Black challenges that center at once. Against slow system play, this is the clean practical reaction.",
      "White points at {{square b7}} and tries to create side pressure before finishing development.",
      "Black keeps developing and refuses to get distracted by ghost pressure on {{square b7}}.",
      "White develops toward castling and keeps the setup compact.",
      "Black supports the center and keeps the light-squared bishop flexible until the structure is clearer.",
      "White develops, but Black is still the side setting the terms of the position.",
      "Black places the bishop on an active square, eyes the kingside, and gets ready to castle.",
      "White castles, but the setup is still short on active counterplay.",
      "Black castles too and removes tactical noise before striking in the center.",
      "White completes development, but the position has already given Black too much freedom.",
      "Black plays ...{{square e5}} at the right moment and reaches the ideal version of this anti-system structure."
    ]
  },
  {
    category: "Center tension",
    id: "vant-kruijs-02-dxe5-main-break",
    name: "After ...e5, meet dxe5 with ...Nxe5",
    description: "When White exchanges after the central break, Black recaptures with a piece, improves activity, and keeps pressure in the middle.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nf3", "e6", "Be2", "Bd6", "O-O", "O-O", "Nbd2", "e5", "dxe5", "Nxe5"],
    explanations: [
      "White begins with the same restrained setup and hopes Black will drift.",
      "Black takes central space immediately.",
      "White supports {{square d4}}, but the position is still quiet and slightly passive.",
      "Black develops and keeps both ...{{square c5}} and ...{{square e5}} available.",
      "White occupies the center.",
      "Black challenges it before White can settle into a free setup.",
      "White repeats the early queen move, trying to distract Black from central play.",
      "Black keeps developing and refuses to waste time on side issues.",
      "White develops naturally toward castling.",
      "Black supports the center and prepares the dark-squared bishop.",
      "White keeps the position compact.",
      "Black develops the bishop to an active square and nears full development.",
      "White castles and hopes the structure will hold.",
      "Black castles and completes the basic setup safely.",
      "White brings out the last minor piece but still has not challenged Black's plan.",
      "Black finally breaks with ...{{square e5}} at the right moment.",
      "White captures to reduce the pressure in the center.",
      "Black recaptures with the knight, improves piece activity, and keeps control over the key central squares."
    ]
  },
  {
    category: "Broad center",
    id: "vant-kruijs-03-bd3-early-e5",
    name: "Bd3 setup met by an immediate ...e5 break",
    description: "If White develops the bishop early and leans on a broad center, Black can hit back with ...e5 before White is fully coordinated.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Bd3", "e5", "dxe5", "Nxe5", "Be2", "Bd6", "Nf3", "O-O"],
    explanations: [
      "White starts quietly and hopes to steer the game into a familiar structure.",
      "Black takes the center at once.",
      "White supports {{square d4}}, but the setup is still slower than a normal queen pawn opening.",
      "Black develops and prepares to challenge the center with pieces and pawns.",
      "White finally builds the center.",
      "Black hits immediately with ...{{square c5}} and refuses to let White sit there uncontested.",
      "White uses Q{{square b3}} again, aiming at {{square b7}} and trying to distract Black from the middle.",
      "Black develops and keeps ignoring side pressure.",
      "White points the bishop toward the kingside and supports {{square e4}} ideas.",
      "Black breaks with ...{{square e5}} before White is ready. That asks the right question immediately.",
      "White captures because leaving the tension alone would concede central space.",
      "Black recaptures with a piece and improves central control at the same time.",
      "White retreats and admits the center did not hold.",
      "Black develops smoothly and points more force toward the center and kingside.",
      "White develops, but Black already has the easier game.",
      "Black castles and reaches a very comfortable structure with no weaknesses."
    ]
  },
  {
    category: "Pawn capture",
    id: "vant-kruijs-04-dxc5-queen-pawn-grab",
    name: "Early dxc5 met by ...Bxc5 and easy development",
    description: "If White grabs on c5 before finishing development, Black wins the pawn back with active piece play and reaches the better structure.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "dxc5", "e6", "Nf3", "Bxc5", "Be2", "O-O", "O-O", "e5"],
    explanations: [
      "White starts with the same slow setup.",
      "Black claims central space immediately.",
      "White prepares {{square d4}} in Colle style.",
      "Black develops and keeps the center under control.",
      "White builds the center.",
      "Black challenges it right away with ...{{square c5}}.",
      "White again places the {{queen b3 full}}, trying to create side pressure.",
      "Black develops and keeps the {{square c5}} pawn tactically supported.",
      "White grabs the pawn, but this costs time and helps Black develop.",
      "Black calmly supports recovery of the pawn and opens lines for the bishop.",
      "White develops, but Black is about to win the pawn back under ideal conditions.",
      "Black recaptures with the bishop and gains active piece play for free.",
      "White continues development, but Black's pieces are already more active.",
      "Black castles and reaches safety with no structural damage.",
      "White castles too, but the pawn grab solved none of White's opening problems.",
      "Black takes more space with ...{{square e5}} and claims the better version of the structure."
    ]
  },
  {
    category: "Against Qb3 pressure",
    id: "vant-kruijs-05-qc7-calms-queenside",
    name: "Qb3 pressure calmly answered by ...Qc7",
    description: "Black covers the queenside in one move, keeps the position healthy, and stays ready for the usual central play.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "e6", "Nf3", "Nc6", "Be2", "Bd6", "O-O", "O-O", "Rd1", "Qc7"],
    explanations: [
      "White starts with the same restrained opening move.",
      "Black claims central space immediately.",
      "White builds toward {{square d4}}, but there is still no direct challenge.",
      "Black develops and keeps the position simple.",
      "White puts a pawn in the center.",
      "Black strikes at it right away. That is the critical practical idea.",
      "White points at {{square b7}} and hopes Black will waste time defending a side target.",
      "Black supports the center first and keeps the structure intact.",
      "White develops normally.",
      "Black develops and keeps control of the dark squares.",
      "White completes another quiet move.",
      "Black develops actively and stays ahead in central influence.",
      "White castles and hopes the {{queen b3 full}} still matters.",
      "Black castles too and removes most tactical nonsense.",
      "White adds support on the d file.",
      "Black calmly plays ...Q{{square c7}}, covers {{square b7}}, and keeps every important central plan available."
    ]
  },
  {
    category: "Bishop drift",
    id: "vant-kruijs-06-bf3-slow-setup",
    name: "Bf3 setup met by clean development and ...e5",
    description: "When White spends extra tempi moving the bishop around, Black should keep building normally and break only when everything is ready.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Be2", "e6", "Bf3", "Bd6", "Nd2", "O-O", "Ne2", "e5"],
    explanations: [
      "White opens with the same slow structure and hopes to reach a comfortable setup.",
      "Black takes central space immediately.",
      "White supports {{square d4}}, but this is still very modest.",
      "Black develops and keeps all the important central breaks available.",
      "White occupies the center, but the structure is not secure yet.",
      "Black challenges the center before White can drift into a free middlegame.",
      "White places the {{queen b3 full}} again, trying to create queenside pressure.",
      "Black keeps developing and refuses to overreact.",
      "White develops, but there is still no direct threat.",
      "Black supports the center and prepares smooth piece play.",
      "White loses another tempo with the bishop. That only helps if Black cooperates.",
      "Black develops the bishop to a natural square and keeps the structure healthy.",
      "White tries to complete development at last.",
      "Black castles and reaches full safety first.",
      "White keeps shuffling instead of challenging Black directly.",
      "Black breaks with ...{{square e5}} once everything is ready and takes over the game."
    ]
  },
  {
    category: "Development",
    id: "vant-kruijs-07-nd2-before-nf3",
    name: "Nd2 first still runs into the same central plan",
    description: "A different move order does not change the verdict. Black still develops, castles, and breaks with ...e5 under ideal conditions.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nd2", "e6", "Ngf3", "Bd6", "Be2", "O-O", "O-O", "e5"],
    explanations: [
      "White begins with the same low-pressure setup.",
      "Black takes central space immediately.",
      "White supports {{square d4}} and still aims for the same shell.",
      "Black develops naturally and keeps the center under control.",
      "White builds the center.",
      "Black challenges it before White gets everything for free.",
      "White repeats the early queen move and points at {{square b7}}.",
      "Black develops calmly and refuses to get provoked.",
      "White chooses a slightly different development order.",
      "Black supports the center and prepares full development.",
      "White finally develops the king knight as well.",
      "Black develops the bishop to its most natural square in this structure.",
      "White keeps consolidating rather than testing Black directly.",
      "Black castles and removes tactical noise from the position.",
      "White castles and reaches the same passive shell.",
      "Black breaks with ...{{square e5}} and gets the same good version of the position."
    ]
  },
  {
    category: "Expansion",
    id: "vant-kruijs-08-e4-overreach",
    name: "e4 overreach met by ...c4",
    description: "If White expands late with e4 after Black is fully ready, Black can lock the structure with ...c4 and seize the more useful space.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nf3", "e6", "Bd3", "Bd6", "O-O", "O-O", "Nbd2", "e5", "e4", "c4"],
    explanations: [
      "White begins with the same restrained setup.",
      "Black takes central space at once.",
      "White prepares {{square d4}} in typical system fashion.",
      "Black develops and keeps the center flexible.",
      "White occupies the center.",
      "Black challenges that center immediately with ...{{square c5}}.",
      "White places the {{queen b3 full}} again, but this still does not solve White's development issues.",
      "Black develops and keeps pressure on the middle of the board.",
      "White develops and keeps the usual shell intact.",
      "Black supports the center and prepares smooth piece play.",
      "White points the bishop toward the kingside and center.",
      "Black mirrors with active development and keeps the {{square e5}} break ready.",
      "White castles and hopes the setup will finally function.",
      "Black castles too and completes the basic setup safely.",
      "White develops the last minor piece, but Black is now ready to challenge the center fully.",
      "Black breaks with ...{{square e5}}, the key move in this structure.",
      "White grabs more space, but the center is now fixed and gives Black clear targets.",
      "Black answers with ...{{square c4}}, gains queenside space, shuts down the bishop, and proves White expanded too late."
    ]
  },
  {
    category: "Misplaced knight",
    id: "vant-kruijs-09-nh3-space-gain",
    name: "Nh3 setup punished with ...c4 and ...g5",
    description: "When White puts the knight on h3, Black can take more space, clamp the structure, and make the awkward piece a direct target.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nh3", "e5", "dxe5", "Nxe5", "Nf4", "c4", "Qc2", "g5"],
    explanations: [
      "White begins with the same slow first move.",
      "Black takes the center immediately.",
      "White prepares {{square d4}}, but still has not challenged Black's development.",
      "Black develops and keeps the central breaks ready.",
      "White claims central space.",
      "Black hits the center before White can settle.",
      "White uses Q{{square b3}} again, hoping for pressure on {{square b7}}.",
      "Black develops and ignores the distraction.",
      "White puts the {{knight h3 full}}, which is clumsy in this structure.",
      "Black takes more central space because awkward development should be punished.",
      "White captures to relieve the pressure.",
      "Black recaptures with a knight and keeps the center and piece activity.",
      "White improves the knight, but it still lacks real influence.",
      "Black gains queenside space and makes White's coordination even worse.",
      "White steps back to hold the position together.",
      "Black expands with ...{{square g5}} and starts hunting the misplaced knight directly."
    ]
  },
  {
    category: "Development race",
    id: "vant-kruijs-10-be2-before-nf3",
    name: "Quiet Be2 move order still favors Black's setup",
    description: "If White delays the king knight and keeps making quiet moves, Black should just complete development and use the standard ...e5 break.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Be2", "e6", "Nf3", "Bd6", "O-O", "O-O", "Nbd2", "e5"],
    explanations: [
      "White starts with the same slow plan and still does not challenge the center.",
      "Black occupies the center immediately.",
      "White supports {{square d4}} in standard system style.",
      "Black develops and keeps control over {{square e4}}.",
      "White claims central space.",
      "Black strikes back immediately with ...{{square c5}} and asks White to justify the setup.",
      "White again spends time on Q{{square b3}} instead of faster development.",
      "Black continues naturally and keeps the {{square c5}} pressure intact.",
      "White develops quietly, but there is still no threat to solve.",
      "Black supports the center and prepares to complete development.",
      "White finally brings out the king knight.",
      "Black places the bishop on its most active square in this structure.",
      "White castles and reaches a familiar shell.",
      "Black castles too and completes the safe setup.",
      "White finishes development, but Black has already reached the ideal version of the structure.",
      "Black plays ...{{square e5}} and claims more central space at exactly the right moment."
    ]
  },
  {
    category: "Central recapture",
    id: "vant-kruijs-11-nxe5-bxe5",
    name: "If White trades twice, recapture toward the center with ...Bxe5",
    description: "After the standard ...e5 break, Black is happy to meet Nxe5 with ...Bxe5 and keep active central piece play.",
    moves: ["e3", "d5", "c3", "Nf6", "d4", "c5", "Qb3", "Nc6", "Nf3", "e6", "Be2", "Bd6", "O-O", "O-O", "Nbd2", "e5", "dxe5", "Nxe5", "Nxe5", "Bxe5"],
    explanations: [
      "White begins with the same restrained setup and hopes Black will drift.",
      "Black takes central space immediately.",
      "White supports {{square d4}}, but the position is still quiet and slightly passive.",
      "Black develops and keeps both ...{{square c5}} and ...{{square e5}} available.",
      "White occupies the center.",
      "Black challenges it before White can settle into a free setup.",
      "White repeats the early queen move, trying to distract Black from central play.",
      "Black keeps developing and refuses to waste time on side issues.",
      "White develops naturally toward castling.",
      "Black supports the center and prepares the dark-squared bishop.",
      "White keeps the position compact.",
      "Black develops the bishop to an active square and nears full development.",
      "White castles and hopes the structure will hold.",
      "Black castles and completes the basic setup safely.",
      "White brings out the last minor piece but still has not challenged Black's plan.",
      "Black finally breaks with ...{{square e5}} at the right moment.",
      "White captures to reduce the pressure in the center.",
      "Black recaptures with the knight and keeps the initiative.",
      "White trades one more time, hoping to simplify into something harmless.",
      "Black recaptures toward the center with the bishop, keeps an active piece on {{square e5}}, and stays more comfortable."
    ]
  }
]);

export const vantKruijsOpeningSEOText = `
The Van't Kruijs Opening drill teaches Black how to punish 1.e3 and the common follow-up shell with c3, d4, Qb3, and quiet development using principled central play instead of cheap tricks. The core plan is simple: meet the setup with ...d5 and ...c5, ignore cosmetic pressure on b7, develop cleanly with ...Nf6, ...Nc6, and ...Bd6, castle safely, and only then strike with ...e5 or recapture toward the center when White exchanges. These lines are built as a practical anti-system repertoire against slow Colle and London style structures reached from 1.e3, so the player learns repeatable plans, useful move orders, and when to punish passive development.
`;
