import { withOpeningFeedback } from "./feedback";

export const viennaGameLines = withOpeningFeedback([
  {
    category: "Vienna Game",
    id: "vienna-game-01-b5d29959",
    name: "Qg4 trap: queen wins itself",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "Qf1+",
      "Bxf1"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 is the Vienna Game attack. You hit g7 and f7 and ask Black to show a defense right now.",
      "...Qf6 is a common defense: it covers f7 and keeps ...d6 in reserve, but the queen can become a tactical target.",
      "Nd5 jumps with tempo. It attacks c7 and f6 and makes Black's queen on f6 feel cramped.",
      "Black goes pawn hunting with check. This is greedy and pulls the queen away from defense.",
      "Kd1 is the practical move: step out of checks and keep pieces available. You are not trying to castle here, you are trying to punish the queen.",
      "...Qf1+ is a last check. Black is basically admitting the queen has no safe retreat squares.",
      "Bxf1 wins the queen. The whole point of the line is that the queen runs out of squares after ...Qxf2+."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-02-152b5a79",
    name: "Qg4 trap: g7 grab and fork tactics",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Be6",
      "Nxc7+",
      "Kd7",
      "Nxe6",
      "Nge7",
      "Nh3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 pressures g7 and f7. Your plan is fast piece activity, not slow pawn grabbing.",
      "...Qf6 defends f7 and invites tactics based on Nd5 hitting the queen.",
      "Nd5 hits the queen and also threatens Nc7 forks in some lines. It forces Black to decide between defense and greed.",
      "...Qxf2+ grabs a pawn with check. This is risky because the queen can get trapped.",
      "Kd1 keeps the king safe enough while you chase the queen. It also keeps the rook on h1 ready if needed.",
      "...d6 tries to give the queen an escape route and stabilise the center.",
      "Qxg7 is the payoff: you grab g7 with tempo and threaten mate ideas on f7 and e5.",
      "...Be6 develops and blocks the queen's line, also hitting your queen on g7.",
      "Nxc7+ is a concrete fork. You check the king and also attack the rook on a8.",
      "...Kd7 is forced. Note how Black's king is stuck in the center because of the early queen adventure.",
      "Nxe6 wins another pawn or piece and keeps Black uncoordinated. You are converting initiative into material.",
      "...Nge7 is a cleanup move: Black tries to bring pieces out and cover critical squares.",
      "Nh3 develops with a clear goal: bring the knight to f2 or g5 and finish development while Black is still tangled."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-03-6364f5a8",
    name: "Dark-square mate vs ...g6",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "Nge7",
      "Nf6+",
      "Kf8",
      "Bh6#"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 goes straight for g7. If Black weakens with ...g6, you can often pivot to a safer square and keep pressure.",
      "...g6 commits a pawn move. It stops Qxg7 immediately but creates dark-square weaknesses and leaves the king less safe.",
      "Qf3 keeps the queen active on the diagonal to f7 and also supports potential sacrifices on f7.",
      "...Qf6 is the 'keep it defended' approach. Black wants to trade queens or at least shut down the direct threats.",
      "Nd5 again hits the queen and opens tactical shots. The knight on d5 also supports Nf6 checks.",
      "...Qxf3 is a queen trade attempt. If Black can trade queens, the attack usually fizzles.",
      "Nxf3 accepts the trade but keeps development clean. Now Black's weakened dark squares matter more.",
      "...Bb6 retreats to avoid tactics and keep the bishop on the diagonal.",
      "d3 is quiet but important: it opens your dark bishop later and gives your pieces stable squares.",
      "...Nge7 develops and prepares ...d5 or ...O-O without losing material.",
      "Nf6+ is the key tactic: a forcing check that drags the king onto a dark square.",
      "...Kf8 is forced.",
      "Bh6# is mate. The bishop uses the weakened diagonal created by ...g6, and Black's pieces cannot cover the escape squares."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-04-e8d59293",
    name: "Qg4 line: meet ...Nd4 counterplay",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Nd4",
      "Ne2",
      "Nxe2",
      "Bxe2"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 pressures g7 and f7 and forces Black to play accurately.",
      "...Qf6 defends f7 but places the queen on a square that can be hit by Nd5.",
      "Nd5 with tempo. The goal is to force the queen to a bad square or tempt Black into ...Qxf2+ again.",
      "...Qxf2+ is the greedy grab. If Black does not find a clean exit, the queen gets stuck.",
      "Kd1 sidesteps checks and sets up Qxg7 to win pawns with tempo.",
      "...d6 is meant to open ...Be6 and give the queen breathing room.",
      "Qxg7 threatens Qxf7 mate ideas and forces Black to spend a move on development with tempo.",
      "...Nd4 is counterplay: Black attacks c2 and also hits your queen's escape squares.",
      "Ne2 is a practical block and development. You challenge the d4 knight and keep your king defended.",
      "...Nxe2 trades off your defender and tries to reduce your attacking pieces.",
      "Bxe2 recaptures and keeps the bishop pair. You have won g7 and forced concessions without losing structure."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-05-a7574f21",
    name: "Quiet Vienna: Na4 and g-file tactics",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Nxf3+",
      "gxf3",
      "Bh3",
      "Rg1",
      "Nh5",
      "Rg5",
      "Nxf4",
      "Rxe5+"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 hits e4 and develops. Compared to ...Bc5 lines, Black prioritizes quick piece pressure.",
      "d3 is the quiet Vienna. You keep the center flexible and prepare to build an attack without overextending.",
      "...Bc5 develops and points at f2, normal Italian-style placement.",
      "f4 is the thematic pawn thrust. Even in the quiet Vienna, it challenges e5 and opens lines for your rook and bishop.",
      "...d6 supports e5 and takes away the e5 break tactics.",
      "Nf3 develops and puts another attacker on e5 while preparing to castle.",
      "...Bg4 pins the knight and tries to slow your kingside development. This pin is often annoying if you play carelessly.",
      "Na4 is a concrete plan: hit the c5 bishop and aim to win the bishop pair or force a retreat.",
      "...Nd4 counters in the center. Black uses the freed d4 square to hit c2 and f3.",
      "Nxc5 trades off the active bishop. This reduces Black's pressure on f2 and clears the a4 knight.",
      "...dxc5 opens the d-file and keeps a pawn in the center. Black accepts an isolated c-pawn in exchange for lines.",
      "c3 kicks the d4 knight and builds a pawn chain that can support d4 later.",
      "...Nxf3+ is structural damage. Black gives up the central knight to smash your kingside pawns.",
      "gxf3 accepts the structure. The tradeoff is the g-file opens for your rook and you get the bishop pair.",
      "...Bh3 targets the rook on g1 ideas and tries to exploit your weakened king.",
      "Rg1 is forced defense and also a useful rook activation on the open file you just created.",
      "...Nh5 reroutes toward f4 or g7 and keeps pressure on your weakened squares.",
      "Rg5 is an active defense: you challenge the knight and also create tactics on e5 and g7.",
      "...Nxf4 grabs a pawn and hits e2 and g2 squares. Black is trying to cash in before you stabilise.",
      "Rxe5+ is a forcing move. The check lets you regain material and drag Black into calculations instead of letting them consolidate.",
      "Play Rxe5+ with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-06-f3c53cdd",
    name: "Queen chase: block ...Qd4 and stabilize",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "Kf8",
      "Nh3",
      "Qd4",
      "d3",
      "d6",
      "Qg3",
      "Bxh3",
      "Rf1",
      "Be6",
      "c3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 attacks g7 and f7. You're forcing a defensive move instead of letting Black develop freely.",
      "...Qf6 defends and also eyes b2 in some lines. The downside is it blocks the g7 knight and can be hit by Nd5.",
      "Nd5 gains tempo on the queen and activates a piece into the center.",
      "...Qxf2+ grabs with check. Again, this is where Black can get punished if the queen overextends.",
      "Kd1 is the clean response. You keep your king safe without wasting time on queen blocks.",
      "...Kf8 steps out of immediate danger and tries to keep the queen alive by avoiding discovered tactics.",
      "Nh3 develops with a purpose: defend f2 squares and prepare Nf2 or g5 to attack the queen.",
      "...Qd4 gives the queen a retreat square and hits your center. It's also a way to keep checking possibilities alive.",
      "d3 blocks the queen's line and solidifies c2 and e4. You are cutting off Black's counterplay.",
      "...d6 reinforces e5 and opens the dark bishop, trying to finally develop.",
      "Qg3 keeps queens on and keeps pressure on f2 squares while staying safe from minor piece attacks.",
      "...Bxh3 grabs the knight. Black is trying to remove your defenders since their queen is still exposed.",
      "Rf1 is the point: you hit f7, line up the rook, and also trap the queen if it ever steps wrong.",
      "...Be6 develops and covers f7 while giving the king more breathing room.",
      "c3 is a simple stabiliser that also takes away d4 as a queen outpost and prepares to chase the queen again."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-07-41660e74",
    name: "Simplify: trade queens and win queenside structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "d6",
      "Be3",
      "Be6",
      "Bxb6",
      "Bxd5",
      "exd5",
      "axb6",
      "dxc6"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 puts immediate pressure on g7. This is only good if you keep tempo and don't let Black hit your queen for free.",
      "...g6 creates dark-square weaknesses but removes Qxg7 tactics.",
      "Qf3 keeps pressure on f7 and also supports d3 and Nge2 development.",
      "...Qf6 is the solid queen defense. Black wants to meet threats and maybe trade queens.",
      "Nd5 is still strong: you improve the knight and force Black to react.",
      "...Qxf3 trades queens to defuse the attack.",
      "Nxf3 keeps development and keeps the bishop pair.",
      "...Bb6 preserves the bishop and keeps pressure on the diagonal.",
      "d3 opens your dark bishop and secures the c4 bishop.",
      "...d6 reinforces e5 and makes ...Be6 easy.",
      "Be3 develops and challenges the c5 bishop and d4 squares.",
      "...Be6 meets that challenge and aims to trade off your active bishop.",
      "Bxb6 is a practical decision: remove the defender and ruin Black's queenside structure.",
      "...Bxd5 trades back and tries to repair the structure.",
      "exd5 recaptures and opens the e-file. You also gain a strong pawn on d5 that can cramp Black.",
      "...axb6 gives Black doubled b-pawns and open a-file issues.",
      "dxc6 wins the c6 knight or pawn depending on the exact position. The idea is you cash in the pressure created by the earlier exchanges."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-08-965ca595",
    name: "Forks with Nxc7 and Nxe6+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Be6",
      "Nxc7+",
      "Kd8",
      "Nxe6+",
      "fxe6",
      "Nf3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 goes for g7 and forces Black to defend accurately.",
      "...Qf6 defends and tempts tactics after Nd5.",
      "Nd5 attacks the queen and also threatens fork ideas on c7.",
      "...Qxf2+ is the pawn grab with check.",
      "Kd1 keeps it simple: avoid queen blocks that lose time.",
      "...d6 prepares ...Be6 to hit your queen and give the king a path to safety.",
      "Qxg7 grabs with tempo and keeps threats alive on f7.",
      "...Be6 hits the queen and develops, trying to finally finish development.",
      "Nxc7+ is the fork shot. You're using tempo while Black's king is still uncastled.",
      "...Kd8 is the safe square. Notice Black still cannot castle because of the center and queen activity.",
      "Nxe6+ is another forcing check. You keep the initiative while removing defenders.",
      "...fxe6 damages Black's structure. Their king gets stuck on the dark squares with weakened pawns.",
      "Nf3 develops and prepares to castle or bring pieces into the attack while Black is still exposed."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-09-796dff6a",
    name: "Solid defense ...Nf6 and tactical cleanup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Nf6",
      "Nge2",
      "O-O",
      "d3",
      "d6",
      "Bg5",
      "Kg7",
      "Nd5",
      "Bg4",
      "Bxf6+",
      "Kg8",
      "Qxg4"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 targets g7. Against ...g6 lines, you often switch to a safer square instead of forcing Qxg7 immediately.",
      "...g6 stops Qxg7 and prepares ...Bg7, but it weakens dark squares.",
      "Qf3 keeps pressure on f7 and supports quick development.",
      "...Nf6 is the cleanest defense: develop and hit e4, while also preparing to castle quickly.",
      "Nge2 develops without blocking the f-pawn. It also supports d4 and f4 pushes later.",
      "...O-O is what Black wants: king safety before the tactics start.",
      "d3 keeps the center stable and opens your dark bishop.",
      "...d6 supports e5 and takes away some Nd5 tactics.",
      "Bg5 pins the f6 knight and increases pressure on f6 and e7 squares.",
      "...Kg7 sidesteps potential checks and unpins ideas, also preparing ...h6.",
      "Nd5 centralises and hits e7 and c7. The knight also supports captures on f6.",
      "...Bg4 is counterplay: Black tries to trade your queen or pin your pieces.",
      "Bxf6+ is a concrete decision. You remove a key defender and force king movement or recapture decisions.",
      "...Kg8 is forced to avoid immediate tactics.",
      "Qxg4 wins the bishop or simplifies. You take the active piece that was creating problems."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-10-79f48a6b",
    name: "Win the rook with Nxa8",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "d6",
      "Be3",
      "Bxe3",
      "Nxc7+",
      "Kd7",
      "Nxa8",
      "Bc5",
      "c3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 attacks g7 and forces Black to respond.",
      "...g6 is the pawn shield. It creates weaknesses, but it can be playable if Black gets ...Bg7 and ...O-O fast.",
      "Qf3 keeps your queen active without allowing tempo hits.",
      "...Qf6 defends f7 and keeps an eye on the center.",
      "Nd5 hits the queen and also threatens Nxc7 forks.",
      "...Qxf3 goes for a queen trade to kill the attack.",
      "Nxf3 keeps development clean.",
      "...Bb6 preserves the bishop and keeps control of the diagonal.",
      "d3 stabilises and prepares Be3.",
      "...d6 supports the center and opens the dark bishop.",
      "Be3 develops and asks the bishop on b6 a question.",
      "...Bxe3 trades your active bishop and tries to reduce your attacking resources.",
      "Nxc7+ is the fork. Even without queens, the tactical shot still works because the king and rook alignment is bad.",
      "...Kd7 is forced.",
      "Nxa8 wins the rook. The cost is that your knight is stuck in the corner for a while.",
      "...Bc5 develops and tries to trap the knight on a8.",
      "c3 is the escape plan: you control b4 and prepare b4 or d4 to give the knight a route back."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-11-0c9a409b",
    name: "Quiet Vienna: g-file pressure after ...Nxf3+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Nxf3+",
      "gxf3",
      "Bh3",
      "Rg1",
      "g6",
      "fxe5",
      "Nh5",
      "Bg5"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 pressures e4 and accelerates development.",
      "d3 keeps the structure flexible. You're choosing a slower build instead of immediate gambit tactics.",
      "...Bc5 develops and aims at f2.",
      "f4 challenges the center and asks Black if they can hold e5.",
      "...d6 supports e5 and prepares ...Be6 or ...O-O.",
      "Nf3 develops and puts more pressure on e5.",
      "...Bg4 pins and tries to provoke weaknesses.",
      "Na4 is the standard Vienna plan: hit the bishop and claim the bishop pair.",
      "...Nd4 hits c2 and f3, using the center as counterplay.",
      "Nxc5 trades off the bishop. This reduces Black's immediate activity.",
      "...dxc5 keeps a pawn in the center and opens lines.",
      "c3 kicks the d4 knight and prepares d4 later.",
      "...Nxf3+ forces a structural decision.",
      "gxf3 opens the g-file. You accept doubled pawns in exchange for active rooks and bishops.",
      "...Bh3 tries to exploit the open g-file and target your rook squares.",
      "Rg1 is both defense and activation: you put a rook on the file you opened.",
      "...g6 is a stabiliser: it gives the king luft and prepares ...Bg7.",
      "fxe5 is a practical capture to remove central tension and open lines.",
      "...Nh5 reroutes to f4 and also eyes g7 squares.",
      "Bg5 pins and challenges. You are aiming to punish Black's slow kingside setup.",
      "Play Bg5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-12-61478354",
    name: "Kingside clamp with f5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "O-O",
      "f5",
      "a6",
      "Bg5",
      "h6",
      "Bh4",
      "Nd4",
      "Nxd4",
      "Bxd4",
      "Nd5"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 is natural and challenges e4.",
      "d3 keeps your center intact and prepares Nf3 and f4.",
      "...Bc5 develops quickly.",
      "f4 is the critical pawn break, challenging e5.",
      "...d6 supports e5 and clamps down on e5 pushes.",
      "Nf3 develops and prepares to castle.",
      "...O-O is good defense: king safety before tactics.",
      "f5 gains space and clamps down on e6 and g6. It also signals a kingside attack.",
      "...a6 prepares ...b5 and keeps the bishop from being hit by Na4 ideas.",
      "Bg5 pins the f6 knight, making it harder for Black to defend the kingside.",
      "...h6 asks the bishop to decide and gains luft.",
      "Bh4 keeps the pin and preserves the bishop.",
      "...Nd4 is counterplay in the center. Black tries to hit c2 and f3 and distract you from the kingside.",
      "Nxd4 is the right reaction: remove the central outpost before it becomes a fork factory.",
      "...Bxd4 recaptures and keeps the bishop active.",
      "Nd5 is the follow-up: you plant a knight in the center and threaten c7 and e7, creating tactical pressure.",
      "Play Nd5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-13-e94d3abc",
    name: "Queenside counterplay ...b5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "O-O",
      "f5",
      "a6",
      "Bg5",
      "h6",
      "Bh4",
      "b5",
      "Bb3",
      "Nd4",
      "Nxd4",
      "Bxd4",
      "Nd5"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 challenges e4.",
      "d3 supports e4 and keeps your pawn chain flexible.",
      "...Bc5 develops and pressures f2.",
      "f4 is your central challenge to e5.",
      "...d6 is solid support.",
      "Nf3 continues development.",
      "...O-O prioritizes king safety.",
      "f5 grabs space and starts the kingside clamp.",
      "...a6 prepares ...b5 expansion and stops Na4 from being too annoying.",
      "Bg5 pins the knight and increases attacking potential.",
      "...h6 forces a decision.",
      "Bh4 keeps the pin and maintains pressure.",
      "...b5 is queenside counterplay. Black is trying to expand while your pawns are advanced.",
      "Bb3 preserves the bishop and keeps the diagonal toward f7.",
      "...Nd4 is the central counterstrike.",
      "Nxd4 eliminates the outpost before it forks or hits f3.",
      "...Bxd4 keeps Black's bishop active.",
      "Nd5 plants a knight and threatens c7 and e7 again, often forcing concessions.",
      "Play Nd5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-14-47395b62",
    name: "Pin-break line: Bb5 after structure damage",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Bxf3",
      "gxf3",
      "Nc6",
      "Bb5"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 develops and hits e4.",
      "d3 is the quiet setup, keeping options.",
      "...Bc5 develops.",
      "f4 challenges e5.",
      "...d6 supports and restrains.",
      "Nf3 develops.",
      "...Bg4 pins and aims to slow your kingside.",
      "Na4 hits the bishop and forces it to decide.",
      "...Nd4 is counterplay and tries to punish your knight leaving f3 squares.",
      "Nxc5 trades off the bishop to reduce pressure.",
      "...dxc5 opens lines and keeps a pawn in the center.",
      "c3 kicks the knight and builds a strong pawn chain.",
      "...Bxf3 removes your defender and doubles your pawns again, aiming to expose your king.",
      "gxf3 accepts it and opens the g-file for rook activity.",
      "...Nc6 retreats and re-centers, also attacking d4 and b4 squares.",
      "Bb5 is a check and development idea: you pin the knight and often provoke ...Bd7 or ...d7 concessions.",
      "Play Bb5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-15-3a650599",
    name: "Simple development vs ...Bb4",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bb4",
      "Ne2",
      "O-O",
      "O-O"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 develops and challenges e4.",
      "d3 keeps everything solid. You're aiming for a simple plan: develop, castle, then choose f4 or Nf3 setups.",
      "...Bb4 pins the knight and tries to provoke weaknesses or force you into awkward development.",
      "Ne2 is the antidote: break the pin without compromising your structure, and keep c3 defended.",
      "...O-O finishes development for Black.",
      "O-O completes your own development. This line is about reaching a playable middlegame without tactics.",
      "Play O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-16-15866b05",
    name: "Bishop pair grab with Na4 and Nxb6",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Bb6",
      "Nxb6",
      "axb6",
      "c3",
      "O-O",
      "O-O"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 challenges e4.",
      "d3 is the quiet Vienna. You keep your center and avoid early tactics.",
      "...Bc5 develops and points at f2.",
      "f4 is the thematic break to contest e5.",
      "...d6 supports e5.",
      "Nf3 develops and prepares to castle.",
      "...Bg4 pins the knight to slow your plan.",
      "Na4 immediately challenges the c5 bishop, a key idea in many Vienna setups.",
      "...Bb6 retreats to keep the bishop and avoid exchanging.",
      "Nxb6 is a choice: trade the bishop and damage Black's queenside structure.",
      "...axb6 recaptures, leaving Black with doubled b-pawns and open a-file issues.",
      "c3 is structure: it prepares d4 and keeps central squares controlled.",
      "...O-O finishes development.",
      "O-O completes yours. Now you can push d4 or f5 depending on Black's setup.",
      "Play O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-17-7c28abfb",
    name: "Meet ...d5 strike and keep development",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bb4",
      "Ne2",
      "d5",
      "exd5",
      "Nxd5",
      "O-O",
      "Nxc3",
      "bxc3",
      "Bd6",
      "Ng3"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 develops and attacks e4.",
      "d3 keeps it solid and supports your center.",
      "...Bb4 pins the knight and pressures c3.",
      "Ne2 breaks the pin and prepares to castle without losing the bishop pair.",
      "...d5 is the direct strike. Black tries to punish your slower d3 setup by taking space immediately.",
      "exd5 accepts the challenge and opens lines. If you ignore ...d5 you can get cramped.",
      "...Nxd5 recaptures with a piece, centralising the knight.",
      "O-O gets the king safe before the center opens further.",
      "...Nxc3 grabs on c3 and tries to damage your structure.",
      "bxc3 accepts doubled pawns but opens the b-file and keeps bishops.",
      "...Bd6 develops and targets h2 in some lines.",
      "Ng3 develops with purpose: protect e4, eye f5 and h5, and prepare f4 ideas later.",
      "Play Ng3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-18-833fa36d",
    name: "Central outpost: eliminate ...Nd4",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Nf6",
      "Nge2",
      "O-O",
      "d3",
      "Nd4",
      "Nxd4",
      "exd4",
      "Nd5",
      "Nxd5",
      "Bxd5",
      "c6",
      "Bb3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending e4. In the Vienna, Nc3 also keeps options like f4 or Qg4 open.",
      "Black develops and supports the e5 pawn, preparing ...Nf6 or ...Bc5.",
      "Develop with tempo: Bc4 immediately eyes f7, the weakest point in Black's camp early.",
      "Black matches with ...Bc5, aiming at f2 and racing development.",
      "Qg4 pressures g7 and tries to slow Black's king safety.",
      "...g6 is the pawn shield, but it weakens dark squares around the king.",
      "Qf3 keeps pressure on f7 and supports quick development.",
      "...Nf6 is accurate: develop and hit e4.",
      "Nge2 develops and keeps the f-pawn free.",
      "...O-O is the defensive goal: get the king safe.",
      "d3 supports the center and opens your dark bishop.",
      "...Nd4 is a central jump that hits c2 and creates tactics.",
      "Nxd4 removes the outpost immediately. Letting that knight sit on d4 is asking for forks.",
      "...exd4 opens the e-file and creates a pawn wedge on d4.",
      "Nd5 plants a knight and targets c7 and e7 again.",
      "...Nxd5 trades it off to reduce your pressure.",
      "Bxd5 keeps a bishop on the strong diagonal and restores material balance.",
      "...c6 kicks the bishop and gains space.",
      "Bb3 retreats while keeping pressure on f7 and the diagonal."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-19-3fb807cb",
    name: "Opposite-side castle attack plan",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "exf4",
      "Bxf4",
      "O-O",
      "Qd2",
      "d6",
      "O-O-O"
    ],
    explanations: [
      "Play e4 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play e5 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc3 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play Nc6 with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...Nf6 challenges e4 and speeds up development.",
      "d3 keeps the center stable and prepares Nf3.",
      "...Bc5 develops and targets f2.",
      "f4 is the thematic pawn thrust, challenging e5 immediately.",
      "...exf4 accepts the pawn and opens the e-file and f-file dynamics.",
      "Bxf4 recaptures quickly. The key is not to let Black keep the extra pawn while you fall behind in development.",
      "...O-O secures the king.",
      "Qd2 is a clear plan: connect rooks, prepare long castle, and line up pieces for a kingside pawn storm.",
      "...d6 supports e5 and opens the dark bishop.",
      "O-O-O is the commitment. Opposite-side castling means the game becomes a race: you attack the king while Black counterattacks your king.",
      "Play O-O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  }
]);
