import { withOpeningFeedback } from "./feedback";

export const viennaGameSEOText = `
The Vienna Game starts with 1. e4 e5 2. Nc3 and can branch into direct Qg4 tactics or slower kingside builds.

These drills cover the practical student-facing ideas already in this file:
- direct Qg4 trap lines against ...Bc5 and ...Qf6, where queen hunting and f7 pressure matter more than memorizing names
- quieter Vienna Game setups with d3 and f4, where White builds a kingside attack without rushing the center
- transcript-backed Vienna System plans with g3, Bg2, Nge2, O-O, h3, Kh2, and a fast f4 break
- early ...d5 counterbreak lines where White recaptures bxc3, uses the b-file and long diagonal, and pressures e5 with Re1

Each line explains the concrete point of the move: what gets pinned, what square is being prepared, which move-order detail matters, and where the attack is supposed to come from.
`;

export const viennaGameLines = withOpeningFeedback([
  {
    category: "Vienna Game",
    id: "vienna-game-01-b5d29959",
    name: "Qg4 trap: queen wins itself",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "Qf1+",
      "Bxf1"
    ],
    explanations: [
      "Let's learn the Vienna Game! Start with pawn to {{square e4}} and develop the knight to {{square c3}} for flexible attacking play.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} is the Vienna Game attack. You hit {{square g7}} and {{square f7}} and ask Black to show a defense right now.",
      "...Q{{square f6}} is a common defense: it covers {{square f7}} and keeps ...{{square d6}} in reserve, but the queen can become a tactical target.",
      "N{{square d5}} jumps with tempo. It attacks {{square c7}} and {{square f6}} and makes Black's {{queen f6 full}} feel cramped.",
      "Black goes pawn hunting with check. This is greedy and pulls the queen away from defense.",
      "K{{square d1}} is the practical move: step out of checks and keep pieces available. You are not trying to castle here, you are trying to punish the queen.",
      "...Q{{square f1}}+ is a last check. Black is basically admitting the queen has no safe retreat squares.",
      "Bx{{square f1}} wins the queen. The whole point of the line is that the queen runs out of squares after ...Qx{{square f2}}+."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-02-152b5a79",
    name: "Qg4 trap: g7 grab and fork tactics",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Be6",
      "Nxc7+",
      "Kd7",
      "Nxe6",
      "Nge7",
      "Nh3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} pressures {{square g7}} and {{square f7}}. Your plan is fast piece activity, not slow pawn grabbing.",
      "...Q{{square f6}} defends {{square f7}} and invites tactics based on N{{square d5}} hitting the queen.",
      "N{{square d5}} hits the queen and also threatens N{{square c7}} forks in some lines. It forces Black to decide between defense and greed.",
      "...Qx{{square f2}}+ grabs a pawn with check. This is risky because the queen can get trapped.",
      "K{{square d1}} keeps the king safe enough while you chase the queen. It also keeps the {{rook h1 full}} ready if needed.",
      "...{{square d6}} tries to give the queen an escape route and stabilise the center.",
      "Qx{{square g7}} is the payoff: you grab {{square g7}} with tempo and threaten mate ideas on {{square f7}} and {{square e5}}.",
      "...B{{square e6}} develops and blocks the queen's line, also hitting your {{queen g7 full}}.",
      "Nx{{square c7}}+ is a concrete fork. You check the king and also attack the {{rook a8 full}}.",
      "...K{{square d7}} is forced. Note how Black's king is stuck in the center because of the early queen adventure.",
      "Nx{{square e6}} wins another pawn or piece and keeps Black uncoordinated. You are converting initiative into material.",
      "...Ng{{square e7}} is a cleanup move: Black tries to bring pieces out and cover critical squares.",
      "N{{square h3}} develops with a clear goal: bring the knight to {{square f2}} or {{square g5}} and finish development while Black is still tangled."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-03-6364f5a8",
    name: "Dark-square mate vs ...g6",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "Nge7",
      "Nf6+",
      "Kf8",
      "Bh6#"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} goes straight for {{square g7}}. If Black weakens with ...{{square g6}}, you can often pivot to a safer square and keep pressure.",
      "...{{square g6}} commits a pawn move. It stops Qx{{square g7}} immediately but creates dark-square weaknesses and leaves the king less safe.",
      "Q{{square f3}} keeps the queen active on the diagonal to {{square f7}} and also supports potential sacrifices on {{square f7}}.",
      "...Q{{square f6}} is the 'keep it defended' approach. Black wants to trade queens or at least shut down the direct threats.",
      "N{{square d5}} again hits the queen and opens tactical shots. The {{knight d5 full}} also supports N{{square f6}} checks.",
      "...Qx{{square f3}} is a queen trade attempt. If Black can trade queens, the attack usually fizzles.",
      "Nx{{square f3}} accepts the trade but keeps development clean. Now Black's weakened dark squares matter more.",
      "...B{{square b6}} retreats to avoid tactics and keep the bishop on the diagonal.",
      "{{square d3}} is quiet but important: it opens your dark bishop later and gives your pieces stable squares.",
      "...Ng{{square e7}} develops and prepares ...{{square d5}} or ...O-O without losing material.",
      "N{{square f6}}+ is the key tactic: a forcing check that drags the king onto a dark square.",
      "...K{{square f8}} is forced.",
      "B{{square h6}}# is mate. The bishop uses the weakened diagonal created by ...{{square g6}}, and Black's pieces cannot cover the escape squares."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-04-e8d59293",
    name: "Qg4 line: meet ...Nd4 counterplay",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Nd4",
      "Ne2",
      "Nxe2",
      "Bxe2"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} pressures {{square g7}} and {{square f7}} and forces Black to play accurately.",
      "...Q{{square f6}} defends {{square f7}} but places the queen on a square that can be hit by N{{square d5}}.",
      "N{{square d5}} with tempo. The goal is to force the queen to a bad square or tempt Black into ...Qx{{square f2}}+ again.",
      "...Qx{{square f2}}+ is the greedy grab. If Black does not find a clean exit, the queen gets stuck.",
      "K{{square d1}} sidesteps checks and sets up Qx{{square g7}} to win pawns with tempo.",
      "...{{square d6}} is meant to open ...B{{square e6}} and give the queen breathing room.",
      "Qx{{square g7}} threatens Qx{{square f7}} mate ideas and forces Black to spend a move on development with tempo.",
      "...N{{square d4}} is counterplay: Black attacks {{square c2}} and also hits your queen's escape squares.",
      "N{{square e2}} is a practical block and development. You challenge the {{square d4}} knight and keep your king defended.",
      "...Nx{{square e2}} trades off your defender and tries to reduce your attacking pieces.",
      "Bx{{square e2}} recaptures and keeps the bishop pair. You have won {{square g7}} and forced concessions without losing structure."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-05-a7574f21",
    name: "Quiet Vienna: Na4 and g-file tactics",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Nxf3+",
      "gxf3",
      "Bh3",
      "Rg1",
      "Nh5",
      "Rg5",
      "Nxf4",
      "Rxe5+"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} hits {{square e4}} and develops. Compared to ...B{{square c5}} lines, Black prioritizes quick piece pressure.",
      "{{square d3}} is the quiet Vienna. You keep the center flexible and prepare to build an attack without overextending.",
      "...B{{square c5}} develops and points at {{square f2}}, normal Italian-style placement.",
      "{{square f4}} is the thematic pawn thrust. Even in the quiet Vienna, it challenges {{square e5}} and opens lines for your rook and bishop.",
      "...{{square d6}} supports {{square e5}} and takes away the {{square e5}} break tactics.",
      "N{{square f3}} develops and puts another attacker on {{square e5}} while preparing to castle.",
      "...B{{square g4}} pins the knight and tries to slow your kingside development. This pin is often annoying if you play carelessly.",
      "N{{square a4}} is a concrete plan: hit the {{square c5}} bishop and aim to win the bishop pair or force a retreat.",
      "...N{{square d4}} counters in the center. Black uses the freed {{square d4}} square to hit {{square c2}} and {{square f3}}.",
      "Nx{{square c5}} trades off the active bishop. This reduces Black's pressure on {{square f2}} and clears the {{square a4}} knight.",
      "...dx{{square c5}} opens the d-file and keeps a pawn in the center. Black accepts an isolated c-pawn in exchange for lines.",
      "{{square c3}} kicks the {{square d4}} knight and builds a pawn chain that can support {{square d4}} later.",
      "...Nx{{square f3}}+ is structural damage. Black gives up the central knight to smash your kingside pawns.",
      "gx{{square f3}} accepts the structure. The tradeoff is the g-file opens for your rook and you get the bishop pair.",
      "...B{{square h3}} targets the {{rook g1 full}} ideas and tries to exploit your weakened king.",
      "R{{square g1}} is forced defense and also a useful rook activation on the open file you just created.",
      "...N{{square h5}} reroutes toward {{square f4}} or {{square g7}} and keeps pressure on your weakened squares.",
      "R{{square g5}} is an active defense: you challenge the knight and also create tactics on {{square e5}} and {{square g7}}.",
      "...Nx{{square f4}} grabs a pawn and hits {{square e2}} and {{square g2}} squares. Black is trying to cash in before you stabilise.",
      "Rx{{square e5}}+ is a forcing move. The check lets you regain material and drag Black into calculations instead of letting them consolidate.",
      "Play Rx{{square e5}}+ with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-06-f3c53cdd",
    name: "Queen chase: block ...Qd4 and stabilize",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "Kf8",
      "Nh3",
      "Qd4",
      "d3",
      "d6",
      "Qg3",
      "Bxh3",
      "Rf1",
      "Be6",
      "c3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} attacks {{square g7}} and {{square f7}}. You're forcing a defensive move instead of letting Black develop freely.",
      "...Q{{square f6}} defends and also eyes {{square b2}} in some lines. The downside is it blocks the {{square g7}} knight and can be hit by N{{square d5}}.",
      "N{{square d5}} gains tempo on the queen and activates a piece into the center.",
      "...Qx{{square f2}}+ grabs with check. Again, this is where Black can get punished if the queen overextends.",
      "K{{square d1}} is the clean response. You keep your king safe without wasting time on queen blocks.",
      "...K{{square f8}} steps out of immediate danger and tries to keep the queen alive by avoiding discovered tactics.",
      "N{{square h3}} develops with a purpose: defend {{square f2}} squares and prepare N{{square f2}} or {{square g5}} to attack the queen.",
      "...Q{{square d4}} gives the queen a retreat square and hits your center. It's also a way to keep checking possibilities alive.",
      "{{square d3}} blocks the queen's line and solidifies {{square c2}} and {{square e4}}. You are cutting off Black's counterplay.",
      "...{{square d6}} reinforces {{square e5}} and opens the dark bishop, trying to finally develop.",
      "Q{{square g3}} keeps queens on and keeps pressure on {{square f2}} squares while staying safe from minor piece attacks.",
      "...Bx{{square h3}} grabs the knight. Black is trying to remove your defenders since their queen is still exposed.",
      "R{{square f1}} is the point: you hit {{square f7}}, line up the rook, and also trap the queen if it ever steps wrong.",
      "...B{{square e6}} develops and covers {{square f7}} while giving the king more breathing room.",
      "{{square c3}} is a simple stabiliser that also takes away {{square d4}} as a queen outpost and prepares to chase the queen again."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-07-41660e74",
    name: "Simplify: trade queens and win queenside structure",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "d6",
      "Be3",
      "Be6",
      "Bxb6",
      "Bxd5",
      "exd5",
      "axb6",
      "dxc6"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} puts immediate pressure on {{square g7}}. This is only good if you keep tempo and don't let Black hit your queen for free.",
      "...{{square g6}} creates dark-square weaknesses but removes Qx{{square g7}} tactics.",
      "Q{{square f3}} keeps pressure on {{square f7}} and also supports {{square d3}} and Ng{{square e2}} development.",
      "...Q{{square f6}} is the solid queen defense. Black wants to meet threats and maybe trade queens.",
      "N{{square d5}} is still strong: you improve the knight and force Black to react.",
      "...Qx{{square f3}} trades queens to defuse the attack.",
      "Nx{{square f3}} keeps development and keeps the bishop pair.",
      "...B{{square b6}} preserves the bishop and keeps pressure on the diagonal.",
      "{{square d3}} opens your dark bishop and secures the {{square c4}} bishop.",
      "...{{square d6}} reinforces {{square e5}} and makes ...B{{square e6}} easy.",
      "B{{square e3}} develops and challenges the {{square c5}} bishop and {{square d4}} squares.",
      "...B{{square e6}} meets that challenge and aims to trade off your active bishop.",
      "Bx{{square b6}} is a practical decision: remove the defender and ruin Black's queenside structure.",
      "...Bx{{square d5}} trades back and tries to repair the structure.",
      "ex{{square d5}} recaptures and opens the e-file. You also gain a strong {{pawn d5 full}} that can cramp Black.",
      "...ax{{square b6}} gives Black doubled b-pawns and open a-file issues.",
      "dx{{square c6}} wins the {{square c6}} knight or pawn depending on the exact position. The idea is you cash in the pressure created by the earlier exchanges."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-08-965ca595",
    name: "Forks with Nxc7 and Nxe6+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "Qf6",
      "Nd5",
      "Qxf2+",
      "Kd1",
      "d6",
      "Qxg7",
      "Be6",
      "Nxc7+",
      "Kd8",
      "Nxe6+",
      "fxe6",
      "Nf3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} goes for {{square g7}} and forces Black to defend accurately.",
      "...Q{{square f6}} defends and tempts tactics after N{{square d5}}.",
      "N{{square d5}} attacks the queen and also threatens fork ideas on {{square c7}}.",
      "...Qx{{square f2}}+ is the pawn grab with check.",
      "K{{square d1}} keeps it simple: avoid queen blocks that lose time.",
      "...{{square d6}} prepares ...B{{square e6}} to hit your queen and give the king a path to safety.",
      "Qx{{square g7}} grabs with tempo and keeps threats alive on {{square f7}}.",
      "...B{{square e6}} hits the queen and develops, trying to finally finish development.",
      "Nx{{square c7}}+ is the fork shot. You're using tempo while Black's king is still uncastled.",
      "...K{{square d8}} is the safe square. Notice Black still cannot castle because of the center and queen activity.",
      "Nx{{square e6}}+ is another forcing check. You keep the initiative while removing defenders.",
      "...fx{{square e6}} damages Black's structure. Their king gets stuck on the dark squares with weakened pawns.",
      "N{{square f3}} develops and prepares to castle or bring pieces into the attack while Black is still exposed."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-09-796dff6a",
    name: "Solid defense ...Nf6 and tactical cleanup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Nf6",
      "Nge2",
      "O-O",
      "d3",
      "d6",
      "Bg5",
      "Kg7",
      "Nd5",
      "Bg4",
      "Bxf6+",
      "Kg8",
      "Qxg4"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} targets {{square g7}}. Against ...{{square g6}} lines, you often switch to a safer square instead of forcing Qx{{square g7}} immediately.",
      "...{{square g6}} stops Qx{{square g7}} and prepares ...B{{square g7}}, but it weakens dark squares.",
      "Q{{square f3}} keeps pressure on {{square f7}} and supports quick development.",
      "...N{{square f6}} is the cleanest defense: develop and hit {{square e4}}, while also preparing to castle quickly.",
      "Ng{{square e2}} develops without blocking the f-pawn. It also supports {{square d4}} and {{square f4}} pushes later.",
      "...O-O is what Black wants: king safety before the tactics start.",
      "{{square d3}} keeps the center stable and opens your dark bishop.",
      "...{{square d6}} supports {{square e5}} and takes away some N{{square d5}} tactics.",
      "B{{square g5}} pins the {{square f6}} knight and increases pressure on {{square f6}} and {{square e7}} squares.",
      "...K{{square g7}} sidesteps potential checks and unpins ideas, also preparing ...{{square h6}}.",
      "N{{square d5}} centralises and hits {{square e7}} and {{square c7}}. The knight also supports captures on {{square f6}}.",
      "...B{{square g4}} is counterplay: Black tries to trade your queen or pin your pieces.",
      "Bx{{square f6}}+ is a concrete decision. You remove a key defender and force king movement or recapture decisions.",
      "...K{{square g8}} is forced to avoid immediate tactics.",
      "Qx{{square g4}} wins the bishop or simplifies. You take the active piece that was creating problems."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-10-79f48a6b",
    name: "Win the rook with Nxa8",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Qf6",
      "Nd5",
      "Qxf3",
      "Nxf3",
      "Bb6",
      "d3",
      "d6",
      "Be3",
      "Bxe3",
      "Nxc7+",
      "Kd7",
      "Nxa8",
      "Bc5",
      "c3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} attacks {{square g7}} and forces Black to respond.",
      "...{{square g6}} is the pawn shield. It creates weaknesses, but it can be playable if Black gets ...B{{square g7}} and ...O-O fast.",
      "Q{{square f3}} keeps your queen active without allowing tempo hits.",
      "...Q{{square f6}} defends {{square f7}} and keeps an eye on the center.",
      "N{{square d5}} hits the queen and also threatens Nx{{square c7}} forks.",
      "...Qx{{square f3}} goes for a queen trade to kill the attack.",
      "Nx{{square f3}} keeps development clean.",
      "...B{{square b6}} preserves the bishop and keeps control of the diagonal.",
      "{{square d3}} stabilises and prepares B{{square e3}}.",
      "...{{square d6}} supports the center and opens the dark bishop.",
      "B{{square e3}} develops and asks the {{bishop b6 full}} a question.",
      "...Bx{{square e3}} trades your active bishop and tries to reduce your attacking resources.",
      "Nx{{square c7}}+ is the fork. Even without queens, the tactical shot still works because the king and rook alignment is bad.",
      "...K{{square d7}} is forced.",
      "Nx{{square a8}} wins the rook. The cost is that your knight is stuck in the corner for a while.",
      "...B{{square c5}} develops and tries to trap the {{knight a8 full}}.",
      "{{square c3}} is the escape plan: you control {{square b4}} and prepare {{square b4}} or {{square d4}} to give the knight a route back."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-11-0c9a409b",
    name: "Quiet Vienna: g-file pressure after ...Nxf3+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Nxf3+",
      "gxf3",
      "Bh3",
      "Rg1",
      "g6",
      "fxe5",
      "Nh5",
      "Bg5"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} pressures {{square e4}} and accelerates development.",
      "{{square d3}} keeps the structure flexible. You're choosing a slower build instead of immediate gambit tactics.",
      "...B{{square c5}} develops and aims at {{square f2}}.",
      "{{square f4}} challenges the center and asks Black if they can hold {{square e5}}.",
      "...{{square d6}} supports {{square e5}} and prepares ...B{{square e6}} or ...O-O.",
      "N{{square f3}} develops and puts more pressure on {{square e5}}.",
      "...B{{square g4}} pins and tries to provoke weaknesses.",
      "N{{square a4}} is the standard Vienna plan: hit the bishop and claim the bishop pair.",
      "...N{{square d4}} hits {{square c2}} and {{square f3}}, using the center as counterplay.",
      "Nx{{square c5}} trades off the bishop. This reduces Black's immediate activity.",
      "...dx{{square c5}} keeps a pawn in the center and opens lines.",
      "{{square c3}} kicks the {{square d4}} knight and prepares {{square d4}} later.",
      "...Nx{{square f3}}+ forces a structural decision.",
      "gx{{square f3}} opens the g-file. You accept doubled pawns in exchange for active rooks and bishops.",
      "...B{{square h3}} tries to exploit the open g-file and target your rook squares.",
      "R{{square g1}} is both defense and activation: you put a rook on the file you opened.",
      "...{{square g6}} is a stabiliser: it gives the king luft and prepares ...B{{square g7}}.",
      "fx{{square e5}} is a practical capture to remove central tension and open lines.",
      "...N{{square h5}} reroutes to {{square f4}} and also eyes {{square g7}} squares.",
      "B{{square g5}} pins and challenges. You are aiming to punish Black's slow kingside setup.",
      "Play B{{square g5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-12-61478354",
    name: "Kingside clamp with f5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "O-O",
      "f5",
      "a6",
      "Bg5",
      "h6",
      "Bh4",
      "Nd4",
      "Nxd4",
      "Bxd4",
      "Nd5"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} is natural and challenges {{square e4}}.",
      "{{square d3}} keeps your center intact and prepares N{{square f3}} and {{square f4}}.",
      "...B{{square c5}} develops quickly.",
      "{{square f4}} is the critical pawn break, challenging {{square e5}}.",
      "...{{square d6}} supports {{square e5}} and clamps down on {{square e5}} pushes.",
      "N{{square f3}} develops and prepares to castle.",
      "...O-O is good defense: king safety before tactics.",
      "{{square f5}} gains space and clamps down on {{square e6}} and {{square g6}}. It also signals a kingside attack.",
      "...{{square a6}} prepares ...{{square b5}} and keeps the bishop from being hit by N{{square a4}} ideas.",
      "B{{square g5}} pins the {{square f6}} knight, making it harder for Black to defend the kingside.",
      "...{{square h6}} asks the bishop to decide and gains luft.",
      "B{{square h4}} keeps the pin and preserves the bishop.",
      "...N{{square d4}} is counterplay in the center. Black tries to hit {{square c2}} and {{square f3}} and distract you from the kingside.",
      "Nx{{square d4}} is the right reaction: remove the central outpost before it becomes a fork factory.",
      "...Bx{{square d4}} recaptures and keeps the bishop active.",
      "N{{square d5}} is the follow-up: you plant a knight in the center and threaten {{square c7}} and {{square e7}}, creating tactical pressure.",
      "Play N{{square d5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-13-e94d3abc",
    name: "Queenside counterplay ...b5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "O-O",
      "f5",
      "a6",
      "Bg5",
      "h6",
      "Bh4",
      "b5",
      "Bb3",
      "Nd4",
      "Nxd4",
      "Bxd4",
      "Nd5"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} challenges {{square e4}}.",
      "{{square d3}} supports {{square e4}} and keeps your pawn chain flexible.",
      "...B{{square c5}} develops and pressures {{square f2}}.",
      "{{square f4}} is your central challenge to {{square e5}}.",
      "...{{square d6}} is solid support.",
      "N{{square f3}} continues development.",
      "...O-O prioritizes king safety.",
      "{{square f5}} grabs space and starts the kingside clamp.",
      "...{{square a6}} prepares ...{{square b5}} expansion and stops N{{square a4}} from being too annoying.",
      "B{{square g5}} pins the knight and increases attacking potential.",
      "...{{square h6}} forces a decision.",
      "B{{square h4}} keeps the pin and maintains pressure.",
      "...{{square b5}} is queenside counterplay. Black is trying to expand while your pawns are advanced.",
      "B{{square b3}} preserves the bishop and keeps the diagonal toward {{square f7}}.",
      "...N{{square d4}} is the central counterstrike.",
      "Nx{{square d4}} eliminates the outpost before it forks or hits {{square f3}}.",
      "...Bx{{square d4}} keeps Black's bishop active.",
      "N{{square d5}} plants a knight and threatens {{square c7}} and {{square e7}} again, often forcing concessions.",
      "Play N{{square d5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-14-47395b62",
    name: "Pin-break line: Bb5 after structure damage",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Nd4",
      "Nxc5",
      "dxc5",
      "c3",
      "Bxf3",
      "gxf3",
      "Nc6",
      "Bb5"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} develops and hits {{square e4}}.",
      "{{square d3}} is the quiet setup, keeping options.",
      "...B{{square c5}} develops.",
      "{{square f4}} challenges {{square e5}}.",
      "...{{square d6}} supports and restrains.",
      "N{{square f3}} develops.",
      "...B{{square g4}} pins and aims to slow your kingside.",
      "N{{square a4}} hits the bishop and forces it to decide.",
      "...N{{square d4}} is counterplay and tries to punish your knight leaving {{square f3}} squares.",
      "Nx{{square c5}} trades off the bishop to reduce pressure.",
      "...dx{{square c5}} opens lines and keeps a pawn in the center.",
      "{{square c3}} kicks the knight and builds a strong pawn chain.",
      "...Bx{{square f3}} removes your defender and doubles your pawns again, aiming to expose your king.",
      "gx{{square f3}} accepts it and opens the g-file for rook activity.",
      "...N{{square c6}} retreats and re-centers, also attacking {{square d4}} and {{square b4}} squares.",
      "B{{square b5}} is a check and development idea: you pin the knight and often provoke ...B{{square d7}} or ...{{square d7}} concessions.",
      "Play B{{square b5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-15-3a650599",
    name: "Simple development vs ...Bb4",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bb4",
      "Ne2",
      "O-O",
      "O-O"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} develops and challenges {{square e4}}.",
      "{{square d3}} keeps everything solid. You're aiming for a simple plan: develop, castle, then choose {{square f4}} or N{{square f3}} setups.",
      "...B{{square b4}} pins the knight and tries to provoke weaknesses or force you into awkward development.",
      "N{{square e2}} is the antidote: break the pin without compromising your structure, and keep the f-pawn free for a later {{square f4}} break.",
      "...O-O finishes development for Black.",
      "O-O completes your own development. This line is about reaching a playable middlegame without tactics.",
      "Play O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-16-15866b05",
    name: "Bishop pair grab with Na4 and Nxb6",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "d6",
      "Nf3",
      "Bg4",
      "Na4",
      "Bb6",
      "Nxb6",
      "axb6",
      "c3",
      "O-O",
      "O-O"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} challenges {{square e4}}.",
      "{{square d3}} is the quiet Vienna. You keep your center and avoid early tactics.",
      "...B{{square c5}} develops and points at {{square f2}}.",
      "{{square f4}} is the thematic break to contest {{square e5}}.",
      "...{{square d6}} supports {{square e5}}.",
      "N{{square f3}} develops and prepares to castle.",
      "...B{{square g4}} pins the knight to slow your plan.",
      "N{{square a4}} immediately challenges the {{square c5}} bishop, a key idea in many Vienna setups.",
      "...B{{square b6}} retreats to keep the bishop and avoid exchanging.",
      "Nx{{square b6}} is a choice: trade the bishop and damage Black's queenside structure.",
      "...ax{{square b6}} recaptures, leaving Black with doubled b-pawns and open a-file issues.",
      "{{square c3}} is structure: it prepares {{square d4}} and keeps central squares controlled.",
      "...O-O finishes development.",
      "O-O completes yours. Now you can push {{square d4}} or {{square f5}} depending on Black's setup.",
      "Play O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-17-7c28abfb",
    name: "Meet ...d5 strike and keep development",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bb4",
      "Ne2",
      "d5",
      "exd5",
      "Nxd5",
      "O-O",
      "Nxc3",
      "bxc3",
      "Bd6",
      "Ng3"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} develops and attacks {{square e4}}.",
      "{{square d3}} keeps it solid and supports your center.",
      "...B{{square b4}} pins the knight and pressures {{square c3}}.",
      "N{{square e2}} breaks the pin, keeps the bishop pair, and leaves the f-pawn free so {{square f4}} is still a real plan later.",
      "...{{square d5}} is the direct strike. Black tries to punish your slower {{square d3}} setup by taking space immediately.",
      "ex{{square d5}} accepts the challenge and opens lines. If you ignore ...{{square d5}} you can get cramped.",
      "...Nx{{square d5}} recaptures with a piece, centralising the knight.",
      "O-O gets the king safe before the center opens further.",
      "...Nx{{square c3}} grabs on {{square c3}} and tries to damage your structure.",
      "bx{{square c3}} accepts doubled pawns but opens the b-file and keeps bishops.",
      "...B{{square d6}} develops and targets {{square h2}} in some lines.",
      "N{{square g3}} develops with purpose: protect {{square e4}}, eye {{square f5}} and {{square h5}}, and prepare {{square f4}} ideas later.",
      "Play N{{square g3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-18-833fa36d",
    name: "Central outpost: eliminate ...Nd4",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Bc5",
      "Qg4",
      "g6",
      "Qf3",
      "Nf6",
      "Nge2",
      "O-O",
      "d3",
      "Nd4",
      "Nxd4",
      "exd4",
      "Nd5",
      "Nxd5",
      "Bxd5",
      "c6",
      "Bb3"
    ],
    explanations: [
      "Take space in the center so your pieces have room to develop and attack.",
      "Black mirrors with a central pawn and keeps development flexible.",
      "Develop while defending {{square e4}}. In the Vienna, N{{square c3}} also keeps options like {{square f4}} or Q{{square g4}} open.",
      "Black develops and supports the {{square e5}} pawn, preparing ...N{{square f6}} or ...B{{square c5}}.",
      "Develop with tempo: B{{square c4}} immediately eyes {{square f7}}, the weakest point in Black's camp early.",
      "Black matches with ...B{{square c5}}, aiming at {{square f2}} and racing development.",
      "Q{{square g4}} pressures {{square g7}} and tries to slow Black's king safety.",
      "...{{square g6}} is the pawn shield, but it weakens dark squares around the king.",
      "Q{{square f3}} keeps pressure on {{square f7}} and supports quick development.",
      "...N{{square f6}} is accurate: develop and hit {{square e4}}.",
      "Ng{{square e2}} develops and keeps the f-pawn free.",
      "...O-O is the defensive goal: get the king safe.",
      "{{square d3}} supports the center and opens your dark bishop.",
      "...N{{square d4}} is a central jump that hits {{square c2}} and creates tactics.",
      "Nx{{square d4}} removes the outpost immediately. Letting that knight sit on {{square d4}} is asking for forks.",
      "...ex{{square d4}} opens the e-file and creates a pawn wedge on {{square d4}}.",
      "N{{square d5}} plants a knight and targets {{square c7}} and {{square e7}} again.",
      "...Nx{{square d5}} trades it off to reduce your pressure.",
      "Bx{{square d5}} keeps a bishop on the strong diagonal and restores material balance.",
      "...{{square c6}} kicks the bishop and gains space.",
      "B{{square b3}} retreats while keeping pressure on {{square f7}} and the diagonal."
    ]
  },

  {
    category: "Vienna Game",
    id: "vienna-game-19-3fb807cb",
    name: "Opposite-side castle attack plan",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "f4",
      "exf4",
      "Bxf4",
      "O-O",
      "Qd2",
      "d6",
      "O-O-O"
    ],
    explanations: [
      "Play {{square e4}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play {{square e5}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c3}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "Play N{{square c6}} with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea.",
      "...N{{square f6}} challenges {{square e4}} and speeds up development.",
      "{{square d3}} keeps the center stable and prepares N{{square f3}}.",
      "...B{{square c5}} develops and targets {{square f2}}.",
      "{{square f4}} is the thematic pawn thrust, challenging {{square e5}} immediately.",
      "...ex{{square f4}} accepts the pawn and opens the e-file and f-file dynamics.",
      "Bx{{square f4}} recaptures quickly. The key is not to let Black keep the extra pawn while you fall behind in development.",
      "...O-O secures the king.",
      "Q{{square d2}} is a clear plan: connect rooks, prepare long castle, and line up pieces for a kingside pawn storm.",
      "...{{square d6}} supports {{square e5}} and opens the dark bishop.",
      "O-O-O is the commitment. Opposite-side castling means the game becomes a race: you attack the king while Black counterattacks your king.",
      "Play O-O-O with a concrete purpose: create a threat, improve a piece, or stop your opponent's idea."
    ]
  }
,
  {
    category: "Vienna Game",
    id: "vienna-game-20-e3f7c9b1",
    name: "Vienna System: ...d6 lets Na4 hit the bishop pair",
    description: "Transcript-backed g3 and Bg2 setup where ...d6 makes the c5 bishop easier to chase.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "g3",
      "Bc5",
      "Bg2",
      "Nc6",
      "Nge2",
      "O-O",
      "O-O",
      "d6",
      "Na4"
    ],
    explanations: [
      "White starts the Vienna with N{{square c3}} in reserve, keeping both {{square g3}} systems and f-pawn play available.",
      "Black mirrors the center and asks White what kind of Vienna setup is coming.",
      "N{{square c3}} is the Vienna move. It supports {{square e4}} and keeps the f-pawn free for later kingside play.",
      "...N{{square f6}} develops with tempo against {{square e4}} before Black commits the bishop.",
      "{{square g3}} announces the quieter Vienna System. White wants B{{square g2}}, Ng{{square e2}}, castling, and then a later {{square f4}} break.",
      "...B{{square c5}} is the normal Italian-style square, but it also means Black has to watch the bishop's retreat path.",
      "B{{square g2}} puts the bishop on the long diagonal and is one reason an early ...{{square d5}} break is no longer easy.",
      "...N{{square c6}} develops and keeps {{square e5}} protected.",
      "Ng{{square e2}} is the key setup detail from the transcript. White keeps the f-pawn free instead of blocking it with N{{square f3}}.",
      "...O-O gets the king safe, but Black still has to solve the bishop placement carefully.",
      "White castles and keeps the whole plan intact: slow setup first, then kingside expansion.",
      "...{{square d6}} looks natural, but it shuts the bishop's easiest retreat and gives White a concrete target.",
      "N{{square a4}} is the point. White hits the {{square c5}} bishop and makes Black give up the bishop pair or lose time retreating it awkwardly."
    ]
  },
  {
    category: "Vienna Game",
    id: "vienna-game-21-b48d2e6f",
    name: "Vienna System: h3, Kh2, and fast f4",
    description: "Transcript-backed move-order trick where White prepares f4 before Black can break with ...d5.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "g3",
      "Bc5",
      "Bg2",
      "Nc6",
      "Nge2",
      "O-O",
      "O-O",
      "a6",
      "h3",
      "d6",
      "Kh2",
      "Be6",
      "f4"
    ],
    explanations: [
      "White claims central space and leaves room for a flexible Vienna setup.",
      "Black mirrors the center and keeps a standard {{square e5}} structure.",
      "N{{square c3}} defines the opening and keeps White's options broader than an immediate N{{square f3}} setup.",
      "...N{{square f6}} pressures {{square e4}} and develops naturally.",
      "{{square g3}} starts the Vienna System. White is aiming for a controlled build before the kingside pawn storm.",
      "...B{{square c5}} develops toward {{square f2}} and follows the familiar Italian pattern.",
      "B{{square g2}} places the bishop on the long diagonal where it will support queenside pressure if the center opens.",
      "...N{{square c6}} supports {{square e5}} and finishes Black's basic development.",
      "Ng{{square e2}} is important. White refuses to block the f-pawn because {{square f4}} is the main attacking break later.",
      "...O-O secures the king before the middlegame plans start.",
      "White also castles. The setup is complete enough that White can start thinking about pawn play.",
      "...{{square a6}} is Black's usual fix. The idea is to prepare ...B{{square a7}} and only then play ...{{square d6}}.",
      "{{square h3}} is the move-order trick from the transcript. White wants K{{square h2}} and a very fast {{square f4}} before Black gets in ...{{square d5}}.",
      "...{{square d6}} is the normal follow-up, but it also means Black still has not challenged White in the center.",
      "K{{square h2}} steps off the {{square g1}}-{{square a7}} diagonal and clears the way for the f-pawn to advance safely.",
      "...B{{square e6}} is a normal developing move, but Black is one tempo short of the central counterbreak.",
      "{{square f4}} is the whole point. White gets the kingside attack started before Black manages to hit back with ...{{square d5}}."
    ]
  },
  {
    category: "Vienna Game",
    id: "vienna-game-22-7af1d0c4",
    name: "Vienna System trap: ...exf4 runs into d4",
    description: "Transcript-backed tactical line where grabbing on f4 lets White hit back in the center.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "g3",
      "Bc5",
      "Bg2",
      "Nc6",
      "Nge2",
      "O-O",
      "O-O",
      "a6",
      "h3",
      "d6",
      "Kh2",
      "Be6",
      "f4",
      "exf4",
      "d4",
      "fxg3+",
      "Kg3",
      "Nh5+",
      "Kh2"
    ],
    explanations: [
      "White starts from the same Vienna System shell: safe king, {{bishop g2 full}}, and the f-pawn ready to move.",
      "Black mirrors the center and keeps the usual {{square e5}} structure.",
      "N{{square c3}} supports {{square e4}} and keeps the opening in Vienna territory.",
      "...N{{square f6}} develops with pressure on {{square e4}}.",
      "{{square g3}} signals that White is building rather than forcing an immediate tactical fight.",
      "...B{{square c5}} follows the standard development path and keeps pressure on {{square f2}}.",
      "B{{square g2}} puts White's bishop on the long diagonal, where it can become powerful if the center opens.",
      "...N{{square c6}} adds support to {{square e5}} and keeps Black flexible.",
      "Ng{{square e2}} keeps the f-pawn free, which is the key move-order detail in this whole system.",
      "...O-O gets Black's king out of the center before the pawn storm starts.",
      "White castles and is ready to play on the kingside.",
      "...{{square a6}} prepares the bishop retreat to {{square a7}}, which is Black's usual practical fix.",
      "{{square h3}} is still required. White needs K{{square h2}} in before opening the kingside with {{square f4}}.",
      "...{{square d6}} is solid, but it also means Black is still reacting instead of striking the center.",
      "K{{square h2}} makes the pawn break possible without allowing cheap checks on the long diagonal.",
      "...B{{square e6}} develops, but Black is still a move short of the counterbreak the transcript warns about.",
      "{{square f4}} starts the attack on schedule. White has won the move-order race and now asks Black to decide whether to grab or sit tight.",
      "...ex{{square f4}} is the greedy test. Black wins a pawn for the moment but gives White tactical play in return.",
      "{{square d4}} is the transcript's key surprise. White opens the center immediately and attacks the bishop while Black's queenside pieces are still undeveloped.",
      "...fx{{square g3}}+ is Black's practical try: grab more material and throw in a check before White's center rolls forward.",
      "K{{square g3}} is the important recapture. White keeps the {{square e2}} knight at home so it can still support the {{square d4}} pawn.",
      "...N{{square h5}}+ looks scary, but Black does not actually have enough pieces nearby to keep the attack going.",
      "K{{square h2}} is the calm finish from the transcript. White's king steps back and Black still has to deal with the center and the {{square d5}} fork ideas."
    ]
  },
  {
    category: "Vienna Game",
    id: "vienna-game-23-c6a52f88",
    name: "Vienna System vs ...d5: bxc3 and Re1 pressure",
    description: "Transcript-backed early ...d5 line where White accepts doubled pawns for the b-file and pressure on e5.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "g3",
      "d5",
      "exd5",
      "Nxd5",
      "Bg2",
      "Nxc3",
      "bxc3",
      "Nc6",
      "Nf3",
      "Be7",
      "O-O",
      "O-O",
      "Re1",
      "Re8",
      "d4"
    ],
    explanations: [
      "White opens with the Vienna move and keeps the structure flexible.",
      "Black takes the center and keeps the game in open-{{square e4}} territory.",
      "N{{square c3}} defines the Vienna and leaves White ready for either a kingside setup or a central capture.",
      "...N{{square f6}} develops and adds pressure to {{square e4}} before Black strikes in the center.",
      "{{square g3}} is the transcript's system move. White wants B{{square g2}} and piece pressure instead of a direct pawn center right away.",
      "...{{square d5}} is the immediate counterbreak. This is the right timing if Black wants to challenge White before B{{square g2}} makes it harder.",
      "White should take. Letting Black keep the full center would concede exactly what the transcript warns about.",
      "...Nx{{square d5}} restores the pawn and places the knight actively in the middle.",
      "B{{square g2}} changes the character of the position. White's bishop now points toward the queenside rather than just the king.",
      "...Nx{{square c3}} is the theoretical choice from the transcript. Black gives up the active knight to damage White's pawns before White gets organized.",
      "bx{{square c3}} is the required recapture. White wants the extra central control and the half-open b-file, not a quiet queen recapture.",
      "...N{{square c6}} develops and keeps the {{square e5}} pawn defended for the moment.",
      "N{{square f3}} starts the pressure plan. White wants quick castling and then R{{square e1}} to ask how Black will really hold {{square e5}}.",
      "...B{{square e7}} is a solid developing move, but it does not solve the long-term {{square e5}} pressure by itself.",
      "White castles and keeps development simple.",
      "Black also castles, but White's pressure plan is now easier to execute than Black's counterplay.",
      "R{{square e1}} is the recurring theme from the transcript. White lines up on {{square e5}} and forces Black to think about that pawn every move.",
      "...R{{square e8}} is a common defensive reaction, but it ties Black to passive defense.",
      "{{square d4}} is the payoff. White finally seizes the center once the pieces are ready and Black's {{square e5}} pawn is pinned to the rook behind it."
    ]
  },
  {
    category: "Vienna Game",
    id: "vienna-game-24-f1248d73",
    name: "Vienna System vs ...d5: ...Nb6 is passive",
    description: "Transcript-backed sideline showing how White targets e5 when Black retreats instead of taking on c3.",
    moves: [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "g3",
      "d5",
      "exd5",
      "Nxd5",
      "Bg2",
      "Nb6",
      "Nf3",
      "Nc6",
      "O-O",
      "Be7",
      "Re1",
      "O-O"
    ],
    explanations: [
      "White starts with the Vienna move and keeps a flexible center.",
      "Black mirrors and keeps an open-game structure.",
      "N{{square c3}} defines the Vienna and prepares both {{square g3}} systems and direct central play.",
      "...N{{square f6}} develops with immediate pressure on {{square e4}}.",
      "{{square g3}} prepares the bishop fianchetto that the transcript builds the whole system around.",
      "...{{square d5}} is the right moment for Black to hit the center before White finishes the setup.",
      "White exchanges in the center so Black does not get a full pawn duo for free.",
      "...Nx{{square d5}} restores the pawn and keeps the knight active.",
      "B{{square g2}} is consistent. White wants queenside pressure and long-diagonal influence in these early-...{{square d5}} lines.",
      "...N{{square b6}} is one of the passive retreats the transcript criticizes. Black keeps the knight but gives White time.",
      "N{{square f3}} improves the attack on {{square e5}} and prepares to castle.",
      "...N{{square c6}} finally reinforces {{square e5}}, but Black is still slightly tied down.",
      "White castles and removes king safety from the list of problems.",
      "...B{{square e7}} is a normal developing move, though it still leaves the {{square e5}} question unresolved.",
      "R{{square e1}} is the simple plan the transcript repeats. White asks Black to defend {{square e5}} without making a concession elsewhere.",
      "...O-O finishes development, but White remains the easier side to play because the pressure against {{square e5}} is so straightforward."
    ]
  }

]);
