import { withOpeningFeedback } from "./feedback";

// src/openings/viennaGambitCounterLines.js

export const viennaGambitCounterLines = withOpeningFeedback([
  
  {
    category: "Vienna Gambit Counter",
    id: "vienna-counter-mainline",
    name: "Vienna Counter: The d5 Strike",
    description: "The coach's recommendation for Black: strike back in the center immediately and exploit White's kingside weaknesses.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5"],
    explanations: [
      "White starts with {{square e4}}.",
      "Let's learn the Vienna Gambit Counter! We respond symmetrically. {{square e5}}",
      "The Vienna Knight! White delays development to keep the f-pawn flexible.",
      "Black develops naturally, attacking e4.",
      "The Gambit! White offers a pawn to rip open the f-file.",
      "The Counter-Punch! We ignore the pawn and strike the center immediately with 3... d5. This is the only 'good' way to play against the Vienna Gambit!"
    ]
  },

  {
    category: "Vienna Gambit Counter",

    id: "vienna-counter-01-cb43922c",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Be7", "Qxe5", "Nf6", "Bxf4"],
    explanations: ["White starts with pawn to {{square e4}} and prepares quick kingside development.", "Let's learn the Vienna Gambit Counter! When White plays {{square e4}}, answer with pawn to {{square e5}} and meet the Vienna on your terms.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the {{square f6}} knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports {{square e5}} and prepares ...dx{{square e5}} or ...B{{square e7}} while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports {{square e4}} and eyes {{square e5}}. In Vienna lines, Q{{square e2}} often helps you regain the pawn while staying active.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "Take back in the center with tempo. You want material back, but still keep pieces active and threats alive.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-counter-02-a9fd29f2",
    name: "Trap: queen takes rook on h1",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "fxe5", "Nxc3", "bxc3", "Qh4+", "g3", "Qe4+", "Qe2", "Qxh1"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "Support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}} and preparing ...{{square d5}}.", "Vienna Gambit: White tries to seize initiative, but the moved f-pawn also weakens the {{square h4}}-{{square e1}} diagonal.", "This is the key counterpunch from the transcript: hit the center immediately before White gets a free attack.", "White chooses the ex{{square d5}} branch and opens the position instead of chasing the knight.", "Easy recapture. The knight is defended by the queen and lands on an active central square.", "White grabs another pawn for the moment, but now the kingside weaknesses matter.", "Black removes the knight first. This forces bx{{square c3}} and opens the diagonal for the queen check.", "White recaptures, but the structure damage is exactly what makes the trap work.", "Standard punishment. ...Q{{square h4}}+ uses the weakened diagonal created by {{square f4}}.", "This blocks the check, but it is exactly the move Black wants to see.", "Keep checking and step the queen into the middle. The {{rook h1 full}} is now a concrete target.", "White covers what it can, but the rook still cannot be saved.", "Black wins the {{rook h1 full}}. This is the core ex{{square d5}} trap from the transcript."]
  },

  {
    id: "vienna-counter-03-ee3fd007",
    name: "Main trap: ...Nd4 and rook fork",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qd3", "dxe4", "Qxe4", "Bf5", "Qxb7", "Rb8", "Qxa7", "Nxc2+", "Kd1", "Nxa1"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "Support {{square e4}} and keep the f-pawn free for {{square f4}}.", "Black develops while hitting {{square e4}} and preparing the central counterstrike.", "Vienna Gambit. White wants quick initiative before Black can settle.", "This is the key counter from the transcript: strike the center immediately instead of drifting into White's attack.", "White chases the knight and expects to gain time.", "Black ignores the threat and plants a centralized {{knight e4 full}}. That knight is the whole point of the counter.", "This is White's main move. The queen pressures {{square e4}} and hopes to force favorable trades.", "Quiet looking, but this sets the trap. Black acts like normal development is the plan.", "Natural and greedy. White expects ...dx{{square e4}} and then Qx{{square e4}} to recover the pawn cleanly.", "The nasty in-between move from the transcript. The knight hits {{square f3}} and {{square c2}}, and the fork on {{square c2}} is the real threat.", "White tries to hold the position together and stop the fork ideas.", "Now Black recaptures. White's queen is still exposed and {{square c2}} is still weak.", "White finally wins the pawn back and thinks the danger is over.", "This is the shot. The bishop skewers the queen and keeps {{square c2}} under Black's control.", "White stays greedy, but this only gives Black more time.", "Attack the queen first. The transcript makes this exact point before cashing in with the fork.", "White grabs one more pawn, but the king and rook are now hanging.", "Fork check. This is the payoff of the whole trap.", "The king has to move, but the rook still cannot be saved.", "Black wins the {{rook a1 full}} and the trap has fully landed."]
  },

  {
    id: "vienna-counter-04-41e75f7c",
    name: "Bb5 sidestep still fails",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qe2", "Qh4+", "g3", "Qe4", "Nf3", "Qxf3", "Qxf3", "Bxf3"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "Support {{square e4}} and keep the f-pawn free for {{square f4}}.", "Black develops while hitting {{square e4}} and preparing ...{{square d5}}.", "Vienna Gambit. White wants initiative and fast development.", "Black counterstrikes in the center immediately, which is the whole theme of the transcript.", "White chases the knight and hopes to build momentum.", "Black keeps the knight centralized and makes White solve concrete tactical problems.", "White adds pressure to {{square e4}} and hopes to force trades on favorable terms.", "This quiet move prepares the trap instead of rushing.", "This is White's practical sidestep from the transcript. The pin tries to stop ...N{{square d4}}.", "Black ignores the pressure and prepares the real point: ...B{{square d5}} with tempo.", "White grabs the knight anyway and thinks the pin solved everything.", "Black opens the diagonal and keeps White's queen exposed.", "White wins the pawn back, but the queen has walked onto the square Black wanted.", "This is why ...B{{square e6}} came first. The bishop hits the queen and points straight at {{square g2}}.", "The usual retreat. White tries to regroup and cover the king.", "Black switches straight into attack with check.", "This blocks the check, but it is the fatal weakening from the transcript.", "Black builds the queen-bishop battery on the weakened diagonal and keeps the pressure on {{square h1}} and {{square f3}}.", "White develops, but too late. The attack is already doing the work.", "Black removes a key defender and strips more cover from White's king.", "Forced recapture.", "Black wins more material and reaches a clearly winning position."]
  },

  {
    id: "vienna-counter-05-4f60a1b9",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "Bc4", "Nc6", "Qh5", "g6", "Qe2", "Nd4", "Qxe4", "Bf5", "Qxb7", "Rb8", "Qxa7", "Nxc2+"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Develop the bishop to {{square c4}} so it can influence the center and join the attack.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Develop the queen to {{square h5}} so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Queen supports {{square e4}} and eyes {{square e5}}. In Vienna lines, Q{{square e2}} often helps you regain the pawn while staying active.", "Black develops the knight to {{square d4}} to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to {{square f5}} to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the rook to {{square b8}} to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Fork check: Black looks to win material while forcing your king to move."]
  },

  {
    id: "vienna-counter-06-9759c095",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "Qe2", "Bf5", "g4", "Qh4+", "Kd1", "Bxg4", "Nf3", "Bxf3", "Qxf3", "exf3"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Queen supports {{square e4}} and eyes {{square e5}}. In Vienna lines, Q{{square e2}} often helps you regain the pawn while staying active.", "Black develops the bishop to {{square f5}} to contest the center and meet your threats.", "Make a pawn move that supports your center or opens lines for your pieces.", "Direct check: force weaknesses like {{square g3}} and try to slow your attack by making you defend.", "Step away from checks and keep your rooks connected later. You are trading safety for time.", "Black captures to simplify or to remove your attacking pieces.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-07-1fc8397e",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qd1", "dxe4", "c3", "Nc6", "Bb5", "Qd5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Q{{square f3}} pressures {{square f4}} and {{square f7}} ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the knight to {{square d4}} to contest the center and meet your threats.", "Develop the queen to {{square d1}} so it can influence the center and join the attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Make a pawn move that supports your center or opens lines for your pieces.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: B{{square b5}} adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the queen to {{square d5}} to contest the center and meet your threats."]
  },

  {
    id: "vienna-counter-08-123e2a7c",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nf3", "Bc5", "d4", "Bb4", "Bd2", "c5", "Nxe4", "dxe4", "Bxb4", "cxb4", "Ng1", "O-O"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to {{square c5}} to contest the center and meet your threats.", "You push {{square d4}} to challenge the center and open diagonals, but you must watch tactics on {{square e4}}.", "Black pins the knight to slow your development and increase pressure on {{square e4}} and {{square d4}}.", "Develop the bishop to {{square d2}} so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Develop the knight to {{square g1}} so it can influence the center and join the attack.", "Black castles to get out of the center and try to convert defense into counterplay."]
  },

  {
    id: "vienna-counter-09-866df47b",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qg4", "h5", "Qg3", "Qd7", "Nf3", "a6", "Bxc6", "Qxc6"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Q{{square f3}} pressures {{square f4}} and {{square f7}} ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: B{{square b5}} adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the bishop to {{square e6}} to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to {{square d5}} to contest the center and meet your threats.", "Develop the queen to {{square g4}} so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Develop the queen to {{square g3}} so it can influence the center and join the attack.", "Black develops the queen to {{square d7}} to contest the center and meet your threats.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black advances a pawn to challenge your center or create counterplay.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-10-ebf6ccfc",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "d4", "exd3", "Bxd3", "Qh4+", "g3", "Qe7", "Nf3", "Nc6"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "You push {{square d4}} to challenge the center and open diagonals, but you must watch tactics on {{square e4}}.", "Black captures to open files against your king and keep the initiative with tempo threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Direct check: force weaknesses like {{square g3}} and try to slow your attack by making you defend.", "Block the check, but note the cost: {{square g3}} weakens dark squares and can become a long-term target.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on {{square c7}}.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns."]
  },

  {
    id: "vienna-counter-11-a8f21662",
    name: "Qg4 line meets ...h5 and ...Qh4+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qg4", "h5", "Qe2", "Qh4+"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "Support {{square e4}} and keep the f-pawn free for {{square f4}}.", "Black develops while hitting {{square e4}} and preparing ...{{square d5}}.", "Vienna Gambit. White wants initiative and fast development.", "Black counterstrikes in the center immediately, which is the whole point of the setup.", "White chases the knight and hopes to gain time.", "Black plants the knight in the center and asks White to prove compensation.", "White pressures {{square e4}} and hopes to force a clean liquidation.", "Black develops quietly and keeps the tactical idea in reserve.", "White again uses B{{square b5}} to interfere with ...N{{square d4}}.", "Black still prepares ...B{{square d5}} and does not rush.", "White takes the knight anyway.", "Black opens lines and leaves White's queen exposed.", "White gets the pawn back, but the tactical pressure remains.", "The bishop lands with tempo, exactly as in the transcript line.", "Some players try to stay active with the queen instead of retreating passively.", "Black kicks the queen first. The transcript explicitly points out this move before the attack continues.", "White has to retreat after all.", "Black reaches the same attacking setup anyway, with check and pressure on the weakened dark squares."]
  },

  {
    id: "vienna-counter-12-5110a782",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qc3", "dxe4", "Ne2", "Nc6", "Ng3", "Qd5", "Bc4", "Qxe5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Q{{square f3}} pressures {{square f4}} and {{square f7}} ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the knight to {{square d4}} to contest the center and meet your threats.", "Develop the queen to {{square c3}} so it can influence the center and join the attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Re-route the knight to {{square g3}} or {{square f4}} squares and support central defense, often preparing to recapture cleanly.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Develop the knight to {{square g3}} so it can influence the center and join the attack.", "Black develops the queen to {{square d5}} to contest the center and meet your threats.", "Develop the bishop to {{square c4}} so it can influence the center and join the attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-13-773a7e2b",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "fxe5", "Nxc3", "bxc3", "Qh4+", "Ke2", "Bg4+", "Nf3", "Nc6", "d4", "O-O-O", "Qe1", "Qh5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "Support {{square e4}} and keep the f-pawn free for {{square f4}}.", "Black develops while hitting {{square e4}} and preparing ...{{square d5}}.", "Vienna Gambit: White goes for initiative, but the moved f-pawn also weakens the {{square h4}}-{{square e1}} diagonal.", "This is the counterpunch from the transcript. Black hits the center before White gets a free attack.", "White chooses the ex{{square d5}} branch and opens the center.", "Simple recapture. The queen defends the knight, so Black loses no time.", "White grabs the {{pawn e5 full}} and hopes the extra pawn will justify the opening.", "Black trades on {{square c3}} first so the b-pawn has to recapture and the queen check becomes stronger.", "White accepts the damaged structure, but the king is about to feel it.", "Black immediately checks on {{square h4}}, using the diagonal weakened by {{square f4}}.", "White refuses {{square g3}} and walks the king out. This avoids the rook loss for the moment, but leaves the king stranded.", "Keep gaining time. Black develops with check and refuses to let White stabilize.", "White tries to cover key squares and finish development.", "Black adds another piece and keeps the exposed king under pressure.", "White tries to justify the king walk by opening the center and claiming space.", "Black castles long and brings the rook toward the middle right away.", "White tries to untangle and cover dark squares.", "Black keeps the queen active and the king exposed. White never gets the easy attacking game the gambit was supposed to create."]
  },

  {
    id: "vienna-counter-14-92d886ae",
    name: "Check with Bb5+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nf3", "Bc5", "d4", "Bb4", "Bd2", "c5", "Bb5+", "Nc6", "O-O", "O-O"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes {{square e4}} and challenges your center. If you are careless, your queen can get hit with tempo.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to {{square c5}} to contest the center and meet your threats.", "You push {{square d4}} to challenge the center and open diagonals, but you must watch tactics on {{square e4}}.", "Black pins the knight to slow your development and increase pressure on {{square e4}} and {{square d4}}.", "Develop the bishop to {{square d2}} so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Play with check to gain tempo and force a defensive move, keeping your initiative alive.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Castle to turn your development lead into real threats without your king getting checked forever.", "Black castles to get out of the center and try to convert defense into counterplay."]
  },

  {
    id: "vienna-counter-15-ac4fe7a3",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "Nxd5", "Qxd5", "fxe5", "Nc6", "Nf3", "Bg4", "Be2", "Nxe5", "Nxe5", "Qxe5", "d4", "Qe7"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support {{square e4}} and keep the f-pawn free for {{square f4}} without blocking N{{square f3}}.", "Black develops while hitting {{square e4}}, forcing you to show how you will defend the center.", "You still play {{square f4}} to chase initiative, but note Black can answer with ...{{square d5}} to hit your center immediately.", "Key counter: ...{{square d5}} hits {{square e4}} and {{square f4}} at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black centralizes the queen after trades and tries to simplify while holding the extra pawn or initiative.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops and adds pressure on {{square e5}} and {{square d4}}, aiming to meet your center with pieces, not just pawns.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to {{square g4}} to contest the center and meet your threats.", "Develop the bishop to {{square e2}} so it can influence the center and join the attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on {{square c7}}."]
  }

]);
