// src/openings/viennaGambitLines.js

export const viennaGambitLines = [
  
  {
    category: "Vienna Gambit",

    id: "vienna-gambit-01-bd8b935b",
    name: "Nh5 blunder punished",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Nh5", "Qxh5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "Black tries to hang onto f4 and chase your queen later, but this often walks into tactics on h5.", "Punish the knight jump: win the piece and instantly remove Black's idea of holding the f4 pawn."]
  },

  {
    id: "vienna-gambit-02-6c270e9b",
    name: "Tactic: Nxc7+ fork",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Qe7", "Qe2", "Ng8", "Nf3", "d6", "Nd5", "Qe6", "Nxc7+"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on c7.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Jump into the outpost: Nd5 hits c7 and e7 and can create forks if Black's queen and king are uncoordinated.", "Black develops the queen to e6 to contest the center and meet your threats.", "Classic fork: hit the king and rook. This is why early queen moves by Black can be risky here."]
  },

  {
    id: "vienna-gambit-03-0b9ddfae",
    name: "...Nc6 development",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "Nc6", "fxe5", "Nxe5", "d4", "Ng6", "e5", "Ng8", "Nf3"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black develops the knight to g6 to contest the center and meet your threats.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways."]
  },

  {
    id: "vienna-gambit-04-db06b173",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "Nc6", "d4", "d6", "Bxf4", "dxe5", "Nxe5", "Nxe5", "Bxe5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-gambit-05-9569edf5",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Nc6", "Bxf4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-gambit-06-87b67a22",
    name: "Tactic: Nxc7+ fork",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Qe7", "Qe2", "Ng8", "Nf3", "Nc6", "d4", "d6", "Nd5", "Qd8", "Nxc7+", "Qxc7", "exd6+", "Be7", "dxc7"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on c7.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Jump into the outpost: Nd5 hits c7 and e7 and can create forks if Black's queen and king are uncoordinated.", "Black steps back to remove tactics and keep the position under control.", "Classic fork: hit the king and rook. This is why early queen moves by Black can be risky here.", "Black captures to simplify or to remove your attacking pieces.", "Play with check to gain tempo and force a defensive move, keeping your initiative alive.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-gambit-07-1b726472",
    name: "Check with Bb5+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "g5", "d4", "g4", "Bxf4", "gxf3", "Qxf3", "d6", "Bb5+", "c6", "O-O", "cxb5", "Bg5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black supports the extra pawn and gains space, but also weakens the king side squares.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black tries to kick your knight and keep lines closed, but it creates targets and can open the g-file.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Play with check to gain tempo and force a defensive move, keeping your initiative alive.", "Black advances a pawn to challenge your center or create counterplay.", "Castle to turn your development lead into real threats without your king getting checked forever.", "Black captures to simplify or to remove your attacking pieces.", "Develop the bishop to g5 so it can influence the center and join the attack."]
  },

  {
    id: "vienna-gambit-08-d4b5e0e1",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Bb4", "Qxe5+", "Qe7", "Bxf4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black pins the knight to slow your development and increase pressure on e4 and d4.", "Play with check to gain tempo and force a defensive move, keeping your initiative alive.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on c7.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-gambit-09-ad3aae2a",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Be7", "Qxe5", "Nc6", "Bb5", "Bd7", "Bxc6", "Bxc6", "d5", "Bd7", "Bxf4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "Take back in the center with tempo. You want material back, but still keep pieces active and threats alive.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending.", "Black breaks the pin and prepares to complete development without losing the knight.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Make a pawn move that supports your center or opens lines for your pieces.", "Black breaks the pin and prepares to complete development without losing the knight.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-gambit-10-07fba3d5",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d6", "Nf3", "exf4", "d4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Open the center while you are ahead in development. This is how gambits convert time into attack."]
  },

  {
    id: "vienna-gambit-11-3a106f98",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d6", "Nf3", "Nc6", "Bb5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending."]
  },

  {
    id: "vienna-gambit-12-c5066d53",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nxc3", "bxc3", "Be7", "d4", "O-O", "Bd3", "Be6", "Ne2"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black grabs your knight to damage your structure and reduce your piece pressure.", "Recapture and accept the structure damage. Your compensation is open lines and faster development.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "You push d4 to challenge the center and open diagonals, but you must watch tactics on e4.", "Black castles to get out of the center and try to convert defense into counterplay.", "Point the bishop at the king side and support quick castling, while keeping an eye on the center.", "Black develops the bishop to e6 to contest the center and meet your threats.", "Re-route the knight to g3 or f4 squares and support central defense, often preparing to recapture cleanly."]
  },

  {
    id: "vienna-gambit-13-cb43922c",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Be7", "Qxe5", "Nf6", "Bxf4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", "support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "Take back in the center with tempo. You want material back, but still keep pieces active and threats alive.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  }

];
