import { withOpeningFeedback } from "./feedback";

// src/openings/viennaGambitCounterLines.js

export const viennaGambitCounterLines = withOpeningFeedback([
  
  {
    category: "Vienna Gambit Counter",

    id: "vienna-counter-01-cb43922c",
    name: "Solid ...d6 setup",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "exf4", "e5", "Ng8", "Nf3", "d6", "d4", "dxe5", "Qe2", "Be7", "Qxe5", "Nf6", "Bxf4"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Vienna Gambit: offer a pawn to gain time, open files, and attack before Black is settled.", "Black grabs the pawn. Your job is to get quick development and targets, not to win the pawn back slowly.", "Space grab with tempo: kick the f6 knight and try to make Black waste a move while you open the center.", "The knight retreats. That loss of time is the compensation you are playing for.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black plays solid: supports e5 and prepares ...dxe5 or ...Be7 while keeping the king safe.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black trades in the center to reduce your space and open lines before your attack is ready.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops calmly and aims to castle, trying to survive the opening phase without concessions.", "Take back in the center with tempo. You want material back, but still keep pieces active and threats alive.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "Capture with purpose: either win material back, remove a defender, or open a file for attack."]
  },

  {
    id: "vienna-counter-02-a9fd29f2",
    name: "Trap: queen takes rook on h1",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "fxe5", "Nxc3", "bxc3", "Qh4+", "g3", "Qe4+", "Qe2", "Qxh1"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black grabs your knight to damage your structure and reduce your piece pressure.", "Recapture and accept the structure damage. Your compensation is open lines and faster development.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend.", "Block the check, but note the cost: g3 weakens dark squares and can become a long-term target.", "Another check to keep you tied up. Black wants you spending moves on defense, not development.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Trap payoff: Black takes the rook. If you allow this, you must have immediate compensation or the game is basically over."]
  },

  {
    id: "vienna-counter-03-ee3fd007",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qd3", "dxe4", "Qxe4", "Bf5", "Qxb7", "Rb8", "Qxa7", "Nxc2+", "Kd1", "Nxa1"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the knight to d4 to contest the center and meet your threats.", "Develop the queen to d3 so it can influence the center and join the attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to f5 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the rook to b8 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Fork check: Black looks to win material while forcing your king to move.", "Step away from checks and keep your rooks connected later. You are trading safety for time.", "Black converts the fork into a rook win, usually deciding the game if you cannot generate an attack."]
  },

  {
    id: "vienna-counter-04-41e75f7c",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qe2", "Qh4+", "g3", "Qe4", "Nf3", "Qxf3", "Qxf3", "Bxf3"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the bishop to e6 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to d5 to contest the center and meet your threats.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend.", "Block the check, but note the cost: g3 weakens dark squares and can become a long-term target.", "Black develops the queen to e4 to contest the center and meet your threats.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-05-4f60a1b9",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "Bc4", "Nc6", "Qh5", "g6", "Qe2", "Nd4", "Qxe4", "Bf5", "Qxb7", "Rb8", "Qxa7", "Nxc2+"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Develop the bishop to c4 so it can influence the center and join the attack.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop the queen to h5 so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops the knight to d4 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to f5 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the rook to b8 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Fork check: Black looks to win material while forcing your king to move."]
  },

  {
    id: "vienna-counter-06-9759c095",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "Qe2", "Bf5", "g4", "Qh4+", "Kd1", "Bxg4", "Nf3", "Bxf3", "Qxf3", "exf3"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Black develops the bishop to f5 to contest the center and meet your threats.", "Make a pawn move that supports your center or opens lines for your pieces.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend.", "Step away from checks and keep your rooks connected later. You are trading safety for time.", "Black captures to simplify or to remove your attacking pieces.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-07-1fc8397e",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qd1", "dxe4", "c3", "Nc6", "Bb5", "Qd5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the knight to d4 to contest the center and meet your threats.", "Develop the queen to d1 so it can influence the center and join the attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Make a pawn move that supports your center or opens lines for your pieces.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the queen to d5 to contest the center and meet your threats."]
  },

  {
    id: "vienna-counter-08-123e2a7c",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nf3", "Bc5", "d4", "Bb4", "Bd2", "c5", "Nxe4", "dxe4", "Bxb4", "cxb4", "Ng1", "O-O"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to c5 to contest the center and meet your threats.", "You push d4 to challenge the center and open diagonals, but you must watch tactics on e4.", "Black pins the knight to slow your development and increase pressure on e4 and d4.", "Develop the bishop to d2 so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Develop the knight to g1 so it can influence the center and join the attack.", "Black castles to get out of the center and try to convert defense into counterplay."]
  },

  {
    id: "vienna-counter-09-866df47b",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qg4", "h5", "Qg3", "Qd7", "Nf3", "a6", "Bxc6", "Qxc6"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the bishop to e6 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to d5 to contest the center and meet your threats.", "Develop the queen to g4 so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Develop the queen to g3 so it can influence the center and join the attack.", "Black develops the queen to d7 to contest the center and meet your threats.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black advances a pawn to challenge your center or create counterplay.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-10-ebf6ccfc",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nxe4", "dxe4", "d4", "exd3", "Bxd3", "Qh4+", "g3", "Qe7", "Nf3", "Nc6"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "You push d4 to challenge the center and open diagonals, but you must watch tactics on e4.", "Black captures to open files against your king and keep the initiative with tempo threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend.", "Block the check, but note the cost: g3 weakens dark squares and can become a long-term target.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on c7.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns."]
  },

  {
    id: "vienna-counter-11-a8f21662",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Bb5", "Be6", "Nxe4", "dxe4", "Qxe4", "Bd5", "Qg4", "h5", "Qe2", "Qh4+"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop with purpose: Bb5 adds pressure and often forces Black to spend time unpinning or defending.", "Black develops the bishop to e6 to contest the center and meet your threats.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the bishop to d5 to contest the center and meet your threats.", "Develop the queen to g4 so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Queen supports e4 and eyes e5. In Vienna lines, Qe2 often helps you regain the pawn while staying active.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend."]
  },

  {
    id: "vienna-counter-12-5110a782",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Qf3", "Nc6", "Nxe4", "Nd4", "Qc3", "dxe4", "Ne2", "Nc6", "Ng3", "Qd5", "Bc4", "Qxe5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Qf3 pressures f4 and f7 ideas, and also keeps your recaptures in the center coordinated.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops the knight to d4 to contest the center and meet your threats.", "Develop the queen to c3 so it can influence the center and join the attack.", "Black takes in the center to convert the initiative into material and force your pieces to spend time recapturing.", "Re-route the knight to g3 or f4 squares and support central defense, often preparing to recapture cleanly.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop the knight to g3 so it can influence the center and join the attack.", "Black develops the queen to d5 to contest the center and meet your threats.", "Develop the bishop to c4 so it can influence the center and join the attack.", "Black captures to simplify or to remove your attacking pieces."]
  },

  {
    id: "vienna-counter-13-773a7e2b",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "fxe5", "Nxc3", "bxc3", "Qh4+", "Ke2", "Bg4+", "Nf3", "Nc6", "d4", "O-O-O", "Qe1", "Qh5"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black grabs your knight to damage your structure and reduce your piece pressure.", "Recapture and accept the structure damage. Your compensation is open lines and faster development.", "Direct check: force weaknesses like g3 and try to slow your attack by making you defend.", "Emergency king move. If you go here, you must play for activity because castling is no longer simple.", "Check with tempo. Black tries to keep your king exposed so your extra development does not matter.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black castles long to keep the king safe and bring the rook to the center quickly for counterplay.", "Develop the queen to e1 so it can influence the center and join the attack.", "Aggressive queen placement: Black looks for quick threats while your king is still in the middle."]
  },

  {
    id: "vienna-counter-14-92d886ae",
    name: "Check with Bb5+",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nf3", "Bc5", "d4", "Bb4", "Bd2", "c5", "Bb5+", "Nc6", "O-O", "O-O"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Tactical grab: Black takes e4 and challenges your center. If you are careless, your queen can get hit with tempo.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to c5 to contest the center and meet your threats.", "You push d4 to challenge the center and open diagonals, but you must watch tactics on e4.", "Black pins the knight to slow your development and increase pressure on e4 and d4.", "Develop the bishop to d2 so it can influence the center and join the attack.", "Black advances a pawn to challenge your center or create counterplay.", "Play with check to gain tempo and force a defensive move, keeping your initiative alive.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Castle to turn your development lead into real threats without your king getting checked forever.", "Black castles to get out of the center and try to convert defense into counterplay."]
  },

  {
    id: "vienna-counter-15-ac4fe7a3",
    name: "Central strike ...d5",
    description: "Coach style: explains the point of each move and the main tactical ideas.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "Nxd5", "Qxd5", "fxe5", "Nc6", "Nf3", "Bg4", "Be2", "Nxe5", "Nxe5", "Qxe5", "d4", "Qe7"],
    explanations: ["Take the center and keep lines open so your pieces can jump out fast.", "Black matches your central claim and keeps everything flexible.", " support e4 and keep the f-pawn free for f4 without blocking Nf3.", "Black develops while hitting e4, forcing you to show how you will defend the center.", "You still play f4 to chase initiative, but note Black can answer with ...d5 to hit your center immediately.", "Key counter: ...d5 hits e4 and f4 at once and tries to blunt your initiative by opening the center on Black's terms.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black centralizes the queen after trades and tries to simplify while holding the extra pawn or initiative.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black develops and adds pressure on e5 and d4, aiming to meet your center with pieces, not just pawns.", "Develop and prepare to castle. In gambits, king safety matters because open lines cut both ways.", "Black develops the bishop to g4 to contest the center and meet your threats.", "Develop the bishop to e2 so it can influence the center and join the attack.", "Black captures to simplify or to remove your attacking pieces.", "Capture with purpose: either win material back, remove a defender, or open a file for attack.", "Black captures to simplify or to remove your attacking pieces.", "Open the center while you are ahead in development. This is how gambits convert time into attack.", "Black stabilizes with the queen, defending key points and trying to prevent tactical forks on c7."]
  }

]);
